### ISSUE TITLE
Stop using appstream-glib to validate appstream files

### ISSUE THREAD

**Issue by tsdgeos** [flathub/flathub#1000]
It does some totally arbitrary checks like
     style-invalid : has vertical padding [http://kde.org/images/screenshots/katomic.png]

**Comment by barthalion** [comment]
We have relaxed some of the checks already: https://github.com/flathub/org.freedesktop.appstream-glib/blob/master/0001-Relax-validation-requirements-a-bit.patch

**Comment by tsdgeos** [comment]
Unfortunately that doesn't seem to help
   https://flathub.org/builds/#/builders/19/builds/406

katomic built fine in flathub before, i would really appreciate if it still could be built.

**Comment by barthalion** [comment]
I'm going to disable padding checks as well. OARS and releases are going to stay though.

**Comment by tsdgeos** [comment]
That's unfortunate.

Is there any mailing list of similar where we can be informed of such changes happening?

Not being able to update to x.y.0 to x.y.1 because suddenly the flathub requirements have changed really isn't good for our users that now can't have updated versions of our software.

**Comment by barthalion** [comment]
We always required these two tags for apps which were shipping their appdata with flatpak manifest, it just wasn't convenient to do with these shipped with the code. I agree it's not perfect that the change wasn't communicated properly, we will try to sort it out somehow in the future.

**Comment by tsdgeos** [comment]
yes please having this kind of "this was good last month but it isn't anymore" situations appearing out of nowhere are very demotivational.

I guess i'll close this, hopefully at some point in the future we'll able to update the kde applications.

**Comment by bilelmoussaoui** [comment]
@barthalion Can we also get the screenshots validation less verbose? 
```
builddir/files/share/appdata/com.github.alecaddd.sequeler.appdata.xml: FAILED:
• attribute-invalid     : <screenshot> height too large [https://raw.githubusercontent.com/Alecaddd/sequeler/master/data/assets/screenshots/sequeler-screenshot.png] maximum is 900px
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/Alecaddd/sequeler/master/data/assets/screenshots/sequeler-screenshot.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/Alecaddd/sequeler/master/data/assets/screenshots/sequeler-screenshot.png]
• attribute-invalid     : <screenshot> width too large [https://raw.githubusercontent.com/Alecaddd/sequeler/master/data/assets/screenshots/sequeler-screenshot1.png] maximum is 1600px
• attribute-invalid     : <screenshot> height too large [https://raw.githubusercontent.com/Alecaddd/sequeler/master/data/assets/screenshots/sequeler-screenshot1.png] maximum is 900px
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/Alecaddd/sequeler/master/data/assets/screenshots/sequeler-screenshot1.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/Alecaddd/sequeler/master/data/assets/screenshots/sequeler-screenshot1.png]
• attribute-invalid     : <screenshot> width too large [https://raw.githubusercontent.com/Alecaddd/sequeler/master/data/assets/screenshots/sequeler-screenshot2.png] maximum is 1600px
• attribute-invalid     : <screenshot> height too large [https://raw.githubusercontent.com/Alecaddd/sequeler/master/data/assets/screenshots/sequeler-screenshot2.png] maximum is 900px
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/Alecaddd/sequeler/master/data/assets/screenshots/sequeler-screenshot2.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/Alecaddd/sequeler/master/data/assets/screenshots/sequeler-screenshot2.png]
• attribute-invalid     : <screenshot> width too large [https://raw.githubusercontent.com/Alecaddd/sequeler/master/data/assets/screenshots/sequeler-screenshot3.png] maximum is 1600px
• attribute-invalid     : <screenshot> height too large [https://raw.githubusercontent.com/Alecaddd/sequeler/master/data/assets/screenshots/sequeler-screenshot3.png] maximum is 900px
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/Alecaddd/sequeler/master/data/assets/screenshots/sequeler-screenshot3.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/Alecaddd/sequeler/master/data/assets/screenshots/sequeler-screenshot3.png]
Validation of files failed
```
I can't seem to update few apps because of the changes.

**Comment by barthalion** [comment]
Can you upload appdata file somewhere?

**Comment by bilelmoussaoui** [comment]
@barthalion It's the appdata file of Sequeler which can be found here https://github.com/Alecaddd/sequeler/blob/master/data/com.github.alecaddd.sequeler.appdata.xml.in.in

**Comment by barthalion** [comment]
It validates fine with current version of org.freedesktop.appstream-glib used in buildbot.

**Comment by bilelmoussaoui** [comment]
Thanks, will trigger a new build.
