### ISSUE TITLE
Nvidia 430.14 New long live branch

### ISSUE THREAD

**Issue by chui2ch** [flathub/flathub#1001]
Nvidia has released the 430.14 driver and it is the newest long live branch driver. I just got the update on Ubuntu, but it does not appear that it has been packaged for flatpak. https://devtalk.nvidia.com/default/topic/1051837/announcements-and-news/linux-solaris-and-freebsd-driver-430-14-long-lived-branch-release-/

**Comment by TingPing** [comment]
Wrong repo but fixed by https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/commit/998ca94c6247b2608b787a740e91b1b8c1cdd6ad

**Comment by chui2ch** [comment]
@TingPing Sorry I posted in the wrong repo. Thanks for the link!
