### ISSUE TITLE
Documentation regarding the Appstream requirements is outdated

### ISSUE THREAD

**Issue by scx** [flathub/flathub#1006]
The documentation says:
https://github.com/flathub/flathub/wiki/App-Requirements#Appstream 
> Appstream is the standard used to provide metadata about applications. Applications must provide appstream data and:
> * pass appstream-util `validate-relax` (bonus points for `validate` or `validate-strict`).

However, it seems to me that now AppData needs to pass `validate`, not just `validate-relax`, like it was in the past.
https://flathub.org/builds/#/builders/32/builds/3634
https://flathub.org/builds/api/v2/logs/171317/raw

I'm not sure if this is a good idea. This may require rewriting descriptions because it defines their acceptable length and content.

See also:
https://github.com/flathub/flathub/issues/383#issuecomment-387843193

**Comment by barthalion** [comment]
Updated documentation to mention Flathub's "fork" of appstream-glib and which command to use.

**Comment by scx** [comment]
In my opinion this validation is too strict, because it literally defines how a description should look. It will fail so many times for trivial reasons, like caption is too short, caption is too long, caption should start with a capital letter (even if the first word is a stylized program name like `dconf Editor`, `gImageReader`, `mtPaint`, `uGet`, `wxHexEditor`, `wxMaxima`, etc.), description cannot contain a hyperlink, etc.
```
• style-invalid         : <caption> is too short [Main view];shortest allowed is 10 chars
```
```
• style-invalid         : <caption> is too short [Task view];shortest allowed is 10 chars
```
```
• style-invalid         : <caption> is too short [Edit mode];shortest allowed is 10 chars
```
```
• style-invalid         : <caption> is too long [wxMaxima provides wizards for the most important functions of Maxima];longest allowed is 50 chars
```
```
• style-invalid         : <caption> requires sentence case [xterm with its popup menus superimposed]
```
```
• style-invalid         : <li> cannot contain a hyperlink [CMake is now our main build system: It is supported under MSVC, XCode, Code::Blocks, its output looks much nicer than the one from the autotools and setting it up uses much more straightforward constructs. The recipe to build a debian package using cmake can be found at https://code.launchpad.net/~peterpall/wxmaxima/packaging]
```
This actually may require a lot of editorial work on the vendor side. I'm not sure if they'll be happy about it.

**Comment by scx** [comment]
See also:
https://github.com/flathub/org.freedesktop.appstream-glib/issues/1
https://github.com/flathub/org.freedesktop.appstream-glib/pull/2
