### ISSUE TITLE
Proper retirement of i386 version of com.valvesoftware.Steam

### ISSUE THREAD

**Issue by nanonyme** [flathub/flathub#1012]
Only x86_64 variant is getting built. The i386 version was dropped possibly around a year ago and I think was never migrated to 18.08 runtime. It would be nice if that could be marked eol so end-users would know they're installing the wrong thing if they try to install it.

**Comment by nanonyme** [comment]
Ping @barthalion

**Comment by barthalion** [comment]
As discussed on IRC, I couldn't find it in `flatpak remote-ls flathub --arch i386` or `ostree refs` on server so I guess it was removed in the past.
