### ISSUE TITLE
Please delete "Ring" old package from flathub !

### ISSUE THREAD

**Issue by Nokia808** [flathub/flathub#1014]
Hi.
There is now 2 packages for Jami (formally Ring) in flayhub:

1) 1st one called "Ring" which is unmaintained:
https://github.com/flathub/cx.ring.Ring

2) 2nd called "Jami" which is recently added.

Please delete "Ring" because it confusing users. Why we have 2 packages for same project ?

**Comment by TingPing** [comment]
I marked it EOL (https://github.com/flathub/cx.ring.Ring/commit/cf38bccd21ea468a591fb557f7de2de47194086c) but it fails to build. Will have to workaround...

**Comment by barthalion** [comment]
Marked EOL manually.
