### ISSUE TITLE
Screenshots appear in wrong order

### ISSUE THREAD

**Issue by create3000** [flathub/flathub#1017]
I have four screenshots specified in the appdata.xml:

https://github.com/flathub/de.create3000.titania/blob/135a4ce52933bf2ddae73fc864fe56eb0019fd50/de.create3000.titania.appdata.xml#L55-L72

but on the Flathub website they appear in wrong order 2,3,4,1. Also the default attribute does not work.

**Comment by TingPing** [comment]
https://github.com/flathub/linux-store-frontend/issues/80
