### ISSUE TITLE
cant install battle.net app

### ISSUE THREAD

**Issue by fishxz** [flathub/flathub#1021]
if i try to install battle.net launcher, the installation starts for 2 seconds and just quits... leaves me with a not installed battle.net launcher.

tried both:
https://lutris.net/games/battlenet/
https://lutris.net/games/world-of-warcraft/

also lutris tells me there is no wine installed on my system, im sure it didnt said that before.

**Comment by barthalion** [comment]
Lutris hasn't been even merged yet. If you have a problem, post it under its pull request.

**Comment by fishxz** [comment]
i got told to open an issue...
