### ISSUE TITLE
Add Adwaita Dark theme

### ISSUE THREAD

**Issue by memeplex** [flathub/flathub#1023]
This seems like a gross omission to me, there are now a lot of themes as flatpaks but the official Adwaita-dark is missing. Flatpak apps use Adwaita when the system theme is Adwaita-dark.

**Comment by memeplex** [comment]
See discussions supporting adding Adwaita-dark here:

* In flatpak https://github.com/flatpak/flatpak/issues/2937 they suggested adding support in the freedesktop runtime.

* In freedesktop runtime https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/801 they said: it's already there but since there is no simple way to set the variant (let alone pick it up from the sandbox) a workaround would be to add Adwaita-dark to flathub the same than other alternative themes.

* In https://gitlab.gnome.org/GNOME/gnome-tweaks/issues/220 I requested an improvement to this confusing situation.

**Comment by TingPing** [comment]
Added https://github.com/flathub/org.gtk.Gtk3theme.Adwaita-dark
