### ISSUE TITLE
Failure to update Freedesktop Platform on Fedora 30 !

### ISSUE THREAD

**Issue by Nokia808** [flathub/flathub#1025]
Hi. I'm on Fedora 30 X 64 bit Cinnamon edition & already installed GNOME software center on my system. FlatHub is already installed & enabled on my system & I can install & remove & update application without problem till this day.

Today my software center show me 2 updates available: InVesaluis & "Freedesktop Platform". I updated InVesalius without any problem. But when I tried to update "Freedesktop Platform" it stocked at Zero & no any progression ! I waited 1/2 hr without any progression ! So, I cancel updating & restart my PC & tried again but for 3/4 hr & same result !

Internet net speed of download now between 900 kb/sec - 1 mb/sec !

Please your care about this problem ! I feel that the problem is from your servers side ......

Best.

**Comment by Nokia808** [comment]
By the way, my GNOME software center show 2 "Freedesktop Platform" & what happened to any of them happened to other as being identical twins ! See attached screenshot bellow. 

![freedesktop-platform](https://user-images.githubusercontent.com/25375330/58859148-ae5d1e80-8698-11e9-952b-a64be670d28b.png)

Is this normal or it is a bug ? And if it is a bug then is it on your side or on GNOME software center ? Please inform me if being a bug not on your side, so as to file a bug to GNOME .....

I'm, already, run:

sudo dnf repoquery --duplicated

& output was nothing (this mean no duplicated packages on my system.

**Comment by barthalion** [comment]
Both sound like issue with Fedora, not our infrastructure. Please bring it there.

**Comment by Nokia808** [comment]
@barthalion 
Hi again ! I opened 2 bugs on RedHat bugzilla but no response till now. 
Today I tried again but same error.
1) Just an idea: can I try to remove "Freedesktop Platform" from my system using GNOME software center then install it again using GNOME software center ? I asked this question because I'm very afraid that if I do this then "Freedesktop Platform" will not appear to me from within GNOME software center ! I noticed that some (in fact many) packages have no metadata for GNOME software center so that it do not displayed in this center unless after being installed. If user remove them then they are not displayed in center ! If this occur with "Freedesktop Platform" after I remove it, then this mean that I will be unable to install them again & this will make all my flatpaks not working ...... 
2) other thing: I noticed today that there is other package installed on my system related to flatpak which is "KDE Application Platform Version Master". But I have currently no KDE application installed on my system from flathub. Previously I was installed Okular then I remove it. 
So, is this package existence on my system normal ? Sorry for asking this question here but I did not like to bother this site by opening new issue about this question ....

**Comment by barthalion** [comment]
Could you run `flatpak list` in the terminal and paste the output here? It will be easier to help.

**Comment by Nokia808** [comment]
@barthalion 
Thank you very much for your kind help !

This is the output:

```
$ flatpak list
Description                                                              Application                     Version    Branch Arch   Origin  Installation
InVesalius - 3D medical imaging reconstruction software                  br.gov.cti.invesalius           3.1.99993  stable x86_64 flathub system
ScanTailor Advanced - Interactive post-processing tool for scanned pages …hub._4lex4.ScanTailor-Advanced v1.0.16    stable x86_64 flathub system
PDF Slicer - A simple tool to extract, rotate and reorder pages of a PD… com.github.junrrein.PDFSlicer   1.6.3      stable x86_64 flathub system
AstroMenace - Hardcore 3D space scroll-shooter with spaceship upgrade p… com.viewizard.AstroMenace       1.4.1      stable x86_64 flathub system
TORCS - The Open Racing Car Simulator                                    net.sourceforge.torcs           1.3.7      stable x86_64 flathub system
SuperTuxKart - A 3D arcade racer with a variety of characters, tracks, … net.supertuxkart.SuperTuxKart              stable x86_64 flathub system
Freedesktop.org Application Platform version 1.6 - Shared libraries pro… org.freedesktop.Platform        1.6        1.6    x86_64 flathub system
Freedesktop Platform - Shared libraries                                  org.freedesktop.Platform        18.08.31.1 18.08  x86_64 flathub system
Intel VAAPI Driver - Intel driver for hardware accelerated video decodi… …eedesktop.Platform.VAAPI.Intel            1.6    x86_64 flathub system
Intel                                                                    …eedesktop.Platform.VAAPI.Intel            18.08  x86_64 flathub system
FFmpeg extension - Add support for aac, mpeg4 and h264                   org.freedesktop.Platform.ffmpeg            1.6    x86_64 flathub system
html5-codecs                                                             …edesktop.Platform.html5-codecs            18.08  x86_64 flathub system
GNOME Application Platform version 3.28 - Shared libraries used by GNOM… org.gnome.Platform                         3.28   x86_64 flathub system
GNOME Application Platform version 3.30 - Shared libraries used by GNOM… org.gnome.Platform                         3.30   x86_64 flathub system
GNOME Application Platform version 3.32 - Shared libraries used by GNOM… org.gnome.Platform                         3.32   x86_64 flathub system
Mint-Y-Dark Gtk Theme - Mint-Y-Dark theme                                org.gtk.Gtk3theme.Mint-Y-Dark              3.22   x86_64 flathub system
Adwaita theme - Adwaita widget theme matching the GNOME adwaita theme    org.kde.KStyle.Adwaita                     5.12   x86_64 flathub system
KDE Application Platform version master - Shared libraries used by KDE … org.kde.Platform                           5.11   x86_64 flathub system
KDE Application Platform - Shared libraries used by KDE applications     org.kde.Platform                           5.12   x86_64 flathub system
Xonotic - Multiplayer, deathmatch oriented first person shooter          org.xonotic.Xonotic             0.8.2      stable x86_64 flathub system
i2pd - Invisible Internet                                                website.i2pd.i2pd               2.25.0     stable x86_64 flathub system
OpenArena - Free and open source first-person shooter                    ws.openarena.OpenArena          0.8.8      stable x86_64 flathub system

```

**Comment by barthalion** [comment]
You see Freedesktop twice in G-S because you have two versions installed; one of KDE platforms is called "master" but it's in fact 5.12 as seen in the third column, my guess is that KDE team just forgot to change it when it was released.

**Comment by Nokia808** [comment]
1) So, what I have to do ? Is this the cause of failure of update ? How can I solve problem of failure to update ?

2) Also, is there a duplicated packages on my system ? I mean I see for example 3 "GNOME Application Platform" (3.28, 3.30, 3.32) is this normal ? I mean when new version come, then should the old version(s) removed or I'm wrong ? Do I have to remove version 3.28 & 3.30 ? Or flatpak has different approach from .rpm system ?

**Comment by barthalion** [comment]
1. Have you tried `flatpak update` from terminal?
2. Yes, it's normal. Various app can target different versions of the same runtime. If `flatpak uninstall --unused` doesn't remove them, then they're required.

**Comment by Nokia808** [comment]
Issue had been solved since yesterday - see bellow link (my user name in Fedora community forum is User808):

https://forums.fedoraforum.org/showthread.php?321643-Failure-to-update-quot-Freedesktop-Platform-quot-of-flathub-flatpak

I run update from terminal after repair flatpak by command line ....

**Comment by AsciiWolf** [comment]
Hmm, this may be the same issue as [this one](https://gitlab.gnome.org/GNOME/gnome-software/issues/684).

**Comment by alexxtasi** [comment]
Hi all
it's been a long time since the last post... but I came to this problem now and write here although I am in another platform.

I am running `Solus 4.1 Fortitude` with `Linux 5.6.19-159` kernel and `GNOME Shell 3.38.1`.
Found the same issue from another Solus user and it's forum suggested it's not Solus's problem.

I run the commands @Nokia808 suggested with no success:
- updated my system and reboot just in case
- `sudo flatpak repair --system`
- `flatpak repair --user`
- `flatpak update`

but those _end-of-life_ messages are still there:
```
$ flatpak update 
Looking for updates…
Info: org.gnome.Platform is end-of-life, with reason: The GNOME 3.34 runtime is no longer supported as of 14th August 2020. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform is end-of-life, with reason: The GNOME 3.28 runtime is no longer supported and does not receive security updates. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform.Locale is end-of-life, with reason: The GNOME 3.34 runtime is no longer supported as of 14th August 2020. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform.Locale is end-of-life, with reason: The GNOME 3.28 runtime is no longer supported and does not receive security updates. Please ask your application developer to migrate to a supported platform.
Info: org.freedesktop.Platform.ffmpeg is end-of-life, with reason: The Freedesktop 1.6 runtime is no longer supported and does not receive security updates. Please ask your application developer to migrate to a supported runtime.
Info: org.freedesktop.Platform.VAAPI.Intel is end-of-life, with reason: The Freedesktop 1.6 runtime is no longer supported and does not receive security updates. Please ask your application developer to migrate to a supported runtime.
Nothing to do.
```
Until running @barthalion suggestion:
`flatpak uninstall --unused`

I cannot figure out if it's gnome's problem or not... just stating my experience :)
regards
