### ISSUE TITLE
typo on buildbot

### ISSUE THREAD

**Issue by nedrichards** [flathub/flathub#1042]
Inspired by #968 I noticed that there's a typo in the page title on buildbot. It says 'flahub' rather than 'flathub'. I can't find that string anywhere in the project so I assume it's inferred by something.

![Screenshot from 2019-06-15 19-55-56](https://user-images.githubusercontent.com/302677/59555303-1fa9a500-8fa8-11e9-8f76-764205631bf2.png)

**Comment by barthalion** [comment]
LITERALLY UNUSABLE

Just kidding, I'll fix it tomorrow.

**Comment by AsciiWolf** [comment]
Seems to be fixed. :)
