### ISSUE TITLE
Installing Minecraft issues :C

### ISSUE THREAD

**Issue by camdenorrb** [flathub/flathub#1049]
```
camdenorrb@hostname ~ $ flatpak install flathub com.mojang.Minecraft
Installing in system:
com.mojang.Minecraft/x86_64/stable flathub ac1cdb1d3d27
  permissions: ipc, network, pulseaudio, x11, dri
  tags: proprietary
Is this ok [y/n]: y
Installing: com.mojang.Minecraft/x86_64/stable from flathub
[######################] Downloading files: 1/1 67.0 MB (11.2 MB/s)          
error: Failed to install com.mojang.Minecraft/x86_64/stable: Wrong size for extra data https://launcher.mojang.com/download/Minecraft.tar.gz
```

(On Solus)

**Comment by camdenorrb** [comment]
I made a PR https://github.com/flathub/com.mojang.Minecraft/pull/8

**Comment by cdplayer** [comment]
**This still happens:**

$ flatpak install flathub com.mojang.Minecraft
Looking for matches…

com.mojang.Minecraft permissions:
    ipc          network     pulseaudio     x11     dri
    tags [1]

    [1] proprietary


        ID                     Arch      Branch   Remote   Download
 1. [✗] com.mojang.Minecraft   aarch64   stable   flathub  67.5 MB / 129.0 MB

Error: Wrong size for extra data https://launcher.mojang.com/download/Minecraft.tar.gz
error: Failed to install com.mojang.Minecraft: Wrong size for extra data https://launcher.mojang.com/download/Minecraft.tar.gz
