### ISSUE TITLE
VAAPI Error with org.kde.Platform

### ISSUE THREAD

**Issue by FastOSlinux** [flathub/flathub#1059]
https://github.com/flathub/com.obsproject.Studio/issues/33

after this does not work (I have to downgrade to this version)

 ID: org.kde.Platform
      Ref: runtime/org.kde.Platform/x86_64/5.12
     Arq.: x86_64
     Ramo: 5.12
  Licença: GPL-2.0+
  Coleção: org.flathub.Stable

VAAPI. Works OK with OBS Studio

Commit: 101871e091000616ad2b635e06c414eb0e1c4e1c34292a205c5239935ee5ea44
  Assunto: Update to Qt 5.12.3 (02adbdb1)
     Data: 2019-04-18 18:32:43 +0000

**Comment by TingPing** [comment]
Driver issues would be reported here: https://gitlab.com/freedesktop-sdk/freedesktop-sdk
