### ISSUE TITLE
Pop Gtk Theme for gnome 3.24 and beyond 

### ISSUE THREAD

**Issue by aditiapratama** [flathub/flathub#106]
I've installed pop gtk theme and it seems the theme is outdated
`org.gtk.Gtk3theme.Pop/x86_64/3.22`
Is there any plan to update it?

**Comment by TingPing** [comment]
The Gtk theme API was largely stabilized on 3.22 so a 3.22 theme can work on 3.24. As such there is no benefit for us to package it twice.

**Comment by aditiapratama** [comment]
@TingPing why my flatpak apps doesn't use Pop gtk theme then? is there any workaround?

**Comment by TingPing** [comment]
What application?

**Comment by aditiapratama** [comment]
corebird and polari

**Comment by TingPing** [comment]
Works as expected here:
![screenshot from 2017-09-22 03-31-06](https://user-images.githubusercontent.com/798838/30733808-93a1750e-9f46-11e7-92ab-7ace219ab064.png)

Are you using the same theme on the host?

**Comment by aditiapratama** [comment]
I'm using light variant

**Comment by aditiapratama** [comment]
ah I see, it seems pop gtk theme from flathub doesn't respect the variant from main theme

**Comment by TingPing** [comment]
Yea, Pop has 6 variants which is a PITA to package them all. I will add the light variant really quick though.

**Comment by aditiapratama** [comment]
@TingPing ah thank you, please add light and compact one :+1:

**Comment by TingPing** [comment]
Here is light: https://github.com/flathub/org.gtk.Gtk3theme.Pop-light

I'll have to automate the other 4 variants some other day.

**Comment by aditiapratama** [comment]
@TingPing yeay, thanks a lot

**Comment by loxK** [comment]
Ping. 
I am using POP-compact.

Thanks in advance.

**Comment by TingPing** [comment]
Honestly I really want the Pop folks to maintain these.
