### ISSUE TITLE
Create repositories for Mint-Y theme variants

### ISSUE THREAD

**Issue by TingPing** [flathub/flathub#1061]
Mint has a lot of theme variants that need to have repos, this is just a tracker to remember getting it done:

- [x] Mint-Y
- [ ] Mint-Y-Aqua
- [ ] Mint-Y-Blue
- [ ] Mint-Y-Brown
- [ ] Mint-Y-Grey
- [ ] Mint-Y-Orange
- [ ] Mint-Y-Pink
- [ ] Mint-Y-Purple
- [ ] Mint-Y-Red
- [ ] Mint-Y-Sand
- [ ] Mint-Y-Teal
- [x] Mint-Y-Dark
- [ ] Mint-Y-Dark-Aqua
- [ ] Mint-Y-Dark-Blue
- [ ] Mint-Y-Dark-Brown
- [ ] Mint-Y-Dark-Grey
- [ ] Mint-Y-Dark-Orange
- [ ] Mint-Y-Dark-Pink
- [ ] Mint-Y-Dark-Purple
- [ ] Mint-Y-Dark-Red
- [ ] Mint-Y-Dark-Sand
- [ ] Mint-Y-Dark-Teal
- [x] Mint-Y-Darker
- [ ] Mint-Y-Darker-Aqua
- [ ] Mint-Y-Darker-Blue
- [ ] Mint-Y-Darker-Brown
- [ ] Mint-Y-Darker-Grey
- [ ] Mint-Y-Darker-Orange
- [ ] Mint-Y-Darker-Pink
- [ ] Mint-Y-Darker-Purple
- [ ] Mint-Y-Darker-Red
- [ ] Mint-Y-Darker-Sand
- [ ] Mint-Y-Darker-Teal

(And add clefebvre as committer)

**Comment by barthalion** [comment]
All repositories were created and added @clefebvre as collaborator.

**Comment by clefebvre** [comment]
@barthalion @TingPing many thanks for this!
