### ISSUE TITLE
Server returned HTTP 502

### ISSUE THREAD

**Issue by cmurf** [flathub/flathub#1064]
Fedora 30 is complaining of error 502's with flathub, whereas I can't (yet) reproduce this on Fedora Rawhide. So the error makes me suspicious of a server side problem, but the fact I can't reproduce it with Fedora Rawhide which has a newer libcurl makes me wonder if it's a local problem.

Anyway this happened at 'Jul 09 02:51:42' UTC if you have any logs on your end that can confirm or deny a server side problem that might be useful.

Fedora bug is here:
https://bugzilla.redhat.com/show_bug.cgi?id=1728093

**Comment by barthalion** [comment]
This was bug in Fedora.
