### ISSUE TITLE
How to fix pk-gtk-module ?

### ISSUE THREAD

**Issue by liberodark** [flathub/flathub#1069]
Hi have build a flatpak app but not run have this error on Centos 7.6 x64

https://github.com/flathub/flathub/pull/1067

```
flatpak run com.termius.termius
Gtk-Message: 15:16:24.661: Failed to load module "pk-gtk-module"
Gtk-Message: 15:16:24.664: Failed to load module "pk-gtk-module"

```

Best Regards

**Comment by TingPing** [comment]
That isn't an error, it is a warning that can safely be ignored. So lets just keep the discussion of the app not working in #1067
