### ISSUE TITLE
 Publishing builds: FAILURE

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/flathub#1080]
https://flathub.org/builds/#/builders/32/builds/5729
```
Publishing build https://hub.flathub.org/api/v1/build/5505
Api call to https://hub.flathub.org/api/v1/build/5505/publish failed with status 400, details: {'current-state': 'unpublished', 'error-type': 'wrong-published-state', 'expected-state': 'published', 'message': 'Build has already been published', 'status': 400}
```

**Comment by bilelmoussaoui** [comment]
This was reproduced 4 days ago again
https://flathub.org/builds/#/builders/29/builds/6932

**Comment by gjanssens** [comment]
I see the same error when pushing a new GnuCash release:
https://flathub.org/builds/#/builders/29/builds/7386

**Comment by gjanssens** [comment]
@bilelmoussaoui Thanks. I had found that page.

However these publishing failures seem to happen consistently on the gnucash builds. I see this in all previous builds as well since I'm involved in the gnucash flathub package.

**Comment by gjanssens** [comment]
@bilelmoussaoui Same publishing error on your restarted build...
https://flathub.org/builds/#/builders/29/builds/7406

**Comment by gjanssens** [comment]
It seems my issue actually was a wrong component type in the appdata file :(
For org.gnucash.GnuCash this was flathub/org.gnucash.GnuCash#29 and now resolved.
