### ISSUE TITLE
More JetBrains IDEs

### ISSUE THREAD

**Issue by BjoernDaase** [flathub/flathub#1090]
I would love to see more JetBrains IDEs packaged as Flatpaks because it's the way better  package management software than Snap.

Especially, I would like to see:
- [ ] Rubymine
- [ ] CLion (looks like that has already been tried https://github.com/flathub/flathub/pull/537, but maybe we could give it another try)
- [ ] Pycharm Professional (there is already a MR for it https://github.com/flathub/flathub/pull/1087)
- [ ] PhpStorm

If somebody could give me a link to some kind of instructions how to add them, I would love to participate.

**Comment by bilelmoussaoui** [comment]
flathub/flathub issues are not about app requests. If you want to help package any of these apps, just take a look at what's done by other Jetbrains products here on Flathub https://github.com/flathub?utf8=%E2%9C%93&q=jetbrains.
