### ISSUE TITLE
Runtime compaibility question

### ISSUE THREAD

**Issue by caspermeijn** [flathub/flathub#1099]
I don't if this is the correct place to ask. If it's not please point me to a better place.

A user reported a problem with the [ONVIFViewer](https://flathub.org/apps/details/net.meijn.onvifviewer) flatpak ([original bug report](https://gitlab.com/caspermeijn/onvifviewer/issues/45)), which made me think. The flatpak was last build [two months ago](https://flathub.org/builds/#/apps/net.meijn.onvifviewer). Does that mean that it uses the runtime from that time or will it use the most recent runtime? If the most recent, how does it know that the application is still compatible?

Also I would like to know the difference between my amd64 laptop and a raspberry pi. If I test the application on my laptop, can I assume it just works on a raspberry pi?

**Comment by barthalion** [comment]
> Does that mean that it uses the runtime from that time or will it use the most recent runtime?

Runtimes are separate and that's main advantage of flatpak that some base set of libraries is shared and updated independently.

>  If the most recent, how does it know that the application is still compatible?

Runtime maintainers promise to keep API and ABI stable. If application stops working suddenly, it's serious oversight and needs to be addressed by runtime team.

> Also I would like to know the difference between my amd64 laptop and a raspberry pi. If I test the application on my laptop, can I assume it just works on a raspberry pi?

Usually yes, but things like GPU support differ, also between distributions. Unfortunately ARM isn't very universal environment.

**Comment by caspermeijn** [comment]
Thanks, I understand now!
