### ISSUE TITLE
Thunderbird from FlatHub does not appearing in my GNOME software centre !

### ISSUE THREAD

**Issue by Nokia808** [flathub/flathub#1108]
Hi. I noticed - since long time - that Thunderbird from FlatHub does not appearing in my GNOME software centre ! Only Thunderbird .rpm package from "fedoraproject.org" & Thunderbird flatpak from "registry.fedoraproject.org" are currently appearing !

I tried to delete PackageKit cache, but same result !

It does not appearing in search engine of this site also:
https://www.flathub.org/home

Could you please investigate this issue.

**Comment by barthalion** [comment]
Thunderbird is marked end-of-life because it lacks a maintainer. It was recently updated though and is still installable via CLI `flatpak install flathub org.mozilla.Thunderbird`.
