### ISSUE TITLE
No system to protect Flatpak from non-mentained packages in FlatHub ?!!

### ISSUE THREAD

**Issue by Nokia808** [flathub/flathub#1109]
Hi. I noticed that there are some outdated packages with no update or even already deprecated ! But they are still existing in FlatHub !

For example:

1) Mist: please take look for their repository on GitHub:
https://github.com/ethereum/mist
They announce officially that Mist is already DEPRECATED !
So, is it safe for FlatHub to have already deprecated applications within it ??

2) Jami:
https://github.com/flathub/net.jami.Jami
The package is already out of date & not including new feature. Moreover it was launched on Fedora 28 BUT FAILED COMPLETELY to make any communication ! But now I completely NOT LAUNCHED AT ALL at Fedora 30 !
I open issues but developer did not respond unless: I have no time to work on this package !! - see:
https://github.com/flathub/net.jami.Jami/issues/4
&
https://github.com/flathub/net.jami.Jami/issues/6

Not only on Fedora it failed ! But also on openSUSE - see:
https://github.com/flathub/net.jami.Jami/issues/7

Again, no any response ! If packager have no time to work on his package(s) then why submit them for FlatHub ??!!

I would like to ask here: is their a system or rules govern the packagers in FlatHub to insure that they maintain the packages that they obligate themselves by themselves to maintain them ? There should be a system to detect discontinuations of packagers from mantain their packages so as to remove such package from FlatHub if there are no other maintainers available to maintain them ! This is the case in Fedora/Debian/openSUSE ..... official package repositories systems & FlatHub should behave similarly, otherwise it will finally will end by failure ......   

Outdated, non-functioning  or already deprecated packages are great security risks ! Such packages must purged as quick as possible, preferably by automatic system of monitoring & follow up .....

**Comment by TingPing** [comment]
> If packager have no time to work on his package(s) then why submit them for FlatHub ??!!

In general humans have unpredictable lives =)

> They announce officially that Mist is already DEPRECATED !

I have marked this package end-of-life:

https://github.com/flathub/org.ethereum.Mist/commit/937bd1974ef4e46c1d345032daec1ef6a9b947bb

**Comment by TingPing** [comment]
> This is the case in Fedora/Debian/openSUSE ..... official package repositories systems

The situation in Fedora (I can't speak for the others) is identical to this issue. As long as everything builds nobody cares. When something fails they poke the maintainer, if the maintainer doesn't respond then action is taken.

**Comment by Eonfge** [comment]
@TingPing Not sure if this is the right place to report it, but I have a few more packages who might be unmaintained:
* https://github.com/flathub/io.github.Freedoom-Phase-1
* https://github.com/flathub/io.github.Freedoom-Phase-2
* https://github.com/flathub/net.mancubus.SLADE

_There might be a few others as well, like FreeDM and Blade of Agony, but I have not confirmed those._

These packages are all maintained by https://github.com/Alexander-Wilms but he has not been on Github since the beginning of June. For these three packages, I have outstanding pull requests that deal with bugs and outdated versions.

Could it be possible to document a workflow for situations like these?

**Comment by bilelmoussaoui** [comment]
@Eonfge Just ping one of the maintainers & we will take care of merging any PR.

**Comment by bilelmoussaoui** [comment]
I don't think we can do anything more anyway.
