### ISSUE TITLE
VLC does not play files placed out of my home

### ISSUE THREAD

**Issue by glaubersm** [flathub/flathub#111]
Hi 
I installed VLC flatpak on kde plasma 5 (neon distro), I cant play files from my ntfs partition.
If I select "play with VLC" from my file manager context menu, VLC shows an error message, freezes and causes high cpu usage (50% of i3 3110M cpu).
Can you solve this problem please? Thanks.

**Comment by TingPing** [comment]
`flatpak override --filesystem=host org.videolan.VLC` will grant complete access. Now VLC freezing is their bug.

**Comment by glaubersm** [comment]
Thank you TingPing, your command worked.
But flatpak VLC should play any file "out of the box".

**Comment by TingPing** [comment]
Opening files from your file manager should always work, not sure what happened there.

**Comment by glaubersm** [comment]
your command is not working anymore on Arch Linux.
