### ISSUE TITLE
[Question] Can we limit access of flatpak application to certain user account only ?

### ISSUE THREAD

**Issue by Nokia808** [flathub/flathub#1121]
Hi. There is a method to make system package (.deb or .rpm) to be accessed ONLY by single or certain user account(s) as following:

> example for firefox:
> Here is a quick way to do it with firefox as an example:
>     1. Create a group webusers 
>     2. change the rights of the firefox binary to 750 (root:rwx, webusers:r-x) and the ownership to root:webusers 
>     3. add all users who should be allowed to use firefox to the group webusers 
> You can, of course, create groups for all individual programs. Here are the commands for doing it.
> sudo addgroup webusers
> sudo chown root:webusers /usr/bin/firefox
> sudo chmod 750 /usr/bin/firefox
> sudo adduser alice webusers
> sudo adduser bob webusers

I would like to know is this possible for flatpak applications ? If yes, then which is the command used to locate flatpak binaries ? I mean we use: which command to locate binaries for standard packages like Firefox, so:
$ which firefox
it yeld the following:
/usr/bin/firefox

**Comment by TingPing** [comment]
Just install it with `--user`?

I'm not entirely sure why you want this.

**Comment by Nokia808** [comment]
@TingPing 
I'm targeting WineHQ (Phoenicis or Lutiris).
I'm currently using WineHQ as .rpm package from official Fedora repositories in this way:
- created special group called "riskywork"
- created special user called "wineuser"
- make this user without sude, without su,
- install WineHQ from official Fedora repositories
- change rights & ownership of installed Wine to be used only by "wineuser" as discribed in my 1st post
- add "wineuser" to "riskywork" group
- make "riskywork" group unable to access polkit at all

The problem with above approach is that - inspite of being fully secure - it cost me 423 MB download size EACH TIME I make system upgrade to next Fedora release. Taking in mind that I'm living in Iraq, where bad Internet speed & bad electricity with long & unpredictable period of cut, I'm currently at risk of cut at middle of upgrading process making me (if happened) with unbootable system ..... For that I prefer to remove WineHQ that I installed from official Fedora repositories & replace it by Wine from as flatpak package & limit it's use to be used only by "wineuser".

So, can you give me complete command for Phoecitics ? Where I should put "--user" in the following:
`flatpak install flathub org.phoenicis.playonlinux`
at it's end ?

**Comment by LeandroStanger** [comment]
**Command:**
>flatpak install --user flathub org.phoenicis.playonlinux

**Comment by Nokia808** [comment]
@LeandroStanger 
Dear I have 2 accounts on my system: "Nokia808" (in wheel group with root power) & "wineuser" (no sudo, no su, no polkit powers)

Do you mean that I have to login 1st to "wineuser" account then run the command:
flatpak install --user flathub org.phoenicis.playonlinux
If yes, then I would like to know how flatpak can be used by account like "wineuser" which has no any root power ? Is flatpak install application without root power ? What is method that flatpak using to elevate itself to root privilege level ? I know only polkit to make user level applications to get function as if they root level while they are in fact merely user level application !

**Comment by barthalion** [comment]
`--user` means that installation is user-only, not system wide. It doesn't need to assume root or elevate permissions in any way.

**Comment by Nokia808** [comment]
@barthalion 
This is extremely useful & make things very very simple ! It make creation of new group (riskywork) unnecessary at all ! 

All what we need is that:
1) create new user account:
sudo useradd -m -d /windows/data -s /bin/bash wineuser
sudo passwd wineuser
rebbot
2) disable wineuser from ability to use sudo & su:
- sudo already disabled by default on Fedora for any newly created user account which by default out of wheel group
- disable any newly added user account from utilizing su by:
sudo vi /etc/pam.d/su then uncomment the following line:
#auth required	pam_wheel.so use_uid then save & exit by :wq
reboot
3) make "wineuser" not able to use polkit. On Cinnamon DE by:
sudo setfacl -m u:wineuser:--- /usr/libexec/polkit-gnome-authentication-agent-1
4) login to "wineuser" account, then install WineHQ application:
flatpak install --user flathub org.phoenicis.playonlinux

Unfortunately pure WineHQ not available on FlatHub & will never be, because WineHQ is command line program .......

I see the following PR on FlatHub:
https://github.com/flathub/flathub/pull/1060
does this could be used alone as pure WineHQ or it is only to be used via Lutris ?

**Comment by Nokia808** [comment]
@barthalion 
Dear just single question: does flatpak package that installed by "--user" flag, does such package will be able to touch any thing (read ? write ?) outside of home directory of user account that used to install it by "--user" flag or not ?

**Comment by TingPing** [comment]
@Nokia808 	It runs as your user, so it can do only what your user can do.
