### ISSUE TITLE
screenshot: doesn't respect type=default marker

### ISSUE THREAD

**Issue by gdesmott** [flathub/flathub#1131]
My appdata file contains two screenshots, one marked as `default`: https://gitlab.freedesktop.org/gdesmott/karapulse/blob/0.1.0/data/org.karapulse.Karapulse.appdata.xml.in.in#L16

But the flathub page shows the other one by default, see https://flathub.org/apps/details/org.karapulse.Karapulse

**Comment by AsciiWolf** [comment]
Yeah, it's reversed for some reason. :)

**Comment by bilelmoussaoui** [comment]
Duplicate of https://github.com/flathub/linux-store-frontend/issues/80
