### ISSUE TITLE
In 32-bit flatpak open/save file dialogs don't work in Qt/KDE applications

### ISSUE THREAD

**Issue by denismn** [flathub/flathub#1134]
Don't work in Kdenlive, VLC, Telegram.
Works in Audacity.

I checked on Xubuntu 16.04, Debian 10 and openSUSE Tumbleweed i686.
In Xubuntu 16.04 Flatpak from PPA, in other cases from distribution repositories.
Doesn't work means doesn't appear.

**Comment by TingPing** [comment]
This is likely something you'll need to report against Qt.

**Comment by bilelmoussaoui** [comment]
Not a Flathub issue.
