### ISSUE TITLE
[Question] About flatpak package that installed with "--user" flag

### ISSUE THREAD

**Issue by Nokia808** [flathub/flathub#1136]
Hi. I would like to know: does flatpak package that installed with "--user" flag , does such package limited (due to using --user flag) to be NOT able to touch any thing outside home directory of user account that used to install it or not ?

I mean if I have 2 accounts: Nokia808 & John & I used John to install a flatpak application with --user flag. Then does this flatpak will not be able to touch any thing outside home directory of user John , or it still able to touch something outside home directory of John ?

Best.

**Comment by bilelmoussaoui** [comment]
I think this actually answers your question https://github.com/flathub/flathub/issues/1121#issuecomment-526272703.
