### ISSUE TITLE
Ship GLU with Steam flatpak

### ISSUE THREAD

**Issue by ChrootDoot** [flathub/flathub#114]
There are currently some games which require LibGLU, however, GLU is not packaged with the Freedesktop runtime, nor the Steam runtime

**Comment by alexlarsson** [comment]
libGLU is ancient crap and has no place in a minimal runtime. If some apps need it we should add it to the steam app.

**Comment by ChrootDoot** [comment]
That's what I meant, sorry for the miscommunication.

Also I wasn't sure if there were maintainers for individual applications, but it sounds like I could make a pull request and push this change myself.

**Comment by TingPing** [comment]
Each app has its own bug tracker: https://github.com/flathub/com.valvesoftware.Steam

**Comment by ChrootDoot** [comment]
Okay, thank you, I will discuss this there
