### ISSUE TITLE
How to set category?

### ISSUE THREAD

**Issue by linuxhw** [flathub/flathub#1143]
Hello,

How to setup category for the app? I want to put https://flathub.org/apps/details/org.linux_hardware.hw-probe in `Developer Tools` or `Utilities` category.

Thanks.

**Comment by TingPing** [comment]
The `Categories` entry in the desktop file: https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html

**Comment by linuxhw** [comment]
This has fixed the issue.

Thank you.
