### ISSUE TITLE
raspberry pi ldconfig failed

### ISSUE THREAD

**Issue by caspermeijn** [flathub/flathub#1150]
In an effort to debug a [user reported problem](https://gitlab.com/caspermeijn/onvifviewer/issues/45), I installed [ONVIFViewer flatpak](https://flathub.org/apps/details/net.meijn.onvifviewer) on a Raspberry Pi running raspbian. When trying to run the application, I get the following error:

> $ flatpak run net.meijn.onvifviewer
> Note that the directories
>
> '/var/lib/flatpak/exports/share'
> '/home/pi/.local/share/flatpak/exports/share'
>
>are not in the search path set by the XDG_DATA_DIRS environment variable, so applications installed by Flatpak may not appear on your desktop until the session is restarted
>
>error: ldconfig failed, exit status 35584

This seems similar to [this stackoverflow question](https://raspberrypi.stackexchange.com/questions/101356/error-35584-when-trying-to-run-minetest-with-flatpak).

**Comment by TingPing** [comment]
Flatpak bugs are reported here: https://github.com/flatpak/flatpak
