### ISSUE TITLE
build-arm: url-not-found: <screenshot> failed to connect: Cannot resolve hostname [https://github.com/...png]

### ISSUE THREAD

**Issue by linuxhw** [flathub/flathub#1151]
Hi,

The build on arm is failed due to failure:

> url-not-found         : <screenshot> failed to connect: Cannot resolve hostname [https://github.com/linuxhw/build-stuff/releases/download/1.4/image-2.png]

Build URL: https://flathub.org/builds/#/builders/57/builds/597

Builds on other platforms are OK.

**Comment by TingPing** [comment]
I imagine it was a temporary network issue, did you try retriggering it?

**Comment by linuxhw** [comment]
Yes, retriggering the build fixed the issue.

Thanks.
