### ISSUE TITLE
Buildbot exception: JSON manifest is NoneType

### ISSUE THREAD

**Issue by 404NetworkError** [flathub/flathub#1152]
The NVIDIA repo was recently updated and triggered a [build](https://flathub.org/builds/#/builders/32/builds/7644) on Flathub's buildbot setup which resulted in the following exception: `builtins.TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'`. Sometime between releases v2.3.0.flathub7 (the last successful [build](https://flathub.org/builds/#/builders/32/builds/7193)) and v2.3.0.flathub9 (current release) of Buildbot, the manifest loading mechanism was updated. I'm not exactly sure what needs to be changed in the NVIDIA repo so that the manifest gets loaded properly. Any help would be appreciated.

**Comment by barthalion** [comment]
Fixed, sorry for the trouble.

https://flathub.org/builds/#/builders/32/builds/7651

**Comment by 404NetworkError** [comment]
Thank you very much.
