### ISSUE TITLE
Id heritage on Flathub

### ISSUE THREAD

**Issue by Eonfge** [flathub/flathub#1160]
I've had the ambitious idea to ensure that all of Id Software's GPL powered engines are available on Flathub. This will make it a lot easier to play these games, and it will certainly add nicely to the growth of Flathub. Doing this alone is quite a challenge, and not so much fun, so if you read this topic and you like the thought of contributing to Flathub, then drop a line in the comments about which one you would like to take up.

**Update 0**
Some Id Tech games are already available, added them to the index for posterity.

**Update 1**
GZDoom and Zandronum are done. Zandronum does have some release trouble with the build-server (#1170) but that should not impact the process overall.

**Update 2**
Lot of work already completed for ezQuake, Some work put into ET:Legacy but there are some technical issues there.

**Update 3**
ezQuake and Yamagi Quake are up for review. ET:Legacy will likely require some upstream help. iortcw is going well though.

**Update 4**
I removed all products that are now supported. Of cause, there are many competing source ports, so there can always be new packages, but I think it's best to focus one supporting all games with at least a single port first. We've done a lot of great work, and I think it's great to have products like Zandronum and ET:Legacy available, which offer one-click installations for active multiplayer games. Keep up the good work.

**Update 5**
I removed all products that are now supported. Added DSDA Doom which is one of the most popular speed-run versions right now. It also has a launcher which would be good to bundle.

---

### Wolfenstein 3D era
* [ ] EC Wolf (https://maniacsvault.net/ecwolf/)

### Doom  Era
* [ ] DSDA Doom (https://github.com/kraflab/dsda-doom)
  * [ ] DSDA Launcher (https://github.com/Pedro-Beirao/dsda-launcher)

### Id Tech 4
* [ ] The Dark Mod (Free game data) (https://www.thedarkmod.com/main/)

### Additional
Not really games, but closely related. These tools should be primarily focused on editing Id Tech content. Feel free to recommend other tools in the comments.
* [ ] NetRadiant (https://gitlab.com/xonotic/netradiant)

## Game Data
Not all game have free game data, so some thought must go into helping potential users in getting their commercial files in the right directory. There is currently an open discussion on this at #1155 so keep an eye out for updates.

**Comment by julianrichen** [comment]
It wasn't possible when I tried this before because of a bug with app extensions (which I believe is fixed now) but you could distribute the non-free game data as an extension point that downloads the file at install with extra-data. I was testing this with ET: Legacy.

So for example, you can distribute the game engine engine as GPL as `com.etlegacy.ETLegacy` and then extra-data the [non-free files](https://cdn.splashdamage.com/downloads/games/wet/et260b.x86_full.zip) from Splash Damage's website as `com.etlegacy.ETLegacy.Data` or similar.

I think I still have the flatpak manifest on my computer, I can try compiling it again when I get home tonight.

**Comment by Eonfge** [comment]
@julianrichen An app extension would not actually be required, it has been decided that non-libre items can be included using an 'extra-data' source. 

For ET:Legacy, it would be easy to include an extra-data source because this is almost literally what the currrent ET:Legacy does right now. Right now, their .sh script asks you to download the non-libre components, after which it puts them in the installation directory.

If you could look at the ET:L script you had, that would be a great start

**Comment by julianrichen** [comment]
@Eonfge Here are the manifests. I included the combined and split extra-data approach:

https://github.com/julianrichen/com.etlegacy.etl

Would probably be a good idea to upstream the appdata and small patch to the build script.

I was able to get into the game before but now it just launches a black window and closes, not sure why. It should at least get you started with ET: Legacy.

Besides licensing the biggest reason to split the game data into an extension is to make downloads easier. Every time you update the base app it requires you to re-download the extra-data. In ET: Legacy's case the assets from Splash Damage aren't going to change, they haven't in a decade. So you force the user to re-download 263 MB of data every time something is changed when the base is just 10 MB. As an extension, unless you change the extension or the checksum it wont re-download which is nice. But the approach would depend on how Flathub would like to handle it.

**Comment by Eonfge** [comment]
@julianrichen 
I've looked into it a bit. The game has a segmentation fault on booting, but I'm not really sure why yet.

```strace
mmap(NULL, 4198400, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f40844cf000
brk(0x5586fbcb5000)                     = 0x5586fbcb5000
mmap(NULL, 4198400, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f40840ce000
munmap(0x7f40840ce000, 4198400)         = 0
ioctl(39, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x4a, 0xc0), 0x7fff592c1e20) = 0
ioctl(39, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x57, 0x38), 0x7fff592c1cf0) = 0
stat("/home/kevin/.etlegacy/legacy/gameinfo.txt", 0x7fff592c2e30) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/kevin/.etlegacy/legacy/pak3_v2.76.pk3", O_RDONLY) = 59
fstat(59, {st_mode=S_IFREG|0664, st_size=7107688, ...}) = 0
fstat(59, {st_mode=S_IFREG|0664, st_size=7107688, ...}) = 0
lseek(59, 7106560, SEEK_SET)            = 7106560
read(59, "\0\r\0\0\0\0\0\0\0\0\0\264\201\330\277j\0weapons/mp40.we"..., 1128) = 1128
lseek(59, 7107688, SEEK_SET)            = 7107688
lseek(59, 7107688, SEEK_SET)            = 7107688
lseek(59, 7008256, SEEK_SET)            = 7008256
read(59, "\5\2371\354\260w\252v\t\177\26\34\320|\337\7\n\343\274v\361\274\24\310Z\0044\337\271`/\36"..., 4096) = 4096
lseek(59, 7012352, SEEK_SET)            = 7012352
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2940, ...}) = 0
lseek(59, 7012352, SEEK_SET)            = 7012352
read(59, "alic.ttfUT\5\0\7\220\3421\\ux\0\0PK\1\2\24\3\24\0\10\0\10"..., 4096) = 4096
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2940, ...}) = 0
lseek(59, 1249280, SEEK_SET)            = 1249280
read(59, "\245\336v,\303\205\275\257p\367\204\16\247\3228\\\217\343\371\336\210\375\377\177\3v\276[\315\224\276\325"..., 4096) = 4096
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2940, ...}) = 0
read(59, "info.txtUT\r\0\7\220\3421\\\237\211;\\\220\3421\\ux\v\0\1\4\350"..., 4096) = 4096
read(59, "\345OI\202\33h\22~\240\r8\273!Y\320a\266t\221\236\240\201\204\360z{?\25q\1\1\241"..., 28672) = 28672
read(59, "&\211\357=\366\266tm\261\266(\3009L,\37\243^\346\344\257K]\366\263\311\350)\325\330\374\225"..., 4096) = 4096
close(59)                               = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

Also, I made a simplified version of your script so it's easier to compare behaviour between the original package and the Flatpak package:

https://github.com/Eonfge/flathub/tree/com.etlegacy.ETL

There is much to be said for making the package more structured, but in practice most Id Software games play fast and loose with their libs and .pk3. Trying to be smarter then them, will bring a whole series of new incompatibility problems forward.

**Comment by fishxz** [comment]
have you considered q2pro? its a quake 2 client, focused for multiplayer.

**Comment by Eonfge** [comment]
@fishxz There is a problem with it though: It doesn't do any releases. That means that every 5 or so days, a new version comes out, based on the master of the project. To track this with Flathub, would be a very labour intensive job. Most of the projects currently listed have like one major release every year, which makes it manageable without to much upstream involvement. 

If @skullernet is willing to update through Flathub, then I'm willing to help a hand with making the manifest, but else it will be to much work for me at the moment.

**Comment by rafal1137** [comment]
@Eonfge Hi There I am about write about this issue posted on our tracker https://dev.etlegacy.com/issues/1351

So far my progress stopped at trying to run single-click-build.sh
I am getting error/errors

> Can't parse 'com.etlegacy.ETL.yaml': <data>:1:6: błąd przetwarzania: unexpected identifier `app-id', expected value

**Comment by julianrichen** [comment]
What's your `flatpak-builder` version? I'm guessing you have a version less than 0.10.10 which doesn't support YAML.

**Comment by rafal1137** [comment]
@julianrichen Yes you are correct 0.10.9 here

**Comment by Eonfge** [comment]
@rafal1137 & @julianrichen I got it working yesterday night!
https://dev.etlegacy.com/issues/1351

I asked the guys upstream and they told me that it's indeed crashing a lot on 64bit. They also told me that most people don't use 64bit because it's not mod-compatible, so for now, I compile it 32bit only.

Not sure if I can get it to work with 19.08 though. Perhaps one of you can give that a try.

**Comment by mattiasb** [comment]
I took a first stab at an `ioquake3` manifest [here](https://github.com/mattiasb/org.ioquake3.IOQuake3).

I need to add Appstream data, a `flathub.json` file and check that I don't leave around any crap after build (not sure how to check for that).

There's also the fact that ioquake3 doesn't seem to do releases. :/

**Comment by Eonfge** [comment]
@mattiasb Looking good!

For the appsteam data, you can do both. You can add the metainfo.xml to Flathub-pr repository and submit it like that. If you then also make an upstream pull request, that's perfectly in line with the current workflow. Ideally, all changes here on Flathub should be upstreamed, but we can function as a staging ground until the next release comes around.

For ET Legacy, I did the same. The original manifest they included had a few errors so I patched those using sed and then I made an upstream pull request to include those changes. Next release of ET Legacy should then fix those issues.

Original ETLegacy pulll request:
https://github.com/flathub/flathub/pull/2144

Current workaround:
https://github.com/flathub/com.etlegacy.ETLegacy/blob/40355f4ea7efadee7079b7ead8d4f5be7fc2c487/com.etlegacy.ETLegacy.yaml#L164

**Comment by Mailaender** [comment]
I tried to compile and run them but I had no luck so far:
* https://github.com/Mailaender/flathub/tree/q3rally
* https://github.com/Mailaender/flathub/tree/darkmod
* https://github.com/Mailaender/flathub/tree/reaction
* https://github.com/Mailaender/flathub/tree/smokinguns

**Comment by frogs-social** [comment]
Some winter 2023 updates!

> * [ ]  EC Wolf

Technically this is covered. [RetroArch](https://flathub.org/apps/org.libretro.RetroArch) has a [core](https://docs.libretro.com/library/ecwolf/).

> * [ ]  IOquake3

✓[ioquake3](https://flathub.org/apps/org.ioquake3.ioquake3)

> * [ ]  RBDoom3BFG

✓[RBDoom3BFG OpenGL](https://flathub.org/apps/io.github.RobertBeckebans.RBDoom3BFG-GL)

> * [ ]  DarkRadiant

✓[DarkRadiant](https://flathub.org/apps/net.darkradiant.DarkRadiant)

**Comment by bbhtt** [comment]
The repo here is for reporting issues, packaging requests should go to https://discourse.flathub.org/c/requests/5 but note that posting there doesn't guarantee it'll be added as everything is community based.

I'm closing this as it seems have run its course and a bunch of the games are packaged.

**Comment by Eonfge** [comment]
In my defence, discource.flathub.org did not exist when I started  this issue to track the packaging of Id related titles. Alas, most is done now
