### ISSUE TITLE
Installing Adobe Flash Plugin from flathub

### ISSUE THREAD

**Issue by Rei-Ayanami** [flathub/flathub#1167]
Hello dears. I am a really newbie in using flathub and flatpaks. I am using a Clear Linux and try to install a flash plugin from flathub, but while installing this software I am getting an error about extra data for this package is mismatched. There is a output of the package installation: 

http://dpaste.com/1YC8RTV.txt

How I can install this software from flathub? The manual installing of this package is a little bit strange for me...

Sorry if I wrote this post in wrong place, please provide me a link to community or other place where I can find some help about that problem. Thanx a lot.

**Comment by bilelmoussaoui** [comment]
The issue must be reported in the application repository. You can find that by clicking on 
![Screenshot from 2019-09-18 22-12-33](https://user-images.githubusercontent.com/7660997/65182372-728c7000-da61-11e9-80b4-b154f76da3c9.png)
from the application's page on Flathub. 

The app needs to be updated which is the cause of your issue.
