### ISSUE TITLE
Remove EOL applications from site

### ISSUE THREAD

**Issue by skierpage** [flathub/flathub#1168]
`flatpak update` reported
```
Info: io.github.Fontforge.Locale is end-of-life, with reason: This application has moved to a new appid. The new appid is org.fontforge.FontForge
Info: io.github.Fontforge is end-of-life, with reason: This application has moved to a new appid. The new appid is org.fontforge.FontForge
```
The ever-helpful TingPing commented on IRC "well the package maintainer can't remove entries from the site so an admin has to do it," hence this bug report.

_However_, the new FontForge URL doesn't show up in Google search or Flathub search (it does appear as one of two refs in `flatpak install FontForge`) and its page https://flathub.org/apps/details/org.fontforge.FontForge is blank. I think this is known issue https://github.com/flathub/org.fontforge.FontForge/issues/3 . Is it better to have no search results or only get the EOL flatpak (which dates from March 2019)? It may be fixed soon.

**Comment by bilelmoussaoui** [comment]
Same as 
- https://flathub.org/apps/details/org.gnome.iagno
- https://flathub.org/apps/details/org.gnome.quadrapassel
- https://flathub.org/apps/details/org.gnome.ghex
- https://flathub.org/apps/details/org.gnome.tetravex

**Comment by GabMus** [comment]
I'd add same as https://flathub.org/apps/details/org.gabmus.gnome-feeds

This version is EOL, still people can find it and install it instead of the current one. It needs to be removed or hidden from flathub.

**Comment by barthalion** [comment]
Fixed with https://github.com/flathub/linux-store-backend/commit/d5c3797656e1093a52311b87cda17c5b02487282 and https://github.com/flathub/ansible-playbook/commit/4a5f8170156aa5e6412ac97f42b198fe1e20e411.

**Comment by DontUseGithub** [comment]
isn't it better to just provide a warning instead of removing them completely? Some apps could still do their job well enough despite not being maintained anymore.
