### ISSUE TITLE
Adobe Flash installation from Flathub problem

### ISSUE THREAD

**Issue by Rei-Ayanami** [flathub/flathub#1169]
Hello dears. I am a really newbie in using flathub and flatpaks. I am using a Clear Linux and try to install a flash plugin from flathub, but while installing this software I am getting an error about extra data for this package is mismatched. There is a output of the package installation:

http://dpaste.com/1YC8RTV.txt

How I can install this software from flathub? The manual installing of this package is a little bit strange for me...

Sorry if I wrote this post in wrong place, please provide me a link to community or other place where I can find some help about that problem. Thanx a lot.

**Comment by LeandroStanger** [comment]
Report error here https://github.com/flathub/com.adobe.Flash-Player-Projector/issues
