### ISSUE TITLE
Difference in behaviour .flatpakref and local host

### ISSUE THREAD

**Issue by Eonfge** [flathub/flathub#1175]
I've found an issue during development which I can't fully unravel. While packaging ezQuake for Flathub (#1173), I discovered this and it would be nice to have your feedback on it.

### Setup
During development, I created multiple symlinks from the `~/.ezquake/` directory to the `/app/bin/`. The reasoning being, is that the user gets a copy of the base configuration which they can edit. Quake (from 1997) didn't account for home folders and all it's source ports have not picked up on that yet. This way, individual users can have their own config.

### what is happening
Now, when I build a repository locally, it works. The `persist=.ezquake` redirects the user config to the application, and it runs. But, when I download the .flathubref from the builder-bot, this link suddenly fails. I've tried it multiple times, and everything is the same: Exactly  the same manifest, same Flatpak permissions, same user directory.

### What gives
So, what is different between my own testing repository and the .flatpakref?

### How to reproduce
Branch can be found here: https://github.com/Eonfge/flathub/tree/io.github.ezQuake
Do mind that you need a copy of Quake to test the application running, shareware version found here: https://community.pcgamingwiki.com/files/file/411-quake-shareware-pak/

**Comment by barthalion** [comment]
See my comment here: https://github.com/flathub/flathub/pull/1173#discussion_r328499461
