### ISSUE TITLE
flatpak list --app-runtime doesn't filter by runtime arch/version

### ISSUE THREAD

**Issue by codingepaduli** [flathub/flathub#1176]
I'm tring to check all the apps using a specific runtime version. These are what I got when try
**flatpak list --app  --app-runtime=org.gnome.Platform/x86_64 --columns=application**

- com.transmissionbt.Transmission
- me.kozec.syncthingtk
- org.codeblocks.codeblocks
- org.gnome.Evince
- org.gnome.gedit
- org.gnome.meld
- org.remmina.Remmina

But when I want to know apps by two different runtime version, I got the following:
**flatpak list --app  --app-runtime=org.gnome.Platform/x86_64/3.32 --columns=application**

- com.transmissionbt.Transmission
- me.kozec.syncthingtk
- org.codeblocks.codeblocks
- org.gnome.Evince
- org.remmina.Remmina

**flatpak list --app  --app-runtime=org.gnome.Platform/x86_64/3.34 --columns=application**
- org.codeblocks.codeblocks
- org.gnome.gedit
- org.gnome.meld

**How can it be that codeblocks depends from both version 3.32 and 3.34?**

I checked for different version of the same app:
**flatpak list --app  --columns=application,version,branch,options,size,active,arch,latest,origin**
but I didn't find duplicated app.

I checked also errors by
**flatpak repair**
But no error was found

Is it a bug or a feature to improve?

**Comment by bilelmoussaoui** [comment]
CodeBlocks doesn't use 3.32 nor 3.34. It doesn't even use GNOME runtime. It's probably a bug on flatpak CLI side. Should be reported there instead.
