### ISSUE TITLE
Website not being updated with new apps

### ISSUE THREAD

**Issue by Eonfge** [flathub/flathub#1189]
Case in point;
https://flathub.org/apps/details/com.github.Flacon

It looks like all builds are successful, but for some reason it doesn't show up on the store. You can even install it using `flatpak install flathub com.github.Flacon` but something on the website gives way.

9001 should now be live: 
https://flathub.org/builds/#/apps/com.github.Flacon

**Comment by bilelmoussaoui** [comment]
Fixed here https://github.com/flathub/com.github.Flacon/commit/8d89b7b54208176d37d529b217d170ce898ef518.
