### ISSUE TITLE
Add Insomnia to Flatpak

### ISSUE THREAD

**Issue by doums** [flathub/flathub#1195]
Hi,

That would be great if some good people adds [Insomnia](https://insomnia.rest/) to Flatpak.
Unfortunately it has already been tried in the past with no success apparently -> https://github.com/flathub/flathub/pull/504

Can someone help on this ? On my side I don't know about the process on how to add a new app to Flatpak :(

**Comment by TingPing** [comment]
This is documented here: https://github.com/flathub/flathub/wiki/App-Submission
