### ISSUE TITLE
Random build failures during upload build step

### ISSUE THREAD

**Issue by mbooth101** [flathub/flathub#1198]
Four most recent examples:

* https://flathub.org/builds/#/builders/8/builds/1124/steps/14/logs/stdio
* https://flathub.org/builds/#/builders/54/builds/730/steps/14/logs/stdio
* https://flathub.org/builds/#/builders/39/builds/1138/steps/14/logs/stdio
* https://flathub.org/builds/#/builders/56/builds/735/steps/14/logs/stdio
* https://flathub.org/builds/#/builders/57/builds/717/steps/14/logs/stdio

I just keep hitting rebuild and hoping it will succeed, but it's pretty annoying because depending on which builder is picked it can take up to 2 hour to get to this stage before the failure happens :-(

It's not just my apps -- I observed this happen to another app that I do not maintain:

* https://flathub.org/builds/#/builders/8/builds/1120/steps/14/logs/stdio

**Comment by jakobjakobson13** [comment]
>     * https://flathub.org/builds/#/builders/8/builds/1120/steps/14/logs/stdio

Well, the last one is quite reproducible. ;)

**Comment by mbooth101** [comment]
I just observed the failure again:

* https://flathub.org/builds/#/builders/56/builds/782/steps/13/logs/stdio

**Comment by mbooth101** [comment]
Here's another:

  * https://flathub.org/builds/#/builders/42/builds/786/steps/13/logs/stdio

**Comment by barthalion** [comment]
cncf-x86-1 and cncf-x86-2 run modified flat-manager-client now which retries entire "push" function instead of only files upload.

**Comment by mbooth101** [comment]
Here's another occurrence: https://flathub.org/builds/#/builders/32/builds/11582

**Comment by barthalion** [comment]
@mbooth101 We've migrated to new hardware today. Curious to see if you trigger it again somehow.

**Comment by barthalion** [comment]
I assume you haven't!

**Comment by mbooth101** [comment]
Yeah I don't recall seeing it recently, thanks :-)
