### ISSUE TITLE
Spotify on elementary OS : missing album art, icons categories

### ISSUE THREAD

**Issue by 1LinuxGuy** [flathub/flathub#120]
I just intalled Spotify from Flathub on elementary OS Loki.

version 1.0.64.407.g9bd02c2d 

Here's how it looks. (From Flatpak, before, with an earlier version, I had no problems.)

![capture d ecran de 2017-10-04 01 35 20](https://user-images.githubusercontent.com/19640810/31161348-5836d998-a8a4-11e7-83ba-4c3258edbe6f.png)

![capture d ecran de 2017-10-04 01 26 55](https://user-images.githubusercontent.com/19640810/31161232-a8002110-a8a3-11e7-882f-10c5ef1ad77f.png)

**Comment by TingPing** [comment]
This issue is being tracked here: flathub/com.spotify.Client#8
