### ISSUE TITLE
No i386 org.kde.Sdk and org.kde.Platform version 5.13, but only x86_64

### ISSUE THREAD

**Issue by ThanosApostolou** [flathub/flathub#1201]
I'm new to building flatpaks and I am currently building some in my own repo in order to use them across my PCs (I plan to submit some of those to flathub when I have enough experience). I have both 64 and 32 bits machines so I need to build for both of those architectures according to the official instructions. I noticed that there isn't any platform and Sdk for org.kde version 5.13. Is i386 being deprecated? Or is it a bug which I need to report? I don't find the repositories where flathub runtimes are built that's why I ask here.

**Comment by barthalion** [comment]
FreeDesktop SDK 19.08 has deprecated i386, thus GNOME SDK 3.24 and KDE 5.13 also doesn't have it. KDE SDK/Platform 5.12 is said to be LTS, but FDO 18.08 (which 5.12 builds upon) will be supported for one more year.

**Comment by ThanosApostolou** [comment]
Thx for the info. This is sad, I still have many i386 PCs and flatpak seems the best way to maintain software for all of these (especially now that most distros are deprecating it leaving me with the outdated debian as my only option).

Since flatpak flexibility allows it, is there (or will be in the future) any guide/tutorial/instructions to show me how to build these runtimes for i386 in my custom repo even after they've been deprecated completely? I find several instructions about apps but I cannot find anything about runtimes. Can you give me any directions (maybe starting with the github repos from which these runtimes are built because I cannot find them)?

**Comment by barthalion** [comment]
The grim reality is that it's getting less and less popular so it's often hard to justify additional maintenance workload.

KDE runtime is built using flatpak-builder: https://github.com/KDE/flatpak-kde-runtime
FDO SDK uses buildstream, you will find more documentation following README: https://gitlab.com/freedesktop-sdk/freedesktop-sdk

**Comment by ThanosApostolou** [comment]
Sorry to bother you again but one last question. When FDO 18.08 is deprecated will it be available in flathub (if yes for how long) or will it be completely removed? I see FDO 1.6 hasn't been removed but I don't know about future plans. If it is to be removed maybe it will be worth it for me to create full bundled standalone flatpaks before that (because the procedure for building and using the runtimes myself seems difficult).

**Comment by barthalion** [comment]
We never removed anything from Flathub. I think it's safe to assume it won't happen. Deprecated runtimes are marked as end-of-life but it only causes various flatpak "clients" to hide them, it doesn't mean it was deleted.

**Comment by ThanosApostolou** [comment]
Aaaa nice! That's actually really good!! Thx a lot for explaining!
