### ISSUE TITLE
Remote "flathub" not found

### ISSUE THREAD

**Issue by mahmoodn** [flathub/flathub#1204]
I want to install two packages according to [this](https://github.com/FreeRDP/FreeRDP/wiki/Compilation) freerdp guide, but I get "flathub" not found error.

```
# flatpak install flathub org.freedesktop.Platform//18.08
error: Remote "flathub" not found
# flatpak install flathub org.freedesktop.Sdk//18.08
error: Remote "flathub" not found
```

What is wrong with flathub then?

**Comment by barthalion** [comment]
Your guide links to [Flathub setup page](https://flatpak.org/setup/) you also need to follow. Some distributions configure it by default but not all.

**Comment by mahmoodn** [comment]
I read the document at https://flatpak.org/setup/Red%20Hat%20Enterprise%20Linux/
What do that means installing a repo?
For example, epel repository has an RPM file and it is straight-forward. 

```
[root@hpc yum.repos.d]# yum install flatpak
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.centos.jt.iq
 * centosplus: mirror.centos.jt.iq
 * extras: mirror.centos.jt.iq
 * updates: mirror.centos.jt.iq
Package flatpak-1.0.2-7.el7.x86_64 already installed and latest version
Nothing to do
[root@hpc yum.repos.d]# wget https://flathub.org/repo/flathub.flatpakrepo
--2019-10-10 16:42:40--  https://flathub.org/repo/flathub.flatpakrepo
Resolving flathub.org (flathub.org)... 93.93.128.161, 93.93.130.103, 2a00:1098:82:e::1, ...
Connecting to flathub.org (flathub.org)|93.93.128.161|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4040 (3.9K) [application/octet-stream]
Saving to: ‘flathub.flatpakrepo’

100%[==============================================>] 4,040       --.-K/s   in 0s

2019-10-10 16:42:41 (322 MB/s) - ‘flathub.flatpakrepo’ saved [4040/4040]

```

**Comment by TingPing** [comment]
You should be able to just open that file in your file manager.

Otherwise `flatpak remote-add flathub https://flathub.org/repo/flathub.flatpakrepo`

**Comment by EliRoberts5** [comment]
that really helped solve the install problem on arm64, however I  also logged out and back in..
