### ISSUE TITLE
Inconsistent program names

### ISSUE THREAD

**Issue by fbruetting** [flathub/flathub#1209]
When you list all available packages via `flatpak remote-ls`, you see that (at least for the GNOME programs) there is no consistent naming scheme for the package names. Wouldn’t it make sense to unify that, so that either all GNOME applications are preceded by “GNOME”, or leaving “GNOME” out completely for all GNOME applications?

Otherwise, wouldn’t it make sense to introduce an “organization” value to the application’s metadata, which then would separate the application name from the organization’s name?

![Bildschirmfoto von 2019-10-12 17-59-03](https://user-images.githubusercontent.com/10520767/66707081-ae9eb200-ed3b-11e9-94a3-f1a588da45bb.png)

**Comment by TingPing** [comment]
I believe this is purely a discussion to have with GNOME and start some initiative over there. We are not going to start patching names here and for the most part I don't think we want to nit-pick upstream chosen names.

**Comment by bilelmoussaoui** [comment]
That's something you should discuss with GNOME instead of Flathub. Nothing we can do from our side

**Comment by beedell-roke** [comment]
@fbruetting, do you intend to mention this to GNOME?
