### ISSUE TITLE
Development build docs

### ISSUE THREAD

**Issue by fchiacchiaretta** [flathub/flathub#121]
Hi,
would it be possible to have some docs on how to locally build and test an app based on a flathub git repo?
I'm trying to test a fix on com.spotify.Client, but struggling creating a test build.

Regards,
Federico Chiacchiaretta

**Comment by AsavarTzeth** [comment]
Do you mean something like http://docs.flatpak.org/en/latest/flatpak-builder.html?

**Comment by fchiacchiaretta** [comment]
Thanks, I was stuck with flatpak build-init and flatpak build, didn't know about flatpak-builder.
