### ISSUE TITLE
Appstream's video tag support

### ISSUE THREAD

**Issue by Rampoina** [flathub/flathub#1215]
Appstream supports linking a video through the video tag in the screenshots section.
Implemented here: https://github.com/ximion/appstream/issues/175
And documented here: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

I added a video tag in https://github.com/flathub/com.locomalito.abbayedesmorts but it seems that the build bot is removing it.

I suggest:
- Making it so that the build bot doesn't remove the tag so that other applications using flathub's repo can use it.
- Implementing a video feature in the flathub website

**Comment by TingPing** [comment]
The buildbot problem is probably an `appstream-glib` problem.

The website issue should be discussed over at https://github.com/flathub/linux-store-frontend

**Comment by Rampoina** [comment]
Sure, I've opened a new issue in https://github.com/flathub/linux-store-frontend
