### ISSUE TITLE
"y" working with "flatpak update" ! Is this okay ?

### ISSUE THREAD

**Issue by Nokia808** [flathub/flathub#1219]
Hi. On run:
flatpak update
if there is update available, then terminal ask us to press "Y" to update flatpak packages.
 
Today, I did mistake because I forgot to use CapsLock key before press Y so that in fact I press "y" instead "Y". But it worked & flatpak update respond to "y" exactly as it was done with "Y".

Just I like to insure about safety of this. Is it okay to use "y" instead of "Y" ?

**Comment by pizzadude** [comment]
The capital letter just means it's the preferred answer, so when you press enter it will default to Y (yes).

**Comment by bilelmoussaoui** [comment]
Please open your flatpak related questions on the right repository.
