### ISSUE TITLE
Gtk theme is not used unless I set the variable GTK_THEME

### ISSUE THREAD

**Issue by ThanosApostolou** [flathub/flathub#1225]
I am on Kubuntu 19.10 and even though I've set many themes (breeze, materia, yaru) as my gtk theme (with the equivalent org.gtk.Gtk3theme.THEME installed) the gtk apps are using the Adwaita theme. For example I set my gtk theme as "Breeze" and I check to see that it is correctly set by kde systemsettings at the files **~/.gtkrc-2.0**, **~/.config/gtk-3.0/settings.ini** and the dconf path **/org/gnome/desktop/interface/gtk-theme**. Here are the screenshots:

```
flatpak run org.gnome.clocks
```
![Screenshot_20191028_014101](https://user-images.githubusercontent.com/21288843/67643807-105a4100-f924-11e9-9139-1d6389aa633f.png)

```
GTK_THEME=Breeze flatpak run org.gnome.clocks
```
![Screenshot_20191028_014204](https://user-images.githubusercontent.com/21288843/67643826-3c75c200-f924-11e9-928a-a8892f9b7439.png)

Is this a flatpak bug, a flathub theme bug, or a KDE bug in which case I should do a bug report there and ask them to export GTK_THEME environmental variable by default?

**Comment by TingPing** [comment]
On X11 you need an XSettings service running. Nothing else matters.

**Comment by ThanosApostolou** [comment]
Aaaa you are right, indeed this happens only on X session in KDE. Installing and configuring xsettingsd fixes this. So, I'm closing this. Thx for the reply!
