### ISSUE TITLE
Audacity cant read music files

### ISSUE THREAD

**Issue by joergister** [flathub/flathub#125]
Audacity cant read music files. Neither mp3 nor opus. I always get the suggestion that I should install FFMPEG (which i have installed on my system). That does not seem to be included in the Flatpak.

Also every time  start the audacity Flatpak I first get these errors. 
[list_of_errors.txt](https://github.com/flathub/flathub/files/1366410/list_of_errors.txt)

As someone outstanding I have the question: what about a multimedia runtime that include FFMPEG and GSTREAMER and all the codecs?
Perhaps it would make things easier and a lot of Flatpaks less big in their size.

Keep up the good work. I really like the idea of putting every application into a flatpak that can then be installed on every linux distribution. 
Thanks a lot

**Comment by TingPing** [comment]
It builds `ffmpeg` with these codecs: https://github.com/flathub/org.audacityteam.Audacity/blob/master/org.audacityteam.Audacity.json#L52-L86

Perhaps you are trying to play music with a different one?

**Comment by TingPing** [comment]
Your errors seem related to Alsa and Pulseaudio not codecs.

**Comment by joergister** [comment]
Tried it again. 
You are right. Every codec seems to work fine except mp3 and opus. 

When I tried to import mp3 files a message appeared that told me that audacity was build without the support for mp3 files. That was something I understood.

Than I got confused: cause when I tried to import an opus file, a message appeared that told me I should install ffmpeg. 

After this is wrote the issue.
Now I tried to export music to files and that works pretty well. Well, seems like ffmpeg is available and works well. Only the message that appears when i try to import an opus file does not make sense to me.

Fuck, sorry, should have tested better.

**Comment by joergister** [comment]
At least, is there a special reason for why you didn't include mp3, libid3tag and opus into your flatpak build? 
I thought about using the flatpak instead of the audacity build provided by my distribution but I need audacity to be able to handle these two codecs.

**Comment by TingPing** [comment]
Probably no reason, should be easy to enable them.

**Comment by TingPing** [comment]
@joergister I enabled some extra mp3 and opus features, it will take a bit for it to build and get updated but let me know once it updates if that solved it.

(https://flathub.org/builds/#/buildrequests/3185)

**Comment by joergister** [comment]
I will, but it seems like there is no new build available yet. 
thanks a lot so far.

**Comment by TingPing** [comment]
Ugh seems like there is a problem with the builders, check again tomorrow maybe.

**Comment by joergister** [comment]
seems like something went wrong with the build since I didn't get an update. 
I don't want to get on your nerves but only wanted to give feedback in case you didn't notice for some reason.

**Comment by TingPing** [comment]
Sorry bout that: https://flathub.org/builds/#/builders/1/builds/656

**Comment by joergister** [comment]
No problem but thanks a lot. 
importing mp3 files woks now even though it is marked as disabled which is kinda funny I think
![screenshot_20171020_163808](https://user-images.githubusercontent.com/24881413/31826417-46e2bf72-b5b5-11e7-883e-6e9896e1ea21.png)

**Comment by joergister** [comment]
funny side fact: both importing mp3 and sound-touch is marked as disabled though they work both very well. 
![screenshot_20171020_164800](https://user-images.githubusercontent.com/24881413/31827607-86ac52b4-b5b8-11e7-85d6-4c536a7473c2.png)

**Comment by joergister** [comment]
I'm only curious. Do you plan to make it possible to import .opus files when using the audacity flatpak by including this FFMPEG-Compatibility mode into the audacity Flatpak build?

Cause at the moment I'm kinda stuck with the audacity build my distribution has in its repositories since I'm depending on this feature. 
I would really like to use the flapaked version but at the moment this is unfortunately not possible.

At least I think Flatpaks will only succeed if they include all the feature a software has. Otherwise it seems like one is using a "limited version" and one will probably continue to use the builds that are available in the repositories of the distribution one is using.

**Comment by TingPing** [comment]
Well I passed some flags to enable the opus decoder so somebody just needs to figure out if I missed something.

**Comment by joergister** [comment]
Seems like the is unfortunately the case, since importing opus files still doesn't work in the latest audacity build available on flathub. 

I send some screenshots on that in a previous post. 
It seems like importing opus files (or at least maybe the opus encoder) is somehow depending on an ffmpeg compatibility mode or at least this is what the screenshots I took make me think.

**Comment by jurf** [comment]
Yeah, something is missing, removing `--disable-everything` fixes all import issues for me (I’ve had problems with `.m4a` and `.opus` imports), but I haven’t figured out which flags need to be present for that yet.

**Comment by joergister** [comment]
Dont know weather it helps or not (I'm just testing and guessing) but Audacity Version 2.2.0 (_BTW_ **Thanks a lot for the update!!**) gives some more information on failed import of `.opus` files. 


![screenshot_20171114_194055](https://user-images.githubusercontent.com/24881413/32797979-beebed82-c973-11e7-8856-33822e9bfab3.png)

**Comment by joergister** [comment]
I don't wanna get on anybody s nerves, but the problem with importing .opus files does still exist.

**Comment by joergister** [comment]
Oh I just realized that importing .wma files is also not possible.

**Comment by nedrichards** [comment]
@jurf this commit should fix the m4a issues. https://github.com/flathub/org.audacityteam.Audacity/commit/b8dde8d664451bc2964f25fa72fd6ce503ff07cf

I'm looking at opus and wma right now as well.

**Comment by nedrichards** [comment]
Opus and WMA should be enabled by this: https://github.com/flathub/org.audacityteam.Audacity/commit/4391711ec7df479a7b05ffc03b6beb1bb7394efd

**Comment by jurf** [comment]
Cool, works for me, thanks!

**Comment by joergister** [comment]
Works for me aswell now. 
And audacity has a shiny New ui in gtk3 now. Looks a lot better now.

Thanks a lot for your effort!!!!
