### ISSUE TITLE
Provide a 'handover' workflow

### ISSUE THREAD

**Issue by jimmac** [flathub/flathub#129]
The purpose of flatpak is to give control over the distribution back to the application authors. However to get them aboard it's quite tricky in the transitional period where kinda-sorta-working-alternatives exist. 

It would help us to get more buy-in by having 3rd party get the flatpak build going and then hand it off to the actual project maintainer. Show that it works, rather than asking to provide flatpaks. It's way more appealing to hear "here's how you could maintain a binary for your app that works on most Linux distributions and has an update mechanism" than hearing the same but with "it might not actually work and you have to do all the work yourself."

**Comment by TingPing** [comment]
This has happened in a few PRs where they pinged upstream or opened an issue upstream and we added them as a co-maintainer with the original submitter.

**Comment by bbhtt** [comment]
I think this can be closed. If upstream is interested, we already add them as maintainers during the submission merge or whenever they ask.

If they aren't reaching out is not going to do anything more.
