### ISSUE TITLE
Build fails with segmentation fault during stripping on ARM

### ISSUE THREAD

**Issue by Unrud** [flathub/flathub#1310]
```
FB: Running: eu-strip --remove-comment --reloc-debug-sections -f /srv/buildbot/worker/build-arm-5/build/.flatpak-builder/rofiles/rofiles-6SJGpd/files/lib/debug/lib/libMonoSupportW.so.debug -F /app/lib/debug/lib/libMonoSupportW.so.debug /srv/buildbot/worker/build-arm-5/build/.flatpak-builder/rofiles/rofiles-6SJGpd/files/lib/libMonoSupportW.so
FB: unmounting rofiles-fuse /srv/buildbot/worker/build-arm-5/build/.flatpak-builder/rofiles/rofiles-6SJGpd
process killed by signal 11
program finished with exit code -1
elapsedTime=962.868334
```
https://flathub.org/builds/#/builders/42/builds/896/steps/6/logs/stdio

Is this a bug in **eu-strip**?

**Comment by barthalion** [comment]
The builder it was scheduled on runs Ubuntu 16.04. I remember similar failures on old elfutils, they were gone after upgrade. I will upgrade said server to 18.04 on Monday.

**Comment by barthalion** [comment]
The builder was upgraded.

**Comment by Unrud** [comment]
Still doesn't work: https://flathub.org/builds/#/builders/6/builds/945/steps/6/logs/stdio

**Comment by barthalion** [comment]
Too bad, hoped it's the same issue. I will take a look later this week.

**Comment by bbhtt** [comment]
I doubt this is useful anymore. Closing, please open new issues if anything comes up.
