### ISSUE TITLE
Adopt a Code of Conduct

### ISSUE THREAD

**Issue by bochecha** [flathub/flathub#1317]
*Note: apologies if this isn't the right place to submit this, I didn't find any better forum.*

We should adopt a code of conduct and a process for handling incidents.

Flathub has been growing quite a lot since its inception. As it continues growing, conflicts and incidents are going to happen.

In addition, the very fact of adopting a code of conduct usually helps set the tone for the community, hopefully attracting a more diverse contributor base and avoiding such issues.

For reference, GNOME recently adopted a new code of conduct after months of work from a dedicated committee and consulting experts: https://wiki.gnome.org/Foundation/CodeOfConduct

I'm sure other communities have their own examples of codes of conduct to take inspiration from.

**Comment by TingPing** [comment]
I'll just say this is being actively discussed.

**Comment by BrainBlasted** [comment]
I think the GNOME Code of Conduct would be a good base. It's very well-rounded.

**Comment by barthalion** [comment]
I took the liberty to open a thread on Discourse: https://discourse.flathub.org/t/adopting-code-of-conduct/128

Let's discuss it there.
