### ISSUE TITLE
Flathub is not updating app version

### ISSUE THREAD

**Issue by miguelmota** [flathub/flathub#1318]
The app version for [com.github.miguelmota.Cointop](https://github.com/flathub/com.github.miguelmota.Cointop/blob/master/com.github.miguelmota.Cointop.json) on the flathub [app page](https://flathub.org/apps/details/com.github.miguelmota.Cointop) shows a really outdated version.

![Screenshot from 2019-12-30 18-11-32](https://user-images.githubusercontent.com/168240/71607687-4d170400-2b30-11ea-8f87-6facd6c20322.png)

Any idea on why it hasn't been able to update to the correct version based on the flathub app json file?

**Comment by barthalion** [comment]
I've scheduled a new build. Looks like it publishing job failed (that happens every now and then now as we were doing initial rsync to the new server).

**Comment by barthalion** [comment]
Also note that we pull that info from `appdata` file. Looks like it wasn't updated in project's repository: https://github.com/miguelmota/cointop/blob/master/.flathub/com.github.miguelmota.Cointop.appdata.xml#L20

**Comment by miguelmota** [comment]
@barthalion thanks a ton, I completely missed that 👍
