### ISSUE TITLE
Publish gpg repository key on second channel

### ISSUE THREAD

**Issue by jodkalemon** [flathub/flathub#1324]
https://flathub.org/repo/flathub.flatpakrepo includes the gpg key but there should be a second channel to verify the key. I thought I could at least find the fingerprint elsewhere.

**Comment by bbhtt** [comment]
It's published https://keyserver.ubuntu.com/pks/lookup?search=0x4184DD4D907A7CAE&fingerprint=on&op=index https://keys.openpgp.org/vks/v1/by-fingerprint/6E5C05D979C76DAF93C081354184DD4D907A7CAE

**Comment by bbhtt** [comment]
No it'd be only useful if there was a way to manually verify the commit signatures and if the repo signing key was signed by the person verifying the signature or by someone in their WoT but it is not signed by anyone.
