### ISSUE TITLE
Require new manual review when apps add new holes in sandbox?

### ISSUE THREAD

**Issue by wjt** [flathub/flathub#1337]
At present, when apps are submitted to Flathub they are very heavily scrutinised by a small set of people before they are accepted; but once they are accepted the maintainer can just push whatever they want and we trust that they won't abuse this privilege. It seems only a matter of time before this trust proves misplaced.

I don't think it is practical or desirable to require manual review from that small set of reviewers for each app update, but I wonder whether we could define some kinds of changes which could be detected programmatically and block publishing the new build of the app to the stable channel until the change has been manually reviewed.

The criterion that comes to mind is “the app punches more holes in the sandbox than the previous published version did”. The thinking here is that if it was acceptable for an app to pass `--filesystem=home` when it was first accepted onto Flathub, then further releases with the same permission are no more risky than that original release (and reviewers don't review the _code_, only the manifest etc.). On the other hand, if an app initially didn't have this permission when it was accepted onto Flathub, it is somewhat suspicious for it to suddenly require it.

**Comment by wjt** [comment]
Highlights of discussion on `#flatpak`:

> nedrichards> wjt: conceptually if the app changes substantially then yes, it could deserve a re-review. I wouldn't be against that and a less restrictive set of permissions would absolutely be a review step.
> (you shouldn't be penalised for cleaning up things like dconf holes)
> there may also be something about change of control or similar

> barthalion> wjt: not saying no, but following this trail, reviewers should also get prompted when git repo or url change, or huge patches are being added, as I find it as likely to be abused
> wherever you draw the line, there's always something we will never catch if someone has malicious intent
> so to be actually sure we should be reviewing all changes made, which kinda destroys the point of build and distribution service for applications 
> and we're also giving out tokens to mozilla or freedesktopsdk… nobody reviews that either
> so I am sceptical how much value is in this

I think the sandbox is our main bastion against app maintainers “going bad”. For pragmatic reasons like “wanting fully-functioning apps in our app store”, Flathub is likely to have many apps with the `--filesystem=home` permission for the foreseeable future, and it's not hard to see that this permission allows arbitrary code execution on the host, so when such apps are approved we are placing a great deal of trust in the maintainers. Nonetheless I think we should start exploring options to help this trust perimeter get smaller, not larger, over time. This is just one idea!

**Comment by Erick555** [comment]
I think that insecure permissions are so ubiquitous on flathub that this change is too little to matter in practice. There are also no explicit rules when specific permissions is acceptable so any reviewer decision is subjective and people may feel treated differently. This may bring more annoyance than value.
[filesystem=home](https://github.com/search?q=org%3Aflathub+%22filesystem%3Dhome%22&type=Code)
[filesystem=host](https://github.com/search?q=org%3Aflathub+%22filesystem%3Dhost%22&type=Code)

**Comment by TingPing** [comment]
Modern `flatpak` tells users of permission changes now which helps. Sadly `gnome-software` at this rate likely won't do that.

**Comment by AsciiWolf** [comment]
@TingPing See this ticket: https://gitlab.gnome.org/GNOME/gnome-software/issues/568

**Comment by TingPing** [comment]
Good to know, wonder how specific it is with permissions.

**Comment by awerlang** [comment]
I agree with @Erick555. Assume that apps with permission, even read-only, to host/home are security-critical. No automatic update should happen. At the same time, add fine-grained permissions to each app.

**Comment by SISheogorath** [comment]
@awerlang I definitely disagree with "No automatic updates". For those who want to manually take care of updates, that can be easily done by disabling automatic updates. But we should keep in mind that people don't change defaults. And secure defaults are therefore key. Part of secure defaults, given you read any modern recommendations from the US NIST to the German BSI, are automated updates to be enabled unless you explicitly disable and manually maintain them. And I think this has been proven to be true looking at the any scans of the internet that is able to hit software.

What we can consider is requiring a peer review or send out some sort of heads-up when App permissions are changed in a way that can cause questionable behaviour such as mounting `home`, `host` or `.ssh`. Same obviously goes for exposing `--device=all` or freely accessing various dbus endpoints. Yes, it's not perfect and we might have stuff slipping through, but we also have those kinds of script to prevent random package maintainers to package `rm -rf /` in RPMs and alike. It doesn't hurt to have protections for the most obvious stuff in place.

**Comment by mindinsomnia** [comment]
What if Flatpak had an [Android style permission system,](https://i.stack.imgur.com/4FHva.png) where Flatpak applications added to Flathub can specify what permissions they would like to **request** during install, and users are shown a list of those permissions with the ability to tick or untick the permissions they wish to give the application.

Then when updates are performed, if an application requests permissions it didn't previously have, it could be flagged for review and users would be shown a notification that the application is requesting new permissions?

Applications with a lot of security sensitive permissions could be flagged for review automatically based on certain conditions on a regular basis, if they have been updated.

That way users who wish to fully trust applications can do so, easily, and give all the permissions an application requests upon installation, and users who wish to sandbox more tightly certain applications can choose during install what permissions they trust the application to have. And an applications permissions never change without the user being notified.

**Comment by hadess** [comment]
> What if Flatpak had an [Android style permission system,](https://i.stack.imgur.com/4FHva.png) where Flatpak applications added to Flathub can specify what permissions they would like to **request** during install, and users are shown a list of those permissions with the ability to tick or untick the permissions they wish to give the application.

This would potentially break applications, with the application authors having no say in what required sandbox holes are needed. The end goal is to have no need for any permissions at installation time, and request all the required ones at runtime, where applications will have been modified to take advantage of the more flexible system.

I don't think that offering users the ability to break their apps before they're even installed is a good idea.

**Comment by bbhtt** [comment]
This was implemented recently in the website https://github.com/flathub-infra/website/pull/2413, all apps with any change in permission has to be reviewed and approved right now.
