### ISSUE TITLE
Adding the beta-repo results in GPG error

### ISSUE THREAD

**Issue by stonerl** [flathub/flathub#1342]
I added the beta-repo according to README but I get the following error:

`
"GPG verification enabled, but no signatures found (use gpg-verify=false in remote config to disable)"
`

The repo is added but apps cannot be installed because installation aborts with the same error message. The system I encountered this issue is Linux Mint 19.2 Cinnamon.

**Comment by barthalion** [comment]
Does it still happen to you?

**Comment by stonerl** [comment]
No, I checked it right now and I don't get the error anymore. Closing this one.

What exactly was the problem?

**Comment by barthalion** [comment]
One of the server behind load balancer/CDN was serving stale summary/signature, causing the error.
