### ISSUE TITLE
Remove nz.scuttlebutt.Patchwork from flathub

### ISSUE THREAD

**Issue by Powersource** [flathub/flathub#1369]
I don't know if this is the best place to post this but it seemed ok.

Patchwork is [still maintained]() but the [flathub distribution](https://github.com/flathub/nz.scuttlebutt.Patchwork) is not and hasn't been updated for quite a while. We don't want users to run really old versions of patchwork (security and so on) so we'd appreciate if the repo was removed, since we currently don't have the time to maintain it.

**Comment by TingPing** [comment]
@ptomato Do you have time to maintain this? If not marking it end of life is reasonable.

**Comment by ptomato** [comment]
I would be fine removing it, I thought I was going to use it extensively until I found out you can't log in from multiple devices, so I doubt I will find any more time to maintain it. I would be happy to review others' pull requests to update it though.

**Comment by Powersource** [comment]
@TingPing How do we mark it end of life?

**Comment by TingPing** [comment]
Just add a file to the repo: https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life

The hardest part is I expect building to fail since it hasn't been built in 2 years. In which case an admin will probably have to mark it eol by hand.

**Comment by bilelmoussaoui** [comment]
Done
