### ISSUE TITLE
Application Recommendations

### ISSUE THREAD

**Issue by MakuSensei** [flathub/flathub#137]
hello I wanted to recommend if you can package in flatpak the applications: Handbrake, smplayer, Aegisub, JDownloader2, TeamViewer, Kodi, Chromium or Google chrome, VirtualBox

**Comment by joergister** [comment]
At least Virtualbox should be a problem cause it is depending on dkms kernel module afaik. This is integrated very deep into the system.
Chromium or chrome on the other hand, would be very nice to have them in an sandbox. Same with Firefox.

**Comment by TingPing** [comment]
Chromium cannot reasonably be Flatpak'd atm because it uses its own sandbox.

**Comment by joergister** [comment]
Well I thought about restricted acces in the filesystem. Like only the downloads folder.

**Comment by joergister** [comment]
BTW does Firefox also use its own sandbox? Or could it be flatpak'd?

**Comment by TingPing** [comment]
Firefox has a much weaker sandbox so it being disabled doesn't really matter for now. It is already flatpak'd: https://firefox-flatpak.mojefedora.cz/

**Comment by joergister** [comment]
Good to know. 
But I'm one of the guys having this little issue. 
https://github.com/xhorak/firefox-devedition-flatpak/issues/1
This way it doesn't work for me. 
:relieved:

**Comment by TingPing** [comment]
Add the repo, then install. I have no clue whats broken about their server but that works for me.

**Comment by joergister** [comment]
After ~44MB the download is cancelled every time again. 
Perhaps there is a timeout (yes I have a very slow connection to the internet)

**Comment by joergister** [comment]
I should contact them

**Comment by TingPing** [comment]
Anyway I'll be closing this issue. I don't believe requests make much sense here as all applications are wanted somebody just needs to package them.

**Comment by theScrabi** [comment]
Well teamviewer would be an awesome addition :)

**Comment by muelli** [comment]
> Well teamviewer would be an awesome addition :)

that should be quite easy, actually. There's a standalone binary in the tarball.
