### ISSUE TITLE
Some apps have no info listed on the sandboxing security level

### ISSUE THREAD

**Issue by etc0de** [flathub/flathub#1374]
I know flatpak has at least the potential to have the same security level as other containerization stuff. However, if I recall some apps are packaged with full disk access or even no sandboxing at all which obviously is super insecure in comparison (but of course usually is intended for flexibility, a trade-off).

Now I wanted to see if there was a sandboxed browser and found this:

https://flathub.org/apps/details/org.midori_browser.Midori

But I can't find any info on the entire page about the security level. I think this is suboptimal, and ideally every flatpak package should list in detail about how sandboxed it is (or isn't) so users can make an optimal decision.

**Comment by TingPing** [comment]
This is reported here: https://github.com/flathub/linux-store-frontend/issues/122

Note that other frontends may present the data differently. The `flatpak` cli tool for example is very explicit about them.
