### ISSUE TITLE
Please add the upstream team to org.glimpse_editor.Glimpse

### ISSUE THREAD

**Issue by bochecha** [flathub/flathub#1377]
Hi, upstream Glimpse would like to have access to the Github repository so they can push updates and beta builds.

I was asked to have [the following people](https://github.com/orgs/glimpse-editor/teams/head-honchos) have access:

* @chaomodus
* @Member1221
* @BrainBlasted
* @TrechNex

**Comment by bilelmoussaoui** [comment]
Done
