### ISSUE TITLE
Update fails with "is not available"

### ISSUE THREAD

**Issue by lazka** [flathub/flathub#1380]
```
sudo flatpak update                               
Looking for updates…


        ID                                      Branch           Op           Remote           Download
 1. [✗] io.github.quodlibet.QuodLibet           stable           u            flathub          1.0 kB / 14,6 MB

Error: app/io.github.quodlibet.QuodLibet/x86_64/stable is not available
Updates complete.
error: There were one or more errors
```

* removing the app and reinstalling worked, so I can no longer reproduce.
* using Flatpak 1.6.2

**Comment by barthalion** [comment]
No idea what's this about. Mind re-opening when it happens again? Probably passing `-v` to flatpak will also help to make this error useful.

**Comment by lazka** [comment]
ok. I think I tried "-v" but it didn't show much more. The only special thing I did before was install the test build from buildbot, maybe that confused it.
