### ISSUE TITLE
Force pushing to master in project repo?

### ISSUE THREAD

**Issue by bvschaik** [flathub/flathub#1382]
I made a small f-up: I accidentally committed and pushed to my flathub repo's master branch with my work email address attached to the commit. I would like to remove that commit since I don't want to associate my work email address with my personal one, but my force-push to update the commit got rejected. Who can help me out here?

**Comment by TingPing** [comment]
Link me the commit and I can edit it (Just an email change?). We just don't want general maintainers having the ability to modify history.

**Comment by TingPing** [comment]
I believe I found the commit and edited it. Let me know if there is anything else.

**Comment by bvschaik** [comment]
That was it, thanks! And I understand the restriction on force pushing/rewriting history, for this case it was quite inconvenient though :smiley:
