### ISSUE TITLE
Cannot get Breeze GTK theme to work

### ISSUE THREAD

**Issue by glaubersm** [flathub/flathub#1384]
Hi
This issue was already reported in KDE bugzilla.
https://bugs.kde.org/show_bug.cgi?id=417441
I use Arch Linux + KDE Plasma 5.18.2.
GTK apps from flathub do not respect theme settings because
org.gtk.Gtk3theme.Breeze and org.gtk.Gtk3theme.Breeze-dark
are outdated and built only for the old runtime. Could you update them please? Thanks.

**Comment by TingPing** [comment]
None of these things are relevant. You probably just don't have an XSettings daemon on your system for GTK to read its theme.

**Comment by glaubersm** [comment]
xsettingsd 1.0.0-2 package is installed on my system and the problem persists.

**Comment by TingPing** [comment]
Installed, but did you configure it also?

**Comment by glaubersm** [comment]
I have just configured it according to Arch wiki
https://wiki.archlinux.org/index.php/Xsettingsd

However, the gtk theme is always the same, gtk theme changing via Plasma GUI
has no effect.

**Comment by TingPing** [comment]
The Plasma GUI will never mean anything, it doesn't support XSettings.

**Comment by glaubersm** [comment]
yes, it supports.
https://bugs.kde.org/show_bug.cgi?id=417441#c14

**Comment by TingPing** [comment]
Oh neat.

Still though it doesn't change how any of this works. You are on X11 right not Wayland because that changes everything.

**Comment by glaubersm** [comment]
Using X11 changes nothing regarding xsettings support.
~/.config/xsettingsd/xsettingsd.conf file is updated in the same way on both X11 and Wayland sessions.
But on X11 both GTK3 apps from distro repos and GTK3 apps from flathub respect GTK3 theme settings and on Wayland only GTK3 apps from distro repos respect GTK3 theme settings.

**Comment by TingPing** [comment]
> ~/.config/xsettingsd/xsettingsd.conf file is updated in the same way on both X11 and Wayland sessions.

Sure that file just means nothing on Wayland... XSettings is an extension to X11.

> and on Wayland only GTK3 apps from distro repos respect GTK3 theme settings.

You need an up to date `xdg-desktop-portal-gtk` if it still doesn't work report that there.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
http://github.com/flathub/flathub/issues/1384#issue-571712431, [org.gtk.Gtk3theme.Breeze-dark](http://github.com/flathub/org.gtk.Gtk3theme.Breeze-dark) has never funtioned for me, whereas [org.gtk.Gtk3theme.Breeze](http://github.com/flathub/org.gtk.Gtk3theme.Breeze) has, always.

**Comment by bbhtt** [comment]
This seems to be a system config issue, not very actionable from Flathub's side.
