### ISSUE TITLE
KiCad install error

### ISSUE THREAD

**Issue by jg-fossh** [flathub/flathub#1393]
Got error trying to install KiCad on Clear Linux 
 `Error: Failed to read commit a5ab7cc172d32a150ca2107cb4dace4ea5ca5a1205c22bc649aed9c0ed78024c: No such metadata object f719928575711fafcc58577722db28930360f0ac771cede8dde22a04a056244b.dirtree
error: Failed to install org.kicad_pcb.KiCad: Failed to read commit a5ab7cc172d32a150ca2107cb4dace4ea5ca5a1205c22bc649aed9c0ed78024c: No such metadata object f719928575711fafcc58577722db28930360f0ac771cede8dde22a04a056244b.dirtree`

**Comment by jonathon-love** [comment]
i had a similar error recently. retrying seemed to fix the issue.
