### ISSUE TITLE
Flathub build bot broke, out of hard drive space?

### ISSUE THREAD

**Issue by corecontingency** [flathub/flathub#1403]
I am trying to submit a pull request [here](https://github.com/flathub/com.play0ad.zeroad/pull/8), and buildbot [fails and complains](https://flathub.org/builds/#/builders/32/builds/16619):
```
error: file write error: No space left on device
fatal: unable to write loose object file
fatal: unpack-objects failed
```
in the `checkout manifest` step of `Download sources`.

Anybody know what is going on? Is buildbot out of hard disk space?

**Comment by jonathon-love** [comment]
this appears to be resolved now.

**Comment by barthalion** [comment]
Indeed. I also fixed alert which should have woken me up.
