### ISSUE TITLE
How to get working Qt file chooser

### ISSUE THREAD

**Issue by marcoscarpetta** [flathub/flathub#1410]
Hi,
I'm the developer of PDF Mix Tool [1] and the maintainer of its flatpak package on flathub [2].

In the application, there is a button to open a PDF file and then editing operations on the opened file can be defined. The file is then exported with the "Save" button or the "Save as..." button. When the "Save as..." button is pressed a file chooser dialog is showed and the output file can be selected, while if the "Save" button is pressed the application crash and this is expected since the user didn't authorize the write operation. If the same opened file is first selected through "Save as..." and then the "Save" button is pressed, it works and this is also expected because the user selected that file.

So, the question is: is there a way to make the "Save" button work? Adding other permissions, e.g. `--filesystem=home` is the only way? If so, may I add this permission to the flatpak package [2]?

Finally, a user reported the "Save" button works on his system [3]. How is it possible?

I hope you can answer to my questions.

[1] https://gitlab.com/scarpetta/pdfmixtool
[2] https://github.com/flathub/eu.scarpetta.PDFMixTool
[3] https://gitlab.com/scarpetta/pdfmixtool/-/issues/41#note_305824645

EDIT
I've added the ability to open the application from the "Open with..." context menu and again I think the only way to make it work in flatpak is by adding some filesystem permission, isn't it?

**Comment by TingPing** [comment]
Well the crash is just your bug and not relevant to flatpak.

Anyway you use the portal for it. Qt's file chooser can work but there are some details to use it properly.

**Comment by grulja** [comment]
To make the QFileChooser work with the portal support, you need to use it with default settings, which means avoid using QFileDialog::DontUseNativeDialog. There shouldn't be anything special needed, everything works out of the box.

**Comment by marcoscarpetta** [comment]
It works indeed. The problem only occurs when I use QFileDialog::getOpenFileName to open a file and then I try to save it. Should I create a QFileDialog instead of using the static function?

And what about this?
> I've added the ability to open the application from the "Open with..." context menu and again I think the only way to make it work in flatpak is by adding some filesystem permission, isn't it?

I simply added `MimeType=application/pdf;` to the desktop file. I tested the flatpak locally and it crashes on startup unless I add the `--filesystem=home` permission. Any ideas to make it work without it?

**Comment by grulja** [comment]
I haven't checked the code of QFileDialog, but in documentation it says:
`On Windows, and macOS, this static function will use the native file dialog and not a QFileDialog.`

Based on this, I would guess it doesn't use a native dialog on Linux.

**Comment by marcoscarpetta** [comment]
After a few tests, I concluded that the only way to make it work is to use a QFileDialog with `setAcceptMode(QFileDialog::AcceptSave)` or to use the `QFileDialog::getSaveFileName` static function, but a "Save" button is showed in this case in the dialog that is used to **open** the file and this is unacceptable.

Using `QFileDialog::getSaveFileName` perfectly works when I want to select a file for saving, which can clearly also be the starting file. Please read the first post if this is not clear.

I'm on Arch Linux with xdg-desktop-portal-kde 5.18.3 and xdg-desktop-portal 1.6.0, if this can be useful.

I didn't find any reference to a `QFileChooser` on the web...

Please, a comment on this:
> And what about this?
>> I've added the ability to open the application from the "Open with..." context menu and again I think the only way to make it work in flatpak is by adding some filesystem permission, isn't it?
>
> I simply added MimeType=application/pdf; to the desktop file. I tested the flatpak locally and it crashes on startup unless I add the --filesystem=home permission. Any ideas to make it work without it?

**Comment by grulja** [comment]
When you open a file with QFileDialog, then in case you don't use --filesystem=home, the file is exported to your app through the document portal and you can only read it, you are not allowed to write to it. You will need to first check whether you are allowed to write to that file and if not, you need to use `QFileDialog::getSaveFileName()` or QFileDialog with `setAcceptMode(QFileDialog::AcceptSave)`. 

With `QFileChooser` I actually meant `QFileDialog`, sorry for confusion.

**Comment by marcoscarpetta** [comment]
Ok, thank you. This was what I was asking in the first post (whether I can write to a file opened with `QFileDialog::getOpenFileName` without filesystem permissions). Maybe I had not been clear enough.

Anyway it's getting harder and harder to maintain the package... What should I do now? Disable the "Save" button in the flatpak build?

**Comment by grulja** [comment]
> Ok, thank you. This was what I was asking in the first post (whether I can write to a file opened with `QFileDialog::getOpenFileName` without filesystem permissions). Maybe I had not been clear enough.
> 

It was clear, I just read it in hurry before.

> Anyway it's getting harder and harder to maintain the package... What should I do now? Disable the "Save" button in the flatpak build?

You don't need to disable it, just before doing anything with the file, you just check whether you have permission to write to it, and if you don't, you simply call the same code you have for "Save as".

**Comment by marcoscarpetta** [comment]
But the purpose of the "Save" button is to directly save the file without showing the QFileDialog. It would make no sense to keep it, since it would behave exactly as the "Save as" button, which is next to it.

**Comment by grulja** [comment]
> But the purpose of the "Save" button is to directly save the file without showing the QFileDialog. It would make no sense to keep it, since it would behave exactly as the "Save as" button, which is next to it.

I don't really know what might be a solution to this, unless you use `--filesystem=home`. What if you use `QFileDialog` with `setAcceptMode(QFileDialog::AcceptSave)` and you change the accept label with `setLabelText(QFileDialog::Accept, "Open")`. You will also need to change the window title to "Open file". This should do the trick in my opinion and you will get the file opened for both write and read access.

**Comment by marcoscarpetta** [comment]
It works but the confirmation dialog for file overwriting is shown even if `setOption(QFileDialog::DontConfirmOverwrite, true)` is set and (this is a minor problem) the button icon can't be changed.

> And what about this?
>> I've added the ability to open the application from the "Open with..." context menu and again I think the only way to make it work in flatpak is by adding some filesystem permission, isn't it?
>
> I simply added MimeType=application/pdf; to the desktop file. I tested the flatpak locally and it crashes on startup unless I add the --filesystem=home permission. Any ideas to make it work without it?

There is no way to do this, right? If so, you answered all my questions, so I think we can close. Thank you!

**Comment by TingPing** [comment]
I would say just have the `save` button be hidden or insensitive if the file isn't writable.

**Comment by marcoscarpetta** [comment]
As a final note, I think these operations (write to a file previously selected with an "open file" dialog, open a file in the application with the "open with..." contextual menu) should be somehow permitted in flatpak. There are indeed many applications using filesystem permissions (gimp, libreoffice, evince, abiword, just to name a few), and they would not need it, in my opinion, if these operations were permitted.

Currently, applications without filesystem permissions need to get mutilated and no clear policy about permissions is given. This makes maintaining applications really frustating.

**Comment by TingPing** [comment]
>  think these operations (write to a file previously selected with an "open file" dialog, open a file in the application with the "open with..." contextual menu) should be somehow permitted in flatpak. 

They are. I don't know about the Qt dialogs design, but the GTK dialogs expose a checkbox to be read-only or writable (the default).

I *think* your problem if I read this conversation correctly is some files are being opened by passing the file to the application at launch time from the desktop file?

**Comment by grulja** [comment]
There seems to really be an option to make the opened file writable, just someone didn't mention it in the portal documentation and that's why we don't have it. I will add this option to xdg-desktop-portal-kde, making the opened file automatically writable and open a PR for xdg-desktop-portal to update the documentation.

**Comment by grulja** [comment]
Here you go:
https://github.com/flatpak/xdg-desktop-portal/pull/459
https://phabricator.kde.org/D28218

With that ^ you should be able to keep your current code.

**Comment by marcoscarpetta** [comment]
> Here you go:
> [flatpak/xdg-desktop-portal#459](https://github.com/flatpak/xdg-desktop-portal/pull/459)
> https://phabricator.kde.org/D28218
> 
> With that ^ you should be able to keep your current code.

Great! Thank you

> I _think_ your problem if I read this conversation correctly is some files are being opened by passing the file to the application at launch time from the desktop file?

Yes, this is the second problem

**Comment by TingPing** [comment]
> Yes, this is the second problem

I think you just need to live with that behavior and detect if its writable as mentioned.

**Comment by TingPing** [comment]
Anyway I think this issue can be closed. Great work @grulja.
