### ISSUE TITLE
EOL com.valvesoftware.Steam.VulkanLayer.MangoHud

### ISSUE THREAD

**Issue by gasinvein** [flathub/flathub#1419]
MangoHud changed it's extension point and got new a ID, but since the old extension point was removed from Steam app, old MangoHud extension doesn't build anymore. Please EOL it manually, if possible.
CC @barthalion

**Comment by barthalion** [comment]
Done, it will become visible after summary file is updated by publishing job.

**Comment by gasinvein** [comment]
Thanks!
