### ISSUE TITLE
Please archive com.github.gkarsay.parlatype

### ISSUE THREAD

**Issue by gkarsay** [flathub/flathub#1421]
I've added `end-of-life` and `end-of-life-rebase` to flathub.json. It has been renamed to org.parlatype.Parlatype. Please archive the old name com.github.gkarsay.parlatype.

The new name https://flathub.org/apps/details/org.parlatype.Parlatype gives me "App not found". I guess/hope this is normal and takes a bit of time from the moment I pushed the rebase commit.

**Comment by bilelmoussaoui** [comment]
Done, for archiving the app. I don't think the build started once the repository was created, do you mind pushing something to the org.parlatype.Parlatype to trigger a new build? thanks

**Comment by gkarsay** [comment]
I triggered a build, it works now. Thank you!
