### ISSUE TITLE
EOL org.freedesktop.Platform.openh264//19.08

### ISSUE THREAD

**Issue by nanonyme** [flathub/flathub#1423]
Please eol-rebase org.freedesktop.Platform.openh264//19.08 to org.freedesktop.Platform.openh264//2.0. The former is broken and not fully license-compliant. While runtimes have already moved to 2.0, apparently users keep getting warnings if they still have the 19.08 one installed.

**Comment by barthalion** [comment]
Apparently it's not possible as --end-of-life-rebase operates only on app ids, not entire refs.

**Comment by barthalion** [comment]
I can only suggest specifing end of life message via flat-manager-client.

**Comment by alexlarsson** [comment]
If its license is problematic we can replace it with something that is essentially empty.
