### ISSUE TITLE
Add cuda toolkit extension

### ISSUE THREAD

**Issue by Red-Eyed** [flathub/flathub#1437]
A lot off applications, such as Blender (3D rendering) ML applications and Cryptocurrency requires NVIDIA CUDA
As GPU computing grows and NVIDIA CUDA is defacto the primary GPU computing framework  

So, it would be nice to add cuda tollkit extension which includes:
cuda toolkit and cudnn

**Comment by bbhtt** [comment]
The repo here is for reporting issues, packaging requests should go to https://discourse.flathub.org/c/requests/5 but note that posting there doesn't guarantee it'll be added as everything is community based.
