### ISSUE TITLE
Adding Cryptomator // 

### ISSUE THREAD

**Issue by FONDSMATIVE** [flathub/flathub#1443]
Hi everybody! 

First of all many thanks for that great *community*!

**It would be great to add *Cryptomator* to Flathub** as well. 
I would really love to see this *App* on Flathub. 
You will find their [project here as well](https://github.com/cryptomator/cryptomator).

**Unfortunately I do not know where to start adding this to Flathub or even if I am legally allowed to. Maybe you guys can get in touch with Cryptomator's team? That is why I opened this issue**.

Many thanks to all of you!!! 

P.S. 
What they say: 
***Free client-side encryption for your cloud files***. Open source software: No backdoors, no registration. **That is what they stand for!**

Support 
[One-time or recurring donation via Cryptomator's website.](https://cryptomator.org/#donate)
[Become a sponsor via Cryptomator's sponsors website.](https://cryptomator.org/sponsors/)

**Comment by bilelmoussaoui** [comment]
There's an issue upstream to track that https://github.com/cryptomator/cryptomator/issues/729. This repository isn't for applications requests, as they should be submitted by the developers themselves

**Comment by FONDSMATIVE** [comment]
@bilelmoussaoui 
Thank you so much! I didn't know that open issue cryptomator/cryptomator#729.
Many thanks again!
