### ISSUE TITLE
error: Transferred a partial file

### ISSUE THREAD

**Issue by cmurf** [flathub/flathub#1447]
Other updates worked, but one is consistently failing with a partial file transfer.

```
Error: While pulling app/com.jgraph.drawio.desktop/x86_64/stable from remote flathub: While fetching https://dl.flathub.org/repo/objects/64/7bbf002083d7cb8976d15defc886e65ea1e5ee438077db95dd28e96eff1146.filez: [18] Transferred a partial file
Updates complete.
error: There were one or more errors
$ flatpak update
Looking for updates…


        ID                                  Branch          Op          Remote           Download
 1. [✗] com.jgraph.drawio.desktop           stable          u           flathub          75.2 MB / 100.0 MB

Error: While pulling app/com.jgraph.drawio.desktop/x86_64/stable from remote flathub: While fetching https://dl.flathub.org/repo/objects/64/7bbf002083d7cb8976d15defc886e65ea1e5ee438077db95dd28e96eff1146.filez: [18] Transferred a partial file
Updates complete.
error: There were one or more errors
```

**Comment by cmurf** [comment]
Today, same flatpack, different error. I have may be a dozen other flatpaks that continue to update without errors.

Error: While pulling app/com.jgraph.drawio.desktop/x86_64/stable from remote flathub: While fetching https://dl.flathub.org/repo/objects/e6/8860cad5f6cd86aa6ceb5139776290dc1849b177607dd4384a38dc14b5e81c.filez: [92] Stream error in the HTTP/2 framing layer
Updates complete.
error: There were one or more errors
$ 

Tried to update a second time, and it worked (no error). So I guess this can be closed.

**Comment by AmateurECE** [comment]
I'm also seeing this issue on Gentoo Linux, with Flatpak version 1.14.4. I'm not seeing anything like this in any other application I'm running...@cmurf, did you resolve your issue?

**Comment by bbhtt** [comment]
@cmurf is this still an issue?

**Comment by bbhtt** [comment]
Closing this as this might have been a transient error or might have been resolved. Please reopen if it still happens.
