### ISSUE TITLE
Qt BaseApp vs automatic rebuild?

### ISSUE THREAD

**Issue by eszlari** [flathub/flathub#1453]
Apps like https://github.com/flathub/org.kde.skrooge, that use Qt plugins, need to be rebuild, even after a minor version bump (e.g. 5.14.1 to 5.14.2).

We need a system that triggers a rebuild of all apps that need it, and even better, that holds back the upload of the new runtime, until these rebuilds are finished.

If this is too convoluted, we could also provide a Qt BaseApp for these apps (with all the drawbacks this bundling entails).

related bug report: https://bugs.kde.org/show_bug.cgi?id=408970

**Comment by TingPing** [comment]
The situation sucks but I don't think a baseapp helps, it just moves the problem.

**Comment by eszlari** [comment]
> The runtime itself needs Qt so it includes Qt.

I meant a Qt BaseApp used together with the freedesktop runtime.

**Comment by eszlari** [comment]
We could merge `io.qt.qtwebkit.BaseApp` and `io.qt.qtwebengine.BaseApp` together with the rest of Qt (no KDE deps, maybe Pyside/PyQt) into one BaseApp and provide convenient cleanup scripts for each component, so everyone can take what one needs.

I'm curious what @aleixpol thinks.

**Comment by aleixpol** [comment]
I don't understand what you win. Qt WebKit and Qt Web Engine are magnitudes bigger than all KDE dependencies combined.

**Comment by eszlari** [comment]
Certainly, but you would need a cleanup script for every KDE component (could be automated with cmake's install_manifest.txt).

**Comment by aleixpol** [comment]
Let's recap.

Here the problem is that QtWebKit needs updating when Qt changes.
Nothing here has anything to do with KDE Frameworks or any of the components.

A solution would be to have io.qt.QtWebKit/Engine be runtimes instead of BaseApps, this way they wouldn't be packaged into the app, we'd only need to update the webkit which we do anyway.

For QtWebKit this should be trivial. For QtWebEngine less so because python2 (which is the main reason why it was split from org.kde.Platform really) but still doable.

**Comment by eszlari** [comment]
This thread is not specifically about the QtWebKit/Engine BaseApps, but more generally about every app that needs a specific Qt version and thus needs to bundle Qt itself.

I just mentioned QtWebKit/Engine, because putting everything in one BaseApp would decrease the maintenance burden.

**Comment by aleixpol** [comment]
Which application needs to bundle Qt itself?

> Apps like https://github.com/flathub/org.kde.skrooge, that use Qt plugins, need to be rebuild, even after a minor version bump (e.g. 5.14.1 to 5.14.2).

Please revisit this premise, I think you've misunderstood the problem.

**Comment by eszlari** [comment]
```
$ flatpak install flathub org.kde.skrooge
$ flatpak update --commit=1679bd11a2d6c881009254ae1d753437b79f43de2e5f61757083fa65d1251d4f org.kde.skrooge
$ flatpak run org.kde.skrooge 
##FATAL: Cannot mix incompatible Qt library (version 0x50e01) with this library (version 0x50e02)
```


> Which application needs to bundle Qt itself?

I don't know the number, but it would be every app that e.g. in Debian depends on [qtbase-abi-5-x-x](https://packages.debian.org/sid/qtbase-abi-5-12-5) (a virtual package, so determining reverse dependencies seemingly [not possible](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=647053)).

Examples:
https://packages.debian.org/sid/skrooge
https://packages.debian.org/sid/calibre-bin
https://packages.debian.org/sid/qtcreator

**Comment by aleixpol** [comment]
> ##FATAL: Cannot mix incompatible Qt library (version 0x50e01) with this library (version 0x50e02)

Because you're mixing different Qt libraries. Don't do that.

**Comment by Erick555** [comment]
Having Qt as part of freedeskto-sdk or as separate baseapp was proposed multiple times and rejected. KDE folks have no time to maintain second Qt runtime and nobody will trust random folks to do it.

If for some reason your app can't use Qt from KDE runtime then you have to use freedesktop-sdk runtime and bundle qt yourself.

**Comment by eszlari** [comment]
> For flathub it would be nothing

The last build took over 8 hours:
https://flathub.org/builds/#/builders/32/builds/18837

>  for local use it would be cached

...which is a worse developer experience that downloading your distribution's version or the official pre-compiled SDK from: http://download.qt.io/official_releases/qt/

**Comment by Erick555** [comment]
Sadly there are no timestamps so hard to say what takes so much time but qt5-base takes 30m to build on my several years old notebook which is incomparable to flatub beasts. App won't need every qt feature

We're talking about very corner case where app can't use Qt from runtime not an overage app. If particular app breaks on every qt bump then it will break in distro too (unless such distro just skips qt updates like debian). Also I heard pre-compiled stuff will be customer-only soon developers of such apps are will have hard time no matter what.

**Comment by barthalion** [comment]
It should stay as `Automatic rebuild after runtime update`. qtwebkit/qtwebengine base apps are also affected so I don't see why we shouldn't extend it into specific apps. Not a perfect solution from portability point of view but such is life.

**Comment by eszlari** [comment]
Another "solution" could be, to use freedesktop as the runtime and kde as the sdk and manually copying the files that are needed to /app.

**Comment by williamjmorenor** [comment]
Hello I am new here, just currios to know if the org.kde.Platform include PyQT5

I am looking into flatpaking a PyQT5 base app but the single PyQT5 library is 381.4 MB on my venv and I do not use more that some modules and do not want to bunble all the PyQT5 library in the final package.

![Captura de pantalla de 2020-08-01 11-04-10](https://user-images.githubusercontent.com/3522386/89106410-d94f1980-d3e6-11ea-82d5-e20a3b3aacef.png)

**Comment by Erick555** [comment]
Kde Platform doesn't include pyqt5 but apps may [easily bundle it](https://github.com/flathub/com.github.micahflee.torbrowser-launcher/blob/f6df58bef59e6281926d8b7a2fce90b205fc22c4/com.github.micahflee.torbrowser-launcher.yaml#L39) though.

I think pyqt5 is too small and simple to be in baseapp alone (in my sytem it's just 25MB) and it doesn't make sense to bundle tons of modules nobody would use there neither so I don't know why you want to make a baseapp. Also this question is rather out of topic here.

**Comment by williamjmorenor** [comment]
Thank a lot for the link!

**Comment by bbhtt** [comment]
let's continue this in https://invent.kde.org/packaging/flatpak-kde-runtime/-/issues/64, that's the ideal solution, and anything else would be brittle.
