### ISSUE TITLE
Brave Flatpak?

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/flathub#1468]
Hello, I am wondering if there could be Brave packaged as Flatpak. There are a lot of people asking for a flatpakd packaged of Brave's repo: https://github.com/brave/brave-browser/issues/1000.

One of the members has also said that they are willing to create a Brave Flatpak, if someone is willing to help them: https://github.com/brave/brave-browser/issues/1000#issuecomment-520582286.

**Comment by TingPing** [comment]
You can make package requests here: https://discourse.flathub.org/c/requests/5

Sandboxing Chromium is tricky but I think is approaching doable.

**Comment by mati865** [comment]
Already requested: https://discourse.flathub.org/t/brave-browser-flatpak-request/205
