### ISSUE TITLE
How to flag "outdated"?

### ISSUE THREAD

**Issue by nazar2sfive** [flathub/flathub#1469]
![image](https://user-images.githubusercontent.com/12841320/80280820-569f2a00-8726-11ea-9ec4-2003ade9445e.png)

![image](https://user-images.githubusercontent.com/12841320/80280827-63bc1900-8726-11ea-8b14-70819262aec3.png)

latest is **9505**

Please add a option to flag.

**Comment by bilelmoussaoui** [comment]
Click on see details which will redirect you the Github repository that contains the manifest that builds WPS and open an issue there.
