### ISSUE TITLE
question: why flathub allows distributing proprietary software?

### ISSUE THREAD

**Issue by kolokd** [flathub/flathub#1478]

**Comment by Nokia808** [comment]
@kolokd 
And what is the wrong by this as long as they warn you about their packages whether being open source or closed source ?

Flatpak - being a sandbox by default - is the best way to use such closed source applications & packages without allowing them to penetrate your Linux ...... From this point of view, it is very very useful & helpful (& secure - in fact most secure currently) for FlatHub to ship such closed source applications & dangerous software like WINE which can run viruses on your Linux .....

**Comment by TingPing** [comment]
Its just a policy we allow them, I don't think we need to get into any philosophical debates on here.
