### ISSUE TITLE
Why Zoom not Jitsi on flatHub ?

### ISSUE THREAD

**Issue by Nokia808** [flathub/flathub#1481]
Sorry for this. I thought to contact FlatHub administrators in private emails about this, but due to it's significant during these days of COVID19 pandemic where video conferences become very important for far study & work from house, I decided to post it here. 

Dear, I notice that you are very indulgent in maintain Zoom on FlatHub ..... Okay this is good. But why you do not give attention for Jitsi which is too much better than Zoom ?!

Jitsi is:
1) open source while Zoom is closed source,
2) Jitsi is completely free of charge while Zoom is of free & paid versions,
3) Zoom is a USA service while the Jitsi is of multi-instances:
https://meet.jit.si    (is developer team official instance which is Switzerland service operated by developers team of Jitsi & it is their web official application)
But we have other instances like:
- the Jitsi instance of Infomaniak.com - see:
https://www.infomaniak.com/en/meet/
https://meet.infomaniak.com/?lang=en
- Jitsi instance of disroot.org - see:
https://calls.disroot.org/

Moreover, every one - if expert - can build heir/his Jitsi instance !
4) Jitsi is UNLIMITED in number of those who can take part in video conference ! & for free !

Jitsi has a program - currently available for Linux officially as AppImage - see:
https://github.com/jitsi/jitsi-meet-electron
https://github.com/jitsi/jitsi-meet-electron/releases

I asked them to add it as flatpak, but they refuse - see:
https://github.com/jitsi/jitsi-meet/issues/6503

Please notice that I post my request in wrong repository - see discussion bellow:
https://github.com/jitsi/jitsi-meet-electron/issues/318

So the package that should be packaged as flatpak is "jitsi-meet-electron":
https://github.com/jitsi/jitsi-meet-electron

I would like to suggest on the maintainers of flatpak packages on FlatHub & FlatHub administrators to pay attention for "jitsi-meet-electron" & make it available as flatpak on FlatHub because "jitsi-meet-electron" has an option set by default on https://meet.jit.si but user can reconfigure it & change it to utilize other Jitsi instances ..... 

Thank you for you.

**Comment by barthalion** [comment]
Someone submitted Zoom but no one submitted Jitsi. Not much more to explain here.
