### ISSUE TITLE
Request for maintainership "com.shatteredpixel.shatteredpixeldungeon"

### ISSUE THREAD

**Issue by daniel-wtd** [flathub/flathub#1494]
Hello,

the repository below is outdated and unmaintained for some time. I want to request the maintainership. I had a look and keeping it up to date seems quite simple.

https://github.com/flathub/com.shatteredpixel.shatteredpixeldungeon

Please feel free to reach out to me in case, you are having any questions.

**Comment by bilelmoussaoui** [comment]
You can just send merge requests in the mean time and ping me, I will try to merge things as soon as possible. We can grant you write access once you have contributed a bit to the package.

**Comment by daniel-wtd** [comment]
@bilelmoussaoui Thanks a lot, sounds awesome. Will do so.

**Comment by bilelmoussaoui** [comment]
Just add me as a reviewer to your merge requests in case I don't notice.

**Comment by bilelmoussaoui** [comment]
I went ahead and gave you write permissions after seeing some PR landing :) thanks!

**Comment by daniel-wtd** [comment]
Thanks a lot :) I will do my very best.
