### ISSUE TITLE
Gtk3 themes not updated for newer GNOME runtimes

### ISSUE THREAD

**Issue by tidux** [flathub/flathub#1503]
There is exactly one Gtk3 theme on Flathub that supports GNOME runtimes newer than 3.28.  There are only four theme families that support GNOME runtimes newer than 3.22.  Most of these themes do support newer GNOME versions in their non-flatpak iterations so this looks like lazy packaging.  If the original maintainers are no longer updating them, it's time to change ownership.

**Comment by bilelmoussaoui** [comment]
GTK3 themes don't require an update of the runtime; it's only used at build time. Pull requests are welcome anyway.

**Comment by TingPing** [comment]
I'll just close this since this isn't really actionable. The runtime used indeed does not matter at all.
