### ISSUE TITLE
Request for maintainership of "org.kicad_pcb.KiCad"

### ISSUE THREAD

**Issue by jmaibaum** [flathub/flathub#1527]
Hello,

I have been adding a few PR's to [org.kicad_pcb.KiCad](https://github.com/flathub/org.kicad_pcb.KiCad) throughout the last few months in order to keep the program up to date on flathub. I have a few more things in the pipeline to fix open/outstanding issues with the flatpak (like adding docs for example). A few of the PR's have been merged quite fast by the flathub team, but currently four more are still waiting.

Recently @eszlari , another previous contributor to the flathub/org.kicad_pcb.KiCad repo has been motivating me to ask for maintainership here.

If it is generally accepted that users (I am using the KiCad flathub flatpak on a few machines myself, but I am not a core KiCad developer) are maintaining flathub packages, even though they might suffer from lack of time themselves, at times, I would be very happy to maintain org.kicad_pcb.KiCad.

**Comment by bilelmoussaoui** [comment]
I have sent you an invitation; please let us know if you need any help! thanks
