### ISSUE TITLE
Gydl cant establish a connection to the internet

### ISSUE THREAD

**Issue by joergister** [flathub/flathub#153]
Download in Gydl doesn't work. Every time I paste a link to a youtube Video, select an audio or video codec (and quality) and click on download, I get a popup that tells me that a connection to the internet could not be established, even though it exists.

![screenshot](https://user-images.githubusercontent.com/24881413/32797469-259bb528-c972-11e7-8dc4-7fe11485e859.png)

This way the flatpak is kinda useless for me, being a downloader that can't download anything;)

Starting the app via the command line by tiping:

> flatpak run -v com.github.JannikHv.Gydl 

gives this as an output:

```

```
> XA: No installations directory in /etc/flatpak/installations.d. Skipping
> XA: Opening user flatpak installation at path /home/youdontknow/.local/share/flatpak
> XA: Opening system flatpak installation at path /var/lib/flatpak
> XA: Opening user flatpak installation at path /home/youdontknow/.local/share/flatpak
> XA: Opening system flatpak installation at path /var/lib/flatpak
> XA: Disallowing ipc access
> XA: Allowing x11 access
> XA: Allowing wayland access
```


```

Don't know what `ipc access` is... is it internet connection?

**Comment by TingPing** [comment]
There is a discussion over it here: flathub/com.github.JannikHv.Gydl#1
