### ISSUE TITLE
App Maintenance: replace .appdata.xml with .metainfo.xml

### ISSUE THREAD

**Issue by cbm755** [flathub/flathub#1530]
At https://github.com/flathub/flathub/wiki/App-Maintenance#acceptable-but-should-be-submitted-upstream there is an example `com.example.MyCoolApp.appdata.xml`.

I tried to update this to `com.example.MyCoolApp.metainfo.xml` but couldn't find an edit button on the wiki (perhaps its disabled).

**Comment by TingPing** [comment]
Changed.
