### ISSUE TITLE
App Maintenance wiki: mentions i386: do we have that?

### ISSUE THREAD

**Issue by cbm755** [flathub/flathub#1531]
The build bot only seems to be doing `x86_64`, `arm` and `aarch64`.  Is there a canonical list somewhere?  If so the wiki could be linked to there.

**Comment by TingPing** [comment]
The list depends on the runtime and the current releases of all runtimes do not support `i386`.

**Comment by cbm755** [comment]
So then wiki entry https://github.com/flathub/flathub/wiki/App-Maintenance needs updated to remove i386.

**Comment by bilelmoussaoui** [comment]
I don't think we should remove that. Flathub builders still do support building on i386, it's just the runtimes based on fdo 19.08 or newer that don't support i386 anymore.

**Comment by EchedeyLR** [comment]
> I don't think we should remove that. Flathub builders still do support building on i386, it's just the runtimes based on fdo 19.08 or newer that don't support i386 anymore.

As "anymore" what do you mean?. Do you have the reference about it to check?

**Comment by linuxhw** [comment]
i386 is still used by ~5% of users: https://github.com/linuxhw/Trends#arch

How to rebuild i386 18.08 platform version of the app if I already updated to 20.08?

**Comment by TingPing** [comment]
Change the runtime in the manifest and build it. 18.08 isn't supported any longer I believe so its not a great idea.

**Comment by hfiguiere** [comment]
only x86_64 and aarch64 are supported. There are option to provide 32bit compatible for when there is no option but the flatpak arch will remain either of these.

**Comment by razzeee** [comment]
Wiki no longer mentions `i386` will close this.
