### ISSUE TITLE
New packages infinitely loading

### ISSUE THREAD

**Issue by linkmauve** [flathub/flathub#1559]
I just updated this recipe: https://flathub.org/apps/details/io.poez.Poezio

Here it’s stuck loading forever, with a weird `LOADING ...` typography (it should be `LOADING…`, note the ellipsis).

The issue seems to stem from the `main….js` file being actually a HTML file, but this file exists for other packages so the root of the issue might be different.

**Comment by bilelmoussaoui** [comment]
Your latest build wasn't published yet https://flathub.org/builds/#/builders/32/builds/20876

**Comment by linkmauve** [comment]
Oh indeed, but the UX is still sub-par, the user should be notified when the JS file fails to load instead of facing an infinitely (non-)loading spinner.

**Comment by bilelmoussaoui** [comment]
In such case the issue should be opened on https://github.com/flathub/linux-store-frontend

**Comment by linkmauve** [comment]
There, thanks. :)
