### ISSUE TITLE
Unable to load summary from remote flathub: Signature made Thu 01 jan 1970 02:00:00 +0200 using [unknown name] key ID

### ISSUE THREAD

**Issue by ieugen** [flathub/flathub#1568]
Hello,

I'm having some issues when `flatpak update` and `flatpak install` . 
I've removed flathub repo, added it again hoping it will work but it does not.

Yesterday it did the same. 

Any ideas?

```
 An error was encountered searching remote ‘flathub’ for ‘com.discordapp.Discord’: Unable to load summary from remote flathub: Signature made Jo 01 ian 1970 02:00:00 +0200 using [unknown name] key ID 562702E9E3ED7EE8
BAD signature from "Flathub Repo Signing Key <flathub@flathub.org>"
Primary key ID 4184DD4D907A7CAE
Primary key expires Lu 14 iun 2027 16:18:56 +0300
error: No remote refs found similar to ‘com.discordapp.Discord’
```

Other notes from this experience:

- When I remove the repo I have to remove all of my applications. This seems kind of strange and not practical, especially when I might just want to add the repo again later. I should be able to keep my applications or at least have an easy way to save them and re-install them afterwards.

**Comment by A-Hussein-M** [comment]
Confirming this on Fedora 32, it seems to be happening randomly since it managed to update yesterday after couple tries, now its back.

**Comment by froseb** [comment]
Same here on Debian Bullseye. The update did work about half an hour ago for me.

**Comment by barthalion** [comment]
There was a bug in post-publish script which caused CDN to serve stale summary file. It's fixed now.
