### ISSUE TITLE
Please remove com.airtame.Client i386 variant

### ISSUE THREAD

**Issue by klausenbusk** [flathub/flathub#1569]
Hi

Upstream never provided a i386 binary, but the Flatpak did not reflect that. It has been fixed in: https://github.com/flathub/com.airtame.Client/commit/97cf907a9473673f78be83eb8c2f927018926d62

So the not-working i386 variant needs to be removed.

\- Kristian

/cc @barthalion

**Comment by barthalion** [comment]
Done.
