### ISSUE TITLE
Document flathubbot's use of flatpak-external-data-checker

### ISSUE THREAD

**Issue by wshanks** [flathub/flathub#1582]
After [writing my own flatpak update checker](https://github.com/willsALMANJ/flatpak_update), it was [pointed out to me](https://github.com/flathub/de.klayout.KLayout/pull/1#issuecomment-641606414) that this functionality already exists in [the flatpak-external-data-checker repo](https://github.com/flathub/flatpak-external-data-checker) and flathubbot already runs this checker all the flathub flatpak repos. It would be good to document this feature on the [App Maintenance wiki page](https://github.com/flathub/flathub/wiki/App-Maintenance), perhaps in the "Test builds and pull requests" section or in a new section just below titled "Automated checking and updating of manifest files" with text:

> Buildbot checks each manifest file in your repository periodically for broken links using the [Flatpak External Data Checker](https://github.com/flathub/flatpak-external-data-checker). The Flatpak External Data Checker can also check for new versions of a Flatpak dependencies and create pull requests with the update manifest file. See the Flatpak External Data Checker's documentation for how to configure the check for new versions.

Also, while updating the wiki, perhaps this passage:

> You can track your build status, follow the build log for current and historic builds, start builds or publishe build on the Buildbot instance website.

could have the sentence "To modify or publish builds, make sure to sign into buildbot with your GitHub account" added (and fix the "publishe" type). I missed this at first and thought I could only monitor the build since the UI elements for modifying the build are not shown until you log in.

**Comment by barthalion** [comment]
This is somewhat documented at https://github.com/flathub/flatpak-external-data-checker. Our documentation needs major overhaul, automatic updates surely belongs there.

**Comment by j8r** [comment]
How to configure/use it is rather quite documented, but not what to expect of @flathubbot. Is it already setup and will submit PRs, otherwise what we have to do to make it to do so? Do we have to run our own external checker?

An other thing, in my opinion, the Flathub Wiki/documentation should better be a repository, so anyone can submit PRs to improve it.

**Comment by j8r** [comment]
I see there is a GitHub Actions in this repo: https://github.com/flathub/flathub/blob/master/.github/workflows/external-data-checker.yml, and I successfully run the container:
`podman run -it --rm -v $PWD:/dir -w /dir ghcr.io/flathub/flatpak-external-data-checker:latest org.flycast.Flycast.yml`

```
+ 2021-04-20 20:08:17,934    INFO src.checker: Checking 1 external data items
+ 2021-04-20 20:08:17,935    INFO src.checker: Started check [1/1] flycast.git (from org.flycast.Flycast.yml)
+ 2021-04-20 20:08:18,688 WARNING src.lib.externaldata: Source flycast.git: remote data changed
+ 2021-04-20 20:08:18,688    INFO src.checker: Finished check [1/1] flycast.git (from org.flycast.Flycast.yml)
BROKEN: flycast.git
 Has a new version:
  URL:       https://github.com/flyinghead/flycast.git
  Commit:    a9e22c2e20b5a408e6a4a69f4dcce743e869dff3
  Tag:       None
  Branch:    master
  Version:   None
  Timestamp: None
```

What I'm missing to enable @flathubbot to submit a PR?

**Comment by barthalion** [comment]
> Is it already setup and will submit PRs, otherwise what we have to do to make it to do so? Do we have to run our own external checker?

At the moment, there's a GitHub action running every hour in this repository, which clones all Flathub repositories and looks for `x-data-checker` string. So as long as it's there, f-e-d-c will run on your app.

Note flatpak-external-data-checker, while could be used this way, isn't generally designed to bump on every commit (and neither is Flathub meant to be general CI system). For example, OpenRCT2 combines GitHub Actions and `repository_dispatch` event to update Flathub repo on push to the project's repo: see https://github.com/OpenRCT2/OpenRCT2/blob/develop/.github/workflows/ci.yml#L252 and https://github.com/flathub/io.openrct2.OpenRCT2/blob/master/.github/workflows/beta.yml

Alternatively, Obsidian maintainer uses GitHub Actions and cron for pull-based updates like f-e-d-c would do: https://github.com/flathub/md.obsidian.Obsidian/blob/master/.github/workflows/auto-update.yml

**Comment by j8r** [comment]
Thanks @barthalion ! What I didn't understand was for https://github.com/flathub/net.rpcs3.RPCS3/blob/master/net.rpcs3.RPCS3.yaml, which has @flathubbot updating its `https://github.com/RPCS3/rpcs3.git` repository hash, which has not a `x-checker-data` - only `libevdev` has it.

Anyway, good idea, I'll create a GitHub Action cron to bump the commit hash - simple and effective. Thanks again!

**Comment by barthalion** [comment]
Yeah, it's because it's simple `grep -r x-data-checker`, so basically a comment with that string would suffice to make f-e-d-c run for given repo.

**Comment by j8r** [comment]
It is in fact `x-checker-data`, from https://github.com/flathub/actions/blob/master/flathub-external-data-checker/entrypoint.sh

**Comment by razzeee** [comment]
I've added this here in the new docs https://docs.flathub.org/docs/for-app-authors/external-data-checker

Not sure if we would like to flesh it out some more at that location

**Comment by wshanks** [comment]
I think that is good enough to close this. When this was opened, I think you had to find out about it by seeing it referenced in other issues or pull requests.
