### ISSUE TITLE
Adjust builderbot for new branch settings from Github

### ISSUE THREAD

**Issue by Eonfge** [flathub/flathub#1593]
In the current set-up, the stable versions are linked to 'master'-branches, while the beta versions are linked to 'beta'-branches. Since Github has announced their policy on new branches and repositories, we'll have to adjust the configurations for stable and beta versions. 

# Scenario 1
Now, beta is already using the 'beta'-branch, so it would make more sense to have a 'stable'-branch for all stable versions on Flathub. Are there any technical hurdles, or is it possible to publish stable versions from a 'stable'-branch, unless a 'master'-branch exists? This will keep backwards compatibility, and it is more clear to the future.

# Scenario 2
Change the create-repo bot configuration to make a 'master'-branch, continuing business as usual.

_Edit: Did accidentally close it. Feel free to ignore that_

**Comment by klausenbusk** [comment]
> Since Github has announced their policy on new branches and repositories, we'll have to adjust the configurations for stable and beta versions.

Could you elaborate on which new policy you are referring to?

**Comment by barthalion** [comment]
I believe GitHub hasn't announced new naming yet. When that changes, I'll take a look, as it will require some changes to buildbot and other automation.

**Comment by klausenbusk** [comment]
> Could you elaborate on which new policy you are referring to?

https://www.bbc.com/news/technology-53050955
