### ISSUE TITLE
Establish an ID convention for OSS codebase derived apps maintained at Flathub

### ISSUE THREAD

**Issue by mzabaluev** [flathub/flathub#1595]
This came up in https://github.com/flathub/com.visualstudio.code.oss/pull/56#issuecomment-644591977: an ID convention might be needed for apps developed as Flathub projects, but based on open source code controlled by a vendor and used as the basis for proprietary apps.

To clearly disambiguate and to avoid control issues with using name prefixes controlled by the original vendors, I propose `org.flathub.app.$vendor.$AppName`.

**Comment by gasinvein** [comment]
`.app` feels redundant here. Also, who's the `$vendor` here?

**Comment by mzabaluev** [comment]
> `.app` feels redundant here.

I thought it is nice to have a namespace for the apps under `org.flathub`, plus `org.flathub.app` has a good self-descriptive ring to it.

> Also, who's the `$vendor` here?

The publicly recognized name of the entity controlling the domain name of the project, the GitHub org, etc.
Examples: `microsoft`, `google`, `github`.

**Comment by barthalion** [comment]
Sorry, but these are not Flathub projects, and establishing a naming convention for literally one app is just silly. `code-oss` looks good enough and avoiding problems with GNOME Software sounds like a good reason to do the eol/eol-rebase dance, feel free to submit it as a new app.

**Comment by mzabaluev** [comment]
> Sorry, but these are not Flathub projects

Sorry, but the only place the project formerly known as `com.visualstudio.code.oss` can be said to have a presence is this GitHub org. Microsoft has had nothing to do with supporting it, and should it decide to publish its own Flatpak apps, this kind of ID may even come into contention.

> avoiding problems with GNOME Software sounds like a good reason to do the eol/eol-rebase dance,

That was a problem with that particular app ID, bit it is not the main concern here.

**Comment by bilelmoussaoui** [comment]
The app-id doesn't really tell you who published which app, the user never notice that and if they use a frontend like GNOME Software or KDE Discover, they never know that such thing exists. 

If the issue is about informing that the application is not published by the developers/vendor themselves, that should be mentioned on the appdata, see https://flathub.org/apps/details/com.amazon.Workspaces for example.

**Comment by mzabaluev** [comment]
OK. I dunno, all that talk about name ownership in [Flatpak documentation](https://docs.flatpak.org/en/latest/conventions.html#application-ids) had me worked up :man_shrugging:

**Comment by mzabaluev** [comment]
@bilelmoussaoui It does come up, for example, in bug repro scenarios, where it's typically required to name the exact ID and even commit rather go with "search for so-and-so app on this Software thing".

> See https://flathub.org/apps/details/com.amazon.Workspaces for example.

That's another repack of the official shipped binaries, so it falls in with `com.visualstudio.code` and similar cases (i.e. lawyers might still come knocking, but at least it's clear who's shipping and supporting the original software).

**Comment by bilelmoussaoui** [comment]
The issue here is that the application can't be re-distributed by Flathub, which we don't do. The official binary is only downloaded on the user's machine when they install it. See https://github.com/flathub/com.visualstudio.code/blob/master/com.visualstudio.code.yaml#L88-L93  and https://github.com/flathub/com.visualstudio.code/blob/master/com.visualstudio.code.yaml#L88-L93 the apply-extra script is executed on install.

**Comment by mzabaluev** [comment]
@bilelmoussaoui
> The official binary is only downloaded on the user's machine when they install it.

Good. Now what about this `com.visualstudio.code-oss` app from #1596? Which organization publishes and distributes it?

**Comment by bilelmoussaoui** [comment]
The app-id != the publisher. I have already said that before. It's a unique identifier of the app, nothing more.

**Comment by bilelmoussaoui** [comment]
Also I'm more inclined in not including the OSS build of VSCode, it will just end up not maintained in few weeks :/

**Comment by mzabaluev** [comment]
Err, that's not the kind of supportive attitude towards prospective app developers that I was hoping for.

**Comment by gasinvein** [comment]
> it will just end up not maintained in few weeks

Oh, didn't know this. Should I retire it right now, so you won't need to wait for a few weeks?

**Comment by bilelmoussaoui** [comment]
> > it will just end up not maintained in few weeks
> 
> Oh, didn't know this. Should I retire it right now, so you won't need to wait for a few weeks?

That's not what I said. Maintaining a custom build of VSCode isn't an easy task, if you want to put your efforts and time on it, feel free to do so

**Comment by gasinvein** [comment]
That's exactly what you said:
>I'm more inclined in not including the OSS build of VSCode

**Comment by gasinvein** [comment]
Anyway, I believe maintaining VS Code OSS is way, way easier now since the flatpak-node-generator received a plenty of improvements, including some vscode-specific. Latest update was as easy as bumping version and re-generating sources. So I'll continue to use and maintain it, just not on Flathub.

**Comment by barthalion** [comment]
Please keep discussion under the respective pull request. I don't think there's anything more to discuss here; we won't be distributing applications as `org.flathub`.
