### ISSUE TITLE
Proposal for chat programs using filesystem=home

### ISSUE THREAD

**Issue by lionirdeadman** [flathub/flathub#1652]
This would affect :
- https://github.com/flathub/org.signal.Signal
- https://github.com/flathub/network.loki.Session
- https://github.com/flathub/com.mattermost.Desktop
- https://github.com/flathub/com.wire.WireDesktop
- https://github.com/flathub/org.gnome.Fractal
- https://github.com/flathub/info.mumble.Mumble

(Maybe more, I simply checked those using filesystem=home)

Instead of using :
`filesystem=home`
They should use : 
`filesystem=home:ro`
`filesystem=xdg-download`

Why?

All of these need $home only for sharing files and they usually need downloads if they want to write something, there's no need from what I can tell to need full home read & write. (Note : I think Fractal could probably just use the portals for that because it's GTK?)

**Comment by bilelmoussaoui** [comment]
There's a merge request to make electron uses GtkNativeFileChooser. I prefer having the apps being usable by the users rather than enforcing the sandboxing and cause data loss for users.

**Comment by lionirdeadman** [comment]
I don't see how my proposal would create data loss. Mind expanding on that?

Also, of course portals are better but I don't expect most of these apps to jump to that newer version, they tend to use older versions for a bit.

**Comment by bilelmoussaoui** [comment]
Fractal is already using the portal iirc, the home access could be removed. For other applications, this should be discussed with the maintainers of the various applications.

**Comment by muelli** [comment]
> I don't see how my proposal would create data loss. Mind expanding on that?

I guess a scenario is that the user expects to receive or download a file which then can't be written. If the app handles that case poorly, then the file is potentially lost.

Have you considered bringing this up with the respective apps? That feels like a better place to discuss the implications of such a change.

**Comment by lionirdeadman** [comment]
Actually, considering most are electron based and Fractal is not longer valid. I've decided to just on Zypak to finish their work on the native file picker to portal file picker. Of course, this will require testing before-hand to make sure nothing is broken.

**Comment by bilelmoussaoui** [comment]
This can be closed, feel free to open specific issues per app if needed. The Electron ones requires changes on electron itself & for the apps to update to that newly released version once it's out. Nothing we can do from our side for now.
