### ISSUE TITLE
Add organization as collaborator to repository

### ISSUE THREAD

**Issue by fcastilloec** [flathub/flathub#1678]
I recently became a collaborator to [co.headsetapp.headset](https://github.com/flathub/co.headsetapp.headset) but I was wondering if there's a way to add an organization as collaborators ([headsetapp](https://github.com/headsetapp)).
I'm guessing that any owners and members from the organization would be automatically added as collaborators to flathub, even if new ones are added later on.

**Comment by bilelmoussaoui** [comment]
I don't think github allows such thing. Do you have a list of the members you want us to add?

**Comment by barthalion** [comment]
I asked @fcastilloec to open a bug as I plan to tackle that with a GitHub Action.

**Comment by fcastilloec** [comment]
In the meantime, could you add @danielravina?

**Comment by barthalion** [comment]
Done.
