### ISSUE TITLE
error when downloading geogebra : Server returned status 404: Not Found 

### ISSUE THREAD

**Issue by joergister** [flathub/flathub#168]
I know this is not the right place to report this, but I already reported it on https://github.com/flathub/org.geogebra.GeoGebra/issues/7 6 days ago and there was no reaction. 
If this is usual, just tell me and I will wait longer next time. Perhaps I'm too impatient. Tell me if I am. 

Typing

    ` flatpak install --from https://flathub.org/repo/appstream/org.geogebra.GeoGebra.flatpakref`

results in

`    Fehler: Während des Herunterladens von https://download.geogebra.org/installers/5.0/GeoGebra-Linux-Portable-5-0-392-0.tar.bz2: Server returned status 404: Not Found`

which means

`     Error: When downloading from https://download.geogebra.org/installers/5.0/GeoGebra-Linux-Portable-5-0-392-0.tar.bz2: Server returned status 404: Not Found`

Looks like Geogebra was updated to version 5.0.400 since this link now works https://download.geogebra.org/installers/5.0/GeoGebra-Linux-Portable-5-0-400-0.tar.bz2

**Comment by nedrichards** [comment]
You certainly should've received an update on that ticket more quickly. I've opened a pull request that should fix the issue, and it's test building right now.
