### ISSUE TITLE
[RFE] Provide integration with abrtd

### ISSUE THREAD

**Issue by maci0** [flathub/flathub#169]
Hi, it would be great if we would have an abrtd plugin to automatically upload coredumps to a remote system and get stacktraces along with opening a new issue/adding to an identical one.
The same way it currently works for rpm packages on fedora.

Currently abrtd does capture crashes and save coredumps etc, but there is no easy way to get proper stack traces with debugging symbols. Within the crash directory that abrtd currently creates there a plenty of flatpak references. The plugin would then need to look up which package the binary came from, which repository, and in case its a known one (e.g. flathub, gnome), do the same magic it does for rpm packages.

**Comment by nedrichards** [comment]
This sounds like an issue for the [flatpak](https://github.com/flatpak/flatpak) repo, rather than flathub.

**Comment by maci0** [comment]
ok, recreated there https://github.com/flatpak/flatpak/issues/1222
