### ISSUE TITLE
docs: PRs against new-pr branch

### ISSUE THREAD

**Issue by kparal** [flathub/flathub#170]
Hello,
it's not clear that new PRs should be posted against the `new-pr` branch. Can you please make it clear in https://github.com/flathub/flathub/wiki/Review-Guidelines#review-process ? Or in case this is not correct, please state the correct target branch there.

Thanks.

**Comment by TingPing** [comment]
It is mentioned here: https://github.com/flathub/flathub/wiki/Submission-Guidelines

**Comment by kparal** [comment]
That's good to know. However, it's not linked from anywhere. Main README from https://github.com/flathub/flathub only links https://github.com/flathub/flathub/wiki/Review-Guidelines . That itself doesn't link to https://github.com/flathub/flathub/wiki/Submission-Guidelines , instead it has its own section of `
Review process`. I suggest these two documents should be merged, or logically interlinked.

**Comment by TingPing** [comment]
This has also been added to a CONTRIBUTING file: https://github.com/flathub/flathub/blob/master/CONTRIBUTING.md

**Comment by kparal** [comment]
Great. But still, most people will only read the main README, and not hunt for other files available in the repository. So CONTRIBUTING should get linked from README, if people are to find it.
