### ISSUE TITLE
[RFE] Create a list of top apps missing on Flathub

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/flathub#176]
I think it could be a good idea to make a list of most wanted applications that are missing on Flathub.

For example, my list would be:
- [Chrome](https://www.google.com/chrome/)
- [Kodi](https://kodi.tv)
- [PlayOnLinux](https://www.playonlinux.com/en/)
- [Red Eclipse](https://redeclipse.net)
- [Xonotic](http://www.xonotic.org)
- [Tor Browser](https://www.torproject.org/projects/torbrowser.html.en)
- [Gqrx](http://gqrx.dk)
- [LyX](https://www.lyx.org)

**Comment by manuq** [comment]
I only have one:
- emacs

**Comment by nedrichards** [comment]
This sounds like an interesting wiki page, especially if it could co-ordinate outreach, packaging help and evangelism for the projects concerned. A pure list would be less useful. Feel free to add it to the wiki.

**Comment by RoyiAvital** [comment]
@nedrichards , The problem the Wiki isn't available for editing (I wanted to create such page).

**Comment by antistress** [comment]
I'd also love to see a flatpak for Brasero,
And I'd add to the list : [DevedeNG](https://gitlab.com/rastersoft/devedeng/-/issues/82) & [Imagination](https://sourceforge.net/p/imagination/bugs/87/)

**Comment by AsciiWolf** [comment]
I remember using Devede (the original one) 20 years ago. Thanks for bringing back the nice memories of making family videos! :-)
