### ISSUE TITLE
Will flathub provide installation statistics?

### ISSUE THREAD

**Issue by Jehan** [flathub/flathub#177]
In GIMP, we don't have any statistics, especially since that is installed from so many different place.

I think this would be useful information though (even though we'd have to gather them from various sources), as long as these statistics are fully anonymized of course. This point is extremely important.

Will flathub provide any such installation/update statistics?
Thanks!

**Comment by TingPing** [comment]
It is planned and basic numbers can already be extracted from the logs (total downloads/unique IPs per app). This just needs to be exposed in some form which might come after we have a new flathub web store.

**Comment by Jehan** [comment]
Awesome.

**Comment by nedrichards** [comment]
In the interim, if you'd like an update on your apps stats, ask on IRC @alexlarsson is happy to share the info!

**Comment by sudden6** [comment]
Has there been any progress on this matter?

**Comment by ahayzen** [comment]
There is a task here about providing statistics within flathub.org https://github.com/flathub/linux-store-frontend/issues/19

**Comment by SilverRainZ** [comment]
How is it going now? :D

**Comment by Eonfge** [comment]
I've had questions from Upstream projects concerning download statistics. If I can provide them with rough numbers on download statistics, they can judge if Flathub is a worthy platform to support directly. 

I think we're missing a big marketing opportunity here towards upstream developers, because they want to serve as many users as possible with as little effort as possible. This will likely be even more important for commercial products, for whom install bases need to be financially viable.

**Comment by Jehan** [comment]
For the record, though Flathub does not have official/easy interface to provide statistics (as far as I know; hence this report is still opened), I did realize they already provide daily statistics file in json format, just waiting to be processed. For our needs (on GIMP, so it's more of curiosity than real needs, since we don't care about "commercial" or "opportunities", it's just fun to see how many people download GIMP) I made a quick shell script to process the json files. It's very basic, and basically just tells you how many people downloaded since the last update (or the update before, or again before…) with a per-arch break.

It's here: https://gitlab.gnome.org/Jehan/gimp-flathub-stats

Example run:

```
$ ./flathub-stats org.gimp.GIMP
Counting updates between 2019-09-02 20:28:05 +0000 and 2019-09-25 11:52:25+02:00:
........................ done!

x86-64 (98%): 62928 downloads including 61801 updates
i386 (1%): 953 downloads including 783 updates
aarch64 (0%): 56 downloads including 12 updates
Arm (0%): 86 downloads including 46 updates

Total:   64023 downloads in 24 days
Average: 2667 downloads per day
```

I think this kind of script could be enough for now for people waiting for more. :-)

P.S.: and patches are welcome if anyone wants to improve the script to generate graphs or whatnot.

**Comment by ahayzen** [comment]
FWIW I have a tool that is able to generate graphs for apps here https://gitlab.com/ahayzen/flathub-api-stats-generator

For example it is able to generate a graph of the downloads of GIMP using the following command `python3 main.py --report downloads_by_app --type graph --output out.png --report-args app-id=org.gimp.GIMP` this then generates the following graph (note you can set a `--cache-dir /tmp/cache-dir --model-skip-today` so the model doesn't have to be redownloaded)

![gimp](https://user-images.githubusercontent.com/3669750/65719329-85c0c080-e09d-11e9-984d-7f73d8024231.png)

**Comment by dreua** [comment]
Can someone clarify what the numbers from https://flathub.org/stats/ mean? 
(e.g. `"com.github.jeromerobert.pdfarranger": {"x86_64": [392, 377]}`)
Platform is obvious, but what is the meaning of the two values? My guess would be first: Total downloads including delta downloads; Second: Only delta downloads. Is this correct? Would it be reasonable to call the difference between the two something like "new installations" and plot that instead of delta downloads?

**Comment by TingPing** [comment]
@dreua When a user updates it *may* be a delta update and it may not. We don't know the distinction between new installs and updates always.

**Comment by klausenbusk** [comment]
I just spent some time creating a simple javascript stat page: https://klausenbusk.github.io/flathub-stats/ (source here: https://github.com/klausenbusk/flathub-stats).

It is just a simple [python script](https://github.com/klausenbusk/flathub-stats/blob/982130b7c91c8a8a36a7f5baac4167a7a10fa6fa/pull_stats.py), which pull the stats from `https://flathub.org/stats/` and transform them into a json file per ref + a little javascript to show the data. The data is pulled every 12 hour.

**Comment by razzeee** [comment]
I'll close this, as we have been showing this data on flathub.org for some time now
