### ISSUE TITLE
Automatically archive EOLed repos

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/flathub#1783]
Currently we need to manually archive a repository once the maintainer marked it as EOL. I wonder if we can automate that somehow using Github Actions.

**Comment by barthalion** [comment]
I thought about this in the past but there were apps which we had to un-EOL already. When repository is archived, maintainer cannot unarchive it without admins.

**Comment by bilelmoussaoui** [comment]
Right, but that happens less often

**Comment by bbhtt** [comment]
Solved via https://github.com/flathub/flathub/pull/5381
