### ISSUE TITLE
Elementary OS theme

### ISSUE THREAD

**Issue by giovannicaligaris** [flathub/flathub#180]
Would it be possible to add the Elementary OS default theme? Is the only thing that stops me from using Flatpak applications.

**Comment by MrMarukesu** [comment]
elementary theme is gtk 3.18 for now, and flatpak Gtk3 themes are 3.22. So when Juno comes it begin possible.
Anyway, it's a manifest [here](https://github.com/MrMarukesu/org.gtk.Gtk3theme.elementary) for test that use the 3.22 WIP. if you know how uses flapak-builder, you can use it

**Comment by giovannicaligaris** [comment]
Maybe I am wrong, but the elementary theme has support for gtk 3.22

https://github.com/elementary/stylesheet

I tried it in Ubuntu 17.10 which is gtk 3.24 and it works fine.

**Comment by TingPing** [comment]
The linked manifest seems fine at a glance, so feel free to open a request whenever.

**Comment by MrMarukesu** [comment]
done, pr opened #181

**Comment by TingPing** [comment]
Added: https://github.com/flathub/org.gtk.Gtk3theme.elementary
