### ISSUE TITLE
Does the "check if external data changed" action cover all flatpaks?

### ISSUE THREAD

**Issue by jakobjakobson13** [flathub/flathub#1820]
Hi,

I have the suspicion that not all flatpak manifests are checked for newer data. The reason for this suspicion is that searching the last three log files [flatpak action log](https://pipelines.actions.githubusercontent.com/mCUvq7rgOSBwrPLUYFpYrHe3JkGLgask3prA0yHJLcY9vP0PzM/_apis/pipelines/1/runs/19404/signedlogcontent/3?urlExpires=2020-09-11T15%3A42%3A47.2924035Z&urlSigningMethod=HMACV1&urlSignature=BT71m%2FS6L9bIFLP5lUWujdo71Nu%2BEKj0f9qpZkAcLVk%3D) for the pattern `==> checking` returns only 48 matches even though in the beginning of the files 1287 repositories are cloned.

Am I mistaken or is the check of the manifests aborted too early?

Regards

**Comment by barthalion** [comment]
The manifest needs to have `x-checker-data` specified. We don't run it on all apps in "check checksums" mode as described in the tool's README.

**Comment by jakobjakobson13** [comment]
So I just have to be a bit more patient till the [golang](https://github.com/flathub/org.freedesktop.Sdk.Extension.golang/blob/branch/20.08/org.freedesktop.Sdk.Extension.golang.yaml) manifest will get updated?

**Comment by barthalion** [comment]
The other catch is that only the default branch is processed. I can change it for golang. I need to admit that the way external-data-checker is triggered needs some work.

**Comment by jakobjakobson13** [comment]
> The other catch is that only the default branch is processed.

Okay, there is the catch. Thank you very much.
