### ISSUE TITLE
Corrupt file object in org.gnome.Sdk/3.38

### ISSUE THREAD

**Issue by Zokormazo** [flathub/flathub#1850]
I'm getting corrupt data download org.gnome.Sdk//3.38

```
Error: While pulling runtime/org.gnome.Sdk/x86_64/3.38 from remote flathub: opcode open-splice-and-close: opcode close: Corrupted file object; checksum expected='47347db08c3e959cfaad3c37f38cfd9843fc9c1200afec0e735d6a116dd0643e' actual='dcd682e6f6df1c08cc478c995a704c7af7a4b48f09d10a6f26c78c1695e43363'
error: Failed to install org.gnome.Sdk: While pulling runtime/org.gnome.Sdk/x86_64/3.38 from remote flathub: opcode open-splice-and-close: opcode close: Corrupted file object; checksum expected='47347db08c3e959cfaad3c37f38cfd9843fc9c1200afec0e735d6a116dd0643e' actual='dcd682e6f6df1c08cc478c995a704c7af7a4b48f09d10a6f26c78c1695e43363'
```

**Comment by sumnerevans** [comment]
I'm also seeing this issue as well on a sourcehut build: https://builds.sr.ht/~sumner/job/306810#task-build-flatpak-173

**Comment by subjectdenied** [comment]
same here

**Comment by TheEvilSkeleton** [comment]
Is there a public repo for it? I don't know where Flatpak SDK/runtime repos are located

**Comment by TheEvilSkeleton** [comment]
[Sad, `org.gnome.Sdk/3.38` isn't available in Flathub's repo](https://github.com/flathub?q=sdk&type=&language=)

**Comment by vilgotf** [comment]
Run `sudo flatpak repair` or `flatpak --user repair`, fixed it for me :grin:

**Comment by TheEvilSkeleton** [comment]
That didn't seem to work for me :(

**Comment by barthalion** [comment]
The from-scratch delta contained a corrupted object and has been removed from the server. If you downloaded it before, you can try installing the SDK with `flatpak install --no-static-deltas`.

**Comment by barthalion** [comment]
Note you may need to run `flatpak repair` before the command above.

**Comment by hughsie** [comment]
This fixed it for me, thanks.
