### ISSUE TITLE
[Question] What to do with end of life run time ?

### ISSUE THREAD

**Issue by Nokia808** [flathub/flathub#1853]
Hi.

I have 2 end of life run time on my system - see screenshot bellow:

![end-of-life](https://user-images.githubusercontent.com/25375330/94275762-e72ca100-ff36-11ea-8cb0-0177416af92c.png)

But from time to time receiving update ! - see above screenshot also.

When I run "flatpak uninstall unused" it shows me "no thing unused to be removed".

I'm on Fedora 32 X64 bit Cinnamon edition with flatpak version 1.8.2

**Comment by bilelmoussaoui** [comment]
You should report an issue to the application that still uses that old runtime.
