### ISSUE TITLE
[Question] How to gain push access to a repository?

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/flathub#1855]
Hello, I've submitted some merge request (fixes) in https://github.com/flathub/us.zoom.Zoom, but the problem is that the maintainer(s) is/are not active.

- https://github.com/flathub/us.zoom.Zoom/pull/212
- https://github.com/flathub/us.zoom.Zoom/pull/213

I'm asking this because Zoom is often used by students and teachers. Having late fixes is a big problem for those that want to use the Flatpak, which is why I would like to have push access so they can be pushed (and fixed) as soon as possible. And since it's unusable for users, they will be forced to use a non sandboxed version of Zoom or spend the time tinkering the sandbox.

**Comment by barthalion** [comment]
I don't mind giving you push access there, just please make sure to get a review from someone with larger experience. Current maintainer is @muelli but I remember @nanonyme having some feedback here and there in the past. I also use Zoom somewhat daily but I'm sometimes busy with non-Flathub affairs.

WDYT @muelli?

**Comment by muelli** [comment]
Reg. pushing fixes sooner: I'd say that when it comes to education and important stuff, changes ought to be tested very well, before hitting users who will have better things to do than debug and fix their installation.

Reg. access: I don't particularly mind giving more people access. But maybe the Zoom app is not the best "my first flathub app" to maintain. We have an audit trail what has changed by whom, so we can revert easily in case we notice some breakage. So we can fix things relatively easily, if needed. However, I haven't had the feeling that pushing the "merge" button of a ready-to-go MR has been the blocker, so far.

**Comment by TheEvilSkeleton** [comment]
> Reg. pushing fixes sooner: I'd say that when it comes to education and important stuff, changes ought to be tested very well, before hitting users who will have better things to do than debug and fix their installation.

Fair point

**Comment by TheEvilSkeleton** [comment]
Maybe opening a new branch could help? For example a beta branch or something? That could help us test.

**Comment by muelli** [comment]
yeah, absolutely. Just create MRs against the beta branch.

**Comment by TheEvilSkeleton** [comment]
Can I gain push access to the beta branch so I can start testing in my free time?

**Comment by nanonyme** [comment]
Slight nitpick: beta branch is not different from master in terms of PR's. It may be actively used by someone and it's best to go through PR CI for all changes in order for it not to end up in broken state. PR CI also provides early test builds.

**Comment by TheEvilSkeleton** [comment]
> Slight nitpick: beta branch is not different from master in terms of PR's

I'm aware of that, which is why I upstreamed it and starting submitting MRs there.

> It may be actively used by someone and it's best to go through PR CI for all changes in order for it not to end up in broken state. PR CI also provides early test builds.

Are PR CI the Flathub bot that builds and provides test builds? I'm not sure what those are.

**Comment by muelli** [comment]
> Are PR CI the Flathub bot that builds and provides test builds? I'm not sure what those are.

yes, I think that's what is being referred to.

**Comment by TheEvilSkeleton** [comment]
I'm aware of that, which is why I wouldn't mind having push access only to the beta branch, so I can start extensively testing it.
