### ISSUE TITLE
Request to maintain net.lutris.Lutris

### ISSUE THREAD

**Issue by A6GibKm** [flathub/flathub#1866]
https://github.com/flathub/net.lutris.Lutris is currently without a maintainer. 

I would like to maintain it if the Flathub administrators are OK with it. I am not qualified to troubleshoot some issues beyond upgrading the manifest when updates are available, but in my humble opinion this is miles better than having no maintainer at all.

cc @barthalion, @gasinvein.

**Comment by barthalion** [comment]
Invitation sent.
