### ISSUE TITLE
please unarchive org.fdroid.Repomaker

### ISSUE THREAD

**Issue by eighthave** [flathub/flathub#1877]
@AltNico retired as the maintainer for _org.fdroid.Repomaker_.  I'm working now on getting it production ready and easier to maintain.  Please unarchive _org.fdroid.Repomaker_: https://github.com/flathub/org.fdroid.Repomaker/issues/6

Fixes for https://github.com/flathub/org.fdroid.Repomaker/issues/5 and https://github.com/flathub/org.fdroid.Repomaker/issues/4 are already working on my machine.

**Comment by bilelmoussaoui** [comment]
Done

**Comment by AltNico** [comment]
@bilelmoussaoui Thanks for the quick reaction! I hereby confirm that I retired as maintainer of Repomaker. Could you give @eighthave push access to https://github.com/flathub/org.fdroid.Repomaker so that he can update Repomaker? Thank you!

**Comment by bilelmoussaoui** [comment]
Done as well
