### ISSUE TITLE
Support TLS 1.3 on flathub.org

### ISSUE THREAD

**Issue by kmwyard** [flathub/flathub#1906]
Flathub currently use [TLS 1.2 and support TLS 1.0 and TLS 1.1.](https://www.ssllabs.com/analyze.html?d=flathub.org&s=2a00%3a1098%3a88%3a12%3a0%3a0%3a0%3a1&latest) It makes download flatpak packages slow and insecure. If flathub.org support TLS 1.3 and deprecating TLS 1.0 and TLS 1.1, TLS 1.2, It could safer and faster downloading.

**Comment by barthalion** [comment]
It's up to the client to negotiate available protocols; if for whatever reason someone is stuck with libraries which do not speak TLS 1.3 or 1.2, I don't see a reason to lock them out from accessing our website.

The actual downloads are served from dl.flathub.org and it supports TLS 1.2 only; I don't see why it would affect security or download speed as flatpak/ostree also does signature and checksum checking.

**Comment by kmwyard** [comment]
TLS 1.1 and TLS 1.0 are dangerous to use. If someone is stuck in a version lower than TLS 1.1, we have to tell them that they upgrade to a system that supports TLS 1.2 or higher and stop using old encryption protocols. And TLS 1.3 is more secure and [faster than TLS 1.2, TLS 1.1, TLS 1.0](https://netflixtechblog.com/how-netflix-brings-safer-and-faster-streaming-experience-to-the-living-room-on-crowded-networks-78b8de7f758c?gi=bd3d04fded78).

**Comment by kmwyard** [comment]
@barthalion TLS 1.1 and TLS 1.0 are dangerous to use. If someone is stuck in a version lower than TLS 1.1, we have to tell them that they upgrade to a system that supports TLS 1.2 or higher and stop using old encryption protocols. And TLS 1.3 is more secure and [faster than TLS 1.2, TLS 1.1, TLS 1.0](https://netflixtechblog.com/how-netflix-brings-safer-and-faster-streaming-experience-to-the-living-room-on-crowded-networks-78b8de7f758c?gi=472925715a65).
