### ISSUE TITLE
Provide Wine runtime

### ISSUE THREAD

**Issue by prcastro** [flathub/flathub#191]
Hi. I was thinking about packaging free Windows apps (e.g. Kindle Reader) as Flatpaks. However, maintaining Wine is a bit painful. It would be cool if Flathub provided a runtime (or a base flatpak just like Electron) containing a Wine distribution.

**Comment by TingPing** [comment]
Here is an example of building Wine btw: https://github.com/TingPing/flatpak-packages/blob/master/info.cemu.Cemu.json#L14-L82

I found it fairly simple tbh.

**Comment by Barthalion** [comment]
I'm not sure if we want to spend time on this now, given that especially games often work best only with particular versions of Wine.

**Comment by TingPing** [comment]
I'm also not sure we want wine'd applications on Flathub in general: They are largely unsupportable compared to normal software; If the software regresses and stops working in wine who is going to fix that, they  integrate with the desktop less consistently, and they will probably never support Flatpak portals.

**Comment by nedrichards** [comment]
Yeah, unless there's a development team who want to bring their Windows app to Linux using Wine (and who would benefit from a baseapp potentially) then I'm not sure that Windows apps on flathub are a great fit for the mission. Given that this scenario fits a bunch of games available on Steam, I don't think it's terribly unlikely - but I'm not aware of a team clamouring for it right now.

Personally I'd be happy to take something like a PlayOnLinux or similar onto Flathub but ymmv and even that's not a great fit for an immutable container.

**Comment by TingPing** [comment]
> Personally I'd be happy to take something like a PlayOnLinux or similar onto Flathub but ymmv and even that's not a great fit for an immutable container.

Yea I have an app like that (and upstream is interested): https://github.com/TingPing/flatpak-packages/blob/master/net.lutris.Lutris.json

Though I've been discussing with that developer the opposite approach of using Flatpaks for applications not for itself, so each game can have its own wine runtime.

**Comment by adityashah1212** [comment]
Agreed packaging wine would be more effort than the what it is worth. But we can definitely package something like playonlinux

**Comment by amtlib-dot-dll** [comment]
Wine does not provide adequate isolation, and Flatpak may be used as a simple wrapper of bubblewrap.
