### ISSUE TITLE
Build gets stuck in loop

### ISSUE THREAD

**Issue by rderooy** [flathub/flathub#1913]
A new version of https://github.com/flathub/com.dosbox_x.DOSBox-X was released today so I updated the yaml file with the latest release version. However the build is getting stuck in a loop between configure and make, and I'm not sure why.

You can see such a build here that I stopped
https://flathub.org/builds/#/builders/48/builds/3695/steps/6/logs/stdio

I run into the same issue when building it locally. I'm suspecting a timestamp problem. I switched locally from the implied buildsystem=autotool to buildsystem=simple and specified the build-commands, and I can see the transition from configure to make and back to running configure.

```
...
config.status: creating config.h
config.status: executing depfiles commands
Running: make
make: Warning: File 'Makefile.am' has modification time 1275 s in the future
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /run/build/dosbox-x/missing aclocal-1.16 
 cd . && /bin/sh /run/build/dosbox-x/missing automake-1.16 --foreign
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /run/build/dosbox-x/missing autoconf
/bin/sh ./config.status --recheck
running CONFIG_SHELL=/bin/sh /bin/sh ./configure --enable-core-inline --enable-debug=heavy --enable-sdl2 CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection --no-create --no-recursion
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
...
```

**Comment by rderooy** [comment]
Just a a test, I explicitly set ``buildsystem=autotools`` locally and it now builds. So I made the same change to the yaml in the com.dosbox_x.DOSBox-X repo and it now seems to be proceeding.

The issue seems to the the "missing autoconf", and explicitly specifying the buildsystem allows it to continue.

**Comment by rderooy** [comment]
successful build: https://flathub.org/builds/#/builders/32/builds/31521

**Comment by rderooy** [comment]
p.s. how long does it take from pressing "publish" before it is really available? Both https://flathub.org/apps/details/com.dosbox_x.DOSBox-X and running flatpak install... still has the old version as of writing.

**Comment by barthalion** [comment]
The default publishing delay is 3 hours. This way we can batch multiple builds and save some IO, and also give maintainers possibility to test the build.

You should be able to login at https://flathub.org/builds/#/ via top right corner with your GitHub account. Once logged in, you can manually publish builds.
