### ISSUE TITLE
https://github.com/flathub/de.ifw_dresden.nagstamon is not updating to new release

### ISSUE THREAD

**Issue by HenriWahl** [flathub/flathub#1917]
Hi there,

after finding out how to add a new release version I see that there still is no update available at https://flathub.org/apps/details/de.ifw_dresden.nagstamon.

The build on version 3.4.1 run successfully - what am I missing?

Thanks for any hint.

**Comment by HenriWahl** [comment]
Well - is updated now. Does it just take some time?

**Comment by bilelmoussaoui** [comment]
Yes, the default publishing time is ~3 hours, you can login in https://flathub.org/builds with your github account, select the build & hit publish if you want it out as soon as it's built.

**Comment by HenriWahl** [comment]
Thank you for the info!
