### ISSUE TITLE
Builds fail at "Install/update flat-manager-client" step

### ISSUE THREAD

**Issue by Hofer-Julian** [flathub/flathub#1919]
All builds are currently failing at the "Install/update flat-manager-client" step.
The build log of one of the builds looks like this https://flathub.org/builds/#/builders/32/builds/31690

**Comment by barthalion** [comment]
Yeah, I noticed it yesterday and also retriggered failed jobs after fixing. Sorry for the trouble.

**Comment by Hofer-Julian** [comment]
Thanks for fixing it so quickly 😊
