### ISSUE TITLE
Enable kerberos in Firefox

### ISSUE THREAD

**Issue by djasa** [flathub/flathub#1923]
Fedora flatpak enabled kerberos in firefox some while ago, it would be nice if Flathub follows suit.

* RHBZ bug: https://bugzilla.redhat.com/show_bug.cgi?id=1699235
* related change: https://gitlab.gnome.org/GNOME/gnome-build-meta/-/merge_requests/389

Flathub Firefox:
version: 82.0.2
commit: c264acc4a8f2266f11169f6caa5a656ceab84949472fe6ebfa8ab33795447183

**Comment by barthalion** [comment]
Please report it on Mozilla's bug tracker. Mozilla maintains Firefox on Flathub.
