### ISSUE TITLE
build fails gcc not working on x86_64

### ISSUE THREAD

**Issue by joelkraehemann** [flathub/flathub#1926]
See here:

https://flathub.org/builds/#/builders/19/builds/3792

and here:

https://github.com/flathub/org.nongnu.gsequencer.gsequencer/pull/86

by Joël

**Comment by barthalion** [comment]
I have talked with GNOME runtime maintainers and it seems to be caused by silent ABI breakage after recent freedesktop-sdk release – specifically one of the extensions affects also GNOME runtime. I'll keep you posted.

**Comment by barthalion** [comment]
The root cause is being tracked at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1155. For the time being the extension has been masked on runners. I retriggered gsequencer (and other) jobs.

**Comment by neatdecisions** [comment]
Hi @barthalion , it seems that https://flathub.org/builds/#/builders/35/builds/3806 is still broken (looks like due to the same issue). Do you think there's anything we can do here?

**Comment by barthalion** [comment]
Bad timing, I guess? I started a new build for it at https://flathub.org/builds/#/builders/32/builds/32266 and so far it looks good.

**Comment by neatdecisions** [comment]
Indeed, thanks! :)

**Comment by bilelmoussaoui** [comment]
I guess this can be closed now
