### ISSUE TITLE
Show supported architecture/OS (like ARM/Raspberry Pi OS)

### ISSUE THREAD

**Issue by swschilke** [flathub/flathub#1942]
Hallo, similar to Snapcraft (.io) it would be good to see and be able to filter depending on the supported architecture/OS (like ARM/Raspberry Pi OS).

Regards

.

**Comment by nedrichards** [comment]
Agreed, it would be - this is more of an issue for the website backend https://github.com/flathub/backend and the new UI as well.

**Comment by swschilke** [comment]
Thank you - I opened an issue there (as well).

**Comment by razzeee** [comment]
Closing. We have been showing the arch for some time now.
