### ISSUE TITLE
Provide version information

### ISSUE THREAD

**Issue by Pointedstick** [flathub/flathub#195]
The metadata available for Flathub apps doesn't seem to include the version of the app. This seems like important information. In addition to the general usefulness of this information, here's a specific cases I encountered in which it would have been useful to know an app's version:

The Flathub version of Lollypop (0.9.305) is lower than the version I had available via a PPA on my system, but I didn't know that. Using the earlier Flathub version of Lollypop exposed me to [a bug](https://gitlab.gnome.org/gnumdk/lollypop/issues/1310) that had already been fixed in the later 0.9.306 version. Had I known that the Flathub version was only 0.9.305, I would have stuck with the newer PPA package until Flathub got a newer version.

**Comment by TingPing** [comment]
Please report these against the specific applications: https://gitlab.gnome.org/gnumdk/lollypop/issues

It is in our recommendations that applications have them: https://github.com/flathub/flathub/wiki/Review-Guidelines#desktop-integration

**Comment by Pointedstick** [comment]
Thanks, in progress:
- Lollypop: https://gitlab.gnome.org/gnumdk/lollypop/issues/1313
- Inkscape: https://bugs.launchpad.net/inkscape/+bug/1739898
- Endless Sky: https://github.com/endless-sky/endless-sky/pull/3455
- Blender: https://developer.blender.org/T53611
- Telegram: https://github.com/telegramdesktop/tdesktop/pull/4230
- [Will add more as I submit more patches]

I haven't found a single app that actually includes release information in their upstream AppStream metadata files. What do you think about making this property mandatory for Flathub?

**Comment by Pointedstick** [comment]
FWIW I'm getting a lot of pushback from the Telegram guys: https://github.com/telegramdesktop/tdesktop/pull/4230
