### ISSUE TITLE
Adding contributor to flathub repository

### ISSUE THREAD

**Issue by Mikunj** [flathub/flathub#1950]
We want to add a contributor to our flathub repository but we don't seem to have permissions for it. How would one go about adding them?

Here is the repository: https://github.com/flathub/network.loki.Session

**Comment by nedrichards** [comment]
Tell us what the github username for the person you want to add is and we will add them for you.

**Comment by Mikunj** [comment]
https://github.com/Bilb

**Comment by bilelmoussaoui** [comment]
I've sent an invitation, thanks!
