### ISSUE TITLE
post build unit tests with xvfb-run

### ISSUE THREAD

**Issue by giuspen** [flathub/flathub#1954]
Hi,
I have a post build command that runs the unit tests but needs xvfb-run https://flathub.org/builds/#/builders/32/builds/33356 - is it available somehow or the only way is to build the whole xorg stack myself

**Comment by barthalion** [comment]
Seems like no application bundles it yet. I don't think it would be difficult – most of the libs should be already in the runtime due to GTK3 presence.

**Comment by bbhtt** [comment]
It's used in flatpak-builder manifest, you can use that as an example https://github.com/flathub/org.flatpak.Builder/blob/master/xvfb.json
