### ISSUE TITLE
Add org.freedesktop.fldigi (help)

### ISSUE THREAD

**Issue by lu9dce** [flathub/flathub#1962]
Hi
Someone tells me that I have bad
because the bot checked only once and gave an error
I already corrected it and it is wait
What happens because it does not try to compile the manifest again

**Comment by bilelmoussaoui** [comment]
You can trigger a bot build yourself by commenting 
> bot, build org.freedesktop.fldigi

& there's no need to open an issue for this, a comment on your PR would have been enough. Also, you can just keep pushing to the same branch instead of closing the PR and opening a new one for each change. Thanks

**Comment by lu9dce** [comment]
ahh ok tks
