### ISSUE TITLE
Update review guidelines

### ISSUE THREAD

**Issue by nedrichards** [flathub/flathub#197]
We need to update the review guidelines to reflect some of the newer stances we've been enforcing (e.g. containment being actually encouraged, appstream metadata etc.) and maybe some more documentation as to actually what you need to do to make an app show up in app stores, since GNOME Software and appstream validate have different ideas.

**Comment by TingPing** [comment]
Added some info on app-id: https://github.com/flathub/flathub/wiki/Review-Guidelines#application-ids

So what else do we want from appstream?

- Releases should become mandatory
- OARS should become a recommendation
- 64/128 size icons should become mandatory

And what do we want for permissions?

- system/session bus access should be strongly discouraged unless its a development tool (d-feet).
- all configuration and data files for application should strongly be encouraged to stay within private directories (make note of `--persist` as an option)
- owning bus names are usually a mistake (main name should match app-id, few exceptions like MPRIS)

I think we have to stay pretty lax on filesystem/talk-name/device access for now sadly.

**Comment by nedrichards** [comment]
Agreed with all the above. I'd like to see something like 'any patches or changes should be pushed to the upstream project' as well.

**Comment by TingPing** [comment]
@nedrichards I've added a lot of details and combined the two guidelines into one, feedback would be appreciated: https://github.com/flathub/flathub/wiki/Package-Guidelines

**Comment by nedrichards** [comment]
I think this is a great move and the document is a big improvement.

The main missing bit here is about where and when to use shared_modules.

I think we could add a little bit about upstream involvement (e.g. the principle that they always get to own the repo if they want to) and adding some information about using PRs for test builds on the maintenance page but this makes expectations much more clear.

**Comment by nedrichards** [comment]
lgtm
