### ISSUE TITLE
Remove com.jvieira.tpt.Metronome

### ISSUE THREAD

**Issue by jvieir** [flathub/flathub#1976]
I would like to request the removal of the application com.jvieira.tpt.Metronome (I am the developer of the application).

**Comment by lu9dce** [comment]
This project is licensed under the GNU General Public License v3.0

https://gitlab.gnome.org/jopevieira99/metronome

**Comment by barthalion** [comment]
@lu9dce It's irrelevant; if upstream author wishes to remove it, we will do it.

@jvieir I will handle it tomorrow. Do you plan to resubmit it in the future?

**Comment by lu9dce** [comment]
@barthalion But then what is the use that the software is under a license
I withdraw the programs I made for flatpak

**Comment by barthalion** [comment]
@jvieir Should be done – it will be visible (or rather disappear) in few hours.

**Comment by jvieir** [comment]
> @jvieir I will handle it tomorrow. Do you plan to resubmit it in the future?

Yes, I do!


> @jvieir Should be done – it will be visible (or rather disappear) in few hours.

Thank you!

**Comment by jvieir** [comment]
> @barthalion But then what is the use that the software is under a license
> I withdraw the programs I made for flatpak
> 
> GPL (GNU Public License or General Public License): Basically it defends the access and modification of the code without restrictions, the freedom of distribution and the maintenance of this freedom

@lu9dce I'm am not just the developer of the app, I'm am also the person that was maintaining the application in the Flathub. I wanted to remove the app because I lost the access to the Github account I was using and also because the application repository changed. Also, I plan to resubmit the application in the future. I don't want to stop the "redistribution" off the app, it is the opposite.

@barthalion It looks like the build failed and the app is still visible...

**Comment by jvieir** [comment]
@barthalion It looks like it's still visible...
