### ISSUE TITLE
Installing from flatpak isn't intuitive

### ISSUE THREAD

**Issue by melodie11** [flathub/flathub#1982]
I have fixed my problem with the help provided 3 years ago here: https://github.com/flathub/flathub/issues/60

The issue I had was: 
```
$ flatpak install flathub com.gitlab.ColinDuquesnoy.MellowPlayer
Looking for matches…
error: No remote refs found similar to ‘flathub’
```
Why isn't flatpak a package? (Best guess I probably should ask this one to the Debian/Ubuntu devs).

**Comment by barthalion** [comment]
You mean why Flathub is not enabled by default? There are usually either legal reasons (a company not wanting to be responsible for what is available on Flathub) or philosophical ("use distro packages" or "use our flatpak remote").

Setup instructions are available at https://flatpak.org/setup/.
