### ISSUE TITLE
openal linux

### ISSUE THREAD

**Issue by lu9dce** [flathub/flathub#1984]
I have been testing several flatpaks that need openal
how to be minetest or openshare
everyone I tried gives me an error when they cannot create the device
for example if I go down and compile minetest it is perfect
but in the flatpak version it comes out without sound
checking the log
ERROR [Main]: Audio: Global Initialization: Failed to open device
I ask why I want to create a flatpak with contains openal
What is this error due to?
Is there any solution?
thanks !!
------------------
i use slackware 14.2
Would I have to add any permission to the groups for flatpak?

**Comment by barthalion** [comment]
You need to have PulseAudio installed for sound support.
