### ISSUE TITLE
Several flatpaks from FlatHub don't work in X11 session (Fedora 33)

### ISSUE THREAD

**Issue by valmar** [flathub/flathub#1985]
On Fedora 33, several flatpaks from FlatHub (For example, Foliate, NewsFlash) don't start anymore in the Xorg session (they work perfectly in the Wayland session).

Here are the error messages for these two applications (they both seem to be related to GTK)

```
> flatpak run com.github.johnfactotum.Foliate
Unable to init server: Could not connect: Connection refused
EGLDisplay Initialization failed: EGL_NOT_INITIALIZED
Portal call failed: Failed to start command: Failed to execute child process “dict” (No such file or directory)
Portal call failed: Failed to start command: Failed to execute child process “sdcv” (No such file or directory)
Unable to init server: Could not connect: Connection refused

(com.github.johnfactotum.Foliate:2): Gtk-WARNING **: 11:22:57.766: cannot open display: 
```
And

```
>flatpak run --env=RUST_BACKTRACE=1 com.gitlab.newsflash
Unable to init server: Could not connect: Connection refused
The application panicked (crashed).
Message:  Error initializing gtk.: BoolError { message: "Failed to initialize GTK", filename: "/run/build/newsflash/vendor/gtk/src/rt.rs", function: "gtk::rt", line: 129 }
Location: src/main.rs:57

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: __libc_start_main
    at <unknown source file>

```

Other flatpaks (for example, the ones which are electron-based) work fine both in Wayland and X11

I am opening this issue here because it seems to affect several flatpaks from FlatHub and seem to have a similar source. Please let me know if it would be better to open issues with the specific applications. 

Val

**Comment by barthalion** [comment]
It may sound silly but have you tried to reboot?

**Comment by valmar** [comment]
Yes, many times! I can also cycle through logout -> Wayland -> working -> login -> X11 -> not working -> and back

I would always use Wayland if possible, but some work-related software forces me to use X11 from time to time

Also, I thought the issue could be of general interest

Valeri

**Comment by barthalion** [comment]
It's already reported at https://github.com/flatpak/flatpak/issues/3880 but I'd say GDM should clean up the Wayland socket on session switch instead; either way it's not Flathub bug per se.

**Comment by valmar** [comment]
Thanks, and sorry for the duplicate report, I searched the issues before posting. Should I open a ticket with GDM (if it's not already there?)

Valerio

**Comment by valmar** [comment]
I opened an issue with GDM, which has now been transferred to gnome-session. Please see the comments of the GDM developers here:

https://gitlab.gnome.org/GNOME/gnome-session/-/issues/75
