### ISSUE TITLE
Meld Flatpak Fails in Fedora Silverblue 32 Toolbox Container

### ISSUE THREAD

**Issue by ziswiler** [flathub/flathub#1994]
Don't know what exactly changed but today flatpak is no longer able to launch stuff out of a toolbox container on Fedora Silverblue 32.

```
⬢[user@toolbox ~]$ cat /etc/fedora-release 
Fedora release 32 (Thirty Two)
⬢[user@toolbox ~]$ flatpak run org.gnome.Meld
bwrap: Can't find source path /run/user/1000/doc/by-app/org.gnome.Meld: No such file or directory
⬢[user@toolbox ~]$ ls -al /run/user/1000/doc/
total 0
drwx------.  2 user user  40 Dec 14 08:12 .
drwx------. 19 user user 540 Dec 14 08:17 ..
```

While in a regular shell it still works.

```
[user@localhost ~]$ cat /etc/fedora-release 
Fedora release 32 (Thirty Two)
[user@localhost ~]$ flatpak run org.gnome.Meld
[user@localhost ~]$ ls -al /run/user/1000/doc/by-app/org.gnome.Meld
total 0
dr-x------. 2 user user 0  1. Jan 1970  .
dr-x------. 2 user user 0  1. Jan 1970  ..
```

**Comment by barthalion** [comment]
I don't see how it's related to Flathub? Please report it to Silverblue team; also I wouldn't expect that flatpak will work completely fine directly in the toolbox, you probably want to run it directly on the host.

**Comment by ziswiler** [comment]
> I don't see how it's related to Flathub?

Well, Meld is a flatpak distributed on flathub, isn't it?

> Please report it to Silverblue team;

Yes, I tried doing so and will once their system lets me.

> also I wouldn't expect that flatpak will work completely fine directly in the toolbox, you probably want to run it directly on the host.

No, it worked just fine so far. But stopped working after some update.
