### ISSUE TITLE
Fix HTTPS security on flathub.org

### ISSUE THREAD

**Issue by stackmov** [flathub/flathub#1997]
[flathub.org supports insecure TLS 1.0 and TLS 1.1](https://www.ssllabs.com/ssltest/analyze.html?d=flathub.org&s=2a00:1098:88:12:0:0:0:1), and does not support [fast and secure TLS 1.3](https://netflixtechblog.com/how-netflix-brings-safer-and-faster-streaming-experience-to-the-living-room-on-crowded-networks-78b8de7f758c?gi=8ba6d4012ec4), whereas [snapcraft.io only supports secure protocols TLS 1.2 and TLS 1.3](https://www.ssllabs.com/ssltest/analyze.html?d=snapcraft.io&s=91.189.91.45). With flathub.org discontinuing support for TLS 1.0 and TLS 1.1 and supporting TLS 1.3, the security and privacy of Linux desktop users is enhanced. Would you mind deprecating TLS 1.0 and TLS 1.1, applying TLS 1.3 on flathub.org?

**Comment by loganmarchione** [comment]
@barthalion This issue can be closed, right?

**Comment by barthalion** [comment]
Correct, thanks.
