### ISSUE TITLE
Add collaborator to Jami GNOME

### ISSUE THREAD

**Issue by ntninja** [flathub/flathub#2001]
Please add https://github.com/FuchtelJockel to https://github.com/flathub/net.jami.Jami . They are doing a good job at fixing and updating the build (currently in review) and I don't have the bandwidth anymore to proactively maintain this application.

**Comment by barthalion** [comment]
Invitation sent, @FuchtelJockel can view it at https://github.com/flathub/net.jami.Jami/invitations.
