### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by KerstinMaur** [flathub/flathub#201]
Can you please add [Android Studio](https://developer.android.com/studio/index.html)?

**Comment by adityashah1212** [comment]
I don't want to sound rude, but it would be better if you could rather make the manifest and a pull request for it rather than making requests. It is not really that difficult to write the manifest.

**Comment by TingPing** [comment]
Yea requests don't belong here. A starting point would be the existing pycharm package: https://github.com/flathub/com.jetbrains.PyCharm-Community

**Comment by nedrichards** [comment]
I have a manifest for this that I've been working on - however I don't have time (or use it day to day) to maintain this app. I'd be happy to post it, but wouldn't merge unless some people volunteered to help.

**Comment by KerstinMaur** [comment]
I am quite new to coding but would like to try maintaining it. 😅

**Comment by TingPing** [comment]
It has been packaged and has a maintainer: https://github.com/flathub/com.google.AndroidStudio

**Comment by nedrichards** [comment]
@KerstinMaur Feel free to send Pull Requests for fixes, maintenence and improvements. You'll be a maintainer in no time!
