### ISSUE TITLE
Remove io.github.gustavoperedo.VideoDownloader

### ISSUE THREAD

**Issue by GustavoPeredo** [flathub/flathub#2028]
Hello flathub maintainers! Happy new year!
Unrud, the original developer of the application, is back maintaining Video Downloader; to enchance user experience in the flathub store I'd like to have my application (io.github.gustavoperedo.VideoDownloader) removed (so there are no duplicats).
Thanks.

**Comment by barthalion** [comment]
You can do that this way: https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life

**Comment by GustavoPeredo** [comment]
Thank you, I wasn't able to find this page.

**Comment by GustavoPeredo** [comment]
Done! @barthalion Thanks again.
