### ISSUE TITLE
nodejs either as baseapp or freedesktop extension

### ISSUE THREAD

**Issue by adityashah1212** [flathub/flathub#203]
Now that we can build electron apps (atleast the most generic cases). We should think about how to provide nodejs. I don't think it would be good idea to build node with every app. It would be better to have a Baseapp or a freedesktop extension for nodejs. This will significantly reduce electron app build time.

**Comment by TingPing** [comment]
`nodejs` is actually a relatively small dependency to build. An sdk-extension baseapp only cuts down on build time (few seconds with caching) and doesn't reduce duplication.

**Comment by barthalion** [comment]
Closing as 1) this is old 2) it really is fine to bundle node. We can't have a base app for literally every component which takes longer than 5 minutes to compile.
