### ISSUE TITLE
Couldn't install flatpak on ubuntu

### ISSUE THREAD

**Issue by bancika** [flathub/flathub#2032]
I get these errors

Err:1 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 libostree-1-1 amd64 2019.3-1
  404  Not Found [IP: 91.189.91.39 80]
Err:2 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 flatpak amd64 1.4.3-1
  404  Not Found [IP: 91.189.91.39 80]
Unable to correct missing packages.
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/o/ostree/libostree-1-1_2019.3-1_amd64.deb  404  Not Found [IP: 91.189.91.39 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/f/flatpak/flatpak_1.4.3-1_amd64.deb  404  Not Found [IP: 91.189.91.39 80]
E: Aborting install.

**Comment by barthalion** [comment]
You should report it to Ubuntu; at first glance you haven't run `apt-get update` but again, nothing to do for us here.

**Comment by barthalion** [comment]
Note it's "legit" 404 – available versions are listed at http://us.archive.ubuntu.com/ubuntu/pool/universe/f/flatpak/.although without Ubuntu release info.

**Comment by bancika** [comment]
In that case, your instructions at https://flatpak.org/setup/Ubuntu/ are not valid. I got the error by following those and typing 

sudo apt install flatpak

**Comment by barthalion** [comment]
Just to double check, this is Ubuntu 19.10?
