### ISSUE TITLE
Build bot delta generation time out and size limit for delta generation

### ISSUE THREAD

**Issue by jakobjakobson13** [flathub/flathub#2077]
In the commit https://github.com/flathub/buildbot/commit/106a5c7afaec947174a6a72f43b3cf727017257d you increased the time out for the delta generation. As one of my recent builds https://flathub.org/builds/#/builders/51/builds/2747 (it's pretty huge) timed out, I just wanted to check if my deltas were to big and/or if this time out is/was related to your build bot commit.
Or to put it in a more simple question: Does the time out during the delta generation imply a size limit for flatpak packages?

**Comment by barthalion** [comment]
There is no limit per se, it's just that aarch64 servers have worse single-thread performance than x86_64. We can increase the timeout if it's needed anytime.

**Comment by hfiguiere** [comment]
It is currently needed. See https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/issues/43

**Comment by Eonfge** [comment]
@barthalion and @hfiguiere There are users running into issues with TexLive because the build can't finish. Can you make some exception so that the builds can complete?

**Comment by hfiguiere** [comment]
I no power to do anything.

**Comment by Eonfge** [comment]
@hfiguiere Can you see if it worked? I can't see it
```
flatpak search org.freedesktop.Sdk.Extension.texlive 
```

**Comment by barthalion** [comment]
That's odd, let's try again: https://flathub.org/builds/#/builders/19/builds/7574

**Comment by muelli** [comment]
hm. this is only mildly related, but Wireshark started to fail due to a 1 hour timeout: https://github.com/flathub/org.wireshark.Wireshark/pull/69

**Comment by Eonfge** [comment]
Hey, it seems to be working now:
```
[kevin@kevin-at-fedora ~]$ flatpak search org.freedesktop.Sdk.Extension.texlive 
Name                            Description                      Application ID                                Version            Branch         Remotes
TeX Live Sdk extension          LaTeX packages and tools         org.freedesktop.Sdk.Extension.texlive         2020.04.06         21.08          flathub
TeX Live Sdk extension          LaTeX packages and tools         org.freedesktop.Sdk.Extension.texlive         2020.04.06         20.08          flathub
TeX Live Sdk extension          LaTeX packages and tools         org.freedesktop.Sdk.Extension.texlive                            19.08          flathub
TeX Live Sdk extension          LaTeX packages and tools         org.freedesktop.Sdk.Extension.texlive                            18.08          flathub
```

**Comment by barthalion** [comment]
HUH

Let's close the issue quickly before it disappears!
