### ISSUE TITLE
How to retrive write access for a flathub repo

### ISSUE THREAD

**Issue by adnan449** [flathub/flathub#2091]
My invitation to get write access link expired. The pull request was https://github.com/flathub/flathub/pull/2054 and the repo is https://github.com/flathub/com.gitlab.adnan338.Invoicer and I am already a contributor.

**Comment by barthalion** [comment]
That's odd, I wonder what happened. It should be visible now at https://github.com/flathub/com.gitlab.adnan338.Invoicer/invitations.
