### ISSUE TITLE
GZIP extraction issue when downloading from https://sources.flathub.org

### ISSUE THREAD

**Issue by Zlopez** [flathub/flathub#2099]
Today I received an [update](https://github.com/flathub/org.gnome.Chess/pull/24) from flathubbot, which [failed](https://flathub.org/builds/#/builders/8/builds/4567).

When I was trying to reproduce the issue I found out, that the `tar xf` works on the original source, but it fails to extract on the mirror from https://sources.flathub.org.

**Comment by gasinvein** [comment]
This is a flatpak-external-data-checker issue. It sometimes misses incomplete http read and thinks there was a remote data change. See flathub/flatpak-external-data-checker#142
Sorry for the inconvenience. I'm still trying to figure out why it happens, which is tricky as it doesn't reproduce in synthetic tests.

**Comment by Zlopez** [comment]
Thanks for clarification, I will close this issue for now, if you already tracking it on x-data-checker.
