### ISSUE TITLE
SDK for compiling Go programs

### ISSUE THREAD

**Issue by mki1967** [flathub/flathub#210]
Is there any (planned) SDK for compiling Go programs for Flathub?
(I would like to try to package a program that uses libraries from [go-gl](https://github.com/go-gl) )

**Comment by bil-elmoussaoui** [comment]
I'm working on a simple app using go with gtk bindings, and i would love to distribute the app using flathub only. So a huge +1 to this!

**Comment by nedrichards** [comment]
None planned that I'm aware of, but if there are members of the go community who are keen then we'd be more than happy to have it.

**Comment by TingPing** [comment]
In the short term you can just download the Go binaries: https://golang.org/dl/

**Comment by mki1967** [comment]
I am just making my first flatpak, however I have somehow  installed the Go SDK extension:  #213  in my tutorial-repo and then (by experimenting) I managed to prepare [io.github.mki1967.mki3dgame.json](https://gist.github.com/mki1967/a8c0939160dafc15407fd528a5c385c7) , which I would like to submit to Flathub, as soon as the Go SDK Extension is ready. (I have tested only on `x86_64` - Linux Mint, however I am surprised that I have managed to make a working flatpak of my application.)

**Comment by Barthalion** [comment]
Just merged the extension with Go compiler. Feel free to submit your application in new pull request.
