### ISSUE TITLE
Is it acceptable to include `--filesystem=~/.var/app/our.Nightly.AppId/config/app:ro` to our stable flathub manifest?

### ISSUE THREAD

**Issue by jmaibaum** [flathub/flathub#2100]
The use case would be to offer users of an upcoming self-hosted KiCad nightly flatpak the option to import their configuration on first use of the flathub stable flatpak at https://github.com/flathub/org.kicad.KiCad .

KiCad's users traditionally switch between stable and nightly builds of the app rather often, and importing settings/configuration has long been supported in KiCad, using the `$XDG_CONFIG_DIR` env var and then searching for common paths of the nightly/stable config dirs. The devs noted that this is not possible by default in a flatpak due to sandboxing.

Currently, the work-in-progress app ID for the nightly flatpak is `org.kicad.KiCad.Nightly` to allow both the nightly and stable versions to be accessible from app menus when being installed in parallel.

First tests with local builds of our nightly flatpak show that `flatpak override --user --filesystem=~/.var/app/org.kicad.KiCad/config/kicad:ro` makes the stable config path accesible from within the nightly flatpak sandbox. The question is if adding this filesystem access permanently to the stable manifest to allow for a migration from nightly configration to a stable version of KiCad is acceptable on flathub?

Or is there another, more proper way to offer read-only access to configuration dirs from other app IDs?

CC @craftyjon @sethhillbrand @imciner2

**Comment by barthalion** [comment]
Yes, I think it's reasonable thing to do.
