### ISSUE TITLE
Anbox flatpak?

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/flathub#214]
https://anbox.io/
https://github.com/anbox/anbox
https://github.com/anbox/anbox/issues/62

**Comment by TingPing** [comment]
This isn't a bug tracker for requests. That said it looks like a poor fit for flathub. Warns everywhere its alpha software, the Snap is specifically not sandboxed (wonder why, perhaps won't work with flatpak anyway), and the first launch experience is a CLI tool.
