### ISSUE TITLE
Add me to com.bluejeans.BlueJeans

### ISSUE THREAD

**Issue by hadess** [flathub/flathub#2148]
Can you please add me as one of the commiters on com.bluejeans.BlueJeans as @AsciiWolf mentioned in:
https://github.com/flathub/com.bluejeans.BlueJeans/pull/10#issuecomment-770938673
?

Cheers

**Comment by bilelmoussaoui** [comment]
Done, sorry I missed the ping :-)

**Comment by hadess** [comment]
No worries :)
