### ISSUE TITLE
New maintainer for com.sublimemerge.App

### ISSUE THREAD

**Issue by ptomato** [flathub/flathub#2160]
As per https://github.com/flathub/com.sublimemerge.App/pull/21#issuecomment-790118546 please add @ineol as a maintainer of com.sublimemerge.App. They have been much more active than the current maintainer (me) in shipping updates of Sublime Merge and I think they should be able to publish these updates without waiting for me to approve them.

**Comment by barthalion** [comment]
Done.

**Comment by ptomato** [comment]
Thanks!
