### ISSUE TITLE
Applications not appearing on Flathub.org or updating appearing on the CLI

### ISSUE THREAD

**Issue by Eonfge** [flathub/flathub#2166]
Hey, I think I have a serious issue @barthalion 

I published an update this afternoon for ET Legacy but something must have gone wrong in the backend, for it's not appearing:
https://flathub.org/builds/#/builders/32/builds/42095

Other applications that have been updated since this afternoon, are also not appearing.

**Comment by cbm755** [comment]
My app from 18 hours ago also not appearing.

https://flathub.org/builds/#/builders/32/builds/42127

I say some blue banner that I don't remember seeing before:

```
12    Check for newer published builds                              skipped
```
And under 13  I see:
```
Waiting for commit job
/ Job was started
| Committing ref screenshots/x86_64 (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)
| Job failed: InternalError: Command "flatpak" "build-commit-from" "--timestamp=NOW" "--no-update-summary" "--untrusted" "--force" "--disable-fsync" "--gpg-homedir=/var/lib/flat-manager/.gnupg" "--gpg-sign=xxxxxxxxxxxxxxxxxxxxxx" "--src-repo=/tank/repo/builds/40529/upload" "--src-ref=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" "/tank/repo/builds/40529" "screenshots/x86_64" exited unsuccesfully: error: Failure signing commit file: Pinentry: Inappropriate ioctl for device
| 
\ Job failed
```
But then I get a green light anyway

**Comment by Eonfge** [comment]
@nedrichards @alexlarsson Not sure if it's your department, but this is quite a thing. :scream:

**Comment by cbm755** [comment]
The only thing I possibly did differently this time was a force push to my `bump` branch at https://github.com/flathub/org.plomgrading.PlomClient/pull/15  (not sure if that's relevant)

**Comment by Eonfge** [comment]
@cbm755 Update on my end, seems that the system is working again. Can you double check that for your application?

**Comment by cbm755** [comment]
Seems to be working!  I didn't trigger a new build or anything...  But I just did a `flatpak update` and down it came.

Close I guess?

**Comment by Eonfge** [comment]
Same here, all seems to work now. Really, the biggest thing that still bothers me right now is a total lack of response from the team. Service disruptions are important and I also mailed to the admin mailing list, so perhaps they can comment here. Please Flathub, don't keep secondary maintainers in the dark.

This graph is also not very helpful:
https://status.flathub.org/

**Comment by nedrichards** [comment]
Yep, there was an issue with one of the backend servers and a couple of workers that is now fixed. It was discussed on IRC at the time but I didn't see this issue until now. I believe affected builds were all retriggered but if not do push a new build again. This was only on the developer side of the operation, there was no disruption to end users (other than not getting the latest releases of course).
