### ISSUE TITLE
Flathub builder error: AppData problem: tag-invalid : <release> versions are not in order [40.0 before 40.alpha]

### ISSUE THREAD

**Issue by Zlopez** [flathub/flathub#2179]
The GNOME recently changed the versioning scheme and they now have a version 40.

I tried to build the [new version of org.gnome.chess](https://github.com/flathub/org.gnome.Chess/pull/25) and ended up with:
```
org.gnome.Chess:                   AppData problem: tag-invalid : <release> versions are not in order [40.0 before 40.alpha]
```
The build could be found [here](https://flathub.org/builds/#/builders/32/builds/42738)

What can I do with this error? The GNOME Chess is using 40.0 version instead of just 40, but I don't think this should cause the build to fail.

**Comment by bilelmoussaoui** [comment]
Not a Flathub issue. That's how appstream sorts the versions. You should remove the alpha/beta ones and only keep the stable one.

**Comment by Zlopez** [comment]
The org.gnome.chess is currently running on 3.38, didn't used the 40.alpha anywhere. Not sure how should I remove it and where.

**Comment by Zlopez** [comment]
Nevermind I found it.
