### ISSUE TITLE
org.gnome.Platform won't install for me

### ISSUE THREAD

**Issue by cobalt2727** [flathub/flathub#2185]
I can't seem to update some of my apps, since version 3.38 apparently doesn't exist on Flathub for some reason...?
logs below

cobalt@cobalt-inspiron:~$ flatpak update 
Looking for updates…
Required runtime for [redacted]/x86_64/stable (runtime/org.gnome.Platform/x86_64/3.38) found in remote flathub
Do you want to install it? [Y/n]: y

        ID                      Branch      Op     Remote      Download
 1. [✗] org.gnome.Platform      3.38        i      flathub     1.0 kB / 344.6 MB

Error: While trying to checkout 3f33409122fb5e81e32ddb6bd360376f6ac6514edf7b8eb84748b0cc12bcab5a into /home/cobalt/.local/share/flatpak/runtime/org.gnome.Platform/x86_64/3.38/.3f33409122fb5e81e32ddb6bd360376f6ac6514edf7b8eb84748b0cc12bcab5a-C3DH10: Opening content object 58ce4ec3915e88fa03c8a23a0c3a47e7b185dda5c2a376e4107cbf0096c01170: Couldn't find file object '58ce4ec3915e88fa03c8a23a0c3a47e7b185dda5c2a376e4107cbf0096c01170'
Installation complete.
error: There were one or more errors
cobalt@cobalt-inspiron:~$

**Comment by barthalion** [comment]
Have you tried running `flatpak repair` and `flatpak repair --user`?

**Comment by cobalt2727** [comment]
That did the trick - thanks!
