### ISSUE TITLE
SDK for dotnet cli

### ISSUE THREAD

**Issue by julianrichen** [flathub/flathub#222]
I'm working on packaging an application and one of the dependencies of a dependency is [ByteSize](https://github.com/omar/ByteSize) which is written in C#. I'm not at all familiar with C# but the Makefile in the repo uses the commands `dotnet restore`, `dotnet build`, etc.. I assumed Mono would be fine so I could use the [Mono5 SDK Extention](https://github.com/flathub/org.freedesktop.Sdk.Extension.mono5) but it doesn't have that binary.

So I guess I need [dotnet cli](https://github.com/dotnet/cli) tool? It seems fairly intensive to build and also pulls dependencies from NuGet packages hosted on MyGet, which seems like a whole npm/yarn situation.

So I guess the main question is: What is the best and legal way to build .Net applications & dependencies on flathub. Could it be added as a shared module? Can I use the pre-build binaries from the [release page](https://github.com/dotnet/cli/releases)?

**Comment by nedrichards** [comment]
I was discussing a need for a .Net core SDK Extension with @directhex the other day. This would likely also be required to fix https://github.com/flathub/com.visualstudio.code/issues/9

I haven't looked at NuGet at all, if it needs network during build and can't be stubbed out with a local cache then we'd certainly have to look at repackaging the existing binaries.

**Comment by julianrichen** [comment]
I started exploring building NuGet on Linux but it seems to only come as an .EXE and is run via .NET. While looking I found this SO answer:
https://stackoverflow.com/questions/44770702/build-nuget-package-on-linux-that-targets-net-framework

Which claims mono5 has an equivalent `dotnet` command called `msbuild`:

> 1. Use mono 5+ to build the library.
> 
> This is probably the most stable path.
> 
> Mono 5 and higher contains the needed build logic to build .NET Standar and .NET Core applications. On linux, mono's msbuild may need to be installed as a separate package. So instead of the following commonly used commands
> 
>     dotnet restore
>     dotnet build
>     dotnet publish -c Release
> 
> you would use mono's msbuild to do the following:
> 
>     msbuild /t:Restore
>     msbuild
>     msbuild /t:Publish /p:Configuration=Release

Looks like the source is here:
https://github.com/mono/linux-packaging-msbuild

I'm looking into building it.

**Comment by directhex** [comment]
Nuget 3+ don't build properly on Linux, I don't remember the reasons why, so Mono switched to just shipping a nuget.exe binary https://github.com/mono/monodevelop-flatpak/blob/master/com.xamarin.MonoDevelop.json#L420-L441

**Comment by julianrichen** [comment]
@directhex Well this ls lucky I was about to build msbuild but that flatpak already has it: https://github.com/mono/monodevelop-flatpak/blob/master/com.xamarin.MonoDevelop.json#L355

Guess I'll try that first, thanks for the link :)

**Comment by nedrichards** [comment]
@julianrichen note: that msbuild only works in the FDo 1.4 SDK - there was some discussion on IRC about this earlier in the week with the overall view being to use the binary and just run it in 1.6 rather than enter deeper into a world of sad hacks.

**Comment by omajid** [comment]
> So I guess the main question is: What is the best and legal way to build .Net applications & dependencies on flathub. Could it be added as a shared module? Can I use the pre-build binaries from the release page?

Longer term, the main .NET Core runtime should be based on https://github.com/dotnet/source-build/. That repo is explicitly meant to build the .NET Core SDK and runtime in a way friendly to Linux distributions. That should make it ideal for a flatpak (built from source) as well. I think putting that up as a shared module (or shared runtime? not sure about the correct terminology here) would be the way to go.

**Comment by nedrichards** [comment]
An SDK extension is probably what you want here. We'd be more than happy to host one if the .Net community want to get involved - but I for one am not much of an expert.

**Comment by kirbyfan64** [comment]
FWIW this has been in Flathub for a while. I did end up using the binaries over the build scripts, as the latter seemed to really want internet access, and trying to make them work without turned into a rather large time sink.
