### ISSUE TITLE
Atom Flatpak is not respecting system fonts (for UI)

### ISSUE THREAD

**Issue by valmar** [flathub/flathub#223]
The current Atom Flatpak (Atom 1.23.2) does not seem to respect the system font choice (font and font size). Here I am talking about the UI font (menus, etc), not the editor font. When one install Atom from the rpm package, the font choice is respected, so I think this is a Flatpak issue.

Valerio

**Comment by nedrichards** [comment]
If this is an issue in the Atom package can you open the issue there? https://github.com/flathub/io.atom.Atom

**Comment by valmar** [comment]
Sure, sorry!
