### ISSUE TITLE
wiki/App-Requirements#Filesystem-access: share TMPDIR between multiple sessions

### ISSUE THREAD

**Issue by tinywrkb** [flathub/flathub#2230]
IDK if this is documented somewhere but seems to be a common approach.

```
diff --git a/App-Requirements.md b/App-Requirements.md
index 3836678..a6f54f7 100644
--- a/App-Requirements.md
+++ b/App-Requirements.md
@@ -157,7 +157,8 @@ use `--persist` and it will map the `$HOME` directory to your private directory
 recommended that flatpak installs stay self-contained.

 - If an application uses `$TMPDIR` to contain lock files it may make sense to use `--env=TMPDIR=/var/tmp` or if
-it shares those files outside the sandbox you may need to create a wrapper script that sets it to `$XDG_CACHE_HOME`.
+it shares those files outside the sandbox you may need to create a wrapper script that sets it to `$XDG_CACHE_HOME`.
+If those files are needed to be shared across multiple running instances then use `--env=TMPDIR=xdg-run/app/$your_app_id`.

 #### Device access

```

**Comment by tinywrkb** [comment]
It should also be documented that from Flatpak 1.12, `XDG_RUNTIME_DIR` and `/tmp` will be shared between instances of the same app.  
The mentioned workaround is still needed with outdated Flatpak versions, so unless there's a good reason to restrict the app to >=1.12 Flatpak releases, the workaround should still be used.

* [Share /tmp between instances of the same app](https://github.com/flatpak/flatpak/pull/4093)
* [Create a shared XDG_RUNTIME_DIR for each app-ID](https://github.com/flatpak/flatpak/pull/4126)

**Comment by razzeee** [comment]
Please send a PR with a proposed documentation change on the https://github.com/flathub/documentation repo :)
