### ISSUE TITLE
Maintainership for io.mgba.mGBA

### ISSUE THREAD

**Issue by Parnassius** [flathub/flathub#2281]
Hi,
lately the [mGBA](https://github.com/flathub/io.mgba.mGBA) flathub repo has been quite stagnant, and is currently two versions behind upstream - a [PR to update to 0.8.4](https://github.com/flathub/io.mgba.mGBA/pull/20) has been open since the end of october, and [another one for 0.9.0](https://github.com/flathub/io.mgba.mGBA/pull/23) has been waiting for a couple of weeks (the previous six PRs I made to bump the manifest to a new version were all merged quite quickly). I'm not sure if it's ok for me to ask for maintainership (I'm not involved at all with upstream), but if there are no problems I'd be happy to help maintain this flatpak.

Thanks

**Comment by barthalion** [comment]
Sorry, I turned out to be a poor maintainer. :( Sent you an invitation and also merged the 0.9.0 PR. Thanks for your work!

**Comment by Parnassius** [comment]
Thank you!
