### ISSUE TITLE
dl.flathub.org IPs banned in Russia

### ISSUE THREAD

**Issue by amavlyanov** [flathub/flathub#2314]
Due to Russian government regulatory actions on banning other services all 4 dl.flathub.org IPv4 addresses  banned.

https://isitblockedinrussia.com/?host=dl.flathub.org

Action needed: change IPv4 addresses of dl.flathub.org to "clean" ones (you can check 'em with https://isitblockedinrussia.com/ service).

**Comment by tommytran732** [comment]
How about using a CDN for this?

**Comment by barthalion** [comment]
The thing is dl.flathub.org is already a CDN. You can work it around by changing the remote to use https://front-hex2.flathub.org or https://front-ams.flathub.org for now.

**Comment by razzeee** [comment]
That website now states, that dl.flathub.org is NOT banned in russia, so this can probably be closed
