### ISSUE TITLE
Any interested in maintaining a Guake Flatpak?

### ISSUE THREAD

**Issue by fusion809** [flathub/flathub#232]
Hi,

I've noticed that several GNOME apps are available as Flatpaks and I can't help but to wonder why Guake hasn't. Must admit I really do not understand how Flatpaks are built well enough to do this myself, so I'm wondering if anyone else is interested in doing this.  

Thanks for your time,
Brenton

**Comment by TingPing** [comment]
This is not a place to request packages. Anyway `guake` is a bad fit because it isn't a desktop application and there is no way to set up auto-starting a background application currently.

**Comment by fusion809** [comment]
Where is the place to request packages? Sorry for opening issues in the wrong place, I realize it'd be frustrating. Unfortunately, it's not like the Flathub website tells you where to request them.

**Comment by aiamuzz** [comment]
i guessed as much in my lay man understanding ...

@TingPing 
so does it mean a Linux terminal application in a flatpak package is NOT a possibility ?

**Comment by nedrichards** [comment]
fwiw. and this is something that may be worth putting on the website more clearly - the best place to request a flatpak is with an upstream. You can tell them that flathub provides tools and services that make hosting, building and discovery easier for them - or they can host their own repo but our goal is to stimulate a community of developers rather than a community of packagers (which is at best transitional as we build momentum)

**Comment by nedrichards** [comment]
@aiamuzz you can have them - they're just not particularly easy to use or integrate into a normal terminal workflow and they don't really get the benefits of the newer sandboxing infrastructure around flatpak

**Comment by barthalion** [comment]
That being said, terminal emulator won't really work for using tools installed on the host, but not in the flatpak environment, pretty much defeating the point.

**Comment by TingPing** [comment]
A terminal can be designed to run commands on the host, ala GNOME-Builders integrated terminal. It requires modification to the terminal and `devel` permissions of course.

**Comment by aiamuzz** [comment]
@barthalion ... i thought so ... i thought it would somehow be limited ... like you put it ... it defeats the purpose, considering a linux terminal can pretty much do and have the power to tinker every part of the OS.

@TingPing ... it be great if it was possible ... a flatpak terminal app with absolutely no limitations compared to what a native terminal app can accomplish.

**Comment by class101** [comment]
I'm on a Steam Deck (SteamOS) and the recommended way to install app is Flatpak and this is a bit frustrating to not find Guake on it
