### ISSUE TITLE
EOL and/or deref com.remarkable.reMarkable

### ISSUE THREAD

**Issue by lionirdeadman** [flathub/flathub#2344]
It can't be downloaded and it's no longer available even if it was updated.

**Comment by kevinsmia1939** [comment]
> It can't be downloaded and it's no longer available even if it was updated.

I look through the website, https://remarkable.com/.
I cannot find where to download the client. Maybe they drop support? If so, we should pull it off Flathub.

**Comment by lionirdeadman** [comment]
Yep, precisely why this issue exists.

**Comment by barthalion** [comment]
I have removed ostree references. They will disappear from the summary file next time any build is published.
