### ISSUE TITLE
WhatsApp Desktop

### ISSUE THREAD

**Issue by giovannicaligaris** [flathub/flathub#235]
Enrico made a Flatpak for his Whatsapp electron app. Can it be added to Flathub please?

https://github.com/Enrico204/Whatsapp-Desktop/releases

**Comment by TingPing** [comment]
This bug tracker isn't for requests. Their Flatpak also isn't useful for Flathub which requires apps be built on Flathub servers with `flatpak-builder` which they don't use so a new manifest would need to be made which is non-trivial for Electron apps.
