### ISSUE TITLE
Applying HSTS + TLS 1.3 on flathub

### ISSUE THREAD

**Issue by hashflu** [flathub/flathub#2356]
I think HSTS + TLS 1.3 on flathub providing great security advantages. Applying [HSTS (HTTP Strict Transport Security)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security), [HSTS Preloading](https://hstspreload.org/), and supporting TLS 1.3 with TLS 1.2 (flathub server currently support TLS 1.2 only.) would make less attack surface and prevent  attack from malicious users. 

Thanks

**Comment by loganmarchione** [comment]
Similar to #1997.

It appears only TLS 1.2 is currently supported.  
https://www.ssllabs.com/ssltest/analyze.html?d=flathub.org&latest

**Comment by barthalion** [comment]
https://flathub.org and https://dl.flathub.org use TLS 1.3 now when available. The former always had HSTS headers on, while I've just enabled it with low value for the download endpoint. I don't think we're particularly interested in being listed in the preload list.
