### ISSUE TITLE
Is it allowed to access Internet while building?

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flathub/flathub#236]
For node.js applications, the build process involves downloading from an external repository (npm), and the exact files to download is too many to figure out in the recipe. Thus [Visual Studio Code](https://github.com/flathub/com.visualstudio.code/blob/master/com.visualstudio.code.json) and [Zotero](https://github.com/flathub/flathub/pull/221/files) as well as many applications based on node.js are only "build-able" from an existing build. BTW, there is no official existing build of Visual Studio Code 😂

**Comment by TingPing** [comment]
No, it runs `flatpak-builder` with `--sandbox`. There are some tools to help download `npm` dependencies: https://github.com/flatpak/flatpak-builder-tools

but the build system must still not use other network access which sadly many do.
