### ISSUE TITLE
Archive repos which are EOL

### ISSUE THREAD

**Issue by lionirdeadman** [flathub/flathub#2362]
- [ ] https://github.com/flathub/de.wolfvollprecht.UberWriter.Plugin.TexLive (not properly EOL'ed!)
- [x] https://github.com/flathub/com.github.lainsce.notejot
- [x] https://github.com/flathub/com.github.itext.i7j_rups (not properly EOL'ed!)
- [x] https://github.com/flathub/com.jvieira.tpt.Metronome
- [x] https://github.com/flathub/com.realm667.WolfenDoom_Blade_of_Agony
- [x] https://github.com/flathub/com.github.lainsce.timetable
- [ ] https://github.com/flathub/de.rwth_aachen.ient.RDPlot (not properly EOL'ed!)
- [x] https://github.com/flathub/io.github.Freedoom-Phase-2
- [x] https://github.com/flathub/com.github.lainsce.coin
- [x] https://github.com/flathub/io.github.Freedoom-Phase-1
- [x] https://github.com/flathub/de.wolfvollprecht.UberWriter
- [x] https://github.com/flathub/tk.turtlico.Turtlico

Some of them might have been improperly EOL'ed because I see failing builds.

**Comment by bbhtt** [comment]
Some more:

- [ ]  [io.github.jkozera.ZevDocs](https://github.com/flathub/io.github.jkozera.ZevDocs/) EOL: https://github.com/flathub/io.github.jkozera.ZevDocs/commit/6fccb054cbb04285ab0e4d257dc85cd571a5a6ef
- [ ] [com.github.lainsce.yishu](https://github.com/flathub/com.github.lainsce.yishu/) EOL: https://github.com/flathub/com.github.lainsce.yishu/commit/eca1f7fb82e7920a886e9177626c4eb3249bd21f
- [ ] [io.bit3.WhatsAppQT](https://github.com/flathub/io.bit3.WhatsAppQT) EOL: https://github.com/flathub/io.bit3.WhatsAppQT/commit/421764985a964ab1a6474e40e2741b3824eddca4
- [ ] [dev.rdm.RDM](https://github.com/flathub/dev.rdm.RDM/) EOL: https://github.com/flathub/dev.rdm.RDM/commit/66b550c470ff50d853d20763b15c701fc86c5097
- [ ] [io.github.lukajankovic.ambience](https://github.com/flathub/io.github.lukajankovic.ambience/) EOL: https://github.com/flathub/io.github.lukajankovic.ambience/commit/2724b64ab2f4da7dd3d403113f730b31fb88eeb2
- [ ] [io.github.prateekmedia.flutube](https://github.com/flathub/io.github.prateekmedia.flutube) EOL: https://github.com/flathub/io.github.prateekmedia.flutube/commit/aa55c33135496ed2ce13b47004c0d3f1662aadb1
- [ ] [org.musesequencer.Muse3](https://github.com/flathub/org.musesequencer.Muse3) EOL: https://github.com/flathub/org.musesequencer.Muse3/commit/fc90ba0f0151f950653b7d2dd5a6f7f25ea35b8c 
- [ ] [org.eclipse.Committers](https://github.com/flathub/org.eclipse.Committers/) EOL: https://github.com/flathub/org.eclipse.Committers/commit/edb6f0f2c4c8bcbb94603f5cc296c3755f3b0494
- [ ] [io.bit3.ThreemaQT](https://github.com/flathub/io.bit3.ThreemaQT/) EOL: https://github.com/flathub/io.bit3.ThreemaQT/commit/1d75b0c706036ae002b83d831be46e89633ae002
- [ ] [com.github.elfenware.badger](https://github.com/flathub/com.github.elfenware.badger/) EOL: https://github.com/flathub/com.github.elfenware.badger/commit/dcf429ba364b5d4c06912ba6cb7c1b9c219ed5a6
- [ ] [io.github.harmonoid.harmonoid](https://github.com/flathub/io.github.harmonoid.harmonoid/) EOL: https://github.com/flathub/io.github.harmonoid.harmonoid/commit/6c1b1259cacd551bcf09f74e3a06a54ba7f2ffb9
- [ ] [com.github.alexr4535.siglo](https://github.com/flathub/com.github.alexr4535.siglo/) EOL: https://github.com/flathub/com.github.alexr4535.siglo/commit/2d39509a3b8bc2c95bb45f0efff7fb13793f8610  
- [ ] [com.giuspen.cherrytree](https://github.com/flathub/com.giuspen.cherrytree/) EOL: https://github.com/flathub/com.giuspen.cherrytree/commit/4c9ab2c095f4084f63f0e89dad18c968b06c5030

**Comment by bbhtt** [comment]
> * [ ]  https://github.com/flathub/de.wolfvollprecht.UberWriter.Plugin.TexLive (not properly EOL'ed!)

Seems archived already. Although I don't see it, EOL-ed will look:

```
flatpak remote-info --system flathub de.wolfvollprecht.UberWriter.Plugin.TexLive

TexLive Plugin - Allows to export to pdf and to show formulas in the inline
preview

        ID: de.wolfvollprecht.UberWriter.Plugin.TexLive
       Ref: runtime/de.wolfvollprecht.UberWriter.Plugin.TexLive/x86_64/stable
      Arch: x86_64
    Branch: stable
   License: LPPL
Collection: org.flathub.Stable
  Download: 204.2 MB
 Installed: 367.6 MB

    Commit: 0a5e4257e5ad7e1eecc38aa69fa5ced08721f3edceadd6966b94121b8395c9ee
    Parent: 506796221ba3bea09e7b14f57f42f3f1bb05dc16bca3138bcd83213b75d52e96
   Subject: Skip aarch64, it still refuses to build (4a18f98e)
      Date: 2018-05-23 13:30:51 +0000
```

>     * [ ]  https://github.com/flathub/com.github.itext.i7j_rups (not properly EOL'ed!)

Seems EOL-ed:

```
flatpak remote-info --system flathub com.github.itext.i7j_rups
                ID: com.github.itext.i7j_rups
               Ref: app/com.github.itext.i7j_rups/x86_64/stable
              Arch: x86_64
            Branch: stable
        Collection: org.flathub.Stable
          Download: 63.4 MB
         Installed: 175.0 MB
           Runtime: org.freedesktop.Platform/x86_64/20.08
               Sdk: org.freedesktop.Sdk/x86_64/20.08

            Commit: 8f0e3994e6910cd055f5ed890f1b435f9de1ec66e5d163951850ab967e316b01
            Parent: 991d24ef13642bd040d46fa07eb1acd4aab7a2a528a28644ad1c89577f7f7d54
       End-of-life: The application has been renamed to com.itextpdf.RUPS
End-of-life-rebase: app/com.itextpdf.RUPS/x86_64/stable
           Subject: morefix (6ae0bbd2)
              Date: 2023-01-23 12:16:40 +0000
```

>     * [ ]  https://github.com/flathub/de.rwth_aachen.ient.RDPlot (not properly EOL'ed!)

Seems not EOL, will look:

```
flatpak remote-info --system flathub de.rwth_aachen.ient.RDPlot                 

RDPlot - RDPlot is a tool for plotting rate distortion curves

        ID: de.rwth_aachen.ient.RDPlot
       Ref: app/de.rwth_aachen.ient.RDPlot/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 1.3.1
   License: GPL-3.0-or-later
Collection: org.flathub.Stable
  Download: 62.9 MB
 Installed: 203.8 MB
   Runtime: org.kde.Platform/x86_64/5.12
       Sdk: org.kde.Sdk/x86_64/5.12

    Commit: 275629bfa1e9776006ebc02c68388579f044d9a3dcb2cbec07ba1ff5e550264a
    Parent: 0022b9b1a1665e9d003652c7f44719d72aa51b03a2633abe662fb70b7e862170
   Subject: forgot to change some files for the last commit (c6d2ff1c)
      Date: 2019-10-30 22:49:18 +0000
```

**Comment by bbhtt** [comment]
Those two are tracked https://github.com/flathub/flathub/issues/4493
