### ISSUE TITLE
Update references to IRC channel

### ISSUE THREAD

**Issue by louib** [flathub/flathub#2366]
It is my understanding that Matrix is now used as both development and support channel for Flatpak. There's still a few references to the freenode IRC channel [here](https://github.com/flathub/flathub/wiki/App-Submission#getting-help) and [here](https://github.com/flathub/flathub/blob/master/CONTRIBUTING.md#requesting-a-new-package).

**Comment by nedrichards** [comment]
Both now fixed, thanks!

**Comment by louib** [comment]
There's another reference to the IRC channel [here](https://github.com/flathub/flathub/wiki/App-Requirements) (in the second paragraph)
