### ISSUE TITLE
Require short descriptions in repositories?

### ISSUE THREAD

**Issue by jurf** [flathub/flathub#237]
Just an idea, but it would make browsing Flathub from GitHub nicer, and since the short descriptions are present in the AppStream files and already used on the website it’s hardly any work at all.

**Comment by TingPing** [comment]
I vote no. The downside is that Flathub admins have to manually maintain this information, packagers can't modify it, and it may change as well as just being another step at initial creation. There is no upside either from my perspective as the github interface is only exposed to users when they report bugs it isn't a place to discover new software.

**Comment by Barthalion** [comment]
Yes, it makes no sense to me. The primary way to view Flathub is via GNOME Software/Discover or our website. GitHub is for development only and whoever wants to contribute, they most likely know how to find the appid.

**Comment by jurf** [comment]
Another idea, bit different, maybe more useful: what about a link to the flathub website with the app?

**Comment by TingPing** [comment]
Well the website is still a WIP so no stable links to that exist. Honestly it just isn't valuable IMO, Github is for developers.
