### ISSUE TITLE
IDEA-Community: cannot attach to a running java process

### ISSUE THREAD

**Issue by essembeh** [flathub/flathub#2371]
Hi

I've been using IDEA-Community for a while and recently gave a try to the flatpak version: com.jetbrains.IntelliJ-IDEA-Community

I noticed the I cannot attach to a running Tomcat server, the process is not shown in the dialog via "Run" -> "Attach to Process"
I usually run a custom tomcat webserver which is not in a sandbox and attach it from IntelliJ, but maybe the flatpak apps being sandboxed, they cannot access other PID?

I tried to play with permissions using Flatseal but couldn't make it work.
Is there a solution to attach to process not from the sandbox?

Thanks

**Comment by hfiguiere** [comment]
Please file the issue with the flathub project for this app:

https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community/issues

Thanks.

**Comment by essembeh** [comment]
Thanks,
I opened https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community/issues/69
