### ISSUE TITLE
EOL extensions and utilities made for EOL runtimes

### ISSUE THREAD

**Issue by lionirdeadman** [flathub/flathub#2380]
- [ ] https://github.com/flathub/org.freedesktop.Sdk.Extension.gcc7
- [ ] https://github.com/flathub/org.freedesktop.Platform.ffmpeg
- [ ] https://github.com/flathub/org.freedesktop.Sdk.Extension.gfortran-62
- [ ] https://github.com/flathub/org.freedesktop.Sdk.Extension.gcc8
- [ ] https://github.com/flathub/org.freedesktop.GlxInfo

None of these have any uses for non-EOL runtimes and as such, they should also be EOL'd.

**Comment by bbhtt** [comment]
extensions aren't EOL-ed seperately as they are tied directly to base runtime version/branch.
