### ISSUE TITLE
at.ssh_mitm.server is not visible on flathub.org but can be installed with flatpak

### ISSUE THREAD

**Issue by manfred-kaiser** [flathub/flathub#2382]
I can install ``at.ssh_mitm.server`` with flatpak, but the app is not visible on ``flathub.org``: https://flathub.org/apps/details/at.ssh_mitm.server

Is this an error in my manifest or does it only takes time?

**Comment by hfiguiere** [comment]
It's not an error.

Console applications are not listed.

**Comment by manfred-kaiser** [comment]
Thanks for the info
