### ISSUE TITLE
io.qt.qtwebengine.BaseApp: change default branch to branch/5.15 for f-e-d-c automation

### ISSUE THREAD

**Issue by tinywrkb** [flathub/flathub#2387]
Requesting to change the default branch of [io.qt.qtwebengine.BaseApp](https://github.com/flathub/io.qt.qtwebengine.BaseApp) to branch/5.15 as according to @gasinvein flathubbot only checks the default branch when running flatpak-external-data-checker.  
I have [an open PR adding f-e-d-c support to io.qt.qtwebengine.BaseApp](https://github.com/flathub/io.qt.qtwebengine.BaseApp/pull/15) and it would be great if it will be actually used by the bot.

This hasn't been discussed with the package maintainer so pinging @aleixpol here.

**Comment by hfiguiere** [comment]
I think we need someone with higher privileges like @barthalion or @nedrichards to change the default branch

**Comment by barthalion** [comment]
Done.

**Comment by tinywrkb** [comment]
Thanks!
