### ISSUE TITLE
Desktop remote server app

### ISSUE THREAD

**Issue by alexcraft611** [flathub/flathub#239]
Hi there,

I would like to know if it's possible to add a remote desktop server on flatpak app ( teamviewer, vnc or whatever you want) ?

thanks

**Comment by Barthalion** [comment]
Completely possible, but we're not gathering requests here. Technically every application is wanted and anyone is welcome to contribute manifest for them.

**Comment by alexcraft611** [comment]
OK, sorry

**Comment by nedrichards** [comment]
fwiw I made a sample manifest for TeamViewer https://gist.github.com/nedrichards/a0463a1b1a3fb959a75b37effedf824c however it looks like it uses system calls that are banned inside flatpaks sandbox. I didn't have the time or inclination to investigate further - but if someone wants to try harder and do a bit of strace-ing then that might be interesting.

**Comment by alexcraft611** [comment]
I'm a cusual user, i hope to see your project evolve because for the moment there is no possibility to control endless OS (i use endless os) over internet... too bad.
