### ISSUE TITLE
Permissions for a new contributor

### ISSUE THREAD

**Issue by SemaiCZE** [flathub/flathub#2397]
Hi,

recetly @vchernin was very helpful with maintaining and upgrading `com.mattermost.Desktop` app. I think it would be great if he has also write permission to the repo, so he could make changes and releases on his own. I still want to take care of the app myself, but it's really handy to have someone who can stand in for me.

cc @TingPing @barthalion 

Thanks,
-Petr

**Comment by TingPing** [comment]
Invitation sent.
