### ISSUE TITLE
Flathub status page 404

### ISSUE THREAD

**Issue by vchernin** [flathub/flathub#2401]
[flathub.org](https://flathub.org) links to a status page at the bottom (named "Flathub Status") that leads to [status.flathub.org](https://status.flathub.org) which is a 404.

**Comment by skierpage** [comment]
https://status.flathub.org/ is now failing with "SSL_ERROR_INTERNAL_ERROR_ALERT" in Firefox, and curl reports: `curl: (35) error:0A000438:SSL routines::tlsv1 alert internal error)`

(The http version does a 308 permanent redirect to https, so I can't avoid the SSL error).

**Comment by bilelmoussaoui** [comment]
This seems to work fine now, so closing
