### ISSUE TITLE
Please mark io.github.jkozera.ZevDocs as unmaintained/end-of-life

### ISSUE THREAD

**Issue by jkozera** [flathub/flathub#2418]
io.github.jkozera.ZevDocs is no longer maintained, please mark it in Flathub. Currently it doesn't build with latest GNOME runtime, and I'd rather avoid upgrading, potentially breaking functionalities, just to add flathub.json with `end-of-life`.

**Comment by nedrichards** [comment]
Should be done in https://github.com/flathub/io.github.jkozera.ZevDocs/commit/6fccb054cbb04285ab0e4d257dc85cd571a5a6ef
