### ISSUE TITLE
Please add me as maintainer for org.blender.Blender 

### ISSUE THREAD

**Issue by kevinsmia1939** [flathub/flathub#2422]
Hi,

It look like org.blender.Blender is unmaintained, I send PR but no respond.
https://github.com/flathub/org.blender.Blender/pull/77

I would like to be maintainer of this repository.

Thanks.

**Comment by barthalion** [comment]
Sent the invite, you can accept it at https://github.com/flathub/org.blender.Blender/invitations. Thanks!
