### ISSUE TITLE
Reopen an accidentaly closed app submission PR

### ISSUE THREAD

**Issue by etnadji** [flathub/flathub#2432]
Hello,
I made recently [an app submission pull request](https://github.com/flathub/flathub/pull/2431).
Unfortunately, against master. As I noticed that and fixed the PR to be against new-pr, the PR was closed and now I can't re-open it.
So, can someone re-open it ?

Sorry about that & the awful english.

([fork branch here](https://github.com/etnadji/flathub/tree/fr.etnadji.dispremi))

**Comment by barthalion** [comment]
Hi, it's GitHub limitation. Can you push your branch under a different name and open a new PR? Something along `git push origin fr.etnadji.dispremi:fr.etnadji.dispremi2` should be enough.

**Comment by etnadji** [comment]
Weird, I can't edit or validate PR against new-pr …

![image](https://user-images.githubusercontent.com/6422073/127056536-82de02a9-0016-4c0f-88d7-57f0efd62aa5.png)

**Comment by hfiguiere** [comment]
Probably because YOUR branch is not based on the right branch either.
