### ISSUE TITLE
Build server out of space

### ISSUE THREAD

**Issue by Eonfge** [flathub/flathub#2450]
@TingPing @barthalion @nedrichards 
My apology for pinging you directly, but this is quite urgent.

We've ran out of space on our build server and all builds are failing. Sadly, the builderbot is not aware of this so some master packages are now also in a state of limbo.

https://flathub.org/builds/#/

**Comment by hfiguiere** [comment]
@alexlarsson freed some space on the machine impacted.

**Comment by alexlarsson** [comment]
Yeah, i restarted: https://flathub.org/builds/#/builders/32/builds/55459 and it succeeded. 
Should work for now, but we should look at diskspace use for the sources machine.
