### ISSUE TITLE
Access to com.tutanota.tutanota

### ISSUE THREAD

**Issue by charlag** [flathub/flathub#2494]
Hello
We would like to request membership access change for the Flathub repo of Tutanota:
https://github.com/flathub/com.tutanota.Tutanota

The following members of our team should have write permissions to the repo:
@tutao-jenkins
@ganthern
@johnbotris
@jowlo
@rosso-ptg
@sarashub
@vaf-hub
@vitoreiji

Would be nice if you could change this. Thank you!

**Comment by barthalion** [comment]
All done. As usually, invitations need to be accepted before write access is granted.

**Comment by charlag** [comment]
Thanks!
