### ISSUE TITLE
How can i add maintainer to my flatpak repo or at least transfer ownership?

### ISSUE THREAD

**Issue by actionless** [flathub/flathub#2496]
Due to lack of time to maintain myself a flatpak repo for one of the apps i maintain i was asking community for help (https://github.com/themix-project/oomox/issues/394) and finally got some response.
However after i've attempted to add the maintainer - i've realized what I don't have permissions to the repo Settings page on Github (The repo is https://github.com/flathub/com.github.themix_project.Oomox).
What is the procedure of adding maintainer and/or transferring ownership?

**Comment by HugLifeTiZ** [comment]
If anyone wants to step in and just take care of it, I'm the volunteer in question. I'd really like to start helping out as soon as I can.

**Comment by barthalion** [comment]
I have invited @HugLifeTiZ to collaborators.

**Comment by actionless** [comment]
thanks a lot!
