### ISSUE TITLE
EOL KDE 5.14 runtime

### ISSUE THREAD

**Issue by Erick555** [flathub/flathub#2499]
KDE 5.14 runtime didn't get any updates for long time and KDE developers agreed on `#flatpak` for making it EOL. AFAIK this can't be easily done through kde gitlab repo because flathub doesn't automatically accepts new jobs from non-default branches there so I ask flathub admins to assist (same thing was done for past kde runtimes).

cc @barthalion

**Comment by barthalion** [comment]
This should be done and visible in a few hours.
