### ISSUE TITLE
Screenshots contain padding to make them 16:9

### ISSUE THREAD

**Issue by pwithnall** [flathub/flathub#2506]
This used to be fine, but the appstream spec has [recently changed](https://github.com/ximion/appstream/issues/349) to stop recommending that screenshots are 16:9.

For most screenshots, padding them up to 16:9 is fine, but for some it makes the screenshot content quite small, which gets worse when software centres rescale the padded image further: https://dl.flathub.org/repo/screenshots/com.belmoussaoui.ReadItLater-stable/624x351/com.belmoussaoui.ReadItLater-e70ddb5ca1587d713ef1f1c598c2a4e6.png

See https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1401

My suggestion would be to fix this by porting from appstream-glib to libappstream (`appstreamcli compose`), just as with https://github.com/flathub/flathub/issues/2439, since libappstream should handle screenshots better (although I haven’t tested it).

The alternative would be to patch the appstream-glib version used by flathub to drop the [`AS_IMAGE_SAVE_FLAG_PAD_16_9` flag](https://github.com/hughsie/appstream-glib/blob/master/client/as-util.c#L3264) when it’s composing appstreams.

**Comment by razzeee** [comment]
As we're now on libappstream every newly build app should not contain the padding anymore
