### ISSUE TITLE
Please Mark 18.08/19.08 branches as EOL

### ISSUE THREAD

**Issue by mbooth101** [flathub/flathub#2523]
I added EOL metadata to the 19.08 branches of my SDK extensions, but they are unable to build due to:

`failed Could not find requested SDK org.freedesktop.Sdk//19.08 (failure)`

If I am not allowed to do it from my side, please go ahead and mark 19.08 branches EOL manually for the following extensions:

- [ ] org.freedesktop.Sdk.Extension.openjdk11
- [ ] org.freedesktop.Sdk.Extension.openjdk

**Comment by mbooth101** [comment]
I just noticed that `flatpak remote-ls` still shows 18.08 branches too!

```
$ flatpak update --appstream flathub && flatpak remote-ls | grep 'openjdk.*\(18\|19\)\.08'
OpenJDK SDK Extension   org.freedesktop.Sdk.Extension.openjdk           18.08   x86_64  flathub
OpenJDK SDK Extension   org.freedesktop.Sdk.Extension.openjdk           19.08   x86_64  flathub
OpenJDK 11 SDK Extension        org.freedesktop.Sdk.Extension.openjdk11         18.08   x86_64  flathub
OpenJDK 11 SDK Extension        org.freedesktop.Sdk.Extension.openjdk11         19.08   x86_64  flathub
```

Please mark the above as EOL.

**Comment by barthalion** [comment]
We generally don't EOL branches of SDK/runtime extensions as these runtimes already show a warning about being not supported.
