### ISSUE TITLE
Deprecate arm32 builds of io.mrarm.mcpelauncher

### ISSUE THREAD

**Issue by ChristopherHX** [flathub/flathub#2526]
As [org.kde.sdk 5.14 is EOL](https://github.com/flathub/flathub/issues/2499), no other usable arm32 runtime exists which isn't EOL. The app itself still supports arm32 and x86 in AppImages (to launch older versions of the game like Minecraft 1.12 32bit only), but upgrading flatpak runtimes makes it impossible.

Please mark the arm32 builds of this app as EOL.

If I update the kde runtime to 5.15 then you get an outdated version on an arm32 device (e.g. raspberry pi 2), there is no automatic way to deprecate and remove one architecture from flathub.

I don't want that old versions, probably stopped working, still be available for download without any warning.

I would prefer to include in a deprecation message that uptodate AppImages for arm32 are still available to download from https://mcpelauncher.readthedocs.io.

Original Issue:
https://github.com/flathub/io.mrarm.mcpelauncher/issues/54

Similar Issue: https://github.com/flathub/flathub/issues/1531.

**Comment by hfiguiere** [comment]
there is no mechanism for that.

my take is that RaspberryPi users should use a 64-bits OS. it still baffles me the RaspberryPi foundation hide it away.

**Comment by vchernin** [comment]
For what it's worth the amount of amount of people using the [arm32 builds doesn't seem very high](https://klausenbusk.github.io/flathub-stats/#ref=io.mrarm.mcpelauncher&interval=infinity&downloadType=installs%2Bupdates). You can click on the x86_64 and aarch64 buttons to remove them from the graph. Unfortunately that website doesn't easily give an exact number over time.

**Comment by ChristopherHX** [comment]
I am able to install 64bit linux on 64bit devices, but the raspberry pi 2 I mentioned doesn't have one (cortex-a7 armv7l, if I remember correctly).

You are right arm32 is a minority, but the same thing happend to i386 one year before.
I was told that I should open an issue at this repository (https://github.com/flathub/io.mrarm.mcpelauncher/issues/54#issuecomment-925608735).

Feel free to close this as a won't fix, due to this fact I refused to update the kde sdk of this flatpak.

**Comment by barthalion** [comment]
Please re-open/reply here when you upgrade SDK again and you'll need EOL'ing one architecture.

**Comment by ChristopherHX** [comment]
I have fixed big issue I had with the SDK upgrade and published it to the default branch.
So arm32 builds will get outdated once mojang releases Minecraft 1.17.40 in some weeks or months and I publish an update.

I wonder if it would work to use github actions, probably bad praxis. (might prevent removal of EOL runtimes + sdk)
- to commit the arm manifest (with EOL SDK) for some seconds to create an updated official build
- force push the branch ca. 5 min later for x86_64 and aarch64 with the current SDK

_I think I cannot reopen this issue even if I want to do it_

**Comment by ChristopherHX** [comment]
I'm closing this since arm64 is now also affected for me, because somehow the flatpak sdk's get pretty unstable recently.

arch|lastest usable sdk version for me
---|---
armv7|5.14
arm64|5.15 ( Reverted after bug reports from 5.15-21.08 )
amd64|5.15-21.08

**Comment by ChristopherHX** [comment]
@hfiguiere @barthalion I discovered that there is a mechanism for deprecating on architecture on flathub, but I expected you should be aware of it if that exist.

Add flathub.json to master
```json
{
    "only-arches": [ "arm" ],
    "end-of-life": "My deprecation message"
}
```
Publish it

Finally remove the file again from master

Only those installing the arm version see the deprecation message.

**Comment by barthalion** [comment]
That's hacky, but I like it! Please make sure to report any issues with KDE runtimes to KDE maintainers at https://invent.kde.org/packaging/flatpak-kde-runtime/
