### ISSUE TITLE
Add filters and sorting options 

### ISSUE THREAD

**Issue by andrew712-1** [flathub/flathub#2530]
Add filters and sorting options to all pages. It's essential that people could visit this page https://flathub.org/apps/collection/popular and check a box where it says "show only those which are FOSS" or "show only those which are proprietary", etc... 
Or for this page https://flathub.org/apps/category/All to be able to sort them by **last updated**, etc.

**Comment by haggen88** [comment]
[#217 related](https://github.com/flathub/linux-store-frontend/issues/217)
