### ISSUE TITLE
Name of '.Debug' extension deviates from main package for org.claws_mail.Claws-Mail

### ISSUE THREAD

**Issue by cobratbq** [flathub/flathub#2531]
[Package/repo Claws-Mail](https://github.com/flathub/org.claws_mail.Claws-Mail)

See `flatpak remote-info -m flathub org.claws_mail.Claws-Mail`.

I'm by no means an expert on flatpak, flatpak-builder or naming. I just discovered that by default the `.Debug` extension has an naming inconsistency compared to the main package identifier. I aligned the name for the main package, so I'm hoping you have more insight in whether or not we can fix this. I suspect that the naming convenients have changed for this particular edge case. (See [D-Bus Specification: Valid names](https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-names).)

Main package: `org.claws_mail.Claws-Mail`
Debug extension: `org.claws_mail.Claws_Mail.Debug`

Users that look into this are having trouble finding/installing the debug symbols, and consequently even starting the debug process. I am documenting this inconsistency, but it would help if we can align the naming of extensions. Fortunately one user reported this in https://github.com/flathub/org.claws_mail.Claws-Mail/issues/19.

Do you have any insight or advice on what is the best way to solve this?  
(preferrably to the benefit of users and consistency in general)

`org.claws_mail.Claws-Mail` metadata:
```
[Application]
name=org.claws_mail.Claws-Mail
runtime=org.freedesktop.Platform/x86_64/20.08
sdk=org.freedesktop.Sdk/x86_64/20.08
command=claws-mail-wrapper.sh

[Context]
shared=network;ipc;
sockets=x11;wayland;pcsc;
filesystems=home;

[Session Bus Policy]
org.freedesktop.Notifications=talk

[Extension org.claws_mail.Claws_Mail.Locale]
directory=share/runtime/locale
autodelete=true
locale-subset=true

[Extension org.claws_mail.Claws_Mail.Debug]
directory=lib/debug
autodelete=true
no-autodownload=true

[Build]
built-extensions=org.claws_mail.Claws_Mail.Locale;org.claws_mail.Claws_Mail.Debug;org.claws_mail.Claws_Mail.Sources;
```

**Comment by barthalion** [comment]
This is because dashes are allowed only in the last component of the ID, so when `.Debug` (or any other) is appended, the dash is transformed into underscore. TLDR IDs are tied to D-Bus names, there's longer explanation at https://github.com/flatpak/flatpak-builder/issues/37#issuecomment-335248867.
