### ISSUE TITLE
Handling ABI dependent extensions

### ISSUE THREAD

**Issue by tinywrkb** [flathub/flathub#2533]
The [Fcitx5](https://github.com/flathub/org.fcitx.Fcitx5) and its extensions are outdated quite a while now, so I thought about adding `f-e-d-c` support, but then noticed the dependency of extesnsion on libs from the app's package.  

How to deal with ABI breakage of libs from the app's package?  
The updated app needed to be in the repo in order to build updated extensions, but shouldn't be available to the user.  
Is there a way to have an interim branch and hold off pushing the updated app to the stable branch?  
Is it possible to avoid rebuilding, and just copy the refs from the interim branch to the stable branch after the app and its extensions were updated?

CC @wengxt the developer Fcitx5 and its Flathub app maintainer.

**Comment by barthalion** [comment]
I don't think it's really doable without coordinated (e.g. with me) mass-merge of changes. Re-commiting a non-stable ref to the stable one is possible but also requires my direct involvement on the infrastructure.

**Comment by tinywrkb** [comment]
@barthalion thanks for responding.  
Specifically for Fcitx5, the maintainer of the Flathub app should join the discussion and give his opinion.

For the general case, I hope maybe we can have some guidelines written somewhere, at least mention that this is a possible problem.  

> I don't think it's really doable without coordinated (e.g. with me) mass-merge of changes. Re-commiting a non-stable ref to the stable one is possible but also requires my direct involvement on the infrastructure.

How many of you there are? Adding workload to Flathub's developers seems to me like something that should be avoided.

As I see it, these are the possible solutions that should be added to the guidelines:

* Don't use extensions, package everything with the app.
* The app should manage its plugins/addons instead of using Flatpak extensions. Apps like Steam, Lutris, RetroArch, and Kodi, download and run executable code, so this is nothing new, but will fail if `~/` is mounted with `noexec`.
* Give the developer access to push directly into Flathub. Isn't it time to decide on an official policy? I haven't seen one.

**Comment by tinywrkb** [comment]
I'm closing this as it doesn't look like there's an interest in this, and I suggested to the maintainer of the affected app to use bundled extensions method ([see PR](https://github.com/flathub/org.fcitx.Fcitx5/pull/4), or get authorization to push directly to Flathub.
