### ISSUE TITLE
Add some missing gnome softwares please

### ISSUE THREAD

**Issue by lumingzh** [flathub/flathub#2535]
There are three important gnome softwares missing in flathub:

- [sushi](https://gitlab.gnome.org/GNOME/sushi)
- [simplescan](https://gitlab.gnome.org/GNOME/simple-scan)
- [gnome-screenshot](https://gitlab.gnome.org/GNOME/gnome-screenshot)

Please add them, thank you very much.

**Comment by barthalion** [comment]
This is up to maintainers of these applications to submit them. We don't take "requests" as all apps are welcome on Flathub.
