### ISSUE TITLE
"com.visualstudio.code" and "com.visualstudio.code" are not being adequately maintained.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [flathub/flathub#2542]
http://github.com/flathub/com.visualstudio.code and http://github.com/flathub/com.visualstudio.code.insiders are not being adequately maintained. Observe the pull requests that are pending for http://github.com/flathub/com.visualstudio.code for demonstration of this.

**Comment by barthalion** [comment]
And you, of course, volunteer to pick up the maintenance? Unless that's the case, I don't see the point of this issue.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/flathub/flathub/issues/2542#issuecomment-931653057.

I have not much experience of moderation of such, but I can certainly verify that application version updates are from their upsteam source, and that their sha256 signatures are correct. Shall you mind adding me as a contributor to it? I would much rather remediate these problems than lazily whine.

**Comment by barthalion** [comment]
Please ping me on PRs you consider ready to merge, and I will have a look, and invite you to collaborators after a few.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/flathub/flathub/issues/2542#issuecomment-931707116.

I am very thankful, @barthalion. I shall cease discussion within this issue thus.
