### ISSUE TITLE
Please enable issues for "org.mozilla.firefox.BaseApp".

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [flathub/flathub#2543]
Please enable issues for http://github.com/flathub/org.mozilla.firefox.BaseApp again, because I am desiring the creation of one issue that is specifically for the flatpak version of that software: its openh264 decode performance is abysmal. This is not affecting the DEB or RPM versions of it, so http://github.com/flathub/org.mozilla.firefox.BaseApp is the only place that it is appearing to be worth reporting at, because meaningful discussion (and, hopefully, improvement) shall only be able to occur there due to the integrated nature of http://github.com's reporting and developmental system.

**Comment by barthalion** [comment]
If there are issues with openh264, it should be reported to Cisco; in general it sounds like you simply haven't installed the ffmpeg-full extension. There's nothing to report about the base app here.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/flathub/flathub/issues/2543#issuecomment-931663806.

I also want to create an issue so that I shall be notified when the maintainers update its dependency of org.freedesktop.Platform to 21.08, si that I shall be able to remove 20.08 from my system. We might realise that others have similar retionale for re-enablement of the issues tab.

Have the developers at Mozilla requested disablement of it? If so, I shall mention this to them rather than here.
