### ISSUE TITLE
https://github.com/flathub/com.notepadqq.Notepadqq unmaintained

### ISSUE THREAD

**Issue by akallabeth** [flathub/flathub#2558]
The repo seems dead for 2 years now.

**Comment by hfiguiere** [comment]
do you want to maintain it? there is no PR pending.

**Comment by akallabeth** [comment]
did have a look at updating to `qt 5.15` but did not succeed so far.
as for maintaining, sorry, would be one project too much.

**Comment by hfiguiere** [comment]
I just submitted a PR to update the beta branch 
https://github.com/flathub/com.notepadqq.Notepadqq/pull/8

**Comment by hfiguiere** [comment]
And for the stable branch https://github.com/flathub/com.notepadqq.Notepadqq/pull/9

**Comment by barthalion** [comment]
Thanks @hfiguiere!
