### ISSUE TITLE
io.qt.qtwebengine.BaseApp: Change default branch to branch/5.15-21.08

### ISSUE THREAD

**Issue by tinywrkb** [flathub/flathub#2573]
Another maintenance request, changing the default branch of [io.qt.qtwebengine.BaseApp](https://github.com/flathub/io.qt.qtwebengine.BaseApp) to `branch/5.15-21.08`, so flathubbot will run f-e-d-c and open update PRs against the branch of the most recent runtime release, KDE `5.15-21.08'.

CC @aleixpol

**Comment by nedrichards** [comment]
Done
