### ISSUE TITLE
Remove beta from protected branches

### ISSUE THREAD

**Issue by MehdiChinoune** [flathub/flathub#2606]
Recently, I tried to force-push some changes to beta branch before I found that is now a protected branch.

Please remove that, because I rebase it on the master branch.

**Comment by gasinvein** [comment]
I suppose this is intentional. Git branches that the flatpak is built from (`beta` among them) should have visible history.

**Comment by barthalion** [comment]
Yes, this was an oversight on our end that `beta` branch was not being protected. Unfortunately, you will need to switch to merging branches instead.

**Comment by divVerent** [comment]
This is rather annoying as it means the history of the branches diverges more and more. I tried fixing it up in io.github.divverent.aaaaxy but there's still one merge commit that I can't get on both equally.

Can we maybe allow fastforward merging pull requests too, in addition to merging, rebasing and squashing?

**Comment by barthalion** [comment]
Yes, I'm happy to enable it once it's actually implemented by GitHub. It isn't, though.
