### ISSUE TITLE
Please add company permissions for my repo

### ISSUE THREAD

**Issue by akallabeth** [flathub/flathub#2613]
I´d like to ask you to add https://github.com/thincast company permissions to https://github.com/flathub/com.thincast.client as I don´t seem to be able to do that myself.
thank you!

**Comment by barthalion** [comment]
Hey @akallabeth, unfortunately GitHub does not allow adding organizations as contributors of the repo. Do you have some kind of service account (e.g. used for billing) we can invite with permissions elevated to let you invite specific usernames?

**Comment by akallabeth** [comment]
@barthalion in that case, please either @nfedera or myself.
thank you

**Comment by barthalion** [comment]
I've resent an invitation to @nfedera and raised your privileges to admin, so you should be able to manage collaborators on your own now,

**Comment by akallabeth** [comment]
@barthalion thank you, it is working.
