### ISSUE TITLE
net.blockbench.Blockbench auto build on merge to master not happening

### ISSUE THREAD

**Issue by daenney** [flathub/flathub#2618]
We recently added Blockbench in #2594 and I noticed an update today with a PR pending.

There seem to be 2 things wrong-ish with the repo setup:
* Auto-merge of PRs isn't happening: https://github.com/flathub/net.blockbench.Blockbench/actions/runs/1411460042
  ``` 
  Run /entrypoint.py
  GITHUB_TOKEN environment variable is not set
  Error: Process completed with exit code 1.
  ```
  I'm not sure who is supposed to setup that token or where it's supposed to come from, but I don't have permissions to do so
* After I merged https://github.com/flathub/net.blockbench.Blockbench/pull/1 no build seems to trigger (it looks like it might be queued up in the buildbot but I'm surprised no status shows for that in the mean time on GitHub?)

**Comment by daenney** [comment]
The "Close stale PR" action doesn't look very happy either:

```
Run actions/stale@v1
Error: Error: Input required and not supplied: repo-token
Error: Input required and not supplied: repo-token
```

**Comment by hfiguiere** [comment]
Looks like the build was successfull https://flathub.org/builds/#/builders/28/builds/7844

If you look at the repo, the last commit has a green checkmark.

**Comment by daenney** [comment]
Ah yes. Looks like it only adds status once the build happens, instead of when the build gets queued. That explains my confusion there.

The one thing I'm still not clear about is the automatically created GitHub Actions flows being upset about missing credentials.

**Comment by daenney** [comment]
@barthalion Any chance I could get some help on figuring out why the Actions workflows are broken? I don't have admin access to the repo so I can't really do anything about missing secrets.

**Comment by barthalion** [comment]
The primary problem here is that we haven't caught your submission was based on a wrong branch. All these files are not supposed to be present in an application repo. I have just pushed a commit that removes them.

To make f-e-d-c automerge updates, you need to set up an appropriate key in flathub.json. See https://github.com/flathub/flatpak-external-data-checker/#automatically-merging-prs for details.

**Comment by tmewett** [comment]
Hi, we're also suddenly getting "GITHUB_TOKEN not set" errors, see above linked issue. Was our repo also not set up correctly? It was made by a Flathub bot: https://github.com/flathub/flathub/pull/1558#issuecomment-639385721

**Comment by daenney** [comment]
I would suggest opening up a separate issue, since this is a 2 year old issue and related to a different app.
