### ISSUE TITLE
Add a collection ID and use ostree-metadata

### ISSUE THREAD

**Issue by mwleeds** [flathub/flathub#262]
In order to allow P2P redistribution of Flathub apps (via LANs and USB drives), the server repository needs to have a collection ID set, and use the `ostree-metadata` ref to store repository metadata. There are also keys in the summary file and per-commit metadata that need to be created, so this will require all the commits to be regenerated.

We can start with just enabling them for clients that actively set collection IDs in their local configuration to work out any bugs in the P2P code paths, and move on to deploying them to everyone later (which should probably be after the P2P code in flatpak and ostree is moved outside `--enable-p2p` and `--enable-experimental-api`).

cc: @ramcq

**Comment by ramcq** [comment]
> We can start with just enabling them for clients that actively set collection IDs in their local configuration to work out any bugs in the P2P code paths, and move on to deploying them to everyone later (which should probably be after the P2P code in flatpak and ostree is moved outside --enable-p2p and --enable-experimental-api).

I'm not sure how we can enable things for some clients but not others - there's only one repo and it's served entirely passively from files on disk via nginx. We'd have to turn it on and then from then on I guess the builds/commits would get the right stuff added.

But - generally speaking we're not hugely keen on turning on experimental code in the tooling that controls the archive. It would be good if the collection ID functionality could be moved in an "write only" way (ie we publish the new stuff, but don't otherwise change the way lookups are done?) outside of the ifdefs, which we'd need to co-ordinate and advocate for upstream if you think it's baked/tested enough and the interfaces/APIs are stable.

**Comment by pwithnall** [comment]
> It would be good if the collection ID functionality could be moved in an "write only" way (ie we publish the new stuff, but don't otherwise change the way lookups are done?) outside of the ifdefs, which we'd need to co-ordinate and advocate for upstream if you think it's baked/tested enough and the interfaces/APIs are stable.

There is a deployment path for this, which is precisely as you say. Enabling the collection ID stuff on the repository doesn’t change how the clients use the repository *until* the client sets the `collection-id=` key in their local OSTree repo config. You can do that automatically for all clients (who have a new enough flatpak version) by setting the `xa.collection-id=` key in the repository’s summary metadata; you’d typically do this once you’re happy that everything is working nicely for the clients who’ve tested the repository with collection ID support enabled manually.

You can set the `xa.collection-id=` key using a command like
```
ostree --repo=my/repo/path summary --update --add-metadata="xa.collection-id='org.flathub.Apps'"
```
It will update the `summary` file and the `ostree-metadata` branch.

The repository should always continue to work for old clients who don’t have collection ID support.

**Comment by ramcq** [comment]
Right - what about the per-commit metadata that @mwleeds mentioned?

**Comment by pwithnall** [comment]
The per-commit metadata are the `ostree.ref-binding=` and `ostree.collection-binding=` keys. Any client which has a `collection-id=` key in its local configuration will *require* those metadata to be set in any commits it pulls. Any client which *doesn’t* have a `collection-id=` configured will only look at those keys to check they’re not invalid, without requiring them to be set.

If you generate those metadata in any new commits, and clients only pull the latest commit for each ref/app, then once each app has been rebuilt once things should be good to go.

**Comment by ramcq** [comment]
So how do we get ostree.collection-binding added to the commits on the repo?

**Comment by pwithnall** [comment]
Ensure those commits are being generated by a new-enough version of OSTree and flatpak (with the `--enable-experimental-api`/`--enable-p2p` configure flags enabled), in a repository where the `collection-id=` is set in the repository `config`.

**Comment by ramcq** [comment]
@mwleeds Supposing that Flatpak won't do this stuff without ostree having the new API exported (is this at all avoidable?) we're going to have to do a certain amount of packaging/integration crap to achieve this on Flathub. Namely, import ostree and flatpak into a COPR and maintain our own branch with --enable-experimental-api/--enable-p2p until such time that they are the default upstream, as adding ABI to libostree isn't something we can push out to CentOS regular Flatpak/ostree EPEL users. Hopefully running this on the repo master which does flatpak build-commit-from and then build-update-repo is sufficient to add the new bindings and metadata - can you verify that this is the case?

**Comment by mwleeds** [comment]
@ramcq yes, `build-commit-from` adds the metadata [here](https://github.com/flatpak/flatpak/blob/869a6640c47ab75c938d483057a3b7f034bc26b8/app/flatpak-builtins-build-commit-from.c#L438), and `build-update-repo` does it in `flatpak_repo_update` so you should be good to do it on the repo master. Just remember **not** to set `deploy-collection-id` (which is a config option) or `xa.collection-id` (which is a metadata key).

**Comment by mwleeds** [comment]
And I can't think of a way you could avoid making a COPR

**Comment by ramcq** [comment]
All done!
