### ISSUE TITLE
Can’t make connection from riseup vpn

### ISSUE THREAD

**Issue by boistordu** [flathub/flathub#2628]
I've made all the details available here while thinking it was a problem with flatpack itself 

https://github.com/flatpak/flatpak/issues/4550

**Comment by boistordu** [comment]
Still connection refused 2 days after... what information do you need to make your cdn stop that?

**Comment by barthalion** [comment]
You would need to reach out to Fastly to check why your IP is blocked. We don't do anything specific in CDN configuration to disallow VPN providers.

**Comment by boistordu** [comment]
Are you sure? Because on their support section:

```
Using the IP block list - Editing a blocked IP address
You can edit a blocked IP address or subnet mask at any time. To edit an IP address or a subnet mask, follow the steps below:
```

**Comment by barthalion** [comment]
I'm aware such feature exists, but to repeat once more, we don't explicitly block any IPs. It's something you should ask Fastly support about.
