### ISSUE TITLE
Requesting to become a maintainer for org.geany.Geany

### ISSUE THREAD

**Issue by HugLifeTiZ** [flathub/flathub#2647]
Hi there. I'm requesting to become a maintainer for Geany because it has had a new stable release that has not been integrated for over a month, and a multitude of pull requests that have sit dormant. I am an active user of Geany's flatpak, so I have a vested interest in keeping it up-to-date.

Tagging @barthalion as requested in Matrix; thanks kindly!

**Comment by barthalion** [comment]
I've sent you an invitation. Thanks!
