### ISSUE TITLE
Current maintenance "org.kde.dolphin" is not adequate.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [flathub/flathub#2657]
http://github.com/flathub/org.kde.dolphin is the flatpak package of the most popular file manager for the KDE Desktop Environment. Adequate utilisation of http://github.com/flathub/org.kde.dolphin is barely possible because invocation of the configurator of http://github.com/flathub/org.kde.dolphin is not possible. I shall assist however I am able to assist, but for assistance to occur, response to submission of notification of errata must occur. Consequently, is anybody able to ensure that maintenance shall resume?

**Comment by hfiguiere** [comment]
The proper place to file issue specific to this project (Dolphin) is http://github.com/flathub/org.kde.dolphin/issues/

**Comment by barthalion** [comment]
paging @flathub/kde 

But yeah, that's not a Flathub-wide or infra related issue, so I will close it.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This comment is response to "http://github.com/flathub/flathub/issues/2657#issuecomment-981124967".

I was significantly confident during submission of this issue that observers of it would answer my request after investigation of whether my conclusion is rational, thereby observing the lack of current maintenance.

I have realised that "http://github.com/flathub/org.kde.dolphin/issues" is where notification of problemacy should be submitted to, but my rationale for submission to http://github.com/flathub/flathub/issues/2657 was that I was believing that all maintenance of "http://github.com/flathub/org.kde.dolphin/issues" had ceased.

I have subsequently observed "http://github.com/flathub/org.kde.dolphin/pull/58", which is demonstrative that maintenance is occurring. Consequently, my rationale for submission of "http://github.com/flathub/flathub/issues/2657" was potentially not correct, and provision of it is not significantly useful.

I am apologetic for my wastage of time. Despite my apology, please do consider assisting maintenance of the package until I am able to.
