### ISSUE TITLE
Create policy for minimal flatpak version

### ISSUE THREAD

**Issue by SISheogorath** [flathub/flathub#2660]
As part of the build artefact we can define a minimal Flatpak version (using `--require-version=` as part of `finish-args`) and signal to users, when their Flatpak versions become too old. We should use this prevent us from "backporting" stuff and from ruining the user experience of people running older flatpak versions, which might simply end up with broken apps.

What I'm undecided about is if we want to:
- set it entirely on an app-by-app basis
- set it globally for FlatHub
- set a minimal version for all apps on FlatHub and allow per-app overrides
- give a general recommendation what should be set, verify this on new submissions and over all try to encourage the usage

So what do you suggest? Do you consider this idea useful or rather pointless?

**Comment by vchernin** [comment]
Relevant: https://discourse.flathub.org/t/block-outdated-flatpak-clients/1389

**Comment by jakobjakobson13** [comment]
I'd vote for the last option with the option to update the required flatpak version within the already exisiting manifests in a semi-automated way (perhaps by using fedc?)

**Comment by nedrichards** [comment]
We've always encouraged this on an app by app basis up until now (and the first usage was *very* shortly after the capability was introduced). We've always thought that one of the strengths of the flatpak mindset is that it attempts to decouple as much as possible the applications and runtime versioning from the base os so I'd be reluctant to do anything to undermine that class of users without an extremely good reason. I *am* interested in the idea of a linter or similar tool that can help identify this semi-automatically though, that's absolutely something we'd add to the build validation suite.

**Comment by bbhtt** [comment]
> set it globally for FlatHub
> set a minimal version for all apps on FlatHub and allow per-app overrides

Can't be done. we can't fail all builds asking everyone to add a `--require-version=x.y.z`. 

I don't think a minimal version policy or recommendation makes sense either, it's up to the individual developers and maintainers to decide.

If we wanted to remove support for older Flatpak clients this can be done serverside using user-agent Flatpak sends. But that's a whole different issue and needs a really strong reason.
