### ISSUE TITLE
Request for giving access for KDE app repos to Maui app developer 

### ISSUE THREAD

**Issue by espidev** [flathub/flathub#2671]
Request to give https://github.com/milohr access to kde apps in order to maintain Maui app manifests.

Maui apps:
https://github.com/flathub/org.kde.index
https://github.com/flathub/org.kde.vvave
https://github.com/flathub/org.kde.pix

**Comment by nedrichards** [comment]
I've sent an invitation to @milohr to join the KDE team so they'll get access to those repos and more.
