### ISSUE TITLE
is normal app allowed to be base-apps in flathub?

### ISSUE THREAD

**Issue by MrMarukesu** [flathub/flathub#268]
the case, Indicator-kdeconnect depend, oblivious, of kdeconnect. so,i thinking in use org.kde.kdeconnect for the base, since it make no need to add kde depedencies to app, but i don't known if it accept in flathub or only true baseapp like io.atom.electron.BaseApp are accepted.

**Comment by TingPing** [comment]
How exactly does indicator-kdeconnect depend upon kdeconnect?

**Comment by MrMarukesu** [comment]
its depends of the d-bus daemon, he works if the kdeconnect is installed in the system or in another flatpak anyway

**Comment by TingPing** [comment]
To be honest I sort of question if indicator-kdeconnect made sense to be on flathub at all since it isn't a regular application.

**Comment by nedrichards** [comment]
The short answer is 'yes', you can use another app as a baseapp. Will kdeconnect actually work inside a container though? Or does it need a lot of platform services.

**Comment by MrMarukesu** [comment]
I use the kdeconnect from KDE's flatpakrepo, so, yes its works

@TingPing I don't understand the regular application point

**Comment by nedrichards** [comment]
Huh, it does indeed work very well, I'm impressed. @MrMarukesu I'd certainly support seeing a cleaned up version of that manifest on flathub: https://github.com/KDE/flatpak-kde-applications/blob/master/org.kde.kdeconnect.json Feel free to work with the kdeconnect community to send a pull request. And after that you could consider using it as a baseapp if you require.

**Comment by TingPing** [comment]
> @TingPing I don't understand the regular application point

Is that package useful without any host daemons?
