### ISSUE TITLE
Add status link to the flathub website

### ISSUE THREAD

**Issue by csoriano1618** [flathub/flathub#269]
So it can be tracked if something goes bad - https://status.flathub.org/

**Comment by TingPing** [comment]
Probably best reported here: https://github.com/flathub/flathub.org

**Comment by csoriano1618** [comment]
Sure, how can I move the issue?

**Comment by TingPing** [comment]
There is no "move" on github, just open a new one and close the old.

**Comment by csoriano1618** [comment]
omg :D
