### ISSUE TITLE
Most likely, my invitations has expired

### ISSUE THREAD

**Issue by alexkdeveloper** [flathub/flathub#2700]
It looks like I have a problem with invitations. When I accepted the invitations, a message with a red background appeared at the top of the page. I don't remember what was written there, but most likely it was a message about some kind of error. 
I have read some questions here. There have already been similar problems. Most likely, my invitations has expired. Can I get new invitations for the specified repositories?

flathub/com.github.alexkdeveloper.desktop-files-creator
flathub/com.github.alexkdeveloper.somafm

**Comment by barthalion** [comment]
Hey Alex, I've just sent you fresh invitations. Please make sure to accept them, or they'll expire again!

**Comment by alexkdeveloper** [comment]
Thanks!
