### ISSUE TITLE
Delete old version of GST for ARM from Flathub

### ISSUE THREAD

**Issue by Eonfge** [flathub/flathub#2718]
@barthalion @nedrichards Hey, this is an issue that you'll have to look into.

GST doesn't support ARM, but on Flathub there are still some old ARM packages available, that users can download from the Software Center or using `flatpak install`. This then creates [erroneous error reports](https://gitlab.com/leinardi/gst/-/issues/33). I had this issue myself with a PineBook Pro. Only after talking to @leinardi did I realise that I was accidentally using a four old version of an application that my hardare didn't support.

Considering the situation, I would ask you to go into the actual repository and to flag/remove the old packages for GST on ARM.

**Comment by barthalion** [comment]
I think I must have handled it already because the only available build in the ostree repo is for x86_64.
