### ISSUE TITLE
Delete beta branch on com.github.PintaProject.Pinta

### ISSUE THREAD

**Issue by darkdragon-001** [flathub/flathub#2727]
The beta branch is no longer needed. See https://github.com/flathub/com.github.PintaProject.Pinta/pull/16#issuecomment-1003581886
Please delete this branch.

**Comment by nedrichards** [comment]
Done

**Comment by nedrichards** [comment]
Actually not totally done, will leave this open until it's properly sorted as that needs something I can't do right now.

**Comment by barthalion** [comment]
Done also server-side.
