### ISSUE TITLE
Applications missing release information

### ISSUE THREAD

**Issue by TingPing** [flathub/flathub#273]
- [ ] ch.x29a.playitslowly
- [ ] com.chez.GrafX2
- [ ] com.github.libresprite.LibreSprite
- [ ] com.github.themix_project.Oomox
- [ ] com.play0ad.zeroad
- [ ] com.scoutshonour.Digital
- [ ] com.scoutshonour.dtipbijays
- [ ] com.tux4kids.tuxtype
- [ ] com.viber.Viber
- [ ] fr.free.Homebank
- [ ] id.sideka.App
- [ ] io.github.cloose.CuteMarkEd
- [ ] io.github.qtox.qTox
- [ ] io.gitlab.osslugaru.Lugaru
- [ ] io.howl.Editor
- [ ] io.webtorrent.WebTorrent
- [ ] net.jami.Jami
- [ ] net.olofson.KoboDeluxe
- [ ] net.sourceforge.ExtremeTuxRacer
- [ ] net.sourceforge.Ri-li
- [ ] net.sourceforge.TuxFootball
- [ ] net.sourceforge.atanks
- [ ] net.sourceforge.btanks
- [ ] net.sourceforge.mars-game
- [ ] nl.openoffice.bluefish
- [ ] org.fedoraproject.MediaWriter
- [ ] org.freeciv.Freeciv
- [ ] org.freecol.FreeCol
- [ ] org.freedesktop.GstDebugViewer
- [ ] org.fritzing.Fritzing
- [ ] org.gnome.Devhelp
- [ ] org.gnome.OfficeRunner
- [ ] org.gnome.Quadrapassel
- [ ] org.gnome.frogr
- [ ] org.gnome.gbrainy
- [ ] org.gnome.glabels-3
- [ ] org.homelinuxserver.vance.biblereader
- [ ] org.kde.dolphin
- [ ] org.kde.gcompris
- [ ] org.kde.kalzium
- [ ] org.kde.kapman
- [ ] org.kde.katomic
- [ ] org.kde.kblocks
- [ ] org.kde.kbounce
- [ ] org.kde.kbruch
- [ ] org.kde.kdiamond
- [ ] org.kde.kgeography
- [ ] org.kde.kgoldrunner
- [ ] org.kde.khangman
- [ ] org.kde.kigo
- [ ] org.kde.killbots
- [ ] org.kde.kjumpingcube
- [ ] org.kde.klickety
- [ ] org.kde.klines
- [ ] org.kde.knavalbattle
- [ ] org.kde.knetwalk
- [ ] org.kde.kolourpaint
- [ ] org.kde.ksquares
- [ ] org.kde.ksudoku
- [ ] org.kde.ktuberling
- [ ] org.kde.kubrick
- [ ] org.kde.kwordquiz
- [ ] org.kde.kxstitch
- [ ] org.kde.palapeli
- [ ] org.mapeditor.Tiled
- [ ] org.megaglest.MegaGlest
- [ ] org.mixxx.Mixxx
- [ ] org.seul.pingus
- [ ] org.tordini.flavio.Minitube
- [ ] org.tuxfamily.XMoto
- [ ] org.xiphos.Xiphos
- [ ] uk.co.mangobrain.Infector

---

Source for future reference:

```python
#!/usr/bin/env python3

from os import path
from gi.repository import GLib, Gio
from gi.repository import AppStreamGlib as As

store = As.Store()
appstream_path = path.join(GLib.get_user_data_dir(), 'flatpak', 'appstream',
                           'flathub', 'x86_64', 'active', 'appstream.xml.gz')
store.from_file(Gio.File.new_for_path(appstream_path))

bad_apps = sorted(app.get_id_filename() for app in store.get_apps()
                  if not app.get_release_default() and app.get_kind() == As.AppKind.DESKTOP)
for app in bad_apps:
    print('- [ ] ' + app)
```

**Comment by TingPing** [comment]
@Pointedstick Might be of interest to you =)

**Comment by gnumdk** [comment]
What is needed?
https://gitlab.gnome.org/gnumdk/lollypop/issues/1313

**Comment by Pointedstick** [comment]
Yeah, that! I just submitted a patch for you: https://gitlab.gnome.org/gnumdk/lollypop/merge_requests/1298

**Comment by Pointedstick** [comment]
Endless Sky is already done upstream, FWIW: https://github.com/endless-sky/endless-sky/pull/3455

**Comment by AsciiWolf** [comment]
I have [added](https://github.com/flathub/ws.openarena.OpenArena/commit/5d1a4120be5b17056b28597cf6c5afcaeffba2f2) the release information for OpenArena.

**Comment by Pointedstick** [comment]
Submitted a patch for Inkscape: https://gitlab.com/inkscape/inkscape/merge_requests/228

Oh and BTW, they accepted my patch to fix the app ID. Probably you'll be able to just take the upstream file unadulterated soon.

**Comment by nedrichards** [comment]
Great! Many thanks

**Comment by TingPing** [comment]
@Pointedstick Permission granted.

**Comment by Pointedstick** [comment]
Woohoo! Thanks, I'm honored!

**Comment by joergister** [comment]
I worked on the Audacity `appdata.xml` file and added release information and OARS (content rating), but I'm not quite sure if the `appdata.xml` file needs to be renamed to `org.audacityteam.Audacity.appdata.xml` or not.
Also, I don't know if the  `<launchable type="desktop">audacity.desktop</launchable> ` tag
needs to be renamed to  `<launchable type="desktop">org.audacityteam.Audacity.desktop</launchable>`
or not. In case it also needs to be renamed, the .desktop files obviously needs to be renamed as-well.

@Pointedstick  would you mind reviewing my changes and answer my questions so that this can be submitted to the Audacity devs? 
https://github.com/joergister/audacity/pull/1/files

**Comment by TingPing** [comment]
> I'm not quite sure if the appdata.xml file needs to be renamed to org.audacityteam.Audacity.appdata.xml or not.

It isn't strictly required outside of `flatpak` but its a bit odd to have a filename not matching the app-id.

> Also, I don't know if the <launchable type="desktop">audacity.desktop</launchable> tag
needs to be renamed to <launchable type="desktop">org.audacityteam.Audacity.desktop</launchable>
or not. In case it also needs to be renamed, the .desktop files obviously needs to be renamed as-well.

The `desktop-file-spec` does recommend you have an app-id style desktop-id.

**Comment by TingPing** [comment]
Also `<launchable type="desktop">audacity.desktop</launchable>` is invalid anyway, the type is `"desktop-id"`.

**Comment by joergister** [comment]
thank you for the review, it helped me a lot.

I renamed the `.desktop` file to `org.audacityteam.Audacity.desktop` and  changed 

`launchable type="desktop">audacity.desktop</launchable>` 
to
`launchable type="desktop-id">org.audacityteam.Audacity.desktop</launchable>` 
 
Also I renamed the appdata file to `org.audacityteam.Audacity.appdata.xml`

**Comment by joergister** [comment]
Ah, one more question:
The original .desktop file used to have an .in ending.

I need to add this to the modified version as well, right?

**Comment by TingPing** [comment]
The `.in` usually means it was processed by the build system to replace some variables. That likely won't change and the build system would need to be updated accordingly.

**Comment by joergister** [comment]
Mmm OK so a bit more effort needed there

**Comment by joergister** [comment]
didn't rename the .desktop file but opened a pull request with added release informations, OARS, fixed type `desktop` > `desktop-id` and renamed the appdata.xml file to match the appstream spec
https://github.com/audacity/audacity/pull/278

**Comment by AsavarTzeth** [comment]
You can cross [com.github.wwmm.pulseeffects](https://github.com/flathub/com.github.wwmm.pulseeffects) of the list.

I added release information as well as OARS metadata as a part of my 4.x push today, see https://github.com/flathub/com.github.wwmm.pulseeffects/pull/11.

**Comment by Pointedstick** [comment]
Thanks, I've updated it!

**Comment by gjanssens** [comment]
The most recent push of org.gnucash.GnuCash ships with release information in its appdata file:
https://github.com/flathub/org.gnucash.GnuCash/commit/7f7351a71d588bc9163b3c09319fc59068b691de

 However it's not showing on the flathub app page here:
https://flathub.org/apps/details/org.gnucash.GnuCash

I have no clue why. Perhaps because of #1080 ?

**Comment by Eonfge** [comment]
> io.github.FreeDM
> io.github.Freedoom-Phase-1
> io.github.Freedoom-Phase-2
> org.wesnoth.Wesnoth
> org.supertuxproject.SuperTux

These apps have been updated and are now provided with proper age ratings. Others might also have been updated, so perhaps it's best to just regenerate the whole list.

**Comment by AsciiWolf** [comment]
>org.frozen_bubble.frozen-bubble

This one was also updated. :)

**Comment by bilelmoussaoui** [comment]
I have regenerated and updated the list.

**Comment by barthalion** [comment]
I don't think there's much point in tracking this now – release information is now required on CI's end.

**Comment by ovari** [comment]
Issue created for net.jami.Jami at https://git.jami.net/savoirfairelinux/jami-client-qt/-/issues/1955
