### ISSUE TITLE
builds failing for com.jetbrains.GoLand

### ISSUE THREAD

**Issue by patriziobruno** [flathub/flathub#2736]
The build for com.jetbrains.GoLand fails on `mirror-screenshots`.

https://flathub.org/builds/#/builders/35/builds/8806/steps/6/logs/stdio

This is blocking https://github.com/flathub/com.jetbrains.GoLand/pull/30

**Comment by barthalion** [comment]
It is really bizarre. I will investigate on Monday (or over the weekend if time allows).

**Comment by akurtakov** [comment]
org.eclipse.Java fails too https://github.com/flathub/org.eclipse.Java/pull/55

**Comment by patriziobruno** [comment]
@barthalion I'll be happy to help if you can point me in the right direction

**Comment by patriziobruno** [comment]
@barthalion is there any way I can help? Is the failing code public?

**Comment by barthalion** [comment]
Fixed via https://github.com/flathub/org.flatpak.Builder/pull/70.

I want to make something clear, though: there's absolutely no reason why GoLand should have access to the entire session bus. You should really drop it.
