### ISSUE TITLE
Arches not listed in "only-arches" continue to serve very old app builds

### ISSUE THREAD

**Issue by kparal** [flathub/flathub#2755]
In [FreeFileSync](https://github.com/flathub/org.freefilesync.FreeFileSync) I have `flathub.json`:
```
{
  "only-arches": ["x86_64", "i386"]
}
```
That's because I serve upstream-provided binary builds (because several reasons), and upstream doesn't build for `aarch64` or `arm`. However, other arches **were** built in the past, when I was building the app directly from source. To my surprise, the app can still be installed from Flathub on `aarch64` and `arm`, but the users receive a very old (2.5 years old) app version. Here's a related [bug report](https://github.com/flathub/org.freefilesync.FreeFileSync/issues/67).

I'd expect that when `"only-arches"` or `"skip-arches"` are configured, then those omitted repos should be purged. Otherwise it can be very confusing for users to receive a years-old build.

Possibly related: #1196

**Comment by hfiguiere** [comment]
you should remove "i386" anyway.

**Comment by p2004a** [comment]
Opened https://github.com/flathub/info.beyondallreason.bar/issues/40 but looks like it's issue upstream that doesn't allow to unlist incorrectly published architectures.

**Comment by bbhtt** [comment]
This likely got purged from the server. I no longer see it.

```
flatpak remote-ls --all --arch=* --columns=ref --user flathub|grep "org.freefilesync.FreeFileSync"

app/org.freefilesync.FreeFileSync/aarch64/stable
app/org.freefilesync.FreeFileSync/x86_64/stable
runtime/org.freefilesync.FreeFileSync.Debug/x86_64/stable
runtime/org.freefilesync.FreeFileSync.Locale/aarch64/stable
runtime/org.freefilesync.FreeFileSync.Locale/x86_64/stable
runtime/org.freefilesync.FreeFileSync.Sources/x86_64/stable
```

Closing.
