### ISSUE TITLE
Flatpak'd Corebird doesn't use the existing translations

### ISSUE THREAD

**Issue by kostich** [flathub/flathub#277]
Latest Corebird flatpak doesn't use the existing translations. Instead, everything is displayed in English.

```
$ flatpak info org.baedert.corebird
Ref: app/org.baedert.corebird/x86_64/stable
ID: org.baedert.corebird
Arch: x86_64
Branch: stable
Origin: flathub
Date: 2017-11-19 08:36:59 +0000
Subject: Update to 1.7.3 (bba63429)
Commit: ae7ae0ef17423054f5697331566fd392dabf20aef0c28e8de0cbec1630a4c53f
Parent: 8c1cb822b79b49588e378976d2ffa6d44f2a831fb62f4c7c551e587d3712473d
Location: /var/lib/flatpak/app/org.baedert.corebird/x86_64/stable/ae7ae0ef17423054f5697331566fd392dabf20aef0c28e8de0cbec1630a4c53f
Installed size: 16,5 MB
Runtime: org.gnome.Platform/x86_64/3.26
```

Host is Fedora Atomic Workstation 27 rebased to the Rawhide and the system locale is set to Serbian Cyrillic.

I've poked a bit in `/var/lib/flatpak/app/org.baedert.corebird/x86_64/stable/some-long-uid/files/share/locale/` and it seems that all the symlinks pointing to the translations are broken. No .mo files in the ../../runtime/locale/*/. Instead, the translations are located in the folder `/var/lib/flatpak/runtime/org.baedert.corebird.Locale/x86_64/stable/some-other-long-uid/files/sr/share/sr/`

Other flatpaks are using the correct system language (KDE and GNOME ones).

**Comment by TingPing** [comment]
Please open against the specific package: https://github.com/flathub/org.baedert.corebird
