### ISSUE TITLE
[Feature Request] Flathub "Verified" icon for applications

### ISSUE THREAD

**Issue by jefetienne** [flathub/flathub#2782]
There typically exists a small sentence or paragraph in every community-maintained flatpak description saying something like "_This wrapper is not verified by, affiliated with, or supported by ..._" or "_This flatpak is maintained by the Flathub community, and is not necessarily endorsed or officially maintained by the upstream developers ..._", but I think it is important that we have some sort of obvious visual communication to the user about an application being "verified", as in packaged from the official development team or lead developer for an application, similar to how Twitter has "verified" users with a checkmark icon next to their name.

Having a verified status is not only important in terms of security, but also in terms of knowing what kind of support to expect. Some flatpaks could be third-party wrappers that break with new server updates or fail to connect because the servers block detected unofficial clients. Oftentimes, projects also get new tickets or issues from users resulting from a flatpak, which get shot down because they didn't realize that the official project did not create or support the flatpak.

I do think rebranded forks from an upstream project could also be verified, such as [PolyMC](https://flathub.org/apps/details/org.polymc.PolyMC), a fork of [MultiMC](https://github.com/MultiMC/Launcher) as a result of the upstream developers' unwillingness to create a flatpak. A unique name allows it to stand out from the original project, and the flatpak was "officially" submitted by the maintainer of the fork, so there exists some level of dedicated support for the flatpak.

I would assume an API for retrieving verified status might be added so other applications such as distro storefronts could display its verified status as well.

**Comment by barthalion** [comment]
This is being worked on and has been already reported in multiple places. The proper place to track it right now is https://github.com/flathub/backend/issues/102.
