### ISSUE TITLE
Publishing failure shows up as success

### ISSUE THREAD

**Issue by hadess** [flathub/flathub#2801]
After building the Flatpak, publishing failed with:
```
Publishing build https://hub.flathub.org/api/v1/build/73749
Api call to https://hub.flathub.org/api/v1/build/73749/publish failed with status 400, details: {'status': 400, 'error-type': 'no-error', 'message': 'No json error details from server'}
```

https://flathub.org/builds/#/builders/29/builds/39997

However, the build was still showing up as a success (in green) on https://flathub.org/builds/
I could not manually publish the build, so I had to rebuild it (twice) so that the publication finally worked.

**Comment by barthalion** [comment]
It looks like some bug in flat-manager or the ciient:

```
Jan 27 19:37:48 master.flathub.org flat-manager[504369]:  INFO 2022-01-27T19:37:48Z: flatmanager::logger: 127.0.0.1:37112 "POST /api/v1/build/73529/purge HTTP/1.1" Flathub 200 135 Python/3.9 aiohttp/3.6.2 1.999440
Jan 27 19:37:49 master.flathub.org flat-manager[504369]:  INFO 2022-01-27T19:37:49Z: flatmanager::logger: 127.0.0.1:37114 "GET /status HTTP/1.0" - 200 337 Go-http-client/1.1 0.035101
Jan 27 19:37:49 master.flathub.org flat-manager[504369]:  WARN 2022-01-27T19:37:49Z: actix_web::pipeline: Error occurred during request handling: WrongPublishedState(published): Build has already been published
```

I will look into closer next week.

**Comment by hadess** [comment]
Any luck? This happened again recently

**Comment by hadess** [comment]
> Any luck? This happened again recently

https://flathub.org/builds/#/builders/32/builds/79210

**Comment by hadess** [comment]
Happened again yesterday :/

https://flathub.org/builds/#/builders/29/builds/44563

**Comment by fcastilloec** [comment]
This just happened to me in the past few days. I wouldn't have noticed if it wasn't for a user. The build is successful, but I get the exact same error message. See https://buildbot.flathub.org/#/builders/29/builds/57936
Rebuilding and re-publishing is a workaround to solve this issue.

**Comment by hadess** [comment]
FWIW, you don't need to rebuild, just click "Publish" when logged in to the builds page.

**Comment by fcastilloec** [comment]
The publish button was not available after the error was shown. The only way to make it reappear was to rebuild and then publish. 
BTW, the website still shows the old version even after a successful publish. I thought it took at most 24h after a manual publish to update the site

**Comment by bbhtt** [comment]
flat-manager went through a bunch of changes so this is likely fixed. If this happens again please open another issue.
