### ISSUE TITLE
Would like write/owner permission to io.github.m64p.m64p

### ISSUE THREAD

**Issue by loganmc10** [flathub/flathub#2836]
Hello, I am the author of m64p (https://github.com/m64p/m64p)

I'd like to have write permission to https://github.com/flathub/io.github.m64p.m64p so that I can manage the flatpak

Thanks

**Comment by barthalion** [comment]
You should receive an invitation from GitHub. You can also accept it at https://github.com/flathub/io.github.m64p.m64p/invitations. Thanks for m64p!
