### ISSUE TITLE
Access to de.bund.ausweisapp.ausweisapp2

### ISSUE THREAD

**Issue by e-user** [flathub/flathub#2839]
Hello,

I would like to request write access to [flathub/de.bund.ausweisapp.ausweisapp2](https://github.com/flathub/de.bund.ausweisapp.ausweisapp2) for @misery. Could you please help me?

**Comment by barthalion** [comment]
Done. @misery, please make sure to accept the invite at https://github.com/flathub/de.bund.ausweisapp.ausweisapp2/invitations. Cheers.

**Comment by misery** [comment]
Thanks!

**Comment by e-user** [comment]
Thank you @barthalion!
