### ISSUE TITLE
Remove ARM version of jdMinecraftLauncher

### ISSUE THREAD

**Issue by JakobDev** [flathub/flathub#2857]
While creating and submitting the Flatpak of com.gitlab.JakobDev.jdMinecraftLLauncher I forgot to block ARM platforms, because they are not supported. I had done this in the next version, but Flathub offers for ARM users still the old version, which does not work. Could one of the Admins please remove the old ARM version?

**Comment by barthalion** [comment]
Done on the server; it will disappear in a few hours.
