### ISSUE TITLE
Random build failures/outages

### ISSUE THREAD

**Issue by jonathon-love** [flathub/flathub#2894]
hi,

i've had a string of build failures for org.jamovi.jamovi

first up the x86-64 build errored [here](https://flathub.org/builds/#/builders/48/builds/9579) (the arm build succeeded)

```
FB: host_command_exited_cb 959996 0
Running: python3 setup.py install --prefix=/app --root=/ --optimize=1
FB: Running 'flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/python3-numpy --nofilesystem=host:reset --filesystem=/srv/buildbot/worker/build-x86_64/build/.flatpak-builder/build/python3-numpy-1 --bind-mount=/run/build/python3-numpy=/srv/buildbot/worker/build-x86_64/build/.flatpak-builder/build/python3-numpy-1 --build-dir=/run/build/python3-numpy --bind-mount=/run/ccache=/srv/buildbot/worker/build-x86_64/build/.flatpak-builder/ccache --unshare=network --env=SOURCE_DATE_EPOCH=1646354678 '--env=CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer  -O2 -g' '--env=CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer  -O2 -g' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed ' --env=R_HOME=/app/lib/R --env=LAPACK=/app/lib --env=BLAS=/app/lib --env=ATLAS=None --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=48 /srv/buildbot/worker/build-x86_64/build/.flatpak-builder/rofiles/rofiles-nxrZb6 /bin/sh -c 'python3 setup.py install --prefix=/app --root=/ --optimize=1'' on host
bwrap: Can't get type of source /run/user/995/.flatpak/2213113417: No such file or directory
FB: host_command_exited_cb 1119018 256
```

i pushed an empty commit to the repo to trigger a second attempt. second attempt is [here](https://flathub.org/builds/#/builders/32/builds/80585), both x86-64 and arm failed at the download step:

```
Failed to download sources: module jmv: GnuTLS recv error (-9): Error decoding the received TLS packet.
```

i pushed another empty commit to trigger a third attempt. the x86-64 successfully built, but failed at the upload step: [here](https://flathub.org/builds/#/builders/10/builds/9643)

```
Api call to https://hub.flathub.org/api/v1/build/78548/build_ref failed with status 500, details: {'status': 500, 'error-type': 'no-error', 'message': 'No json error details from server'}
```

any advice on what i should be doing here?

with thanks

**Comment by jonathon-love** [comment]
https://flathub.org/builds/#/builders/29/builds/46488

**Comment by jonathon-love** [comment]
can anyone else build/publish?, because i cannot

https://flathub.org/builds/#/builders/32/builds/85951

**Comment by jonathon-love** [comment]
https://flathub.org/builds/#/builders/28/builds/10330

**Comment by jonathon-love** [comment]
hi,

i'd be really interested in a response here ... the last 5 attempts to build my package have failed with different errors each time. i'm reasonably confident there's nothing wrong with my package.

as a publisher of software, what am i to do?

with thanks

**Comment by barthalion** [comment]
Hey Jonathon, I will have a look at Jamovi build failures today.

**Comment by jonathon-love** [comment]
thanks @barthalion, appreciate it.

**Comment by barthalion** [comment]
```
bwrap: Can't get type of source /run/user/995/.flatpak/2213113417: No such file or directory
```

This one is definitely a hiccup. Our build setup is a little more involved than it used to, as we run a nested flatpak-builder packaged as flatpak, and it just happens.

```
Failed to download sources: module jmv: GnuTLS recv error (-9): Error decoding the received TLS packet.
```

These errors almost always indicate some misconfiguration on the end of the other server. It's not immediately visible from local environment as it depends on SSL library (gnutls vs openssl) and is sometimes affected by routing. We usually recommend finding a mirror in situations like this.

```
https://flathub.org/builds/#/builders/10/builds/9643
```

Logs for this one were already rotated, but failure during `Upload build` usually means a problem on our end. I need to discuss with our infrastructure provider if we can switch to SSD disks, as we're not keeping up with IO when there are multiple upload/publishing operations happening. This is something you've also observed with `Api call to https://hub.flathub.org/api/v1/build/78548/build_ref failed with status 500, details: {'status': 500, 'error-type': 'no-error', 'message': 'No json error details from server'}`.

So yeah, there's no single culprit. We're bursting at the seams a bit lately, and I hope to focus on some of these issues when I wrap up other tasks at work.

**Comment by jonathon-love** [comment]
> We usually recommend finding a mirror in situations like this.

the host in that instance was github

**Comment by jonathon-love** [comment]
i'm still getting failures:

https://flathub.org/builds/#/builders/29/builds/47691

are you happy for me to just keep adding empty commits until it works?

**Comment by hfiguiere** [comment]
you can go to https://flathub.org/builds 

login with GitHub and then you can trigger rebuilds with the interface instead of pushing commits. (if you can push commit, you can rebuild)

**Comment by jonathon-love** [comment]
it does seem to have settled into failing the same way, with a consistent error every time (where as previously, it was more variable, and would occasionally succeed).

```
Api call to https://hub.flathub.org/api/v1/build/86403/publish failed with status 400, details: {'status': 400, 'error-type': 'no-error', 'message': 'No json error details from server'}
```

https://flathub.org/builds/#/builders/29/builds/47843

with thanks

**Comment by bbhtt** [comment]
I don't think this is relevant anymore, it's been 2 years. Feel free to reopen if it's still an issue.
