### ISSUE TITLE
flathub-beta has older version of Inkscape

### ISSUE THREAD

**Issue by skierpage** [flathub/flathub#2916]
I have app/org.inkscape.Inkscape/x86_64/beta version 1.1-rc from flathub-beta that was last built May 2021 and is older than org.inkscape.Inkscape/x86_64/stable version 1.1.2. Is this because there isn't an inkscape beta right now (in which case maybe it should be removed), or is there a problem with the beta build https://flathub.org/builds/#/apps/org.inkscape.Inkscape~2Fbeta ?

I would happily use a nightly flatpak, but it looks like Inkscape isn't building flatpak of its development version -- https://inkscape.org/release/dev/gnulinux/ :disappointed:

**Comment by hfiguiere** [comment]
See https://github.com/flathub/org.inkscape.Inkscape/issues/106

**Comment by hfiguiere** [comment]
can't close this issue, but it is closed.
