### ISSUE TITLE
Please suppress all branches except master for com.bitwig.BitwigStudio

### ISSUE THREAD

**Issue by abique** [flathub/flathub#2922]
Hi,

As #2868 did not get any answer so far, I believe that it won't be addressed anytime soon.

Also we've found that gnome-software's GUI is a bit confusing to the user when there are multiple branches, and it does not select the stable branch by default (it took our oldest branch by default...).

So please, would you remove every branches except master for us?

Thank you very much,
Alexandre

**Comment by barthalion** [comment]
Just to clarify, these refs match "except master" requirement:

```
runtime/com.bitwig.BitwigStudio.Sources/x86_64/early-access
app/com.bitwig.BitwigStudio/x86_64/3.3
runtime/com.bitwig.BitwigStudio.Sources/x86_64/4.0
runtime/com.bitwig.BitwigStudio.Debug/x86_64/early-access
runtime/com.bitwig.BitwigStudio.Sources/x86_64/beta-version
app/com.bitwig.BitwigStudio/x86_64/4.0
runtime/com.bitwig.BitwigStudio.Debug/x86_64/beta-version
app/com.bitwig.BitwigStudio/x86_64/early-access
app/com.bitwig.BitwigStudio/x86_64/beta-version
runtime/com.bitwig.BitwigStudio.Sources/x86_64/3.3
```

If that looks correct, I can handle the removal today.

**Comment by abique** [comment]
Yes please, thank you very much!

**Comment by barthalion** [comment]
Done. As usually, it will take few hours for the change to become visible.

**Comment by abique** [comment]
Thank you very much! :)
