### ISSUE TITLE
"Server returned HTTP 404" trying to download org.kicad.KiCad.Debug/x86_64/stable

### ISSUE THREAD

**Issue by jmaibaum** [flathub/flathub#2927]
This happens after [today's successful update to KiCad 6.0.3](https://flathub.org/builds/#/builders/8/builds/9851), trying to also update the `.Debug` extension:

```console
$ flatpak update -y
Looking for updates…


        KENNUNG                  Zweig     Op   Remote    Download
 1. [✗] org.kicad.KiCad.Debug    stable    u    flathub   1,0 kB / 1,2 GB

Warning: Während des Holens von runtime/org.kicad.KiCad.Debug/x86_64/stable von der entfernten Quelle flathub: Server returned HTTP 404
Updates complete.
```

I have no idea what has caused this. Does anyone have an idea?

**Comment by barthalion** [comment]
I suspect the Debug extension crosses the magical size where something breaks on our infrastructure. Can you try passing `--no-static-deltas`?

**Comment by jmaibaum** [comment]
Using `--no-static-deltas` helped. Thank you. Yet, can the underlying issue be fixed? 1.2GB doesn't sound too much for a debug extension. Or is there anything flatpak packagers can or should do in order to stay under the "magical size"?

**Comment by different55** [comment]
Ran into this today with com.github.rafostar.Clapper. The --no-static-deltas helped with this, and it also seems to have helped with an issue where flatpak was silently hanging when trying to install com.valvesoftware.Steam.

**Comment by barthalion** [comment]
Closing, as I don't think 1) Debug scratch deltas are broken anymore 2) what @different55 reported was related to a recent outage.
