### ISSUE TITLE
org.freedesktop.LinuxAudio.Plugins are not indexed?

### ISSUE THREAD

**Issue by abique** [flathub/flathub#2930]
Hi,

I've searched for `Surge` in flathub and gnome software.
I expected to find at least:
- `org.freedesktop.LinuxAudio.Plugins.Surge`
- `org.freedesktop.LinuxAudio.Plugins.Surge-XT`

Which is part of what `flatpak search surge` can find.
Why aren't those items visible on flathub and gnome software?
How are users supposed to discover audio plugins?

Regards,
Alex

**Comment by abique** [comment]
Is it related to `"skip-icons-check": true`?

**Comment by abique** [comment]
This is linked to: https://github.com/flathub/backend/issues/9

**Comment by abique** [comment]
Related issue: https://github.com/surge-synthesizer/surge/issues/6255

**Comment by bilelmoussaoui** [comment]
Closing as there is an issue to track that on the website repository. Feel free to comment there if you have additional details
