### ISSUE TITLE
Using flatpaks from flathub.org, user has indication what version will be installed

### ISSUE THREAD

**Issue by heis2201** [flathub/flathub#294]
When browsing through the list of available apps on [flathub.org](https://flathub.org/apps/), no information about the version of the app is displayed at all. Is this something that could be added?

It would be interesting to know, for example if the version of package x in my distro's repository is newer or older or the same as the flatpak provided.

**Comment by TingPing** [comment]
The website is being entirely rewritten, you can track this issue here: https://github.com/jgarciao/linux-store-frontend/issues/37

**Comment by heis2201** [comment]
Thanks for your reply! Would be nice to have the output of `flatpak info <package>` (or part of it) somewhere on display. Many thanks for your efforts!

**Comment by TingPing** [comment]
There is also: https://github.com/jgarciao/linux-store-frontend/issues/45
