### ISSUE TITLE
Add deploy key for org.gajim.Gajim

### ISSUE THREAD

**Issue by lovetox** [flathub/flathub#2974]
Hi,

Would it be possible for an admin to add a deploy key to the org.gajim.Gajim repository?

We want to autoamte the publishing process and this seems to be the correct way for GitHub.

Is there already a process in place? Should we email someone or post the public key here into the issue?

Thanks

**Comment by hfiguiere** [comment]
Note that if the only thing you want to do is update the release when a new one is out, flatpak-external-data-checker can be a good solution https://github.com/flathub/flatpak-external-data-checker

tl;dr it checks there is a new release and will update the manifest.

Just a suggestion.

**Comment by lovetox** [comment]
And how will it update the manifest if it has no deploy key?

**Comment by rusty-snake** [comment]
> ## [](https://github.com/flathub/flatpak-external-data-checker#automatically-submitting-prs)Automatically submitting PRs
>
> When run with the --update flag, this tool can commit any necessary changes to Git and open a GitHub pull request. In order to do this, it requires a [GitHub access token](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line), specified in the GITHUB_TOKEN environment variable.

**Comment by hfiguiere** [comment]
All that is needed is to change the manifest as indicated:

https://github.com/flathub/flatpak-external-data-checker#changes-to-flatpak-manifests

**Comment by lovetox** [comment]
So the suggestion is, one lucky developer in our org gets chosen and he can share full access to his personal github account with all the admins in our org who have access to the the CI secrets?

I think i rather choose the deploy key, the tool that has "deploy" in its name and sounds like it was made exactly for this situation.

**Comment by hfiguiere** [comment]
no that's not what I'm saying. I was just trying to suggest the standard solution **If it fits the bill**. It seems it doesn't.

**Comment by hfiguiere** [comment]
and just clarify f-e-d-c doesn't involve sharing any secret or "deploy key". Seems that there was some misunderstanding as to request someone share any key. Which is also why I initially suggested to use that.

**Comment by lovetox** [comment]
The use case is to **automate** the publishing process. Meaning no human is involved.

Whatever your tool does, however fancy it is, at the end it has to commit the changes to the flathub repository. And in that moment it needs to authenticate with some credentials. Credentials that have write access to the flathub repository.

Which credentials will that be?

the Readme of this tool suggests it can only update the repository with a **personal** Github access token. Which means its unfit to be used in any automated CI job, because that would mean we have to checkin some developers personal access token to our CI pipeline. I really hope i would not find such a developer in my org.

**Comment by hfiguiere** [comment]
> The use case is to **automate** the publishing process. Meaning no human is involved.
> 
> Whatever your tool does, however fancy it is, at the end it has to commit the changes to the flathub repository. 

No. What's apparently unclear, is that modify the manifest as described above, AND adding the proper option to the flathub.json will make this automatic. It will go as follow
1. upstream publish a new release (tag, tarball, etc)
2. flathubbot detect there is a new one
3. it submit a PR with the new release
4. if the PR builds, it will, *if configured*, merge the PR
5. on the PR being merged, the new build is triggered and within a few hours, it is published and available to flathub users.

No deploy key or credential, but for the initial setup where a person with merge permission will set it up *once*

This can also be done for dependencies.

Plenty of project do that. the Rust SDK for example gets updated automatically, the rust-nightly being done nightly.

Again, if that's not enough, I'm not trying to steer you away from a more complicated solution that you'd fine more appopriate.

**Comment by hfiguiere** [comment]
The f-e-d-c README implies you want to set the bot, while it's actually active for any flathub hosted project and only the manifest needs to be changed.

**Comment by lovetox** [comment]
Oh, this tool runs on any flathub project. This was not evident to me at all, now it makes sense.
While i think this can be useful, i dont think it fits the bill.
This tool can update dependencys (and the main app) according to predefined version patterns and source urls.

The main point we want to get rid of is, maintaining the manifest in 2 places.
We like to have all files related to the application in our repository, so also the manifest.
Further we need it in our repo because we have our own distribution of flatpaks on our server, for example for nightly which are not supported by flathub.

Development of the application often means that dependencys come and go, which means the manifest has to be edited. I understand that fedc does not help there.
In this case we currently always need to mirror the change manually to github. Thats what we want to get rid of.

**Comment by hfiguiere** [comment]
> The main point we want to get rid of is, maintaining the manifest in 2 places.

That's a legitimate reason, indeed.

**Comment by lovetox** [comment]
so how to proceed? should i post the public key here into the issue, or can i send it to some email?

Thanks

**Comment by barthalion** [comment]
Hey @lovetox, can I catch you somewhere on IRC or Matrix or XMPP to discuss what exactly you want to achieve? There are multiple options to reduce maintenance burden, I just want to make sure we choose the right one.

**Comment by lovetox** [comment]
hi, you can reach me with XMPP under philipp@hoerist.com

Thanks

**Comment by lovetox** [comment]
hey @barthalion you wanted to contact me, i got your sub request, but nothing afterwards. Thanks

**Comment by lovetox** [comment]
Hi, we still would need the deploy key @barthalion

**Comment by lovetox** [comment]
Hi, can maybe someone else help here?
@bilelmoussaoui 

Im not sure who the other admins here on are.

**Comment by barthalion** [comment]
@lovetox Let's see how it goes. Please send me the key to add over e-mail to `b@bpiotrowski.pl`,

**Comment by lovetox** [comment]
Thanks, i close now as i received confirmation of the added keys.
