### ISSUE TITLE
Request for maintainership of "org.sonic3air.Sonic3AIR"

### ISSUE THREAD

**Issue by ArclightMat** [flathub/flathub#2985]
Hello everyone,

@HugLifeTiZ and I would like to take maintainership of Sonic 3 A.I.R, as it seems nobody has been working actively on it since April 2021. Someone opened an issue [requesting an update](https://github.com/flathub/org.sonic3air.Sonic3AIR/issues/3) in August 2021 but that didn't cause an reaction, furthermore the current maintainer seems inactive in GitHub.

https://github.com/flathub/org.sonic3air.Sonic3AIR/

Please feel free to reach out to me or @HugLifeTiZ or take a look at [issue 5 in the repository](https://github.com/flathub/org.sonic3air.Sonic3AIR/issues/5).

**Comment by hfiguiere** [comment]
cc @kekun since he is the last comitter

**Comment by hfiguiere** [comment]
But you could start by submitting PR, you don't need any permission. The lack of work from volunteers is not a sufficiant indication that it is unmaintained.

**Comment by HugLifeTiZ** [comment]
That is true. Our current plan is to update S3AIR to current stable along with the GNOME runtime to current version, and then work on transitioning to the FD.O runtime. So if we make a PR to do that, how long will it need to sit dormant before we are given commit access?

**Comment by barthalion** [comment]
I have sent you invitations. Thanks!
