### ISSUE TITLE
Screenshot data is stripped and reordered

### ISSUE THREAD

**Issue by CendioOssman** [flathub/flathub#2994]
The flathub backend mangles the screenshot data a little bit too aggressively when generating the thumbnails:

 * Screenshots are reordered, messing up any story being presented
 * Captions are stripped
 * The default marker is stripped

This has been reported as #1017 and flathub/linux-store-frontend#80, but I believe those are mis-handled as this is clearly a backend issue not a frontend. You can clearly look in the appdata.xml from flathub and see the data being incorrect. This is also seen in the fact that multiple frontends (both web and GNOME Software) have the same issue.

**Comment by CendioOssman** [comment]
As mentioned in the other reports, the ordering seems to be alphabetical according to the caption. So an ugly workaround for the ordering is to have bogus captions in the order you want.

**Comment by razzeee** [comment]
I think this should basically fix itself as soon as we run https://github.com/flatpak/flatpak-builder/pull/418

At least that's what I'm waiting for for this.

**Comment by hfiguiere** [comment]
which package are you talking about?

**Comment by CendioOssman** [comment]
The [ThinLinc Client](https://flathub.org/apps/details/se.cendio.tlclient).

**Comment by razzeee** [comment]
This should be better now, if you rebuild your app. At least captions show up.

**Comment by CendioOssman** [comment]
Seems to be better, but still incorrect for ThinLinc. The order is now reversed compared to the metainfo order.

But the bug might be in that file, rather than flathub now. I see that all screenshots are marked as default, not just one. Which might be confusing the system.

**Comment by razzeee** [comment]
It is, but it's also valid according to the spec... :smiling_face_with_tear:

**Comment by razzeee** [comment]
Flathub side of things should be fine now.

**Comment by CendioOssman** [comment]
Seems to be working nicely as far as I can tell. Thanks for the fix!
