### ISSUE TITLE
Screenshot thumbnails have sharpening artefacts

### ISSUE THREAD

**Issue by CendioOssman** [flathub/flathub#2995]
The automatically generated thumbnails have some serious edge sharpening applied to them, which creates artefacts and makes things look very off.

Compare this image generated by flathub:

![se cendio tlclient-b019c1f38c5301e25f9e067dc7877664](https://user-images.githubusercontent.com/6640916/162375707-a36990ba-09f1-40c8-bb4d-adab9db7f7ef.png)

With this manually scaled image:

![linux-en-fullscreen-mode](https://user-images.githubusercontent.com/6640916/162375743-27b296b5-b042-4b00-80a4-3a83a760b395.png)

(the frontends then scale the images again, negating any positive effects the sharpening might have had)

**Comment by bbhtt** [comment]
Seems fine now https://dl.flathub.org/media/se/cendio/tlclient/ceb30c32e9b597b3351bf19cff99be0f/screenshots/image-1_orig.png

It's been almost 3 months since Flathub moved to libappstream and I have yet to see one over sharpened image. Please reopen if you see one.
