### ISSUE TITLE
Change default branch for org.freedesktop.Sdk.Extension.haskell to 21.08

### ISSUE THREAD

**Issue by ghost** [flathub/flathub#2996]
Please change the default branch for [org.freedesktop.Sdk.Extension.haskell](https://github.com/flathub/org.freedesktop.Sdk.Extension.haskell) to 21.08.

Is there a specific reason why maintainers can't change the default branch themselves?

**Comment by hfiguiere** [comment]
OP left and 21.08 is obsolete. the SDK hasn't been updated in a long time.
