### ISSUE TITLE
"Need More Input" Error

### ISSUE THREAD

**Issue by pikhosh** [flathub/flathub#3010]
I don't know why, but every time I try to install a program from Flathub, this error is shown; And neither by installing the old versions of Flatpak nor by any other method can this problem be solved! It also doesn't seem that Flathub is blocked in our area...

Can anyone help and say what could be the problem? On any distribution I can't find any program of Flathub in the app centers, .flatpakref can not be installed and there are the same problems through the terminal and the error "Need More Input" is displayed...

I used to use the Flathub on KDE Neon and Manjaro and it wasn't a problem, and I was also able to use the Flathub on the Elementary OS once without any problems, But such a thing never happened again.

My only guess is that it may be due to the limited internet speed in this area, but as I said, I used to use Flathub before, and downloading system updates and Snap programs or even AUR packages with this speed ​​isn't a problem.

**Comment by JakobDev** [comment]
It would be helpful, if you could paste the whole terminal output.

**Comment by pikhosh** [comment]
> It would be helpful, if you could paste the whole terminal output.

![image](https://user-images.githubusercontent.com/73311467/163527920-323b0bdd-2c9a-4378-a8c6-72c9ea688fb5.png)

**Comment by lirezahabibi** [comment]
It seems flathub is not available in Iran 🤔️ (I don't know why). for me this problem was solved by using VPN

**Comment by razzeee** [comment]
Discussion seems to have moved to another issue, I'll close this.

**Comment by shellheim** [comment]
I am having this issue right now and using a VPN doesn't help, it happened with `gnome-logs` and `fluent-reader` which is a rss reader.  
Here's the shell output :  
```shell
flatpak install flathub org.gnome.Logs
Looking for matches…

org.gnome.Logs permissions:
    ipc                  fallback-x11      wayland      x11      dri
    file access [1]

    [1] /var/log/journal:ro


        ID                     Branch         Op         Remote         Download
 1. [✗] org.gnome.Logs         stable         i          flathub        4.6 MB / 1.6 MB

Error: While pulling app/org.gnome.Logs/x86_64/stable from remote flathub: Writing content object: Need more input
error: Failed to install org.gnome.Logs: While pulling app/org.gnome.Logs/x86_64/stable from remote flathub: Writing content object: Need more input
```

**Comment by razzeee** [comment]
That's due to fedora breaking something https://discussion.fedoraproject.org/t/flatpak-updating-bug-due-to-libostree-update-with-solution/84696

**Comment by shellheim** [comment]
gadddamit! Thanks for the help man.

**Comment by shellheim** [comment]
gadddamit! Thanks for the help man.

**Comment by sparklyballs** [comment]
also not working in arch linux with the same message for any package installing or updating......

Warning: While pulling runtime/org.kde.WaylandDecoration.QGnomePlatform-decoration/x86_64/6.4 from remote flathub: Writing content object: Need more input

**Comment by marvix97** [comment]
> also not working in arch linux with the same message for any package installing or updating......
> 
> Warning: While pulling runtime/org.kde.WaylandDecoration.QGnomePlatform-decoration/x86_64/6.4 from remote flathub: Writing content object: Need more input

Downgrading ostree makes it work again, just like on fedora as linked before
