### ISSUE TITLE
The icon has not been updated on the app page

### ISSUE THREAD

**Issue by alexkdeveloper** [flathub/flathub#3023]
The icon has been updated in the published version of the app. The update is now available in Flathub, but the program icon remains from the old version. Can this be fixed?
https://github.com/flathub/com.github.alexkdeveloper.sudoku

**Comment by barthalion** [comment]
As icons don't have unique names, once they're cached on CDN, they're there for good. I have purged the cache for `https://dl.flathub.org/repo/appstream/x86_64/icons/128x128/com.github.alexkdeveloper.sudoku.png` manually and it should become invalidated in a minute or two.

**Comment by alexkdeveloper** [comment]
Thanks) The icon has changed.
