### ISSUE TITLE
Hand over maintainership of Barrier flatpak.

### ISSUE THREAD

**Issue by shymega** [flathub/flathub#3041]
If anyone can help with this:

After my announcement in flathub/com.github.debauchee.barrier#26, @mikeeq has kindly offered to take over maintainership as per flathub/com.github.debauchee.barrier#27. I would be most grateful if @mikeeq could be made the sole maintainer of the Barrier flatpak, as Adrian and I are no longer involved with Barrier, and the Flatpak needs some love. I hopefully will be making a Flatpak for the fork I moved to from Barrier at some point.

Thanks!

**Comment by shymega** [comment]
Just wanted to prod this issue along, as I need to wrap up my involvement with Barrier, and start looking to make a Flatpak for Input Leap instead, and a Snap.

**Comment by barthalion** [comment]
Sorry, this somehow fell off from my radar. I have sent an invitation to @mikeeq.

**Comment by mikeeq** [comment]
Thanks!

**Comment by shymega** [comment]
Thank you for handling this. As long as myself, @p12tic and @AdrianKoshka are the only ones removed, that's perfect, thanks!
