### ISSUE TITLE
'OSX-Arc' theme not supported as flatpak package in flathub repoes like 'Arc' themes. [Feature request]

### ISSUE THREAD

**Issue by Bonsitar** [flathub/flathub#305]
Hi there.
As I have explained [there](https://github.com/LinxGem33/OSX-Arc-Shadow/issues/26) and in issue title, There is no OSX-Arc themes package support for theming flapak applications. It can be very good if anyone could do it like Arc themes package in flathub repoes.
Thanks.

**Comment by TingPing** [comment]
This is not a place to request packages. If upstream is interested and needs help they can feel free to contact us.

https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app is a starting point as well as the dozen themes on here: https://github.com/search?q=org%3Aflathub+gtk3theme

**Comment by Bonsitar** [comment]
Thanks.
