### ISSUE TITLE
Update default branch

### ISSUE THREAD

**Issue by darkdragon-001** [flathub/flathub#3068]
Can you please update the default branch of [org.freedesktop.Sdk.Extension.mono6](https://github.com/flathub/org.freedesktop.Sdk.Extension.mono6) to `branch/21.08` and delete the accidentally pushed branch `branch/22.08`?

**Comment by barthalion** [comment]
Changed the default branch. I guess it's fine to keep 22.08 around, as we're only 3 months away from the new runtime anyway.

**Comment by darkdragon-001** [comment]
Thanks.
