### ISSUE TITLE
All gimp plugins are listed twice.

### ISSUE THREAD

**Issue by ghost** [flathub/flathub#3075]
For some reason, if I use the gnome-software GUI or the command line, I get GIMP plugins listed twice. GIMP itself is listed only once. Even worse, I can only see certain information if I use the terminal. If I use the gnome-software GUI, It just lets me install the plugin twice. I’m on debian 11 stable. What’s going on?

**Comment by hfiguiere** [comment]
it's a bug in gnome software mostly: 
https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1216

**Comment by jointri** [comment]
> it's a bug in gnome software mostly: https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1216

What about knowing which GIMP plugin to install if I was using the command line. It's confusing because I don't know which one I need and which one I don't.

**Comment by bbhtt** [comment]
Seems fixed on gnome software side version 45.2

![image](https://github.com/flathub/flathub/assets/62639087/5c483fa0-e23b-4ab4-bc40-9136ca5fab1c)

**Comment by hfiguiere** [comment]
I don't think it was fixed in GNOME software.

**Comment by hfiguiere** [comment]
but it's not a flathub bug anyway
