### ISSUE TITLE
Error while updating flatpak

### ISSUE THREAD

**Issue by devkolasani** [flathub/flathub#3078]
I'm receiving this error since 2 weeks while trying to update Flatpaks

(flatpak update:21304): GLib-Net-WARNING **: 08:18:36.837: Failed to set GnuTLS session priority with error beginning at %COMPAT: The request is invalid.
F: Warning: Treating remote fetch error as non-fatal since runtime/re.sonny.Commit.Locale/x86_64/stable is already installed: No such ref 'runtime/re.sonny.Commit.Locale/x86_64/stable' in remote flathub

I'm running Fedora 35

Here are my flatpak remotes.
❯ flatpak remotes
Name          Options
fedora        system,oci
flathub       system
flathub       user
gnome-nightly user

My flatpak version
❯ rpm -q flatpak
flatpak-1.12.7-2.fc35.x86_64

**Comment by razzeee** [comment]
Does this still happen to you?

**Comment by bbhtt** [comment]
This is likely an issue with your system packages probably GnuTLS /openssl or curl. Please ask your distro maintainer.
