### ISSUE TITLE
Take ownership of com.viber.Viber

### ISSUE THREAD

**Issue by akurtakov** [flathub/flathub#3079]
https://github.com/flathub/com.viber.Viber seems to lost its maintainer. See https://github.com/flathub/com.viber.Viber/pull/42 . 
Can I be added (or someone else that would accept PRs) be added as a committer so we can keep it up?

**Comment by barthalion** [comment]
I have sent you an invitiation. Thanks!

**Comment by akurtakov** [comment]
Thank you!
