### ISSUE TITLE
Local builds work and run fine but Builbot builds fail with "Failed to find icon com.ozmartians.VidCutter" so cannot push update

### ISSUE THREAD

**Issue by ozmartian** [flathub/flathub#3082]
Trying to update my app to new org.kde.Platform runtime 5.15-21.08. Everything is 100% fine and building the flatpak locally works as expected. Ran it, tested it and all is good. Flathub's buildbots are failing though, unable to find the icon.

TLDR; locally building my updated app com.ozmartians.VidCutter works and runs fine, cannot publish because it fails to build on flathub's buildbots.

Error msg: Error loading desktop file: Failed to find icon: Failed to find icon com.ozmartians.VidCutter

All freedesktop specs and files adhered to as always. Local build works, publishing bots fail to build so won't accept the update.
Much appreciation to anyone who can lend a hand. Thx!

**Comment by ozmartian** [comment]
Buildbot builds include the following before it fails with icon error msg, this doesn't happen when building locally:

Unable to init server: Could not connect: Connection refused
(xdg-desktop-portal-gtk:357558): Gtk-WARNING **: 07:13:35.812: cannot open display: 
dbus-daemon[140153]: [session uid=995 pid=140153] Activated service 'org.freedesktop.impl.portal.desktop.gtk' failed: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
** (/usr/libexec/xdg-desktop-portal:357527): WARNING **: 07:13:35.814: Failed to create access proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
** (/usr/libexec/xdg-desktop-portal:357527): WARNING **: 07:13:35.814: No skeleton to export
dbus-daemon[140153]: [session uid=995 pid=140153] Activating service name='org.freedesktop.impl.portal.desktop.gtk' requested by ':1.125' (uid=995 pid=357527 comm="/usr/libexec/xdg-desktop-portal " label="unconfined")
Unable to init server: Could not connect: Connection refused
(xdg-desktop-portal-gtk:357560): Gtk-WARNING **: 07:13:35.838: cannot open display: 
dbus-daemon[140153]: [session uid=995 pid=140153] Activated service 'org.freedesktop.impl.portal.desktop.gtk' failed: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
** (/usr/libexec/xdg-desktop-portal:357527): WARNING **: 07:13:35.841: Failed to create wallpaper proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
** (/usr/libexec/xdg-desktop-portal:357527): WARNING **: 07:13:35.841: No skeleton to export
dbus-daemon[140153]: [session uid=995 pid=140153] Activating service name='org.freedesktop.impl.portal.desktop.gtk' requested by ':1.125' (uid=995 pid=357527 comm="/usr/libexec/xdg-desktop-portal " label="unconfined")
Unable to init server: Could not connect: Connection refused
(xdg-desktop-portal-gtk:357562): Gtk-WARNING **: 07:13:35.859: cannot open display: 
dbus-daemon[140153]: [session uid=995 pid=140153] Activated service 'org.freedesktop.impl.portal.desktop.gtk' failed: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
** (/usr/libexec/xdg-desktop-portal:357527): WARNING **: 07:13:35.861: Failed to create account proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
** (/usr/libexec/xdg-desktop-portal:357527): WARNING **: 07:13:35.861: No skeleton to export
dbus-daemon[140153]: [session uid=995 pid=140153] Activating service name='org.freedesktop.impl.portal.desktop.gtk' requested by ':1.125' (uid=995 pid=357527 comm="/usr/libexec/xdg-desktop-portal " label="unconfined")
Unable to init server: Could not connect: Connection refused
(xdg-desktop-portal-gtk:357564): Gtk-WARNING **: 07:13:35.879: cannot open display: 
dbus-daemon[140153]: [session uid=995 pid=140153] Activated service 'org.freedesktop.impl.portal.desktop.gtk' failed: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
** (/usr/libexec/xdg-desktop-portal:357527): WARNING **: 07:13:35.881: Failed to create email proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1

**Comment by ozmartian** [comment]
Full server build logs are at:

https://flathub.org/builds/#/builders/32/builds/88988

**Comment by hfiguiere** [comment]
There is a know bug caused by the presence of `/app/usr`. I see in the manifest 
`"ln -sf ${FLATPAK_DEST}/share ${FLATPAK_DEST}/usr"`

BTW `/app/usr` makes no sense

**Comment by hfiguiere** [comment]
Further comment on the PR. This is not a flathub bug.

 https://github.com/flathub/com.ozmartians.VidCutter/pull/27

**Comment by ozmartian** [comment]
Thank you so much. That was something from way back.

**Comment by ozmartian** [comment]
Both icon path + /app/usr madness fixed and testing new build.

Legendary response time guys!

**Comment by bilelmoussaoui** [comment]
I suppose this can be closed now

**Comment by ozmartian** [comment]
Still not working unfortunately. Same error still. Final post-install for the app:

`        "post-install": [
            "mkdir -p ${FLATPAK_DEST}/share/applications",
            "mkdir -p ${FLATPAK_DEST}/share/fonts",
            "mkdir -p ${FLATPAK_DEST}/share/icons",
            "cp vidcutter/fonts/* ${FLATPAK_DEST}/share/fonts",
            "cp -R data/icons/hicolor ${FLATPAK_DEST}/share/icons",
            "cp data/desktop/com.ozmartians.VidCutter.desktop ${FLATPAK_DEST}/share/applications"
        ],`

/app/usr link is gone, icons should be fine. Builds fine locally. Will have to dig deeper.

**Comment by hfiguiere** [comment]
it still is not a flatpak / flathub problem. I have suggested changes.

**Comment by ozmartian** [comment]
Yay! Just checked buildbot and it appears to be all good now. Will you be merging the pull request or should I do it myself once the test builds complete?

**Comment by ozmartian** [comment]
Fixed by you flathubby legends. Thx!
