### ISSUE TITLE
Add maintainer to net.ankiweb.Anki

### ISSUE THREAD

**Issue by ingemarberg** [flathub/flathub#3090]
I've been submitting pull requests maintaining [net.ankiweb.Anki](https://github.com/flathub/net.ankiweb.Anki) for some time. Would you please consider adding me as a maintainer?

**Comment by barthalion** [comment]
What do you think @dsd?

**Comment by dsd** [comment]
Yes please do.
Please also add @corecontingency and @rayes0 in case they wish to submit more contributions.

**Comment by ingemarberg** [comment]
@barthalion Please let me know if there is anything else I need to submit.

**Comment by barthalion** [comment]
Sorry, this has fallen off my radar. I've just sent out invitations.
