### ISSUE TITLE
Problem accessing from Iran

### ISSUE THREAD

**Issue by pikhosh** [flathub/flathub#3095]
I don't know if our country has blocked access to FlatHub or if it's FlatHub CDN that has banned us; But in any case, this isn't a pleasant thing for free software and everyone should have equal and easy access...

If this problem can be solved somehow from the FlatHub side, please fix it!

#3010

**Comment by danialbehzadi** [comment]
> I don't think we can really do anything about our CDN provider blocking Iran. If either https://front-hex2.flathub.org or https://front-ams.flathub.org are accessible for you, you can use it instead of `dl.flathub.org`.

How can we change that?

**Comment by barthalion** [comment]
You can run something along this:

```
flatpak remote-modify --no-follow-redirect flathub --url=https://front-hex2.flathub.org
```

or

```
flatpak remote-modify --no-follow-redirect flathub --url=https://front-ams.flathub.org
```

**Comment by ssmns** [comment]
After

> 

after this, i get: 

```
Looking for matches…
error: Unable to load summary from remote flathub: Remote listing for flathub not available; server has no summary file. Check the URL passed to remote-add was valid.
```

**Comment by barthalion** [comment]
@ssmns The key is "something along this". I did not mean it's going to be 100% correct, just gave a suggestion what to do. It should be `https://front-ams.flathub.org/repo`.

**Comment by danialbehzadi** [comment]
> It should be `https://front-ams.flathub.org/repo`.

Worked for me

**Comment by SHMF1385** [comment]
They return forbidden
![image](https://user-images.githubusercontent.com/60741415/175900061-f11f85ba-aad0-4354-80cd-28a0cb82cd02.png)
![image](https://user-images.githubusercontent.com/60741415/175900097-d30c7729-6314-42b5-826a-6ddb559a675b.png)

**Comment by barthalion** [comment]
@SHMF1385 This path is supposed to be used by Flatpak, not browsed directly.

**Comment by SHMF1385** [comment]
> @SHMF1385 This path is supposed to be used by Flatpak, not browsed directly.

Thanks
