### ISSUE TITLE
Archive org.gnome.PasswordSafe

### ISSUE THREAD

**Issue by bbhtt** [flathub/flathub#3108]
PasswordSafe https://github.com/flathub/org.gnome.PasswordSafe was renamed to [Secrets](https://gitlab.gnome.org/World/secrets/) and now lives at https://github.com/flathub/org.gnome.World.Secrets

It is confusing to have two same apps with two different names/versions (one older and one newer) and same icon.

**Comment by bilelmoussaoui** [comment]
I have asked @A6GibKm about it and they said they wanted to wait a little bit before archiving it.

**Comment by A6GibKm** [comment]
yes, we will probably do it no latter than 7.0 which will be release whenever GTK 4.8 and libadwaita 1.2 get released.

**Comment by bilelmoussaoui** [comment]
Closing as the maintainer prefers to wait for a bit, please open an issue there if you wish to do so.
