### ISSUE TITLE
Inconsistent naming guidelines for appdata XML in docs

### ISSUE THREAD

**Issue by stuartlangridge** [flathub/flathub#3118]
https://github.com/flathub/flathub/wiki/AppData-Guidelines says:

> Place the AppData file into /app/share/metainfo/, name it %{id}.metainfo.xml, where %{id} is the [#ID](https://github.com/flathub/flathub/wiki/AppData-Guidelines#id).

https://docs.flatpak.org/en/latest/conventions.html says:

> AppData files should be named with the application ID and the .appdata.xml file extension, and should be placed in /app/share/metainfo/

I don't know which of these is correct, but they disagree, so I think one of them needs to be changed.

**Comment by hfiguiere** [comment]
fortunaly all these combination work.

**Comment by hfiguiere** [comment]
The bad news: the flatpak doc is managed by the https://github.com/flatpak/flatpak project.
The good news: it's easier to contribute to their documentation with a github PR than to contribute to a github hosted wiki.

**Comment by hfiguiere** [comment]
see https://github.com/flatpak/flatpak-docs/pull/331

**Comment by hfiguiere** [comment]
apparently there was https://github.com/flatpak/flatpak-docs/pull/326 already

**Comment by hfiguiere** [comment]
should be fixed now.
