### ISSUE TITLE
How to name a new PR branch when submitting a new app to Flathub

### ISSUE THREAD

**Issue by stuartlangridge** [flathub/flathub#3120]
https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app says

> Create a new branch with your app’s name: git checkout -b your_app_name

It's probably not actually important whether a branch is called the app's _name_ (MyApp), or the app's _application ID_ (org.example.myapp), but to a developer inexperienced with flatpak packaging it can come across as a bit confusing to know what to pick. If this instruction was tidied up a little bit to make it more obvious that it means the human name of the app then it might help avoid a little mental jolt here:

> Create a new branch with your app’s name (not its ID): git checkout -b YourAppName

or similar.

**Comment by hfiguiere** [comment]
the branch name for a submission does not matter. It is never used.

**Comment by razzeee** [comment]
I think this not playing a role, has been documented recently, I'll close this.
