### ISSUE TITLE
Bug in the retroshare flatpack config file

### ISSUE THREAD

**Issue by csoler** [flathub/flathub#3139]
As currently written, the retroshare flatpack config file creates an executable that contains the following command:

  /usr/bin/flatpak run --branch=stable --arch=x86_64 cc.retroshare.retroshare-gui "$@"

It should rather be

   /usr/bin/flatpak run --branch=stable --arch=x86_64 --filesystem=home cc.retroshare.retroshare-gui "$@"

...because otherwise retroshare will not see files in home directory (instead it shows some virtual empty home directory) and the user is not able to even share his own files. I don't know how to change that though.

**Comment by hfiguiere** [comment]
the right place to file this is https://github.com/flathub/cc.retroshare.retroshare-gui/issues

This is not a flathub problem but rather a problem with the indivual package.

**Comment by rusty-snake** [comment]
> the right place to file this is https://github.com/flathub/cc.retroshare.retroshare-gui/issues

Which is already done: https://github.com/flathub/cc.retroshare.retroshare-gui/issues/2

**Comment by csoler** [comment]
I can see that! Thx.
