### ISSUE TITLE
The documentation for enabling Flathub to Fedora needs to be updated

### ISSUE THREAD

**Issue by uncivilgentleman** [flathub/flathub#3147]
Starting with Fedora 36 Flathub is explicitly disabled. So the documentation for enabling Flathub on Fedora should include `flatpak remote-modify --enable flathub`.

**Comment by hfiguiere** [comment]
You should submit a PR for this file: https://github.com/flatpak/flatpak.github.io/blob/source/data/distro.yml

**Comment by uncivilgentleman** [comment]
Thank you, I'll do that.
