### ISSUE TITLE
No 32 bit support anymore?

### ISSUE THREAD

**Issue by ghost** [flathub/flathub#3193]
Hello.
I noticed that applications are no longer installed:
No APPNAME match in remote flathub repository
Any app.
Checked in Ubuntu 16.04 and Mageia 8.
Network activity analysis shows requests to:
https://dl.flathub.org/repo/summaries/3b6834ac11db42f24b92a683fd43193955ad365c20eec9bd758204a63f4adcc9.idx.sig
https://dl.flathub.org/repo/summary.idx
You removed 32 bit support after all, right?

Interestingly, Flatpak i386 package is still being updated and even for Ubuntu 16.04 in ppa. Weird.

**Comment by barthalion** [comment]
It's temporary, as we hit a limitation in ostree that broke Flathub for everyone. It will be restored when a new Flatpak development release is out.

**Comment by archipelagu** [comment]
Thanks for the info. I'm glad that it's only a temp problem.

**Comment by razzeee** [comment]
Can this be closed?

**Comment by hfiguiere** [comment]
I guess so
