### ISSUE TITLE
Feature Request:  Official package indicators

### ISSUE THREAD

**Issue by meeas** [flathub/flathub#3204]
I don't see anything on the Flathub website nor the Gnome Software tool to indicate whether a package is an OFFICIAL package from the application development team, or if the application is being packaged by a good citizen of the greater Flatpak community.  I would really like to see this added and made very visible in all Flatpak storefronts.  I think this would also be strong motivation for development teams to take over maintaining their own Flatpak releases or to formally adopt volunteer flatpak community members into their development teams.

**Comment by barthalion** [comment]
There are other issues tracking this already.
