### ISSUE TITLE
Can't browse flathub.org/apps to see available package

### ISSUE THREAD

**Issue by focom** [flathub/flathub#322]
Hi, 
Just wanted to know if there is an alternative to see all the apps available. I used to go on the falthub.org/apps but you removed the page. Plus on gnome software you cant browse all the software available. Discovery is pretty low.
It was really handy to see the new package and discover new app.

**Comment by Alexander-Wilms** [comment]
There's beta.flathub.org

**Comment by focom** [comment]
perfect thanks
