### ISSUE TITLE
Add vulongm as maintainer for org.kde.krita

### ISSUE THREAD

**Issue by travier** [flathub/flathub#3223]
Can you add [vulongm](https://github.com/vulongm) as a maintainer for [org.kde.krita](https://github.com/flathub/org.kde.krita)?

He has been doing good work keeping the package up to date: https://github.com/flathub/org.kde.krita/graphs/contributors

Thanks!

**Comment by travier** [comment]
CC @vulongm

**Comment by vulongm** [comment]
@travier Giving a ping here per prior convo.

**Comment by travier** [comment]
Ping @nedrichards @bilelmoussaoui @hfiguiere

**Comment by barthalion** [comment]
Done.

**Comment by travier** [comment]
Thanks!

**Comment by vulongm** [comment]
Accepted the invite, thank you!
