### ISSUE TITLE
Team for Endless apps

### ISSUE THREAD

**Issue by wjt** [flathub/flathub#3238]
Endless has a bunch of apps on Flathub, such as [Photo Editor](https://github.com/flathub/com.endlessm.photos), the abandoned [Hatch Previewer](https://github.com/flathub/com.endlessm.HatchPreviewer), and the [various com.endlessnetwork.* games](https://github.com/flathub?q=com.endlessnetwork&type=all&language=&sort=).

It would be useful if we could have an Endless OS Foundation team within the flathub org, so that we could easily grant commit rights across all these repos to our engineering team (and remove such rights when someone leaves EOSF). Today for instance, @georgesstavracas has reviewed a [change to com.endlessm.photos](https://github.com/flathub/com.endlessm.photos/pull/8) but doesn't have permission to merge it.

(Strictly speaking those com.endlessnetwork.* games are published by a sibling entity, not EOSF, but EOSF supports them in making the games available on Flathub.)

Is such a thing doable?

**Comment by wjt** [comment]
cassidyjames
danigm
dbnicholson
dsd
dylanmccall
erikos
georgesstavracas
jprvita
manuq
pwithnall
ramcq
starnight
vanessa-chang
wjt

Many thanks!

**Comment by wjt** [comment]
Did this team get created? I was reminded of this ticket today because starnight opened https://github.com/flathub/com.hack_computer.Clubhouse/pull/16 and some related PRs. Based on the commit history there I suspect that only danigm may have commit access to the `com.hack_computer.*` apps, but he left Endless last month.

(Updated the list above to remove him.)

**Comment by ramcq** [comment]
Done; am I right that there are 15 repos?

**Comment by wjt** [comment]
Sounds right to me. Thank you!
