### ISSUE TITLE
Give push right to org.freedesktop.LinuxAudio.Plugins.Surge-XT and org.freedesktop.LinuxAudio.Plugins.Surge

### ISSUE THREAD

**Issue by abique** [flathub/flathub#3241]
Please can you give a push right to @baconpaul ?
Many thanks :-)

**Comment by hfiguiere** [comment]
An invite was sent when Surge-XT was created

https://github.com/flathub/flathub/pull/2650#issuecomment-1019359324

**Comment by barthalion** [comment]
I've just checked and Paul accepted the invite when we created the repo.
