### ISSUE TITLE
Fonts are darker in Qt than in GTK+

### ISSUE THREAD

**Issue by jurf** [flathub/flathub#325]
For some reason, fonts in Qt look worse than in Gtk+ in Flathub apps. This seems to be a problem with the FreeType in the Platforms Flathub uses, I’m not sure where it boils down to, however.

MuseScore, for example, provides an option whether to use a built-in FreeType or the system one, whereas the former produces much better results to my eyes. Screenshots here: flathub/org.musescore.MuseScore#6.

**Comment by TingPing** [comment]
Sounds like a discussion for the Qt folks: CC @aleixpol @grulja

**Comment by Pointedstick** [comment]
Reminds me of https://bugs.kde.org/show_bug.cgi?id=391780.

@aleixpol, is our runtime forcing the use of `QtRendering` instead of `NativeRendering`? `QtRendering` is known to produce text that's noticeably lighter than text produced by `NativeRendering`.

**Comment by jurf** [comment]
Actually the fonts are darker/less sharp than in Gtk+ (or even Qt4 apps in the Fedora repos).

**Comment by Pointedstick** [comment]
FWIW, In my book, darker is good (most Linux software has a terrible problem with poor text contrast), but less sharp obviously isn't. Would be good to get to the bottom of this discrepancy.

**Comment by aleixpol** [comment]
@Pointedstick no, we are not forcing anything.
@jurf any way to reproduce this? I can't see this issue.

**Comment by jurf** [comment]
@aleixpol you can try MuseScore now, and the update it to the latest version (that is being built) to see the difference. Also, here are the screenshots from flathub/org.musescore.MuseScore#6 for quick reference:

Built-in:
![musescore-builtin-freetype](https://user-images.githubusercontent.com/7472425/38197852-83280838-368a-11e8-8b10-274c9d0e2659.png)

System:
![musescore-system-freetype](https://user-images.githubusercontent.com/7472425/38197853-86b65a4a-368a-11e8-84c5-a33acc1b1cf4.png)

This is also Inkscape (GTK+ 2):
![snimka obrazovky z 2018-04-04 12-33-20](https://user-images.githubusercontent.com/7472425/38302936-bfcedf2a-3804-11e8-9b21-9e64b3060c51.png)

And LibreOffice (GTK+ 3) (wow, it’s quite hard to find a GTK+ 3 app with a menubar):
![snimka obrazovky z 2018-04-04 12-34-57](https://user-images.githubusercontent.com/7472425/38302942-c49f6c2c-3804-11e8-8904-c1eef848c0a8.png)

I guess it’s a bit subjective though. I guess the better title is ‘darker than GTK+’.

Also the MuseScore one produces _lighter_ fonts than GTK+, which is funny.

Anyway, still, the fonts are noticeably different in GTK+ and in Qt, which shouldn’t be.

**Comment by matthiasclasen** [comment]
this is not a flathub issue

**Comment by jurf** [comment]
@matthiasclasen but can’t we fix/patch it somehow in Flathub? It may not be a Flathub-specific issue but it affects Flathub.

**Comment by bilelmoussaoui** [comment]
Closing as this should be reported to the Freedesktop/KDE SDK's folks.
