### ISSUE TITLE
Some shared-modules are failing to build

### ISSUE THREAD

**Issue by XargonWan** [flathub/flathub#3259]
I had to manually build some libraries instead of relying on the shared-modules because the needed files cannot be retrieved by flatpak-builder.

Since now this happened to glu and gudev, but seems like that every two days a new shared-module is breaking.

`Failed to download sources: module gudev: server certificate verification failed. CAfile: none CRLfile: none`

https://github.com/XargonWan/RetroDECK/runs/6842156938?check_suite_focus=true#step:7:1749

I found a workaround by replacing some of them temporarly with a mirror.

More info there: https://gitlab.com/gnutls/gnutls/-/issues/1335

I am adding the various workarounds after those lines:
https://github.com/XargonWan/RetroDECK/blob/cooker/net.retrodeck.retrodeck.yml#L107-L109

I suggest to replace the official shared-modules with the alternative links like I am doing.

Original issue: https://github.com/XargonWan/RetroDECK/issues/39

**Comment by bilelmoussaoui** [comment]
Open the issue on shared-modules repo instead?

**Comment by barthalion** [comment]
Yeah, please submit pull requests to the shared-modules repo instead.
