### ISSUE TITLE
Access to org.openclonk.OpenClonk add request

### ISSUE THREAD

**Issue by jcaesar** [flathub/flathub#326]
I'd be a bit more comfortable if I wasn't the only person from the upstream team with write access to https://github.com/flathub/org.openclonk.OpenClonk, can I ask to add https://github.com/lluchs to the list of people with push rights? (Otherwise, giving https://github.com/openclonk/ access would also work for me.)

**Comment by TingPing** [comment]
lluchs added. Can't add an entire org as a collaborator. Is that all?

**Comment by jcaesar** [comment]
That's all. Thank you very much.
