### ISSUE TITLE
Wiki update: buildbot instance URL

### ISSUE THREAD

**Issue by Yvan-Masson** [flathub/flathub#3268]
Hi,

[This wiki page](https://github.com/flathub/flathub/wiki/App-Maintenance) currently gives https://flathub.org/builds (which leads to 404) instead of https://buildbot.flathub.org for the buildbot URL. Could you update the URL?

Regards,
Yvan

**Comment by JakobDev** [comment]
It would also be nice to have a redirection

**Comment by barthalion** [comment]
There was a redirect for `/builds/`, just added another one for `/builds`.
