### ISSUE TITLE
tv.plex.PlexHTPC: add user and disable issues tab

### ISSUE THREAD

**Issue by sztomi** [flathub/flathub#3292]
Hi, I'd like to request access for [@plexappbuilder](https://github.com/plexappbuilder) to https://github.com/flathub/tv.plex.PlexHTPC with push rights. 

Also, please disable the issues tab - users started to use it as a general support avenue, but our teams do not monitor it for questions or bug reports, so they wouldn't get the appropriate care. I've linked the official support in the README.

**Comment by barthalion** [comment]
@plexappbuilder is already here:

![image](https://user-images.githubusercontent.com/380403/176648277-df809c19-ee42-4aa5-80a1-cff22e1a250e.png)

Disabled the Issues tab. Thanks!

**Comment by sztomi** [comment]
@barthalion I think that's the other repo: 
![image](https://user-images.githubusercontent.com/240594/176649660-ef9111ce-194c-48e6-a4cd-0b2f4219f5ad.png)
