### ISSUE TITLE
Flathub Documentation misrepresents application IDs

### ISSUE THREAD

**Issue by kkartaltepe** [flathub/flathub#3300]
https://docs.flatpak.org/en/latest/conventions.html#application-ids

In particular `The format is in reverse-DNS style so the first section is a domain controlled by the project`, but this is not the case.

https://github.com/flathub/flathub/pull/464
https://github.com/flathub/flathub/pull/1587
https://github.com/flathub/flathub/pull/1629
https://github.com/flathub/flathub/pull/2795

My understanding is the Plugins is supposed to be a magical keyword that means anyone could have uploaded that plugin but that is not clearly stated. I doubt stating it will prevent any fun and exciting bugs based on this decision but perhaps the documentation should be correct just in case.

**Comment by kkartaltepe** [comment]
Sorry i have found the docs repository.

**Comment by hfiguiere** [comment]
And what you linked at are extensions. For extensions the rule is different, because the `id` represent the type of extension. (I'm the OP of 3 of these PR)

**Comment by kkartaltepe** [comment]
Sure but that is not in the documentation is the point.

Additionally tools do not make such a distinction, e.g. `flatpak search $(any of the above appIDs)` and you get these extensions labeled with "Application ID" not "Extension ID". Im sure this also happens in other things I dont use, probably the software GUIs that people use do exactly what the flatpak tool does.
