### ISSUE TITLE
Archive https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.Surge-XT/

### ISSUE THREAD

**Issue by hfiguiere** [flathub/flathub#3301]
Please archive  https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.Surge-XT/

It has been replaced with https://github.com/flathub/org.surge_synth_team.surge-xt which build the plugins package as well.

**Comment by bilelmoussaoui** [comment]
Could you mark it as EOL please?

**Comment by hfiguiere** [comment]
the binary package `org.freedesktop.LinuxAudio.Plugins.Surge-XT//21.08` is provided by the superceeding repo, so no I shouldn't.

**Comment by bilelmoussaoui** [comment]
I am lost here tbh

**Comment by hfiguiere** [comment]
The plugins are now built out of the standalone app, generating the same flatpak. So we don't EOL the package, it's just built from a different source.

Same case as https://github.com/flathub/flathub/issues/3248

I would have clicked "Archive" already but I don't have the permissions.

**Comment by barthalion** [comment]
Archived.
