### ISSUE TITLE
tv.plex.PlexDesktop: add user with push rights

### ISSUE THREAD

**Issue by sztomi** [flathub/flathub#3302]
Sorry, I mixed up the repos in my previous requests: [tv.plex.PlexDesktop](https://github.com/flathub/tv.plex.PlexDesktop) is the one that @plexappbuilder lacks access to. Could you add it to that repo with push rights? Thanks.

**Comment by bilelmoussaoui** [comment]
Invited

**Comment by sztomi** [comment]
Thank you, I appreciate it!
