### ISSUE TITLE
Add maintainer to org.gajim.Gajim.Plugin.{omemo,openpgp,pgp}

### ISSUE THREAD

**Issue by a-andre** [flathub/flathub#3314]
Please add @lovetox as maintainer to the Gajim plugins `org.gajim.Gajim.Plugin.{omemo,openpgp,pgp}`. He is already a maintainer of org.gajim.Gajim.

**Comment by bilelmoussaoui** [comment]
They seem to already have access to [org.gajim.Gajim.Plugin.pgp](https://github.com/flathub/org.gajim.Gajim.Plugin.pgp), invited them to the other repositories.
