### ISSUE TITLE
Add a maintainer to org.gnome.Todo

### ISSUE THREAD

**Issue by ItsJamie9494** [flathub/flathub#3329]
Hi!

As i've started to become a maintainer for Todo/Endeavour, I would like to have access to the Flathub package. I am listed as a maintainer [in the Endeavour doap](https://gitlab.gnome.org/World/Endeavour/-/blob/main/endeavour.doap).

Thanks a lot!

cc @GeorgesStavracas

**Comment by bilelmoussaoui** [comment]
Invitation sent
