### ISSUE TITLE
The Flathub repository is not accesible in Russia

### ISSUE THREAD

**Issue by acephaleee** [flathub/flathub#3346]
I cant update my apps without using a VPN. I have also found that dl.flathub.org is actually banned in Russia.

**Comment by acephaleee** [comment]
Edit: 
Looks like some Russian IP adresses can get access to repository, but there were many cases of accidental bans of random domains by Russian government.

**Comment by bestperson-free** [comment]
Today I encountered this, only through VPN I was able to update
