### ISSUE TITLE
Team for GNOME core apps

### ISSUE THREAD

**Issue by A6GibKm** [flathub/flathub#3356]
GNOME has a big number of core apps on Flathub, on each release day there are multiple people sending PRs to update the apps but a very small number of people who can review them. It would be useful if we could have GNOME team within the flathub org, so that we could easily grant commit rights across all these repos to the release team and trusted members of our community.

**Comment by nedrichards** [comment]
Yep, happy to do so, it's a good idea.

**Comment by CleoMenezesJr** [comment]
Pretty nice!

**Comment by BrainBlasted** [comment]
I'd be interested. I already handle the apps I maintain, e.g. Weather, Disk Usage Analyzer, Fonts, and Characters

**Comment by A6GibKm** [comment]
I opened a discussion at https://discourse.gnome.org/t/flathub-team-for-gnome-apps/11158

**Comment by hfiguiere** [comment]
I was wondering why I didn't see it in discourse and then realise it was not on Flathub own discourse...

**Comment by A6GibKm** [comment]
@nedrichards @barthalion, after a discussion with the release team this was given a go. Me and @ebassi are interested in being part of the team for now. Is there any other input required?

**Comment by bbhtt** [comment]
This seems done https://github.com/orgs/flathub/teams/gnome, closing. Please open issues to include more release team members.
