### ISSUE TITLE
Please yank aarch64 build of org.blender.Blender

### ISSUE THREAD

**Issue by hfiguiere** [flathub/flathub#3361]
The flathub.json was removed by mistake, and aarch64 flatpak have been produced with x86_64 binaries.

https://github.com/flathub/org.blender.Blender/pull/111#issuecomment-1199934793

And now users are noticing.

https://discourse.flathub.org/t/flatpak-run-org-blender-blender-on-arm-chromebook-has-wrong-architecture/2765

**Comment by barthalion** [comment]
aarch64 were marked for removal, which will happen on the next publish.
