### ISSUE TITLE
Suggestion: Allow --share=network in build-args for the apps that need it, or that would complicate the build process without it

### ISSUE THREAD

**Issue by orowith2os** [flathub/flathub#3392]
This would allow apps that require network access to be built (can't list their sources for one reason or another) to build and publish just fine to flathub, rather than needing to pull pre-built binaries. 
If this isn't possible, an explanation as to why would be appreciated.

**Comment by barthalion** [comment]
We want builds to be reproducible. If you allow network access, any reproducibility guarantees are practically thrown away; the manifest no longer really describes what are the inputs and outputs, build itself is prone to MiTM attacks, and package managers can resolve dependency graphs differently on every run.

**Comment by orowith2os** [comment]
I think part of that can be mitigated by requiring the manifest to list the networks it needs to access, and restricting it to those. One example of why I'm suggesting this is, if an app running through Wine were to be flatpakked, it may need to make requests to external sources to get the necessary dependencies. There are countless more, but there's one.

**Comment by TheBrokenRail** [comment]
This also applies to apps using CMake's `ExternalProject` or `FetchContent`, which oftentimes already have their own verification checks anyways. While these [can be overridden](https://cmake.org/cmake/help/latest/module/FetchContent.html#variable:FETCHCONTENT_SOURCE_DIR_%3CuppercaseName%3E) to use local sources downloaded by Flatpak, it just seems silly IMO to have to keep a redundant copy of the URLs (and hashes) in the Flatpak manifest that has to be manually synced with the main project.

It's not like reproducible builds are guaranteed as-is anyways. After all, Git tags can change which commit they point to and build scripts can do weird unpredictable things. If a developer believes they can build their app with network access while maintaining reproducibility, it should be their choice to do so IMO.

**Comment by hwittenborn** [comment]
I'm wanting this too. I have a Rust project that contains dependencies that call into Go libraries, and getting the Go dependencies to be bundled is proving to be quite the hassle. I'm having quite a few struggles with the [Go `flatpak-builder-tools` tooling](https://github.com/flatpak/flatpak-builder-tools/tree/master/go-get) - I'm not sure if it's the tooling itself or the way I'm using it quite yet, but I honestly just don't care too much about reproducible builds. It would be nice to have, but it's just not a top priority, especially when it's introducing all of this complexity.

Snaps don't require reproducible builds, and it's made it extremely easy to package on there as a result, with my package already being published.

Platforms like the AUR don't require reproducible builds, and it seems to be working just fine on there. I've also created a plethora of projects, none of which are using reproducible builds, and they're all working just fine still.

I just want to get my package up on Flathub. Reproducible builds feels like something I should be able to opt-in at a later time if I want it, but it shouldn't be mandatory. All of it's mostly wrapping back to network access though, as having it forcefully removed is adding in a bunch of complexity to my packaging that I'd rather not have to deal with.

**Comment by gianni-rosato** [comment]
I've been experiencing a similar issue with my application, Aviator. I now have two separate versions with different frameworks because of how convoluted it is to build a package with Rust dependencies as a Flatpak. The crates need to be vendored manually which is an undue burden on the developer. Please listen to the devs, this is a very difficult hurdle to overcome that is becoming a real pain point as development continues and I need to refer people to an alternative repo for the better version of my app.

**Comment by barthalion** [comment]
> I've been experiencing a similar issue with my application, Aviator. I now have two separate versions with different frameworks because of how convoluted it is to build a package with Rust dependencies as a Flatpak

There's no reason why you couldn't build a binary elsewhere and repackage it using Flathub CI.

**Comment by gianni-rosato** [comment]
My app's in Python, & it is atypical to build Python binaries. Is it possible to do this for the dependencies?

**Comment by barthalion** [comment]
One of flatpak-builder arguments is `DIRECTORY`. The `files` subdirectory is essentially what would be exposed as `/app` in Flatpak. You can use it as an artefact and reference in the manifest hosted on Flathub. This is what RetroDeck does, and there's also another app using buildstream to produce that directory.
