### ISSUE TITLE
How to know a runtime isn't needed anymore?

### ISSUE THREAD

**Issue by HROMANO** [flathub/flathub#342]
I like flatpak and flathub, but as I install flatpak apps, I get a lot of runtimes of different versions (gnome 3.24, 3.26, 3.28, kde 5.9, 5.10…), that stay even after the app is uninstalled.
How does one know which runtime isn't needed anymore and can be uninstalled? There needs to be some dependency management (package manager?).

**Comment by nedrichards** [comment]
This sounds like this issue at the flatpak project:

https://github.com/flatpak/flatpak/issues/506
