### ISSUE TITLE
Artifacts in some flatpak apps

### ISSUE THREAD

**Issue by ciro-mota** [flathub/flathub#3443]
**Actual Behavior**

Some flatpak apps such as Black box and Extension manager, when having their windows resized, present these artifacts shown in the attached image. Other flatpak apps installed on this same system do not have this behavior.

In addition to that I don't notice too many hardware acceleration problems on this system.

The theme change was also tested and did not have any effect on the problem presented.

**Flatpak**

1.12.7-5

**Linux distribution**

Fedora Workstation 36 - GNOME

**Graphics**

 X11

**VGA**

AMD RX550

![26-08-22-14-48](https://user-images.githubusercontent.com/57502603/187087015-53e1cf9b-b2a9-4702-b839-ed94ad47df35.png)
![28-08-22-14-16](https://user-images.githubusercontent.com/57502603/187087017-b6eb2570-2fc6-4135-a042-082e6468982b.png)

**Comment by hfiguiere** [comment]
but you forget one important part: which Deskto Environment / Compositor / Window manager as this doesn't look like standard GNOME from Fedora Workstation.

**Comment by hfiguiere** [comment]
But then I doubt this is a Flathub issue anyway.

**Comment by ciro-mota** [comment]
> but you forget one important part: which Deskto Environment / Compositor / Window manager as this doesn't look like standard GNOME from Fedora Workstation.

It's not the default GNOME theme, as I describe the problem occurs both in the default theme and in this specific theme (Flat Remix) as well as in other themes like Dracula.

> But then I doubt this is a Flathub issue anyway.

Please, recommend some testing so I can report the issue to the correct developer/project?

**Comment by barthalion** [comment]
Please report it at https://github.com/flatpak/flatpak.
