### ISSUE TITLE
Qt 6 runtime

### ISSUE THREAD

**Issue by christianparpart** [flathub/flathub#3450]
Hey,

I am looking to package my app using Qt 6 rather than Qt 5 for purely internal technical reasons. I also have no dependency to KDE at all, so requesting some extension to the KDE runtime would be overkill (also given the fact, that KDE is still using Qt 5).

Is there a way to request a Qt 6 runtime, if not here? Or should I start building Qt 6 as part of my own app? But that's something I'd really prefer to avoid, also in order to keep build times as minimal as possible.

**Comment by JakobDev** [comment]
KDE already provides a Runtime for Qt 6. Just use version 6.3 of the KDE runtime.

**Comment by christianparpart** [comment]
> KDE already provides a Runtime for Qt 6. Just use version 6.3 of the KDE runtime.

That wasn't obvious to me for some reason. Thanks.
