### ISSUE TITLE
Adding mainteiners to `com.napster.napster-bigscreen-electron`

### ISSUE THREAD

**Issue by mvgiacomello** [flathub/flathub#3455]
A couple of weeks ago I submitted the Napster app to Flathub: https://github.com/flathub/flathub/pull/3423
Now I need to add [@antebarac](https://github.com/antebarac) as maintainer and also understand why [@lewishut](https://github.com/lewishut) is getting `403`s when trying to push a branch to the repository as he has accepted the [invite that was sent a few days ago](https://github.com/flathub/flathub/pull/3423#issuecomment-1230888060).

**Comment by barthalion** [comment]
Just sent out an invite to @antebarac.

As for Lewis' problem, it sounds like some local misconfiguration. He definitely has write access to the repo.

**Comment by hfiguiere** [comment]
`403` is http. Didn't github disable authenticated http access?

**Comment by razzeee** [comment]
Can this be closed?
