### ISSUE TITLE
Linux Ubuntu. Can't load uri https://flathub.org/repo/flathub.flatpakrepo: Unacceptable TLS certificate

### ISSUE THREAD

**Issue by butterflybob** [flathub/flathub#3456]
Trying to install flatpak on ubuntu linux but I get the error saying "can't load uri https://flathub.org/repo/flathub.flatpakrepo: Unacceptable TLS certificate" after i ran flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

**Comment by jonathon-love** [comment]
this issue popped up a while ago, but then spontaneously fixed itself:

https://github.com/flathub/flathub/issues/2580

however, it seems to have come back again (in the last few days).

i'm using ubuntu 22.04

**Comment by jonathon-love** [comment]
ah, you just need to update your ca certs:

```
sudo apt install ca-certificates
```
