### ISSUE TITLE
m64p has been renamed to simple64 (need to archive io.github.m64p.m64p repo)

### ISSUE THREAD

**Issue by loganmc10** [flathub/flathub#3461]
As per https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life, I am reaching out to inform you that io.github.m64p.m64p has been renamed to io.github.simple64.simple64.

m64p has been updated to point to the new repo:
https://github.com/flathub/io.github.m64p.m64p/blob/d1ea8a98bc82b5f0bd3a05e66f2c996edf2844a4/flathub.json#L3-L4

I believe the final step is for someone to archive the io.github.m64p.m64p repo

**Comment by bilelmoussaoui** [comment]
I have archived the repo, thanks
