### ISSUE TITLE
The icon has not been updated on the app page

### ISSUE THREAD

**Issue by XRenSiu** [flathub/flathub#3464]
The icon has been updated in the published version of the app. The update is now available in Flathub, but the app icon remains from the old version. Can this be fixed?
https://github.com/flathub/net.xmind.XMind

**Comment by JakobDev** [comment]
The Website may take some time

**Comment by XRenSiu** [comment]
> The Website may take some time

[Here is a resolved similar issue.](https://github.com/flathub/flathub/issues/3023)

**Comment by XRenSiu** [comment]
Thanks. The app icon has been updated.
