### ISSUE TITLE
applications on flathub are based on multiple different versions of the same runtime 

### ISSUE THREAD

**Issue by joergister** [flathub/flathub#347]
For users this is a problem that occurs when they are using multiple flatpaked apps:

When they for example install bluefish, it requires the gnome runtime in version 24. Gimp and Thunderbird require the gnome runtime in version 28 and multiple other apps from flathub require the gnome runtime in version 26.
This leads to a lot of used disk space, although this wouldn't be nessesairy if the maintainers would base the apps they maintain on the latest version of the runtime they rely on.

Of cause, everyone could make a pull request to fix small things like this, but I think this is part of the  maintainers job.

please correct me if I'm wrong

Having multiple runtimes installed is just the way flatpak is intended to work. 
But having multiple runtime in multiple different versions installed, makes flatpak and flathub quite unattractive for must users.

**Comment by TingPing** [comment]
Runtimes are de-duplicated so they take less space than you think as as you said that is how Flatpaks are meant to work.

We haven't made an official policy on it but I think it is safe to say that Flathub will slowly move runtime versions forward eventually but 3.28 is fairly new and there is no need to pressure packages from 3.26 yet.

**Comment by TingPing** [comment]
It looks like there are ~17 or so applications using 3.24. I think somebody should honestly just update theme and their deps and submit some PRs.

**Comment by jgarciao** [comment]
Here is a blog post about how flatpak uses ostree to avoid file duplication
https://blogs.gnome.org/alexl/2017/10/02/on-application-sizes-and-bloat-in-flatpak/

**Comment by joergister** [comment]
Ok thanks for clarification.
Of cause, this is always a good thing
