### ISSUE TITLE
Looking for matches… Remote ‘flathub’ found in multiple installations:     1) system    2) user  Which do you want to use (0 to abort)? [0-2]:

### ISSUE THREAD

**Issue by seannewman0915** [flathub/flathub#3481]
what do i do if it says 
Looking for matches…
Remote ‘flathub’ found in multiple installations:

   1) system
   2) user

Which do you want to use (0 to abort)? [0-2]:

**Comment by rusty-snake** [comment]
Answer the question ;)

1. System-wide installation for all users.
2. Only for the current user.

You can also specify `--user` or `--system` to avoid this prompt.
