### ISSUE TITLE
Update to org.freedesktop.Sdk 22.08 breaks aarch64 build

### ISSUE THREAD

**Issue by sebastian-de** [flathub/flathub#3494]
I'd like to update to org.freedesktop.Sdk from 21.08 to 22.08: https://github.com/flathub/dev.lapce.lapce/pull/23
With that change buildbot succeeds on x86_64 but fails on aarch64:
```
Creating ref runtime/dev.lapce.lapce.Debug/aarch64/test with commit 0d204f7310de2bf50e35686eafa667a961bc9b98c16df4191227dc793b6aa4bf
Api call to https://hub.flathub.org/api/v1/build/107336/build_ref failed with status 500, details: {'status': 500, 'error-type': 'no-error', 'message': 'No json error details from server'}
program finished with exit code 1
elapsedTime=112.000994
```
The full build can be found here: https://buildbot.flathub.org/#/builders/32/builds/109700

The error message isn't very helpful, can someone explain to me what it means?

**Comment by Erick555** [comment]
it may be a transient error. You may try restarting it.

**Comment by sebastian-de** [comment]
Thanks, you were right - it worked the second time.

**Comment by hfiguiere** [comment]
@barthalion I see a lot of these errors.
