### ISSUE TITLE
Allow icons with resolution 1024x1024

### ISSUE THREAD

**Issue by darkdragon-001** [flathub/flathub#3536]
It would be nice if icons of size 1024x1024 would also be supported. My build currently fails because of this: https://buildbot.flathub.org/#/builders/32/builds/112909

**Comment by barthalion** [comment]
We follow freedesktop icons theme specification. It's not an arbitrary limit set by Flathub.

**Comment by darkdragon-001** [comment]
@hfiguiere what is the correct path for removal? [a36a853182235fb5676b63ac1e90b750df33e7f7](https://github.com/flathub/io.kopia.KopiaUI/pull/16/commits/a36a853182235fb5676b63ac1e90b750df33e7f7) doesn't seem to be the right one...

**Comment by rowbawts** [comment]
You can check my manifest to see how I resolved it in my project. https://github.com/flathub/sh.cider.Cider/blob/master/sh.cider.Cider.yml

**Comment by hfiguiere** [comment]
> @hfiguiere what is the correct path for removal? [a36a853182235fb5676b63ac1e90b750df33e7f7](https://github.com/flathub/io.kopia.KopiaUI/pull/16/commits/a36a853182235fb5676b63ac1e90b750df33e7f7) doesn't seem to be the right one...
> 
> On the builder, it is `/srv/buildbot/worker/build-x86_64-5/build/builddir/export/share/icons/hicolor/1024x1024/apps/io.kopia.KopiaUI.png`, but `rm /app/share/icons/hicolor/1024x1024/apps/io.kopia.KopiaUI.png` doesn't seem to work.

Because that's not the right icon name as there is a `rename-icon` at the top. Can delete a file that doesn't exist.
