### ISSUE TITLE
Create style guide for yaml

### ISSUE THREAD

**Issue by TingPing** [flathub/flathub#354]
Now that `flatpak-builder` supports yaml we should probably standardize on a style since it is a very flexible format.

Here was my first port for my thoughts on the best layout: https://github.com/flathub/io.github.GnomeMpv/blob/yaml/io.github.GnomeMpv.yml

**Comment by TingPing** [comment]
Made a basic page here: https://github.com/flathub/flathub/wiki/YAML-Style-Guide

Just documents the worst offenders IMO. Feedback welcomed.

**Comment by eszlari** [comment]
How about:
- Put `sources` always at the **end** of a module.
- Don't nest modules. (example: https://github.com/flathub/com.github.wwmm.pulseeffects/blob/master/com.github.wwmm.pulseeffects.yml)

What about the three dashes (“---”)?

**Comment by barthalion** [comment]
Nesting modules isn't really related to YAML or JSON and we don't disallow this. Same about `sources` location – we pay attention to this during initial review but later on, maintainers can do what they want.

I'm for starting files with `---` but given it's not required for yaml to be correct, I don't think we can demand this.
