### ISSUE TITLE
Unarchive org.kde.kate and move it to beta

### ISSUE THREAD

**Issue by travier** [flathub/flathub#3541]
Please unarchive https://github.com/flathub/org.kde.kate and move the default branch to beta.

We've fixed the majors issues that blocked this application from functioning correctly inside Flatpak (https://invent.kde.org/teams/flathub/issues/-/issues/9#note_482296) and we will progressively test it to make it stable.

Thanks!

**Comment by travier** [comment]
CC @flathub/kde

**Comment by barthalion** [comment]
I have unarchived the repo and renamed the `master` branch to `beta`. You will need to push a new commit to trigger a build.

**Comment by travier** [comment]
Thanks!
