### ISSUE TITLE
Orphaning com.jetbrains.PyCharm-Professional

### ISSUE THREAD

**Issue by johanfleury** [flathub/flathub#3546]
Hi.

I’ll be removing myself from the list of contributors on the [flathub/com.jetbrains.PyCharm-Professional](https://github.com/flathub/com.jetbrains.PyCharm-Professional) repository. I’m not and never have been a PyCharm user [^1] and I was only doing the minimal amount of work needed to keep it up to date (mainly merging PRs from external-data-checker).

In the past months, @freeseacher contributed quite a bit to the repository so they might be a good candidate to take over the maintenance (if they agree of course).

For an eventual future maintainer, I think PCP and PCC are basically the same thing and it might be a good idea to actually “rebase” on PCC.

---

[^1]: I created this package because at the time a colleague of mine needed PCP and wanted to rely on snap which I couldn’t tolerate :D

**Comment by freeseacher** [comment]
Yep. Why not. I use Pycharm on linux quite a lot, and already have all the stuff to test and build it

**Comment by barthalion** [comment]
I've sent an invite to @freeseacher. Thanks!
