### ISSUE TITLE
ARM/ARMHF Support

### ISSUE THREAD

**Issue by qstambaugh** [flathub/flathub#3554]
Is "arm" still supported? I know aarch64 has great support (been using flathub with my pinephone), but my older chromebook is stuck with an older architecture (armhf under Debian). I noticed packages from flathub for it haven't been updated in a long time. Gajim is still on 1.2.2, Evolution 3.38.0, LibreOffice 7.0.1.2, etc. I just wasn't sure if that's a bug or if it's intended.

**Comment by rusty-snake** [comment]
https://discourse.flathub.org/t/revisiting-arm-32-bits-support-answer-no/924
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1105

**Comment by qstambaugh** [comment]
Ah okay, thank you for the information. I'll just use Debian's repositories then.
