### ISSUE TITLE
Applying for a 'finish-args-unnecessary-xdg-data-access' exception for com.github.GradienceTeam.Gradience

### ISSUE THREAD

**Issue by LyesSaadi** [flathub/flathub#3557]
Hello,

Gradience being an app which applies some sort of theming to other apps, we added a feature to create overrides in-app so that those changes are applied in flatpak apps as well (this is only done if the user agrees to it). For that to work, we need this permission:
```
        "--filesystem=xdg-data/flatpak/overrides:create",
```

**Comment by barthalion** [comment]
Should be done, please trigger a new build. Thanks!

**Comment by LyesSaadi** [comment]
Thank you!
