### ISSUE TITLE
remove io.github.jazztickets.openflap

### ISSUE THREAD

**Issue by jazztickets** [flathub/flathub#3561]
I recently migrated the project to GitLab, so I need the old github app-id deleted off flathub.org

https://flathub.org/apps/search/openflap

Thanks

**Comment by JakobDev** [comment]
The old ID will disappear automatically from Flathub, after you set it the EOL with the flathub.json. By [looking at the Repo](https://github.com/flathub/io.github.jazztickets.openflap) I found out that you had add a flathub.json, but all builds after that failed. You need at least one successful build with the EOL flathub.json to mark the old ID EOL.

**Comment by jazztickets** [comment]
The archive url link just needs to be updated to `https://gitlab.com/jazztickets/uploads/-/raw/main/openflap-1.0.4r66-src.tar.gz`.

The master branch is protected though.

**Comment by JakobDev** [comment]
Try to make a PR against the master branch

**Comment by jazztickets** [comment]
Ok, it should be here: https://github.com/flathub/io.github.jazztickets.openflap/pull/1

**Comment by JakobDev** [comment]
Your new build has failed, because some links in the AppStream broke:
```
builddir/files/share/appdata/io.github.jazztickets.openflap.appdata.xml: FAILED:
• file-invalid          : <screenshot> failed to load [https://jazztickets.github.io/docs/openflap/img/s_01.png]
```
You should not have deleted the old repo.

**Comment by jazztickets** [comment]
Clearly
