### ISSUE TITLE
media.emby.EmbyServer build failed

### ISSUE THREAD

**Issue by alucryd** [flathub/flathub#3562]
The last build of emby failed saying the screenshot url points to an empty file, but that isn't the case. See https://github.com/flathub/media.emby.EmbyServer/pull/3
Should we host the image somewhere else?

Edit: Oh, it might not like the redirection, will try updating the link.

**Comment by barthalion** [comment]
Yeah, I wonder if it's some coincidence with recent infra changes. There are several apps failing like this but URLs seem to redirect to https://raw.githubusercontent.com now. Doesn't seem to be related to anything that has changed lately.

**Comment by hfiguiere** [comment]
Filed https://github.com/flathub/org.flatpak.Builder/issues/108

**Comment by alucryd** [comment]
Thanks for the quick fix. We went ahead and switched to direct links in the meantime. The latest build passed.
