### ISSUE TITLE
io.gitlab.Goodvibes: appid-code-hosting-too-few-components

### ISSUE THREAD

**Issue by elboulangero** [flathub/flathub#3563]
Heya,

Links to start with:
* https://buildbot.flathub.org/#/builders/32/builds/114430
  * https://buildbot.flathub.org/#/builders/10/builds/13774
  * https://buildbot.flathub.org/#/builders/7/builds/8984

So I understand that Flatpak wants my app to be named `io.gitlab.goodvibes.Goodvibes` rather than `io.gitlab.Goodvibes`. I don't have any issue with that, however this is something I will do in the next release of my application, not now. Changing the app id requires a bit of care and testing.

In the meantime, if you can grant an exception for this time, so that I can push this release, that would be greatly appreciated. Thanks in advance!

**Comment by hfiguiere** [comment]
Filed https://github.com/flathub/flatpak-builder-lint/pull/25 for an exception.

Renaming is not as simple as it require resubmitting, etc.

**Comment by hfiguiere** [comment]
Exceptions was added.

**Comment by elboulangero** [comment]
I can confirm that the exception is in effect, the build succeeded today. Thanks a lot for your support!
