### ISSUE TITLE
Can't push to master branch of Flathub repo

### ISSUE THREAD

**Issue by TheBrokenRail** [flathub/flathub#3568]
When I try to push it says:
```
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 293 bytes | 293.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Changes must be made through a pull request.
To github.com:flathub/com.thebrokenrail.MCPIReborn.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:flathub/com.thebrokenrail.MCPIReborn.git'
```

It seems silly that I have to push to another branch, create a PR, merge said PR, then delete the previous branch just to workaround this.

**Comment by hfiguiere** [comment]
this was announced that there would be no more push directly to master.

See https://discourse.flathub.org/t/enforcing-pull-request-workflow-and-green-ci-status-of-prs/3109

**Comment by TheBrokenRail** [comment]
I still think it's silly for projects only maintained by one person, but OK.

**Comment by marysaka** [comment]
> this was announced that there would be no more push directly to master.
> 
> See https://discourse.flathub.org/t/enforcing-pull-request-workflow-and-green-ci-status-of-prs/3109

It would have been better to inform maintainers of repositories by pinning something here.

Because of it I cannot automate the release process for Ryujinx anymore and need to change everything again 🙃

**Comment by barthalion** [comment]
@marysaka https://github.com/flathub/flatpak-external-data-checker/ uses pull request workflow and can automatically merge changes if they pass CI.

**Comment by barthalion** [comment]
I'd still recommend improving this automation to use pull requests and CI status to decide whether to merge a change. That being said, as it's a first-party app, I have disabled the requirement for Ryujinx.

**Comment by barthalion** [comment]
On 12/10/2022 14.32, Mary-nyan wrote:
> Would it be possible to add @RyujinxBot <https://github.com/RyujinxBot> 
> to the repository on that matter?

Sure, I've just sent an invite. You will need to accept it manually for 
the bot to have write access.
