### ISSUE TITLE
dl.flathub.org no longer works as repository url

### ISSUE THREAD

**Issue by hammerandtongs** [flathub/flathub#3569]
I have some older installs of flatpak pointed at dl.flathub.org (I believe).

flatpak began failing to download manifests from that url with remote fetch errors etc.

adding this to /etc/hosts

`dl.flathub.org flathub.org`

gets me working flatpak updates again.

dl.flathub.org still resolves (into a cdn?) so I'm not quite clear whats happening but it would seem like backend issues.

**Comment by barthalion** [comment]
This is very unlikely as there's no drop in the number of downloads, and flathub.org simply redirects any flatpak traffic to dl.flathub.org. What are the exact errors are you seeing?

**Comment by hammerandtongs** [comment]
I've tested on the 2 hosts (using 2 different northwest pops) and its working again. Maybe some replication issues in the cdn.
