### ISSUE TITLE
Clearly mark paid content

### ISSUE THREAD

**Issue by sofar** [flathub/flathub#357]
So first let me just state that I think it's great that there is paid content and it's not excluded.

However, it would be really nice if content that is freely downloadable but not accessible or only partially accessible due to needing to pay for something, would be clearly marked.

The case here is `Albion` which requires a subscription. Nothing wrong about it, but I just downloaded several gigabytes of data and went through an account registration until I discovered that there is no free content. At least, I don't see any.

Suggestion is to have some sort of checkboxes that can be marked (multiple possible):
- Requires subscription
- Requires a purchase
- Contains in-app purchases
- Contains advertisements
- Contains microtransactions

With that info, people will be more clearly informed that just downloading the software may not grant them access to the software, or sign up for something that they don't want to.

**Comment by TingPing** [comment]
The application correctly sets this: https://github.com/flathub/com.albiononline.AlbionOnline/blob/master/com.albiononline.AlbionOnline.appdata.xml#L54

So really this is a request for GNOME-Software or Plasma Discover to expose it.

**Comment by TingPing** [comment]
Can start an issue for discussing the website here: https://github.com/flathub/linux-store-frontend

**Comment by razzeee** [comment]
I'll close this here, as this seems to be website driven. We do have an OARS issue open over there.
