### ISSUE TITLE
Please disable pull request commit enforcement for com.bitwig.BitwigStudio

### ISSUE THREAD

**Issue by abique** [flathub/flathub#3576]
Hi,

Following up with https://discourse.flathub.org/t/enforcing-pull-request-workflow-and-green-ci-status-of-prs/3109, I request that you disable the PR enforcement against the master branch for com.bitwig.BitwigStudio.

We have a jenkins jobs which takes care of publishing new versions and your changes breaks our workflow and makes everything more complicated for absolutely no benefits.

For us publishing a new version only changes the version and the hash, which is a super minimal change.

Thank you.

**Comment by rusty-snake** [comment]
Related: #3568

**Comment by barthalion** [comment]
This is done now. Please make sure to include our linter into your pipeline.
