### ISSUE TITLE
No access to my repository

### ISSUE THREAD

**Issue by mimbrero** [flathub/flathub#3579]
Hello,

I have no permissions to push to [my repository](https://github.com/flathub/io.github.mimbrero.WhatsAppDesktop). I changed my GitHub main email a while ago, maybe this is the reason. What can I do?

Thanks :)

**Comment by barthalion** [comment]
Please make sure to push to a branch and open a pull request instead of pushing directly to master. See https://discourse.flathub.org/t/enforcing-pull-request-workflow-and-green-ci-status-of-prs/.

**Comment by mimbrero** [comment]
Oh, sure. Sorry and thanks :)
