### ISSUE TITLE
Delete beta branch of my flatpak repo

### ISSUE THREAD

**Issue by MehdiChinoune** [flathub/flathub#3582]
Before beta branch get protected I was using it as an experimental branch, after It got protected (Without getting any notice!) I am stuck with it.
[flathub/com.github.makhber.Makhber](https://github.com/flathub/com.github.makhber.Makhber)

**Comment by hfiguiere** [comment]
Notice was posted https://discourse.flathub.org/t/enforcing-pull-request-workflow-and-green-ci-status-of-prs/3109/

**Comment by MehdiChinoune** [comment]
https://discourse.flathub.org/t/enforcing-branch-protection-on-existing-repositories/1935
They announce after they apply rules not before!
