### ISSUE TITLE
remote: error: Required status check "builds/x86_64" is expected. Changes must be made through a pull request.        

### ISSUE THREAD

**Issue by nukeop** [flathub/flathub#3591]
Hi, sorry for this highly enigmatic title - this is what I get in CI: https://github.com/NuclearPlayer/nuclear-nightly-flatpak/actions/runs/3261612965/jobs/5356903275

I've got a CI job that updates the flatpak repo when I build artifacts on my main repo. So far it was able to just push to master, trigger a build, and set it to deploy automatically. I have it configured this way for several Linux user repositories, so that they're always up to date. Is it still possible to automate deployments somehow? I'm afraid that if I have to do this manually through pull requests every time it's going to make my program update less frequently.

**Comment by JakobDev** [comment]
You can use [f-e-d-c](https://github.com/flathub/flatpak-external-data-checker) to create a PR. You can also configure it to automatic merge that PR.

**Comment by hfiguiere** [comment]
if only you told us which flatpak you are talking about...

**Comment by nukeop** [comment]
Normally, I monitor the build via the Github action that runs it. But it's fine to this rule in place. 
How would I automate this process in this case though? I see it like this:

1. An artifact gets built on my main repo.
2. The flatpak updater is notified, and pushes the updated flatpak config to a branch, then opens a pull request.
3. The pull request goes through CI checks and is then approved or rejected automatically.
4a. I need to be notified in case of a failing PR build. Not sure how yet.
4b. In case of success, the PR should be merged to master automatically. Also not sure how to approach this. Maybe both cases can be handled by an action that monitors PRs.

**Comment by jralls** [comment]
> This looks like a system-wide change that went live some time ago, like I said I was able to push to master until recently.

GnuCash was able to push directly on the 15th, one day before this was filed. So not "Some time ago".

>  If you are not following the regular PR process,

@barthalion Where was this new requirement announced or better discussed with participating project admins?

**Comment by jralls** [comment]
@barthalion Can you at lease enable auto-merge on repositories so that project admins don't have to baby-sit the redundant CI checks to merge a release?

**Comment by barthalion** [comment]
@jralls The change has been announced at https://discourse.flathub.org/t/enforcing-pull-request-workflow-and-green-ci-status-of-prs/3109/1. It wouldn't be practical to discuss it with >1000 people maintaining some packages on Flathub.

I have lifted the requirement for GnuCash. I do recommend you switch to pull request workflow instead, of course.

**Comment by barthalion** [comment]
> Normally, I monitor the build via the Github action that runs it. But it's fine to this rule in place. How would I automate this process in this case though? I see it like this: (…)

Yeah, this makes sense. For both 4a/4b, you would need to poll opened PRs and their statuses, and take some action based on that. For now, I've disabled the requirement for your repo.
