### ISSUE TITLE
A bot to merge beta branch to master branch automatically

### ISSUE THREAD

**Issue by ilya-fedin** [flathub/flathub#3592]
In org.telegram.desktop, we have such an action: https://github.com/flathub/org.telegram.desktop/blob/beta/.github/workflows/beta-merger.yml.

This makes the workflow fully automated: a new version of the application is released -> flathubbot creates a PR with the update -> if the build passes, it's automatically merged -> if the release is stable, the action merges it to master. It also automatically merges libraries updates to master if the current version of the application is stable.

Unfortunately, the action is broken now with the following messages:
```
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Required status check "builds/x86_64" is expected. Changes must be made through a pull request.      
```

This will make the time between the update is released and accessible for stable flathub users a way bigger and some releases to be skipped just like before the action was implemented as it's a manual intervention we often forget about.

Would be nice to have a bot that will provide the same functionality or an exception.

**Comment by barthalion** [comment]
I have disabled the PR workflow requirement for Telegram repo.

**Comment by ilya-fedin** [comment]
Thanks!
