### ISSUE TITLE
Remove branch protection in tv.plex.PlexHTPC and tv.plex.PlexDesktop

### ISSUE THREAD

**Issue by sztomi** [flathub/flathub#3601]
It appears that we can no longer push to these repos with our @plexappbuilder user due to branch protection being enabled. Could you please remove that setting?

Also, if possible, please give our colleague push access as well: https://github.com/moussa

**Comment by sztomi** [comment]
Sorry, I was made aware that this is a policy change.

**Comment by barthalion** [comment]
@sztomi If this interferes with your workflow, we can disable it.

**Comment by barthalion** [comment]
I've invited @moussa to both repos.

**Comment by sztomi** [comment]
>  If this interferes with your workflow, we can disable it.

I appreciate that! I'll defer to @Moussa to answer - it sounded like it shouldn't be a problem. The reason I opened it in the first place was because (not being aware of the policy change) I assumed we would need a flathub team member to approve each PR. Which sounded like a very long wait, seeing how overloaded with tasks you are.

**Comment by Moussa** [comment]
@barthalion @sztomi I think it's fine to keep the branch protection if I can merge the PRs myself. Thanks both 👍
