### ISSUE TITLE
I can not update manifest, because branch 'master' is a protected branch

### ISSUE THREAD

**Issue by vikdevelop** [flathub/flathub#3605]
I want update manifest of repository [flathub/com.github.vikdevelop.timer](https://github.com/flathub/com.github.vikdevelop.timer) but I can not, because branch `master` is a _protected branch_. Why? Previously I could normally update manifest via `master` branch.

**Comment by hfiguiere** [comment]
You have to make a PR and merge it when it passes CI.

This is now enforced as a policy
