### ISSUE TITLE
Pushing the same commit to two branches requires two pull requests

### ISSUE THREAD

**Issue by kparal** [flathub/flathub#3609]
Now that [direct pushes are disabled](https://barthalion.blog/enforcing-pull-request-workflow-and-green-ci-status-of-prs-on-flathub-repositories/) to `master` and `beta`, there is a problematic behavior which I don't think makes much sense. When my `master` and `beta` point to the same branch (they are not diverged), I can't fast-forward one to the other, even if the other was already approved through a pull request. My attempt is rejected with the following message:
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Changes must be made through a pull request.
```
So in order to update a different head to the **same commit** (already approved), I have to create a second PR, completely in vain.

Example:
1. Both `master` and `beta` point to commit [ec9c744](https://github.com/flathub/org.freefilesync.FreeFileSync/commit/ec9c744763890c7772fb3d12289640a5d496f759).
2. `beta` gets updated to a commit [5982d09](https://github.com/flathub/org.freefilesync.FreeFileSync/commit/5982d09d29f7b8feab2c808598745a5a49dbddf5) through a [PR](https://github.com/flathub/org.freefilesync.FreeFileSync/pull/85). The commit 5982d09 is clearly marked as verified in the PR:
    ![commit](https://user-images.githubusercontent.com/755451/198273421-87408d47-1348-4cc3-bbfd-7d7fefd6a676.png)
3. It should be possible to fast-forward `master` to the same commit 5982d09, but it isn't, due to the current flathub setup:
    ```
    $ git switch master
    Switched to branch 'master'
    Your branch is up to date with 'origin/master'.

    $ git merge --ff-only beta
    Updating ec9c744..5982d09
    Fast-forward
     README.md | 40 ++++++++++++++++++++++++++--------------
     1 file changed, 26 insertions(+), 14 deletions(-)

    $ git push
    Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
    remote: error: GH006: Protected branch update failed for refs/heads/master.
    remote: error: Changes must be made through a pull request.
    To github.com:flathub/org.freefilesync.FreeFileSync.git
     ! [remote rejected] master -> master (protected branch hook declined)
    error: failed to push some refs to 'github.com:flathub/org.freefilesync.FreeFileSync.git'
    ```
4. Another PR has to be made to update `beta`->`master`, i.e. one protected (already verified) branch to another, which means manual work, CI work, and waiting.

Can you please verify commits once, instead of once per each target branch? Or allow fast-forward merges from already protected branches?

**Comment by bbhtt** [comment]
GitHub doesn't allow doing this, not much we can do. You can't directly push to a protected branch, no matter if they point to the same commit.
