### ISSUE TITLE
Disable master branch protection for com.boxy_svg.BoxySVG

### ISSUE THREAD

**Issue by jarek-foksa** [flathub/flathub#3612]
I would like to opt-out from the branch protection policy that was [introduced recently](https://discourse.flathub.org/t/enforcing-pull-request-workflow-and-green-ci-status-of-prs/3109). I'm only updating version numbers and checksums in my commits and the old approach with direct pushes to the master branch was much easier to automate.

**Comment by barthalion** [comment]
Done.
