### ISSUE TITLE
As an application maintainer, can not push to beta branch

### ISSUE THREAD

**Issue by Yvan-Masson** [flathub/flathub#3621]
Hi,

I just tried to publish a new version of an application (https://github.com/flathub/fr.masson_informatique.WhosWho/). As I understand, the new process is to push to the `beta` branch and then make a pull request to the `master` branch. But when I try to push to the beta branch, it prints the following error:

```
$ git push
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 4 threads
Compressing objects: 100% (9/9), done.
Writing objects: 100% (9/9), 1.69 KiB | 1.69 MiB/s, done.
Total 9 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 1 local object.
remote: error: GH006: Protected branch update failed for refs/heads/beta.
remote: error: Required status check "builds/x86_64" is expected. Changes must be made through a pull request.
To github.com:flathub/fr.masson_informatique.WhosWho.git
 ! [remote rejected] beta -> beta (protected branch hook declined)
error: failed to push some refs to 'github.com:flathub/fr.masson_informatique.WhosWho.git'
```

I am not at ease with Git and Github: can someone tell me what I doing wrong?

Thanks,
Yvan

**Comment by hfiguiere** [comment]
> As I understand, the new process is to push to the `beta` branch and then make a pull request to the `master` branch.

no that's not the process. I has never been. `beta` is protected, like `master` or `branch/*`
The process is to push to branch that is NOT named beta, and do a pull request. Like any other github project.

**Comment by Yvan-Masson** [comment]
Oh thanks for the explanation, I have probably read too fast…

Regards,
Yvan
