### ISSUE TITLE
Add maintainer for org.polymc.PolyMC

### ISSUE THREAD

**Issue by binex-dsk** [flathub/flathub#3623]
I would like to maintain org.polymc.PolyMC as I was a previous maintainer, and the other maintainer has moved to a new flatpak.

**Comment by Soup-64** [comment]
See: https://github.com/flathub/flathub/issues/3600#issuecomment-1286591722

**Comment by binex-dsk** [comment]
> See: [#3600 (comment)](https://github.com/flathub/flathub/issues/3600#issuecomment-1286591722)

hence why I am asking to be added, as the project is still active.

**Comment by Soup-64** [comment]
Active is subjective to some extent, but the main takeaway from the comment linked is that the flathub maintainers will revisit it when they deem enough time has passed, so it's ultimately up to them to choose when to review the project again, and it has not passed the window specified in the comment either.

**Comment by barthalion** [comment]
I have restored @binex-dsk's write access and also invited @LennyMcLennington as per e-mail to flathub-admins.

**Comment by binex-dsk** [comment]
Thank you!
