### ISSUE TITLE
Low quality screenshots on flathub

### ISSUE THREAD

**Issue by jonathon-love** [flathub/flathub#363]
hi,

i appreciate there's a trade-off between image quality and file-size, but i'm wondering if the image quality can't be bumped up a bit?

(currently, it sorta gives the impression that the software is crappier than it actually is)

with thanks

<img width="1161" alt="screen shot 2018-05-02 at 07 42 57" src="https://user-images.githubusercontent.com/3240247/39495527-efa486d4-4ddd-11e8-81f6-36a9fa95623f.png">

**Comment by TingPing** [comment]
Probably best reported against the website here: https://github.com/flathub/linux-store-frontend

**Comment by jonathon-love** [comment]
ah yup, wasn't sure where it was generated, or which of these two projects was responsible. will do.

**Comment by nedrichards** [comment]
Also possibly worth talking to the general appstream community as these
assets have to be used on software stores on device too.
