### ISSUE TITLE
acer problem

### ISSUE THREAD

**Issue by gamerboy7811** [flathub/flathub#3632]
i put in this code (sudo flatpak install flathub com.unity.UnityHub)
 after this code (sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo) and it syas (Nothing matches com.unity.UnityHub in remote flathub)
can you help me out.

**Comment by gamerboy7811** [comment]
btw i have an acer swift 3

**Comment by applecuckoo** [comment]
Hey, what Linux distro are you using? Putting down the model doesn't help very much.

**Comment by gamerboy7811** [comment]
i'm using chrome os if thats what you mean
    On Sunday, November 13, 2022 at 10:35:18 PM EST, applecuckoo ***@***.***> wrote:  
 
 


Hey, what Linux distro are you using? Putting down the model doesn't help very much.

**Comment by razzeee** [comment]
Did you follow the complete instructions on https://flatpak.org/setup/Chrome%20OS ?
