### ISSUE TITLE
Add proprietary AMD drivers as a runtime extension

### ISSUE THREAD

**Issue by orowith2os** [flathub/flathub#3642]
Some apps, such as OBS, might rely on the proprietary AMD drivers for features such as AMF. Additionally, I've recently came across some bugs in other apps where they don't occur on the proprietary drivers, but do on the open source ones. Having AMDGPU-PRO as a runtime extension would be appreciated for both bugtesting and workflows that require it.

It shouldn't take as much work to support compared to the NVIDIA drivers, as one can run the proprietary and open source AMD drivers side-by-side without issue, and without the versioning issues.

**Comment by firefoxlover** [comment]
This! AMDGPUPro is also not supported on most distros.

If it helps somehow, there is a distrobox for those, made by the ublue team. 

ghcr.io/ublue-os/arch-distrobox-amdgpupro

**Comment by bbhtt** [comment]
This isn't really the place the post packaging requests, you should post to https://discourse.flathub.org/c/requests/5.

The way the system works is if someone wants it, they or someone else from the community has to submit it. There is no resource for fulfilling requests.
