### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by RossComputerGuy** [flathub/flathub#3651]
I tried connecting to Flathub and it looks like the server is down.
![image](https://user-images.githubusercontent.com/19699320/202521559-541cbcd0-ef2c-473c-ba16-1be37d73c0dc.png)

**Comment by RossComputerGuy** [comment]
Yeah, https://flathub.org should take you to an app store looking frontend which you can see isn't showing up in the screenshot.

**Comment by Andreas-Utkilen** [comment]
When will the repo be up and running again?

**Comment by RossComputerGuy** [comment]
> the repositories seem online
> 
> ```
> $ flatpak search chrome
> Name                                Description                                                                                                                 Application ID                           Version            Branch   Remotes
> Google Chrome (unstable)            The web browser from Google                                                                                                 com.google.ChromeDev                     109.0.5410.0-1     stable   flathub
> Google Chrome                       The web browser from Google                                                                                                 com.google.Chrome                        107.0.5304.110-1   stable   flathub
> Chromium Web Browser                The web browser from Chromium project                                                                                       org.chromium.Chromium                    107.0.5304.110     stable   flathub
> ungoogled-chromium                  A lightweight approach to removing Google web service dependency                                                            com.github.Eloston.UngoogledChromium     107.0.5304.110     stable   flathub
> CrosAdapta                          Chrome OS GTK theme                                                                                                         org.gtk.Gtk3theme.CrosAdapta                                3.22     flathub
> PhotoQt Image Viewer                View and manage images                                                                                                      org.photoqt.PhotoQt                      2.9.1              stable   flathub
> Firestorm Viewer                    Client for accessing 3D virtual worlds                                                                                      org.firestormviewer.FirestormViewer      6.3.9.58205        stable   flathub
> Joplin                              A free, open source note taking and to-do application, which can handle a large number of notes organised into notebooks.   net.cozic.joplin_desktop                 2.8.8              stable   flathub
> Google Play Music Desktop Player    Run Google Play Music as a standalone desktop app                                                                           com.googleplaymusicdesktopplayer.GPMDP   4.7.1              stable   flathub
> Gabut Download Manager              Simple and Faster Download Manager                                                                                          com.github.gabutakut.gabutdm             1.9.9              stable   flathub
> Postman                             Postman is a complete API development environment.                                                                          com.getpostman.Postman                   10.1.2             stable   flathub
> Boxy SVG                            Scalable Vector Graphics editor                                                                                             com.boxy_svg.BoxySVG                     3.94.1             stable   flathub
> Shortwave                           Listen to internet radio                                                                                                    de.haeckerfelix.Shortwave                3.1.0              stable   flathub
> ```
> 
> But websites for flatpak.org, flathub.rog and extensions.gnome.org are not online. Meaning: one can still install software via command line or gnome software.

Yeah this part works but this link (https://flathub.org/repo/flathub.flatpakrepo) does not work. So it doesn't seem entirely online.

**Comment by Andreas-Utkilen** [comment]
Yes, trying to add the repo does not work.
`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
`error: Can't load uri https://flathub.org/repo/flathub.flatpakrepo: Server returned status 503: Service Unavailable`

**Comment by junocomp** [comment]
I am having the same issue

**Comment by byquanton** [comment]
https://status.flathub.org/
and i guess also related to https://status.gnome.org/

**Comment by junocomp** [comment]
I can see that, on terminal it still saying the service is unavailable. I am connected to the internet and it is working on other websites.

**Comment by barthalion** [comment]
Nothing related to package installation (or builds) is affected by this outage. Please subscribe to the status page for updates.
