### ISSUE TITLE
Discussion about publishing Warzone 2100 on Flathub directly

### ISSUE THREAD

**Issue by past-due** [flathub/flathub#3652]
(At @barthalion 's request, I'm opening this Issue here.)

With the release of Warzone 2100 4.3, there are now officially supported upstream Flatpak builds (and configuration).

But this means that, currently, Warzone 2100 has 2 Flatpak manifests: one hosted in Flathub, and the upstream one. Instead of maintaining this in two separate places, we'd like to standardize on upstream.

Among the benefits of prioritizing the upstream manifest are:
- Warzone 2100’s CI immediately catches build errors
- It’s managed by upstream
- Releases can be automatically published based on tags, as part of our release process

The last point is especially important for a game like Warzone 2100 that heavily benefits from all clients having the same, up-to-date version (as multiplayer only works between clients that are all the same build), and a simplified workflow for making new releases.

So we’d like to publish Warzone 2100 releases on Flathub directly. We have been largely inspired in our setup by the OBS Studio CI setup. This is already building `.flatpak` files as part of our releases, and we've just merged the plumbing to perform `flat-manager-client` publishing steps as well.

-----

For @barthalion's review:

Our CI setup has some extra pieces to handle how we automate releases, and we are executing the command-line tools directly (instead of using the `flatpak-github-actions`) so we can handle some quirks related to cross-compiling for aarch64 from GitHub Actions runners (which are currently only x64).

However, the high-level overview is:
- https://github.com/Warzone2100/warzone2100/tree/master/.ci/flatpak
   - Specifically: 
      - [build.sh](https://github.com/Warzone2100/warzone2100/blob/master/.ci/flatpak/build.sh) - used for executing the `flatpak-builder` process, building a `.flatpak` (for manual installation), and various validation (appstream, icons, metadata)
      - [publish_to_flathub.sh](https://github.com/Warzone2100/warzone2100/blob/master/.ci/flatpak/publish_to_flathub.sh) - used to replicate the steps of the [flat-manager GitHub Action](https://github.com/flatpak/flatpak-github-actions/tree/master/flat-manager)
- the workflow: https://github.com/Warzone2100/warzone2100/blob/master/.github/workflows/CI_flatpak.yml
   - Specifically, the `build-flatpak` and `publish-release-to-flathub` jobs
      - Note: These have some extras related to our release and CI process, and we have split up build and publishing into separate jobs (transferring the ostree repo between them) so we can use a separate, more tightly-scoped environment for publishing (to restrict secret access and provide additional auditing as part of our release process).

We've tested this to the extent that is possible (absent the appropriate tokens).

Please let me know if you have any questions / suggestions, and we'd be happy to test with the `FLATHUB_BETA_TOKEN` whenever you are ready.

**Comment by bbhtt** [comment]
@past-due Is this solved now? Warzone 2100 is being pushed from upstream.

**Comment by bbhtt** [comment]
Done
