### ISSUE TITLE
Flatpak not working in iran?

### ISSUE THREAD

**Issue by PhantomRex123** [flathub/flathub#3654]
Hello, i have been recently facing issues with Flatpak.

This is my log:

```
ryan@joe:~$ flatpak install flathub dev.lapce.lapce
Looking for matches…



error: Unable to load summary from remote flathub: Socket I/O timed out
ryan@joe:~$ 
```

**Comment by barthalion** [comment]
You can try running

``
flatpak remote-modify --no-follow-redirect flathub  --url=https://front-ams.flathub.org
```

or

```
flatpak remote-modify --no-follow-redirect flathub  --url=https://front-hex2.flathub.org
```

This will bypass the CDN, which probably can't provide its services for US-sanctioned countries.

**Comment by PhantomRex123** [comment]
> You can try running
> 
> ```
> flatpak remote-modify --no-follow-redirect flathub  --url=https://front-ams.flathub.org
> ```
> 
> or
> 
> ```
> flatpak remote-modify --no-follow-redirect flathub  --url=https://front-hex2.flathub.org
> ```
> 
> This will bypass the CDN, which probably can't provide its services for US-sanctioned countries.

Hello it seems the issue has not been resolved. i get the same exact error, any ideas?
