### ISSUE TITLE
gimp is missing meta information

### ISSUE THREAD

**Issue by FlorianLudwig** [flathub/flathub#366]
`updated` and `version` are quite useful ;)

**Comment by TingPing** [comment]
It has a version tag, I think the website didn't update it yet because of this issue: https://github.com/flathub/org.gimp.GIMP/issues/8

**Comment by TingPing** [comment]
I'd look into it locally but webkitgtk doesn't even build here: `make[1]: *** [GNUmakefile:53732: Source/WebCore/bindings/js/libWebCore_la-JSMediaSourceStatesCustom.lo] Segmentation fault (core dumped)
`
