### ISSUE TITLE
Enforce strict permissions

### ISSUE THREAD

**Issue by firefoxlover** [flathub/flathub#3673]
There is a huge number of apps that are just directly ported to Flatpak, without any change in behavior. 

Flatpaks make no sense like that, they need to be containerized and only be granted file access through portals of actively chosen permissions. 

Apps that have /home or host filesystem permissions are (nearly) as insecure as native installs, making the use of Flatpak containerization obsolete. 

Maybe different repositories like "flathub-insecure" and "flathub" could work, so that users actively have to enable the insecure repo, because they get the wrong conception "flatpaks are safe because they are containerized", while that is not true.

The use of Portals has to be enforced and advocated.

[Here is an issue listing all apps with access to the host filesystem](https://github.com/flathub/flathub/issues/2180)

Apps accessing `host` files I found:
- FreeCAD
- FreeFileSync
- KDiskMark
- MakeMKV
- Pitivi (also outdated library)
- PyCharm Professional
- Syncthing GTK
- VSCodium
- ...

Apps accessing `~/` :
- Zotero
- XNViewMP
- XNVConvert
- Tagger
- Session
- F-Droid Repomaker
- PuTTY
- OCRFeeder
- Notorious
- Libreoffice
- LeoCAD
- Giada
- ...

**Comment by bbhtt** [comment]
Most of this is implemented in the linter and manually checking modifications of permissions now.

`host` or `home` is too widely used for legitimate reasons that we cannot block it.

The safety ratings on flathub.org convey that applications with such access are not safe.
