### ISSUE TITLE
Limitation of usable Libraries

### ISSUE THREAD

**Issue by firefoxlover** [flathub/flathub#3674]
It is not unusual for Flatpak users to have 4+ GB of libraries, just because all Flatpak apps can choose their own.

This makes no sense, bloating the system to an unnessecary extent and increasing RAM usage, making Flatpaks slower and heavier on resources.

Containerization should be the future, but not random like that.

Please advocate the use of LTS-like libraries, so that every app can actually run on the same, apart from a few very outdated ones.

Please ensure backwards compatibility in those libraries too.

**Comment by orowith2os** [comment]
Flatpak deduplicates binaries where it can, so even if apps choose their own libraries they will still be efficient on storage. The main runtimes also do keep backwards compatibility, they can update their components so long as there's no ABI breakage.

How flatpak handles libraries is already as efficient as it can be, to keep all the benefits of having a stable runtime.

**Comment by firefoxlover** [comment]
Thanks for the insight! Yes its really good that Libraries are shared, and if you know what you do you can just not install apps that require some weird old Libraries, especially if they reach EOL.

This is actually really nice to do in the Terminal, I dont like to use a GUI software anymore, because its way less transparent imo. 

Still, some setting to auto-exclude EOL runtimes or something would maybe help make it more secure. EOL Runtimes should not be downloaded with just an error warning, but should require manual allowing.

**Comment by orowith2os** [comment]
Technically they already are manually allowed to be installed when you install an application that relies on that runtime, and Flatpak isn't very quiet about EOL packages. If an app is using an EOL runtime then it should be updated asap.
