### ISSUE TITLE
Enforce correct reverse DNS usage

### ISSUE THREAD

**Issue by firefoxlover** [flathub/flathub#3675]
At the moment, developers can name their apps how they want.

This results in unofficial builds like the Fedora GIMP Flatpak having the same packagename as the official GIMP Flatpak.

This is confusing and insecure, as the origin of not yet securely isolated Flatpaks can be faked easily, it seems.

**Comment by JakobDev** [comment]
> At the moment, developers can name their apps how they want.

On Flathub the correct reverse DNS scheme is needed or the Admins will not allow the App to be published

> This results in unofficial builds like the Fedora GIMP Flatpak having the same packagename as the official GIMP Flatpak.

`org.gimp.GIMP` is the coreect name of the Software, so that is the Name all Packages should use. If you use another Name, it can easily break things.

> This is confusing and insecure, as the origin of not yet securely isolated Flatpaks can be faked easily, it seems.

If I try to install Gimp on my System (I have Flathub and Gnome Nightly as remotes), I get this prompt:
```
$ flatpak install org.gimp.GIMP
Looking for matches?
Remotes found with refs similar to org.gimp.GIMP:

   1) flathub (system)
   2) gnome-nightly (user)

Which do you want to use (0 to abort)? [0-2]: 
$ 
```

Why is this confusing?

**Comment by orowith2os** [comment]
Application developers are strongly suggested to use the appropriate reverse-DNS name, so I don't get how they're able to publish to Flathub under the wrong name. If they *do* use the wrong name, then they should EOL the wrong name and resubmit with the correct name.

Where the packages originate from doesn't change the reverse-DNS name, who maintains the application does. If two different developers maintain two different forks of GIMP, then the packages for those should use the appropriate names, which would be different.

I also don't see how the origin of the apps can be misconstrued, unless the repository name isn't shown to users? Or the repository name on the end user's system was changed to the wrong name.
