### ISSUE TITLE
Failed installation through flatpak

### ISSUE THREAD

**Issue by YYCCaa** [flathub/flathub#3685]
Failed to open file "/proc/sys/kernel/random/boot_id": No such file or directory

**Comment by rusty-snake** [comment]
Your issue report should contain more information like
- the flatpak you tried to install
- flatpak version
- distro and version
- kernel version
- ...

**Comment by orowith2os** [comment]
Provide the above information, and this is an issue for [Flatpak](https://github.com/flatpak/flatpak), not Flathub.
