### ISSUE TITLE
Flatpak does not work in Azerbaijan

### ISSUE THREAD

**Issue by jcovik** [flathub/flathub#3695]
Hello from September flatpak stopped working. I can't download anything from dl.flathub.org.
Is there any way to fix this?
![Screenshot from 2022-12-07 00-25-07](https://user-images.githubusercontent.com/102985950/206015325-95c65373-2ee1-4330-9cb8-7490acb62d5f.png)

**Comment by razzeee** [comment]
You could try this https://barthalion.blog/test-driving-flathub-mirror-for-users-in-china/

**Comment by jcovik** [comment]
Hello! Sorry that I did not respond, I forgot that I opened issue about this. 

I tried to the mirror, but it has the same problem. Around February, I switched my provider from AzTelekom to MetroNet, and now I don't have any problems with Flatpak. I did not investigate the reasoning behind blocking Flatpak IPs, so I can't say anything about this.

Because of all of this, I am closing the issue.
