### ISSUE TITLE
SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by XSpielinbox** [flathub/flathub#3713]
When trying to update applications from flathub (running `sudo flatpak update` with flathub repo configured) with the [FUTURE crypto-policy](https://fedoraproject.org/wiki/Changes/StrongCryptoSettings3) enabled in Fedora Linux 37 oder RHEL 9 errors like the following occur:
```
Error: While pulling runtime/org.gnome.Platform.Locale/x86_64/43 from remote flathub: While fetching https://dl.flathub.org/repo/objects/97/990ad73edc13fa80b052028838e3f227c580a192b871a86253d48cbd7ad4ca.commitmeta: [60] SSL peer certificate or SSH remote key was not OK
Updates complete.
error: There were one or more errors
```

This error is very likely due to the fact that dl.flathub.org serves a 2048 bit RSA TLS Cert, but modern cryptography standards require 3072 bit or more when using RSA.

**Comment by barthalion** [comment]
Isn't it, ultimately, the problem you caused yourself? 2048-bit RSA certificates are very common across the Internet, and I see no reason to change anything on our end.

**Comment by XSpielinbox** [comment]
I don't see it as a valid argument that 2048 bit RSA is very common across the internet and therefore nothing needs to be changed. For example SHA-1 has been proven insecure now over and over again and it is still used widely, nevertheless.
If everybody just waits for the the others to change we will never arrive at strong Crypto.

Many guidelines already require better TLS, see:
- https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TG02102/BSI-TR-02102-1.pdf?__blob=publicationFile
- https://www.ecrypt.eu.org/csa/documents/D5.4-FinalAlgKeySizeProt.pdf
- https://english.ncsc.nl/binaries/ncsc-en/documenten/publications/2021/january/19/it-security-guidelines-for-transport-layer-security-2.1/IT+Security+Guidelines+for+Transport+Layer+Security+v2.1.pdf

Of course, it was expected that not everything will work with the FUTURE policy already, but fortunately many things already do and Flathub is one of the remaining things that does not.
Therefore I raised this issue that Flathub hopefully becomes usable also with strong crypto policies - the "FUTURE" policy may not have a concrete date yet, when it will become the standard policy, but it definitely is the way the cryptography should be heading already today.

If you (for whatever reason) can't upgrade to a 3072 bit RSA Cert yet, a dual-cert approach with offering ECDSA in addition would be possible as well.

**Comment by bbhtt** [comment]
The change proposal got rejected from Fedora and it's not using SHA1 signatures.

```
openssl s_client -connect master.flathub.org:443 < /dev/null 2>/dev/null | openssl x509 -text -in /dev/stdin | grep "Signature Algorithm"
        Signature Algorithm: sha256WithRSAEncryption
    Signature Algorithm: sha256WithRSAEncryption
~ 
→ openssl s_client -connect dl.flathub.org:443 < /dev/null 2>/dev/null | openssl x509 -text -in /dev/stdin | grep "Signature Algorithm"    
        Signature Algorithm: sha256WithRSAEncryption
    Signature Algorithm: sha256WithRSAEncryption
```

So I don't think this is an issue.

The RSA parameter size is a different issue.

**Comment by bbhtt** [comment]
It'll be changed when they switch.
