### ISSUE TITLE
[Building] Allow prioritizing package builds on flathub based on whether they build from source or prebuilt binaries

### ISSUE THREAD

**Issue by orowith2os** [flathub/flathub#3740]
I don't think Flathub currently has any priority checking of application builds, however I think it would be ideal to allow specifying package bases inside of an application's flathub.json.

This would allow for getting binary-based builds done faster, or source-based ones, depending on how Flathub wants to handle it.

**Comment by bbhtt** [comment]
There is little point in adding this and seems unfair and will push people to submit or convert source packages to binary ones
