### ISSUE TITLE
[Graphics library request] Add experimental Asahi Linux Mesa extension

### ISSUE THREAD

**Issue by orowith2os** [flathub/flathub#3743]
Asahi Linux is currently in the process of writing GPU drivers for the Apple Silicon macs, and as it might not be ideal to keep backwards compatibility, they might want to break userspace often.

This issue is meant as a request to add https://gitlab.com/OroWith2Os/mesa-git-asahi-flatpak to Flathub Beta, for testing and ease-of-distribution to end users testing Asahi Linux.

EDIT: There's also https://gitlab.com/refi64/mesa-asahi-extension apparently, TIL.

Probably appropriate to @asahilina @alyssarosenzweig and @refi64

**Comment by refi64** [comment]
Heh, it does look like we were operating on similar ideas there, though your repo seems to be a lot further along in terms of cleaning things up than mine vs just switching the branch.

**Comment by orowith2os** [comment]
Oh, I ended up moving my work over to GitHub while porting it to YAML. I've made some decent progress, though now I need to figure out how to build it as a runtime extension and get it to show in `flatpak --gl-drivers`

https://github.com/orowith2os/mesa-asahi-flatpak

**Comment by barthalion** [comment]
I'm not going to block it from being merged to beta, but obviously it needs to be submitted like everything else.

**Comment by orowith2os** [comment]
Alright, thanks for confirming. We just need to figure out some things on our end, like 32-bit builds, I'm not sure if the extension will be affected by everything the other fd.o extensions are, since iirc things like MangoHud can't build for both x86+x86_64 *and* arm+arm64 at the same time.

**Comment by hfiguiere** [comment]
why would 32bits matter here?

**Comment by orowith2os** [comment]
Mainly for WINE usage, since most Windows applications running through it only support x86 and Wine doesn't (yet) support WoW64, so it pulls in tons of 32-bit deps.

Applications like Steam are what I'm thinking of as well.

**Comment by orowith2os** [comment]
*note, I was speaking in the context of running x86 WINE on top of some form of emulation like qemu-user-static. I'm not sure if 32-bit libs would be needed for native aarch64.

**Comment by orowith2os** [comment]
Update: the org.freedesktop.Sdk.Compat.arm extension seems to be deprecated, so only 32-bit x86 builds are needed.

When the [appropriate issue](https://github.com/flatpak/flatpak-builder/issues/381) is resolved I'll submit this to Flathub.

**Comment by orowith2os** [comment]
X86 builds will rely on tons of unrelated things (page sizes, etc) to be resolved before they will work properly, so for aarch64-only workflows the current manifest should work fine. 

I can look into submitting it (hopefully) soon, how would Flathub like to handle the extension? Is it possible to keep it inside of Flathub Beta?

**Comment by orowith2os** [comment]
I'll close this, since it's probably safest to use a third party repo like the Open Build System.
