### ISSUE TITLE
Dashes in group ID.

### ISSUE THREAD

**Issue by shymega** [flathub/flathub#3745]
Hi,

I'm looking to make a Flatpak for the Barrier fork, Input-Leap.

However, our GitHub organisation is named `input-leap`, and `flatpak-builder` doesn't seem to like that name.

It's a bit late for us to change the name completely, and with the name of the project officially being `Input Leap`, or `input-leap` (in sources), this presents a particular challenge.

Is there a way to get past this limitation?

Thank you.

**Comment by rusty-snake** [comment]
I don't think so because the actual limitation comes from D-Bus.


https://docs.flatpak.org/en/latest/conventions.html

> - `org.example-site.Foo`
>
> This ID is not valid according to the DBus specification. You can use `org.example_site.Foo` instead.

**Comment by shymega** [comment]
Ahh, of course. D-Bus. OK, so I'll change the app ID to `com.github.input_leap.input-leap`, and that should be fine. Does it matter that the app ID doesn't correspond 1:1 to the GitHub layout, though?

**Comment by rusty-snake** [comment]
- https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-names
  > Each element must only contain the ASCII characters "[A-Z][a-z][0-9]_" and must not begin with a digit. 
- https://docs.flatpak.org/en/latest/conventions.html
  > - `com.github.foo.Bar`
  > While a project may be hosted on GitHub it does not have any control over the github.com domain. Instead you should use io.github as shown above.

So `io.github.input_leap.input_leap` or `io.github.input_leap.InputLeap` would be the best choices I guess.

It's not possible to include the "correct" github layout. There are already flatpaks out there with the same problem, just search for `flatpak search --columns=application _`.

**Comment by shymega** [comment]
Thanks for the heads-up. I've adjusted my branch to reflect these recommendations.
