### ISSUE TITLE
Request to add maintainers to io.github.Icalingua.Icalingua

### ISSUE THREAD

**Issue by xtexChooser** [flathub/flathub#3747]
Hello,

[io.github.Icalingua.Icalingua](https://github.com/flathub/io.github.Icalingua.Icalingua/pulls)

This repository doesn't look well maintained. I created a new PR and nobody reviews. All PRs to bump version by flathub bot are also not merged. There are a lot of new features and bug fixes, but unavailable on flathub.

I request to add some new maintainers, or, at least, merge some PRs of new version.

**Comment by hfiguiere** [comment]
merged the pending flathubbot PR. thanks for for bringing out to our attention.

**Comment by xtexChooser** [comment]
Thanks.
