### ISSUE TITLE
Can't build Electron-based app: cache mode is 'only-if-cached' but no cached response is available

### ISSUE THREAD

**Issue by jarek-foksa** [flathub/flathub#3760]
I'm no longer able to build new versions of my Electron-based app after updating `flatpak-node-generator`  and other dependencies. The automated build system is throwing the following error:  

> request to https://registry.npmjs.org/electron failed: cache mode is 'only-if-cached' but no cached response is available.

This happens even though I'm using `npm install --offline` and I provide the [generated-sources.json](https://github.com/flathub/com.boxy_svg.BoxySVG/blob/5491912ca51c9755315035544e98541c26d6b520/generated-sources.json) file. It seems to be the same issue as #2993.

**Comment by jarek-foksa** [comment]
I managed to make the build system work again by downgrading NPM version installed on my machine from 9.2.0 to 8.19.3 and recreating generated-sources.json file using that older NPM version.

Any ideas how to make it work with NPM 9? I'm already using the latest version of flatpak-node-generator which [should support v3 lockfiles](https://github.com/flatpak/flatpak-builder-tools/issues/333).

**Comment by barthalion** [comment]
Hi Jarek,

I think the best would be to report an issue at https://github.com/flatpak/flatpak-builder-tools. Alternatively, if you're using something similar to electron-builder, it's also possible to repackage a prebuilt tarball or AppImage.

**Comment by jarek-foksa** [comment]
Yeah, it looks like the problem is caused by this specific tool. I just created a separate issue to track it: https://github.com/flatpak/flatpak-builder-tools/issues/339.

**Comment by DUB1401** [comment]
I solved this problem by using **yarn** and specifying the home directory. Example in https://github.com/flathub/flathub/pull/7045.
