### ISSUE TITLE
Suggestion: Let apps select either Mesa or Mesa (extra) runtime

### ISSUE THREAD

**Issue by user1-github** [flathub/flathub#3762]
Since recently, Flathub downloads both Mesa and Mesa (extra) runtimes by default, which creates unnecessary duplication. The same duplication occurs with 32 bit Mesa runtime as well. So when both 64 bit and 32 bit runtimes are duplicated, about 700mb of disk space is wasted.

**Comment by barthalion** [comment]
```
/v/l/f/runtime ❱ du -sh org.freedesktop.Platform.GL.default/x86_64/22.08{,-extra/}
348M	org.freedesktop.Platform.GL.default/x86_64/22.08
25M	org.freedesktop.Platform.GL.default/x86_64/22.08-extra/
```

The actual size difference between 22.08 and extra variants is 25MB. It's not worth the hassle, and there's no reason app maintainers should be concerned about it at all.

**Comment by user1-github** [comment]
Oh ok, my bad then. Seems Gnome Software doesn't show the correct size of every runtime.
