### ISSUE TITLE
Building your first Flatpak using a directory

### ISSUE THREAD

**Issue by convertto2** [flathub/flathub#3763]
Hello,

I building my [first Flatpak](https://docs.flatpak.org/en/latest/first-build.html), but is-it possible to add a directory instead of only one file (hello.sh), I tried :
```
sources:
      - type: dir
        path: hello
```
"hello" is a directory with 2 files : "hello.sh" and "hello2.sh"
but my second file is never packaged ?

Thanks

**Comment by rusty-snake** [comment]
Well did you `install` it during the build?

And btw this is an issue tracker and not a support forum.

**Comment by convertto2** [comment]
I search a support forum or a tutorial.

**Comment by rusty-snake** [comment]
https://github.com/flatpak/flatpak/blob/main/README.md

> Community discussion happens in [#flatpak:matrix.org](https://matrix.to/#/#flatpak:matrix.org), on [the mailing list](https://lists.freedesktop.org/mailman/listinfo/flatpak), and on [the Flathub Discourse](https://discourse.flathub.org/).

**Comment by convertto2** [comment]
Thanks
