### ISSUE TITLE
Add maintainer to net.crossfireatlas.crossfire

### ISSUE THREAD

**Issue by jmeloranta** [flathub/flathub#3784]
I would like to **add** maintainer to net.crossfireatlas.crossfire: tannerrj (on github).

Thanks,
Jussi Eloranta

**Comment by jmeloranta** [comment]
Anyone, help?

**Comment by barthalion** [comment]
Just sent an invite to @tannerrj. Please make sure to accept it in a few days, otherwise it silently expires. Thanks!
