### ISSUE TITLE
Allow action: `gr2m/create-or-update-pull-request-action`

### ISSUE THREAD

**Issue by dreua** [flathub/flathub#3786]
Can you add the Github Action `gr2m/create-or-update-pull-request-action` to the list of allowed actions? Either globally or for [PDF Arranger](https://github.com/flathub/com.github.jeromerobert.pdfarranger).

Thanks!

**Comment by dreua** [comment]
May I bump this?

**Comment by barthalion** [comment]
Hey @dreua, we already allow `peter-evans/create-pull-request` for two apps: https://github.com/search?q=org%3Aflathub+peter-evans%2Fcreate-pull-request&type=code Is there anything that the action you request does better?

**Comment by razzeee** [comment]
Yes, there are security implications and man power implications on flathubs end as it does not scale to check every action, that someone wants to enable.

In the long run, the change to your own build system, will help with this.

**Comment by dreua** [comment]
Where can I see the list of already allowed actions?

**Comment by razzeee** [comment]
https://docs.flathub.org/docs/for-app-authors/github-actions#using-github-actions-on-your-flathub-repository

**Comment by dreua** [comment]
> In the long run, the change to your own build system, will help with this.

I assume that is not yet possible, right?

Otherwise thank you for adding the documentation!

**Comment by razzeee** [comment]
Technically it's possible, but currently we try to not do it, as it's labor intensive on our end.

When we have all the pieces automated, it should become generally available.
