### ISSUE TITLE
Flathub bot builds the application way too long.

### ISSUE THREAD

**Issue by mrquantumoff** [flathub/flathub#3794]
Lately when I try to update my app by merging new manifest from my fork to flathub/io.github.mrquantumoff.mcmodpackmanager "bot, build"/new pr takes way to too long. Previously it took not more than 4-5 minutes, but now the build doesn't start even after 12 minutes after the pr was opened.

**Comment by mrquantumoff** [comment]
![image](https://user-images.githubusercontent.com/36820091/211210171-4d822602-d269-4237-b3bd-174bdeb8f648.png)

**Comment by mrquantumoff** [comment]
![image](https://user-images.githubusercontent.com/36820091/211210212-4bed821a-412e-4759-a8f8-1db144920585.png)
There is nothing on the flathub buildbot website either

**Comment by hfiguiere** [comment]
it's queued. that mean it hasn't started.

**Comment by mrquantumoff** [comment]
> it's queued. that mean it hasn't started.

I know, but previously it was starting much faster then it is now.

**Comment by Bluefissure** [comment]
It takes hours for the last step as committing, is it normal?

**Comment by Bluefissure** [comment]
![image](https://user-images.githubusercontent.com/9719003/211722043-f41c59a6-a484-47a1-8b34-b0c57ff9baf5.png)
All of them are pending for committing except for `org.gottcode.CuteMaze`, which is running the committing for 3 hours, and the latest log message shows it's waiting for commit job:
![image](https://user-images.githubusercontent.com/9719003/211722253-95764726-de2e-4226-971f-55b5332b09a3.png)
Is the commit job temporarily on hold for any reason?

**Comment by Bluefissure** [comment]
![image](https://user-images.githubusercontent.com/9719003/211723764-1ed2bcbb-e922-4a87-88f9-68eb2bfbc580.png)
With the finished log, we can tell that it was pending 3 hrs for the committing step to start (when other build tasks are at the committing step and I guess it's blocking other tasks) and then took 1 hour (`elapsedTime=3608.337507`) for the commit job to finish.

**Comment by barthalion** [comment]
There was an entry about it on https://status.flathub.org/. It's solved by now.
