### ISSUE TITLE
request to archive https://github.com/flathub/org.racket_lang.DrRacket

### ISSUE THREAD

**Issue by capfredf** [flathub/flathub#3801]
Hi there, 

The https://github.com/flathub/org.racket_lang.DrRacket can be archived because it has been superseded by https://github.com/flathub/org.racket_lang.Racket

**Comment by JakobDev** [comment]
You should add
```json
"end-of-life-rebase": "org.racket_lang.Racket"
```
to the flathub.json before archiving

**Comment by bilelmoussaoui** [comment]
Done
