### ISSUE TITLE
Manual publishing doesn't work

### ISSUE THREAD

**Issue by Bluefissure** [flathub/flathub#3803]
I manually published https://buildbot.flathub.org/#/builders/6/builds/16644 after building successfully, but it's not working: no `repository` and no `revision` in https://buildbot.flathub.org/#/builders/2/builds/5809 , and the app info is not correctly updated after publishing (both in flathub.org and flatpak).

![image](https://user-images.githubusercontent.com/9719003/211945854-7d84f14f-7972-4db7-ae5c-623a1f550ac6.png)

Does that mean I have to wait until the auto-publish in 3 hours?

**Comment by hfiguiere** [comment]
There are ongoing issues. Just be patient.

**Comment by Bluefissure** [comment]
Seems to be working fine now
