### ISSUE TITLE
why are the changes to my app not showing up even after 7 hours on FlatHub?

### ISSUE THREAD

**Issue by vikdevelop** [flathub/flathub#3808]
Hello,
I made some changes to the application [com.github.vikdevelop.timer](https://github.com/flathub/com.github.vikdevelop.timer) added it to the manifest, the build was successful, so I merged the Pull request. The changes included new screenshots, but the changes didn't show up even after 7 hours, previously they showed up after 4 hours. So what is the problem?

**Comment by barthalion** [comment]
The repository was undergoing maintenance today. See https://status.flathub.org/issues/2023-01-13-repo-prune/.
