### ISSUE TITLE
Mongo Compass update was successfully built but it's stuck

### ISSUE THREAD

**Issue by mijorus** [flathub/flathub#3821]
I am the maintainer of the wrapper

The app was updated to version 1.35 and was built successfully 5 days ago
https://github.com/flathub/com.mongodb.Compass/pull/15

Screenshots are also broken on flathub, despite the preview images are perfectly reachable 

https://github.com/flathub/com.mongodb.Compass

**Comment by razzeee** [comment]
I guess newer versions fixed this? :/

**Comment by mijorus** [comment]
Yes, this is very old indeed
