### ISSUE TITLE
Remove unused/unmaintained protected branches of org.freedesktop.Sdk.Extension.mono6

### ISSUE THREAD

**Issue by darkdragon-001** [flathub/flathub#3824]
The branches `branch/19.08` and `branch/20.08` of https://github.com/flathub/org.freedesktop.Sdk.Extension.mono6 are no longer maintained. Can someone please remove?

**Comment by hfiguiere** [comment]
no they shouldn't be removed since they reference a specific build.

**Comment by darkdragon-001** [comment]
How can I mark them as deprecated or unmaintained then?

**Comment by hfiguiere** [comment]
EOL is the only way: https://docs.flathub.org/docs/for-app-authors/maintanance/#end-of-life

But given that these already depend on an EOL runtime...

**Comment by darkdragon-001** [comment]
I marked both as EOL.
