### ISSUE TITLE
Revisit release changelog guidelines

### ISSUE THREAD

**Issue by ptomato** [flathub/flathub#383]
According to the [app requirements][1] app submissions should ideally include a changelog.

I'm preparing to submit Sublime Text to Flathub and including the [rather long changelog][2] makes the appdata file not pass `appstream-util validate` with a flood of errors. This is due to two reasons:
- the markup in the release description tag only allows `<p>`, `<ul>`, `<ol>`, and `<li>`, so we have to misuse `<p>` for headings which makes appstream-validate complain because a `<p>` is not ending with `.`, `:`, or `!`;
- there's an undocumented 100-character limit on `<li>` items.

These restrictions seem a bit on the draconian side if we want to allow upstream changelogs from community-submitted apps, unless community submitters are required to spend time summarizing and editorializing. Maybe the app requirements page should include some guidance on which appstream-validate rules are OK to be broken here?

[1]: https://github.com/flathub/flathub/wiki/App-Requirements
[2]: https://www.sublimetext.com/3

**Comment by TingPing** [comment]
So firstly we do have this requirement:

> pass appstream-util validate-relax (bonus points for validate or validate-strict).

So any extra restrictions that `validate` adds is acceptable to ignore.

I think most of those complaints are fairly reasonable for upstreams to follow but if they do not I don't expect downstream packagers to modify it.

**Comment by ptomato** [comment]
In this case you are told you get the "bonus points" by not including the upstream changelog :smile: It seems like the incentives are wrong there...

**Comment by TingPing** [comment]
Well, I personally think it should be common sense it means passing `validate` without removing content. We can reword it a bit though sure.

**Comment by razzeee** [comment]
Current docs say `validate`, would that be okay? https://docs.flathub.org/docs/for-app-authors/requirements#appstream

**Comment by bbhtt** [comment]
The current docs for this is here https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines#release-notes

Quality guidelines are optional but strongly recommended

I think this can be closed.
