### ISSUE TITLE
Please archive or delete com.github.itext.i7j_rups

### ISSUE THREAD

**Issue by nbenitez** [flathub/flathub#3835]
[com.github.itext.i7j_rups](https://flathub.org/apps/details/com.github.itext.i7j_rups ) has been replaced by  [com.itextpdf.RUPS](https://flathub.org/apps/details/com.itextpdf.RUPS ) from a long time ago.

So please remove [com.github.itext.i7j_rups](https://flathub.org/apps/details/com.github.itext.i7j_rups ) , I'm the packager of both.

Thanks, :-)

**Comment by JakobDev** [comment]
Your old App has a flathub.json with a EOL notice, but is not marked as EOL on Flathub. You should trigger a rebuild, so this App will be marked as EOL on Flathub

**Comment by nbenitez** [comment]
It seems not possible to rebuild, check out my attempt at https://github.com/flathub/com.github.itext.i7j_rups/pull/4

**Comment by hfiguiere** [comment]
well, if you mess with the manifest name, no surprise. You should NEVER rename the manifest or change id. If you revert back to before it should work.
