### ISSUE TITLE
Screenshots are stretched horizontally

### ISSUE THREAD

**Issue by alexkdeveloper** [flathub/flathub#3837]
Screenshots of the following applications, like many others, are very stretched horizontally.
https://flathub.org/apps/details/com.belmoussaoui.Authenticator
https://flathub.org/apps/details/org.gnome.design.Palette
https://flathub.org/apps/details/io.github.lainsce.Colorway
https://flathub.org/apps/details/com.github.alexkdeveloper.somafm

**Comment by barthalion** [comment]
This has been fixed since.
