### ISSUE TITLE
Add a reference to a new site to visit statistics in the wiki

### ISSUE THREAD

**Issue by mijorus** [flathub/flathub#3839]
I would like to ask if it was possible to add a reference to a new website to browse Flathub's stats

Disclaimer: this  webapp is mine
[https://flatstat.mijorus.it/](https://flatstat.mijorus.it/)

The source code can be found here
https://github.com/mijorus/flatstat

Thank you

**Comment by JakobDev** [comment]
The Stats are already shown on the [new Beta Website](https://beta.flathub.org/) on Flathub, so this is not really needed

**Comment by mijorus** [comment]
all right, thank you
