### ISSUE TITLE
Proposal: snap to flatpack conversion how to, script or package

### ISSUE THREAD

**Issue by mitcoes** [flathub/flathub#385]
I would love to migrate ANBOX (now in snap) to flatpack

As snaps are not working in arch distributions and flatpacks work anywhere.

And i would love to use a container for running android games

Also, if it is posible to learn how to make flatpaks to make a Freedos in LXC one and a ReactOS in LXC one, as I think easy to install LXC OSs in flatpaks  will increase the use of GNU/Linux making it easier to run other OSs in containers as MS and Chrome OS are doing with GNU/Linux.

**Comment by TingPing** [comment]
> I would love to migrate ANBOX (now in snap) to flatpack

Can't be done, it requires root access.

Anyway <package format> to flatpak conversion is a concept that doesn't really map with reality. They are very different things.

**Comment by TingPing** [comment]
You would have to run the root parts outside of the sandbox, it would be ugly and not portable largely defeating the purpose of Flatpak. The Snap is likely also not really portable due to that.

**Comment by mitcoes** [comment]
Thanks.
