### ISSUE TITLE
Rename io.github.mrquantumoff.mcmodpackmanager to dev.mrquantumoff.mcmodpackmanager

### ISSUE THREAD

**Issue by mrquantumoff** [flathub/flathub#3854]
I've bought a domain for myself recently and I want to update my app's id to my own domain

**Comment by JakobDev** [comment]
You have to submit the App new with the changed ID. After it got merged, set the old as [End of Life](https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life).

**Comment by mrquantumoff** [comment]
Ok, thanks
