### ISSUE TITLE
Sdk (fdo//aarch64/21.08) download failure on buildbot

### ISSUE THREAD

**Issue by hfiguiere** [flathub/flathub#3870]
aarch64 build fail because
```
Error: Failed to update org.freedesktop.Sdk: While pulling runtime/org.freedesktop.Sdk/aarch64/21.08 from remote flathub: URI https://dl.flathub.org/repo/deltas/Eo/5m3ULrmBAjtkZEcH2KO7LWYnzFQLqnRaTTC9PtJ9M-WYKjtyOaZUIrI4NITggeBGcPSXAFNTofmfGw9LFc5vU/3 exceeded maximum size of 373777 bytes
```

See https://buildbot.flathub.org/#/builders/9/builds/1733

**Comment by hfiguiere** [comment]
I have been able to install the 21.08 SDK on aarch64. (platform was already up to date).

Still happening in the buildbots.

**Comment by hfiguiere** [comment]
Also I have been able to install it on a system that didn't have the platform installed.

**Comment by barthalion** [comment]
This is fixed on builders now.
