### ISSUE TITLE
Corrupted cached images for com.bitwig.BitwigStudio

### ISSUE THREAD

**Issue by abique** [flathub/flathub#3873]
Hi,

The graphics are corrupted: https://flathub.org/apps/details/com.bitwig.BitwigStudio
I believe this followed the recent server issues.
Republishing the package didn't fix it.
I suspect that many application may have the same issue, so you maybe want to re-download/process all the images.

Thank you for taking care of it.

**Comment by barthalion** [comment]
This should be fixed now. If it isn't for you, please make sure to hard refresh the page with Ctrl+Shift+r.

**Comment by abique** [comment]
Thank you very much!
