### ISSUE TITLE
Removal of beta branch from com.github.eneshecan.WhatsAppForLinux

### ISSUE THREAD

**Issue by eneshecan** [flathub/flathub#3880]
Please remove the beta branch from the repo as we don't need it anymore and it creates a lot of confusions on every release.

**Comment by eneshecan** [comment]
Any update on this?

**Comment by bilelmoussaoui** [comment]
you need to mark the beta branch as EOL first i think

**Comment by eneshecan** [comment]
Done!

**Comment by bbhtt** [comment]
`beta` is a protected branch https://docs.flathub.org/docs/for-app-authors/maintenance/#the-repository, there's no need to delete it. It'll remove any git history for the beta flatpak.
