### ISSUE TITLE
No IPv6 support

### ISSUE THREAD

**Issue by UnderEu** [flathub/flathub#3903]
flathub.org doesn't support the current Internet protocol (IPv6), requiring not only users but ISPs to circumvent the lack of its support with mechanisms that lead to latency increase, slow downloads and, worst case scenario, complete unavailability to your stuff.

![image](https://user-images.githubusercontent.com/16519758/218221609-56c70ae2-00a1-4719-bb31-a029c6d69e02.png)

No, this is not a feature request. Lack of IPv6 connectivity, in 2023, is a bug and has to be addressed so users can enjoy their connections' full pottential and you become future-proof.

**Comment by barthalion** [comment]
The download endpoint is IPv6-compatible:

```
;; ANSWER SECTION:
dl.flathub.org.		3432	IN	CNAME	dualstack.k.sni.global.fastly.net.
dualstack.k.sni.global.fastly.net. 19 IN AAAA	2a04:4e42::649
dualstack.k.sni.global.fastly.net. 19 IN AAAA	2a04:4e42:200::649
dualstack.k.sni.global.fastly.net. 19 IN AAAA	2a04:4e42:400::649
dualstack.k.sni.global.fastly.net. 19 IN AAAA	2a04:4e42:600::649
```

Users of the website will have to deal with it until our hosting provider supports it.

**Comment by rail01** [comment]
I am yet to see a more ignorant and disrespectful answer to a bug report this year, but you're a solid champion so far.

**Comment by gtxaspec** [comment]
https://www.mythic-beasts.com/sales/ipv6

The hosting provider supports Ipv6, perhaps you may want to reach out to enable ipv6.
