### ISSUE TITLE
Corrupted cached screenshot for org.cznic.Datovka

### ISSUE THREAD

**Issue by Sesivany** [flathub/flathub#3910]
The screenshot image linked in the metainfo file looks fine: https://www.datovka.cz/images/desktop-main.png
But the cached screenshot is corrupted: https://dl.flathub.org/repo/screenshots/org.cznic.Datovka-stable/624x351/org.cznic.Datovka-5b847e76ee4edb64c92ff5a42ad1625d.png

Even after updating and rebuilding the flatpak.

**Comment by barthalion** [comment]
This should be fixed now.
