### ISSUE TITLE
Add `kavplex` as a maintainer of the `com.hunterwittenborn.Celeste` repository

### ISSUE THREAD

**Issue by hwittenborn** [flathub/flathub#3928]
I have a bot that I used to automate various tasks (@kavplex), and I'd like it to also be able to automate Flathub deployments for me to [flathub/com.hunterwittenborn.Celeste](/flathub/com.hunterwittenborn.Celeste).

Would it be possible to add that user to the list of users who can approve and merge PRs in the repository? I'd do it myself, but it doesn't appear that I have permissions to do so.

**Comment by hwittenborn** [comment]
@barthalion: Any chance you or someone else could get this done?

**Comment by barthalion** [comment]
I have sent an invite to @kavplex.

**Comment by hwittenborn** [comment]
@barthalion: I'm really sorry, but I got sidetracked with some stuff and didn't get a chance to get the invitation accepted, and it looks like it got expired and is no longer letting me accept it. Would you be able to resend the invitation?
