### ISSUE TITLE
Missing org.freedesktop.Platform.GL32.nvidia-396-24

### ISSUE THREAD

**Issue by kbjoon79** [flathub/flathub#393]
**OS** : Fedora rawhide
**Flatpak** : 0.11.7

**Problem** :
nvidia-396-24 32bit runtime does not exist.
Missing **org.freedesktop.Platform.GL32.nvidia-396-24**

```
# flatpak remotes
Name    Options
flathub system 
```

```
# flatpak remote-ls | grep -i nvidia | grep 396-24
org.freedesktop.Platform.GL.nvidia-396-24	flathub
```
If It ever read the wrong repo data, I deleted the repo cache file.
```
# sudo rm -rf /var/lib/flatpak/repo/tmp/cache/summaries/
# flatpak remote-ls | grep -i nvidia | grep 396-24
org.freedesktop.Platform.GL.nvidia-396-24	flathub
```

It seems to be independent of the OS distribution or flatpak version.

**Comment by TingPing** [comment]
This issue is being tracked here: https://github.com/flatpak/freedesktop-sdk-images/issues/100
