### ISSUE TITLE
Can't install Teams for Linux

### ISSUE THREAD

**Issue by mbridon** [flathub/flathub#3946]
Hi,

I just tried to Install Microsoft teams for Linux from Flathub : https://flathub.org/apps/details/com.github.IsmaelMartinez.teams_for_linux

It doesn't install as the `.deb` returns a 404.

Probably something wrong with the extra data ?

**Comment by hfiguiere** [comment]
you should file the issue with the package directly

https://github.com/flathub/com.github.IsmaelMartinez.teams_for_linux/issues

**Comment by mbridon** [comment]
Thanks @hfiguiere, is there an easy way to somehow "move" the issue ? I'm not super fluent in github ^_^

**Comment by hfiguiere** [comment]
just refile it there
