### ISSUE TITLE
Upload Godot 3 Flatpak to be maintained in tandem with Godot 4 Flatpak

### ISSUE THREAD

**Issue by Zishan-Rahman** [flathub/flathub#3960]
Now that Godot 4 is finally at a stable release [that has recently been pushed to Flathub](https://github.com/flathub/org.godotengine.Godot/commit/3c038ba71725efed2d62186e0ae6c1aa75e7acf2), me and some others were discussing whether or not it would be feasible to maintain a Godot 3 Flatpak in conjunction with the Godot 4 one while the former version of Godot is still receiving updates. We eventually agreed on doing so.

[The discussion is linked here for reference](https://github.com/flathub/org.godotengine.Godot/issues/115), and @Calinou, one of the maintainers of the current Godot Flatpak, [gave me his approval to create a new issue here](https://github.com/flathub/org.godotengine.Godot/issues/115#issuecomment-1455149629) on maintaining a Godot 3 Flaptak repository under the Flathub organisation on GitHub, separate to the current one being used for Godot 4. We _could_ potentially be able to use a prior revision of the current Flatpak (before the update to 4.0) for this.

**Comment by Zishan-Rahman** [comment]
[This could also be considered:](https://github.com/flathub/org.godotengine.Godot/issues/115#issuecomment-1456578034)

> I think it would be better to have a `org.godotengine.Godot-LTS` or something, so when Godot 5 eventually comes around you can just upgrade `org.godotengine.Godot` to Godot 5 and `org.godotengine.Godot-LTS` to Godot 4.

(original comment by @reisaraujo-miguel)

**Comment by hfiguiere** [comment]
I think ideally someone would submit it as Godot4. (as a new package of course)

**Comment by Calinou** [comment]
> I think ideally someone would submit it as Godot4. (as a new package of course)

For most users, we'll want to recommend the latest version as just `Godot`, so I'd prefer the current Flatpak to stay as Godot 4.

I'm OK with using `Godot-LTS` for Godot 3, but we don't know if we will need to keep the Godot 3 Flatpak installable once Godot 5 is out (not before a few years).

**Comment by hfiguiere** [comment]
See #3988

**Comment by Zishan-Rahman** [comment]
> See #3988

@hfiguiere [I created a PR on flatpak-builder-lint](https://github.com/flathub/flatpak-builder-lint/pull/125) for adding an exception to the Godot3 Flatpak. I'd like to get it merged before I push some commits over to my ongoing org.godotengine.Godot3 PR (which you linked to), then build it one last time with working editor support before we merge it onto Flathub. Please can you merge it at some point?

**Comment by barthalion** [comment]
Closing as there's a PR open already.
