### ISSUE TITLE
Archive com.github.virtual_puppet_project.vpuppr

### ISSUE THREAD

**Issue by orowith2os** [flathub/flathub#3974]
https://github.com/flathub/flathub/pull/3972
https://github.com/flathub/com.github.virtual_puppet_project.vpuppr/pull/5
https://github.com/flathub/com.github.virtual_puppet_project.vpuppr/pull/6

**Comment by JakobDev** [comment]
You should do the rebase first before archiving

**Comment by orowith2os** [comment]
I have the pull requests there, they just need to be merged because that were built before pro.vpup.vpuppr was on Flathub.

**Comment by orowith2os** [comment]
The rebase is done, it can be archived now.
