### ISSUE TITLE
Please add maintainer to one.ablaze.floorp

### ISSUE THREAD

**Issue by nexryai** [flathub/flathub#3984]
Hello.

Due to my physical condition it has become difficult for me to maintain `one.ablaze.floorp` intermittently. However, fortunately,  members of the developers of this browser has agreed to collaborate with me on the Flatpak packaging.
Could you add the following member as a maintainer of `one.ablaze.floorp` (https://github.com/flathub/one.ablaze.floorp) ? 
Thanks!

@typeling1578
@kaonasi-biwa
@surapunoyousei
@creeper-0910

**Comment by barthalion** [comment]
Done. I hope it's nothing serious and you will get soon!

**Comment by surapunoyousei** [comment]
> Done. I hope it's nothing serious and you will get soonThanks for your quick response!

**Comment by surapunoyousei** [comment]
@barthalion 

Sorry, We need more.

Could you add @dominichayesferen to one.ablaze.floorp?
