### ISSUE TITLE
GL32.nvidia-396-24 missing

### ISSUE THREAD

**Issue by twoDarkMessiah** [flathub/flathub#399]
The Runtime "org.freedesktop.Platform.GL32.nvidia-396-24" is currently missing in flathub repository. 
GL.nvidia-396-24 is provided, but some flatpak application like steam are dependent on 32Bit Libs.

**Comment by TingPing** [comment]
This is reported here: https://github.com/flatpak/freedesktop-sdk-images/issues/100
