### ISSUE TITLE
Connectivity issues from Iran

### ISSUE THREAD

**Issue by barfin** [flathub/flathub#3995]
```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
error: Can't load uri https://flathub.org/repo/flathub.flatpakrepo: While fetching https://flathub.org/repo/flathub.flatpakrepo: [6] Couldn't resolve host name

```
nothing can be downloaded even if you add successfully add the repo with a vpn.
even though anti-sanction tool shecan.ir(which does NOT bypass government censorship) shows that the website is [sanctioned](https://shecan.ir/?url=https%3A%2F%2Fdl.flathub.org%2Frepo%2F#report) and can actually unblock it, I'm not sure if it's sanctioned, because government blocked google play store too and it can still be accessed using shecan.ir duo to a bug in their systems, it's possible that flathub is using a CDN or something that's blocked by iranian government

**Comment by barfin** [comment]
I just noticed orbot(the tor client for android) uses fastly as an option for bypassing censorship and flathub also uses fastly(according to whois websites) so they MIGHT've blocked that to make tor stop working and that also affected the flathub

**Comment by barthalion** [comment]
Yes, Fastly is blocked by multiple authoritarian countries. You may try to substitute flathub.org with front-hex2.flathub.org or front-ams.flathub.org to bypass CDN but YMMV.

**Comment by barfin** [comment]
> 

that actually worked, thanks
