### ISSUE TITLE
My app won;t publish

### ISSUE THREAD

**Issue by vixalien** [flathub/flathub#3999]
https://buildbot.flathub.org/#/builders/2/builds/11733

**Comment by vixalien** [comment]
It just times out

**Comment by hfiguiere** [comment]
which app?

**Comment by vixalien** [comment]
Sticky Notes <https://beta.flathub.org/apps/com.vixalien.sticky>

source <https://github.com/vixalien/sticky>

I think it might be because I updated GNOME runtime to 44

**Comment by vixalien** [comment]
here's the flathub repo as well https://github.com/flathub/com.vixalien.sticky

**Comment by barthalion** [comment]
Could have been related to the outage from Friday? I started a new build at https://buildbot.flathub.org/#/builders/6/builds/30656 but the problem has been resolved since.

**Comment by vixalien** [comment]
it happened when I used the GNOME Runtime version 44, I reverted to 43 and it worked again so....

I'll test this again later
