### ISSUE TITLE
Request to be a maintianer of com.synology.SynologyDrive

### ISSUE THREAD

**Issue by lil5** [flathub/flathub#4007]
Support for com.synology.SynologyDrive is not very active

Link: https://github.com/flathub/com.synology.SynologyDrive

[[Here]](https://github.com/flathub/com.synology.SynologyDrive/pull/31#issuecomment-1482630148); [RayJW](https://github.com/RayJW) and I express wishes to become maintainers for the project to keep it alive.

I heard that this is the place to ask for that.

**Comment by barthalion** [comment]
I've sent you invitations. Thanks for picking it up.
