### ISSUE TITLE
Use Appstream links for "Install" buttons

### ISSUE THREAD

**Issue by Rathmox** [flathub/flathub#4008]
The current "Install" button downloads a .flatpakref file, which isn't bad, but as opening it will open the app store, replacing them with appstream links that also opens the app store wouldn't change anything.

There is a browser extension named [Flatline](https://github.com/CleoMenezesJr/flatline) that does this, but is it possible to do it on the website itself ?

**Comment by JakobDev** [comment]
A appstream link would just say, that you want to install a App with this ID. So the App could be installed from the Repos of your Distro Instead of Folathub. See flathub/website#919 for further discussion.

**Comment by Rathmox** [comment]
Oh, ok, I see.
And if flathub isn't setup in the distro the app won't show up, and the .flatpakref adds automatically flathub

**Comment by CleoMenezesJr** [comment]
Hey, I created a Firefox/Chromium extension that do it. :)

**Comment by Rathmox** [comment]
@CleoMenezesJr I mentionned it

**Comment by CleoMenezesJr** [comment]
> @CleoMenezesJr I mentionned it

sorry for my lack of attention
