### ISSUE TITLE
Incorrect release description in appstream data

### ISSUE THREAD

**Issue by mcrha** [flathub/flathub#4017]
Some apps, like `org.gnome.Boxes`, contain in the appstream data downloaded from the flathub.org remote this version information:

```xml
    <releases>
      <release timestamp="1679011200" version="44.0">
        <description><p>(null)</p></description>
      </release>
    </releases>
```

The `(null)` should not be there. A side effect is that it is shown to the users (in the gnome-software).

There are more such apps.

**Comment by razzeee** [comment]
I faintly remember this being something that appstream-glib causes? So this might be gone, when libappstream lands and the file gets rebuild.

**Comment by bbhtt** [comment]
This was https://github.com/hughsie/appstream-glib/issues/350, should be fixed now with libappstream. If you see anything, please open a separate issue.
