### ISSUE TITLE
Retroactive Funding based on past usage 

### ISSUE THREAD

**Issue by mulles** [flathub/flathub#4045]
Our systems know best what software we used and how much, let's leverage that, for it/flatpak to generate us an offer to distribute variable or fixed budget to them retroactively. 

In regard to https://discourse.flathub.org/t/flathub-in-2023/3808. This is a way to determine how much I should set as  recurring funding in regard to future or one off payment for past usage. 

I hope this is not only a personal problem, but that many people struggle to know what software they use and thus should support. Liberapay.com offers kind of that,  I probably should write a script automatically match the software projects used on my systems, but Flathub is in a much better position.

**Comment by razzeee** [comment]
I don't think flathub is the correct place for this. Flatpak might be, ultimately it might be even better on a higher up level. Or you might be able to write an app, that acts like a system monitor, but just tracks usage time.

**Comment by bbhtt** [comment]
This isn't very actionable, tracking usage times should be done by the system.
