### ISSUE TITLE
Setzer Excess Download Issue

### ISSUE THREAD

**Issue by JohannPopper** [flathub/flathub#4063]
When I install Setzer from Flathub on a number of diverse systems, the download takes significantly longer than other large flatpaks, and, moreover, the download process hangs for a long time near the end, and eventually shows in Terminal that it's downloading significantly more data in excess of what is predicted by flatpak. For example, it might show something like this when the download finally completes: 

 1. [✓] org.cvfosammmm.Setzer                                  stable                   i              flathub               7.6 GB / 5.2 GB

I informed the developers, and they asked me to forward this issue to you at Flathub to figure out what might be the cause. To be clear, the app does eventually succeed in installing. There does seem to be something unexpected going on, and I wouldn't know where to begin investigating, so I wanted you to know. 

Thank you so much for your time and all that you do for the community.

**Comment by hfiguiere** [comment]
With this PR https://github.com/flathub/org.cvfosammmm.Setzer/pull/21 the problem should have been addressed.

In short it will now install the Sdk as an extension.

**Comment by razzeee** [comment]
here is the current breakdown, I think we can close this

![image](https://github.com/flathub/flathub/assets/5943908/bf94f45a-76f5-4732-93aa-0cbc21c7d558)
