### ISSUE TITLE
Flathub not picking up updates

### ISSUE THREAD

**Issue by alexwarddev1230** [flathub/flathub#4064]
Repo: https://github.com/flathub/net.studio08.xbplay

I merged an update to v 1.2.2  here: https://github.com/flathub/net.studio08.xbplay/pull/5/files however, flathub is still showing the previous version: https://flathub.org/apps/details/net.studio08.xbplay (shows v1.2.0) after 15 hours.

I  merged another PR (just update the readme) to see if it would trigger a version update, but no luck.

Can someone help me understand why flathub isn't picking up version updates? Thanks

**Comment by alexwarddev1230** [comment]
@barthalion any idea why flathub website isnt picking up flatpak updates? Seems to be more widespread than just my flatpak.

**Comment by award1230** [comment]
Update: Looks like it picked up the change now. I didn't change anything so perhaps the website was just very delayed?

**Comment by alexwarddev1230** [comment]
Update: Looks like it picked up the change now. I didn't change anything so perhaps the website was just very delayed? I would close this issue if I knew how -_-
