### ISSUE TITLE
Change the default branches for KiCad's ODBCDriver extensions to stable

### ISSUE THREAD

**Issue by jmaibaum** [flathub/flathub#4071]
KiCad's ODBCDriver extensions (added Dec '22/Jan '23) were created with default branch set to `beta`, but since then, stable versions have also been made available.

Can the following repos thus please have their default branch switched to `stable` in order to let flatpak-external-data-checker create PRs for the correct branch?

- https://github.com/flathub/org.kicad.KiCad.ODBCDriver.sqliteodbc
- https://github.com/flathub/org.kicad.KiCad.ODBCDriver.psqlodbc
- https://github.com/flathub/org.kicad.KiCad.ODBCDriver.mariadb-connector-odbc

Thanks

**Comment by barthalion** [comment]
Done, thanks.
