### ISSUE TITLE
add other members to io.podman_desktop.PodmanDesktop

### ISSUE THREAD

**Issue by benoitf** [flathub/flathub#4074]
Hello, I'm a maintainer of both upstream and flatpak repository https://github.com/flathub/io.podman_desktop.PodmanDesktop

But I would like to add other maintainers (committers rights) in the flatpak repository

Could you please other committers of the upstream repository https://github.com/containers/podman-desktop/
https://github.com/cdrage / @cdrage
https://github.com/jeffmaury @jeffmaury
https://github.com/lstocchi @lstocchi

Thanks.

**Comment by barthalion** [comment]
I have sent out invitations. Please make sure to accept it in the coming days as they will otherwise expire.
