### ISSUE TITLE
Non-reproducible build failure of libwmf 0.2.13

### ISSUE THREAD

**Issue by Tamaranch** [flathub/flathub#4078]
I'm building it as a dependency of [Ristretto](https://github.com/flathub/org.xfce.ristretto) and I've had the problem several times already. Here is the last one: https://github.com/flathub/org.xfce.ristretto/pull/80
The [first build](https://buildbot.flathub.org/#/builders/6/builds/35772) fails on this:
```
WARNING: 'automake-1.16' is probably too old.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make: *** [Makefile:428: Makefile.in] Error 1
```
the [second one](https://buildbot.flathub.org/#/builders/6/builds/35776) passes without changing anything.

**Comment by hfiguiere** [comment]
I have these patches with AbiWord:

https://github.com/flathub/com.abisource.AbiWord/blob/master/com.abisource.AbiWord.json#L93

I haven't had issues.

**Comment by hfiguiere** [comment]
actually I see you use a newer release that has the patch upstream.

**Comment by hfiguiere** [comment]
I can build it successfully here. Is this still a problem?

**Comment by Tamaranch** [comment]
It happened to me again on the last PR: https://github.com/flathub/org.xfce.ristretto/pull/88

**Comment by Tamaranch** [comment]
Thanks, seems to work fine: https://github.com/flathub/org.xfce.ristretto/pull/89
Let's close this, I'll reopen if needed.
