### ISSUE TITLE
elementary Icon theme

### ISSUE THREAD

**Issue by cassidyjames** [flathub/flathub#409]
Would it be possible to get the [elementary Icon theme](https://github.com/elementary/icons) packaged up similar to how the Adwaita and Paper icons are available?

**Comment by bilelmoussaoui** [comment]
The icons are now loaded from the host. So no need to package them.

**Comment by TingPing** [comment]
Indeed, and if an application is not functional without them it should just bundle them.

**Comment by bilelmoussaoui** [comment]
@TingPing the two other repositories should be removed to avoid confusions I guess

**Comment by cassidyjames** [comment]
@bilelmoussaoui ah, got it. Thanks. :smile:

**Comment by TingPing** [comment]
@bilelmoussaoui Yes they should, just low priority since they are harmless.
