### ISSUE TITLE
Details of org.gnu.emacs on the Flathub web site are not up to date

### ISSUE THREAD

**Issue by muep** [flathub/flathub#410]
The [Flathub web catalog](https://flathub.org/apps/details/org.gnu.emacs) still shows metadata of the previous Emacs release despite 26.1 being in the repositories. My guess would be that something in the web site is not happy with the Appdata xml file that is provided in the flatpak. I do not know how to verify if this is the case, but I am hoping that I could get some advice on how to troubleshoot this, from someone more familiar with how the site works.

Here is the [org.gnu.emacs.appdata.xml](https://github.com/flathub/flathub/files/2057448/org.gnu.emacs.appdata.txt) of the flatpak in case someone wants to take a look without installing Emacs. It passes the `appstream-util validate-relax org.gnu.emacs.appdata.xml` check and checking with `validate` produces only something that to me look like style errors rather than something that should cause the entire metadata to get discarded.

**Comment by TingPing** [comment]
` <launchable type="desktop-id">emacs</launchable>`

That line is bogus, should be `org.gnu.emacs.desktop`

**Comment by TingPing** [comment]
> If I am understanding the documentation right, this launchable element should at least read emacs.desktop instead of emacs

Correct.

> Would it be it useful to have upstream adopt a change like that,

Well it is invalid atm, so at the very least yes.

> is it also required to have them change the filename of the desktop file to org.gnu.emacs.desktop ?

Not required but it makes our lives easier as well as following the new recommendations from the desktop-file-spec.

**Comment by muep** [comment]
Now with the fixed launchable element, the metadata is updated.
