### ISSUE TITLE
Font scalling ignored by flathub packages

### ISSUE THREAD

**Issue by neggative9** [flathub/flathub#4100]
when scaling fonts on Gnome via Gnome tweaks. the apps that have been installed with [registry.fedoraproject.org](https://registry.fedoraproject.org/)  repo follows the system font scaling. but apps downloaded with [dl.flathub.org](https://dl.flathub.org/) repo don't respect the font scale.

info:-
- sys: fedora 38. Gnome44
- not a tech person

thanks for your reply

**Comment by bbhtt** [comment]
Which specific apps are these?

**Comment by bbhtt** [comment]
Closing as this is not actionable given the info. Please reopen if you see this again with more information.
