### ISSUE TITLE
Add doZennn as a maintainer to the steam rom manager repo

### ISSUE THREAD

**Issue by Witherking25** [flathub/flathub#4107]
He is the actual author of steam rom manager and would like access plz

**Comment by hfiguiere** [comment]
which repository?

**Comment by Witherking25** [comment]
https://github.com/flathub/com.steamgriddb.steam-rom-manager

**Comment by Witherking25** [comment]
i am one of the emudeck devs, and put his app on flathub because we use it for the steam deck, and we are one of the primary use cases for it, and having it up on flathub is convienient

**Comment by barthalion** [comment]
I have just sent an invite to Jozen. Thanks!
