### ISSUE TITLE
Add maintainer to org.bitcoincore.bitcoin-qt

### ISSUE THREAD

**Issue by MarcoFalke** [flathub/flathub#4110]
Please add @achow101 as maintainer to https://github.com/flathub/org.bitcoincore.bitcoin-qt. Thanks

@achow101 is involved in the upstream project. See for example commit https://github.com/bitcoin/bitcoin/commit/079957d2ba5aaf5a832cb5a8be9a29362cf0a77f

**Comment by barthalion** [comment]
I have just sent an invite to Andrew. Thanks!
