### ISSUE TITLE
why you don't add deepin flatpak apps ?? 

### ISSUE THREAD

**Issue by elswerky** [flathub/flathub#413]
why deepin flatapk apps not available on flathub site ??? 

here is a link to add them to repo
https://www.facebook.com/notes/deepin-linux-indonesia/deepin-flatpak-repository/478351619169480/ 

i hope you add them soon

**Comment by nedrichards** [comment]
Flathub only adds applications that developers want to add. People are more than welcome to add their own repositories for apps and propose methods for people to add them, as Deepin appear to be doing. If they want to add their apps to flathub then they can submit them and we'll evaluate them on a case by case basis. But more people using flatpak is a great thing. I wish them well!

**Comment by elswerky** [comment]
i hope deepin_team add them soon
