### ISSUE TITLE
Add Ratfink and FineFindus as maintainers for com.adrienplazas.Metronome

### ISSUE THREAD

**Issue by Ratfink** [flathub/flathub#4147]
@FineFindus and I are the new maintainers of `com.adrienplazas.Metronome`, but we don't have access to the Flathub manifest repository at https://github.com/flathub/com.adrienplazas.Metronome.  Please see [the project's DOAP file](https://gitlab.gnome.org/World/metronome/-/blob/master/metronome.doap) for confirmation that we're maintainers.

If we could get access so that we can manage releases without having to pester Adrien, that would be great. 🙂

**Comment by bilelmoussaoui** [comment]
Done
