### ISSUE TITLE
GTKFileChooserNative portal support

### ISSUE THREAD

**Issue by ovari** [flathub/flathub#418]
Please enable portal support via `GTKFileChooserNative`.

This is useful for Mozilla Firefox and Mozilla Thunderbird
https://github.com/flathub/org.mozilla.Thunderbird/pull/14

If this is the incorrect upstream location, please advise where an issue should be written.

Thank you

**Comment by barthalion** [comment]
It's not matter of enabling anything in the portal. Application has to use GTKFileChooserNative to benefit from it. Report it to Mozilla.

**Comment by ovari** [comment]
Done https://bugzilla.mozilla.org/show_bug.cgi?id=1466327
