### ISSUE TITLE
Desktop Icon does not launch app following install.

### ISSUE THREAD

**Issue by dXQuarionXb** [flathub/flathub#4186]
Fresh install of [g4music](https://github.com/neithern/g4music) results in desktop icon not launching app. 

OS: Pop!_OS 22.04 LTS
Flatpak version: 1.12.07
Application Version: 1.13

App launches normally with command `flatpak run com.github.neithern.g4music`.
.desktop file located in `~/.local/share/flatpak/app/com.github.neithern.g4music/current/active/files/share/applications` is properly configured, as copying this file to `~/.local/share/applications/ ` and re-logging fixes this issue. If more details are necessary let me know.

**Comment by barthalion** [comment]
You should probably bring it up on some Pop!_OS support channel, as it's not a Flathub's issue.
