### ISSUE TITLE
Add maintainer to MMEX Money Manager to allow app to be verified

### ISSUE THREAD

**Issue by ovari** [flathub/flathub#4209]
Please authorize @vomikan to view the developer settings for [MMEX Money Manager](https://flathub.org/apps/org.moneymanagerex.MMEX) to be able to verify app. Cf. https://github.com/flathub/org.moneymanagerex.MMEX/issues/3#issuecomment-1573792856

Email address moneymanagerex@gmail.com
Cf. https://github.com/flathub/org.moneymanagerex.MMEX/issues/3#issuecomment-1573561878

Thank you @razzeee for your suggestion at https://github.com/flathub/org.moneymanagerex.MMEX/issues/3#issuecomment-1575396182

Thank you

**Comment by hfiguiere** [comment]
Not sure I can verify that request since you @ovari  are not listed as the maintainers of the package.

**Comment by ovari** [comment]
> Not sure I can verify that request since you @ovari are not listed as the maintainers of the package.

Can @n-stein, @tasukus, @whalley, @joshua-stone please help or ping someone who can? Thank you

**Comment by ovari** [comment]
Closing as the app is verified on [Flathub](https://flathub.org/en-GB/apps/org.moneymanagerex.MMEX). Thank you
