### ISSUE TITLE
Use `apppstreamcli validate` on the Buildbot

### ISSUE THREAD

**Issue by JakobDev** [flathub/flathub#4213]
flatpak-builder has switched to libappstream, but the Buildbot is still using `appstream-util` to validate the AppStream file. You should switch to `apppstreamcli validate`.

**Comment by bbhtt** [comment]
Solved by https://github.com/flathub-infra/flatpak-builder-lint/commit/bbfc701d87c53d6336febf6d4e1121dad424f367
