### ISSUE TITLE
Most flatpaks I use have no release notes, what to do?

### ISSUE THREAD

**Issue by lestephane** [flathub/flathub#4221]
Out of the list of updates applicable to my system

![image](https://github.com/flathub/flathub/assets/5460884/a91955da-78c1-463a-ba97-4c7c9344538c)

Only Telegram and Evolution show what is present in the new release (ANY kind of information for that matter).

![image](https://github.com/flathub/flathub/assets/5460884/5ba27f76-6749-4898-80b3-c904da585ddd)

![image](https://github.com/flathub/flathub/assets/5460884/6fd2db79-db02-442b-bc8e-01c8874a0c07)

All the others look like this 

![image](https://github.com/flathub/flathub/assets/5460884/0c36d4e1-f255-4ca5-98fe-20475b691c2f)

- How is it possible for publishers to publish new versions without explaining what has changed?
- Is it something that must be fixed on a per flathub project basis?
- If so, will I have to file an individual issue against each affected flatpak app in the flathub repo?
- If so, can I instead fix them myself using PRs?
- If so, is there a guide explaining how to do this (adding/generating release notes). Any example welcome.

For now, I have to cross-check the version number with the upstream project repo release notes, and have disabled automatic updates, besides dropping any overly permissive default. But even this does not scale up, because I have to drop overly permissive defaults for each linux user account I work with locally. I am not aware of a way to drop things for all users by default, only ways to grand permissions globally (using Flatseal for example).

**Comment by razzeee** [comment]
The release notes being there depends on the maintainer adding them to the `metainfo` file. Which in chromiums example would be https://github.com/flathub/org.chromium.Chromium/blob/master/org.chromium.Chromium.metainfo.xml#L29

**Comment by bilelmoussaoui** [comment]
right, nothing actionable from flathub's side. The app developers needs to provide this information
