### ISSUE TITLE
Microsoft and Microsoft Corporation are labeled as separate companies?

### ISSUE THREAD

**Issue by eqgqwgrq** [flathub/flathub#4223]
https://flathub.org/en-GB/apps/com.microsoft.Edge — "Microsoft Corporation"

https://flathub.org/en-GB/apps/com.skype.Client — "Microsoft"

**Comment by razzeee** [comment]
You should probably bring that up in the repos of those apps

**Comment by boeithwoibjeqiogroeq** [comment]
I chose "Microsoft Corporation" because most apps listed it as "Microsoft Corporation".
