### ISSUE TITLE
Captions don't show if locale is hu (Hungarian)

### ISSUE THREAD

**Issue by ovari** [flathub/flathub#4224]
Caption `Dashboard` shows correctly for English: https://flathub.org/en/apps/org.moneymanagerex.MMEX
https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/org.moneymanagerex.MMEX.metainfo.xml#L282
![English](https://github.com/flathub/flathub/assets/17465872/4b291600-bd4a-4536-8b4a-15643870c15f)

Caption `Irányítópult` does not show for Hungarian: https://flathub.org/hu/apps/org.moneymanagerex.MMEX
https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/org.moneymanagerex.MMEX.metainfo.xml#L283
![Hungarian](https://github.com/flathub/flathub/assets/17465872/eac0d3ee-2169-48fa-ad21-62b1276eb7a2)

Thank you

**Comment by razzeee** [comment]
We don't use translations from metadata, that's by design right now.
