### ISSUE TITLE
Kill old docs at wiki url

### ISSUE THREAD

**Issue by razzeee** [flathub/flathub#4238]
Archive and kill https://github.com/flathub/flathub/wiki/App-Submission

**Comment by hfiguiere** [comment]
#4219 should be merged first.

**Comment by hfiguiere** [comment]
but I think a redirect is better. even a manual one.

dead links are bad.

**Comment by hfiguiere** [comment]
This is done now. if I forgot something , let me know

(I didn't delete the pages I just replaced the content with a link to the new location)
