### ISSUE TITLE
Move net.pcsx2.PCSX2 to upstream repository

### ISSUE THREAD

**Issue by stenzek** [flathub/flathub#4248]
I am a developer of the PCSX2 emulator, currently distributed by Flathub as `net.pcsx2.PCSX2` (https://github.com/flathub/net.pcsx2.PCSX2).

This package was created without any coordination with us, nor have the authors made any attempts to reach out. It is a constant support headache for us, as is built in a way which causes various issues, including being weeks/months out of date at times, missing resources and debugging facilities, doesn't match our library versions, and has measurably lower performance.

In order to resolve this, we have started distributing our own Flatpak builds via our releases, both on pcsx2.net, as well as via GitHub.. This was introduced in https://github.com/PCSX2/pcsx2/pull/8942, you can find the manifest at https://github.com/PCSX2/pcsx2/blob/master/.github/workflows/scripts/linux/flatpak/net.pcsx2.PCSX2.json, and the GitHub Actions workflow at https://github.com/PCSX2/pcsx2/blob/master/.github/workflows/linux_build_flatpak.yml.

Mainly due to our development process often requiring users to test pull request builds, having matching configurations between our AppImage and the Flatpak, automatic release generation based on pushes for the nightly branch, and the build process pulling in resources from multiple repositories in our organization which are not directly linked, we cannot use Flathub's infrastructure.

Instead, we request direct push access to the Flathub repository (not the Flathub Git repository), as we have seen done with Firefox, OBS, and other packages. Doing so will allow us to publish releases directly from our CI pipeline, including automatic updates for users, to ensure parity regardless of which platform they are using.

Thank you in advance.

Also tagging @refractionpcsx2.

**Comment by barthalion** [comment]
Also you should use the `stable` branch for Flathub uploads. You can set it using `default-branch` and then overwrite for other builds, or the other way around.

**Comment by stenzek** [comment]
> Your metainfo file doesn't seem to define any screenshots. This wouldn't pass the validation on our CI.
> Once the screenshots are there, you need to pass --mirror-screenshots-url to flatpak-builder with https://dl.flathub.org/repo/screenshots as the value. 

That's fine, I can add those.

> It doesn't make sense to disable no-debuginfo, flatpak-builder will automatically move debugging symbols to the optional Debug extension.

This is intentional. We use `libbacktrace` to generate backtraces on crashes (critical for users bug reports and support), which as far as I'm aware, cannot pull symbols from separated binaries.

**Comment by stenzek** [comment]
Screenshots/branch/mirror should be sorted. I just `ostree commit`'ed them into the `screenshots/x86_64` branch, based on what I could see other projects doing, and `ostree ls`'ed to confirm that they were added - I'm assuming being in the root directory of the branch is correct? (still wrapping my head around the whole OSTree thing)

ID has been verified.

**Comment by barthalion** [comment]
@stenzek Looks good. Do you have a GPG key I could encrypt the beta token with?

**Comment by stenzek** [comment]
Sure. Thanks for the quick reply, we appreciate it!

GPG key: https://gist.githubusercontent.com/stenzek/13a3c5ff3494e53987ae51b1185823f1/raw/2c84960fdf22bf15a72b39fcf6fd0d2fe291ca3e/gpg-pubkey.asc

**Comment by barthalion** [comment]
Sent an encrypted token via e-mail. Please let me know when a first build is uploaded to beta, I will give it a final review.

**Comment by stenzek** [comment]
Thanks! Build should be pushed from our main CI (https://github.com/PCSX2/pcsx2/commit/19cf29e5cfb1a95299f500e110a401949e6c476b).

**Comment by barthalion** [comment]
Looks good. I assume the goal is to submit pre-release builds to the regular Flathub? Would it be possible to push "pre-release" builds once a day instead of on every commit?

**Comment by barthalion** [comment]
You should probably explicitly add the ffmpeg extension to make sure it's installed automatically (example [here](https://github.com/flathub/io.github.kotatogram/blob/fef6ee9400169d163aa340fe96b6a493c3fe8fe0/io.github.kotatogram.yml#L30). `add-build-extension` makes it available during build only

**Comment by stenzek** [comment]
> Looks good. I assume the goal is to submit pre-release builds to the regular Flathub? Would it be possible to push "pre-release" builds once a day instead of on every commit?

For now, yes. However, we're getting close to a 2.0 release (probably within the next month or two), where we're going to split into two channels - monthly/quarterly, and head-of-tree. In which case I was thinking the beta branch would be more appropriate for the latter post-2.0. Currently the "stable" branch is years behind, and not really usable, hence why at the moment we're pushing users to master builds instead.

I guess we _could_ limit pushes to once a day, but it just means if there's a regression, flathub users won't get it until the next merge after that day (could be a couple of days delay). Do frequent releases create a problem for the infrastructure?

> You should probably explicitly add the ffmpeg extension to make sure it's installed automatically (example [here](https://github.com/flathub/io.github.kotatogram/blob/fef6ee9400169d163aa340fe96b6a493c3fe8fe0/io.github.kotatogram.yml#L30). add-build-extension makes it available during build only

Thanks for the tip, will do.

**Comment by barthalion** [comment]
> I guess we could limit pushes to once a day, but it just means if there's a regression, flathub users won't get it until the next merge after that day (could be a couple of days delay). Do frequent releases create a problem for the infrastructure?

It's not a problem *yet*, but we're generally thin on IO bandwidth, and publishing a new build is relatively intensive on resources. Maybe you could make the publishing job possible to trigger manually? This way it could be published once a day, but also give you a way to publish a new build if there was a regression.

**Comment by stenzek** [comment]
I think it should be doable as a scheduled actions workflow (with an optional manual trigger), just need to wrangle the syntax, and figure out some way of knowing whether a build needs to be pushed.

I suspect the easiest way might just be comparing the latest tagged commit in our repo what's on flathub. Fetching/parsing the appstream via the API seems like it might work, unless there's a more straightforward way? (<https://flathub.org/api/v2/appstream/net.pcsx2.PCSX2>).

**Comment by barthalion** [comment]
One more thing I forgot about. For "external builds", we expect a `flathub::manifest` metadata key in appdata/metainfo to point to where the app gets built from, like [OBS does](https://github.com/obsproject/obs-studio/blob/master/UI/xdg-data/com.obsproject.Studio.appdata.xml.in#L47). This is not required yet, but at some point will. I will give you a heads-up for anything else that may become a requirement.

> I suspect the easiest way might just be comparing the latest tagged commit in our repo to what's on flathub. Fetching/parsing the appstream via the API seems like it might work, unless there's a more straightforward way? (https://flathub.org/api/v2/appstream/net.pcsx2.PCSX2).

This might be the easiest way. You could also add a custom metadata tag with commit hash to the appdata file and it would show up at that endpoint, but I guess it doesn't change much.

> I guess that would also mean a separate build for our downloads page and what gets pushed, because we don't retain the OSTree repo after the actions workflow finishes. But since the code should be the same, I don't think that should be an issue.

Yeah, I don't think it's a big deal.

**Comment by razzeee** [comment]
See https://docs.flathub.org/docs/for-app-authors/appdata-guidelines#manifest-location for docs on the manifest link

**Comment by stenzek** [comment]
Thanks for the link.

I've thrown this together in https://github.com/PCSX2/pcsx2/pull/9118 (will merge once CI passes), but easier to see the diff anyway. master pushes will still build the flatpak, but won't push. Also switched the AppStream validator to the flathub version, if that makes any difference (it seemed to pass anyway).

For now the cron schedule is disabled, because currently flathub is reporting a version a few hundred out of date, and I couldn't see a way to query the beta branch instead.

Was there anything else which needed to be done on our end?

**Comment by barthalion** [comment]
Nope, I think we're good here!

**Comment by stenzek** [comment]
Fantastic! I'll close this issue off then. Thanks a lot for the assistance, it's much appreciated.

I've pushed the current build to stable, and it seems to have gone through fine. So, on that note, is the flathub org Git repo going to conflict with our CI in any way, and/or is there anything we have to disable there?

**Comment by barthalion** [comment]
> Not sure why the screenshot links are dead, perhaps I didn't add them correctly to the OSTree? (they show up in a ls, though.

I will check it over the weekend.

**Comment by barthalion** [comment]
Fix for screenshots: https://github.com/PCSX2/pcsx2/pull/9135

> I've pushed the current build to stable, and it seems to have gone through fine. So, on that note, is the flathub org Git repo going to conflict with our CI in any way, and/or is there anything we have to disable there?

Yes, and I think a build from 5 hours ago could have overwritten the one from PCSX2 CI. I have archived https://github.com/flathub/net.pcsx2.PCSX2 so that won't happen again.

**Comment by stenzek** [comment]
Kicked our build manually, and the links in the AppStream XML seem to be valid (just hasn't updated the page yet, but that was delayed yesterday too). Thanks again for checking it out!
