### ISSUE TITLE
Pirated App on Flathub

### ISSUE THREAD

**Issue by chikachika1** [flathub/flathub#4259]
It's a Minecraft Launcher. Here is the link: https://flathub.org/apps/ch.tlaun.TL 

They changed the name from "TL Legacy" to "Legacy Launcher". In the info section, the "project website" redirects to this website: "https://llaun.ch". It's the same launcher, but with another name.

**Comment by barthalion** [comment]
Re-posting my response from Discourse:

> At the time of its submission, we’ve explicitly asked the developer to require logging in with Microsoft account. It doesn’t even seem to launch on my end right now.

So unless it actually allows to bypass the login screen, I don't think there's anything to do for us.

**Comment by razzeee** [comment]
Screenshot from their website

![image](https://github.com/flathub/flathub/assets/5943908/7544b085-4569-4493-9dc5-903ea9e2751c)

**Comment by barthalion** [comment]
cc @Prototik

I don't particularly care if users somehow figure out how to disable the requirement, but mentioning it outright on the website is somewhat too much. While we don't need to act upon requests from people who aren't copyright holders, this puts Flathub in bad light.

**Comment by Prototik** [comment]
@barthalion sorry for the inconveniences, I was unaware of these changes on the site. I asked team to remove all references of this info from the public space and agree any further changes of flatpak distribution with me.

**Comment by barthalion** [comment]
Thanks a lot!
