### ISSUE TITLE
EOL Ark Wallet

### ISSUE THREAD

**Issue by razzeee** [flathub/flathub#4260]
I'm not the maintainer or even a user, but it seems like https://github.com/flathub/io.ark.Desktop should be EOLed

Contributors listed are
@TingPing @nedrichards @fabiscafe

**Comment by hfiguiere** [comment]
It's probably too much work to get it to build for EOL. 5 years no change.

**Comment by razzeee** [comment]
https://github.com/flathub/io.ark.Desktop/pull/8

**Comment by razzeee** [comment]
App is EOLed and somebody also archived the repo. Closing.
