### ISSUE TITLE
App icon not updating

### ISSUE THREAD

**Issue by aleiepure** [flathub/flathub#4261]
I've updated the icon of my app (me.iepure.devtoolbox), but the one shown on the website and distros' store fronts is not changed yet. 
I've seen other similar resolved issues (#3023, #3464, #3581), can I get the same treatment?

I also suggest, if possible, adding a button in the new personal section of the website to fix this in the future without having to ask for help here.

**Comment by razzeee** [comment]
Icon has updated now.
