### ISSUE TITLE
wrong main repo commit is used to build app for Beta branch

### ISSUE THREAD

**Issue by bam80** [flathub/flathub#4268]
We have added our app to flathub-beta by merging updated manifest to "beta" branch:
https://github.com/flathub/app.organicmaps.desktop/pull/35/files

Here we can see we updated the runtime also:
```
- runtime-version: '5.15-22.08'
+ runtime-version: '6.5'
```

From `test` repo, all is good, we see right Runtime is used:
```
bam@Feedme:~$ flatpak remote-info desktop-origin  app.organicmaps.desktop 
        ID: app.organicmaps.desktop
       Ref: app/app.organicmaps.desktop/x86_64/test
      Arch: x86_64
    Branch: test
Collection: org.flathub.Stable.Build31320
  Download: 191,9 MB
 Installed: 477,7 MB
   Runtime: org.kde.Platform/x86_64/6.5
       Sdk: org.kde.Sdk/x86_64/6.5

    Commit: 59edc36dbee8c73c39453c2ba7c4a64bb0b6d984b8072e1442d2619784a67774
   Subject: Update app.organicmaps.desktop.yml (038c499b)
      Date: 2023-06-20 14:02:50 +0000
```

But for beta it seem just uses wrong Runtime and commit in Subject from last build on Stable channel.  
```
bam@Feedme:~$ flatpak remote-info flathub-beta   app.organicmaps.desktop 
        ID: app.organicmaps.desktop
       Ref: app/app.organicmaps.desktop/x86_64/beta
      Arch: x86_64
    Branch: beta
Collection: org.flathub.Beta
  Download: 191,8 MB
 Installed: 477,7 MB
   Runtime: org.kde.Platform/x86_64/5.15-22.08
       Sdk: org.kde.Sdk/x86_64/5.15-22.08

    Commit: 534d6327411063a8fcd4c109e99c99049fbd519a87ff6674ea41ecfb91fee716
   Subject: Update version to 2023.06 (9d0bf789)
      Date: 2023-06-20 20:35:56 +0000
```

Please help, I have no clue what's going wrong..

**Comment by hfiguiere** [comment]
it didn't build

**Comment by hfiguiere** [comment]
because
```
Failed to download sources: module organicmaps: Git commit for branch master is 1e2ed074ec22474a9fa1edecb48fb0c3987041f6, but expected be5a0aa2991377eedd61f19ec3853332b51b114b
```

**Comment by hfiguiere** [comment]
note: I wanted that the presence of `branch` in a git source be a fatal error but I was overruled. so the linter didn't stop you when it should have.

**Comment by bam80** [comment]
Thank you very much, it made me nuts..

**Comment by bam80** [comment]
> Failed to download sources: module organicmaps: Git commit for branch master is 1e2ed074ec22474a9fa1edecb48fb0c3987041f6, but expected be5a0aa2991377eedd61f19ec3853332b51b114b

So I tried to fix it with
https://github.com/flathub/app.organicmaps.desktop/pull/37
but was said there are some branch protecting rules preventing me from doing this?
