### ISSUE TITLE
Please, remove com.mongodb.Compass

### ISSUE THREAD

**Issue by mijorus** [flathub/flathub#4273]
Hi, 
I am the maintainer of this wrapper https://github.com/flathub/com.mongodb.Compass

Unfortunately, because this is an unofficial wrapper it often breaks upon updates, and I don't want to support this wrapper anymore.

In any case, I have reverted to the last working version of the app.

**Comment by razzeee** [comment]
You could start this with setting it end of life https://docs.flathub.org/docs/for-app-authors/maintanance#end-of-life

**Comment by mijorus** [comment]
Thanks, I'm sending the email soon
