### ISSUE TITLE
Create JWT for publishing of org.freedesktop.GL.mesa-git into Flathub beta

### ISSUE THREAD

**Issue by nanonyme** [flathub/flathub#4279]
Needed refs org.freedesktop.Platform.GL.Debug.mesa-git and org.freedesktop.Platform.GL.mesa-git

Public GPG at https://gist.github.com/nanonyme/08f1e07b96ea0f2003bd17f9cfa83785#file-nanonyme-flathub-gpg

**Comment by barthalion** [comment]
I have updated the token in mesa-git's CI/CD settings.
