### ISSUE TITLE
Unable to Install or Update Flatpaks Due to an Error

### ISSUE THREAD

**Issue by ProfessorCode212** [flathub/flathub#4280]
Flatpak: 1.15.4

Flatpak was working fine for me but, on trying to run an update today, I kept getting the following error. I tried it for multiple flatpaks but I got the same error. I tried installing a flatpak from a different remote, but that worked.

```
Error: While pulling app/io.github.alainm23.planify/x86_64/stable from remote flathub: Writing content object: Need more input

Error: While pulling app/org.gnome.eog/x86_64/stable from remote flathub: Writing content object: Need more input

Error: While pulling app/org.flatpak.qtdemo/x86_64/stable from remote flathub: Input buffer too small
```

It seems to fail even after reaching 100%.

**Comment by hfiguiere** [comment]
Do you use Feora? It's a know breakage of Fedora.

**Comment by ProfessorCode212** [comment]
@hfiguiere Yes. I am on Fedora 38. It was working fine until today, though. Is there something I can do about it?

**Comment by hfiguiere** [comment]
https://discussion.fedoraproject.org/t/flatpak-updating-bug-due-to-libostree-update-with-solution/84696
