### ISSUE TITLE
Add new maintainer to tw.ddnet.ddnet

### ISSUE THREAD

**Issue by ElXreno** [flathub/flathub#4286]
@srdante will maintain [tw.ddnet.ddnet](https://github.com/flathub/tw.ddnet.ddnet) from now, please invite him as collaborator to the repository.
See https://github.com/flathub/tw.ddnet.ddnet/issues/39

Thanks!

**Comment by barthalion** [comment]
Done, thanks!

**Comment by miguilimzero** [comment]
@barthalion Hello! I got removed from the repository because of the 2FA requirement. I just enabled it on my account here. Is is possible to add me back? Thank you

**Comment by bbhtt** [comment]
Please open new issues. 

I sent you an invite, make sure to accept it within the week.
