### ISSUE TITLE
Please archive com.obsproject.Studio.Plugin.NVFBC

### ISSUE THREAD

**Issue by guihkx** [flathub/flathub#4287]
Repo: https://github.com/flathub/com.obsproject.Studio.Plugin.NVFBC

This was a popular plugin for OBS Studio, but stopped working after version 28.0.0 was released in 2022-09-01.

Upstream has effectively [abandoned the project as well](https://gitlab.com/fzwoch/obs-nvfbc/-/issues/10#note_1087689048).

Until recently, we could still easily downgrade OBS Studio back to version 27, but that's not possible anymore because the commit is gone from Flathub, rendering the plugin useless.

Thanks!

**Comment by JakobDev** [comment]
You should mark it as eol first

**Comment by guihkx** [comment]
@JakobDe Done. Thanks for the reminder!

**Comment by hfiguiere** [comment]
done
