### ISSUE TITLE
Build failed: couldn't find remote ref

### ISSUE THREAD

**Issue by mijorus** [flathub/flathub#4308]
https://buildbot.flathub.org/#/builders/6/builds/51166

My Build is failing but I don't understand why.
The commit exists on the source repo: 5371ef20df439d180c020876fd5626e9b88e6aeb

**Comment by mijorus** [comment]
Also, the command 

```
git fetch -f -t https://github.com/flathub/it.mijorus.smile refs/pull/32/head --progress
```

runs just fine on my laptop

**Comment by barthalion** [comment]
Seems to have been some hiccup on GitHub's end: https://buildbot.flathub.org/#/builders/6/builds/51190
