### ISSUE TITLE
SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by DrtacoBella** [flathub/flathub#4321]
seems cause of problem is flathub using some kinda proxies.. 

16376 recvfrom(22, "=**_|\201\200\0\1\0\5\0\0\0\0\2dl\7flathub\3org\0\0\34\0\1\300\f\0\5\0\1\0\0\10\236\0#\tdualstack\1n\3sni\6global\6fastly\3net\0\300,\0\34\0\1\0\0_**
\10\236\0\20*\4NB\6\0\0\0\0\0\0\0\0\0\3G\300,\0\34\0\1\0\0\10\236\0\20*\4NB\4\0\0\0\0\0\0\0\0\0\3G\300,\0\34\0\1\0\0\10\236\0\20*\4NB\2\0\0\0\0\0\0\0\0\0\3G\300,\0
\34\0\1\0\0\10\236\0\20*\4NB\0\0\0\0\0\0\0\0\0\0\3G", 65536, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.1.2")}, [28 => 16]) = 191
16376 close(22)                  
   
....

the owner of specific proxies is - 
16376 connect(22, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("151.101.129.91")}, 16) = 0

.. a fastly - https://ipinfo.io/151.101.129.91#block-summary

the error I am seeing on screen:
root@dino:/home/tesla#  flatpak --verbose remote-ls
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /root/.local/share/flatpak
F: Fetching summary index file for remote ‘flathub’
F: Loading https://dl.flathub.org/repo/summary.idx using curl
F: Failed to download optional summary index: While fetching https://dl.flathub.org/repo/summary.idx: [60] SSL peer certificate or SSH remote key was not OK
error: Unable to load summary from remote flathub: While fetching https://dl.flathub.org/repo/summary.idx: [60] SSL peer certificate or SSH remote key was not OK

how to sort this out?

**Comment by DrtacoBella** [comment]
I am on latest Debian 12 .. 
Flatpak 1.14.4

**Comment by bbhtt** [comment]
@DrtacoBella Can you reach https://dl.flathub.org/ from your website? Is your country/ISP blocking Fastly?

**Comment by DrtacoBella** [comment]
Help, close this issue. It is resolved now.

Thank You,
-----------------------------------------------------------------------------------
to avoid peeking and profiling, use this (not for all mails) -

https://keys.openpgp.org/vks/v1/by-fingerprint/E2240AE4E6F5F09FCC9F01D7E6EE15AF065FD9ED

Sent with [Proton Mail](https://proton.me/) secure email.
