### ISSUE TITLE
Migrating to stricter sandboxing permissions - data would need to move

### ISSUE THREAD

**Issue by cobratbq** [flathub/flathub#4323]
I looked into adopting a stricter permission model for the Claws-Mail package, a while ago. Then a few weeks ago, I got reminded on this again because of a [request](<https://github.com/flathub/org.claws_mail.Claws-Mail/issues/33>).

The Claws-mail flatpak-package started out with `--filesystem=home`, because claws-mail assumes it can create any arbitrary directory for storing email messages in any subdirectory that is entered. I would like to move to a model where claws-mail interacts with a sandboxed/isolated home-directory and it is persisted with the application. I am not sure whether `--persist=` is the solution here, because it might be too easy to accidentally "clean up" your email data.

So I have a few questions:

- Are there any practices on migrating data? (e.g. on upgrade)
- Are there practices on a "new major release" such that there is a manual action involved in upgrading, to avoid data-loss (i.e. deletion) or losing access (i.e. sandboxing model now excludes data)?
- Are there any practices on the right set of permissions flags to use to avoid losing important data on mismanagement of the flatpak app?
- Are there any ways to use `--filesystem=` to "redirect" the flatpak's `$HOME` a subdirectory?

**Comment by JakobDev** [comment]
> Are there any practices on migrating data? (e.g. on upgrade)

You can check if the old data directory exists on startup. if yes, move it to the new location.

> Are there any ways to use --filesystem= to "redirect" the flatpak's $HOME a subdirectory?

You can use `--persist=dir` for a directory. e.g. -`-presist=my-dir `would redirect `~/my-dir` t `~/.var/<id>/my-dir`. But there is no Way to do this for the full home directory.

**Comment by cobratbq** [comment]
On July 11, 2023 2:22:20 PM UTC, JakobDev ***@***.***> wrote:
>> Are there any practices on migrating data? (e.g. on upgrade)
>
>You can check if the old data directory exists on startup. if yes, move it to the new location.

That would only work if `--filesystem=home` is still available, so I guess a few-months-long migration path.

>
>> Are there any ways to use --filesystem= to "redirect" the flatpak's $HOME a subdirectory?
>
>You can use `--persist=dir` for a directory. e.g. -`-presist=my-dir `would redirect `~/my-dir` to `~/.var/<id>/my-dir`. But there is no Way to do this for the full home directory.

I know about `--persist`. What bugs me is that this may get cleared when removing the application (with extra flag). In case of email, this often means multiple years, many hundreds of megabytes. Regardless, you confirmed the options I thought I would have.

Migrating the full home dir is not necessary. That is clear to me.

**Comment by barthalion** [comment]
> What bugs me is that this may get cleared when removing the application (with extra flag).

It is what it is, essentially. Files at `/.var/app/ID` are that isolated home directory you're looking for; the flag has to be passed explicitly and a lot of people interact with Flatpak using various UI frontends which don't expose it.

**Comment by bbhtt** [comment]
Flatpak does not migrate data when updating filesystem permissions, it's only a list of permissions.

Rest seems to have been answered.

**Comment by cobratbq** [comment]
Would it be possible/allowed to create a second manifest that __is__ _properly_ sandboxed, off the same 'org.claws_mail.Claws-Mail' repository and modify the original manifest to show a name such as `[..] (unsandboxed)` or `[..] (unprotected)` to allow users time to migrate?

**Comment by bbhtt** [comment]
No

**Comment by cobratbq** [comment]
> No

Is this: "no, not possible" or "no, not allowed". I would combine the migration from Claws-Mail _3.x_ to Claws-Mail _4.x_ with the improved sandboxing parameters. (Migration to Claws-Mail 4.x is currently not yet possible due to bug https://github.com/flatpak/flatpak/issues/5846 in flatpak or its portals.)

**Comment by bbhtt** [comment]
Not possible, you can only build one manifest in the master branch

**Comment by hfiguiere** [comment]
> (Migration to Claws-Mail 4.x is currently not yet possible due to bug https://github.com/flatpak/flatpak/issues/5846 in flatpak or its portals.) 

This is not a flatpak bug. This is a Claws bug. if plugins are in preset directories then Claws should provide the UI to select them. Not a file chooser.

**Comment by cobratbq** [comment]
> > (Migration to Claws-Mail 4.x is currently not yet possible due to bug [flatpak/flatpak#5846](https://github.com/flatpak/flatpak/issues/5846) in flatpak or its portals.)
> 
> This is not a flatpak bug. This is a Claws bug. if plugins are in preset directories then Claws should provide the UI to select them. Not a file chooser.

To clarify (let me know if this is what you meant): the `/app` directory is no longer _accessible_/_available_ at all. Previously, Claws-Mail would immediately present the directory that contains the plugins, within `/app/...`. Now, `/app` is no longer available, therefore the file-picker disconnected from the needed plugins-directory.

Fact: loading plug-ins by selecting the appropriate files from a file-selection dialog has worked for all versions of Claws-Mail 3.x as flatpak, and for Claws-Mail 4.0-4.1.1 as flatpak. Then with version 4.2{,.1} it suddenly stopped working.

Is the above what you meant?
