### ISSUE TITLE
Remove me a BlueJeans maintainer

### ISSUE THREAD

**Issue by hadess** [flathub/flathub#4330]
Please remove me from the committers of https://github.com/flathub/com.bluejeans.BlueJeans

(CC @AsciiWolf, if you eventually want to retire the app)

**Comment by AsciiWolf** [comment]
I wonder (if I can ask), what is the reason for your decision?

**Comment by hadess** [comment]
I'm pretty sure my employer (Red Hat) has stopped using it internally, as my single sign-on account can't even start a personal meeting, but also that I'm being reassigned to do other, non-desktop work, and that even if Red Hat wanted to continue using BlueJeans, they won't give me work time to maintain work tools.

**Comment by AsciiWolf** [comment]
Well, you can maintain it outside of your work time, it's (hopefully) not that time consuming. Just occasionally merge some commit by flathubbot or do some minor manual fixes/changes. But it's your decision and I respect it.

I will keep the app on Flathub for now, although I also do not use it anymore and will try to find a new maintainer for it.

**Comment by hadess** [comment]
This maintenance used to be part of my job, but won't be anymore. I also I don't consider maintaining BlueJeans on Flathub to be a worthwhile hobby.

And finally, I've verified that my work didn't use BlueJeans anymore:
> On April 1, 2023, Red Hat IT will retire BlueJeans Meetings and you’ll need to use Google Meet as your small-scale video conferencing tool for one-on-ones and team meetings.

**Comment by barthalion** [comment]
This is now done.
