### ISSUE TITLE
Flathub api failing error 404

### ISSUE THREAD

**Issue by charlesthobe** [flathub/flathub#4354]
Using flathub api for pushing externally hosted app manifest and app data xml files has been failing for 5 days with error 404:
```
Api call to https://hub.flathub.org/api/v1/build/<?????>/extended failed with status 404, details: {'status': 404, 'error-type': 'no-error', 'message': 'No json error details from server'}
```
```
Error: Failed to publish the build: Error: The process '/home/runner/.local/bin/flat-manager-client' failed with exit code 1
```

[CI file](https://github.com/PCSX2/pcsx2/blob/master/.github/workflows/linux_build_flatpak.yml#L114)

[github actions using said CI file](https://github.com/PCSX2/pcsx2/actions/workflows/cron_publish_flatpak.yml)

**Comment by barthalion** [comment]
You (or the action you're using?) shouldn't use flat-manager-client from master. https://github.com/flatpak/flat-manager/commit/c4ce8feae33233c23137a24e551a6e64dea04a68 should help with the issue but no promise there aren't more down the road; if you can, pin it to `9401efbdc0d6bd489507d8401c567ba219d735d5` for now.

**Comment by charlesthobe** [comment]
The CI, not me, I don't have a token, therefore no access to the api, unlike the pcsx2 team.

> shouldn't use flat-manager-client from master
well nothing gets merged to master unless it's a vetted PR, also it used to work fine 5 days ago.

https://github.com/flatpak/flat-manager/commit/c4ce8feae33233c23137a24e551a6e64dea04a68
This would just fail it sooner if it was going to fail anyway, which is nice, but if there's a problem in the flathub web API, then it needs to be fixed so PCSX2 and/or other apps using flat-manager can resume pushing updates to the flathub store.

**Comment by barthalion** [comment]
As I explained, there's no problem with the API. The problem is that the royal you, as in the project, are using a version of the client that is not backwards compatible.

**Comment by charlesthobe** [comment]
Alright I will try with the PCSX2 team to fix it on their side and report back.

**Comment by stenzek** [comment]
I've pinned it to 9401efbdc0d6bd489507d8401c567ba219d735d5.

For what it's worth, I thought using master was a bit odd too, but I chose that because the Docker script in the actions repo also grabbed from master: https://github.com/flatpak/flatpak-github-actions/blob/master/Dockerfile#L11

**Comment by barthalion** [comment]
I have changed that Dockerfile but I don't really know if that's enough to fix it for everyone, Flathub will likely provide its own publshing action after third-party uploads support is officially released.

**Comment by charlesthobe** [comment]
ty for the help

**Comment by stenzek** [comment]
Thanks for pointing out the issue regardless, appreciated.
