### ISSUE TITLE
Can't delete "stable" branch

### ISSUE THREAD

**Issue by fsobolev** [flathub/flathub#4356]
[Documentation](https://docs.flathub.org/docs/for-app-authors/maintanance#the-repository) says about `master` and `beta` branches being protected, but doesn't say anything about `stable` branch. So I created one for my app and now it's protected and I can't delete it.

Please delete the branch. https://github.com/flathub/org.nickvision.cavalier

**Comment by bbhtt** [comment]
Unfortunately that's outdated, the list of protected branches is here https://discourse.flathub.org/t/enforcing-branch-protection-on-existing-repositories/1935

**Comment by bilelmoussaoui** [comment]
done
