### ISSUE TITLE
kde runtime 5.10 not updated

### ISSUE THREAD

**Issue by eszlari** [flathub/flathub#436]
```
$ flatpak remote-info flathub org.kde.Platform//5.10
Ref: runtime/org.kde.Platform/x86_64/5.10
ID: org.kde.Platform
Arch: x86_64
Branch: 5.10
Date: 2018-05-15 23:13:26 +0000
Subject: Update to KF 5.46.0 (f6ecadb0)
Commit: 238a6fa3cb56b48b706748b1b872b57bdd9a0f01f334fed6bf3b3b32f126a389
Parent: 10cafcbdcddb29db2fb8e12fb58653ccfbf9aeb4331290dac9400b30b3aa38c8
Download size: 579,1 MB
Installed size: 1,6 GB

```
https://flathub.org/builds/#/builders/2/builds/2185

**Comment by eszlari** [comment]
@aleixpol Maybe you can trigger a rebuild?

**Comment by eszlari** [comment]
Yeah, the build was successful, but the binaries have not been uploaded to flathub, it seems.

**Comment by aleixpol** [comment]
Now I have this issue with 5.11. It fails to upload:
https://flathub.org/builds/#/builders/9/builds/1182

`error: Failure signing commit file: GPGME: General error`

Any ideas?

**Comment by eszlari** [comment]
I'm the wrong guy to ask, but maybe @barthalion @jgarciao @alexlarsson @TingPing have an idea.

**Comment by barthalion** [comment]
We're waiting for @ramcq to unlock GPG smartcard used for signing the repo. I'll retrigger everything that failed in the meantime when it happens.

**Comment by eszlari** [comment]
Why have you closed this? The 5.10 runtime is now 7 commits behind.

**Comment by barthalion** [comment]
Because it was triggered last time 8 days ago. Network and GPG smartcard issue were fixed so nothing to do here.

**Comment by eszlari** [comment]
> nothing to do here

How about updating the 5.10 runtime to this commit:
https://github.com/KDE/flatpak-kde-runtime/commit/8d7e6598ac9001ff0a0be40a5146844b85e1b4c8

**Comment by ramcq** [comment]
https://flathub.org/builds/#/builders/2/builds/2671

**Comment by ramcq** [comment]
I restarted the buildbot too, perhaps it was something weird with the builds.json not being reloaded. Because 5.9 and 5.11 seemed to have been built recently, but 5.10 wasn't.
