### ISSUE TITLE
Please add maintainer for Portfolio Performance

### ISSUE THREAD

**Issue by roshanshariff** [flathub/flathub#4371]
Andreas Buchen (@buchen) is the author of [Portfolio Performance](https://github.com/portfolio-performance/portfolio) and should be given access to the [info.portfolio_performance.PortfolioPerformance](https://github.com/flathub/info.portfolio_performance.PortfolioPerformance) Flathub repository as well.

Thanks!

**Comment by barthalion** [comment]
Invite sent. Thanks!
