### ISSUE TITLE
Add Oro as a maintainer to com.usebottles.bottles

### ISSUE THREAD

**Issue by orowith2os** [flathub/flathub#4375]
I asked @mirkobrombin about being a Bottles maintainer and org member not too long ago and was accepted; I'd like to be added as a Flathub package maintainer, so I can merge fixes there too. 

@mirkobrombin needs to confirm this before I can be added.

**Comment by mirkobrombin** [comment]
I confirm.

**Comment by barthalion** [comment]
Done, thank you.
