### ISSUE TITLE
Yuzu and a few other apps don't have releases

### ISSUE THREAD

**Issue by razzeee** [flathub/flathub#4408]
https://flathub.org/apps/org.yuzu_emu.yuzu

[flathub/org.yuzu_emu.yuzu@master/org.yuzu_emu.yuzu.metainfo.xml](https://github.com/flathub/org.yuzu_emu.yuzu/blob/master/org.yuzu_emu.yuzu.metainfo.xml?rgh-link-date=2023-08-10T23%3A45%3A43Z)

Looking at the source file that's currently at https://dl.flathub.org/repo/appstream/x86_64/appstream.xml.gz it does not include any releases. 

It might be the format, that causes some place to drop `releases`

**Comment by razzeee** [comment]
Should check this after libappstream migration, it might improve due to that

**Comment by bbhtt** [comment]
Seems fixed now, website also shows the version: https://flathub.org/apps/org.yuzu_emu.yuzu

![image](https://github.com/flathub/flathub/assets/62639087/9e0c321f-fdec-4f82-8296-574b7a0344d1)

**Comment by hfiguiere** [comment]
Yuzu installed 2 appstream files. That's was probably the original problem.
