### ISSUE TITLE
RuneScape NXT Client Issue

### ISSUE THREAD

**Issue by djwolf** [flathub/flathub#441]
I'm not sure if this is the right place to report this, but flatpak's version of the NXT client completely breaks on Fedora 28 after the installation of Nvidia drivers. I have a GTX 660 and I have provided more information about my specs, including logs, on the linux questions page, here: [https://www.linuxquestions.org/questions/linux-software-2/libgl-error-on-fedora-28-swrast-solved-4175631923/](https://www.linuxquestions.org/questions/linux-software-2/libgl-error-on-fedora-28-swrast-solved-4175631923/)

The gist of the issue is an error with the SWRAST driver. I tried running Flatpak's RuneScape in a VM with the Nouveau drivers and it worked just fine. In order for me to play RuneScape on Fedora with Nvidia drivers, I have to install the official client from their website, made for Ubuntu, and extract it using this reddit tutorial: [https://www.reddit.com/r/runescape/comments/5lfsr1/nxt_installation_on_fedora_25/](https://www.reddit.com/r/runescape/comments/5lfsr1/nxt_installation_on_fedora_25/)

**Comment by ernestask** [comment]
https://github.com/flathub/com.jagex.RuneScape is the place.

**Comment by mkrajnak** [comment]
it is a long term issue https://github.com/flathub/com.jagex.RuneScape/issues/31

**Comment by weedmic** [comment]
from my understanding flatpak is a container with all you need - so if your local drivers work, the flatpak would work.  Meaning I don't think "that" is your issue.

I believe it is more likely:  https://github.com/flathub/com.jagex.RuneScape/issues/23 or what I read on the r/s forum @ QFC 278-279-573-66145484.
