### ISSUE TITLE
Buildbot has stopped working

### ISSUE THREAD

**Issue by realmazharhussain** [flathub/flathub#4427]
The Flathub instance of buildbot has stopped working. Currently, The very last build started 3.75 hours ago and is stuck in the "Commiting builds" phase for all that time. The oldest build still running started almost 5 hours ago and is stuck in "Commiting builds" stage for 4.7 hours.

No new builds can be started.

**Comment by Justinzobel** [comment]
This appears to be fixed now, builds are flowing.
