### ISSUE TITLE
Change default branch of com.riverbankcomputing.PyQt.BaseApp to wiki

### ISSUE THREAD

**Issue by JakobDev** [flathub/flathub#4453]
The default branch of [com.riverbankcomputing.PyQt.BaseApp](https://github.com/flathub/com.riverbankcomputing.PyQt.BaseApp) is currently `branch/5.15-21.08` which is EOL. The Repo contains a `wiki` branch with the documentation. It would be better to have this branch as the default branch.

**Comment by JakobDev** [comment]
Ping @barthalion

**Comment by hfiguiere** [comment]
Done.

Not sure who this make sense, given that now forking a repo by default only take the default brankch, but it's your call. It can still be changed.
