### ISSUE TITLE
Change maintainer of org.cubocore.xxxx apps to another dev of the project

### ISSUE THREAD

**Issue by rahmanshaber** [flathub/flathub#4454]
Hi, all the org.cubocore.xxxx app's maintainer was @s96Abrar, who is one of the dev for the apps. He doesn't have time to maintain them in future so i am requesting to transfer the maintaines to me who is also owner of the project. Here is the project repo where you can verify this https://gitlab.com/groups/cubocore/-/group_members. thanks

**Comment by s96Abrar** [comment]
Yes, it would be better to provide access to @rahmanshaber so that he can maintain the packages for future releases.

**Comment by hfiguiere** [comment]
Sent invites, I hope I didn't miss any.

You have to accept them all.
