### ISSUE TITLE
Verified Apps Do Not Show Up As Installable Apps

### ISSUE THREAD

**Issue by n128-98** [flathub/flathub#4508]
Though On The Website, It Says That There Are Verified Apps, It Seems I Cannot Install Them Through Any Form Of Flathub, Am I Using The Wrong Repository?
![Screenshot 2023-09-12 11 30 27 AM](https://github.com/flathub/flathub/assets/74434783/f4308f01-9d9f-4262-b8b1-6dda0892a360)
![Screenshot 2023-09-12 11 31 14 AM](https://github.com/flathub/flathub/assets/74434783/0cf2573b-2635-49d6-b5fc-ec26aa282d7b)

**Comment by n128-98** [comment]
(I Have Also Tried The com.opera.Opera  Approach, That Doesnt Work Either, I Am Using ChromeOS)

**Comment by hfiguiere** [comment]
> I Am Using ChromeOS

Let me guess. The hardware architecture is arm.

Unfortunately most of these proprietary pieces of software are built to only support Intel-64bits found on PC.

**Comment by n128-98** [comment]
maybe, but why does it just say it doesnt exist? shouldnt it give me an error like ¨installation failed: arm detected. must have Intel64bit To Install¨?

**Comment by razzeee** [comment]
You should raise that issue with https://github.com/flatpak/flatpak as they are the party, that needs to detect, that your trying to access an arm only flatpak

**Comment by rusty-snake** [comment]
flatpak/flatpak#5474
