### ISSUE TITLE
Please archive repositories

### ISSUE THREAD

**Issue by Grumbel** [flathub/flathub#4509]
The following repositories can all be archived, or somebody else can take them over, I have no interest in maintaining them:

* https://github.com/flathub/io.gitlab.construo.construo
* https://github.com/flathub/io.gitlab.evtest_qt.evtest_qt
* https://github.com/flathub/io.gitlab.jstest_gtk.jstest_gtk
* https://github.com/flathub/io.gitlab.sdl_jstest.sdl2_jstest
* https://github.com/flathub/io.gitlab.sdl_jstest.sdl_jstest
* https://github.com/flathub/io.gitlab.windstille.Windstille-0_2
* https://github.com/flathub/org.seul.pingus
* https://github.com/flathub/org.supertux.SuperTux-Milestone1
* https://github.com/flathub/org.supertuxproject.SuperTux

**Comment by hfiguiere** [comment]
Apps must be marked as EOL first.

**Comment by Newbytee** [comment]
I could take over the Supertux games.

**Comment by hfiguiere** [comment]
Some of these packages have had very recent updates submitted but ignored. AKA no merged.

**Comment by AsciiWolf** [comment]
jstest-gtk looks like a really useful tool. It would be pity if it was removed from Flathub. I can take over the Flatpak if needed.

I can also help co-maintain SuperTux.

**Comment by orowith2os** [comment]
I can look at maintaining what's left after everybody else has their fill. At the very least, I can update runtimes.

**Comment by AsciiWolf** [comment]
@Grumbel Please, wait for the people interested in taking over your Flatpaks before setting them as EOL. Thanks!

**Comment by bbhtt** [comment]
All except SuperTux is EOL-ed. It takes significant effort from the admins to un-EOL and not sure if that's even possible or will be done.

**Comment by orowith2os** [comment]
AIUI the process for un-EOLing an application is just removing the tag, and pushing an/the update. If the repository is archived, or needs a new maintainer, *then* it needs more effort.

If there are maintainers willing to step up to the job (and there are, if you scroll up a bit), we can start keeping things rolling.

**Comment by Grumbel** [comment]
Everything is now marked as EOL, except for org.supertuxproject.SuperTux, AsciiWolf and Newbytee can have that package.

**Comment by AsciiWolf** [comment]
@Grumbel I am also interested in the jstest-gtk package, as I already mentioned multiple times. By the way, I and Newbytee can also help with the Pingus package.

No offense, but EOL-ing packages other maintainers are interested in taking over without waiting for them is a not a correct approach. Also, what is the point of these [two](https://gitlab.com/construo/construo/-/commit/88ca3f01b931cb96cc8e8a643280f45c2080710c) [commits](https://gitlab.com/jstest-gtk/jstest-gtk/-/commit/72c5ee0e2b3f8858889370b5666e62e256e361d3)? AppStream metadata are not a Flatpak specific thing and you just made your apps incompatible with any modern Linux packaging system by removing the metadata.

**Comment by AsciiWolf** [comment]
https://gitlab.com/jstest-gtk/jstest-gtk/-/issues/31

**Comment by AsciiWolf** [comment]
> Update for 2018: The /dev/input/jsX interface that jstest-gtk uses is largely obsolete. Most newer software will use /dev/input/eventX, so neither the calibration nor the remapping functionality will have any effect.

(Source: https://jstest-gtk.gitlab.io)

If this is true, I am probably interested in evtest-qt instead of jstest-gtk.

**Comment by AsciiWolf** [comment]
I have changed my mind about the jstest-gtk and evtest-qt Flatpaks. If they do not work properly (as stated in my previous comment), there is no point in keeping them on Flathub. Also, the upstream removal of AppStream metadata indicates that these projects are probably not intended to be maintained for modern Linux distributions anymore. Windstille and Construo are probably the same case.

On the other hand, I am still interested in (co-)maintaining [org.supertuxproject.SuperTux](https://github.com/flathub/org.supertuxproject.SuperTux) and [org.seul.pingus](https://github.com/flathub/org.seul.pingus).

**Comment by AsciiWolf** [comment]
@barthalion Any chance you could add push rights for the _org.supertuxproject.SuperTux_ and _org.seul.pingus_ repos to me and @Newbytee? Thanks!

**Comment by AsciiWolf** [comment]
Still waiting for the push rights for _org.supertuxproject.SuperTux_ and _org.seul.pingus_.

/cc @nedrichards

**Comment by rautamiekka** [comment]
> Everything is now marked as EOL, except for org.supertuxproject.SuperTux, AsciiWolf and Newbytee can have that package.

Just like the others said, I also agree this is sounding like a very selfish mismanagement.

**Comment by bbhtt** [comment]
None other than `org.supertuxproject.SuperTux` was un EOL-ed by new maintainers. So I archived the repos, please open new issues if anyone is interested in picking these up.
