### ISSUE TITLE
Move away from Github to something less intrusive

### ISSUE THREAD

**Issue by dsvi** [flathub/flathub#4543]
Since Github will **force** all the accounts to have 2FA, do you have any plans to move to a hosting wich is less privacy intrusive?

**Comment by razzeee** [comment]
How is 2fa a privacy concern when your using your fido key?

**Comment by dsvi** [comment]
As far as i understand, if you dont have fido key you have to use and adroid app

**Comment by hfiguiere** [comment]
FreeOTP work fine too.

**Comment by dsvi** [comment]
Do you beleive that going through the 2FA troubles, to contribute to an open source project, is a bit too much?
Should it be more accessible?

Security is fine, and other hostings have 2FA if you want one, but none of them **forces** users to use it.

**Comment by rusty-snake** [comment]
You can use any TOTP generator (Google authenticator, Microsoft authrnticator, aegid, keepassxc, keepassdx, ...).

**Comment by dsvi** [comment]
> You can use any TOTP generator (Google authenticator, Microsoft authrnticator, aegis, keepassxc, keepassdx, ...). Even an airgapped OpenBSD can run TOTP Software. How dies this affect privacy in and way.

Still going through the 2FA troubles, just to contribute to an open source project, is too much.
Security is fine, and other hostings have 2FA if you want one, but none of them **forces** you to use it.

**Comment by rusty-snake** [comment]
> but none of them forces you to use it.

Until now. Unfortunately.

> 2FA troubles

What troubles.

**Comment by dsvi** [comment]
> Until now. Unfortunately.

Nope. Only github forces it. No one else does.

**Comment by razzeee** [comment]
Anyway, you will be able to upload builds directly in the future, if you choose so. Only needs you to trust github or gnome gitlab or kde gitlab or gitlab

**Comment by dsvi** [comment]
Well gitlab doesn't force you to use 2FA. So it's a good alternative

And if a corporation is forcing you to do something, you can be certain its not for your good.

**Comment by razzeee** [comment]
I'm not sure, if you get what a second factor is. With all due respect, please read up on it.

**Comment by dsvi** [comment]
Corporations don't have your best interests in mind when they force something upon you.
In that i am sure ;)

**Comment by razzeee** [comment]
Which means 2fa isn't the problem here, gotcha.

**Comment by dsvi** [comment]
The fact that they force it is a problem.

Besides. The easier it is to contribute, the more contribution a project will get.

2FA is just another forced obstacle

I am not sure why Microsoft is the only one who decided to force it, but i am sure they don't do that for your good.
