### ISSUE TITLE
EOL com.musixmatch.Musixmatch

### ISSUE THREAD

**Issue by razzeee** [flathub/flathub#4544]
Has been broken for some time

https://github.com/flathub/com.musixmatch.Musixmatch/issues/7

Another report https://discourse.flathub.org/t/cant-install-musixmatch-for-a-long-time/5214

**Comment by bbhtt** [comment]
Revived a working copy in https://github.com/flathub/com.musixmatch.Musixmatch/pull/371. If anyone wants to pick up the maintenance.

**Comment by hfiguiere** [comment]
if you don't intend to take over, I recommend that the EOL stay. It's not like it contain parts that can be fixed by users.

**Comment by bbhtt** [comment]
Let's merge above. I'll update it when needed (app itself won't receive updates), if it breaks I'll EOL.
