### ISSUE TITLE
Find a way to separate infrastructure from app repos

### ISSUE THREAD

**Issue by razzeee** [flathub/flathub#4587]
I still think it's very unfortunate, that it's very hard to find the non-app projects on the org https://github.com/flathub

Makes it very hard for people to be aware, what parts of code we really have and where to contribute/look for things.

The list is also very long and hard to go through, as you mostly see flathub apps.

I'm not sure what the correct solution for this would be, or if there even is any, but I think we should at least talk about it.

**Comment by razzeee** [comment]
Yeah, but would probably take some effort to get everything moved, with secrets and potential deployments. And once again, can probably only be done by one person.

**Comment by hfiguiere** [comment]
I think there is more than one person with these rights. And we want to reduce the bus factor too.

**Comment by razzeee** [comment]
We're down to these non app repos:

- shared-modules
- flathub
- electron-sample-app
- actions
- governance

So I think we can close this
