### ISSUE TITLE
Allow auto-merge for org.gnome.Calls

### ISSUE THREAD

**Issue by darkdragon-001** [flathub/flathub#4617]
Please enable [auto-merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request) on [org.gnome.Calls](https://github.com/flathub/org.gnome.Calls). This still requires all required statuses to pass but allows auto-merging submodules for dependabot (see [documentation](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request)) or allows clicking the button right when you made changes without waiting for building (tens of minutes) and waiting for status to be reported (hours). This is especially useful for unrelated changes like `README.md` or similar where you know it builds but which still require the full CI round.

**Comment by bbhtt** [comment]
Do you still need this?

**Comment by darkdragon-001** [comment]
@bbhtt yes

**Comment by bbhtt** [comment]
Enabled

**Comment by darkdragon-001** [comment]
Thanks a lot!
