### ISSUE TITLE
Duckstation crashes with error "The Wayland connection broke. Did the Wayland compositor die?"

### ISSUE THREAD

**Issue by PaperVb64** [flathub/flathub#4621]
On ChromeOS, running aarch64.

**Comment by hfiguiere** [comment]
which package is that? Because here is unlikely to be the place.

**Comment by PaperVb64** [comment]
org.duckstation.Duckstation, and flatpak told me to come here before reporting here (AND Duckstation doesn't have an issues tab :D)

**Comment by hfiguiere** [comment]
the flathub project doesn't allow filing issues. Nothing we can do here.

**Comment by hfiguiere** [comment]
> and flatpak told me

I'm not sure who that flatpak person is.

**Comment by PaperVb64** [comment]
as in the issues area for flatpak. Before filing an issue with flatpak, i should check to see if it's an issue with the app itself
________________________________
