### ISSUE TITLE
Enable dot suffix check

### ISSUE THREAD

**Issue by razzeee** [flathub/flathub#4635]
Enable --override=summary-has-dot-suffix=warning,name-has-dot-suffix=warning

See:
https://github.com/ximion/appstream/issues/542#issuecomment-1777474630

**Comment by JakobDev** [comment]
Where do you want to enable this? As far as I know, Flathub still uses the old `appstream-util` instead of the new `appstreamcli` for validation.

**Comment by razzeee** [comment]
Right, so either we do this later, when we've migrated, or we add it to our side of in https://github.com/flathub/flatpak-builder-lint

**Comment by JakobDev** [comment]
Is there still anything blocking the libappstrem migration?

Even if we don't migrate to libappstream yet, we can still use appstreamcli for the validation.

**Comment by razzeee** [comment]
No, there is nothing blocking it, only time constraints

**Comment by bbhtt** [comment]
Solved by https://github.com/flathub-infra/flatpak-builder-lint/blob/f0b5e53414bd4ec913dcef82a0d7586d7a31f566/flatpak_builder_lint/appstream.py#L31

The desicion was not to error from appstreamcli on summary ending with dot. That's probably going to be a separate linter warning. I added it as a todo in https://github.com/flathub-infra/flatpak-builder-lint/issues/156
