### ISSUE TITLE
Duplicate images for Gaia Sky

### ISSUE THREAD

**Issue by BryanQuigley** [flathub/flathub#4638]
We see duplicate images for https://flathub.org/apps/de.uni_heidelberg.zah.GaiaSky.  Effectively, the website shows the same number of images as we have https://github.com/flathub/de.uni_heidelberg.zah.GaiaSky/blob/master/de.uni_heidelberg.zah.GaiaSky.metainfo.xml  but duplicates some of them.

What images are duplicated appears to change on some builds.  This time it is the 2nd and 3rd image (among others). 

I couldn't find any apps that have a similar number of screenshots as us.  Could we be exposing a bug others  haven't found yet?

**Comment by razzeee** [comment]
If you rebuild this, this might be better now

**Comment by bbhtt** [comment]
Triggered a rebuild it's fixed now
