### ISSUE TITLE
Flathub details look terrible in GNOME Software

### ISSUE THREAD

**Issue by allanday** [flathub/flathub#468]
Yesterday I enabled Flathub in Fedora, by downloading the .flatpakrepo file. This is what it looked like when previewed:

![image](https://user-images.githubusercontent.com/213068/41985285-cc4d278a-7a2a-11e8-91cc-7aed94aaa8c8.png)

It's pretty terrible. Ideally we'd provide an encouraging, positive description, which includes directions on how to use it. We'd also provide an attractive image.

**Comment by dsboger** [comment]
It looks like it is being treated as an app. Maybe there should be a specialized view for repos?

**Comment by allanday** [comment]
> Maybe there should be a specialized view for repos?

Quite possibly. The description could still be better though.

**Comment by hadess** [comment]
This is a gnome-software bug, quite clearly.

**Comment by allanday** [comment]
> This is a gnome-software bug, quite clearly.

The description text should be improved.

**Comment by bilelmoussaoui** [comment]
Closing this as https://github.com/flathub/flathub/issues/468 contains more info on how to improve the details.
