### ISSUE TITLE
Publishing fails with "Can't prune build while in use"

### ISSUE THREAD

**Issue by johnfactotum** [flathub/flathub#4687]
https://buildbot.flathub.org/#/builders/6/builds/81264

Publishing failed. It says:

```
Purging build https://hub.flathub.org/api/v1/build/63898
Api call to https://hub.flathub.org/api/v1/build/63898/purge failed with status 400, details: {'error-type': 'generic-error', 'message': "Can't prune build while in use", 'status': 400}
```

**Comment by razzeee** [comment]
In theory, you should get an email about that, if you ever logged in at https://flathub.org and have a valid email set on the account, that you've used for login.

**Comment by m4tx** [comment]
@razzeee interesting — seems like I've never received any emails from the Flathub Buildbot (checked my spam folder, too), even though I have valid email set in my profile:
![image](https://github.com/flathub/flathub/assets/3128220/058988cb-7a9b-4401-889e-ead49e000592)

**Comment by razzeee** [comment]
It's not the build bot, it would be the website and it sending email is kinda new (as is the holding for review)

**Comment by bbhtt** [comment]
Solved by flat-manager https://github.com/flatpak/flat-manager/releases/tag/0.4.3
