### ISSUE TITLE
Allow to publish an app to a channel

### ISSUE THREAD

**Issue by claudioandre-br** [flathub/flathub#469]
Alternative titles could be:
- Allow to publish development snapshots;
- Create channels to publish (not only to the stable channel).
- Allow to publish devel/unstable/(beta, at least) applications.

The concept exists on Ubuntu snap. And also, for example, as "back-ports" repositories anyone can find available everywhere.

It would be be very useful if I don't need to create bundles/personal repositories to deploy the non stable testing, dogfooding version.

**Comment by TingPing** [comment]
I think we generally want this, just needs some work on the bot to pull from different branches.

**Comment by matze** [comment]
Are there any news?

**Comment by somas95** [comment]
This is solved now, right?

**Comment by barthalion** [comment]
Correct, see Alex' blog for details: https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/
