### ISSUE TITLE
TeamSpeak is not available in flathub-beta repository

### ISSUE THREAD

**Issue by Zlopez** [flathub/flathub#4691]
Today I created a [beta branch](https://github.com/flathub/com.teamspeak.TeamSpeak/tree/beta) on TeamSpeak repository to package TeamSpeak5. I was able to fix the [build](https://buildbot.flathub.org/#/builders/6/builds/81535) and even test it. 

I added the `flathub-beta` remote locally, but I don't see TeamSpeak on it:
```
$ flatpak --user install flathub-beta com.teamspeak.TeamSpeak
Looking for matches…
error: Nothing matches com.teamspeak.TeamSpeak in remote flathub-beta
```

I'm not sure if I did something wrong or it just takes so much time to appear there.

**Comment by hfiguiere** [comment]
you just lack patience. publishing take 3-4 hours. This was built less than 1 hour.
