### ISSUE TITLE
Trying to install stremio with Flatpak

### ISSUE THREAD

**Issue by 9acca9** [flathub/flathub#4740]
Im getting this error:
```
flatpak install com.stremio.Stremio.flatpakref
error: No such ref 'app/com.stremio.Stremio/aarch64/stable' in remote flathub
```

There is something i can do?
Thanks!

**Comment by hfiguiere** [comment]
Because this:
![image](https://github.com/flathub/flathub/assets/114441/098b4938-4d96-4745-a6b4-7636404881c9)

Nothing that can be done here. 

You can file an issue with the project directly
https://github.com/flathub/com.stremio.Stremio/issues
