### ISSUE TITLE
Asking Help for port this app to Flathub (Tachidesk-VaadinUI)

### ISSUE THREAD

**Issue by dtantono** [flathub/flathub#4758]
Hi
it looks like the dev have a problem to port this app to flathub. Anybody to help? 

https://github.com/Suwayomi/Tachidesk-VaadinUI/issues/82

**Comment by hfiguiere** [comment]
https://docs.flathub.org/docs/for-app-authors/submission/

**Comment by dtantono** [comment]
@hfiguiere I got this error. What do you think?
![image](https://github.com/flathub/flathub/assets/29157187/61ffa856-d6ec-442a-bd51-75fbe2e654a9)

**Comment by bbhtt** [comment]
I see it up at https://discourse.flathub.org/t/tachidesk-vaadinui-flatpak-request-help/5589. Please use the discourse to make/talk about package requests, thanks.
