### ISSUE TITLE
Need JWT for org.freedesktop.Platform.openh264

### ISSUE THREAD

**Issue by mcatanzaro** [flathub/flathub#4766]
Hi, we need a new JWT for org.freedesktop.Platform.openh264

I don't fully understand what this is so I'm probably not the best person to report this issue, but I've been told to request it here in order to fix CI for https://gitlab.com/freedesktop-sdk/openh264-extension

**Comment by barthalion** [comment]
Updated the token and started a new pipeline: https://gitlab.com/freedesktop-sdk/openh264-extension/-/pipelines/1094975553
