### ISSUE TITLE
[Wiki] Mention that enabling the network at build time is forbidden

### ISSUE THREAD

**Issue by bochecha** [flathub/flathub#477]
As far as I know, we don't accept apps on Flathub which enable the network at build time.

This should be written on the App-Requirements page, to make it clear to newcomers.

I can't find any mention of it on the current page.

**Comment by nedrichards** [comment]
Thanks, I fixed in this revision. https://github.com/flathub/flathub/wiki/App-Requirements/e7b783a09c6d05513b020463c4940fb5b731c1e3
