### ISSUE TITLE
RetroDECK please enable xdg-config-access

### ISSUE THREAD

**Issue by XargonWan** [flathub/flathub#4786]
https://buildbot.flathub.org/#/builders/37/builds/10832

Some bundled emulators and Zenity are using this access in read only.

**Comment by JakobDev** [comment]
You need to make a PR against [this file](https://github.com/flathub/flatpak-builder-lint/blob/master/flatpak_builder_lint/staticfiles/exceptions.json).

**Comment by XargonWan** [comment]
Done: https://github.com/flathub/flatpak-builder-lint/pull/229

**Comment by XargonWan** [comment]
I still have this issue: https://buildbot.flathub.org/#/builders/37/builds/14155
