### ISSUE TITLE
Add Calinou to org.godotengine.Godot3Sharp as Collaborator (if he hasn't been added already)

### ISSUE THREAD

**Issue by Zishan-Rahman** [flathub/flathub#4795]
I don't think @Calinou (sorry for the ping) was added to [`org.godotengine.Godot3Sharp`](https://github.com/flathub/org.godotengine.Godot3Sharp/) as a Collaborator yet. He has Collaborator permissions for [`org.godotengine.Godot`](https://github.com/flathub/org.godotengine.Godot/), [`org.godotengine.Godot3`](https://github.com/flathub/org.godotengine.Godot3/) and [`org.godotengine.GodotSharp`](https://github.com/flathub/org.godotengine.GodotSharp/), so I'd like to kindly request that he be added as a Collaborator to `org.godotengine.Godot3Sharp` as well, please (if he wasn't already added as a Collaborator).

**Comment by hfiguiere** [comment]
invite sent.
