### ISSUE TITLE
Flathub.org front page layout update.

### ISSUE THREAD

**Issue by BeverlyCode** [flathub/flathub#4808]
It now displays less items per category, whats up with that? I'm not so sure this is a good change. :worried:

**Comment by razzeee** [comment]
The idea is to show less elements, so the page loads/renders faster.

It should also motivate users to scroll, as previously your whole screen could have been taken by the first category.

And it's kind of foreshadowing new additions to that page, so for us to add new stuff, we got rid of some old.

**Comment by razzeee** [comment]
That's all already prepared, but it's not random.

And the Ajax thingy is probably not a good idea or at least raises the question why you just won't click more on there.

**Comment by razzeee** [comment]
I've never clicked the wrong more button, but I am unhappy with it, as SEO wise it has no context.

We can not guarantee any app that's been newly added to be on the front page for however long. It's just too brittle, it depends on what and how new submissions get merged. So you might have had a L just to bad luck before.

Anyway most newly added apps do pass the app review, but are not really up to our metadata quality standard. So not showing them on the homepage might be a net good. I usually go through the new additions and try to get them better, but it takes time.
