### ISSUE TITLE
Package request: HopToDesk (Remote Desktop App)

### ISSUE THREAD

**Issue by boustanihani** [flathub/flathub#4809]
Please add a package for HopToDesk
https://www.hoptodesk.com/

**HopToDesk** is an opensource remote desktop app similar to **TeamViewer** and **Anydesk**.

A ***.deb** package for **(debian/ubuntu)** already exists.

**Comment by razzeee** [comment]
Requests can be done in the forum, still there is no guarantee of anyone picking up that request.
