### ISSUE TITLE
Add new maintainer to io.edcd.EDMarketConnector

### ISSUE THREAD

**Issue by der-eismann** [flathub/flathub#4823]
Hey everyone, I'd kindly ask you to add @dvdmuckle as an additional maintainer to io.edcd.EDMarketConnector as requested in https://github.com/EDCD/EDMarketConnector/issues/1689#issuecomment-1872419540.
Could you tell me if someone else has write permissions on the repository? I can't find the info anywhere.

**Comment by bbhtt** [comment]
Invite sent, please accept within a week.
