### ISSUE TITLE
Error compiling gcl for io.github.wxmaxima_developers.wxMaxima

### ISSUE THREAD

**Issue by bztd** [flathub/flathub#4824]
I have been trying to compile gcl but the compilation stops without any error message that could give me an idea of what is happening.

https://buildbot.flathub.org/#/builders/6/builds/90555

On the other hand, when I compile on my system the compilation is successful.
I would appreciate any ideas, thanks in advance.

**Comment by bbhtt** [comment]
The error is here on the top:

```
make[1]: Entering directory '/run/build/gcl/lsp'
makefile:33: warning: ignoring prerequisites on suffix rule definition
../unixport/saved_pre_gcl ../unixport/ -compile gcl_collectfn.lsp
make[1]: ../unixport/saved_pre_gcl: No such file or directory <----------
make[1]: *** [makefile:35: gcl_collectfn.o] Error 127 <----------
make[1]: Leaving directory '/run/build/gcl/cmpnew'
make[1]: *** No rule to make target 'gcl_info.o'.  Stop. <----------
make[1]: Leaving directory '/run/build/gcl/lsp'
make: *** [makefile:111: cmpnew/gcl_collectfn.o] Error 2 <----------
make: *** Waiting for unfinished jobs....
make: *** [makefile:111: lsp/gcl_info.o] Error 2 <----------
make[1]: Entering directory '/run/build/gcl/info'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/run/build/gcl/info'
make[1]: Entering directory '/run/build/gcl'
```

**Comment by bbhtt** [comment]
I don't have any immediate suggestions to fix the build. Not familiar with gcl. Looks like both Fedora and Debian build gcl with a bunch of patches. I'd suggest looking there or reporting directly to the developers https://savannah.gnu.org/bugs/?group=gcl or https://lists.gnu.org/mailman/listinfo/gcl-devel
