### ISSUE TITLE
Feature suggestion: provide proper no sandbox mode for IDE tooling that includes program access

### ISSUE THREAD

**Issue by ell1e** [flathub/flathub#4825]
*(My apologies if this is a duplicate or if it's already available, but given all code editors I've ever tried on FlatHub other than maybe GNOME Builder suffer from this problem, it doesn't seem to be resolved)*

**The problem:**

As is elaborated here https://bugs.kde.org/show_bug.cgi?id=431223 and in so many other places I've come across, whatever is found on FlatHub of **most dev tooling seems to be currently borderline unusable unless you work on the most standard project types,** due to the sandboxing. This happens even with full host filesystem access enabled (which it usually is for IDE tools) which then actually leaves arguably little to no security benefit at this point anyway, because the environment vars are too different and separate, and as a result no tooling the user may have installed outside seems to be usually accessible. This can be seen [here with what is apparently needed to work around that](https://gitlab.gnome.org/GNOME/gnome-builder/-/commit/fee5214c927c841b66cfd34c0321b8c9890149ce).

This seems to be especially a problem for: 1. unusual LSPs (no flatpak extension image stuff can ever solve that because there's always another one that nobody thought of, it doesn't scale), 2. unusual extra tools people may want to use in the IDE terminal like different style checkers or formatters, 3. different build tools people may want to use in the IDE terminal that aren't the usual ones used for that programming language, 4. probably more I didn't think of.

**A potential solution:**

As a solution, I propose that there's a proper, extended no sandboxing mode that will 1. merge PATH such that maybe the stuff inside the flatpak filesystem is secondary, and everything from the outside PATH is preferred, 2. set and use all the XDG config, cache, socket, whatever dirs from the outside system including /tmp and such, 3. whatever else I may have forgotten that is needed to make most of the "outside" tooling work. Basically, what [gnome builder is currently manually doing, or similar.](https://gitlab.gnome.org/GNOME/gnome-builder/-/commit/fee5214c927c841b66cfd34c0321b8c9890149ce)

I'm aware this also introduces new corner case problems due to the merged PATH and whatnot, and possibly binaries from the inside unintentionally calling things from the outside instead of intended neighboring inside copies. However, a lot of this can be avoided when the inside image of the flatpak contains for example a proper portable install of the app, e.g. by wrapping an AppImage.

I'm aware this making-it-portable-if-it-wasn't-to-start-with flatpak was originally also intended to solve which such a new mode would kind of in parts undo, but the thing is, flatpak also solves a lot of other things, among them 1. way more accessible methods of distribution for beginners than figuring out how to download & find again an AppImage in your filesystem and manually keep that up to date and all that, 2. better directories and methods of browsing of what is even available via platforms like FlatHub, 3. better update mechanisms to rely on for the app developer if the app doesn't bother with an integrated one, 4. integrates better into immutable-style distros, 5. other stuff I probably didn't think of.

All of these advantages would remain available, so IDE tooling which wanted to access these but wanted to go the extra mile of wrapping a more portable binary inside the flatpak (which they might already have at zero cost if they also provide AppImages) could then use this new mode to make sure that the user can actually access all dev tooling they would ever want with mostly no more weird separations and indirections.

**TL;DR:**

I suggest flatpak lets IDE stuff trade some portability and risk more clashes between the binaries and such, via a even-less-sandboxing mode, in favor of actually accessing tooling on the host system properly without many restrictions. (Without manually needing to figure out and do the hackery that gnome builder is doing.)

**Comment by bbhtt** [comment]
This seems more like a feature request for flatpak, than Flathub. Some of the shortcomings are already known, though.

> As a solution, I propose that there's a proper, extended no sandboxing mode that will 1. merge PATH such that maybe the stuff inside the flatpak filesystem is secondary, and everything from the outside PATH is preferred, 2. set and use all the XDG config, cache, socket, whatever dirs from the outside system including /tmp and such, 3. whatever else I may have forgotten that is needed to make most of the "outside" tooling work.

You have to ask this in flatpak, it has been asked already in various forms like https://github.com/flatpak/flatpak/issues/2742. Given how flatpak is set up I have doubts whether such a "no-sandbox" mode can easily be achievable. 

Right now, 

You can ask in https://gitlab.com/freedesktop-sdk/freedesktop-sdk for a "common" extension point for all development tools and create an extension based on that extension point on Flathub that'll include language servers, CLI tools etc. This will not only be useful to Kate, but also to all the other IDEs on Flathub that share the same need.

The other part is launching arbitrary commands that are not included in the flatpak package. For that, as you can see, Kate already has https://github.com/flathub/org.kde.kate/blob/66cbd6ca5359569f892acc9fedbe00cacebd47ab/org.kde.kate.json#L16 flatpak-spawn permission as does many other IDEs on Flathub. With that, you can run a command installed on the host by prefixing it with `flatpak-spawn --host command`.

**Comment by ell1e** [comment]
> You can ask in https://gitlab.com/freedesktop-sdk/freedesktop-sdk for a "common" extension point for all development tools and create an extension based on that extension point on Flathub that'll include language servers

This really doesn't scale, and is also useless for niche languages and unusual tooling if I understand correctly how it works.

I meant to file this in the flatpak repo actually and just accidentally picked the wrong one :joy:  my apologies.

**Comment by bbhtt** [comment]
For languages, there is already an SDK extension point https://github.com/flathub?q=org.freedesktop.Sdk.Extension&type=all&language=&sort=

> I meant to file this in the flatpak repo actually and just accidentally picked the wrong one 😂 my apologies.

Ok let's close this then
