### ISSUE TITLE
Ownership transfer request for so.libdb.gtkcord4

### ISSUE THREAD

**Issue by tfuxu** [flathub/flathub#4841]
I want to request an ownership transfer of [`so.libdb.gtkcord4`](https://github.com/flathub/so.libdb.gtkcord4) repository to me. This is because of the original package maintainer losing its Github account and not contacting with upstream for more than 2 months, making the package, as of now, 2 versions behind.

This has been discussed with the project owner [here](https://github.com/flathub/so.libdb.gtkcord4/issues/5).

**Comment by barthalion** [comment]
I have sent you an invite.
