### ISSUE TITLE
Can't merge PR because "Some checks haven’t completed yet"

### ISSUE THREAD

**Issue by MightyCreak** [flathub/flathub#4863]
I've created a new PR: https://github.com/flathub/io.github.mightycreak.Diffuse/pull/6

The Flathub build is successful: https://buildbot.flathub.org/#/builders/6/builds/93181

But I can't merge my PR as "Some checks haven’t completed yet".

I can still force merge my PR using local git command-lines, but I wonder if there's something I could/should do to be able to merge directly on GitHub.

Thanks!

**Comment by bbhtt** [comment]
It's up now. Please have patience, sometimes Github takes a while to update due to servers/API requests being slow etc.

PRs requires status checks to pass to merge/push.

**Comment by hfiguiere** [comment]
> but I wonder if there's something I could/should do to be able to merge directly on GitHub.

Just do have patience. It's bunch of computer working together over a network, it's all be deterministic. As for merging without checks, we were there before and it didn't go well.

**Comment by MightyCreak** [comment]
I did wait for around 15 minutes after the build was green on Flathub, at which point I thought that I might have been doing something wrong. In the end, it was just a matter of waiting a bit more, sorry for that :sweat_smile:

**Comment by ZVNexus** [comment]
@bbhtt Recently it's been extraordinarily slow, e.g. I have 9 PRs to be merged, and for each pull request it needs to pass the flathubbot CI check, but it's taking 2-3 hours for GitHub to acknowledge the return status from the bot.

Because each PR needs to be on the latest HEAD before it can be merged, that means 2-3 hours for *each* PR. So for a chain of changes it's taking a full day's worth of hours.

**Comment by bbhtt** [comment]
Not much I can do, @barthalion has access to the server infrastructure of Flathub.

**Comment by fedelibre** [comment]
I'm having the same issue: a PR with a successful build completed three hours ago, but still I cannot merge it.

**Comment by bbhtt** [comment]
Please open new issues with a link.
