### ISSUE TITLE
Ownership transfer request for net.drawpile.drawpile

### ISSUE THREAD

**Issue by askmeaboutlo0m** [flathub/flathub#4865]
Hi, I'm the maintainer of Drawpile, which is [net.drawpile.drawpile on Flathub](https://flathub.org/apps/net.drawpile.drawpile). I'd like to take ownership of that.

I am logged into Flathub using this GitHub account, which has access to the [Drawpile GitHub organization](https://github.com/drawpile), under which [the Drawpile repository is located](https://github.com/drawpile/Drawpile), where you can see by my commits that I'm maintaining the thing.

There's [an open PR from me to update the Flatpak to version 2.2.0](https://github.com/flathub/net.drawpile.drawpile/pull/4), which is coming from a repository out of that organization.

I also own drawpile.net, where you can find a reference to Flatpak [in the 2.2.0 announcement](https://drawpile.net/news/release-2.2.0/). The [Linux download page](https://drawpile.net/download/#Linux) has a reference to the open Flathub PR.

If further proof of ownership or anything else is needed, please let me know.

**Comment by bbhtt** [comment]
Invite sent, please accept within a week. Thanks.
