### ISSUE TITLE
Deprecated `developer_name` element

### ISSUE THREAD

**Issue by sabriunal** [flathub/flathub#4882]
Upstream 1.0 has been released, and the toplevel `developer_name` element is deprecated.

`appstreamcli` suggests using the `name` element in a `developer` block instead.

For example:

```
  <developer id="gnome.org">
    <name>The Loupe Team</name>
  </developer>
```

It seems that Flathub does not yet support this new usage.

Sources:

-  [Upstream Metadata](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-url)
- [appstream issue](https://github.com/ximion/appstream/blob/1217913bc0276ad5a0bf02b8ab93744c373fc4f4/src/as-validator-issue-tag.h#L581-L586)
- [Relevent discourse topic on flathub.org](https://discourse.flathub.org/t/deprecated-developer-name-element/5746)
- [Relevent GNOME changes](https://gitlab.gnome.org/GNOME/Initiatives/-/issues/46)
- [Relevant GNOME Software chages](https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1863)

**Comment by afranke** [comment]
Can you expand on that? Is there a reason it’s sticking to that old version?

**Comment by razzeee** [comment]
It's not simple to switch out and last time we tried, every ubuntu that was using flatpak couldn't update/install anymore. (they had old versions)

There have been more important things since then, but it's the next thing in the pipeline afaik

**Comment by hfiguiere** [comment]
> Can you expand on that? Is there a reason it’s sticking to that old version?

Because all the breaking changes in appstreamcli will cause certain amount of build failure and we need to brace for that. No flathub admin was given the heads up on the breaking change either so no one was able to prepare ahead of time.

You can watch for https://github.com/flathub/org.flatpak.Builder/pull/196 for some of the progress.

**Comment by bbhtt** [comment]
Solved by 

https://github.com/flathub/org.flatpak.Builder/commit/5aaf845242fb98c8e77f0a0868065152e21c047a
https://github.com/flathub-infra/flatpak-builder-lint/commit/7bcac8e2eba9f2d2e06bd9d752972036c3f0e6c9
https://github.com/flathub-infra/flatpak-builder-lint/commit/bbfc701d87c53d6336febf6d4e1121dad424f367

Docs will be updated soon
