### ISSUE TITLE
Extension in beta branch cannot be tested

### ISSUE THREAD

**Issue by bztd** [flathub/flathub#4889]
How can I test an extension that is in the beta branch? I have installed the extension and it does not mount when I run the package. The extension is installed on the system and configured to work with the installed package branch

package: org.lyx.LyX//stable 

extension: org.lyx.LyX.Plugin.SweaveKnitr//beta

**Comment by bbhtt** [comment]
Try adding `versions: 'stable;beta'` to the extension point, without it stable is the default.

**Comment by bztd** [comment]
@bbhtt, It works thank you.
