### ISSUE TITLE
Remove com.github.alainm23.planner

### ISSUE THREAD

**Issue by alainm23** [flathub/flathub#4905]
@barthalion  I have stopped maintaining the project and would like it to no longer be available for download.

**Comment by bbhtt** [comment]
You need to EOL it first https://github.com/flathub/com.github.alainm23.planner/pull/16

**Comment by alainm23** [comment]
Done

**Comment by bbhtt** [comment]
Then the process is done https://docs.flathub.org/docs/for-app-authors/maintenance#end-of-life 

I archived the repo. Unless something happened, builds aren't purged from the server.

**Comment by hfiguiere** [comment]
and it doesn't have a redirect.

**Comment by bbhtt** [comment]
> and it doesn't have a redirect.

@alainm23 Do you want to setup a redirect to io.github.alainm23.planify ? Looks like that one is being maintained

**Comment by hfiguiere** [comment]
That was the question 6 month agi https://github.com/flathub/com.github.alainm23.planner/pull/16#issuecomment-1656782832

**Comment by alainm23** [comment]
@bbhtt Yes please, Planify is under constant maintenance and is the next version of Planner.

**Comment by bbhtt** [comment]
Done https://github.com/flathub/com.github.alainm23.planner/commit/a5f025c4592f66eb9513b484e784feb6b2d0c1a0
