### ISSUE TITLE
Requesting temporary write access of dev.alextren.Spot 

### ISSUE THREAD

**Issue by Diegovsky** [flathub/flathub#4906]
I am one of the maintainers of [Spot](https://github.com/xou816/spot/). Due to the original author currently being in [hiatus], I would like to request temporary write access to push new updates. 

I'm currently developing Spot in [my own repo](https://github.com/Diegovsky/Spot) due to write access issues. 

[hiatus]: https://github.com/xou816/spot/issues/591

**Comment by bbhtt** [comment]
I don't think it's a good idea to switch it to a fork right now without @xou816 confirming, because the application is in their namespace.

I have no issues with giving you write access other than that.

**Comment by Diegovsky** [comment]
I understand your concern. I would prefer to keep in their namespace, but due to the way permissions are set, I can't merge new code without other maintainers approving, and I'm the only one active for now. I can merge other people's PRs though.

I'm mostly asking this because I can't reach @xou816 and there is an issue with Spotify's new api that broke the current version on flathub. While it would certainly be easier, I would like to avoid a hard fork and rebranding/renaming of the app.

Here's the issue in question: [link](https://github.com/xou816/spot/issues/689)

If you're not comfortable with the idea, I could go the hard-fork route and migrate to a new namespace.

**Comment by bbhtt** [comment]
> If you're not comfortable with the idea, I could go the hard-fork route and migrate to a new namespace.

Yes, submitting a fork separately seems to be the better idea and would give you more control. Just be sure to make the name/icon/summary distinct.

In case the original project becomes active again/you don't want to maintain a fork anymore, we can set up an EOL rebase of the the forked app on Flathub to point to the original and vice-versa. https://docs.flathub.org/docs/for-app-authors/maintenance#end-of-life

**Comment by Diegovsky** [comment]
Ok, I will be doing that then. Thank you for the directions

**Comment by Diegovsky** [comment]
@bbhtt I noticed I have write access to branches I create. Would it be alright if instead of pointint to my fork, it pointed to a different branch instead?

**Comment by Diegovsky** [comment]
I uploaded a commit that reverts back to the original repo. Hopefully, this enables development to continue from the original repo, even if in a different branch :)

**Comment by ksaadDE** [comment]
> I uploaded a commit that reverts back to the original repo. Hopefully, this enables development to continue from the original repo, even if in a different branch :)

Is there any final decisions where you guys want to develop the app? 
Recommendation: Someone of you creates a repo where all of the core devs having "administrative" access, so in case someone of you has to go inactive you can just resume or handover the torch.

**Comment by Diegovsky** [comment]
I'm trying to figure this out while xou816 is out... We could discuss this in the original repo. For now, I'm trying to publish a new version of Spot so it can be used again
