### ISSUE TITLE
Assign rights to com.enjoyingfoss.feeel repo

### ISSUE THREAD

**Issue by 12people** [flathub/flathub#4923]
I'm the developer behind Feeel, and I originally proposed the Flathub here as well.

However, it seems that the [Flathub repo](https://github.com/flathub/com.enjoyingfoss.feeel) is not linked to my Github account, but rather just to my name and e-mail.

As such, the app is not linked to my Flathub account and I can't verify the app.

Please assign me the requisite rights to the [Feeel Flathub repo](https://github.com/flathub/com.enjoyingfoss.feeel).

([Relevant Flathub Discourse discussion](https://discourse.flathub.org/t/not-seeing-my-app-under-authored-apps/6039/2))

**Comment by bbhtt** [comment]
How would I verify that you are the author of the app or a member of the Enjoyingfoss org?

The org members are hidden and all commits are made by a deleted account Miroslav Mazel.

Can you please put something up on the repo or make a commit under the current account?

**Comment by 12people** [comment]
@hfiguiere Hm, I guess not. In any case, it seems that the invitation is no longer valid. Would it be possible to resend it?

@bbhtt I hope perhaps [the thread that hfiguiere linked to above](https://github.com/flathub/flathub/pull/3671#issuecomment-1328303257) can serve as proof? I also have another app called Parlera, which is also an enjoyingfoss.com app and whose [Flathub repo](https://github.com/flathub/com.enjoyingfoss.Parlera) I do have access rights to.

**Comment by bbhtt** [comment]
Yes, should be enough. I sent you an invite. Please accept within the week.

**Comment by 12people** [comment]
Wonderful, thank you so much!
