### ISSUE TITLE
Add lua sdk support

### ISSUE THREAD

**Issue by 00pandora00** [flathub/flathub#4940]
Suggestion

hi, first of all, i don’t know if this is the place to put this request. if this is not the place to put this issue, please help me to find the correct place.

said the above, there are any plans to add lua sdk ? (the same way rust sdk is implemented)

why i ask for this?
some programs (vstudiocode, vscodium) need that sdk, and i think that allowing them get it from the system (if that is possible) Detroit the idea of flatpak a little (the sandbox part)

**Comment by hfiguiere** [comment]
the way this works is "you want it, you do it, and you'll maintain it".

There is no resource to have any other to full fill random request.

not I'm not even sure of the use case here. Lua is not Rust.
