### ISSUE TITLE
Fix verification for country-specific domains

### ISSUE THREAD

**Issue by silash35** [flathub/flathub#4943]
Hello, I live in Brazil and here they sell “.br” domains, the so-called [country code top-level domain](https://en.wikipedia.org/wiki/Country_code_top-level_domain). “.br” domains are only sold containing a category before the .br. There is no possibility of purchasing a domain like silas.br, for example.

That's why I own the domain silas.eng.br (eng, category for engineers).

silas.eng.br is NOT a subdomain of eng.br. in the same way that eng.br, com.br, org.br and others are not domains but top-level domains that contain a country code.

Now the problem: I recently had the br.eng.silas.qpdftools app approved on flathub, but when trying to verify the site asks me to put the file “org.flathub.VerifiedApps.txt” in eng.br.

I believe it should identify that eng.br is not a domain and allow me to place the file in the real domain which is silas.eng.br

**Comment by hfiguiere** [comment]
@razzeee I think that's your domain.

**Comment by hfiguiere** [comment]
I theory we shouldn't have to even know about this. 

Remove the app name (last comment), revert, remove leading `_` that prefix digits, and replace remaining `_` with `-`.

**Comment by hfiguiere** [comment]
This is the package in question https://github.com/flathub/br.eng.silas.qpdftools

**Comment by razzeee** [comment]
See https://github.com/flathub-infra/website/pull/2301 but it's on hold for now, as it needs to be checked by @barthalion

**Comment by razzeee** [comment]
Can we move this to the website issue tracker?

**Comment by hfiguiere** [comment]
Moved to https://github.com/flathub-infra/website/issues/3259

**Comment by hfiguiere** [comment]
We should keep it open until fixed.

**Comment by ikolomiko** [comment]
The issue is fixed for me, thanks everyone who has involved!

**Comment by bbhtt** [comment]
The fix sometimes causes issues when the id has 5 or more components. Please report them to https://github.com/flathub-infra/website/issues/ separately
