### ISSUE TITLE
License Model for Apps where majority of code is opensource

### ISSUE THREAD

**Issue by helloanoop** [flathub/flathub#4944]
Hi!

I am the maintainer of the opensource project [Bruno](https://github.com/usebruno/bruno)
Majority of the codebase is opensource and free and distributed under the MIT license.

We do however plan to add some addons which are paid and closed source.
Currently, our we have marked the license is marked as `<project_license>LicenseRef-proprietary</project_license>`

![image](https://github.com/flathub/flathub/assets/9350733/d8a5e8a2-ac62-4d59-ab63-4210c034e2a8)

I also see that [flathub search](https://flathub.org/apps/search?q=project) only supports two types of licenses. 
![image](https://github.com/flathub/flathub/assets/9350733/04f1bffe-4a75-40b3-b6a0-86cbbe7c7391)

I know this may not be possible, but I just wanted to check and confirm if there is a way to represent in the license that some parts of the code is opensource.

If we do not have that option, I think its good to explore the possibility of a COSS category - Commercial Open Source.

Thank you.

Reference tickets where this discussion is happening in Bruno
* https://github.com/usebruno/bruno/issues/1398
* https://github.com/flathub/com.usebruno.Bruno/issues/1

**Comment by razzeee** [comment]
Don't addons allow their own license?

Anyway, you can set multiple licenses see https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#license

**Comment by bbhtt** [comment]
Marking as solved as per above comment.
