### ISSUE TITLE
Broken Screenshots Localization

### ISSUE THREAD

**Issue by Bytezz** [flathub/flathub#4949]
Hi,
I've just noticed that on [Flathub](https://flathub.org/apps/io.github.bytezz.IPLookup) all the [AppStream](https://github.com/Bytezz/IPLookup-gtk/blob/main/data/io.github.bytezz.IPLookup.appdata.xml.in)'s screenshots are shown, even those marked with a different langauge code (`xml:lang`).
Browser sends `Accept-Language: en-US,en;q=0.5`.

Gnome-software shows all screenshots too, but `gnome-software --show-metainfo` shows only the right screenshots.

<details>
<summary>Screenshots</summary>

![Flathub screenshot n1](https://github.com/flathub/flathub/assets/25850701/9aeeb1c0-f731-4918-8f63-67a049e318b1)
![Flathub screenshot n2](https://github.com/flathub/flathub/assets/25850701/e6addeb7-90b5-4d4a-bb63-bbfcadff3016)

![Gnome-software](https://github.com/flathub/flathub/assets/25850701/e84d45b1-22ef-49aa-9139-3c981828a855)

`LC_ALL=ru_RU.utf8 gnome-software --show-metainfo`
![LC_ALL=ru_RU.utf8 gnome-software --show-metainfo](https://github.com/flathub/flathub/assets/25850701/8a60b7b0-2543-453e-9465-4be83488ebbc)
</details>

**Comment by JakobDev** [comment]
Flathub switched from `appstream-glib `to `libappstream` yesterday, which may caused this problem. Try to rebuild the Flatpak. You can do this on the [Buildbot](https://buildbot.flathub.org).

**Comment by razzeee** [comment]
Did you just notice it or do you think it changed? 

From memory I would think, that we always showed all screenshots.

Then again, I wouldn't be surprised if https://github.com/flathub-infra/website/blob/main/backend/app/utils.py#L119 broke

**Comment by Bytezz** [comment]
@JakobDev
> yesterday

I've updated the manifest at Feb 11 at 06:33am UTC.
I don't think this is the case. How long does it takes to update the screenshots?

@razzeee
> Did you just notice it or do you think it changed?

I've just added, some days ago, translated screenshots and took a look at flathub after one/two days to see those screenshots and saw that all screenshots are shown. I've never seen another app with multiple language screenshots before neither on flathub nor on gnome-software.
Sorry for report misleading wording.

> From memory I would think, that we always showed all screenshots.

Is there a plane to change it?

**Comment by razzeee** [comment]
Not sure how good it will work, as I'm not sure if the locales will match correctly, but it shouldn't be too hard to do. But will need some fallback where apps don't show any screenshots.

Showing liggt/dark Screenshots is a similar topic

**Comment by jarek-foksa** [comment]
I can observe the same problem with `<ul xml:lang="xx">` in the `<description>` (but not with `<p xml:lang="xx">`):
- https://flathub.org/apps/com.boxy_svg.BoxySVG
- https://gist.github.com/jarek-foksa/98e81ed8d49993bb5c569ed189e619c7

**Comment by jarek-foksa** [comment]
@JakobDev Thanks, I didn't realize [only `<li>` elements can have the `xml:lang` attribute](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description). Apparently this rule was not enforced until recently.

**Comment by bbhtt** [comment]
> I've just noticed that on [Flathub](https://flathub.org/apps/io.github.bytezz.IPLookup) all the [AppStream](https://github.com/Bytezz/IPLookup-gtk/blob/main/data/io.github.bytezz.IPLookup.appdata.xml.in)'s screenshots are shown, even those marked with a different langauge code (xml:lang).

The issue here is xml:lang property is missing from image tags in composed catalogue data. The app wasn't rebuilt after the switch to libappstream, I'll start a rebuild to see how things look now.

**Comment by bbhtt** [comment]
Seems solved now, flathub.org will take a while to update

![image](https://github.com/flathub/flathub/assets/62639087/78191389-0b65-420a-8d7d-c927fc377a75)

**Comment by kriptolix** [comment]
When I went to make the required changes I ended up doing a wrong sync, so I'm going to close this PR, fix the problems and then submit another one to avoid all the mess of commits that ended up going into this PR
