### ISSUE TITLE
Every new build on "com.mongodb.Compass" fails, and i don't get the issue

### ISSUE THREAD

**Issue by dominikzogg** [flathub/flathub#4964]
[Example failed build](https://buildbot.flathub.org/#/builders/7/builds/12454)

```
Run failed, some data was ignored.
Errors were raised during this compose run:
com.mongodb.Compass
  E: gui-app-without-icon
general
  E: filters-but-no-output
Refer to the generated issue report data for details on the individual problems.
Error: ERROR: appstreamcli compose failed: Child process exited with code 1
FB: Unmounting read-only fs: fusermount -uz /srv/buildbot/worker/build-x86_64-6/build/.flatpak-builder/rofiles/rofiles-D7b8ta
program finished with exit code 1
elapsedTime=264.832091
```

**Comment by bbhtt** [comment]
This was because the appdata file was missing a launchable tag @barthalion added one yesterday https://github.com/flathub/com.mongodb.Compass/commit/401d74ba9ad74be7fbdb37b419ab09a1d9a5f37c but missed the desktop suffix

I'll fix it now.

**Comment by bbhtt** [comment]
Solved

**Comment by dominikzogg** [comment]
thx

**Comment by dominikzogg** [comment]
@bbhtt I the meanwhile the builds seem to work, but the only pr, that could be merge was yours, the others are idling at "builds/x86_64 Expected — Waiting for status to be reported"

**Comment by bbhtt** [comment]
Should be fine now sometimes status checks are slow to update either due to Github or Flathub being slow.
