### ISSUE TITLE
appstream-missing-developer-name warning is broken

### ISSUE THREAD

**Issue by aleixpol** [flathub/flathub#4970]
So flathub was complaining about `developer-name-tag-deprecated` (in a warning) in the app I'm packaging. https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer

Then I thought I'd be a good citizen and port to the new API. Now it seems flathub's linter is broken and also complains, presumably because it is looking for developer_name.

https://buildbot.flathub.org/#/builders/26/builds/12488

:cry:

**Comment by ZVNexus** [comment]
Looks like the name tag is missing:
`<developer id="qgis.org">QGIS Development Team</developer>`

Error should go away once that's added, "Every developer element must have a name tag as child, which contains a translatable name for the respective developer."

```
<developer id="qgis.org">
  <name>QGIS Development Team</name>
</developer>
```

**Comment by bbhtt** [comment]
Yea indeed it has to be in the `name` child tag https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#name-summary-and-developer-name (spec also says the same thing)

https://github.com/flathub/org.qgis.qgis/pull/431/files#diff-33aed91fc2df15ede5ecb8452a941f0aebe783504d84c86e1e9ee91ea0ba2081R16
