### ISSUE TITLE
Can't submit package update: "Waiting for status to be reported"

### ISSUE THREAD

**Issue by divVerent** [flathub/flathub#4971]
I currently can't make anymore changes to my package.

- https://github.com/flathub/io.github.divverent.aaaaxy/pull/86
- https://github.com/flathub/io.github.divverent.aaaaxy/pull/87

It is stuck in "builds/x86_64 Expected — Waiting for status to be reported" status, despite having got the build success message:

```
Build [101354 successful](https://buildbot.flathub.org/#/builders/6/builds/101354)
To test this build, install it from the testing repository:

flatpak install --user https://dl.flathub.org/build-repo/84134/io.github.divverent.aaaaxy.flatpakref
```

Seems something's broken with the build check integration. Can anyone look what's going on?

I already tried adding an empty commit to retrigger, and even closing and recreating my pull request.

Also, the pages on buildbot.flathub.org take way longer to load than usual - this may have something to do with the issue. Is the build infrastructure simply down or overloaded?

Or is it just a matter of waiting a lot longer than usual? If so, I guess all is OK and I can publish tomorrow.

Thanks!

**Comment by bbhtt** [comment]
I'll merge it, the status check is being slow to update due to infra being overloaded and slow.
