### ISSUE TITLE
Github status reports not arriving

### ISSUE THREAD

**Issue by peppy** [flathub/flathub#4977]
See https://github.com/flathub/sh.ppy.osu/pull/158, I can't merge without the status report arriving but they seem quite flaky as of recent.

**Comment by bbhtt** [comment]
Yes, there's an issue with status checks. it's being looked into.

I'll merge it for you in the meantime.

**Comment by peppy** [comment]
Thank you!

**Comment by mpharoah** [comment]
I've noticed it getting slower and slower over time. When I first added FlatPak as a distribution method for my app, it was always the slowest to update, but if I opened the PR first, by the time I built on Windows, Mac, and deployed to Launchpad, COPR, and AUR, I wouldn't have to wait long for the FlatPak to also be published. Nowadays, it takes multiple hours, so I just don't even bother waiting for the Flatpak build before announcing new releases.

For what it's worth, it _does_ seem to always _eventually_ get the status update and let me merge. There's just no indication of when that will be.

**Comment by jmaibaum** [comment]
I have the same issue on the following PRs:

* https://github.com/flathub/org.kicad.KiCad/pull/278
* https://github.com/flathub/org.kicad.KiCad.Library.Templates/pull/58
* https://github.com/flathub/org.kicad.KiCad.Library.Packages3D/pull/51

I would be glad if someone could merge them, as we want to get the last 7.0.x release out the door and to users who might want to pin it, before KiCad 8.0.0 gets released in a couple of hours or days.

Thanks

**Comment by mpharoah** [comment]
Might as well post my own stalled PR here too since it seems status notifications may have finally died for good now
https://github.com/flathub/ca.parallel_launcher.ParallelLauncher/pull/27

**Comment by jmaibaum** [comment]
Thanks for merging.
