### ISSUE TITLE
Volunteer to maintain com.google.Chrome

### ISSUE THREAD

**Issue by evan-a-a** [flathub/flathub#4983]
I would like to volunteer to take over regular maintenance of https://github.com/flathub/com.google.Chrome. @refi64 [mentioned](https://github.com/flathub/com.google.Chrome/pull/261#issuecomment-1897660119) that they don't use x86 regularly and are unable to test recent updates. The Edge flatpak, which I've been maintaining for a few months, is also similar and I'd like to ensure they have functional parity with each other.

**Comment by hfiguiere** [comment]
@refi64, please ack.

**Comment by evan-a-a** [comment]
Closing, my situation has changed.
