### ISSUE TITLE
Builder bot does not tell github that the build succeded for my app

### ISSUE THREAD

**Issue by A6GibKm** [flathub/flathub#4988]
The ci at https://github.com/flathub/org.electrum.electrum/pull/61 succeeded over 24h in the past but Github won't allow me to merge it.

I would greatly appreciate if someone could merge it for me. In the long run it would be interesting to make the system more reliable as this happens rather often when the builder bot is very congested.

**Comment by bbhtt** [comment]
There's was an issue that was resolved yesterday https://github.com/flathub/flathub/issues/4977, it should work now if you rebuild

**Comment by bbhtt** [comment]
Should be fine now, status is green.
