### ISSUE TITLE
com.github.tmewett.BrogueCE workflows failing

### ISSUE THREAD

**Issue by mserajnik** [flathub/flathub#5003]
First and foremost: I am not the maintainer of (or even associated with) [com.github.tmewett.BrogueCE](https://github.com/flathub/com.github.tmewett.BrogueCE), I am merely a concerned user. I had initially opened [an issue in the application repository](https://github.com/flathub/com.github.tmewett.BrogueCE/issues/17) and talked to the maintainer about it, but we weren't able to figure it out. Since I haven't seen any further action taken that would resolve this problem since it was originally brought up months ago, I decided to do so myself.

As suggested [here](https://github.com/flathub/flathub/issues/2618#issuecomment-1782797537) I am opening a new issue about this: [workflows have been failing](https://github.com/flathub/com.github.tmewett.BrogueCE/actions) for com.github.tmewett.BrogueCE for quite a while now, from what I can see for at least a year.

As I already outlined [here](https://github.com/flathub/com.github.tmewett.BrogueCE/issues/17) it seems like `secrets.FLATHUBBOT_TOKEN` (and therefore also `GITHUB_TOKEN`) is not set, causing the workflows to fail; this is apparently not something that the repository owner can (or is even supposed to) set. But I am not sure if that is the actual problem here, as [this comment](https://github.com/flathub/flathub/issues/2618#issuecomment-964888997) (relating to an apparently similar problem with a different repository) suggests that the repository structure might also be wrong or outdated in our case.

This also means that https://flathub.org/apps/com.github.tmewett.BrogueCE has not been updated to the latest version (1.13) yet.

Thank you for looking into this.

**Comment by bbhtt** [comment]
Answered in the app repo. You can safely remove them or ignore the failed runs.

**Comment by hfiguiere** [comment]
the workflow failure happen because the repository for the flaptak has the github action from the submission, likely because it was not made against `new-pr`.

![image](https://github.com/flathub/flathub/assets/114441/cd74d189-0bbb-4713-b5da-7c408faf5f32)

You should remove it all, not just 'stale'

**Comment by mserajnik** [comment]
@hfiguiere Thank you, we already [figured it out](https://github.com/flathub/com.github.tmewett.BrogueCE/issues/17#issuecomment-1967264457) and I made a [PR](https://github.com/flathub/com.github.tmewett.BrogueCE/pull/18) that removes those workflows.

**Comment by hfiguiere** [comment]
The version is also published:
```
$ flatpak remote-info flathub com.github.tmewett.BrogueCE
BrogueCE - Brogue: Community Edition - a community-lead fork of the much-loved
minimalist roguelike game

        ID: com.github.tmewett.BrogueCE
       Ref: app/com.github.tmewett.BrogueCE/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 1.12
   License: AGPL-3.0+
Collection: org.flathub.Stable
  Download: 926.0 kB
 Installed: 1.8 MB
   Runtime: org.freedesktop.Platform/x86_64/22.08
       Sdk: org.freedesktop.Sdk/x86_64/22.08

    Commit: 7b7ca3bec16f0d11c31f45740e432fdb84a45d234115a3725aa42f1ca351e79c
    Parent: 0c52aad541b40b815b0398974936f949306dfaf188137c4b9dcd4a5039737d33
   Subject: Delete broken stale PR workflow (#15) (c629de21)
      Date: 2023-10-05 16:54:32 +0000
```

If the version number is incorrect on flathub.org is because the appstream file is incorrect.

**Comment by hfiguiere** [comment]
forget what I said. build was retriggered
