### ISSUE TITLE
Translating lists in AppStream descriptions

### ISSUE THREAD

**Issue by fpiesche** [flathub/flathub#5005]
Hi,

We've [noticed](https://github.com/flathub/io.github.theforceengine.tfe/pull/3#issuecomment-1963669259) over on io.github.theforceengine.tfe that Flathub (as well as other AppStream implementations) isn't capable of handling translated `<ul>`/`<ol>`/`<li>` tags in the `<description>` element - the `xml:lang` attribute on these is seen as valid by the linter (and thus Flathub's build infra) but the actual site displays this:
![Screenshot_20240227_235253](https://github.com/flathub/flathub/assets/393620/2fbc1484-6de4-43a4-ae6e-1f9934e28b52)

The "intuitive" fix for this would be to apply the `xml:lang` to a `<p>` wrapped around the list; however that is *not* valid as per AppStream spec.

Is this undefined behaviour in the spec, or is there a way to produce lists with translations that will render correctly?

**Comment by razzeee** [comment]
https://github.com/flathub-infra/website/pull/2647 should take care of that

**Comment by razzeee** [comment]
It's not the website, it's a libappstream bug I guess. The description in http://hub.flathub.org/repo/appstream/x86_64/appstream.xml.gz has no language tags anymore on the `ul`.

Can you raise an issue over at https://github.com/ximion/appstream/issues ?

**Comment by bbhtt** [comment]
The `xml:lang` is supppsed to be inside `li` not `ul`, probably that's the reason See https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#metainfo-translations
