### ISSUE TITLE
Scribus

### ISSUE THREAD

**Issue by brittyazel** [flathub/flathub#501]
Hey guys,

Over on the GNOME Engagement channels many of us have pushed the use of tools like Scribus for much of our layout design, i.e. the GNOME annual report, instead of tools like Inkscape. The problem is that Scribus is not hosted on flathub.

I've been in contact with the semi-official Scribus flatpak maintainer, and he has said he is ready and willing to bring Scribus to FlatHub, but he was concerned about the fact that as of right now Scribus 1.4 (stable) isn't that great to use due to super limited features, and scribus 1.5.4 (dev build leading to 1.6) is the only Scribus release worth anyone's time. He said that Flathub has a "stable only" policy, and that it was prohibiting him from bringing the 1.5 builds to Flathub. Is this the case? Can we make an exception? Technically the 1.5.x releases are full releases, they just themselves are in the unstable channel.

https://github.com/jurf/scribus-flatpak/issues/10

**Comment by barthalion** [comment]
@jurf, what makes 1.4 "super limited"?

We are not eager to add unstable releases due to poor user experience. If developers can attest to its stability then I don't see a problem.

**Comment by nedrichards** [comment]
It's up to the developer what they call a stable release. But if they don't call it stable themselves, then Flathub will tend to believe them. At the end of the day it's about getting quality apps to people. Scribus say this on their download page:

> The development branch is currently 1.5.x. It’s mainly being released for people who want to help us testing and improving Scribus, so the next stable series (1.6.x) will work well. However, as of version 1.5.1, we consider the development branch reasonably stable, so it can be used for serious work by users who accept that not all new features are already working perfectly. Features already available in the officially stable version will work much better in 1.5.1+, though.

Given that, and the fact that they offer the two versions side by side (it's not like Firefox where the beta release is hidden to normal users). I'd be inclined to accept this. *However* the word of the developer is paramount here. Flathub exists to help developers, and in cases like this, it'd be much more compelling to us if upstream are involved.

Also, fwiw there is a PR already that's being developed and it hasn't quite passed review/built perfectly: https://github.com/flathub/flathub/pull/405

**Comment by jurf** [comment]
@brittyazel eh, sorry, should’ve warned you that when asking about this I might get a notification for it. :-)

@barthalion, never really said ‘super limited’, but I consider Scribus 1.4 well… ancient. Haven’t used it in _years_. Qt 4, lacks any type of OTF support, etc. I don’t have a use case for it for me since I rely heavily on typographical features.

@nedrichards I can ask some of the devs to weigh in. IMHO having 1.5.4 on Flathub would be completely fine, if we labeled it as such – e.g. ‘Scribus (pre-release)’ or something. I personally consider it stable enough for that, and it’s quite an essential application in the open-source Linux creative suite, it’s missed on Flathub.

Anyway, they’ve been working on 1.5.x for… well, as far as I can remember.

#405 is my job, though I temporarily gave up after a variety of architectural build failures.

Sorry for the delayed reply, I didn’t have much free time.

**Comment by jurf** [comment]
Just to quote myself from #405:

> So, what now? Arch already [uses](https://www.archlinux.org/packages/community/x86_64/scribus/) 1.5.4 in the stable repositories. Personally, I would really like to see this on Flathub (not just because I invested a _tonne_ of time into it). Maybe change the label to Beta or something, to show it’s not completely stable?

**Comment by jurf** [comment]
Conversation from IRC:


> **jurf:** Hey. Would you consider Scribus 1.5.4 to be stable enough for daily use? I.e., do you think that there are enough advantages in it over 1.4.6 to consider providing it as the default one?
> **a-l-e:** no, i don't think that 1.5 should be the default.
> **a-l-e**: it depends on the context, though.
> **a-l-e**: for flatpaks, as long as they are a secondary way for installing newer / other software i think that only providing 1.5 is safe.
> **a-l-e**: for the distribution repositories, 1.5 should be marked as beta.
> **a-l-e**: almost every user should do the first project with 1.4, imo.
> **a-l-e**: except if she really needs features that are only in 1.5... (but even there, if possible, she should do a smaller project with 1.4 first) 
> **a-l-e**: personally, i've been working with 1.5 for years now and i'm happy with it. but there are parts of it that are not stable yet.
> **a-l-e**: anyway, that's only my personal point of view and i don't speak for scribus.

So yeah. I think it’s fine if we ship 1.5.4, as long as we label it as ‘Beta’. I think a lot of people will appreciate it being here. We should just emphasise that this is an exception to the rule and that Flathub isn’t for hosting unstable packages.

**Comment by nedrichards** [comment]
lgtm

**Comment by nedrichards** [comment]
https://github.com/flathub/net.scribus.Scribus
