### ISSUE TITLE
EOL io.github.dhadder3.SkiffDesktopAdw

### ISSUE THREAD

**Issue by dhadder3** [flathub/flathub#5019]
Please archive my old repository for io.github.dhadder3.SkiffDesktopAdw as the Skiff Desktop project is EOL due to the acquisition of Skiff, thank you.

**Comment by bbhtt** [comment]
Can you remove the eol-rebase and set eol message to above? It's getting rebased to yet another EOL app.

**Comment by bbhtt** [comment]
Done
