### ISSUE TITLE
Unacceptable TLS error

### ISSUE THREAD

**Issue by The-BigDaddy** [flathub/flathub#502]
#### Relevant/Useful info:
**uname -a**: Linux void 4.17.9_1 #1 SMP PREEMPT Mon Jul 23 20:12:05 UTC 2018 x86_64 GNU/Linux
**GnuTLS Version:** 3.5.19
**LibreSSL Version:** 2.7.4
**CA Certificates**: 20170717 

Hi,

So normally I've never had issues with Flatpak w/ Flathub before. I'm on somewhat of a niche Linux distro called [Void Linux](https://voidlinux.org/) that makes use of LibreSSL. I don't have a lot of things installed with Flatpak, just Krita and Slack, and when I ran `flatpak update` I got the error

    error: Unable to load summary from remote flathub: Unacceptable TLS certificate

Passing `--verbose`

    F: Opening user flatpak installation at path /home/bigdaddy/.local/share/flatpak
    F: Opening system flatpak installation at path /var/lib/flatpak
    Looking for updates...
    F: flathub:x86_64 appstream age 18446744073709551615 is greater than ttl 86400
    F: Updating appstream data for remote flathub
    F: Fetching summary file for remote ‘flathub’
    F: Failed to download optional summary
    F: Error updating: Error updating appstream2: Unable to load summary from remote flathub: Unacceptable TLS certificate; Error updating appstream: Unable to load summary from remote flathub: Unacceptable TLS certificate

I looked around in `/var/lib/flatpak`, and, where I'm assuming is suppose to be something for Flathub, in `/var/lib/flatpak/repo/refs/remotes` there's nothing. There *is* a `gpg` file called `flathub.trustedkeys.gpg` in `/var/lib/flatpak/repo`.

Other than that, I'm not 100% sure what else I would need to provide to you all to help me with my situation

**Comment by Ruedii** [comment]
I get a similar error:
`error: Failed to install org.freedesktop.Platform/x86_64/18.08: While pulling runtime/org.freedesktop.Platform/x86_64/18.08 from remote flathub: Peer failed to perform TLS handshake`

**Comment by dixonge** [comment]
still getting this - Lubuntu 18.10 - get the same whether installing from Discover or CLI

**Comment by qury** [comment]
I have the exact same issue when trying to run flatpak from behind the company firewall.
I have the firewall's cert installed, so i can browse normally but somehow flatpak does not pick this up.

**Comment by mismatso** [comment]
I had the same problem, but it was because I had been playing with my authority certificates, to install an internal CA.

To rule out this problem, I recommend reconfiguring authority certificates to ensure that all known public CAs are being considered.

`sudo dpkg-reconfigure ca-certificates`

**Comment by barthalion** [comment]
Usual checks would be testing if curl works with `curl -I https://dl.flathub.org/repo/summary.sig`, if it doesn't, trying directly against our internal load balancers with `curl -I https://front-hex.flathub.org/repo/summary.sig`. If `dl` works, it means something is misconfigured with how libsoup validates certificates; if `dl` does not work but `front-hex` does, you should ask Fastly support for clarification. If neither does, our infra is a toast or you wouldn't be able to visit GitHub to mention it here.

I don't think there's anything actionable here on our end.

**Comment by blockspacer** [comment]
> I have the exact same issue when trying to run flatpak from behind the company firewall.
> I have the firewall's cert installed, so i can browse normally but somehow flatpak does not pick this up.

same issue

 flatpak does not pick up company certs

**Comment by ahmouse15** [comment]
SOLUTION: `sudo apt install --reinstall  ca-certificates`
This should fix the issue in most cases (Thanks to [this person](https://askubuntu.com/a/1273628 for finding this)
