### ISSUE TITLE
Yuzu should be taken off of Flathub ASAP.

### ISSUE THREAD

**Issue by K4LCIFER** [flathub/flathub#5020]
Disclaimer: I am not a legal expert, nor a legal professional.

This is reposted from https://github.com/flathub/org.yuzu_emu.yuzu/issues/1463.

---

Yuzu has lost their court case against Nintendo ([source](https://www.theverge.com/2024/3/4/24090357/nintendo-yuzu-emulator-lawsuit-settlement)). The court case cites §1201(a)(2)(A) of the [Digital Millenium Copyright Act](https://www.copyright.gov/title17/92chap12.html):
> 1201. Circumvention of copyright protection systems
> (a) Violations Regarding Circumvention of Technological Measures.—(1)(A) No person shall circumvent a technological measure that effectively controls access to a work protected under this title. The prohibition contained in the preceding sentence shall take effect at the end of the 2-year period beginning on the date of the enactment of this chapter.
> (2) No person shall manufacture, import, offer to the public, provide, or otherwise traffic in any technology, product, service, device, component, or part thereof, that—
> (A) is primarily designed or produced for the purpose of circumventing a technological measure that effectively controls access to a work protected under this title;

I am concerned that continuing to offer Yuzu on Flathub puts Flathub at risk of being sued under this section.

**Comment by bbhtt** [comment]
People are working on it, we are aware.

**Comment by frantisekz** [comment]
Well, I am quite surprised by this, is yuzu now prohibited on flathub? If not, I'd like to switch the flathub repository to the archived source code from the yuzu-mirror, and keep it up2date platform-wise and up on flathub. What would the process for that @bbhtt ?

Yuzu didn't lose, they made a deal with Nintendo which prohibits the original makers from redistributing the source and the binaries, but not any other parties from doing so.

Also, if we're to cite DMCA (if flathub org resides under the US law), all emulators for modern platforms should go away, not just yuzu.

**Comment by bbhtt** [comment]
> is yuzu now prohibited on flathub

No, if the official source is gone and development has ceased, it's standard to mark it as end-of-life, meaning it won't be receiving any further updates or activity.

> I'd like to switch the flathub repository to the archived source code from the yuzu-mirror,

Switching out from official sources is against policy. The mirrors are not official in any way and belong to third party which cannot be trusted. 

It's also deceiving the people who installed the software from Flathub.

**Comment by frantisekz** [comment]
> Switching out from official sources is against policy. The mirrors are not official in any way and belong to third party which cannot be trusted.

Okay, fair enough, thanks for the explanation!
