### ISSUE TITLE
Inactive maintainer: `com.visualstudio.code.tool.fish`

### ISSUE THREAD

**Issue by JavkhlanK** [flathub/flathub#5026]
Hi, the runtime `com.visualstudio.code.tool.fish` [has been outdated for some time now](https://github.com/flathub/com.visualstudio.code.tool.fish/pull/21) and the only maintainer I know of (@gasinvein) seems to be inactive. I'd like to step up to maintain the runtime.

**Comment by bbhtt** [comment]
@gasinvein any objections here?

**Comment by gasinvein** [comment]
> @gasinvein any objections here?

No, feel free to take over.

**Comment by bbhtt** [comment]
Invite sent, I'll merge the 23.08 pr and set it to default.

**Comment by JavkhlanK** [comment]
Thanks!
