### ISSUE TITLE
Access request to org.freedesktop.Platform.VulkanLayer.MangoHud

### ISSUE THREAD

**Issue by jntesteves** [flathub/flathub#5028]
Requesting access for myself to https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.MangoHud

This was discussed with @gasinvein on Matrix on the Flathub room [permalink](https://matrix.to/#/!xFJJgxGKItHQPfstha:matrix.org/$8TO4Vx9b_VEpcBPeZiclSI-orD9-Dtg71m2wNGZEnWI?via=matrix.org&via=gnome.org&via=fedora.im) and in DM (screenshot of conversation attached below for context). This is not a takeover, there's no need to remove any current access.

![Screenshot from 2024-03-07 15-01-23](https://github.com/flathub/flathub/assets/133886/45903b6b-874e-4c0d-b9b4-a6594d710b1a)

**Comment by bbhtt** [comment]
Done.

cc @gasinvein
