### ISSUE TITLE
Requesting temporary write access of dev.alextren.Spot, take two

### ISSUE THREAD

**Issue by Diegovsky** [flathub/flathub#5035]
Some time ago, I requested access to the aforementioned app becase I was maintaining it in my own repository. It was rightly turned down for this reason (#4906).

Since then, I managed to keep updating the app in a [different branch](https://github.com/xou816/spot/tree/maintenance) still in the original repository.

Would you feel comfortable granting me ownership of the flathub repository?

**Comment by bbhtt** [comment]
Done, as long as it is using the same GitHub source, it's fine.

**Comment by Diegovsky** [comment]
Thank you very much :D
