### ISSUE TITLE
error: Failed to update org.freedesktop.Platform.Icontheme.Adwaita/x86_64/1.0: Server returned HTTP 404

### ISSUE THREAD

**Issue by hferreiro** [flathub/flathub#505]
```
$ flatpak install flathub org.mozilla.Thunderbird
Installing in system:
org.mozilla.Thunderbird/x86_64/stable flathub 109e698ef6ec
  permissions: ipc, network, pulseaudio, x11, dri
  file access: home:ro, xdg-download, xdg-run/dconf, ~/.cache/thunderbird:create, ~/.config/dconf:ro, ~/.thunderbird:create
  dbus access: ca.desrt.dconf, org.a11y.*, org.freedesktop.Notifications
Updating in system:
org.freedesktop.Platform.Icontheme.Adwaita/x86_64/1.0 flathub 8fe112097924
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6       flathub f5b764620d7b
org.freedesktop.Platform.ffmpeg/x86_64/1.6            flathub e01955d7feef
Is this ok [y/n]: y
Updating: org.freedesktop.Platform.Icontheme.Adwaita/x86_64/1.0 from flathub
error: Failed to update org.freedesktop.Platform.Icontheme.Adwaita/x86_64/1.0: Server returned HTTP 404
```

```
$ flatpak --version
Flatpak 0.99.3
```

**Comment by Zlopez** [comment]
I had the same issue with `org.gnome.Sdk` package. But it looks like flathub is only unable to handle current load. I don't know why it is responding with error 404. It should be something like 408 (Request timeout) or better 503 (Service Unavailable).

**Comment by bilelmoussaoui** [comment]
As far as I know. Flatpak now uses the icon theme of the host. So the icon themes were removed. Adawaita too. You have to remove it manually I think.

**Comment by hferreiro** [comment]
Removing it manually still complained about `org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6` and `org.freedesktop.Platform.ffmpeg/x86_64/1.6`. It was fixed by removing them too. Later, they were installed from the gnome repo as dependencies of Thunderbird.

**Comment by osirase** [comment]
Just in case there are other people stuck on this as nooby as I am, you need to remove these things within flatpak. For me I had to remove these, pay attention to exactly what flatpak says it can't update so you don't accidentally remove the wrong thing.

`flatpak remove org.freedesktop.Platform.ffmpeg`

`flatpak remove org.freedesktop.Platform.VAAPI.Intel//1.6`

`flatpak remove org.freedesktop.Platform.Icontheme.Adwaita`
