### ISSUE TITLE
Adding net.veloren.airshipper and net.veloren.veloren maintainers

### ISSUE THREAD

**Issue by jiminycrick** [flathub/flathub#5055]
Hi!

I'm one of the developers of Veloren (airshipper is the launcher for Veloren). The Airshipper and Veloren Flatpaks are out of date and the current maintainer is no longer able to maintain it consistently.

Would it be possible to add a few members of our development team as maintainers?

The users to add as maintainers:
@imberflur
@xMAC94x
@veloren-bot

Thanks!

**Comment by bbhtt** [comment]
I couldn't find a way to verify yours and the bot account as part of the project. Is the bot really needed? Let me know if there is a way like member/push activity etc.

Added the other two persons.

**Comment by jiminycrick** [comment]
The bot account is so we can set up automatic updates with our CI. We do our development over on GitLab. The users I linked above correspond to the following gitlab users who are both maintainers of Veloren and Airshipper:
https://gitlab.com/Imbris
https://gitlab.com/xMAC94x

The list of maintainers for our repositories can be found here: https://gitlab.com/groups/veloren/-/group_members

@xMAC94x runs a lot of our infrastructure and setup the @veloren-bot account. I'll ping both of them over on discord and ask them to comment here

**Comment by bbhtt** [comment]
The users are fine, I added them.

Need something to connect the Github account for the bot with the Gitlab account or maybe make it a member of the Github org for veloren.

**Comment by jiminycrick** [comment]
Ah I misread your comment. My account on gitlab is https://gitlab.com/jiminycrick but I am not a maintainer and don't need to be added to the flatpaks. I pinged @xMAC94x on discord so he should be able to provide more details about the @veloren-bot account soon

**Comment by xMAC94x** [comment]
Hi :)

The @veloren-bot  is already a member of https://github.com/veloren
I am unaware of any bridges between gitlab and github. But we would like to use some seperate user for our CI, to not depend on a singles person api-token. Thus the bot account

**Comment by bbhtt** [comment]
Can't see it, is it public?

![Screenshot_20240316_003701_Firefox Nightly.jpg](https://github.com/flathub/flathub/assets/62639087/0ae2e7a5-2352-4ca7-8d88-72a9b6cd7456)

**Comment by xMAC94x** [comment]
@bbhtt  It seems like github messes things up here. On the personal page its shown, but on the public veloren page it isn't.... I just updated it, didn't knew that there are private memberships
