### ISSUE TITLE
The overlay on the flatpak version of steam doesn't work. 

### ISSUE THREAD

**Issue by Abdulsarhan** [flathub/flathub#5056]
The steam overlay works just fine on the native steam but on the flatpak steam, the overlay doesn't work. 

1 - The steam overlay is enabled globally, and for every game that I tested. 
2 - The overlay doesn't work regardless if it's a native game or if it's running through proton. 
3 - I made sure that the overlay key is bound to shift+tab. And that's the key combination that I used to try to open the overlay.

System:
I am on Arch Linux.
Kernel: Linux arch 6.7.9-arch1-1 
My system is fully up to date.

**Comment by hfiguiere** [comment]
Like https://github.com/flatpak/flatpak/issues/5727

Reporting it to the package is probably more appropriate:

https://github.com/flathub/com.valvesoftware.Steam/issues
