### ISSUE TITLE
Archive `org.mpdevil.mpdevil`

### ISSUE THREAD

**Issue by SoongNoonien** [flathub/flathub#5066]
Hi!
Today `de.wagnermartin.Plattenalbum` (#5027) has been added to flathub. It should replace `org.mpdevil.mpdevil`. I think the usual procedure is to set `org.mpdevil.mpdevil` as end of life and eventually mark it as archived at github. I've tried to mark it as end of life (https://github.com/flathub/org.mpdevil.mpdevil/pull/9) but the upstream manifest doesn't pass the new tests. Is there a way to skip these tests or do I have to create a new branch upstream which fixes the errors? Or is there another solution I haven't thought of yet?

**Comment by bbhtt** [comment]
Please try to add a patch to make it pass. Should be simple.

**Comment by SoongNoonien** [comment]
Ok, thanks! It should be fixed now.

**Comment by bbhtt** [comment]
archived
