### ISSUE TITLE
Support request: Provide push privileges to WPS-office

### ISSUE THREAD

**Issue by NL-TCH** [flathub/flathub#5067]
As the old maintainer stated, we are allowed to request push permissions to the WPS office repo.
https://discourse.flathub.org/t/new-wps-office-maintainer-wanted/1321

I want this permissions to merge some PR's and keep WPS up to date (fixes quite some security problems in the process)

User: NL-TCH
Permission: Push (merge + commit)
repo: https://github.com/flathub/com.wps.Office

*moved from https://github.com/flatpak/flatpak/issues/5734

**Comment by bbhtt** [comment]
Hi @gasinvein please ack.

Do you have any previous involvement with Flatpak/Flathub?

**Comment by NL-TCH** [comment]
@bbhtt, the post was 3 years old and no gitub activity for 3 months, i'm curious if you'll get a reply.

No development involvement, but i do have 3+ years as in usage involvement

**Comment by gasinvein** [comment]
> Hi @gasinvein please ack.

I don't object, although I believe WPS Office, being a rather popular app, should be transferred to someone interested in prolonged maintenance of the flatpak (thus I've posted the request on Discourse).

**Comment by NL-TCH** [comment]
I completely agree!
But in the mean time i think i could fix some github issues and some flathub comments of WPS office.

My perception on the current situation:

```mermaid
flowchart TD
    A(Flatpak isn't updated) --> B(New user sees WPS flatpak)
    B --> C(User loses interest because of issues and old version)
    C --> A
```

**Comment by bbhtt** [comment]
Looks like @barthalion added @mlawson27 as a maintainer to WPS office yesterday. I'd consider the issue of not having a maintainer to be solved.

But please don't hesitate to send PRs to it or reach out, we are open to adding more people if necessary.
