### ISSUE TITLE
Remove org.featherwallet.Feather

### ISSUE THREAD

**Issue by tobtoht** [flathub/flathub#5073]
I'm the lead developer of this software (check my profile). We now ship an official Flatpak [using our own infrastructure](https://docs.featherwallet.org/guides/linux#flatpak). The Flathub package is unmaintained.

See [rationale](https://github.com/feather-wallet/feather/issues/47#issuecomment-1657344631) and a [relevant comment](https://github.com/feather-wallet/feather/issues/47#issuecomment-1657382474) from the Flathub package maintainer.

**Comment by bbhtt** [comment]
You have to mark it as end-of-life https://docs.flathub.org/docs/for-app-authors/maintenance#end-of-life

**Comment by tobtoht** [comment]
I don't have commit access to [flathub/org.featherwallet.Feather](https://github.com/flathub/org.featherwallet.Feather). Can it be granted?

Or, @vorot93 would you be able to do this?

**Comment by bbhtt** [comment]
> I don't have commit access to [flathub/org.featherwallet.Feather](https://github.com/flathub/org.featherwallet.Feather). Can it be granted?

Sure
