### ISSUE TITLE
Build system is way too slow.

### ISSUE THREAD

**Issue by sgehrman** [flathub/flathub#5075]
3 hours now and nothing is happening.  I push a pull request for my app and it takes hours.

Why is your build system so slow?  Please fix.

**Comment by guihkx** [comment]
There's a ~3 hour delay to publish the app, and it's intentional, as far as I know.

Perhaps this information could be added to the documentation (unless it's already documented and I just couldn't find it).

**Comment by razzeee** [comment]
It's mentioned here https://docs.flathub.org/docs/for-app-authors/maintenance#buildbot
