### ISSUE TITLE
No maintainer activity for com.discordapp.DiscordCanary

### ISSUE THREAD

**Issue by Nik-mmzd** [flathub/flathub#5079]
There is no maintainer activity for about last half a year. Package uses legacy (22.08) freedesktop runtime, maintainer ignores the [issue](https://github.com/flathub/com.discordapp.DiscordCanary/issues/97). I tried contacting maintainer using metadata-provided email, got no response.

I can volunteer myself to maintain the package (at least, update the runtime and startup scripts to mirror changes in com.discordapp.Discord)

**Comment by bbhtt** [comment]
They are active in the community, maybe just busy? 


> I can volunteer myself to maintain the package 

Hi, @refi64, are you fine with this?

**Comment by refi64** [comment]
I saw the email but it was during the work week & I hadn't gotten around to it yet. Tbh I've been considering asking if anyone else wanted to maintain Canary because I don't really use it anymore; if @Nik-mmzd wants to instead then it's fine by me.

**Comment by bbhtt** [comment]
Invite sent, I posted some comments on the runtime update PR.
