### ISSUE TITLE
Add Brave employees as collaborators to "com.brave.Browser"

### ISSUE THREAD

**Issue by rany2** [flathub/flathub#5090]
Please add as collaborators for [com.brave.Browser](https://github.com/flathub/com.brave.Browser):

- @fmarier
- @oajara
- @wknapik
- @mihaiplesa

I'll remain as a collaborator for the time being as they aren't fully committed yet.

**Comment by bbhtt** [comment]
@fmarier already has access, invites have been sent for the rest.

**Comment by rany2** [comment]
@bbhtt Could you resend the invite for @wknapik? He was on vacation when the invite was sent and so it just expired.

**Comment by bbhtt** [comment]
Sent again.
