### ISSUE TITLE
Add "networkException" as collaborator to "com.github.Eloston.UngoogledChromium"

### ISSUE THREAD

**Issue by rany2** [flathub/flathub#5097]
He's an admin in @ungoogled-software. We're asking to increase the chances of manual verification to work.

**Comment by rany2** [comment]
CC @networkException

**Comment by bbhtt** [comment]
It won't work, do you need access anyways?

**Comment by rany2** [comment]
Well, he doesn't _need_ access but seeing that he already has admin access to the org it wouldn't hurt.

**Comment by bbhtt** [comment]
Done
