### ISSUE TITLE
Request for assistance fixing LTS builds for `org.qgis.qgis`

### ISSUE THREAD

**Issue by mfisher87** [flathub/flathub#5108]
Hello friends,

I currently use QGIS from Flathub and would really like to have the latest LTS version available. I'm also an author of the [QGreenland](https://qgreenland.org) project, for which we recommend the latest QGIS LTS, so I'm hoping this update will also help our users out!

However, the repository currently has some issues with the way the LTS build is set up:

* In this PR, @bbhtt kindly pointed out the issue, incorrect branch name: https://github.com/flathub/org.qgis.qgis/pull/396
* In this issue, @neluji kindly provided a step-by-step breakdown of how to address the root cause: https://github.com/flathub/org.qgis.qgis/issues/329

I'd like to help out with this in any way I can, but as a non-maintainer, I cannot create a new branch on the repository or propose such with a PR. Can someone please advise me on next steps?

I'm willing to become a maintainer of this repository, but have no affiliation with the upstream project nor experience as a Flathub maintainer. I do have experience as a Conda Forge maintainer so I feel I have some chance of not messing things up too badly ;)

**Comment by bbhtt** [comment]
Applications aren't supposed to use branches other than `master` and `beta`, maybe the maintainer can make LTS available on master and move the current version from master to beta?

Any random branch won't work.

**Comment by mfisher87** [comment]
Thanks for your response @bbhtt!

@neluji suggested `stable/lts`, as `stable/*` is mentioned in the [maintenance docs](https://docs.flathub.org/docs/for-app-authors/maintenance/#the-repository), but it isn't very clear to me what the intended use is. Can you link me to documentation that might provide more context on this?

**Comment by bbhtt** [comment]
Those won't work, you can only publish a build via `master` and `beta` for applications

They are marked as protected only on GitHub because at some point we were thinking of changing the default git branch from `master` to either `main` or `stable`. But that never happened.

**Comment by mfisher87** [comment]
Thanks so much for the context!

**Comment by mfisher87** [comment]
If there were a need for more than two build maturities, e.g. `lts`, `stable`, and `beta`, is there a way to support this?

**Comment by bbhtt** [comment]
No there are currently no plans to allow multiple branches for applications. There's no way to show them on the website, most desktop software stores cannot handle this well, cli confuses people if there are multiple versions available, there are costs to running CI and hosting/storage.

They used to be allowed but apps started ab(using) them, so they are no longer allowed.

**Comment by bbhtt** [comment]
Looks like there are no `beta` branches, for qgis, you can also do the opposite and push LTS to `beta` and keep master as is.

**Comment by bbhtt** [comment]
You can see https://github.com/flathub/flathub/issues/4849#issuecomment-1887722279 for an example on how multiple branches confuses software stores.

**Comment by bbhtt** [comment]
Another options is to submit the LTS build as `org.qgis.qgis-lts` if the maintainer wants. THis might need patches to modify the application ID bus names etc.

**Comment by mfisher87** [comment]
Awesome, thanks again for the additional context!

**Comment by sonicnkt** [comment]
> Another options is to submit the LTS build as `org.qgis.qgis-lts` if the maintainer wants. This might need patches to modify the application ID bus names etc but still might cause confusion on the stores due to same icon etc.

I think this would be the best solution if flathub limits the channelss to standard and beta.
Having LTR on beta would make no sense and moving the stable to beta would cause even more confusion as you would essentially downgrade users which would result in projects files not opening anymore.

The LTR version is a quite established name. Having the same icon should not be an issue if the name clearly indicates the version : "QGIS Desktop" vs" QGIS Desktop - LTR" .

This would also have the benefit to have both version easily installed side by side. Something that is not that unusual imo.
For work related projects i use the LTR since that is the version we deploy at the office for more stability. Sometimes i want to play arround with the latest features though.
