### ISSUE TITLE
Archive old Decibels manifest (com.vixalien.decibels)

### ISSUE THREAD

**Issue by cassidyjames** [flathub/flathub#5116]
Pending:
- [x] https://github.com/flathub/flathub/pull/5087
- [x] https://github.com/flathub/com.vixalien.decibels/pull/6

**Comment by cassidyjames** [comment]
This is good to go.

**Comment by bbhtt** [comment]
It needs to build fully before archiving otherwise the build will fail if repo becomes read only

**Comment by bbhtt** [comment]
Done
