### ISSUE TITLE
Verification of Apps

### ISSUE THREAD

**Issue by BeverlyCode** [flathub/flathub#5119]
Atm it depends on uploading a verification file to the domain of the reverse dns system used by the app.

How about you allow me to verify it some other way like via the github account its pulled from?

At the moment the current method doesn't work for me and changing the domain used in the reverse dns system seems like a worse option than putting verification files in all the domains.

It's a bit of a pain. I could verify them via the domains, but it would be nice if there was other options.

**Comment by bbhtt** [comment]
> At the moment the current method doesn't work for me 

You should've been careful when submitting the application when it is repeated several times on the PR checlist and in the docs page why choosing the right ID matters.

> How about you allow me to verify it some other way like via the github account its pulled from?

This will work if you have a `com.github` or `io.github` app id. You are verifying that you own the domain used in the app id there's no other way around this.

**Comment by hfiguiere** [comment]
> At the moment the current method doesn't work for me

how come?

**Comment by razzeee** [comment]
Change your jekyll config
https://github.com/jekyll/jekyll/issues/7917#issuecomment-560165639
