### ISSUE TITLE
Some advice on re-formatting

### ISSUE THREAD

**Issue by BeverlyCode** [flathub/flathub#5127]
# 1

https://flathub.org/apps/com.voxdsp.AstroImpact

This app, can you explain the 35 char title limit and why that length is vital? Some of my apps like this one already have a fairly concise summary.

Could maybe someone suggest how this could be shortened and improved?

If I shorten it to "A multi-player space game" it would seem to simplistic, you could have the appstore looking a bit spammy with lots of apps saying pretty much the same generic thing.

---
# 2

Also here it says "Don't start with an Article" https://flathub.org/apps/com.voxdsp.Snowling and here https://flathub.org/apps/com.voxdsp.Snowboarder
Any suggestions as to how to reformat that, or do you think it's actually fine and was wrongly flagged as it's already seeming pretty concise of a description.

Also I think asking people to take screenshots with fade around the border is a bit... well you ask people not to do that with the icon but to do it with the screenshot. My screenshots are all taken on Linux using the XFCE Desktop, I don't have fade on my window borders out of preference lol and as such I wont be providing screenshots with fade around the border. - I think this request is a little odd, I understand some window managers may have more "modern" appearances that may fit better with the localised appstore software but - and that having programmatic shadow would be harder in this respect because most screenshots on vanilla Ubuntu or Fedora would have shadow baked into them and that would be a pain to manually remove. 

---
# 3

https://flathub.org/apps/com.voxdsp.VoxelPaintPro

This app is just over 35, but still very concise, probably fine to leave it as-is?  I know "!" is considered bad formatting but 🤷 to be fair every font renderer supports the exclamation mark. Although it is extraneous/superfluous. It also conveys a sentiment of words in one character.

---
# 4

https://flathub.org/apps/xyz.woxel.Woxel

Again here I am slightly over 35 but I would suggest it's not a big deal? It's already concise and informative?

---

App tumbs overview
![image](https://github.com/flathub/flathub/assets/118085961/cadddd29-f138-43e3-b1f1-b90351b6e1b7)

---

Correct me if I am wrong with any assumptions, I ask as I am hoping to learn more about these restrictions and why they are in place. 🙇

**Comment by bbhtt** [comment]
The 35 character limit is mostly to prevent too long and wordy summaries. It's supposed to be a short and catchy one-liner to hook people into the app. You don't need "akin to $other game" in summaries, it should stand out on its own.

`Defend the planet from asteroids!` or `Bowling game of luck` seems a good place to start for me, but I'll defer to @bertob or @cassidyjames to come up with better suggestions.

**Comment by bbhtt** [comment]
Seems solved now
