### ISSUE TITLE
Consider adding <developer_name> to searchable parameters

### ISSUE THREAD

**Issue by BeverlyCode** [flathub/flathub#5128]
I noticed that once verified you can search the name of the verified dns to find other apps of the same dns.

The problem in my case if I use a few different dns, but primarily voxdsp.com

On Snapcraft I can easily get a list of all my apps using two methods:
https://snapcraft.io/publisher/voxdsp
https://snapcraft.io/search?q=voxdsp

The only way I could achieve this on Flathub is if you index the `<developer_name>` string as a search parameter, that way I can set all my apps to "James William Fletcher" and get all my apps listed in one search result via that string.

Unless there is already a better way, maybe I can specify custom search tag/keywords in the appdata.xml file?

**Comment by razzeee** [comment]
https://flathub.org/apps/collection/developer/James%20William%20Fletcher/1
