### ISSUE TITLE
Waiting for an update

### ISSUE THREAD

**Issue by alexkdeveloper** [flathub/flathub#5129]
The manifest of the com.github.alexkdeveloper.recorder application was updated 4 days ago, but it is still under pending.

**Comment by bbhtt** [comment]
The last 2 builds failed due to the server having some connection issues. I started a rebuild.

**Comment by alexkdeveloper** [comment]
After a successful build, the application is added to the list of unpublished builds and sent for publication after about four hours.

**Comment by bbhtt** [comment]
Should be fixed now https://buildbot.flathub.org/#/builders/6/builds/112151
