### ISSUE TITLE
New contributor to GIMP repository

### ISSUE THREAD

**Issue by Jehan** [flathub/flathub#5131]
Hello!

I would like to request to add @brunolopesdsilv as a new contributor to GIMP flatpak: https://github.com/flathub/org.gimp.GIMP/

Thanks!

**Comment by brunolopesdsilv** [comment]
> Hello!
> 
> I would like to request to add @brunolopesdsilv as a new contributor to GIMP flatpak: https://github.com/flathub/org.gimp.GIMP/
> 
> Thanks!

Thanks 🫂

**Comment by bbhtt** [comment]
Added

**Comment by Jehan** [comment]
Thanks @bbhtt !
