### ISSUE TITLE
Please add as maintainer for org.clementine_player.Clementine

### ISSUE THREAD

**Issue by sfalken** [flathub/flathub#5139]
I've just issued a PR to update Clementine to the latest KDE-5.15 runtime (Upstream hasn't ported to Qt6 yet), and I don't mind babysitting this package, to make sure it stays up and running.

https://github.com/flathub/org.clementine_player.Clementine/pull/132

**Comment by bbhtt** [comment]
@FakeShemp do you have anything against this?

**Comment by sfalken** [comment]
Given as the maintainers appear to be responsive, I am perfectly fine with not being accepted for this, it's just built against a very old runtime currently.

**Comment by FakeShemp** [comment]
I have no objections at all.

**Comment by bbhtt** [comment]
Added, please fix the issue in the above PR before merging.

**Comment by Justinzobel** [comment]
This PR still hasn't been merged. Can @sfalken and I please be added as maintainers, thank you.

**Comment by bbhtt** [comment]
sfalken has access I added you.

**Comment by Justinzobel** [comment]
Thank you!
