### ISSUE TITLE
Displaying Image Captions on the website

### ISSUE THREAD

**Issue by mrbid** [flathub/flathub#5141]
Has anyone got any examples of image captions that are decent? I am not sure it's a good look, I only set my image captions because it was a requirement - could I have just included the caption tags and left the captions empty? _(I would prefer this to the caption text below the image making my app page look dumb lol, and now I have to re-update all my apps to fix this, more wasted time, more load on build system)_

I don't think people care to read image captions to be honest with you lol, I can't think of any good use case of what to write in them other than "Appname Screenshot".

"This is a screenshot of the main software"

"This is a screenshot of the menu dialog"

"This is a screenshot of a 3D game containing game characters"

Henrik Ibsen: "A picture is worth a thousand words"

lol seriously wtf

**Comment by bbhtt** [comment]
https://flathub.org/apps/org.kde.krita

>  could I have just included the caption tags and left the captions empty

It'll trigger a warning from the linter, if/when we decide to promote this to an error your build will fail.

>  I can't think of any good use case of what to write in them other than "Appname Screenshot".

Describe the screenshot in a short sentence.

**Comment by bbhtt** [comment]
The quality guidelines doesn't place too much restrictions on captions https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#image-captions as long as it is relevant and meaningful it should be fine.

>  Flathub is going to have an appstore littered with dumb comments on screenshots 

We will figure out what to do when that happens.

**Comment by razzeee** [comment]
Captions are waaaaay more important. But as said here, they are not required - but it's the right thing to do, as they will factor into the discoverability of your app and are important for people that depend on a11y.
