### ISSUE TITLE
Cannot add flathub repo | SSL peer certificate or SSH remote key was not OK |Debian 12 

### ISSUE THREAD

**Issue by Gubble89** [flathub/flathub#5144]
I executed the following commands on my up-to-date Debian 12 machine: 

`sudo apt install flatpak`
`sudo apt install gnome-software-plugin-flatpak`
`flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo`

And I get the following error:

`error: Can't load uri https://dl.flathub.org/repo/flathub.flatpakrepo: While fetching https://dl.flathub.org/repo/flathub.flatpakrepo: [60] SSL peer certificate or SSH remote key was not OK
`

Any idea why this is happening? Connecting a different mirror does not work 

Flatpak version: 1.14.4
Is installed: Yes

**Comment by Gubble89** [comment]
It kept happening. Fixed by switching distro

**Comment by peiyuanix** [comment]
The same error. Both Ubuntu 22.04 and Ubuntu 24.04.

**Comment by bbhtt** [comment]
> The same error. Both Ubuntu 22.04 and Ubuntu 24.04.
> 
> UPDATE: For me, it's a problem of system clock/datetiem. I fix it by adjust system datetime.
> 
> Refer to: https://groups.google.com/g/linux.debian.bugs.dist/c/xvpaQkxCM1Y

Please open a new issue.

**Comment by prayer7777777** [comment]
> The same error. Both Ubuntu 22.04 and Ubuntu 24.04.同样的错误。Ubuntu 22.04 和 Ubuntu 24.04 都可用。
> 
> UPDATE: For me, it's a problem of system clock/datetiem. I fix it by adjust system datetime.更新：对我来说，这是系统时钟/日期的问题。通过调整系统日期时间来修复。
> 
> Refer to: https://groups.google.com/g/linux.debian.bugs.dist/c/xvpaQkxCM1Y请参阅：https://groups.google.com/g/linux.debian.bugs.dist/c/xvpaQkxCM1Y
Me too.
