### ISSUE TITLE
Add "brave-builds" as collaborator to "com.brave.Browser"

### ISSUE THREAD

**Issue by rany2** [flathub/flathub#5154]
Brave is integrating the Flatpak into their CI and needs to allow the @brave-builds user access to the repository. 

CC @oajara

**Comment by bbhtt** [comment]
Making the automated account's membership to the Brave Github org would be nice and help me verify.

**Comment by rany2** [comment]
@bbhtt Look at https://github.com/brave/brave-core/pull/22900, it shows it as collaborator.

**Comment by bbhtt** [comment]
Invite sent to @brave-builds
