### ISSUE TITLE
Define Stable Package

### ISSUE THREAD

**Issue by hydrian** [flathub/flathub#5155]
What's Flatpak's policy on stable beta software? Does it truly require a stable release?

I want to submit a package that isn't being developed anymore and it was left with only a beta release but the software runs quite stablely. It is a fully open source but the source code maintainer is unresponsive and hasn't updated the code since March of 2017.  I'm assuming it has been abandoned. 

The software is CStitich (https://cstitch.sourceforge.net/). It is very niche software and is not likely to get a new maintainer anytime soon. 

The software as is, is a pain the butt to build because of the incomplete build scripts and poor documentation. It also uses some aging QT5 requirements that newer systems may not have. This makes it a prime candidate for Flatpak packaging. 

Do I even try to submit it to Flathub for approval?

**Comment by bbhtt** [comment]
Generally speaking, software with dead or inactive upstreams when the submission is being made, should be avoided.

It doesn't help if it has to be EOL-ed in a year or so because a change in runtime broke something and there is no one to fix the issue. You have to update the runtime at least once every two years, because old runtimes get EOL-ed.

> It also uses some aging QT5 requirements that newer systems may not have. 

If it needs EOL runtimes, then we won't accept it.

> This makes it a prime candidate for Flatpak 

You can package it or host your own repository https://docs.flatpak.org/en/latest/hosting-a-repository.html

**Comment by hfiguiere** [comment]
> Generally speaking, software with dead or inactive upstreams when the submission is being made, should be avoided.

Sometime that's actually a good way to ship old software. The expectation is that the submitter maintains the package. And if you need to patch it, so be it.

Stable mean that it's not a nightly of development build. That's not the purpose of Flathub to ship development snapshots.

Note that Qt 5.15 is still shipped by supported runtime so I don't see what is the problem you are alluding to.

**Comment by hydrian** [comment]
> > Generally speaking, software with dead or inactive upstreams when the submission is being made, should be avoided.
> 
> Sometime that's actually a good way to ship old software. The expectation is that the submitter maintains the package. And if you need to patch it, so be it.
> 

This was my general feeling. Flatpak is a great way to package legacy software. Flatpak constraints the possible less than secure application and keeps the aging dependancies away from the core system. As I said before, it also helps with difficult build process too.

**Comment by bbhtt** [comment]
Most of the time it gets immediately abandoned after some time of submission. If you want to patch it and maintain it sure but not sure how much it can be maintained with a dead upstream.

If it starts depending on EOL runtimes, the website, local software clients and cli will start showing warnings, means a big chunk of people will not use it anymore.

KDE also moved away from Qt5, Qt5 will not get new runtimes after 5.15-24.08.

**Comment by hydrian** [comment]
I was planning on maintaining the package.  My wife has been looking for a piece of software like Cstitich. 

Unfortunately, I'm not a QT dev, maintaining the upstream source isn't possible for me. But I'm more than comfortable with debugging make scripts.

**Comment by bbhtt** [comment]
The assumption that it'll continue to work, doesn't quite work unless you are using EOL runtimes where nothing gets changed and no updates are made.

A supported runtime will receive updates, and you sometimes need to fix or add dependencies, fix build issues related to it.

If you want to do that, submit it.
