### ISSUE TITLE
Allowance for both X11 and Wayland for RetroDECK

### ISSUE THREAD

**Issue by XargonWan** [flathub/flathub#5164]
Greetings, I am requesting the allowance for having both X11 and Wayland on RetroDECK.
RetroDECK is including a selection of components (suc ash emulators) and different components require different permission to work together, in this case if we don't add both Wayland and X11 it won't work correctly.

Removing Wayland will break basically all the modern Linux distrubtions, while removing X11 will break it for SteamOS as it's still using X11.

[Related build](https://buildbot.flathub.org/#/builders/37/builds/14155)
```
flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions manifest net.retrodeck.retrodeck.yml
 in dir /srv/buildbot/worker/build-x86_64-2/build (timeout 1200 secs)
 watching logfiles {}
 argv: b'flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions manifest net.retrodeck.retrodeck.yml'
 using PTY: False
{
    "errors": [
        "finish-args-unnecessary-xdg-config-access"
    ],
    "warnings": [
        "finish-args-contains-both-x11-and-wayland"
    ],
    "message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}
program finished with exit code 1
elapsedTime=0.671030
```

Thanks in advance.

**Comment by hfiguiere** [comment]
It's a warning. Nothing to do.

**Comment by hfiguiere** [comment]
> Removing Wayland will break basically all the modern Linux distrubtions,

This is actually false.

**Comment by XargonWan** [comment]
> > Removing Wayland will break basically all the modern Linux distrubtions,
> 
> This is actually false.

But that it's what actually happened in our testing grounds.

**Comment by XargonWan** [comment]
> It's a warning. Nothing to do.

Right, I see the blocking error is actually "finish-args-unnecessary-xdg-config-access", but I believe that this was already sorted out on the previous update.
