### ISSUE TITLE
Add as maintainer for net.opentabletdriver.OpenTabletDriver

### ISSUE THREAD

**Issue by jamesbt365** [flathub/flathub#5165]
Currently no core developers of OpenTabletDriver actually have any permissions on the Flatpak package, currently both @InfinityGhost and @X9VoiD (the main developers of OpenTabletDriver) are rather busy currently so I'm not sure they'll be able to contribute to the Flatpak at this time but ideally they should have access to the repository. With the knowledge I have its safe to assume they didn't receive an invite, see OpenTabletDriver/OpenTabletDriver#3265.

For now could me and @gonX (Current Maintainer of the AUR package alongside some of our official documentation at https://opentabletdriver.net) receive an invite.

I have not asked gonX if he would like permissions yet, but considering his experience with maintaining OpenTabletDriver as is alongside writing documentation, one of the current weaknesses of the current Flatpak package.

Reasons for attempting to gain write access myself is because I'm also a core contributor to the upstream application, I have written docs, currently mainly spend my time implementing new support for tablets and providing support for users within our official Discord server.

If a package that practically supports most distros exists for our application then we want to make sure that its well maintained, the current state isn't satisfactory and I'm not happy with the current state of the documentation & the scripts used.

**Comment by bbhtt** [comment]
Invite sent to @gonX @jamesbt365 @InfinityGhost @X9VoiD

CC @first-storm

**Comment by first-storm** [comment]
> Invite sent to @gonX @jamesbt365 @InfinityGhost @X9VoiD
> 
> CC @first-storm

Thanks alot
