### ISSUE TITLE
[Repo Permissions] Enable pull request auto merge for com.brave.Browser

### ISSUE THREAD

**Issue by rany2** [flathub/flathub#5171]
Brave is asking for the following permission to be granted to them, `enablePullRequestAutoMerge`. They are integrating the Flatpak into their release system and they got this error when trying to enable auto-merge:

`GraphQL: Pull request Auto merge is not allowed for this repository (enablePullRequestAutoMerge)`

CC @oajara @mihaiplesa

**Comment by bbhtt** [comment]
Enabled, note that it will still require the status checks to be green.
