### ISSUE TITLE
EOL beta branch for ru.linux_gaming.PortProton

### ISSUE THREAD

**Issue by Boria138** [flathub/flathub#5190]
Since this is my first application in flathub I was not quite sure how everything works and created a beta branch for testing updates, but later found out that test builds are enough for me, and maintaining two branches instead of one only wastes time, on the advice of the flathub forum I open an issue here to remove the beta branch

**Comment by bbhtt** [comment]
See https://docs.flathub.org/docs/for-app-authors/maintenance#end-of-life we don't remove the beta branch because it can be useful in the future and it preserves the git history of the branch. You can just EOL it following the instructions above.
