### ISSUE TITLE
Please add upstream author to org.rncbc.qsynth

### ISSUE THREAD

**Issue by pedrolcl** [flathub/flathub#5193]
@rncbc (a.k.a Rui Nuno Capela) is the upstream author of [org.rncbc.qsynth](https://flathub.org/es/apps/org.rncbc.qsynth) but he doesn't have write permission on the [flathub repository](https://github.com/flathub/org.rncbc.qsynth). Please add him as a collaborator. Thanks.

**Comment by hfiguiere** [comment]
Invite sent.
