### ISSUE TITLE
Archive `io.gitlab.gregorni.Calligraphy`

### ISSUE THREAD

**Issue by gregorni** [flathub/flathub#5194]
The application `io.gitlab.gregorni.Calligraphy` has been abandoned by its maintainer (me). I'd like to archive the Flathub repository now, since it won't be used anymore.

**Comment by hfiguiere** [comment]
it needs to be EOL first.

**Comment by gregorni** [comment]
EOL'ed in https://github.com/flathub/io.gitlab.gregorni.Calligraphy/pull/1

**Comment by bbhtt** [comment]
Done

**Comment by gregorni** [comment]
Thank you!
