### ISSUE TITLE
Shotcut | Build #100288 held for review

### ISSUE THREAD

**Issue by ddennedy** [flathub/flathub#5200]
I try to be patient, but it has been 28 hours since I received the e-mail with the subject above.

> the app's metadata has changed
> talk-session-bus...

All I did to cause this was update the KDE runtime. When users install the flatpak with a runtime that has an end-of-support warning using some graphical software UIs (e.g. [Linux Mint Software Center](https://community.linuxmint.com/software/view/software-center)); it appears to install successful, but it does not install the unsupported runtime and fails to launch! It would be nice to fix that horrible UX.

**Comment by hfiguiere** [comment]
We are all volunteer

**Comment by ddennedy** [comment]
Yes I understand, Hubert, but I thought maybe this could have slipped through some crack. Thank you!
