### ISSUE TITLE
Add a "Packaged by" field

### ISSUE THREAD

**Issue by kekkoudesu** [flathub/flathub#5206]
I think adding a "Packaged by" field for every app would improve the UI for Flathub.

Here's why:

1. **The user can clearly see the software is developed "by Google", but refi64 is responsible for packaging it.** The "Unverified" tag already communicates that to those who know what it means (the [About page](https://flathub.org/about) explains it), but adding a "Packaged by" field would make it crystal clear.
2. **Packagers should get some recognition!** They make a big difference in user's lives by bringing up-to-date software to them they otherwise wouldn't be able to use, and they make a big difference for upstream developers who don't need to figure out how to write a Flatpak manifest from scratch when they decide to take ownership of the package.

Here's what I think it might look like:

![image](https://github.com/flathub/flathub/assets/88186997/0143593e-4946-4630-967d-c490ea5dc84e)

**Comment by bbhtt** [comment]
Please open at https://github.com/flathub-infra/website.
