### ISSUE TITLE
Download of module fail: unknown compression

### ISSUE THREAD

**Issue by hfiguiere** [flathub/flathub#5213]
This is Sonic Pi https://github.com/flathub/net.sonic_pi.SonicPi/pull/20

The build fail:
https://buildbot.flathub.org/#/builders/19/builds/14697/steps/7/logs/stdio

```
Failed to download sources: module aubio: Unrecognized content encoding type. libcurl understands deflate, gzip content encodings.
```

I have set `"disable-http-decompression": true` in the manifest. Without it it doesn't work locally (using the flatpak version of flatpak builder). With it set, it works as expected.

curl alone

```
$curl --compressed https://aubio.org/pub/aubio-0.4.9.tar.bz2 -o foo.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  4  388k    4 16384    0     0  17982      0  0:00:22 --:--:--  0:00:22 17964
curl: (61) Unrecognized content encoding type. libcurl understands deflate, gzip, br content encodings.
```

This also occur with https://github.com/flathub/org.rncbc.qtractor/pull/48#issuecomment-2094110676

I believe it's a problem on build bot.

**Comment by hfiguiere** [comment]
The latest build of https://github.com/flathub/net.sonic_pi.SonicPi/ failed on aarch64 because of this issue.

Now it failed on BOTH arch after a retrigger:
https://buildbot.flathub.org/#/builders/6/builds/122324

**Comment by bbhtt** [comment]
Added some fixes to org.flatpak.Builder, at least https://github.com/flathub/org.rncbc.qtractor/pull/56#issuecomment-2363962817 seems to work now with `https://aubio.org/pub/aubio-0.4.9.tar.bz2` ootb.

I guess this can be closed, the other one already switched source URL.
