### ISSUE TITLE
Please add MackBambu as maintainer for com.bambulab.BambuStudio

### ISSUE THREAD

**Issue by hadess** [flathub/flathub#5220]
As discussed privately with @lanewei120, please add @MackBambu as one of the upstream maintainers to the com.bambulab.BambuStudio repository.

@lanewei120, please confirm here that this is correct.

**Comment by lanewei120** [comment]
yes, confirmed

thanks

**Comment by bbhtt** [comment]
The Github account of MackBambu seems to have no connection with Bambulab, but I'm adding them since the other collaborators confirmed.
