### ISSUE TITLE
50% of apps use developer name for the app name?

### ISSUE THREAD

**Issue by boredsquirrel** [flathub/flathub#5223]
At least when installing them as --user apps, these apps all have the developer name displayed, instead of the apps name:

- qbittorrent
- inkscape
- gimp
- warp
- pinta
- tauon music box
- syncthingy
- nextcloud
- seabird
- cameractrls
- carburetor
- freetube
- ytdn
- footage
- cryptomator
- darktable
- ghostwriter
- localsend
- onionshare

but many other apps all show the correct name. What is going on here? do all these apps need to be patched?

[see this PR on qBittorrent](https://github.com/flathub/org.qbittorrent.qBittorrent/pull/150) is this correct?

**Comment by hfiguiere** [comment]
This is:

https://github.com/flatpak/flatpak/issues/5700

Yf you use 1.15.8  it will be fixed when the app is updated

**Comment by hfiguiere** [comment]
And by updated, there is NOTHING TO CHANGE on the app side.
