### ISSUE TITLE
Transfer ownership/maintainership of com.parsecgaming.parsec

### ISSUE THREAD

**Issue by SISheogorath** [flathub/flathub#5230]
Currently I'm the maintainer of the [parsec flatpak](https://github.com/flathub/com.parsecgaming.parsec). Since I couldn't validate various bugs and no longer use parsec, I would like to transfer it to https://github.com/Kodikuu.

For those looking for some history, please refer to https://github.com/flathub/com.parsecgaming.parsec/issues/53

**Comment by razzeee** [comment]
To whom?

**Comment by SISheogorath** [comment]
Sorry, hit the enter key by accident, filled the details :)

**Comment by Kodikuu** [comment]
👋🏻 Parsec dev here, can be reached by my Unity email if you want it for confirmation

**Comment by bbhtt** [comment]
> 👋🏻 Parsec dev here, can be reached by my Unity email if you want it for confirmation (Though I don't want to post it publicly here)

Yes if you can send some kind of confirmation via an official email to admins@flathub.org that'd be nice.

Or maybe parsec.app website has some confirmation?

**Comment by Kodikuu** [comment]
I'm not doing this in quite an official capacity, so I'll just send an email in a few minutes

**Comment by bbhtt** [comment]
We need a way to confirm that what you say is true via some channel that links you to the website of the application. As it is proprietary we can't see git repo.

**Comment by Kodikuu** [comment]
Email sent

**Comment by bbhtt** [comment]
Thanks, @barthalion verified the email. I sent an invite.
