### ISSUE TITLE
Delete the `branch/debug-crash` branch of `io.github.loot.loot`

### ISSUE THREAD

**Issue by Ortham** [flathub/flathub#5263]
I accidentally created [this branch](https://github.com/flathub/io.github.loot.loot/tree/branch/debug-crash) (I only meant to create a temporary branch to help a user with some debugging, and mistyped the name) and found that I can't delete it, could someone do that for me?

**Comment by bbhtt** [comment]
Certain branches are protected by default. Please see https://docs.flathub.org/docs/for-app-authors/maintenance#the-repository. Those should not be used as personal branches.

I've deleted the branch.
