### ISSUE TITLE
Appstream data for several programs missing languages

### ISSUE THREAD

**Issue by haaninjo** [flathub/flathub#5272]
Originally filed against gnome-software as https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2574 , but it was suggested to be originating from Flathub.

In GNOME OS Nightly with gnome-software, several apps get a banner about not being available in my language (Swedish).

Underlying cause seems to be appstream data from Flathub not holding information about all languages for those apps in `lang` tags.

Example for GNOME Boxes (but the bug linked above lists about 20 other affected apps):

In my /var/lib/flatpak/flathub/x86_64/active/appstream.xml only en_GB and en_US were listed as languages for Boxes:

```
    <languages>
      <lang percentage="100">en_GB</lang>
      <lang percentage="100">en_US</lang>
    </languages>
```

Any idea why no other languages are picked up?

**Comment by bbhtt** [comment]
Yea seems to be the symlinks, if I disable "locale migration" by doing:

```patch
diff --git a/org.gnome.meld.json b/org.gnome.meld.json
index ad962d1..545be37 100644
--- a/org.gnome.meld.json
+++ b/org.gnome.meld.json
@@ -3,6 +3,7 @@
     "runtime": "org.gnome.Platform",
     "runtime-version": "45",
     "sdk": "org.gnome.Sdk",
+    "separate-locales": false,
     "command": "meld",
     "cleanup": [
         "/include",
```

Then the metainfo has percentage data for all languages.

**Comment by ximion** [comment]
Very odd... My initial impulse would be to look at the original MetaInfo data and double-check that the [translation tag](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-translation) is set correctly for the respective file.

If the symlink targets exist, I see no reason why the locale data wouldn't be read.

**Comment by ximion** [comment]
> Yea seems to be the symlinks

I just checked the code, symlinks are indeed ignored, apparently for performance reasons... I doubt it would hurt performance *that much* if we quickly checked if the symlink target exists... I'll have a look at this later :-)

**Comment by bbhtt** [comment]
Thank you. There's no hurry, as apps will need to get rebuilt to refresh the catalogue data, anyways. I'll wait for the release.

**Comment by bbhtt** [comment]
Added it as a patch, as we might need to parse the tag soon to check for language availability. Will be removed on next appstream update.


Once it is published in 4-5 hours, you'll have to ask maintainers of affected apps to rebuild their respective apps by going to https://buildbot.flathub.org/#/ or wait until they get rebuilt to fix the original issue.
