### ISSUE TITLE
Flathub buildbot failing to commit successful builds with cryptic error

### ISSUE THREAD

**Issue by mpharoah** [flathub/flathub#5278]
I am experiencing issues with the Flathub CI builds. My updated packages builds and installs perfectly fine locally, and it passes the build step in Flathub buildbot, but the Commiting Builds step always fails with the same error:
> Job failed: InternalError: Command "flatpak" "build-commit-from" "--timestamp=NOW" "--no-update-summary" "--untrusted" "--force" "--disable-fsync" "--gpg-homedir=/var/lib/flat-manager/.gnupg" "--gpg-sign=4184DD4D907A7CAE" "--src-repo=/tank/repo/builds/105803/upload" "--src-ref=6fe4fd2121644a03ea410a16d612018f2451abb1da459c9bed12f14f9887b5b4" "/tank/repo/builds/105803" "app/ca.parallel_launcher.ParallelLauncher/x86_64/test" exited unsuccesfully: error: fsck content object c548653d97dc85a497d482a29917a745236186562e9dc518ea9ae4069de46433: Couldn't find file object 'c548653d97dc85a497d482a29917a745236186562e9dc518ea9ae4069de46433'

It seems like its either failing to fetch the data from the previous build step, or the build step isn't uploading it correctly. I've attempted multiple builds, but all of them failed with the same error. [Here](https://buildbot.flathub.org/#/builders/6/builds/122861) is the most recent failed build, and [here](https://github.com/flathub/ca.parallel_launcher.ParallelLauncher/pull/35) is the associated pull request.

**Comment by bbhtt** [comment]
The repo was pruned recently because storage was running out and looks like some objects somehow got dropped during the process.

You will have to wait for @barthalion to resolve this.

**Comment by mpharoah** [comment]
The entire repo, including its full git history, is just under 1 MiB. Why would it be pruned? Or do you just mean FlatHub in general and not my specific repo?

**Comment by bbhtt** [comment]
It's the Flathub repo not git repositories.

**Comment by mpharoah** [comment]
Looks like its working now, at least for my repo specifically anyway
