### ISSUE TITLE
appstream-compose fails on webp screenshots

### ISSUE THREAD

**Issue by Chocobo1** [flathub/flathub#5289]
Sorry if this is the wrong place to ask for help.
The issue is from this PR: https://github.com/flathub/org.qbittorrent.qBittorrent/pull/151

The last build failed with error `appstream-missing-screenshots`. Build log here: https://buildbot.flathub.org/#/builders/6/builds/123894
And here is the .metainfo.xml of the app: https://github.com/qbittorrent/qBittorrent/blob/release-4.6.5/dist/unix/org.qbittorrent.qBittorrent.metainfo.xml#L33-L50
The screenshots should be correct and running the [validation check](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#validation) manually on the .metainfo.xml didn't report any issues.

Could someone help pinpoint the issue?

**Comment by razzeee** [comment]
Wondering if this is similar to https://github.com/flathub/re.sonny.Junction/commit/c044a31135990b0ccc976fcca053993efd78775b but reading the linked MR makes me think it should be solved since we ponted to libappstream

**Comment by Erick555** [comment]
glib-networking is included in runtime already

**Comment by hfiguiere** [comment]
WEBP is not supported. And has never been.

**Comment by hfiguiere** [comment]
See https://github.com/qbittorrent/qBittorrent/commit/40833ca5106fe0c3b3f6411d25a5d0a336bf0c5e

**Comment by bbhtt** [comment]
Yea changing back to png will fix the issue. Please reopen if it doesn't work out.

**Comment by Chocobo1** [comment]
>WEBP is not supported. And has never been.

Is it different to the description here? 
>https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots
>Images should ideally be provided in the PNG format; using JPEG or ***WebP is also permitted*** for images in metainfo files.

**Comment by bbhtt** [comment]
which seems to not match reality. You should open an issue for that upstream.

**Comment by Chocobo1** [comment]
>which seems to not match reality. You should open an issue for that upstream. Maybe the docs are outdated there.

A little bit of digging reveal this.
The upstream commit that allowed WebP: https://github.com/ximion/appstream/commit/950e043c154718943d4f822521831e156ea8efca
Related discussion: https://github.com/ximion/appstream/issues/252

Currently it seems flatpak/flathub is not compliant to the spec IMO.

**Comment by bbhtt** [comment]
Again please ask upstream we do not change anything there.

**Comment by Chocobo1** [comment]
>Again please ask upstream we do not change anything there. That is an addition to docs only.

By upstream you meant https://github.com/ximion/appstream?

**Comment by bbhtt** [comment]
Yep

**Comment by Chocobo1** [comment]
>My guess is compose doesn't work with webp because the media directory is completely empty when it is supposed to have screenshots downloaded and converted.

I looked into the source code a bit and I started here: https://github.com/ximion/appstream/blob/e92858da0310be987950fa5c22a12fc0a747d17b/compose/asc-utils-screenshots.c#L839
and eventually I stopped here: https://github.com/ximion/appstream/blob/e92858da0310be987950fa5c22a12fc0a747d17b/compose/asc-image.c#L457
It seems that `appstream compose` was loading image data via `gdk_pixbuf` and AFAIK loading .webp images requires a plugin: [webp-pixbuf-loader](https://github.com/aruiz/webp-pixbuf-loader). How can I be sure that the flathub package builder has the plugin installed? I searched a bit but I couldn't find any info about the environment/image of the flathub package builder.

**Comment by bbhtt** [comment]
It doesn't, if that's the case I can add it create a test build.

**Comment by bbhtt** [comment]
I still don't see any screenshots saved in https://github.com/flathub/org.flatpak.Builder/pull/250#issuecomment-2133275631

```

**Comment by Chocobo1** [comment]
>Hey, @ximion any idea why the screenshots aren't being saved by compose? They are definitely being downloaded by curl and changing them to png seems to work.

Out of curiosity, I tried to put .svg file as screenshot and it worked. The .svg is converted to .png.

Also I see this entry in `gdk-pixbuf-2.0/2.10.0/loaders.cache`:
```
"/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so"
"svg" 6 "gdk-pixbuf" "Scalable Vector Graphics" "LGPL"
"image/svg+xml" "image/svg" "image/svg-xml" "image/vnd.adobe.svg+xml" "text/xml-svg" "image/svg+xml-compressed" ""
"svg" "svgz" "svg.gz" ""
" <svg" "*    " 100
" <!DOCTYPE svg" "*             " 100
```

I suppose this mean the svg plugin works and the webp plugin does not somehow.
I wonder would it be possible to install the webp plugin to the base image? I mean not under `/app` but in `/usr/lib/x86_64-linux-gnu`.

**Comment by bbhtt** [comment]
`/usr` is read-only and comes from the runtime. You don't need to put it into `/usr` because the loader cache is regenerated with loaders from both `/usr` and the new webp loader in `/app`.

**Comment by Chocobo1** [comment]
>You don't need to put it into /usr because the loader cache is being regenerated with loaders from both /usr and the new webp loader in /app.

I'm suspecting that for unknown reason gdk-pixbuf is unable to read/access `/app` but I don't have concrete evidence. It is the next suspect of my investigation.

**Comment by bbhtt** [comment]
There should be no reason for that. Multiple apps on Flathub use it in the same way to support webp.

**Comment by bbhtt** [comment]
Ok I got it working. You were right. I forgot to add the proper env var so that it can query loader cache from `/app`. I thought I did it already. I'll deploy something soon.

Sorry if I sounded a bit annoyed. Been dealing with some other things.
