### ISSUE TITLE
Helpful information for anyone looking to test their flatpaks locally offline using flatpak-builder.

### ISSUE THREAD

**Issue by mrbid** [flathub/flathub#5293]
```
sudo apt install flatpak
sudo apt install flatpak-builder
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.freedesktop.Sdk/x86_64/23.08
flatpak install flathub org.freedesktop.Platform/x86_64/23.08
```

Then you just....

`flatpak-builder build-dir /home/user/com.yoursite.YourApp.yaml`

I think that the two freedesktop files may already be installed if you've already used flathub to install apps via flatpak in the past, although I may be wrong, either way they do seem to be required!

**Comment by hfiguiere** [comment]
no, you should pass `--install` to flatpak-builder and flatpak run.

**Comment by bbhtt** [comment]
This is already documented in https://docs.flathub.org/docs/for-app-authors/submission#before-submission
