### ISSUE TITLE
PR test build keeps failing "Commiting builds" with fsck error

### ISSUE THREAD

**Issue by stbergmann** [flathub/flathub#5294]
Test builds of <https://github.com/flathub/org.libreoffice.LibreOffice/pull/291> "Update gvfs-1.54.0.tar.xz to 1.54.1" keep failing (e.g., <https://buildbot.flathub.org/#/builders/6/builds/123363>) in the "Commiting builds" phase with `Job failed: InternalError: Command "flatpak" "build-commit-from" "--timestamp=NOW" "--no-update-summary" "--untrusted" "--force" "--disable-fsync" "--gpg-homedir=/var/lib/flat-manager/.gnupg" "--gpg-sign=4184DD4D907A7CAE" "--src-repo=/tank/repo/builds/106304/upload" "--src-ref=4de0f536536dc3323f6a49b997fe932251ff64d1cbe637236ea2d0f38404287f" "/tank/repo/builds/106304" "runtime/org.libreoffice.LibreOffice.Help/aarch64/test" exited unsuccesfully: error: fsck content object 588a33105ada465a38289d92aec806c4dcdf06389a93eb91bf3223fe859813a3: Couldn't find file object '588a33105ada465a38289d92aec806c4dcdf06389a93eb91bf3223fe859813a3'`.

**Comment by bbhtt** [comment]
Should be fixed now.
