### ISSUE TITLE
Please add upstream author to write access.

### ISSUE THREAD

**Issue by BryanQuigley** [flathub/flathub#5301]
please add [langurmonkey](https://github.com/langurmonkey) to https://github.com/flathub/de.uni_heidelberg.zah.GaiaSky repo.  He is the upstream author.

Relatedly, we are also looking to get [verified](https://github.com/flathub/de.uni_heidelberg.zah.GaiaSky/issues/57) - any suggestions welcome!

**Comment by bbhtt** [comment]
I need some verification that the codeberg account https://codeberg.org/langurmonkey is connected to the GitHub account https://github.com/langurmonkey. 

Or something else that connects the two.

@langurmonkey can you please link those? Eg. add the github account link to codeberg profile or on your website there?

**Comment by bbhtt** [comment]
> Relatedly, we are also looking to get https://github.com/flathub/de.uni_heidelberg.zah.GaiaSky/issues/57 - any suggestions welcome!

What's the issue there? Is the subdomain causing issues?

**Comment by langurmonkey** [comment]
@bbhtt I added a link in my codeberg account pointing to github: https://codeberg.org/langurmonkey

The issue with the verification is that the `uni-heidelberg.de` and `zah.uni-heidelberg.de` domains are managed by my institution(s) (Heidelberg University and Zentrum fuer Astronomie). I don't really have direct access to the web server. I can only edit the Gaia Sky part in the typo3 CMS.

**Comment by bbhtt** [comment]
Then you have to resubmit it with a domain you control, otherwise verification is not possible.

Note that subdomain verification won't work right now, so `zah.uni-heidelberg.de` wouldn't have worked anyway right now. But allowing subdomain is on the list see https://github.com/flathub/flathub/issues/4943

**Comment by bbhtt** [comment]
I've added you to the repo
