### ISSUE TITLE
Transfer access of packages to different user

### ISSUE THREAD

**Issue by ItsJamie9494** [flathub/flathub#5303]
I would like to transfer access of the Flathub packages [org.gtk.Gtk3theme.Helium](https://github.com/flathub/org.gtk.Gtk3theme.Helium) and [org.gtk.Gtk3theme.Helium-dark](https://github.com/flathub/org.gtk.Gtk3theme.Helium-dark) to @lleyton.

**Comment by bbhtt** [comment]
Done
