### ISSUE TITLE
Flathub Icon Image not updating?

### ISSUE THREAD

**Issue by BeverlyCode** [flathub/flathub#5314]
https://flathub.org/apps/com.voxdsp.CubeShooter

I updated the image recently: https://notabug.org/Vandarin/CubeShooter/src/master/flatpak/cubeshooter.png

It's been a few days and the Flathub website is still using the old icon, I guess this is some kind of bug?

**Comment by hfiguiere** [comment]
maybe because the appstream file point somewhere else

![image](https://github.com/flathub/flathub/assets/114441/4483d11a-86c9-4004-a008-5b4c4941f303)

**Comment by hfiguiere** [comment]
oh the icon... not the screenshot

**Comment by bbhtt** [comment]
dl.flathub.org (https://dl.flathub.org/media/com/voxdsp/CubeShooter/2d86e99d91baf03b8054a9271da9048e/icons/128x128/com.voxdsp.CubeShooter.png) is behind a Fastly cache, it will take some time to expire and the new icon to be up.

If you go to the direct endpoint you can see the new icon https://master.flathub.org/media/com/voxdsp/CubeShooter/2d86e99d91baf03b8054a9271da9048e/icons/128x128/com.voxdsp.CubeShooter.png
