### ISSUE TITLE
gpt4all in flathub can anyone make it available in flathub

### ISSUE THREAD

**Issue by userforsource** [flathub/flathub#5316]
https://gpt4all.io/index.html
https://github.com/nomic-ai/gpt4all

**Comment by hfiguiere** [comment]
this tracker is not to request packages.

Also it was merged 2 days ago https://github.com/flathub/flathub/pull/5210

https://flathub.org/apps/io.gpt4all.gpt4all

**Comment by userforsource** [comment]
This is not verified can you verify that app

**Comment by hfiguiere** [comment]
no I can't. This is not the place to ask this either.
