### ISSUE TITLE
Flathub Website Changes

### ISSUE THREAD

**Issue by mrbid** [flathub/flathub#5320]
When I view an app from a developer it would suggest other apps made by that developer, I thought this was a really good idea but this feature seems to have been removed in the last few days. I am just wondering why this was removed?

You could make the developer name into a (`https://flathub.org/apps/collection/developer/`) hyper-link at minimum, so that people can use that to find all the apps released by a specific developer.

**Comment by razzeee** [comment]
That's a bug and not intended. Collections still exist.

**Comment by bbhtt** [comment]
> this feature seems to have been removed in the last few days. 

Where? I still see it

![image](https://github.com/flathub/flathub/assets/62639087/60bb0c00-7500-46ad-ad53-4898de8eb8a9)
