### ISSUE TITLE
More rights on VLC repos

### ISSUE THREAD

**Issue by MatMaul** [flathub/flathub#5322]
I am the maintainer of VLC and its plugins, and I can't change the default branch of those.

This is annoying since the dependencies update checker is only checking on the default branch.

Can I get enough rights on those repo so I can change the default branch ? If not, could you change the default branch to `branch/3-23.08` for the plugins ?

Thanks !

https://github.com/flathub/org.videolan.VLC
https://github.com/flathub/org.videolan.VLC.Plugin.makemkv
https://github.com/flathub/org.videolan.VLC.Plugin.fdkaac
https://github.com/flathub/org.videolan.VLC.Plugin.bdj

**Comment by bbhtt** [comment]
Changed the branches. Github doesn't allow giving someone fine grained access, so permission to change branches is equivalent to permission to changing repo settings which includes some protected stuff.

You can use a custom x-checker workflow to run the x-checker on multiple branches. See the example for Edge or Qtwebengine baseapp.

**Comment by MatMaul** [comment]
Thanks!
