### ISSUE TITLE
Yank aarch64 for net.ankiweb.Anki (for now)

### ISSUE THREAD

**Issue by rayes0** [flathub/flathub#5333]
The aarch64 builds were leftover from previously when the package was built from source and is now outdated. Users seem to find that annoying. Though I am planning on building the package from source someday, I do not have the time to work on that currently, so please remove the builds for now.

see: https://github.com/flathub/net.ankiweb.Anki/issues/125

**Comment by hfiguiere** [comment]
why did you stop building from source? It's not nice to the users.

**Comment by rayes0** [comment]
The decision was not mine, but from a previous maintainer, from what I can tell it was because of the complexity of the build system. The flatpak currently uses official builds distributed by the devs. Anki has since changed build systems, so it should be more manageable now.

**Comment by rayes0** [comment]
No longer needed after https://github.com/flathub/net.ankiweb.Anki/pull/172
