### ISSUE TITLE
Adding maintainer to org.freedesktop.Sdk.Extension.texlive

### ISSUE THREAD

**Issue by jakobjakobson13** [flathub/flathub#5335]
In https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/issues/157 axtloss asked for maintainer rights for org.freedesktop.Sdk.Extension.texlive. I have no objections and from the answers of hfiguiere I guess that he agrees.

**Comment by hfiguiere** [comment]
That was not an agreement. Just a procedure thing (ie how to request it). 

It remains YOUR call.

**Comment by bbhtt** [comment]
Yea see https://docs.flathub.org/docs/for-app-authors/maintenance#maintainer-access-to-flathub-application-repository

I sent an invite
