### ISSUE TITLE
Add maintainers to org.openchemistry.Avogadro2

### ISSUE THREAD

**Issue by matterhorn103** [flathub/flathub#5336]
The lead developer of Avogadro 2 does not currently have access rights to the flathub repo. Can you please add @ghutchis as a maintainer of the [Avogadro 2 flatpak](https://github.com/flathub/org.openchemistry.Avogadro2) as he is the primary maintainer of the [application](https://github.com/OpenChemistry/avogadrolibs) and the main active member of the [parent project](https://github.com/OpenChemistry)?

Subsequently, could you also add me, @matterhorn103, as an extra maintainer? I suggested this at the bottom of [this thread](https://discuss.avogadro.cc/t/flatpak-verification-and-nightly/5257/7) on the Avogadro discussion board, with the intention of working on meeting the new quality guidelines and getting verified status, and I took the thumbs-up reaction from @ghutchis to indicate approval.

I also mentioned the current maintainer, @kevinsmia1939, on the discussion thread, but presumably they are not a frequent visitor to the forum as there was no response; they are likely more active on here.

**Comment by bbhtt** [comment]
> Can you please add @ghutchis

They already have access.

> Subsequently, could you also add me, @matterhorn103, as an extra maintainer? I

Added

cc @kevinsmia1939

**Comment by matterhorn103** [comment]
> They already have access.

Oh ok.

Thanks!

**Comment by kevinsmia1939** [comment]
Ok
