### ISSUE TITLE
EOL org.freedesktop.Sdk.Extension.dotnet7

### ISSUE THREAD

**Issue by Dryadxon** [flathub/flathub#5363]
.NET 7 SDK has reached [end of life](https://devblogs.microsoft.com/dotnet/dotnet-7-end-of-support/), and should be archived.
On that note, this should also apply to [.NET 5 `org.freedesktop.Sdk.Extension.dotnet5`](https://devblogs.microsoft.com/dotnet/dotnet-5-end-of-support-update/) and [.NET Core 3.1 `org.freedesktop.Sdk.Extension.dotnet`](https://devblogs.microsoft.com/dotnet/net-core-3-1-will-reach-end-of-support-on-december-13-2022/) since those are no loger supported.

**Comment by bbhtt** [comment]
Archived all 3, extensions aren't EOL-ed separately.
