### ISSUE TITLE
restore org.freedesktop.Sdk.Extension.rust-nightly

### ISSUE THREAD

**Issue by da2ce7** [flathub/flathub#5364]
The important SDK: https://flathub.org/apps/org.freedesktop.Sdk.Extension.rust-nightly

> "This repository has been archived by the owner on May 14, 2024. It is now read-only. "

There has been no public announcement of the deprecation of this important developer and testing SDK.

I made a post on the flathub forum: https://discourse.flathub.org/t/unannounced-deprecation-of-rust-nightly-sdk/6979 , without reply.

Note: I offer to takeover the maintenance of this repository others are unable.

**Comment by bbhtt** [comment]
Nightly is not allowed on Flathub, it won't be unarchived in the current form.

**Comment by bbhtt** [comment]
This was also the reason for which it was archived. This policy existed internally for long but was not strictly enforced until recently.

If you depend on it, I suggest bundling rust-nightly with your app, see the example here https://github.com/flathub/io.github.ungoogled_software.ungoogled_chromium/pull/21 . With bundling you can control the exact version to depend on.

**Comment by da2ce7** [comment]
@bbhtt thankyou for the reply, however the repo was just abruptly archived: the Readme was not updated with a rationale for the deprecation, nor dose the public facing page: https://flathub.org/apps/org.freedesktop.Sdk.Extension.rust-nightly have any record that this sdk is deprecation.

How could this silent and abrupt deprecation of a package be the actual policy of flathub?

**Comment by bbhtt** [comment]
I'm talking about the policy of not allowing nightly releases on Flathub.

The only way to announce an End of Life to the world is to EOL it https://docs.flathub.org/docs/for-app-authors/maintenance#end-of-life, but extensions are not EOL-ed for various technical reasons. 

I can update the README.

**Comment by da2ce7** [comment]
My workflow is to use the Nightly SDK in my developer setup. I use these SDK's in my developer environment for testing, or actual coding with for example VSCodium.

I do not bundle the Rust Nightly SDK in anything that I ship, instead I use it for it's intended purpose: for software development.

I would like to to at-least have a link to the Flathub Policy that says that this Nightly Software Development Kit not allowed, and then have the description on flathub and it's github readme updated to show how it is conflighting with the policy of flathub.

**Comment by bbhtt** [comment]
> I would like to to at-least have a link to the Flathub Policy that says that this Nightly Software Development Kit not allowed

https://docs.flathub.org/docs/for-app-authors/requirements#stable-releases-reproducible-builds

>  and it's github readme updated to show how it is conflicting with the policy of flathub.

Added a deprecation notice to readme and appstream data https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-nightly/commit/1d5570d13abca743d8dafbf7d1f596810f017849. 

It should update the page on https://flathub.org/apps/org.freedesktop.Sdk.Extension.rust-nightly when published.

**Comment by da2ce7** [comment]
@bbhtt Thank You :)  This is much more clear, and will not confuse people of this SDK like myself.

I would love to have a way to easily have the Rust Nightly SDK accessible from my flatpak VSCodium: the stable SDK is often not appropriate for developmental tasks.
