### ISSUE TITLE
I need to give permission to a icon designer to see the review status of flathub.

### ISSUE THREAD

**Issue by sergiotarxz** [flathub/flathub#5379]
I would like to give permission to an icon designer to see the review status of the icon and the branding colours, but I am afraid it can have other permissions that could mess with the project build system or code.

Can someone guide me to do so?

I am not capable alone to design a icon that fullfills the guidelines.

**Comment by razzeee** [comment]
Realistically the guide and the SVG template here https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#app-icon should be all the designer needs.

Maybe the https://docs.flathub.org/banner-preview too, but that's not really that relevant to the icon.

**Comment by hfiguiere** [comment]
the can submit pull request and you can merge as needed. This is how github works.

**Comment by sergiotarxz** [comment]
Yes, I only wanted she to be able to see her results by herself to provide her greater transparency since I am going to pay her.

I wanted her to be able to see this after her pull requests.
![image](https://github.com/flathub/flathub/assets/25019174/d1188023-8ca2-4def-a0c3-0ee032f088fe)

But I do not want to provide her any additional privilege.

**Comment by razzeee** [comment]
This is not possible currently

**Comment by sergiotarxz** [comment]
Thank you, you can close now if it is for me, if you think it would be useful to do something about it then keep it open or move to the web repo or whatever you think fits best.

**Comment by fedelibre** [comment]
> This is not possible currently

@razzeee There's any script to check if an app passes the quality guidelines validation? I've hopefully fixed the warnings of my app, but I'm not sure. How can I verify it? Thanks

**Comment by fedelibre** [comment]
I've read the docs and  already made the changes that hopefully will clear the warnings, but I'm not sure about the screenshots. I'll open a discussion on the forum.

**Comment by bbhtt** [comment]
Can you open a new issue?
