### ISSUE TITLE
Add maintainer to SyncthingTray

### ISSUE THREAD

**Issue by qgymib** [flathub/flathub#5382]
Can you please grant @Martchus access to https://github.com/flathub/io.github.martchus.syncthingtray ?

Thanks very much :)

**Comment by Martchus** [comment]
It would be appreciated as I am the developer/maintainer of https://github.com/Martchus/syncthingtray.

**Comment by bbhtt** [comment]
Done

**Comment by Martchus** [comment]
Thanks!
