### ISSUE TITLE
Include existing flatpak into my flatpak

### ISSUE THREAD

**Issue by Corvonn** [flathub/flathub#5384]
Hey
I hope this is the right place for this kind of question. 

The following problem: 
The software in my flatpak needs VLC Media Player installed in the system in one case in order to work correctly. My thought was that I could integrate the existing VLC Flatpak into my Flatpak so that VLC is available in the Flatpak. 
The only question is: How do I do this? I tried a bit, looked at the documentation and asked Chat GPT as a test. I've had a few promising attempts, but unfortunately none of them have worked so far.
Is it even possible to do it the way I imagined and if so, how?

**Comment by bbhtt** [comment]
Use it as a baseapp https://github.com/flathub/com.netease.CloudMusic/blob/5e4f5cb11c86fee1048a8af23cdf2ed2a9af49b6/com.netease.CloudMusic.json#L6 or build it in the manifest yourself.

**Comment by Corvonn** [comment]
Sorry for my late response, unfortunately I had a lot to do. And thank you very much for your quick reply :D
I already have Electron as my base app at the moment. Then I can't also use VLC as a baseapp, can I?
And I had already considered building it myself, but the original VLC Flatpak looks quite complex. I had hoped that there were simpler ways.

**Comment by bbhtt** [comment]
No you can't add two baseapps. You have to choose one. the electron baseapp is a lot simpler and faster to build, so you can build those components in your manifest.

Pick the ones you actually need from the baseapp for example the electron baseapp has libspeechd for speech recognition. If your app doesn't need that, don't build it.
