### ISSUE TITLE
Date rounding is wrong

### ISSUE THREAD

**Issue by mrbid** [flathub/flathub#5386]
https://flathub.org/apps/org.kde.haruna
![image](https://github.com/flathub/flathub/assets/78346668/3a03af97-0fdc-49d6-bbc2-dbb8cf241f86)

https://flathub.org/apps/com.voxdsp.TempleDriver
![image](https://github.com/flathub/flathub/assets/78346668/2fc38487-8ca4-4496-b40c-e1cfc2f503f2)

I know that `0 months ago` would look bad, but adding an extra month is just as bad, I would just not display the months when it's 0 and display the correct number of months otherwise.

**Comment by razzeee** [comment]
You realize that those are different dates?

**Comment by razzeee** [comment]
> Whats the first non bracketed date for? It's not very clear or obvious where that date is coming from or what its representing?

Date of the release. Originally, only that existed, but was confusing in some cases, as year old releases can start appearing on the start page as recently released, as they only just got published/build as a flatpak.

**Comment by bbhtt** [comment]
Please open flathub.org website issues in https://github.com/flathub-infra/website unless it's an infra issue. It's in the README here.
