### ISSUE TITLE
Certain Flatpak apps not launching proper GUIs

### ISSUE THREAD

**Issue by Iron-Squid** [flathub/flathub#5387]
Distro: Fedora 39

I've recently updated all of my flatpaks this morning, and have noticed that two separate apps fail to properly launch their GUI. Their initialization screens pop up, but their main UI fails to properly display.
The two apps in question are `io.github.hydrusnetwork.hydrus` and `com.calibre_ebook.calibre`.

I have since uninstalled the flatpak version of Calibre and have fallen back onto the `rpm` package for Fedora, and am working on getting Hydrus working on its own. 

Shown below is a screenshot of how Hydrus (and Calibre) have appeared since updating.
![image](https://github.com/flathub/flathub/assets/68481224/1c6ac79d-9972-49f2-84ae-1834de899d06)

I had assumed that this was just a problem with Hydrus' packaging, but the fact that two separate apps with similar GUI toolkits have the same issue leads me to believe that this may be a runtime error.

**Comment by Iron-Squid** [comment]
If this is the incorrect repo to be posting this report, please direct me to the proper one!

**Comment by Iron-Squid** [comment]
Update: After uninstalling Calibre (dnf) and reinstalling Calibre (flathub), it apparently works perfectly fine with no issues.
I attempted to reinstall Hydrus (flathub) as well to see if reinstalling it would work. It didn't.

**Comment by bbhtt** [comment]
Please report it here https://github.com/flathub/io.github.hydrusnetwork.hydrus
