### ISSUE TITLE
Random failures while building the `i386` NVIDIA drivers

### ISSUE THREAD

**Issue by guihkx** [flathub/flathub#5388]
The latest `i386` build of `org.freedesktop.Platform.GL.nvidia`, has failed:

- https://buildbot.flathub.org/#/builders/6/builds/132946

These failures seem random and they've happened many times before. I'm not sure what causes them, but I have a suspicion:

It seems like the only buildbot worker able to build the i386 driver successfully is `cncf-x86-4`.

Examples:

- https://buildbot.flathub.org/#/builders/38/builds/20
- https://buildbot.flathub.org/#/builders/38/builds/23
- https://buildbot.flathub.org/#/builders/38/builds/25

Meanwhile, the `cncf-x86-3` worker has failed every time:

- https://buildbot.flathub.org/#/builders/38/builds/21
- https://buildbot.flathub.org/#/builders/38/builds/22
- https://buildbot.flathub.org/#/builders/38/builds/24

But then again, maybe those are just coincidences...

If I may suggest something, perhaps making the Freedesktop 1.6 i386 SDK publicly available on Flathub, would prevent this.

```
$ flatpak remote-info flathub org.freedesktop.Sdk/i386/1.6
error: Error searching remote flathub: Can't find ref org.freedesktop.Sdk/i386/1.6
```

**Comment by guihkx** [comment]
Yes, but so has the 1.6 x86_64 SDK, which is still downloadable through Flathub regardless:

```
$ flatpak remote-info flathub org.freedesktop.Sdk/x86_64/1.6
         ID: org.freedesktop.Sdk
        Ref: runtime/org.freedesktop.Sdk/x86_64/1.6
       Arch: x86_64
     Branch: 1.6
 Collection: org.flathub.Stable
   Download: 717,1 MB
  Installed: 1,9 GB

     Commit: c02e7a722d26f43a5af534cb70b0d61f593c0c12f44d5aa3000db2227a5a90e0
     Parent: d1e0781a699ab6c89e3fad6ad1362f4903834c45df6fb900dbdf4981405ff18c
End-of-life: The Freedesktop 1.6 SDK is no longer supported and does not receive security updates. We strongly recommend migrating to a supported runtime.
    Subject: build of org.freedesktop.Sdk, Tue Nov  6 17:56:02 UTC 2018
       Date: 2018-11-07 00:08:07 +0000
```

**Comment by guihkx** [comment]
Okay, so what I'll say doesn't change this issue, but I created and published my own i386 build of the 1.6 SDK [on this repo](https://github.com/guihkx/freedesktop-sdk-1.6-i386), for whoever needs it to build/package their NVIDIA drivers locally.

**Comment by nanonyme** [comment]
The main problem with nVidia extension is specifically that it is using too old version of runtime. There's a branch to step upward but it is two years old and against a bit newer but also EOL runtime https://github.com/nanonyme/org.freedesktop.Platform.GL.nvidia/tree/newer-runtime. If anyone wants to grab this work, rebase it, test it and upstream it, then it would probably allow fixing this issue.

**Comment by guihkx** [comment]
@nanonyme I've implemented that in https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/pull/322

Unfortunately, the overall build time has been increased by ~1 hour (~5 hours total), because we now have to also build liblzma and zlib (in addition to libzstd), as the 24.08 SDK we're now using doesn't provide the static version of these libraries (the old 1.6 SDK did).

Speaking of which, it'd be great if the SDK could provide us with these 3 static libraries, because since the number of drivers can only grow, so will the overall build time...

I think this can be closed now, but maybe we should wait a few weeks just to make sure the changes I introduced won't break something for someone...

**Comment by nanonyme** [comment]
Static libraries are removed by intent. Apps (or here extensions) should build them.

**Comment by nanonyme** [comment]
Increased build time is expected .

**Comment by bbhtt** [comment]
> If I may suggest something, perhaps making the Freedesktop 1.6 i386 SDK publicly available on Flathub, would prevent this.

i386 refs were deleted from the repo server a while back, I don't think it's possible to bring them back unless you can get 1.6 building on i386 again which at this is point is pretty impossible.

**Comment by guihkx** [comment]
> Static libraries are removed by intent. Apps (or here extensions) should build them.
> Increased build time is expected.

I understand that, but it's undeniable that build time would decrease exponentially by just having the SDK providing static versions of those 3 libraries - again, like the 1.6 SDK used to do for some libraries, like zlib and liblzma.

And I believe Flathub's build infrastructure would also greatly benefit from such addition as well.

But I understand if that's not possible at this time.

**Comment by bbhtt** [comment]
How much time are you spending on building just the dependencies apart from the drivers itself? Maybe a baseapp for this makes sense.

**Comment by bbhtt** [comment]
Err rather an extension, so that you can simply cp stuff when building this the Nvidia drivers.

**Comment by guihkx** [comment]
>How much time are you spending on building just the dependencies apart from the drivers itself?

On my quad-core, 3.6 GHz CPU, it takes 1 minute and 40 seconds just to build zlib, liblzma, libzstd and libarchive (which I forgot to mention previously).

>Err rather an extension, so that you can simply cp stuff when building the Nvidia drivers.

That's an interesting idea. I've never built an extension from scratch before, but I suppose I can take a look at it. For the extension id, do you have any suggestions?

**Comment by bbhtt** [comment]
You won't have control over the ID as the extension point needs to be in runtime/SDK.

But 1 min 40s is not a lot, Flathub runners are a lot more powerful than that, it's likely <1 min on the runners.

**Comment by guihkx** [comment]
>You won't have control over the ID as the extension point needs to be in runtime/SDK.

Oh. I thought it would be something like the [NodeJS extension](https://github.com/flathub/org.freedesktop.Sdk.Extension.node20), where I would follow the regular submission process.

>But 1 min 40s is not a lot, Flathub runners are a lot more powerful than that, it's likely <1 min on the runners which seems a bit insignificant even when multiplied by driver versions.

Well, on my machine it would take roughly ~11 hours (110 * 373 / 3600) to build all drivers, and Flathub [currently takes 5 hours](https://buildbot.flathub.org/#/builders/6/builds/170818), so roughly 30 seconds to build each driver version. I'd say that's still a lot.

>How many are you building at the moment? I'm not sure where the +1 hour is coming from.

373 versions. And that will only increase.

**Comment by nanonyme** [comment]
> How much time are you spending on building just the dependencies apart from the drivers itself? Maybe a baseapp for this makes sense.

Yeah, base app or Sdk extension that would contain needed static libraries would cut down the cost of building extensions *a lot*.

**Comment by bbhtt** [comment]
Yes you can use the nodejs extension point as that is in the SDK, it'd be a Flathub submission yes. I don't think a static library extension from fdsdk directly makes sense.

Maybe you should try to check locally if it improves anything. Note that, an extra extension in the manifest means it's another thing the runners need to install (for the first time) or run update on from the next time. 

Ultimately the time saved might not be a lot but would bring extra maintenance burden.

**Comment by guihkx** [comment]
Gotcha.

Although I'm fairly confident this will have a positive impact, I'll make sure to test this locally before committing to anything.

Would `org.freedesktop.Platform.GL.nvidia-base` be an acceptable/valid id for such extension?

**Comment by bbhtt** [comment]
Currently builldbot is being a bit slow since it starts leaking memory every now and then after being hammered with too many builds.

The time increase might be partly from that.

We would likely restart it after the holidays.

**Comment by nanonyme** [comment]
IMHO the underlying issue here is that we have hundreds of extensions build in custom way from one repo rather than having one repo per nVidia extension. Normally you *do not need to* build anything except the one new extension. The normal thing to happen is nVidia release a new driver which needs to be packaged. Old drivers do not need to be touched.

**Comment by bbhtt** [comment]
> Would org.freedesktop.Platform.GL.nvidia-base be an acceptable/valid id for such extension?

I'd prefer org.freedesktop.Sdk.Extension.nvidia-base or something along those lines.

I've never tried this so it might not work, just thinking it out.

**Comment by bbhtt** [comment]
> IMHO the underlying issue here is that we have hundreds of extensions build in custom way from one repo rather than having one repo per nVidia extension. Normally you do not need to build anything except the one new extension. The normal thing to happen is nVidia release a new driver which needs to be packaged. Old drivers do not need to be touched.


Yea I think it should be optimised if possible

**Comment by guihkx** [comment]
>IMHO the underlying issue here is that we have hundreds of extensions build in custom way from one repo rather than having one repo per nVidia extension

Ideally, yes, but in reality it would be humanly impossible for anyone to maintain 373 separate repos (and counting)...

>Normally you *do not need* to build anything except the one new extension. The normal thing to happen is nVidia release a new driver which needs to be packaged. Old drivers do not need to be touched.

Again, ideally that would be true, but after maintaining the NVIDIA drivers for the last few months, from time to time we do need to tweak the [driver extractor program](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/blob/7d380e9e4e7ffa4a1b967d2a6bbc24cd7d2e1091/nvidia-apply-extra.c) so it can extract crucial libraries that were previously missing, or just fix general issues.

And sometimes these changes require all driver versions need to be repackaged again, including old ones.

I have [this PR](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/pull/234) (which is ready, but currently needs a rebase) that would move away the drivers from extra-data. But unfortunately that brings its own share of issues as well...
