### ISSUE TITLE
Only the active GTK theme is installed on Ubuntu 24.04

### ISSUE THREAD

**Issue by ZVNexus** [flathub/flathub#5391]
On Ubuntu 24.04 there are 10 accent colors which are handled with 20 different GTK themes, however when you install a Flatpak only the theme that is currently active is the one that gets installed.

This means if the user switches accent colors, they will end up with an app not using the native theme. For example, if you switch from Yaru-dark to Yaru-viridian-dark, your app's window decorations will be blindingly white.

This is extremely jarring, but I'm not sure what a good solution would be. Is there a way that we could install every GTK theme that is present on a system if a corresponding Flatpak for it exists? The issue would remain for any theme that gets installed afterwards, but it would at least cover the Ubuntu usecase.

**Comment by bbhtt** [comment]
This is done by Flatpak, Flathub plays no part here other than hosting the flatpak-ed themes.

**Comment by ZVNexus** [comment]
> This is done by Flatpak, Flathub plays no part here other than hosting the flatpak-ed themes.

I had just opened a Flatpak issue prior to this since I thought the same, but they said they don't define any of these:
https://github.com/flatpak/flatpak/issues/5866

**Comment by bbhtt** [comment]
It's done here https://github.com/flatpak/flatpak/blob/92d7f9ec49e2db4ad93040d8e607531791165024/common/flatpak-utils.c#L5620-L5625

If changing the accent colour does not change the theme variant they Flatpak cannot obviously ask the extensions to be downloaded.

**Comment by ZVNexus** [comment]
> It's done here https://github.com/flatpak/flatpak/blob/92d7f9ec49e2db4ad93040d8e607531791165024/common/flatpak-utils.c#L5620-L5625
> 
> If changing the accent colour does not change the theme variant they Flatpak cannot obviously ask the extensions to be downloaded.

It does change the theme variant, but it doesn't automatically install the theme until you install the app again (or update the app afaik).

What I'm looking for is the flatpak binary to automatically check /usr/share/themes/ and check if Flathub has any of the themes listed in there.

**Comment by bbhtt** [comment]
> but it doesn't automatically install the theme until you install the app again 

That's expected. That's how it works, you don't want flatpak to start installing random extensions in the background without user interaction.

**Comment by bbhtt** [comment]
> check if Flathub has any of the themes listed in there.

Flathub has no part here. Flatpak will detect the theme variant check if an extension named by theme exists in one of your remotes then install it. It can be any remote doesn't have to be Flathub.

**Comment by ZVNexus** [comment]
> That's expected. That's how it works, you don't want flatpak to start installing random extensions in the background without user interaction.

Are they random extensions though? If they're in /usr/share/themes they are themes installed on the system by default or by a package manager. Having this be expected seems like pretty awful UX, at least if you're a user comparing a Flatpak to a native .deb for example

**Comment by bbhtt** [comment]
> Having this be expected seems like pretty awful UX, at least if you're a user comparing a Flatpak to a native .deb for example

You can ask in Flatpak for improving this. 

But right now Flatpak does not differentiate between theme extensions or any other extensions or a dependency of another Flatpak. They are downloaded in the same way, only on user interaction.
