### ISSUE TITLE
Need to add App Owner to Greenery on Flathub

### ISSUE THREAD

**Issue by tmrdev** [flathub/flathub#5395]
I am the developer who is maintaining the Greenery app on Flathub.  

Repo link: https://github.com/flathub/io.greenfire.Greenery

I need to add the App Owner for the app, Corey Stedman:

https://github.com/CoreyDesir

The company name is Greenfire Inc and the official Github is below:

https://github.com/GreenfireInc

Corey needs Flathub Dev Portal access so that he can verify the domain name.

**Comment by bbhtt** [comment]
Added
