### ISSUE TITLE
Request: Atom Editor

### ISSUE THREAD

**Issue by prcastro** [flathub/flathub#54]
[Atom](https://atom.io/) is one of the most widely used editors on Linux (alongside Emacs, Vim, Sublime Text and VSCode). Would be very nice if it was available on Flathub.

**Comment by TingPing** [comment]
Please don't open issues just requesting packages. Generally any popular package is wanted and those who are interested in doing it can submit a PR.

**Comment by prcastro** [comment]
So sorry. I figured that this was the place to request new packages, since in the description of the repo is written "Requests for new applications to be added".

**Comment by TingPing** [comment]
That is referring to pull requests but I can see how that could be unclear.

**Comment by Barthalion** [comment]
The repository used to be named `requests` and at least in my opinion, it's completely fine to let people open issues for requested applications. I don't see the point in closing any of this.

**Comment by TingPing** [comment]
I don't want to start any argument but I just don't see value in it; Every application is wanted so opening an issue doesn't provide anything more. Those who plan on doing the actual packaging just do the actual packaging. For example I don't believe any other distribution or store allows you to request packages (AUR votes don't really count).

**Comment by manuq** [comment]
I agree with TingPing. Filling the issue tracker with requests like this doesn't add any value, as potentially any Linux desktop app can be added to Flathub.

It is interesting however to see discussions on the most wanted applications. Like for example this survey started in the Endless OS forums: https://community.endlessos.com/t/flatpak-software-wishlist/1657/17

**Comment by prcastro** [comment]
I agree with Manuq, maybe add a Wishlist somewhere, where people can vote for example. This would make it eaasier to prioritize what software should be included in flathub to please its users (if thats what you want, of course).

**Comment by TingPing** [comment]
I'm sure the Endless folks won't mind using that forum thread for now.
