### ISSUE TITLE
Add maintainer to Proton-GE

### ISSUE THREAD

**Issue by ChrisHobday** [flathub/flathub#5409]
Hello. I'd like to be added as a maintainer for https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE . I've already forked and updated it to the latest version. I have also contacted Lctrs, a current maintainer and was advised to come here to ask for permissions. Thanks.

**Comment by bbhtt** [comment]
I have unarchived it. Can you please open a PR with the changes you are willing to make? I can send an invite after giving a light review on it.

**Comment by ChrisHobday** [comment]
Alright I've submitted a PR here https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE/pull/190 .

**Comment by bbhtt** [comment]
Sent you the invite.
