### ISSUE TITLE
Question: User-defined, fine-grained permissions in flatpaks

### ISSUE THREAD

**Issue by ghost** [flathub/flathub#542]
Dear developers,

recently I read a text (
[Why I Dig the Control Snap Apps Offer Me](https://www.omgubuntu.co.uk/2018/07/snap-app-permissions-manager)) about user-defined, fine-grained user permissions of snap packages. Does flatpak offer a similar mechanism? If not is in planned for some future versions? That would be very nice as Android and iOS also already have a similar approach and at the end it should be left to the user how much system access is granted to a application.

Regards

**Comment by TingPing** [comment]
It is somewhat simliar: `flatpak override --user --nosocket=pulseaudio org.example.Foo`

**Comment by JakobJakobson** [comment]
Is there also a way to do that via a GUI ?

**Comment by TingPing** [comment]
Not currently.
