### ISSUE TITLE
Archive com.powerball253.eternalmodmanager

### ISSUE THREAD

**Issue by brunoanc** [flathub/flathub#5424]
[com.powerball253.eternalmodmanager](https://github.com/flathub/com.powerball253.eternalmodmanager) has been recently renamed to io.github.brunoanc.eternalmodmanager in #5413. I have added a [flathub.json](https://github.com/flathub/com.powerball253.eternalmodmanager/blob/master/flathub.json) file to mark it EOL and add the rebase.

Could you please archive the old repo? Thank you!

(BTW, am I missing anything else for the renaming process? I already added the `provides` and `replaces` fields in the appdata.)

**Comment by bbhtt** [comment]
No seems fine.
