### ISSUE TITLE
How to increase download timeout on flathub builders?

### ISSUE THREAD

**Issue by mfschumann** [flathub/flathub#5428]
Hi, 

I get frequent timeouts when downloading the source during build of eu.betterbird.Betterbird. Most of the time, only the x64 builds are affected, like in [this example](https://buildbot.flathub.org/#/builders/37/builds/16650).

The problems have gotten worse over the last few weeks. I now have to repeat the build every few runs and hope that it passes. 

Is there any way to increase the timeout for the source download?

Thanks!
Martin

**Comment by bbhtt** [comment]
No, this is not possible. Flatpak builder uses the defaults used by curl.

**Comment by bbhtt** [comment]
Maybe try changing the URLs to see if it helps https://archive.mozilla.org/pub/thunderbird/candidates/128.0esr-candidates/build3/source/ or https://download-installer.cdn.mozilla.net/pub/thunderbird/candidates/128.0esr-candidates/build3/source/

**Comment by bbhtt** [comment]
Closing this, if you think download timeout should be increased please open an issue https://github.com/flatpak/flatpak-builder/

But generally it will more often cause builds to hang forever and jam the build queue than actually helping
