### ISSUE TITLE
Failing to apply patches doesn't abort the build

### ISSUE THREAD

**Issue by Mailaender** [flathub/flathub#5430]
https://buildbot.flathub.org/#/builders/6/builds/135583 took 1 hour to finally time out.

**Comment by bbhtt** [comment]
Open an issue here https://github.com/flatpak/flatpak-builder/ that's the default behaviour of GNU patch if the patch is already applied or the file does not exist.

Flatpak-builder can probbaly run patch with `-f` or `-t` by default.

**Comment by Mailaender** [comment]
https://github.com/flatpak/flatpak-builder/issues/446
