### ISSUE TITLE
App Listing Quality review lacking any feedback

### ISSUE THREAD

**Issue by ztefn** [flathub/flathub#5436]
Its infuriating that there is absolutely no feedback from the app listing quality review other than _Doesn't fill too much or too little of the canvas_ as **Not passed**. So my apps ([Haguichi](https://flathub.org/apps/com.github.ztefn.haguichi)) icon is perfectly aligned to the grid. Yet somehow its failed to pass.

![Screenshot from 2024-07-22 20-08-38](https://github.com/user-attachments/assets/ed9676ae-ce96-428e-9e74-9464f3b1e63e)

So hopefully the reviewer(s) can be made aware of this issue and tell me exactly what they want me to do to make it pass:
- Move the shape some 8px to the left to **visually** align it more to the center (because numerically it is).
- Stretch (and thus distort) the shape shape to fit the whole width (which I'm for obvious reasons not gonna do).
- Make the logo higher to fit more vertical space.
- Some other genius idea?

Please enlighten me!

**Comment by bbhtt** [comment]
cc @razzeee @bertob

**Comment by razzeee** [comment]
I assume it's just not covering enough of the canvas, but wait for tobias to confirm.

**Comment by bertob** [comment]
Yeah, the problem here is just that the icon does not cover enough area. From the [guidelines](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines/#reasonable-footprint):

> The icon shouldn't fill [...] too little of the canvas. [...] Similarly, avoid thin shapes that are hard to see.

> You can use our icon grid ([SVG template download](https://docs.flathub.org/img/app-icon-grid.svg)) with square and circular base shapes to check if your icon's footprint is too large or too small. The examples below show the grid overlaid on some app icons.

I'd recommend either putting the glyph inside a square or circle, or making it thicker/larger.

**Comment by ztefn** [comment]
> [...] putting the glyph inside a square or circle

Ugh, really? I hate this trend of making icons look "uniform" by slapping everything on a square or circle.

> [...] or making it thicker/larger.

Well, thicker is not an option because like I said I'm not going to distort the logo. So that leaves me only with the option of making it larger.

Keeping it within boundaries the result would be like this:

| Before | After |
|---|---|
| ![Screenshot from 2024-07-24 00-09-12](https://github.com/user-attachments/assets/b2e2e2f7-9df3-429a-9649-7afc13df5688)  | ![Screenshot from 2024-07-24 00-11-49](https://github.com/user-attachments/assets/90f0dcd2-529f-440e-be46-480ef1676f7b)  |

 Would that get the approval of the design committee™? Or is this all just an elaborate scheme to favor GNOME Circle apps...

**Comment by bertob** [comment]
The grid is for square/circle-like shapes. More pointy shapes can use the outer parts of the canvas a bit more in a few spots, that's not necessarily a problem. Here's a quick attempt at a similar shape that would work in terms of visual weight, but I did have to make it a little bit thicker:

![image](https://github.com/user-attachments/assets/e112900f-bf0c-4aef-a8ba-41c6086504cb)

![image](https://github.com/user-attachments/assets/360636a9-c4bd-48fe-ad0b-6238cce7c85c)

If you're dead set on keeping the current shape I'm not sure there's any way around a background circle/square, but I think that could look good too :)

**Comment by ztefn** [comment]
@bertob Thanks for the clarification!

So far I've ended up making the overall size larger, extending the use of the canvas in all directions:

![Screenshot from 2024-07-26 20-49-54](https://github.com/user-attachments/assets/452447a7-bcac-4ebc-bdb7-ddee7b927b86)

![Preview](https://github.com/user-attachments/assets/07216d7b-9075-44f7-84ca-89eb3afb94f2)

Still might not be as bulky compared to some GNOME icons, but I think the keyword here is **reasonable footprint**... 😉

**Comment by bertob** [comment]
Definitely a bit on the slim side, but I guess it's fine like that.

**Comment by bbhtt** [comment]
Seems this is done.
