### ISSUE TITLE
Ownership of com.maplerain.telsis_translator_flutter

### ISSUE THREAD

**Issue by vivian-ng** [flathub/flathub#5445]
Hi, I put the app
[com.maplerain.telsis_translator_flutter](https://github.com/flathub/com.maplerain.telsis_translator_flutter)
on flathub a while ago without creating an account. I would like to tie it to my account on GitHub and request for the app to be verified.

According to [this](https://docs.flathub.org/docs/for-app-authors/submission/#someone-else-has-put-my-app-on-flathubwhat-do-i-do), I am supposed to raise an issue or email, so that is what I am doing.

**Comment by hfiguiere** [comment]
> without creating an account

How did you ? Github doesn't allow anonymous PR.

**Comment by hfiguiere** [comment]
And you are the user that committed to it.

**Comment by vivian-ng** [comment]
I meant I didn't have an account on Flathub back then. So when I sent the app for publishing on Flathub via the repo on GitHub, I did it through my GitHub account (this one) but now, when I follow the instruction for verification on Flathub, I realized that the app does not show up in Flathub when I log in to Flathub through my GitHub account (since I just linked my GitHub account to Flathub like 30 minutes ago).

**Comment by bbhtt** [comment]
You already have access, hit refresh on the developer portal a couple of times and it should show up.

https://docs.flathub.org/docs/for-app-authors/submission#i-cant-see-the-app-in-my-authored-apps-on-the-developer-portal-why
