### ISSUE TITLE
End Of Life issues

### ISSUE THREAD

**Issue by coolhandluke57** [flathub/flathub#5452]
It appears that your Master PDF Editor (net.codeindustry.MasterPDFEditor version 5.9.82) found in LinuxMint Software Manager uses runtime org.kde.Platform//5.15-22.08 which has reached end-of-life.

It appears that your Guiscrcpy (in.srev.guiscrcpy version 4.11.3) found in LinuxMint Software Manager uses runtime org.kde.Platform//5.15-21.08 which has reached end-of-life.

It appears that your Kdeconnect (com.github.bajoja.indicator-kdeconnect version 21.12.3-0ubuntu1) found in LinuxMint Software Manager uses runtime org.gnome.Platform//3.36 which has reached end-of-life.

**Comment by rusty-snake** [comment]
- https://github.com/flathub/net.codeindustry.MasterPDFEditor/issues/80
- https://github.com/flathub/in.srev.guiscrcpy/issues/10 -> Unmaintained
- https://github.com/flathub/com.github.bajoja.indicator-kdeconnect/issues/16 and https://github.com/flathub/com.github.bajoja.indicator-kdeconnect/issues/19 -> Unmaintained

**Comment by hfiguiere** [comment]
File these with the individual project if the issues don't already exist.
