### ISSUE TITLE
Give me access please :D (io.github.yairm210.unciv)

### ISSUE THREAD

**Issue by yairm210** [flathub/flathub#5461]
I'm the creator of [Unciv](https://github.com/yairm210/Unciv), the app for which this is the Flatpak repo. 

Since last month, Flatpak has disallowed `automerge-flathubbot-prs": true` in the config, which causes the builds to fail.

The fix looks simple enough, but unfortunately I don't have permissions to this repo to actually fix it 😅 

Shooting out at those related to the [initial creation](https://github.com/flathub/flathub/pull/1339) who can probably help out

@MayeulC @barthalion @bilelmoussaoui

As an addendum - since the automerge is disabled, is there another known way I can "auto-accept" flathubbot PRs that have passed tests? This sounds like a common ask 🤔

**Comment by bbhtt** [comment]
> since the automerge is disabled, is there another known way I can "auto-accept" flathubbot PRs

It will continue to send PRs whenever there is an update, but you will have to merge them manually. If you have a good reason for auto-merging you can ask for an exception https://docs.flathub.org/docs/for-app-authors/linter#exceptions

I sent you the invite with the permission to the repo.
