### ISSUE TITLE
Archive net.seamly.seamly2d

### ISSUE THREAD

**Issue by csett86** [flathub/flathub#5476]
[net.seamly.seamly2d](https://github.com/flathub/net.seamly.seamly2d) has been recently renamed to io.seamly.seamly2d in https://github.com/flathub/flathub/pull/5444. I have added a [flathub.json](https://github.com/flathub/net.seamly.seamly2d/blob/master/flathub.json) file in the old repo to mark it EOL and add the rebase.

Could you please archive the old repo? Thank you!

**Comment by bbhtt** [comment]
done
