### ISSUE TITLE
io.github.lawstorant.boxflat fails guidelines review

### ISSUE THREAD

**Issue by Lawstorant** [flathub/flathub#5485]
To the point, the review fails at "default settings" but I am using default settings in screenshots. I've rechecked everything and there's no custom theme, no custom fo ts nor font sizes. Everything looks just like Gnome set it up and there are only two darkmode screenshots out of six.

I even made sure to use default Gnome font hinting and antialiasing

Could someone explain the reason for not passing this or is it just a omission?

Thanks

**Comment by razzeee** [comment]
Gnome by default only has the `X` icon in the top right. The `_` to minimize isn't the default.

**Comment by Lawstorant** [comment]
Couldn't that be outlined somewhere? I must've changed it about 7 years ago. I honestly would never notice that this is the issue

**Comment by Lawstorant** [comment]
Thanks, I'll create another one to refresh the embed after I'm done updating the screens

**Comment by razzeee** [comment]
It's outlined in the docs, but you could argue, that it's only implied. Mostly, cause we don't want to give gnome specific instructions, but general ones.

https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#default-settings
