### ISSUE TITLE
Add maintainer to org.gnome.NetworkDisplays

### ISSUE THREAD

**Issue by LorbusChris** [flathub/flathub#5494]
Please add myself (@LorbusChris) as a maintainer to https://github.com/flathub/org.gnome.NetworkDisplays

I'm one of the upstream maintainers at https://gitlab.gnome.org/GNOME/gnome-network-displays/ and would like help with downstream Flatpakaging :) 

If you need any other info (or someone to vouch for me), please let me know.

**Comment by bbhtt** [comment]
added
