### ISSUE TITLE
Request to archive old repository: io.itch.drwhut.TabletopClub

### ISSUE THREAD

**Issue by drwhut** [flathub/flathub#5495]
As of today, I have moved my app ID from `io.itch.drwhut.TabletopClub` to `net.tabletopclub.TabletopClub` to facilitate verifying the app.

I have just pushed the `end-of-life` and `end-of-life-rebase` to the repository, and the build has succeeded, but I don't believe it has been fully published yet.

Would it be possible to archive the old [io.itch.drwhut.TabletopClub](https://github.com/flathub/io.itch.drwhut.TabletopClub) repository, as it will no longer be in use?

**Comment by hfiguiere** [comment]
done
