### ISSUE TITLE
Request: Sublime Text

### ISSUE THREAD

**Issue by prcastro** [flathub/flathub#55]
[Sublime Text](https://www.sublimetext.com/) is one of the most widely used editors on Linux (alongside Emacs, Vim, Atom and VSCode). Would be very nice if it was available on Flathub. I don't know if its license pose restrictions to this, but since Skype is available now, I though it was possible.

**Comment by TingPing** [comment]
https://github.com/flathub/flathub/issues/54#issuecomment-314538787
