### ISSUE TITLE
Upgrading to new org.freedesktop.Platform version didn't remove old version

### ISSUE THREAD

**Issue by matthew-cline** [flathub/flathub#550]
On doing a flatpak update version 18.08 of `org.freedesktop.Platform` was pulled (`org.freedesktop.Platform/x86_64/18.08`) but the old 1.6 version still remained, rather than being removed.

The only app I have installed is Steam.

**Comment by barthalion** [comment]
I don't think unused "dependencies" are automatically removed. What if you run `flatpak uninstall --unused` (assuming you're running recent flatpak)?

**Comment by barthalion** [comment]
It's fine, I'll close the issue for now. If it happens again, try reporting it against flatpak repo as it's not flathub issue per se.
