### ISSUE TITLE
Transfer ownership of org.DolphinEmu.dolphin-emu to upstream developer

### ISSUE THREAD

**Issue by cpba** [flathub/flathub#5511]
The dolphin project wants to make org.DolphinEmu.dolphin-emu official: https://github.com/flathub/org.DolphinEmu.dolphin-emu/issues/224

I want to request that ownership of the repo be transfered to https://github.com/OatmealDome

**Comment by bbhtt** [comment]
Added, they have to accept the invite within a week.
