### ISSUE TITLE
Cataclysm: Dark Days Ahead ownership

### ISSUE THREAD

**Issue by kevingranade** [flathub/flathub#5513]
Hi I am the lead developer of Cataclysm: Dark Days Ahead.  A contributor recently registered CDDA with flathub (in good faith,  coordinating with issue https://github.com/CleverRaven/Cataclysm-DDA/issues/75504).

As I'm looking into validation as requested in https://github.com/CleverRaven/Cataclysm-DDA/issues/75772 I seem to be blocked by the application being attached to a different acccount.

**Comment by bbhtt** [comment]
I sent you an invite to the Flathub repo. Once you accept that, go to the website and login. You can find it in your authored apps.

If it doesn't show up, see https://docs.flathub.org/docs/for-app-authors/submission#i-cant-see-the-app-in-my-authored-apps-on-the-developer-portal-why

Once you have it in your authored apps, you can find the verification options which involves uploading a txt file with the token on cataclysmdda.org See https://docs.flathub.org/docs/for-app-authors/verification#website
