### ISSUE TITLE
Request to add a collaborator to the Q-Zandronum repo

### ISSUE THREAD

**Issue by kreatoo** [flathub/flathub#5515]
Hi,

I've been reached out by the Q-Zandronum developers to add them as a collaborator to [the repo](https://github.com/flathub/com.qzandronum.Q-Zandronum)  but I don't seem to have the permissions to do that.

If someone that has the permission could add @kultasakaali and @IgeNiaI that would be appreciated.

I couldn't find an email and/or ticket to send this request which is why I'm sending it from here.

**Comment by bbhtt** [comment]
Added them.

You are in the correct place, it's in the docs https://docs.flathub.org/docs/for-app-authors/maintenance#maintainer-access-to-flathub-application-repository

https://docs.flathub.org/docs/for-app-authors/submission#someone-else-has-put-my-app-on-flathubwhat-do-i-do
