### ISSUE TITLE
Feature Request: Download .flatpak bundles on flathub.org

### ISSUE THREAD

**Issue by thepragmaticmero** [flathub/flathub#5518]
I just want to download a .flatpak file from the flathub.org website. More info on why [here](https://github.com/flatpak/flatpak/issues/5906).

> I was traveling to an inside province of my home country Peru (cute country btw, go visit, there are cute llamas and alpacas). And I encountered a very peculiar problem for my setup. I have a miniPC and small screen that I carry with me when I travel. The home I was staying at had no internet but a nearby coffee shop had. I couldn't carry my minipc to that place. So I resorted to download my apps through my phone. Question is, I couldn't "download" the apps from flathub. I had to resort to downloading .AppImages (eew). I know that flatpak has the capability of offline installs. But appears to be that flathub doesn't.

I had to resort once to downloading a .flatpak bundle from [github](https://github.com/rustdesk/rustdesk/releases/download/1.3.0/rustdesk-1.3.0-x86_64.flatpak)

**Comment by bbhtt** [comment]
Flatpak bundles are not fully offline you would still need the internet for dependencies like the runtime and extensions.

With the way the repo is set up we don't produce single file bundles and we do not have plans to support this. This was already discussed in https://github.com/flathub/flathub/issues/921

**Comment by thepragmaticmero** [comment]
.appimage > flatpak Hmmp!! *tsundere noises *

**Comment by razzeee** [comment]
thing is, appimages are not guaranteed to work and will break on random occations

**Comment by thepragmaticmero** [comment]
better than "not working if u don't have internet for an offline application". I mean yes you can with `flatpak create-usb` but tell me how to use that command on an android phone and I'll be happy to retract my words, 4 now -> .appimage >>> flatpak

**Comment by razzeee** [comment]
feel free to send patches for android enablement

**Comment by thepragmaticmero** [comment]
Yeah, i might, an alpine linux based mini-android app, that executes the `create-usb` using the flatpak cli.... huh... that might be an interesting first programming project.
