### ISSUE TITLE
How change app id?  

### ISSUE THREAD

**Issue by sgehrman** [flathub/flathub#5528]
Currently app id is:  com.cocoatech.deckr

I wanted to get my app verified and realized that this id is not the same as my website url.  https://deckr.surf
I do own the cocoatech.com domain, but this is a new app, and I posted it here before I had a website and didn't think it mattered.

Send exact instruction.  99% of the stuff in your docs, forums etc makes zero sense to me.

Will the current users seemlessly be updated, or do I have to tell them somehow using the old app?

To get verified does my new app id need to be surf.deckr?  I already added the .well-known file to https://deckr.surf

Thanks

**Comment by bbhtt** [comment]
See https://docs.flathub.org/docs/for-app-authors/maintenance#renaming-the-flatpak-id

> does my new app id need to be surf.deckr? 

`surf.deckr.APPNAME` yes

> Will the current users seemlessly be updated, or do I have to tell them somehow using the old app?

They will see a prompt to move to the new ID whenever the EOL rebase is done. Any data in `~/./var/app/$FLATPAK_ID` will be migrated, any data not managed by Flatpak will not

**Comment by sgehrman** [comment]
app name is deckr, so surf.deckr.deckr?

**Comment by bbhtt** [comment]
Yes that's fine.
