### ISSUE TITLE
Sober/Flatpak installation issue

### ISSUE THREAD

**Issue by FrostyyyDev** [flathub/flathub#5539]
# Linux Distro/Version:
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
```

# Issue:
### Okay, so first I setup Flatpak and installed the gnome-software plugin, and when I go to install the sober flatpakref, I get an error #60. I don't know if this is an issue with Flat or Sober, but i'm sending this error to both Sober and you all just to be safe.
# Error logs

```CPP
// installing the flatpak

redeyedfrost@penguin:~$  flatpak install --user https://sober.vinegarhq.org/sober.flatpakref

error:  Can't load uri https://sober.vinegarhq.org/sober.flatpakref: While fetching https://sober.vinegarhq.org/sober.flatpakref: [60] SSL peer certificate or SSH remote key was not OK

redeyedfrost@penguin:~$  []
```

**Comment by bbhtt** [comment]
You should report it to https://vinegarhq.org/ we don't distribute that Flatpak
