### ISSUE TITLE
Problems installing LibreOffice 6.1.0.3

### ISSUE THREAD

**Issue by orschiro** [flathub/flathub#555]
Dear all, 

Apologies for filing this issue at the potentially wrong place. 

I found the instructions at [1] indicating to use `flatpak install flathub org.libreoffice.LibreOffice` to install LibreOffice. 

However, the download is always aborting with the following error:

```
[orschiro@X230 Téléchargements]$ flatpak install flathub org.libreoffice.LibreOffice
Installing in system:
org.libreoffice.LibreOffice/x86_64/stable flathub 304eb32e6666
  permissions: ipc, network, pulseaudio, wayland, x11, dri
  file access: host, xdg-run/dconf
  dbus access: ca.desrt.dconf, org.gtk.vfs.*
  dbus ownership: org.libreoffice.LibreOfficeIpc0
Is this ok [y/n]: y
Installing: org.libreoffice.LibreOffice/x86_64/stable from flathub
[#####               ] Downloading: 15,3 MB/86,1 MB (1,7 MB/s)
Warning: Failed to install org.libreoffice.LibreOffice/x86_64/stable: While pulling app/org.libreoffice.LibreOffice/x86_64/stable from remote flathub: [56] Failure when receiving data from the peer
```

Can you please let me know if you get to see the same error?

I am running Fedora 28 and Flatpak version 0.99.3 if that is of importance. 

Thank you!

[1] https://flathub.org/apps/details/org.libreoffice.LibreOffice

**Comment by cmurf** [comment]
I just installed Libreoffice via GNOME Software using the dl.flathub.org source. And it installed without error on Fedora 28.
flatpak-1.0.0-2.fc28.x86_64
gnome-software-3.28.2-1.fc28.x86_64

**Comment by orschiro** [comment]
Dear @cmurf,

Thanks for testing it! I am closing this then. 

I guess it has to do with some misconfiguration of my system.

I will investigate that by myself.

Thank you!
