### ISSUE TITLE
Adopting com.clarahobbs.chessclock

### ISSUE THREAD

**Issue by fortysixandtwo** [flathub/flathub#5555]
Hi,

I'm in the process of [adopting Chess Clock upstream](https://gitlab.gnome.org/World/chess-clock/-/merge_requests/26)
and I'm wondering how to go about the adoption process
and whether I `SHOULD` (or even `MUST`) change the app id, etc.

I'm hoping you can help me here, as I will have to push a new release soon because of https://gitlab.gnome.org/World/chess-clock/-/issues/29 and https://gitlab.gnome.org/Teams/Circle/-/issues/239

Cheers and thanks in advance for your reply

**Comment by fortysixandtwo** [comment]
FYI

I have tested if I can schedule a manual build on the buildbot, but I don't have permission to do that
(which makes perfect sense)

![image](https://github.com/user-attachments/assets/3cf43453-c51f-4758-90c9-a10046b8799d)

**Comment by bbhtt** [comment]
If you intend to verify the app and don't have control over `clarahobbs.com`, the ID needs to be changed. https://docs.flathub.org/docs/for-app-authors/maintenance#renaming-the-flatpak-id

> I have tested if I can schedule a manual build on the buildbot, but I don't have permission to do that

If you just want access to the current chess clock repo on Flathub, I can send you an invite.

**Comment by bbhtt** [comment]
Looks like it is already verified but tied to `clarahobbs.com`. I guess you can leave that alone then, unless you plan to change the app ID.

**Comment by fortysixandtwo** [comment]
> Looks like it is already verified but tied to clarahobbs.com. I guess you can leave that alone then, unless you plan to change the app ID.

I think that would be a reason to switch the app ID.
In that case I would just submit it as if it were a new app?
i.e. https://docs.flathub.org/docs/for-app-authors/submission/ right?

**Comment by bbhtt** [comment]
Yes

**Comment by bbhtt** [comment]
I guess this can be closed now.
