### ISSUE TITLE
Add maintainer for io.github.yairm210.unciv

### ISSUE THREAD

**Issue by MayeulC** [flathub/flathub#5559]
Hello, could you add @yairm210, who is the main developer, as a co-maintainer (or perhaps the main one, if there is such a distinction?) for https://github.com/flathub/io.github.yairm210.unciv/ ?

Here is a request from the owner: https://github.com/yairm210/Unciv/issues/11375#issuecomment-2030544326

Thanks in advance :)

**Comment by bbhtt** [comment]
they were already added in https://github.com/flathub/flathub/issues/5461

**Comment by MayeulC** [comment]
My bad. Thank you for your answer, for adding them, and sorry for the noise.

**Comment by MayeulC** [comment]
@bbhtt Interestingly, they still cannot verify the app when they log in with the flathub portal: https://github.com/yairm210/Unciv/issues/11375#issuecomment-2336423604

Is there any way to fix this?

**Comment by bbhtt** [comment]
> @bbhtt Interestingly, they still cannot verify the app when they log in with the flathub portal: [yairm210/Unciv#11375 (comment)](https://github.com/yairm210/Unciv/issues/11375#issuecomment-2336423604)
> 
> Is there any way to fix this?

https://docs.flathub.org/docs/for-app-authors/submission#i-cant-see-the-app-in-my-authored-apps-on-the-developer-portal-why

click refresh button there
