### ISSUE TITLE
Add me as maintainer for nz.mega.MEGAsync

### ISSUE THREAD

**Issue by jasongodev** [flathub/flathub#5560]
Good day everyone, it has been months since the last working build of MEGAsync flatpak. There has been no fix done for the packaging issues and bug issues since version 5.0 onwards.

I took the liberty to rewrite the flatpak manifest to conform with the new build instructions of MEGAsync. My work was tested by flatbot and built successfully: https://github.com/flathub/nz.mega.MEGAsync/pull/94

With so many months delayed with no fix I believe my work deserves an urgent consideration to be merged.

I personally use MEGAsync in my Linux workstations and so I am dedicated to oversee this repo moving forward.

Hoping for your consideration.

-- Jason Go

**Comment by bbhtt** [comment]
Once that PR is reviewed and in a mergable state I can send you the access.

**Comment by jasongodev** [comment]
> Once that PR is reviewed and in a mergable state I can send you the access.

I'm happy to comply. Thank you for this attention.

**Comment by bbhtt** [comment]
Closing this, the current maintainer decided to mark the app EOL see https://github.com/flathub/flathub/issues/5932

If you ever wish to get back to the PR feel free to ask us to unarchive the repo.
