### ISSUE TITLE
Request to remove collaborators from flathub/com.brave.Browser

### ISSUE THREAD

**Issue by fmarier** [flathub/flathub#5564]
In an effort to keep the ACL as small as possible (to reduce the risk of a compromised GitHub account leading to a compromised flatpak), we would like to limit the collaborators to the https://github.com/flathub/com.brave.Browser repository to active contributors.

The following people are currently listed as collaborators but have not worked on the flatpak since 2022:
- @refi64
- @TheEvilSkeleton

and we'd like to revoke their direct access to the repository since it doesn't appear to be needed at this time.

Of course, we thank them for their past contributions and would welcome them again as active contributors in the future should they choose to. The reason why Brave was able to take maintenance of the flatpak and make it an officially-supported distribution channel is that all of the hard work was done by volunteers in the Flathub community. :heart:

**Comment by bbhtt** [comment]
Removed.
