### ISSUE TITLE
Organization rename

### ISSUE THREAD

**Issue by ZachBacon** [flathub/flathub#5576]
Hi there, so I'm working on updating the vba-m flatpak, first question is primarily organizational, we no longer serve content from vba-m.com (we still own the domain) but from visualboyadvance-m.org could we have the com.vba_m.visualboyadvance-m repo renamed to org.visualboyadvance_m.visualboyadvance-m?

**Comment by hfiguiere** [comment]
Renaming requires re-submitting and then an EOL+rebase of the original.

**Comment by ZachBacon** [comment]
Gotcha, I'll try and have that done before the end of the week.

**Comment by bbhtt** [comment]
This is also documented in https://docs.flathub.org/docs/for-app-authors/maintenance#renaming-the-flatpak-id
