### ISSUE TITLE
Move Kate text editor from beta to stable

### ISSUE THREAD

**Issue by Waqar144** [flathub/flathub#5585]
We have fixed most of the issues related to flatpak and the team wants to move it to stable now.

CC: @travier @christoph-cullmann

Ref: 
- https://invent.kde.org/teams/flathub/issues/-/issues/9
- https://github.com/flathub/org.kde.kate/issues/31

**Comment by bbhtt** [comment]
What do you need from us? You can just create the master branch and merge beta onto it and then push.

Once you did that I can make master the default branch in Github repo.

**Comment by hfiguiere** [comment]
cc @flathub/kde

**Comment by tsdgeos** [comment]
Yes

**Comment by tsdgeos** [comment]
ah we need to do work manually :D

**Comment by travier** [comment]
I've pushed the master branch and a build is started: https://buildbot.flathub.org/#/apps/org.kde.kate

**Comment by bbhtt** [comment]
Switched the default branch.
