### ISSUE TITLE
Add me as com.google.Chrome mantainer

### ISSUE THREAD

**Issue by xanscale** [flathub/flathub#5591]
Hi, i'm asking to add as mantainer of com.google.Chrome.

Actually Chrome is the most popular flathub app (but seams not much refined), i want to improve wrapper, without making huge changes, like:

- clean up issues
- improve metainfo
- icon as svg
- move to platform 24.08
- apply linter suggestions
- etc

PS im the mantainer of Android Studio Wrapper (https://github.com/flathub/com.google.AndroidStudio), so you can see my work

thanks

@refi64

**Comment by bbhtt** [comment]
Did @refi64 say they needed help or are you volunteering ? Can you start by submitting some PRs first ?

**Comment by xanscale** [comment]
https://github.com/flathub/com.google.Chrome/pull/328

it's just a cleanup PR

**Comment by bbhtt** [comment]
Hey @refi64 do you have any objections to having xanscale as a second maintainer ?
