### ISSUE TITLE
Version 1 api no longer accessible?

### ISSUE THREAD

**Issue by alkazar** [flathub/flathub#5606]
I have an application that is in production that seems to have become broken a few days ago (according to user reports).

The issue appears to be that this API is no longer accessible: https://flathub.org/api/v1/apps
That now gives a "Not found" error.

Was it removed on purpose? If so, where can I get information on these kinds of changes in the future?

**Comment by bbhtt** [comment]
It's present under the /compat route `https://flathub.org/api/v2/compat/apps/{appid}`. This was removed about 2-3 years ago when the website backend was redesigned. None of these APIs are considered as stable so expect them to change without announcement.

Also as the backend is implemented in the website, you should open issues at https://github.com/flathub-infra/website/

**Comment by razzeee** [comment]
@alkazar what's that application?
