### ISSUE TITLE
Volunteer to maintain io.github.thaunknown.miru

### ISSUE THREAD

**Issue by Angxddeep** [flathub/flathub#5615]
I’d like to take over maintaining [this package](https://github.com/flathub/io.github.thaunknown.miru) as it currently doesn’t have an active maintainer. I’ve also received approval from the [upstream maintainer](https://github.com/ThaUnknown/miru/pull/531#issuecomment-2365015363) here.

While TBH I don’t have previous experience in flatpak package maintenance, I’ve gone through the documentation and even successfully tested a new build of this particular Flatpak. Since the infrastructure for the package is already in place, it’s mostly about maintaining stuff now.

**Comment by bbhtt** [comment]
Sent you the invite
