### ISSUE TITLE
Add me as maintainer org.freedesktop.Sdk.Extension.bazel

### ISSUE THREAD

**Issue by phoepsilonix** [flathub/flathub#5627]
I heard that there is currently no maintainer.
If you'd like, please allow me to run for the position.

For now, there are one thing we need to do:
1.  Create a branch for 24.08.

**Comment by hfiguiere** [comment]
the branch is created but still build 23.08. You can start with a PR for that.

**Comment by bbhtt** [comment]
I created it https://github.com/flathub/org.freedesktop.Sdk.Extension.bazel/pull/6, cancelled the previous build, it was in the queue so nothing is published.

**Comment by phoepsilonix** [comment]
Understood.
A branch for 24.08 has also been created.
The 7.3.1 update has been merged so it's not urgent.
The person who merged it told me that there is no maintainer. So I volunteered to be the maintainer.
Thank you.

**Comment by bbhtt** [comment]
Sen you an invite.
