### ISSUE TITLE
Support to install bundled assets when application's sources are extra-data

### ISSUE THREAD

**Issue by x80486** [flathub/flathub#5628]
## Description

Currently, there is no real path to include and install bundled assets when application's sources are `extra-data` — for instance: flathub/com.syntevo.SmartGit/pull/113

This is somehow counterintuitive to the packaging process because reusing application's assets should be the first option, rather than maintaining copies.

I suggest implementing a mechanism that allows developers to specify bundled assets in Flatpak manifest when application's sources are `extra-data`, which would be then installed alongside the application.

**Comment by bbhtt** [comment]
We don't have plans to support this, it was blocked by the linter some time in 2022-2023
See https://github.com/flatpak/flatpak-builder/issues/617#issuecomment-2371398896
