### ISSUE TITLE
Set `branch/24.08` as default branch for org.freedesktop.Platform.GStreamer.openmpt

### ISSUE THREAD

**Issue by detjensrobert** [flathub/flathub#5630]
Now that the new runtime is releasing soon, please mark the 24.08 branch as default for <https://github.com/flathub/org.freedesktop.Platform.GStreamer.openmpt>.

~~Additionally, what is the correct way to have multiple branches build? How can I build extension updates for both supported runtime versions? As far as I can tell only the default branch is built.~~ Ah, I see all `branch/*`s get built, but only after a PR merge.

**Comment by bbhtt** [comment]
Done
