### ISSUE TITLE
Quality guidelines: Ruffle app icon

### ISSUE THREAD

**Issue by kjarosh** [flathub/flathub#5633]
Hello,

I'm trying to make Ruffle (https://flathub.org/apps/rs.ruffle.Ruffle) adhere to the quality guidelines of Flathub.

Regarding the app icon, I expected that we'll fail "Doesn't fill too much or too little of the canvas", because the current icon is too big. However I did not expect to fail "In line with contemporary styles", because frankly, the icon seems okay to me. It's a flat-style icon with the official Ruffle logo (which you can see in its full glory on https://ruffle.rs/).

Now I'm trying to replace the icon with something better, however I don't know how I should address the "contemporary styles" issue. That's why I wanted to make sure that the new icon is okay before replacing it.

I was thinking about using one of these (preferably the second one):

![new-logo-A](https://github.com/user-attachments/assets/7ba64482-6180-4dca-8946-32e500633eee)
![new-logo-B](https://github.com/user-attachments/assets/b309063d-0628-4f73-9c51-a794d61197ba)

The first version uses the r letter only, I'm not sure if that fills enough of the canvas though. The second one uses the Ruffle blue color as its background tile, which fits inside the template. Adding the blue background is a nice touch IMO as Ruffle uses Ruffle orange and Ruffle blue as its official colors (which make a good contrast together).

I would appreciate any feedback!

**Comment by bertob** [comment]
The second one looks fine to me, the style thing seems like an oversight.

**Comment by kjarosh** [comment]
Alright, thank you! Will be replacing the icon soon

**Comment by bbhtt** [comment]
I assume the question is answered.
