### ISSUE TITLE
DesMuMe flathub page doesn't match current version

### ISSUE THREAD

**Issue by intra0** [flathub/flathub#5634]
The page displays version 9.11
but the version it installs is 9.14.

the maintainer hasn't interacted with the repository for multiple years.
is there anyway to update the version listed on the page?

**Comment by bbhtt** [comment]
You have to update the metainfo file https://github.com/TASEmulators/desmume/blob/91196788eb6f8543ea395ac1f6ad9e056dc7c5c2/desmume/src/frontend/posix/gtk/org.desmume.DeSmuME.metainfo.xml#L33 with the new release. You can submit a patch upstream, then add that patch to the Flatpak package. https://docs.flatpak.org/en/latest/module-sources.html#patch-sources

**Comment by bbhtt** [comment]
If you open a PR ping me and I can merge it. otherwise this is kind of the maintainer's duty.
