### ISSUE TITLE
Can't automatically verify com.github.marinm.songrec due to missing dash in the Flathub package name

### ISSUE THREAD

**Issue by marin-m** [flathub/flathub#5652]
Hello,

I have been suggested to verify my SongRec flathub package (https://github.com/marin-m/SongRec, https://flathub.org/apps/com.github.marinm.songrec, https://github.com/flathub/com.github.marinm.songrec) by an user (https://github.com/marin-m/SongRec/issues/180), so that for example the package - which is currently unverified - appears without extra steps in the Linux Mint software center.

However, I can't do this on https://flathub.org/apps/manage/com.github.marinm.songrec because I originally prefixed the app with `com.github.marinm` for typographical standard purposes, and the UI refuses to consider this an acceptable name as the @marinm account on Github is owned by someone else:

![image](https://github.com/user-attachments/assets/d79eb996-73fc-4834-96ba-fd8308926ce3)

I guess that the simplest thing to do would be apply the verification status manually on the Flathub side, if possible (as I'm posting from the account owning the source Github repo), as this would avoid breakage on the userbase side,

I have been suggested to otherwise rename the package by re-submitting it to overcome this (with another name, such as io.github.marin-m.songrec, or io.github.songrec, or a domain I own or may buy like dev.moulinier.songrec or io.songrec, etc.). But I am fearful that this would raise other UX issues, that I am globally not sure about:

* I have observed that SongRec has been publicised through a handful of blog posts authored by third parties around the web that I personally don't know, often bundled with command-line install instructions - would the pre-existing command-line install instructions containing the current package name break if the package name was renamed (as well as the links to the page on the store)? Or would a form of redirect internal to the Flatpak package distribution infrastructure be left?
* Would the users that installed the package with its former name still obtain updates/would the new package be installed automatically for them?
* Would the pre-existing launch command line `flatpak run com.github.marinm.songrec` be broken as well?
* Would the pre-existing desktop shortcuts or Freedesktop extension associations break as well? (Would renaming the XDG `.desktop` association file be required at all?)
* Would the package install count on the Flathub store be lost (there seem to be some people having the app installed and I wouldn't like to incur much breakage)?

Regards,

**Comment by bbhtt** [comment]
Flatpak will automatically migrate existing users to the new package upon EOL rebasing, then they will get updates from the new package.

`flatpak install old_app_id` will also automaitcally redirect to the new app id.

Install numbers on the site will be added to the new install count.

> flatpak run com.github.marinm.songrec be broken as well?

This will no longer work.

> Would the pre-existing desktop shortcuts or Freedesktop extension associations break as well?

Old desktop file will be gone, a new one will be installed in its place. If you associated file extensions will the old one, they are outside of Flatpak's control and cannot be updated.

**Comment by bbhtt** [comment]
> apply the verification status manually on the Flathub side, if possible

Yours is not an exceptional case to apply manual verification. The rules of app id existed long before the package was submitted. The current ID is wrong.
