### ISSUE TITLE
Verification of dev.lizardbyte.app.Sunshine

### ISSUE THREAD

**Issue by ReenigneArcher** [flathub/flathub#5663]
I am trying to go through the verification process, but it's using the wrong address.

![image](https://github.com/user-attachments/assets/ac32691f-425f-4fcd-9bd8-3a53d88b5727)

We publish our github pages to `app.lizardbyte.dev` not to `lizardbyte.dev`. Is there a way to use the `app` prefix?

**Comment by hfiguiere** [comment]
no. if you don't control `lizardbyte.dev` then the app-id is invalid.

**Comment by hfiguiere** [comment]
oh it's a different bug.

**Comment by ReenigneArcher** [comment]
I control it, but github points to app.lizardbyte.dev, not lizardbyte.dev.

Ideally, we should be able to use a TXT reccord, like github uses for verification.

![image](https://github.com/user-attachments/assets/532be44e-9d0e-4622-ac74-b10f8bacc4fb)

**Comment by bbhtt** [comment]
Same issue as https://github.com/flathub-infra/website/issues/3844

**Comment by ReenigneArcher** [comment]
Perhaps it can be manually verified? https://app.lizardbyte.dev/.well-known/org.flathub.VerifiedApps.txt

**Comment by ReenigneArcher** [comment]
I was able to get it verified by making a few tweaks which I then reverted. I imagine this PSL thing is going to be a pain point for many. Might want to reconsider it.

Easy option is to allow verification through a TXT DNS record, then no one needs to add any page to their website and can do this much quicker with a minor DNS adjustment.
