### ISSUE TITLE
Random icons within apps installed from Flatpak/Flathub are missing icons.

### ISSUE THREAD

**Issue by Unstuffedspare** [flathub/flathub#5669]
I'm running Fedora 40 - fully updated.

I've tried reinstalling Fedora, turning off all extensions and uninstalling/reinstalling Flathub/Flatpak as well as all apps.

![image](https://github.com/user-attachments/assets/88109e6f-5471-43cc-86b3-33a973832515)
![image](https://github.com/user-attachments/assets/a85f8d7f-6ae5-42b2-8422-fa46dbfe67e4)
![image](https://github.com/user-attachments/assets/db047aac-3bf5-4dd5-a9df-28679d0ed27b)
![image](https://github.com/user-attachments/assets/4617edee-3c84-4d5c-afd7-9fa3eec43eb6)
![image](https://github.com/user-attachments/assets/905c14de-3fc4-4c4f-bc25-30eede69bf0a)

Will do some more testing in a VM, but really confused at what is happening here. Apps installed via Appimage/RPM have no issues.

**Comment by Unstuffedspare** [comment]
Issue also filed on Flatpak: https://github.com/flatpak/flatpak/issues/5954

**Comment by bbhtt** [comment]
Flatpak uses icons from your host, so something is wrong with your host icon theme. Probably not updated to the latest version or a missing package.

**Comment by Unstuffedspare** [comment]
> Flatpak uses icons from your host, so something is wrong with your host icon theme. Probably not updated to the latest version or a missing package.

I'm using Papirus - Might try downloading it from another source. Thanks for the tip. Will mention if I got things working.
