### ISSUE TITLE
Add me as a maintainer of org.b3log.siyuan

### ISSUE THREAD

**Issue by 5l2** [flathub/flathub#5673]
It was only @proletarius101 who maintained [SiYuan Note](https://github.com/siyuan-note/siyuan) on Flatpak, i.e. https://github.com/flathub/org.b3log.siyuan/.

Now the project lacks maintenance and has fallen behind the main version. I submitted [an issue](https://github.com/siyuan-note/siyuan/issues/12446) to the SiYuan Note official about three weeks ago.

I made some pull requests for org.b3log.siyuan before. I can maintain the project in my spare time.

Could you please consider granting me the repository access?

**Comment by bbhtt** [comment]
Added you
