### ISSUE TITLE
[Question] Domain used for the application ID

### ISSUE THREAD

**Issue by ollm** [flathub/flathub#5676]
Hi.

My app has been using the ID `org.opencomic.app` for several years ([OpenComic](https://github.com/ollm/OpenComic)), but I don't currently own the [opencomic.org](https://opencomic.org) domain, only [opencomic.app](https://opencomic.app).

Can I keep the ID `org.opencomic.app` to publish on Flathub? I have the domain [org.opencomic.app](https://org.opencomic.app), but it has to be reverse domain name?

Or would it be better to change the ID it for Flathub to, for example, `app.opencomic.org`, since I have the domain [org.opencomic.app](https://org.opencomic.app), even if it is only for Flathub and the other releases remain the same?

Thanks in advance.

**Comment by bbhtt** [comment]
If you don't control it, you cannot use that in the ID. Rename the ID, you can make it specific to Flathub only through patches.

**Comment by ollm** [comment]
Thanks for the quick reply! I'm going to change it.

**Comment by ollm** [comment]
I will probably end up using `dev.opencomic.app` (I have also the [opencomic.dev](https://opencomic.dev) domain)

**Comment by hfiguiere** [comment]
`app` isn't the app name either. And yes had you owned the `.org` this would have been pointed out at review. The last component is the application name.

**Comment by ollm** [comment]
Thanks for the clarification, I'll probably end up using `dev.opencomic.opencomic` or some like `app.opencomic.OpenComic`
