### ISSUE TITLE
Verify com.rustdesk.RustDesk

### ISSUE THREAD

**Issue by rustdesk** [flathub/flathub#5677]
Following https://github.com/flathub/com.rustdesk.RustDesk/issues/1

**Comment by bbhtt** [comment]
Did you accept the invite to the repo? If no accept then and the log on to flathub.org using GitHub.

Then go to the developer portal and Rustfusk should be in your authored apps. If it doesn't show up wait for sometime and/or hit refresh.

Once it shows up you can verify it from there.

**Comment by rustdesk** [comment]
Thanks, it is verified now.
![image](https://github.com/user-attachments/assets/78fba555-09b5-41da-be9b-48ed43e3d94e)
