### ISSUE TITLE
OrcaSlicer App Add Request

### ISSUE THREAD

**Issue by ZeFoxii** [flathub/flathub#5684]
I'm not sure how to request an app be uploaded to flathub, but last I saw about this is someone said to post here about it. I want OrcaSlicer added to flathub I'm a 3rd party user and I hope I did this right.

**Comment by hfiguiere** [comment]
> I'm not sure how to request an app be uploaded to flathub

You don't. Either someone submit it, or you do. But we definitely don't take requests.

**Comment by kugelzucker** [comment]
> Follow [SoftFever/OrcaSlicer#3949](https://github.com/SoftFever/OrcaSlicer/issues/3949)

that issue is dead...
