### ISSUE TITLE
Age rating not shown in app page

### ISSUE THREAD

**Issue by sidt4** [flathub/flathub#5685]
From https://github.com/flathub/net.krafting.PleasureDVR/issues/2#issuecomment-1865146275

Age rating not shown in app page in flathub, while GNOME Software displays it

### From https://flathub.org/apps/net.krafting.PleasureDVR: 

![flathub-age-rating-missing](https://github.com/user-attachments/assets/f4d456bb-b2ac-4200-80bd-10d6f88c2d02)

### From GNOME Software:

![gs-age-rating](https://github.com/user-attachments/assets/6fcf517f-bdf9-442b-923b-d1bf2fa45c16)

Related:

- https://github.com/flathub/flathub/issues/158
- https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2411

**Comment by bbhtt** [comment]
This is a website frontend issue https://github.com/flathub-infra/website/issues/114
