### ISSUE TITLE
Can we provide the old version of Intel libva?

### ISSUE THREAD

**Issue by fxzxmicah** [flathub/flathub#5688]
The new version of Intel libva lacks a lot of video hardware decoding capabilities on older hardware.

**Comment by bbhtt** [comment]
Flathub does not provide it, libva comes from the freedesktop runtime. https://gitlab.com/freedesktop-sdk/freedesktop-sdk/

You can bundle it in your app if an old version is needed. It's unlikely that it will be downgraded. https://github.com/flathub/fr.handbrake.ghb.Plugin.IntelMediaSDK/blob/master/fr.handbrake.ghb.Plugin.IntelMediaSDK.json has an example of bundling.

**Comment by fxzxmicah** [comment]
It seems like I didn't express myself clearly, I mean this one https://github.com/intel/intel-vaapi-driver. However, it seems that it has already been provided, so the problem I encountered may be due to an issue with the version used by the application.

**Comment by jumperes** [comment]
Today I stumbled over this as well. I took a look at the link for the freedesktop runtime in bbhtt's comment. There's a subfolder for the VAAPI extensions and [the commit log for that folder](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/commits/master/elements/extensions/platform-vaapi-intel) reveals [this commit](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/commit/8b3b68e32821b60f6abc35c285b796378ac20365) from 2024-11-04:

> Remove intel-vaapi-driver
> 
> It has been discontinued by Intel https://github.com/intel/intel-vaapi-driver/commit/fd727a4e9cb8b2878a1e93d4dddc8dd1c1a4e0ea
> and the current version is already 4 years old and has incompatibilities
> with newer Mesa or libva. See [#1804](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/work_items/1804)
> 
> We realistically cannot keep this working or commit to supporting for
> another 2 years when 25.08 reaches stable.
> 
> Unfortunately this drops support for a bunch of older Intel cards like
> Cantiga, Ironlake, Sandy Bridge, Ivy Bridge most of which were released
> around 2008-2012 but a few newer cards too like Cannon Lake

@fxzxmicah While this certanly isn't the answer you were hoping for I suspect this properly explains the situation.
