### ISSUE TITLE
add access to repository for eu.vcmi.VCMI 

### ISSUE THREAD

**Issue by Laserlicht** [flathub/flathub#5692]
Can someone add @IvanSavenko and me (@Laserlicht) as repository owner? We're contributors from upstream (see [here](https://github.com/vcmi/vcmi/graphs/contributors)).

It seems `Alexander Wilms` isn't on Github anymore (at least his account, all PR's and issues are gone). So this repo seems to be unmaintained.

**Comment by bbhtt** [comment]
Added
