### ISSUE TITLE
Collaborator access for com.github.hluk.copyq

### ISSUE THREAD

**Issue by hluk** [flathub/flathub#5697]
I'm trying to follow the [Verification documentation](https://docs.flathub.org/docs/for-app-authors/verification/), but I don't see any Developer Setting for the app I maintain (https://github.com/flathub/com.github.hluk.copyq).

BTW, I logged into Flathub using my github account.

Can you allow me to modify com.github.hluk.copyq on Flathub?

**Comment by bbhtt** [comment]
You already have access.

Try hitting the refresh button a few times and wait. It should appear eventually

![image](https://github.com/user-attachments/assets/456cc98c-7b20-4f07-8c52-08b719b1cef4)

**Comment by hluk** [comment]
Ah, now I see it! Thanks for quick reply! :+1:
