### ISSUE TITLE
Volunteering to help maintain older Java SDKs

### ISSUE THREAD

**Issue by guihkx** [flathub/flathub#5705]
I maintain a few apps that rely on the Java runtime:

- https://github.com/flathub/es.estoes.wallpaperDownloader
- https://github.com/flathub/com.tonikelope.MegaBasterd
- https://github.com/flathub/br.gov.fazenda.receita.irpf2022
- https://github.com/flathub/br.gov.fazenda.receita.irpf2023
- https://github.com/flathub/br.gov.fazenda.receita.irpf2024

Unfortunately, the current maintainers of old Java SDKs (namely, versions [8](https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk8) and [11](https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11)) are a bit slow to review/merge pull requests, so I'd like to help with that...

**Comment by bbhtt** [comment]
@MatMaul any objections to having guihkx as a second maintainer?

**Comment by MatMaul** [comment]
Definitively, I am a bit burn by those since I don't really use them. Feel free to nominate @guihkx on any OpenJDK repo I maintain. Thanks @guihkx 🙏
