### ISSUE TITLE
Add maintainers for org.sil repos

### ISSUE THREAD

**Issue by chrisvire** [flathub/flathub#5712]
As per the discussion over on the [discourse](https://discourse.flathub.org/t/how-would-i-go-around-with-requesting-a-new-user-as-a-maintainer-for-a-repo/5446) page, I am creating an issue to add these maintainers:

@davidmoore1
@rpmargetts

 for the following repos:

[org.sil.scripture-app-builder](https://github.com/flathub/org.sil.scripture-app-builder)
[org.sil.reading-app-builder](https://github.com/flathub/org.sil.reading-app-builder)
[org.sil.dictionary-app-builder](https://github.com/flathub/org.sil.dictionary-app-builder)

They are other maintainers of the underlying software.

**Comment by bbhtt** [comment]
Done

**Comment by chrisvire** [comment]
@bbhtt The last app was added this morning.  Could you also add these maintainers:

@davidmoore1
@rpmargetts

for this repo:

[org.sil.keyboard-app-builder](https://github.com/flathub/org.sil.keyboard-app-builder)

Thanks!

Chris Hubbard

**Comment by bbhtt** [comment]
Added, you can mention it when doing the submission PR and they can be added when merging
