### ISSUE TITLE
Discussion around allowing packages without reverse DNS names

### ISSUE THREAD

**Issue by ZVNexus** [flathub/flathub#5720]
Current documentation dictates that packages on Flathub need to have a reverse DNS package name, but this is often not the case for a lot of the most popular proprietary applications (e.g. Discord, Spotify, Slack, Steam, etc).

This requirement of Flathub is causing some desktop files to not be associated with their application's window, for example in KDE with Slack.

The window decoration app icon is falling back to the fallback "X11" icon. This is seemingly not possible to resolve with current Flathub rules, since the desktop file has to be "com.slack.Slack.desktop", but the WM_CLASS will always be "slack" since it is set by the application itself, so the compositor will look for "slack.desktop".

Getting these apps to rename themselves doesn't seem realistic so not sure what else can be done for this. Made a post in Spotify's Linux forum just in case but haven't gotten a response.

Submitted a change to kwin to look and see if any desktop files contain a StartupWMClass entry that matches the current WM_CLASS or app_id, that works but is currently being blocked by KDE because they don't want to workaround application shortcomings.

Alternative maybe is to allow for desktop files to not follow the Flatpak ID itself?

**Comment by bbhtt** [comment]
> This requirement of Flathub is causing some desktop files to not be associated with their application's window, for example in KDE with Slack.

>  itself, so the compositor will look for "slack.desktop".

These are appliction bugs. The rDNS scheme existed long before Flathub. Check the Freedesktop DBus spec or the desktop file naming spec.

> Alternative maybe is to allow for desktop files to not follow the Flatpak ID itself?

This cannot be done. It's a security risk to allow Flatpak's to expose arbitrary desktop files to host.


There is a `patch-desktop-filename` script in the Electron baseapp that you can use to fix those. https://docs.flatpak.org/en/latest/electron.html#use-correct-desktop-filename

**Comment by ZVNexus** [comment]
> Check the Freedesktop DBus spec or the desktop file naming spec.

Looking at https://specifications.freedesktop.org/desktop-entry-spec/latest/file-naming.html, doesn't seem to explicitly give any hard requirements? Says that apps __should__ use reverse DNS, but not __must__.

> There is a `patch-desktop-filename` script in the Electron baseapp that you can use to fix those. https://docs.flatpak.org/en/latest/electron.html#use-correct-desktop-filename

Thanks! Took a look for Slack, it works when running in Wayland natively but not in XWayland. Still an improvement so adding it.

What about apps like Spotify? They're not using Electron, they use CEF. Is the only solution for this one that Spotify renames their app?

**Comment by bbhtt** [comment]
You can take it to Freedesktop I don't know why it says should. rDNS is the only way to guarantee uniqueness and ownership.
