### ISSUE TITLE
Add maintainer to io.qt.QtCreator and io.qt.qtdesignstudio

### ISSUE THREAD

**Issue by marbub** [flathub/flathub#5736]
I will be on a longer trip. @tjenssen wants to do the updates for both repositories. It would be nice if he would be added as a maintainer.

**Comment by bbhtt** [comment]
Added

**Comment by tjenssen** [comment]
Thank you

**Comment by tjenssen** [comment]
I was not aware that I needed to click the invitation, so it's expired. Can you resend it, please?

**Comment by bbhtt** [comment]
Sent it again
