### ISSUE TITLE
Archive com.chenyifaer.FaFaRunner

### ISSUE THREAD

**Issue by kjxbyz** [flathub/flathub#5760]
[com.chenyifaer.FaFaRunner](https://github.com/flathub/com.chenyifaer.FaFaRunner) has been recently renamed to com.fafarunner.FaFaRunner in #5759. I have added a [flathub.json](https://github.com/flathub/com.chenyifaer.FaFaRunner/blob/master/flathub.json) file to mark it EOL and add the rebase.

Could you please archive the old repo? Thank you!

(BTW, am I missing anything else for the renaming process? I already added the `provides` and `replaces` fields in the appdata.)

**Comment by hfiguiere** [comment]
what you miss is that the EOL rabase is currently rebasing on nothing because the package doesn't exist. Something about putting the cart before the horse.

**Comment by kjxbyz** [comment]
Do you mean I need to wait for new packages to be released before I can update eol?

**Comment by bbhtt** [comment]
Yes, also repos are automatically archived now upon EOLing after some fixed period of inactivity.

**Comment by kjxbyz** [comment]
Should I revert this [commit](https://github.com/flathub/com.chenyifaer.FaFaRunner/commit/8e2960afcfb727b6f5a47eeae808ac855f31dd01)?

**Comment by bbhtt** [comment]
Yes

**Comment by kjxbyz** [comment]
@bbhtt Please reopen this issue. Thank you!
