### ISSUE TITLE
Mark MendeleyDesktop as EOL 

### ISSUE THREAD

**Issue by yakushabb** [flathub/flathub#5765]
Mendeley Desktop appears to have been archived without being marked as EOL.

https://github.com/flathub/com.elsevier.MendeleyDesktop

I think @bbhtt or other volunteers might know a way to mark the application as EOL.

**Comment by bbhtt** [comment]
See the description, it was archived because the maintainer deleted their account. Do you wish to EOL it?

**Comment by yakushabb** [comment]
Thanks. I dont.
