### ISSUE TITLE
Move com.github.quaternion to io.github.quotient_im.Quaternion

### ISSUE THREAD

**Issue by KitsuneRal** [flathub/flathub#5772]
In order to verify my GitHub-hosted application (https://github.com/flathub/com.github.quaternion), I was told I have to change its app-id. How do I go around it - can I just request the repo to be renamed (if yes, consider this a request), or should I submit the application afresh and EOL the old repo?

**Comment by bbhtt** [comment]
Needs a new submission, see https://docs.flathub.org/docs/for-app-authors/maintenance#renaming-the-flatpak-id
