### ISSUE TITLE
403 "Forbidden" error on automatic build after merge request

### ISSUE THREAD

**Issue by be1** [flathub/flathub#5801]
Hello,
I hope this is the correct place to fill an issue on buildbot:

Updating QSpeakers (fr.free.brouits.qspeakers), the pull request triggered an automatic buildbot test that failed with error 403 in some web api, while the actual build works well actually on a local machine.

https://github.com/flathub/fr.free.brouits.qspeakers/pull/7#issuecomment-2452158775

```
Performing POST request to https://hub.flathub.org/api/v1/token_subset
Request failed, retrying in 10 sec...Status code: 403
```

The full traceback is here:
https://buildbot.flathub.org/#/builders/6/builds/158338

Is there a mean to fix this from my side ?

**Comment by bbhtt** [comment]
No, a token expired on our side. Just do a rebuild by commenting `bot, build`

**Comment by be1** [comment]
Many thanks  for your reactivity and reply !
