### ISSUE TITLE
Add repo fail

### ISSUE THREAD

**Issue by Pyras00** [flathub/flathub#5805]
Trying to add repo get can't load uri https://dl.flathub.org/repo/flathub.flatpakrepo: [6] could not resolve hostname

**Comment by bbhtt** [comment]
That sounds like some DNS issue on your end or something blocking the connection. Are you able to reach the URL through the browser?

**Comment by Pyras00** [comment]
Server can't find address refused
Server 192.168.49.1
Address 192.168.49.1#53

**Comment by bbhtt** [comment]
That sounds like a DNS issue on your end. Try changing your DNS servers.
