### ISSUE TITLE
"Commiting build" fails

### ISSUE THREAD

**Issue by issakomi** [flathub/flathub#5806]
It seems like a lot of builds fail at this point.

![Screenshot 2024-11-03 at 10-11-12 Build of com github AlizaMedicalImaging AlizaMS(test)](https://github.com/user-attachments/assets/f177a806-4dd1-4aeb-afb9-b7472dd8ecb9)

**Comment by bbhtt** [comment]
We are aware, the token on the repo server expired and we are trying to reach the person who has access to it.

**Comment by issakomi** [comment]
Thank you!

**Comment by Nordup** [comment]
What is the status of the problem? Do you know when approximately it will be fixed?

**Comment by bbhtt** [comment]
This should be resolved now.
