### ISSUE TITLE
[Ownership Transfer] io.frappe.books

### ISSUE THREAD

**Issue by kskarthik** [flathub/flathub#5812]
I request to transfer the flathub ownership to @akshayitzme who is one of the upstream authors.

Although, I  will still continue maintain the flatpak updates. The upstream will have control over it. They will do the flathub verification process etc...

**Comment by bbhtt** [comment]
Added

**Comment by kskarthik** [comment]
@akshayitzme i believe you could now login to flathub (with github) & see the verification section https://flathub.org/apps/manage/io.frappe.books

**Comment by akshayitzme** [comment]
> @akshayitzme i believe you could now login to flathub (with github) & see the verification section https://flathub.org/apps/manage/io.frappe.books

Sorry for the delayed response. I started with the steps. It requires me to complete a verification similar to a domain verification, by placing a token in the `.well-known` directory. I will get in touch with the Frappe Team to complete the process.

**Comment by kskarthik** [comment]
@akshayitzme hi, is there any progress on verification from the frappe team?

**Comment by akshayitzme** [comment]
> [@akshayitzme](https://github.com/akshayitzme) hi, is there any progress on verification from the frappe team?

not yet. I'm following up

**Comment by kskarthik** [comment]
@akshayitzme any update so far?

**Comment by akshayitzme** [comment]
CC: @rmehta
