### ISSUE TITLE
Is flathub beta the right place for pre-alpha releases?

### ISSUE THREAD

**Issue by grimmy** [flathub/flathub#5815]
I have an odd question I'm hoping you all can maybe give me some insight on. I'm the lead developer of Pidgin instant messenger and we're finally getting to the point of creating an experimental preview release of Pidgin 3. We're targeting the end of the calendar year for this release.

Obviously since this is an experimental release we don't want to put it on the flathub stable, but as I mentioned in the summary this is a pre-alpha release as well. I've read through https://discourse.flathub.org/t/how-to-use-flathub-beta/2111 and this seems like an acceptable use case, but some confirmation would be appreciated. 

We currently have our manifest and everything in our source tree, but I assume we would need to get a new repository added under the flathub organization to get cloud builds and everything running?

Also Pidgin 2 and Pidgin 3 as installable side by side, so the new repository would be named im.pidgin.Pidgin3 which is what we're using in our manifests.

So am I understanding all of this correctly, if not please let me know and how we can proceed.

**Comment by razzeee** [comment]
Yes, that's fine, as long, as you don't build/change it nightly.

**Comment by hfiguiere** [comment]
also be aware that there is no way to redirect people to the `stable` branch when the testing period is over. and the beta always have precedence over stable.

**Comment by grimmy** [comment]
That's some good information. My concern with putting it in stable is that it will get more attention than we can support right now.

As for the precedence, I assume a 2.90.0 on beta won't take precedence over a 3.0.0 on stable right? Or will we just need to delete the beta versions when we get to stable releases?

**Comment by bbhtt** [comment]
> As for the precedence, I assume a 2.90.0 on beta won't take precedence over a 3.0.0 on stable right? Or will we just need to delete the beta versions when we get to stable releases?

It's about the Flatpak branch `//beta`, the software version doesn't matter.
