### ISSUE TITLE
Add access to com.prusa3d.PrusaSlicer

### ISSUE THREAD

**Issue by xarbit** [flathub/flathub#5820]
I kindly request the transfer of ownership for the com.prusa3d.PrusaSlicer repository. 
Please include the following, official upstream developers from @Prusa3D to the repository. 

•	@lukasmatena
•	@SachCZ

We are in active communication and we have agreed on this transfer.

thanks 🙏

**Comment by bbhtt** [comment]
Added please make sure to accept within a week.
