### ISSUE TITLE
Applying for maintainership of org.jellyfin.JellyfinServer

### ISSUE THREAD

**Issue by lwbt** [flathub/flathub#5849]
> * https://github.com/flathub/org.jellyfin.JellyfinServer - Last published version is 11 months old. 2 new minor releases (10.9 and 10.10 last weekend) have been released since then and several bugfix releases. I opened a pull request for 10.9 upgrade which has not been answered/reviewed by the maintainer. Dependabot PRs and issues have been ignored for a few months. I also have a branch in the work for a 10.10 upgrade. Edit: 10.10 just built successfully with latest dependencies and SDK.
> 
>     * https://github.com/flathub/org.jellyfin.JellyfinServer.Plugin.IntelComputeRuntime - Same maintainer, would be a good idea to keep an eye on it.
> 
> 
> **I'd like to apply for maintainership.**

https://github.com/flathub/flathub/issues/3693#issuecomment-2442708600

Original issue to add Jellyfin to Flathub: https://github.com/flathub/flathub/pull/3998

**Comment by bbhtt** [comment]
cc @istori1 

Do you have any past contributions to the app or the flathub repo?

> . I also have a branch in the work for a 10.10 upgrade. Edit: 10.10 just built successfully with latest dependencies and SDK.

Can you open a PR for this?

**Comment by lwbt** [comment]
> cc @istori1
> 
> Do you have any past contributions to the app or the flathub repo?
> 
> > . I also have a branch in the work for a 10.10 upgrade. Edit: 10.10 just built successfully with latest dependencies and SDK.
> 
> Can you open a PR for this?

Do you mean these or something else?

- https://github.com/flathub/org.jellyfin.JellyfinServer/pull/354
- https://github.com/flathub/org.jellyfin.JellyfinServer/pull/432

I would prefer that PR 354 gets merged first, creates a 10.9.z release and then merge PR 432 with 10.10.z to have eventual migration issues covered for users who are still on 10.8.z. I had no issues, but better be safe than sorry.

**Comment by bbhtt** [comment]
Send you the invite
