### ISSUE TITLE
Blackmagic DaVinci Resolve

### ISSUE THREAD

**Issue by cassidyjames** [flathub/flathub#585]
There's a big long thread about installing DaVinci Resolve on Linux at https://forum.blackmagicdesign.com/viewtopic.php?f=21&t=56878&hilit=linux

At least one person has recommended Flatpaking it up to make the installation process easier, and I'd love to see that taken on and hosted at Flathub. There are even instructions there for downloading the app from Blackmagic's site and generating a .deb file, so I don't believe Flatpaking it would be too extraordinary for someone smart to do :sweat:

**Comment by eszlari** [comment]
You will have to ask Blackmagic for direct download URL to make this possible.

**Comment by bilelmoussaoui** [comment]
Would work on this one if there was an easy way to download the binaries.

**Comment by TingPing** [comment]
Sorry but this isn't a forum to make package requests.
