### ISSUE TITLE
Maintainership of com.pokemmo.PokeMMO

### ISSUE THREAD

**Issue by kyu-n** [flathub/flathub#5856]
Hi,

I am a developer of https://pokemmo.com/. The package which has been available on Flathub [[com.pokemmo.PokeMMO](https://github.com/flathub/com.pokemmo.PokeMMO)] was created by an unassociated user who has orphaned the package (see: #3693).

This package is now completely broken and the game does not start. @PokeMMO & I are requesting access to take over as maintainers of this package and to remove the unassociated users.

**Comment by bbhtt** [comment]
> I am a developer of https://pokemmo.com/. T

Is there a way for me to verify this? Something that connects the GitHub account to the site?

Can you upload something to `/.well-known` or is the account linked somewhere?

**Comment by kyu-n** [comment]
> > I am a developer of https://pokemmo.com/. T
> 
> Is there a way for me to verify this? Something that connects the GitHub account to the site?
> 
> Can you upload something to `/.well-known` or is the account linked somewhere?

My work email `kyu@pokemmo.com` is verified and publicly visible on my github profile. I have a publicly accessible community profile available at https://forums.pokemmo.com/index.php?/profile/9-kyu/ as well.

If you need more, please let me know

**Comment by bbhtt** [comment]
Sent invites to both.
