### ISSUE TITLE
net.sourceforge.paulstretch was put to readonly by error

### ISSUE THREAD

**Issue by nbenitez** [flathub/flathub#5861]
[I submitted net.sourceforge.paulstretch](https://github.com/flathub/flathub/pull/3526) app in 2022 and it got [published](https://flathub.org/apps/net.sourceforge.paulstretch) but it seems by error I was not added as owner and so Flathub automatically put repo to [read-only](https://github.com/flathub/net.sourceforge.paulstretch).

I found out about this problem recently when I was about to update runtime and some dep versions.

Please add me as packager/owner of Paulstretch app and unset readonly status, I want to update app to last 24.08 runtime and also its FLTK dep as it now there's a new FLTK version that supports Wayland.

Regards,

**Comment by bbhtt** [comment]
You forgot to accept the invite, it had no maintainers.

Unarchived and invited you back.

**Comment by nbenitez** [comment]
Thanks!!
