### ISSUE TITLE
flathub bot needs manual intervention with Kvantum runtime update

### ISSUE THREAD

**Issue by Gpinchon** [flathub/flathub#5865]
It seems flathub bot [keeps banging its head against the wall](https://github.com/flathub/org.kde.KStyle.Kvantum/pull/36), failing to update the necessary dependencies for Kvantum's new version. This means automatic build keeps failing because it cannot find Qt6... Version 1.1.3 brings critical fixes to Kvantum and this update seems mandatory.

**Comment by Gpinchon** [comment]
I'm not sure I understand what you expect from me, do you want me to create a merge request ?
I can try but I've never contributed to flathub and the time it would take me to understand how it works would certainly suffice to someone with expertise to do the update.

**Comment by Gpinchon** [comment]
I did but they don't seem to be active anymore since they already ignored a 6 months old request to update the runtime to 1.1.0

**Comment by bbhtt** [comment]
They are active.

I don't see any issues from you here https://github.com/flathub/org.kde.KStyle.Kvantum

**Comment by bbhtt** [comment]
Well you said 

> I did 

but that issue is not opened by you.

Anyway, updating it to the latest version is up to the maintainers. There is no reason to interfere.

**Comment by Gpinchon** [comment]
Yes you're right sorry, I realized that just after posting my comment.
I opened a new issue, I'll wait and see...
