### ISSUE TITLE
add me as mantainer of com.jetbrains.IntelliJ-IDEA-Ultimate and com.jetbrains.IntelliJ-IDEA-Community

### ISSUE THREAD

**Issue by xanscale** [flathub/flathub#5870]
i'm already the mantainer of Android Studio flatpak wrapper.

as requested from this issues, i can help for this other 2 apps, (that are almost the same :D )

https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/issues/108
https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community/issues/103

@bbhtt  @barthalion

**Comment by x80486** [comment]
> @x80486 can you confirm?

Yes, I can confirm that. Alessandro have been maintaining Android Studio for a while, so he should be quite familiar with JetBrains' products already.
