### ISSUE TITLE
Make flatpak: protocol

### ISSUE THREAD

**Issue by regs01** [flathub/flathub#5873]
URI with flatpak: protocol will make operation between hub and client installers/managers easier. Steam has it, snap has it etc. There would be no need for flatpak files flooding Downloads folder.

It doesn't need much of option in URL. Just action, app id, version and source hub, with last two being optional.

Something like `flatpak://info/com.valvesoftware.Steam` to just open it in client, `flatpak://install/org.onlyoffice.desktopeditors` directly to install it.

**Comment by bbhtt** [comment]
See https://github.com/flathub-infra/website/issues/919
