### ISSUE TITLE
Consider unifying filesystem rights for emulators

### ISSUE THREAD

**Issue by Pixelnarium** [flathub/flathub#588]
In my personal experience the standard rights given by the maintainers are pretty confusing.

[Dolphin](https://github.com/flathub/org.DolphinEmu.dolphin-emu/blob/master/org.DolphinEmu.dolphin-emu.json) allows **host:ro**, [FS-UAE](https://github.com/flathub/net.fsuae.FS-UAE/blob/master/net.fsuae.FS-UAE.yml) allows **home**, [mGBA](https://github.com/flathub/io.mgba.mGBA/blob/master/io.mgba.mGBA.json) allows **host:rw**, [Nestopia](https://github.com/flathub/ca._0ldsk00l.Nestopia/blob/master/ca._0ldsk00l.Nestopia.json) allows **home:ro** and [ScummVM](https://github.com/flathub/org.scummvm.ScummVM/blob/master/org.scummvm.ScummVM.json) allows **xdg-documents**.

5 Emulators, 5 different rights. Maybe there are more, just checked these 5. I know that you can override it to your personal needs. For a beginner that normally means that you have to open up a terminal and type strange things into it. That is not a problem for me, but a problem for beginners. Sometimes a portal gives you the right to the file through the open dialog but maybe not always. But if it is handled through portals then "no rights" may be possible?

I think that (as a group "emulators") everything should be at least "host:ro" (and host:rw in extreme cases like mGBA) because you just don't know where the user stores the files. Every experienced user can now override it when needed.

Overall I think when applications in general are doing nearly the same stuff they should have the same rights.

**Comment by TingPing** [comment]
Some emulators suck and write save files to the dir that the rom is in. That is why `mgba` is `rw`.

**Comment by TingPing** [comment]
Honestly I suggest just opening a PR against the outliars like Nestopia or whatever. Explain why its needed and go from there.

I do not think the category of app has any actual bearing on what the permissions should be nor do I think Flathub should enforce anything like that.
