### ISSUE TITLE
Please enable automatic merge of PR

### ISSUE THREAD

**Issue by sblantipodi** [flathub/flathub#5884]
Hi there,
as discussed with @barthalion on Element my software is built with a CI after 
all tests are done and passed.

The build environment is 1:1 with the test one so really no need to add manual steps to my CI.

Is it possible to enable automatic merging of the PR once all the statuses are green or to remove the blocking feature that prevents the PR to be merged when the status are running?

Is it also possible to enable GitHub Actions? I have this error:
remote: Permission to flathub/org.dpsoftware.FireflyLuciferin.git denied to github-actions[bot].

This is the repo
https://github.com/flathub/org.dpsoftware.FireflyLuciferin

Thank you guys, I'm loving flathub.
If it's not possible, no problem I will do it manually. 

But it would be cool to have this feature enabled.

**Comment by bbhtt** [comment]
> The build environment is 1:1 with the test one so really no need to add manual steps to my CI.

I don't see any workflows in your CI https://github.com/sblantipodi/firefly_luciferin/blob/master/.github/workflows/ that builds using the Flatpak runtimes.

So clearly it is not 1:1.

**Comment by sblantipodi** [comment]
ok no problem thanks
