### ISSUE TITLE
Add me as maintainer to GNOME design apps.

### ISSUE THREAD

**Issue by A6GibKm** [flathub/flathub#5885]
I have maintainer role at the https://gitlab.gnome.org/World/design/ group, I would like to request push permission for the following apps.

- https://github.com/flathub/org.gnome.design.AppIconPreview
- https://github.com/flathub/org.gnome.design.IconLibrary/
- https://github.com/flathub/org.gnome.design.SymbolicPreview
- https://github.com/flathub/org.gnome.design.Palette/
- https://github.com/flathub/org.gnome.design.Typography/
- https://github.com/flathub/org.gnome.design.Contrast/

**Comment by bbhtt** [comment]
Probably easier if I can give the flathub/gnome team access to these. These were likely pre-merge action doing that.

**Comment by bbhtt** [comment]
Added flathub/gnome to all, some already had it beforehand. You should have access through that team.

**Comment by A6GibKm** [comment]
thanks!
