### ISSUE TITLE
Add maintainer to com.mattjakeman.ExtensionManager

### ISSUE THREAD

**Issue by mjakeman** [flathub/flathub#5892]
Hi, could @oscfdezdz please be added as a maintainer to Extension Manager (https://github.com/flathub/com.mattjakeman.ExtensionManager).

Apologies if there's a proper process for this, I wasn't able to find any docs on it - thanks!

**Comment by bbhtt** [comment]
Added

docs are at https://docs.flathub.org/docs/for-app-authors/maintenance#maintainer-access-to-flathub-application-repository
