### ISSUE TITLE
[Security] Request sended assets to flathub to be signed with domain private key.

### ISSUE THREAD

**Issue by nintyfan** [flathub/flathub#5894]
Looking at snap problems with cryptocurrency tools, I wonder if there was an option to enhance security with flathub.
I am not sure if flathub already doing something similar, but why do not allow package vendors to check package was signed by domain (web) owner? In this case, flathub will download public key of web page and check if package is really signed by this domain's key.
For example:
1. I am owner of pl.cryptocurrency.wallet package
2. I sign this package by wallet.cryptocurrency.pl domain private key
3. I click given checkbox
4. User will see enhanced security of package string on flathub

What do you think?

**Comment by bbhtt** [comment]
> Looking at snap problems with cryptocurrency tools,

Not sure what problem you are referring to but the for the ones I know the developer uploading the app was malicious. So letting everyone sign things with their own keys won't change anything. 

> I am not sure if flathub already doing something similar, but why do not allow package vendors to check package was signed by domain (web) owner? In this case, flathub will download public key of web page and check if package is really signed by this domain's key.

Flathub provides the builds, and the contents of the ostree repository are signed by Flathub's GPG key. It's not possible to let individual packagers sign those contents using their keys.

What you are describing is kind of how "Verified" apps on Flathub work. If the upstream vendor verifies the app on Flathub and maintains it, that practically archives the same thing.

**Comment by nintyfan** [comment]
I refer to identity of app vendors. Flatpak's names are reversed domain name. If people could sign with one's key, we are sure, owner of app sign it.
