### ISSUE TITLE
offer an electron runtime and build some of its apps

### ISSUE THREAD

**Issue by muayyad-alsadi** [flathub/flathub#59]
[electron](https://electron.atom.io/) is a platform for making desktop apps using html and js
there so [many electron apps](https://electron.atom.io/apps/) including:

* [atom](https://atom.io/)
* [vscode](https://github.com/Microsoft/vscode)
* [upterm](https://github.com/railsware/upterm)

and some non-opensource like slack

it would be awesome if we build an electron runtime at least one app like atom.

here is how atom for fedora is built in copr

https://github.com/FZUG/repo/tree/master/rpms/atom

**Comment by TingPing** [comment]
There is some progress on making electron apps buildable: http://blog.manuq.com.ar/posts/building-electron-apps-offline-for-flathub/

**Comment by muayyad-alsadi** [comment]
a short term solution is like atom in copr, add a checkbox to allow build online instead of offline
I know this is bad, but it's good enough as a start

**Comment by TingPing** [comment]
Flathub currently has no plans to allow that.

**Comment by manuq** [comment]
As soon as [a GTK3 electron build happens](https://github.com/electron/electron/issues/2927) I will check which modules are missing from the runtime and propose a new shared-modules to easly include them.

**Comment by bil-elmoussaoui** [comment]
@manuq One bad thing about electron is that they're still using gconf instead of dconf :( Other than this, i don't know if there's any other modules that might be missing, unless something specific per app like libnotify for notifications

**Comment by TingPing** [comment]
@bil-elmoussaoui You can see a list: https://github.com/flathub/flathub/pull/74

**Comment by adityashah1212** [comment]
@TingPing  I may be wrong, and if so I apologize, but wouldn't we also need node.js in the base app as well for it to work?

**Comment by TingPing** [comment]
@adityashah1212 The baseapp is just dependencies needed for electron apps and electron apps bundle everything else on top.

**Comment by adityashah1212** [comment]
Wouldn't it be better to have nodejs in the base or perhaps on common modules, since all electron apps will need it anyway?

**Comment by TingPing** [comment]
@adityashah1212 Currently no Electron apps are built from source on flathub because that is nearly an impossible task (you have to fight the tools, extract all deps manually, etc). So nodejs is meaningless for the use-case we use it for now of proprietary binary applications. Once we are at the point of Electron being buildable there will probably be some variation on what version of node they want and you are going to be downloading hundreds of packages so its not like node is a big deal.

**Comment by prcastro** [comment]
With the Electron base now on Flathub (and Atom/VSCode there too) I believe this is no longer an issue

**Comment by TingPing** [comment]
We still aren't at a point where we can easily build electron apps from source but sure this specific issue can be closed.
