### ISSUE TITLE
App Listing Quality has lots of false negatives

### ISSUE THREAD

**Issue by ilya-fedin** [flathub/flathub#5900]
I checked the list on two apps I maintain (https://flathub.org/apps/org.telegram.desktop and https://flathub.org/apps/io.github.kotatogram) and it looks like quite a lot of failed checks in the list are false negatives.

org.telegram.desktop:
1. App Icon - No baked-in shadows: I don't see any shadow on the icon
2. App Name - Just the name: It's just the name... This is the official name of the app and its name like that in almost every store (Flathub, Snap Store, Microsoft Store), the only exception being Mac App Store where it was forced to be renamed to Telegram Lite.
3. Summary - No weird formatting or punctuation: While technically it doesn't fit the rules, I wouldn't call it weird, it seem to look awesome on branding preview: ![](https://github.com/user-attachments/assets/7041eb74-dc7b-4f0d-b626-d260e0f317d6)
4. Screenshots - Just the app window: It's just the app window, nothing more...
5. Screenshots - Default settings: It's default settings!
6. Screenshots - Include window shadow and rounded corners: It does include shadows and there seem to be no rounded corners using default settings of the environment it was taken on...
7. Screenshots - Up to date: Should screenshots be updated only after major changes or even after any minor change? If the former, I would say it's up to date, if the latter... Well, not sure how realistic it would be to update after any minor change.

io.github.kotatogram:
1. App Icon - No baked-in shadows: Again, there's no shadow...
2. App Name - Just the name: Again, it's just the name...
3. Summary - No weird formatting or punctuation: I don't see any weird punctuation here? Yeah, it violates "Doesn't repeat the app name" but not this one
4. Screenshots - Reasonable window size: While not technically fits the rules, I'd say the window size on screenshot is reasonable and looks nice

**Comment by bbhtt** [comment]
@flathub/quality-moderation should be able to help.

**Comment by bertob** [comment]
A few of these were indeed mistakes, fixed those. As for the remaining ones:

org.telegram.desktop:
- Name: I'm guessing this is in reference to the "Desktop" part, is there a reason why it's not just "Telegram"?
- Summary: Formatting aside, this summary also doesn't tell you anything about what the app does. I'd suggest something like "Talk to your friends", or something else that's not just generic adjectives
- Shadows: There's a white background behind the screenshot, it should be just the window screenshot with a transparent shadow

io.github.kotatogram:
- Name: See above, probably also refers to the "Desktop" part
- Size: Seeing as the screenshot has to be retaken anyway, might as well fix that as well at the same time

**Comment by hfiguiere** [comment]
> Name: I'm guessing this is in reference to the "Desktop" part, is there a reason why it's not just "Telegram"?

That's because back then the reviewers didn't reject this kind of naming. We just push against harder now, but legacy is debt.

**Comment by hfiguiere** [comment]
> io.github.kotatogram:
>
>    Name: See above, probably also refers to the "Desktop" part

This one also whould be rejected. It's a github based ID it MUST have 4 component. Strictly enforced. Again legacy is debt.

Both cases can be solved by resubmitting the package with a new name, but this is a disruptive process and the reviewers will pick it appart. So it's not worth the effort. In the second case this also prevent from "verifying".

**Comment by bbhtt** [comment]
If passing the guidelines is the goal, it's best to just drop `Destkop` from the `<name>`, I don't see `Desktop` being necessary here in either case.

**Comment by ilya-fedin** [comment]
> * I'm guessing this is in reference to the "Desktop" part, is there a reason why it's not just "Telegram"?

I'm not sure but I guess it's because there are other clients. On macOS there's Telegram for macOS and for any platform there's Telegram Web. Moreover, it seems that some software centers on Linux even provide Telegram Web in search results...

> * Formatting aside, this summary also doesn't tell you anything about what the app does. I'd suggest something like "Talk to your friends", or something else that's not just generic adjectives

I'm not sure it's possible to change but I will ask...

> * Shadows: There's a white background behind the screenshot, it should be just the window screenshot with a transparent shadow

Oh, indeed...

> * Name: See above, probably also refers to the "Desktop" part
> 
> * Size: Seeing as the screenshot has to be retaken anyway, might as well fix that at the same time

Fair enough...

> It's a github based ID it MUST have 4 component.

What's the problem with 3 components? io.github.kotatogram.kotatogram will just be weirder...

**Comment by hfiguiere** [comment]
> What's the problem with 3 components? io.github.kotatogram.kotatogram will just be weirder...

Component 3 is the org / user and 4 is the app name. That's the way it is.

But then it would be `io.github.kotatogram.kotatogram-desktop`  to be verifiable. It's not weirder. It's just like that.

Note that existing app have gotten an exception to let the linter pass and there is no plan to change that.

**Comment by ilya-fedin** [comment]
> io.github.kotatogram.kotatogram-desktop

Why exactly `kotatogram-desktop`?

**Comment by hfiguiere** [comment]
![image](https://github.com/user-attachments/assets/12c79b0a-9a1c-4930-ae50-5e83181c4389)

**Comment by ilya-fedin** [comment]
Is that enforced? Can't another app name be chosen, like `Kotatogram` or `KotatogramDesktop`?

**Comment by bbhtt** [comment]
> Is that enforced?

Yes but only for new submissions

**Comment by ilya-fedin** [comment]
> Yes but only for new submissions. See https://docs.flathub.org/docs/for-app-authors/requirements#code-hosting

Thanks, the link clears it

**Comment by ilya-fedin** [comment]
> * Shadows: There's a white background behind the screenshot, it should be just the window screenshot with a transparent shadow

Maybe have a note in the guidelines that screenshots should be transparent to avoid future confusion?

**Comment by ilya-fedin** [comment]
> As for the remaining ones:

What about the up to date one? I see it still fails but it's not clear whether

> Should screenshots be updated only after major changes or even after any minor change?

**Comment by ilya-fedin** [comment]
Oh, ok, thanks. Will see whether it disappears after update...

**Comment by ilya-fedin** [comment]
org.telegram.desktop semm to be ok now but io.github.kotatogram fails on "Screenshots - Good content". What's wrong with the content? It's not that different to the previous screenshot and it passed with the previous one iirc.

**Comment by bertob** [comment]
A chat app with just two chats doesn't look very close to what it's like in real-world use. At least having 5 or so chats in there to fill the window height would be nice.

**Comment by ilya-fedin** [comment]
I have a problem with updating screenshots for Kotatogram: they were updated but URL is the same, I triggered a package rebuild but flathub still shows the old screenshots...

**Comment by razzeee** [comment]
They have been update in the source, we're caching pretty heavily on the website, so you likely just need to wait some more.

**Comment by razzeee** [comment]
> > you likely just need to wait some more
> 
> How much? The website says "Built 1 day ago" so I guess 24 hours have already passed.

it's a bug, due to no metainfo change, the used md5 (presumably of the metainfo) did not change - thus the screenshots only updated partially

https://github.com/flathub/flathub/issues/5927

https://dl.flathub.org/media/io/github/kotatogram/63f0075c53e2675179e69b0e40499f95/screenshots/image-1_orig.png is still wrong, while https://master.flathub.org/media/io/github/kotatogram/63f0075c53e2675179e69b0e40499f95/screenshots/image-1_orig.png got the correct image

**Comment by ilya-fedin** [comment]
it's finally all checked
