### ISSUE TITLE
Request to be a Maintainer of chat.revolt.RevoltDesktop

### ISSUE THREAD

**Issue by RayJW** [flathub/flathub#5904]
I would like to assist the developers of Revolt with their Flatpak packaging. While there is no issue to reference, I did talk to the developers on their own platform. Particularly @insertish has shown support for this, as they surely can confirm here :) I have maintainership of one other Flatpak and contributed numerous times across a number of Flatpaks. I hope that is enough to request becoming a maintainer of this Flatpak ^^

In the past, this was the place to ask, as far as I am aware.

**Comment by bbhtt** [comment]
Ok once someone confirms I can send you access. Revolt is unofficially maintained, is there any interest to maintain it officially by upstream?

**Comment by insertish** [comment]
Hello, confirming I'm happy for them to become a maintainer.

w.r.t upstream; we don't currently have anyone versed in Flatpak on our team who could potentially maintain this.

**Comment by RayJW** [comment]
> w.r.t upstream; we don't currently have anyone versed in Flatpak on our team who could potentially maintain this.

I think it's also simply a question, whether the team is happy with endorsing the Flatpak. From the [docs](https://docs.flathub.org/docs/for-app-authors/verification/):

> Verification is a process by which Flathub can confirm that an app is published by its original developer or a third party approved by the developer. This is done by verifying the developer's identity using a link to their website or to their account on a source code hosting site. The methods available for verification depend on the app ID.

If you'd be happy with this interpretation, I'll gladly assist with getting the Flatpak verified. This would be great, also for ease of use, as some distros like Mint per default don't show unverified Flatpak packages in their store.

**Comment by bbhtt** [comment]
I added you, looks like @insertish already has access. SO you should be able to verify if you want.
