### ISSUE TITLE
Request to add maintainers to org.sasview.sasview

### ISSUE THREAD

**Issue by jamescrake-merani** [flathub/flathub#5905]
I'm currently the only developer from upstream designated as a maintainer for SasView. At our last meeting yesterday, we agreed the following people should also be added as maintainers:

@krzywon
@rozyczko
@wpotrzebowski
@butlerpd
@gonzalezma
@backmari

Could we please add all of these users as maintainers? They are all also involved with development upstream.

**Comment by bbhtt** [comment]
Added everyone, make sure to accept the respective invites within a week
