### ISSUE TITLE
Add HarmonyHoney as maintainer for net.hhoney.rota

### ISSUE THREAD

**Issue by cassidyjames** [flathub/flathub#5910]
The source repo is [HarmonyHoney/ROTA](https://github.com/HarmonyHoney/ROTA); it'd be nice for @HarmonyHoney to be able to manage [flathub/net.hhoney.rota](https://github.com/flathub/net.hhoney.rota) and thus the app in the developer portal on Flathub.

**Comment by bbhtt** [comment]
They already have access that's what the @ ping on /merge command does.

**Comment by cassidyjames** [comment]
Ah @HarmonyHoney can you double-check that, then? :)
