### ISSUE TITLE
toolchain-i386 is missing on most arches

### ISSUE THREAD

**Issue by stsp** [flathub/flathub#5915]
### Questions or Feedback

I am using `org.freedesktop.Sdk.Extension.toolchain-i386`
to build my app. My app is cross-platform, but
it needs `toolchain-i386` on any platform, along
with the native toolchain.
I've found that `org.freedesktop.Sdk.Extension.toolchain-i386`
is only provided for x86_64.
Would it be possible to provide that
extension on other arches, at least on
aarch64?

**Comment by hfiguiere** [comment]
why would it need that? and how much sense does this make on other arch?

**Comment by stsp** [comment]
> why would it need that?

My app contains a few i386 asm
files that I need to assemble and
link with cross binutils.

> and how much sense does this make on other arch?

Just like any distro provides the
cross-compilation tools. I.e. on
aarch64 ubuntu or fedora I can
easily install the i386 toolchain.
Its there for cross-compiling.

**Comment by stsp** [comment]
Note: my app uses simulation
framework, so even when the
resulting file is non-native, it
still runs.

**Comment by hfiguiere** [comment]
there is no cross-compilation tools for flathub. This i386 SDK is used to build legacy code to run on x86_64. Nothing more.

Also not knowing what your app is make it even harder to understand why you want to do that.

**Comment by stsp** [comment]
My app is called [dosemu2](https://github.com/dosemu2/dosemu2/).
It has the simulation framework within,
and it needs to assemble a few i386
files.

**Comment by stsp** [comment]
Basically it just always needs an
i386 cross-toolchain. its not a problem
on distros.

**Comment by stsp** [comment]
> This i386 SDK is used to build legacy code to run on x86_64. Nothing more.

Well at least on x86_64 it suits
for my needs. I do `CROSS_LD=i686-unknown-linux-gnu-ld`
and it works fine. Of course besides
the fact that native x86_64 linker has
the --32 flag, so on x86_64 the cross-toolchain
is an optional dep.
So if toolchain-i386 is not what I need,
then what do you suggest for me on aarch64?

**Comment by hfiguiere** [comment]
to build it yourself.
