### ISSUE TITLE
Quality guideline problems for Oku

### ISSUE THREAD

**Issue by emmyoh** [flathub/flathub#5919]
### Flathub store page link

https://flathub.org/apps/details/io.github.OkuBrowser.oku

### Questions or Feedback
- Screenshots - Default settings: Screenshots were taken on GNOME with the default appearance settings; this app is using GTK4 and `libadwaita` with no application-specific style changes. Half of the screenshots were in light mode, and the other half were in dark mode. What issues were observed with these screenshots?
- Screenshots - Reasonable window size: All screenshots were taken with the window sized at 1000x700 pixels, as [recommended in the Flathub documentation](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines/#reasonable-window-size). What screenshots were problematic here?
- Screenshots - Good content: I'd appreciate tips on how to improve certain screenshots in this regard. If you could point to specific examples and suggest alternatives, that'd be very helpful.
Thank you!

**Comment by bertob** [comment]
Hi, thanks for reaching out!

- Default settings: The non-default setting in question are the window controls, the default is close-only.
- Reasonable size: That looks like an oversight, but if you're retaking the screenshot I'd recommend making it a little bit smaller in this case.
- Good content: Screenshots of content apps like image viewers, browsers, etc. should show off great third-party content to emphasize their role as a generic viewer tool. So for a browser, a visually nice website of e.g. an artist or font or something. There are some example websites here: https://gitlab.gnome.org/Teams/Design/example-content

**Comment by emmyoh** [comment]
@bertob Thanks for your reply! I'll keep this feedback in mind the next time I update the screenshots; thank you.
By the way, saw your posts on Mastodon regarding p2panda; would love to learn more about the project from you [if you have the time to chat](https://calendar.app.google/GNXX2o13985pH89k6).
Thanks!

**Comment by bertob** [comment]
Awesome, thanks! As for the p2panda thing, probably not before the holidays, but feel free to shoot me an email or find me on Matrix and we can set something up in the new year :)
