### ISSUE TITLE
Quality guideline problems for IntelliJ IDEA Ultimate

### ISSUE THREAD

**Issue by xanscale** [flathub/flathub#5925]
### Flathub store page link

https://flathub.org/apps/details/com.jetbrains.IntelliJ-IDEA-Ultimate

### Questions or Feedback
Actually i have 2 fail in summary quality checks:

- Understandable for a non-technical person
- No weird formatting or punctuation

Actual summary:

> Leading Java and Kotlin IDE

I don't understand what are the problems.

**Comment by razzeee** [comment]
IDE is something non devs would not understand (so it's technical)

Kotlin and Java are technical too, but I guess that's non negotiable

**Comment by xanscale** [comment]
any suggestion? 

IDE is for "integrated development environment"

**Comment by xanscale** [comment]
> Leading Java and Kotlin editor

it's good ?

**Comment by razzeee** [comment]
let's wait for @bertob

**Comment by bertob** [comment]
> Leading Java and Kotlin editor

Sounds fine :+1:
