### ISSUE TITLE
org.kde.kalm: Enable squash merging and set it as default

### ISSUE THREAD

**Issue by plata** [flathub/flathub#5931]
I can only do a "plain" merge and the commit message is in the form "Merge branch 'master' into". I would like to use squash merge with the commit message defaulting to the PR title.

Please also enable auto merge (also for org.kde.telly-skout).

**Comment by bbhtt** [comment]
squash is already enabled, all 3 enabled is the default, we don't change anything there.

![image](https://github.com/user-attachments/assets/26b2d065-980b-4aaa-a6a7-cce53599ef76)

**Comment by hfiguiere** [comment]
also the last option you selected sticks.

**Comment by bbhtt** [comment]
You can click the drop-down the merge button to change the strategy

![image](https://github.com/user-attachments/assets/85b231e4-9c95-4e84-ba14-b4f6ac1c293c)

**Comment by plata** [comment]
> We generally don't enable auto-merge because the test builds in the PRs are supposed to be tested by maintainers using the test builds posted before merging.

Ok, that's fine for me.

Could you change the settings such that squash merge is the only option in kalm (as per telly-skout)?

**Comment by bbhtt** [comment]
Ok disabled the rest except the squash strategy on `org.kde.kalm`, commit message is set to PR title and details.
