### ISSUE TITLE
Bad icon scaling for Hawkthorne

### ISSUE THREAD

**Issue by MateusRodCosta** [flathub/flathub#5935]
Recently submitted Hawkthorne (https://flathub.org/apps/com.projecthawkthorne.Hawkthorne) to Flathub.
It has a pixel art art style and a pixel art icon to match.

I initially submitted it with neighbor scaling, meaning the 128x128 size looks like this:

![com projecthawkthorne Hawkthorne](https://github.com/user-attachments/assets/30925f7d-6b9e-4379-aabe-db26cc88a1b4)

However after changing to lanczos scaling the 128x128 looks like this:

![com projecthawkthorne Hawkthorne](https://github.com/user-attachments/assets/df677bcb-aa15-4138-bcf0-286a4510802e)

And this is what is shown on flathub right now:

![image](https://github.com/user-attachments/assets/955d8a12-0f39-400a-ba0e-4be641d6c508)

What can be done so scaling is closer to the lanczos scaling which has proven to be high quality for this specific scenario?

**Comment by bbhtt** [comment]
What's the issue? I can't spot any difference with the naked eye.

**Comment by MateusRodCosta** [comment]
Basically many details have been lost on both the neighbor and Flathub version compared to the lanczos one.

Pixel art has a tendency to have a 1px black line around several objects, but here the line has been generally broken on several places, this ends up taking away from the "pixel art" aspect.

**Comment by MateusRodCosta** [comment]
For reference, this is the original:

![hawkthorne](https://github.com/user-attachments/assets/593c5619-0d3e-4df9-bc46-53a0b183ed99)

From https://github.com/hawkthorne/hawkthorne-journey/blob/master/templates/linux/hawkthorne.png

**Comment by bbhtt** [comment]
The image didn't get updated on the CDN endpoint, the non-CDN endpoint shows the second image which I assume is what you want. 

https://master.flathub.org/media/com/projecthawkthorne/Hawkthorne/80acf7295b466505807e2750f87aaad6/icons/128x128/com.projecthawkthorne.Hawkthorne.png

This is https://github.com/flathub/flathub/issues/5927

If you change something in metainfo, it will force an update. You will need to wait for a few hours after that regardless as it is cached by Fastly.

**Comment by bbhtt** [comment]
Closing this then, subscribe to the other issue. You can always add a patch to change something.
