### ISSUE TITLE
Add Trisquel to Supported Distro List

### ISSUE THREAD

**Issue by asddsaz** [flathub/flathub#594]
**Suggestion**: Add Trisquel as an officially supported distro: https://www.flatpak.org/setup/
In my experience it works if you follow the Ubuntu setup steps. 
**WHY**?: New users may not understand this

**Comment by nedrichards** [comment]
Good idea. Please open an issue against the website repo https://github.com/flatpak/flatpak.github.io/ or better, send a PR implementing it.
