### ISSUE TITLE
add members to io.podman_desktop.PodmanDesktop

### ISSUE THREAD

**Issue by axel7083** [flathub/flathub#5941]
Hello (similar to https://github.com/flathub/flathub/issues/4074#issue-1668496794) ! I am a maintainer of https://github.com/orgs/podman-desktop

Could the following maintainers be added (list from https://github.com/orgs/podman-desktop/teams/maintainers and https://github.com/orgs/podman-desktop/teams/reviewers)

- https://github.com/deboer-tim @deboer-tim
- https://github.com/gastoner @gastoner
- https://github.com/SoniaSandler @SoniaSandler
- https://github.com/feloy @feloy 
- https://github.com/dgolovin @dgolovin 
- https://github.com/axel7083 @axel7083  (myself)

Thanks

cc @benoitf

**Comment by bbhtt** [comment]
>  I am a maintainer of https://github.com/orgs/podman-desktop

Your org membership is private so I can't verify this. Either you should make it public or one of the existing maintainers in https://github.com/flathub/io.podman_desktop.PodmanDesktop/ needs to confirm.

**Comment by benoitf** [comment]
I confirm the list @deboer-tim @gastoner @SoniaSandler @feloy @dgolovin @axel7083 

you can also check that they're committers as part of https://github.com/podman-desktop/podman-desktop/graphs/contributors

**Comment by bbhtt** [comment]
All done. make sure to accept the respective invites within a week
