### ISSUE TITLE
Flathub repo 403 forbidden

### ISSUE THREAD

**Issue by KweezyCode** [flathub/flathub#5946]
![image](https://github.com/user-attachments/assets/6859d974-b807-46c5-b143-2a3a0124ccf1)
what should i do? i cannot update my flatpak apps anymore

**Comment by razzeee** [comment]
https://dl.flathub.org/repo/flathub.flatpakrepo still works fine for me, so it's likely your provider (that url you've posted never worked)

**Comment by KweezyCode** [comment]
> https://dl.flathub.org/repo/flathub.flatpakrepo still works fine for me, so it's likely your provider (that url you've posted never worked)

The problem seems to have resolved itself (I got errors about corrupted object during flatpak update before). closing the issue
