### ISSUE TITLE
Error in appstream.xml.gz metadata prevents searching for packages

### ISSUE THREAD

**Issue by arteymix** [flathub/flathub#5948]
I can't search packages anymore. I'm assuming this is due to a recent metadata update since it was working a few hours ago.

```
flatpak search gnome
```

```
F: Failed to parse /home/poirigui/.local/share/flatpak/appstream/flathub/x86_64/active/appstream.xml.gz file: Error on line 7057 char 29: <p> already set '
      Organic Maps is a free Android & iOS offline maps app for travelers,
      tourists, hikers, drivers and cyclists.
      It uses crowd-sourced OpenStreetMap data and is developed with love by
      ' and tried to replace with ' ('

```

I use Flatpak 1.6.5

**Comment by razzeee** [comment]
are you sure about that version? You should really update...

**Comment by bbhtt** [comment]
Update your Flatpak version.

**Comment by arteymix** [comment]
I'm using Ubuntu 20.04 and this is the latest version of Flatpak available there.

I can install the PPA, but you should consider adjusting the instructions in https://flathub.org/setup/Ubuntu if you consider this version too old.

**Comment by bbhtt** [comment]
We don't provide the PPA, it's up to your distro. Either update your Ubuntu version to something that was released in the last 2 years or contact the PPA maintainer.

**Comment by arteymix** [comment]
Agreed. You should update the minimum Ubuntu release in the setup docs accordingly.
