### ISSUE TITLE
Request to be added as maintainer

### ISSUE THREAD

**Issue by mquevill** [flathub/flathub#5951]
As a maintainer of the Caprine upstream code, I'd like to be added as a maintainer for the Flathub distribution to ensure that the newest releases are available. Especially since the Flathub bot continues to make daily PRs when a new release is detected.

**Comment by bbhtt** [comment]
I sent you an invite, you have to accept within a week.

I'd like to see https://github.com/flathub/com.sindresorhus.Caprine/issues/72 solved by someone, since it is way past the deadline set to 2 months after May 2024.
