### ISSUE TITLE
Adding kiwix team as maintainer of flathub/org.kiwix.desktop

### ISSUE THREAD

**Issue by mgautierfr** [flathub/flathub#5954]
Hi,

Is it possible to add the kiwix's "Lieutenants" team (https://github.com/orgs/kiwix/teams/lieutenants) as maintainers of https://github.com/flathub/org.kiwix.desktop please.

Or, at default, to add @rgaudin and @kelson42 as maintainers (the same way I am).

Thanks

**Comment by bbhtt** [comment]
Teams outside of the flathub org cannot be added, that's a GitHub limitation.

> Or, at default, to add @rgaudin and @kelson42 as maintainers (the same way I am).

Added both, make sure to accept the invite within a week.

**Comment by kelson42** [comment]
@bbhtt Thank you
