### ISSUE TITLE
Request to grant maintainer privilege for io.ente.auth

### ISSUE THREAD

**Issue by ua741** [flathub/flathub#5959]
Hello,

Our team is responsible for managing the Ente Auth application.
Could you please add me (@ua741) and Vishnu (@vishnukvmd) as maintainers of the app?

The current maintainer originally raised the request here: https://github.com/flathub/io.ente.auth/issues/2

Thank you!

**Comment by bbhtt** [comment]
Sent invites to both, make sure to accept within a week.
