### ISSUE TITLE
Official permission to package/maintain ... Deepin Apps on our Flathub repository !!!

### ISSUE THREAD

**Issue by aiamuzz** [flathub/flathub#596]
Hi,

I am no coder, but here is the [PERMISSION](https://github.com/linuxdeepin/developer-center/issues/549#issuecomment-417557672) from the Deepin team to package/maintain their apps on flathub.

Deepin have their own flatpak versions of the apps they distribute on their Deepin Operating System. As you can see above, they have just confirmed that they do not have the time to package/maintain a separate version for the Flathub repository, **appreciate if someone here who is qualified and willing to take over the task of packaging/maintaining the Deepin Apps on Flathub.** 

**As you can see the Deepin team is willing to assist in any way they can** ... as they already have flatpak versions of their apps for their own distribution ... i am guessing that could mean that much less time and effort to add them to flathub repository for anybody who may come forward.

Anybody willing to adopt Deepin Apps on Flathub ???

**Comment by TingPing** [comment]
They are free software so we always had permissions. I'd much rather upstream get involved though since they already maintain their own Flatpak repo it seems like a no-brainer to me.

Anyway closing this since it is just a comment and not really actionable.

**Comment by aiamuzz** [comment]
> they already maintain their own Flatpak repo it seems like a no-brainer to me.
they are good apps ... worth running acroos linux distro's and a very good candidate to be hosted on flathub repo ... their flatpak caters only to Deepin OS ... limiting the reach of good quality apps to other Linux distro's

So i was wondering if you kept this thread open ... may be someone might actually pick up this project ... 

**I am afraid closing this thread would mean ... out of sight ... out of mind !!!**

**Comment by TingPing** [comment]
The purpose of this bug tracker is not to request packages.

**Comment by aiamuzz** [comment]
> The purpose of this bug tracker is not to request packages.

:(

**Comment by aiamuzz** [comment]
@bilelmoussaoui  ... oh thanks for your interest ... there are some good apps that will be good on flathub ... should you decide to invest your time.

About your comment @[hualet](https://github.com/hualet) will be more than helpful ... as he himself has said so [here](https://github.com/linuxdeepin/developer-center/issues/549#issuecomment-417557672) ... he is a better person for the tech speak ... about dependencies and upstream assistance 

:)

**Comment by aiamuzz** [comment]
> @aiamuzz I think the first thing to be done in order to host Deepin apps on Flathub is to have a Deepin runtime. Which must be handled and updated by upstream or at least someone who has an idea which dependencies must be included...
> I can work on adding some basic apps to Flathub but upstream must work on updating them...

I think i would like to take you up on the offer of packaging/maintaining Deepin Apps on flathub ... 

my Deepin OS runs a primitive version of ... `flatpak ... version 0.11.7-1deepin` ... just now i managed to uninstall this Deepin distributed version and replaced it with ... `Flatpak ... version 1.0.1` ... as a side effect ... the Deepin's flatpak version of apps are broken as they depend on the 0.11.7 version(as pasted below) ...

`sudo apt-get install deepin-fpapp-org.deepin.flatdeb.deepin-calculator 
`
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 deepin-fpapp-org.deepin.flatdeb.deepin-calculator : Depends: deepin-fprt-org.deepin.flatdeb.base.platform-15.5 but it is not going to be installed
 libostree-dev : Depends: libostree-1-1 (= 2018.5-1) but 2018.8-1 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```
**I would really look forward to you adopting Deepin Apps to be flatpak'd for flathub ... so i can have them installed on my Flatpak Ver. 1.0.1**
