### ISSUE TITLE
Access to OptiImage

### ISSUE THREAD

**Issue by CarlSchwan** [flathub/flathub#5961]
Hi, can I (and the rest of the kde flathub people) get access to https://flathub.org/apps/org.kde.optiimage

Cheers

**Comment by bbhtt** [comment]
You have it already

![image](https://github.com/user-attachments/assets/445ad760-bd59-4ca3-9cd7-be796da05ae9)

**Comment by bbhtt** [comment]
I guess this is about the app not showing up in your developer portal. In that case, hit the refresh button on the portal and wait for some time. It should appear eventually.
