### ISSUE TITLE
Enable GitHub Discussions by default for all (or all *new*) repositories.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [flathub/flathub#5966]
Summarily, most discussions already occur on GitHub instead of the Discourse forum. Not needing to register a new account is a significant hurdle to participation eliminated. It would clear the issue section from questions.

Additional rationale is available at https://github.com/8go/matrix-commander/issues/68#issue-1237645245:

<blockquote>

I believe that [GitHub Discussions](https://docs.github.com/en/discussions/quickstart#introduction) [^1] would be useful, because it allows questions to be asked without unnecessary triage and closure (as issues necessitate) like a forum does, and provides obvious demonstration of resolution.

[^1]: [`github.com/github/docs/blob/3f4776ee823022ac5394ce61e3f53b72c46d6004/content/discussions/collaborating-with-your-community-using-discussions/about-discussions.md`](https://github.com/github/docs/blob/3f4776ee823022ac5394ce61e3f53b72c46d6004/content/discussions/collaborating-with-your-community-using-discussions/about-discussions.md#about--data-variablesproductprodname_discussions-:~:text=data%20variables.product.prodname_discussions%20%25%7D-,With%20%7B%25%20data%20variables.product.prodname_discussions%20%25%7D%2C,single%20repository%20in%20your%20organization.,-%7B%25%20ifversion%20discussions%2Dclosable)

</blockquote>

**Comment by hfiguiere** [comment]
no

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub/flathub/issues/5966#issuecomment-2561478390

@hfiguiere, that's somewhat succinct. Might I be privy to why?

**Comment by bbhtt** [comment]
These Flathub repos are meant to serve the manifest and deal with packaging related issues. Any project discussion should happen upstream if the app is verified.

For community maintained things, feel free to use issues.

Most of these are maintained by single people and adding discussions upon issues adds another thing everyone has to manage and manage/moderate.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub/flathub/issues/5966#issuecomment-2561760830

@bbhtt, perhaps creating a "question" tag and issue template that is applied to all repositories would be a useful replacement? It would certainly lessen the triage burden if those asking questions can always self-tag their issues as such, whilst retaining the administrators’ abilities to transfer them between repositories.

**Comment by bbhtt** [comment]
We can't retroactively add templates to 3270 repos, it'd consume too much API quota blowing up things and pushing to `master` will cause a new build.

I don't want to enforce labels for newly created repos as well, it should be upto the maintainer to handle them how they like it.

I think you are thinking too much, a plain issue is fine. In most cases unless a repo is getting 10-20 issues per day, labels should not be needed.
