### ISSUE TITLE
Use specific video device for applications?

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [flathub/flathub#5972]
I have a internal webcam for my laptop, and a external one, is there any way to like, tell a application to use a specific one, I know flatpak portals essentially kind of forward access to whatever it thinks is the primary video device, so how do I change that? and can I change that on a per application basis, for example discord uses my external webcam and lets say snapshot uses my internal, just a example.

**Comment by hfiguiere** [comment]
not a flathub issue.
