### ISSUE TITLE
Instructions for installing from apps flathub don't work

### ISSUE THREAD

**Issue by HoboPrimate** [flathub/flathub#60]
The instructions shown don't work:

> flatpak remote-add flathub https://flathub.org/repo/flathub.flatpakrepo
> flatpak --user install flathub org.gnome.Recipes

giving the error "no remote flathub found"

instead you have to either install the remote with --user, or install the flatpak app with no --user

flatpak 0.9.7 on Fedora 26

**Comment by JuanjoSalvador** [comment]
Just

    flatpak install flathub org.gnome.Recipes

and go.

**Comment by alexfornuto** [comment]
```
$ flatpak install flathub org.gnome.Recipes
error: Remote "flathub" not found
```

**Comment by Nakxion** [comment]
error: Nothing matches io.brackets.Brackets.flatpakref in remote flathub

**Comment by TingPing** [comment]
@Nakxion 	Remove `.flatpakref` from the name.

**Comment by dyoungwd** [comment]
run `flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo` in the terminal and everything should then work allowing you to install fltpaks from flathub

**Comment by jayknoxqu** [comment]
You can manually do it with:
**remote-add --user**
```bash
sudo flatpak remote-delete flathub
sudo flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```

**Comment by bilelmoussaoui** [comment]
No you don't need sudo.
