### ISSUE TITLE
LibreOffice, built-in help is not included

### ISSUE THREAD

**Issue by cmurf** [flathub/flathub#609]
The flathub.org LibreOffice does not install LibreOffice Help. Is this intentional?

Install LibreOffice flatpak, launch, click on Help button in the lower left corner, see dialog:
```
LibreOffice Help Not Installed
The LibreOffice built-in help for current UI language (English (USA)) is not installed on your computer. You may either install it from our website or your system's repositories, or read an online version.
```
Clicking the Read Help Online button opens a blank Firefox window, as if the link messaging between LibreOffice and Firefox didn't work.

**Comment by TingPing** [comment]
Please report it against the package: https://github.com/flathub/org.libreoffice.LibreOffice
