### ISSUE TITLE
Clearly label applications that are modified from upstream

### ISSUE THREAD

**Issue by p-e-w** [flathub/flathub#612]
Recently I was surprised to find out that [the Flathub package for the Atom text editor](https://github.com/flathub/io.atom.Atom) is not only not maintained by any upstream developers (which should be made [much more clear](https://github.com/flathub/flathub/issues/264)), but actually [contained third-party bundled software](https://github.com/flathub/io.atom.Atom/issues/2) that is not contained in the upstream release, and is not required for normal operation of the application. (Note: This bundled software has since been removed from the package.)

I believe that if a package is anything other than a simple redistribution of the software as provided by upstream, this should be prominently indicated on Flathub.

**Comment by barthalion** [comment]
As you already pointed out, there is an open issue for this. Bundling additional tool isn't really modifying upstream either.
