### ISSUE TITLE
Rename org.eu.encom.matrique to org.eu.encom.spectral

### ISSUE THREAD

**Issue by encombhat** [flathub/flathub#627]
We decided to change Matrique's name into Spectral due to negative meanings of Matrique in French.
So the AppStream ID will be changed as well, from org.eu.encom.matrique to org.eu.encom.spectral.

However, from #227 , it seems that AppStream ID cannot be changed easily. So there are two options:

1. Change the AppStream anyway and ignore all resulting misbehaviors.
2. Delete org.eu.encom.matrique from Flathub and resubmit it as org.eu.encom.spectral

The second option may be more preferable.

**Comment by TingPing** [comment]
> Change the AppStream anyway and ignore all resulting misbehaviors.

Flathub will just deny it.

I know @ramcq was looking into handling renaming this week.

**Comment by encombhat** [comment]
That's good to know!

**Comment by encombhat** [comment]
Any updates?
