### ISSUE TITLE
Force Gtk themes to add a screenshot

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/flathub#632]
The Gtk themes should have a screenshot too and maybe some other information on their appdata file.
For now it has only some basic stuff, see this for example https://github.com/flathub/org.gtk.Gtk3theme.Sierra-Negra/blob/master/org.gtk.Gtk3theme.Sierra-Negra.appdata.xml

This would allow software centers to show a good representation of the theme when the user install it.

**Comment by TingPing** [comment]
Nah, GTK themes in Flatpak are not for users to discover (you can't set them or anything), they are just an automatic response to themes already on the host.
