### ISSUE TITLE
New & Updated Apps Section in FlatHub Website - Separate into Dedicated New and Updated Sections

### ISSUE THREAD

**Issue by RoyiAvital** [flathub/flathub#661]
Hello,

There is a [New & Updated Apps](https://flathub.org/apps/collection/recently-updated) section in the [FlatHub](https://flathub.org/) website.

I was wondering if you could separate them into dedicated page for New Applications and dedicated section for Updated Applications.

Thank You.

**Comment by TingPing** [comment]
Website issues are reported here: https://github.com/flathub/linux-store-frontend/issues
