### ISSUE TITLE
License: 'Free' is ambiguous

### ISSUE THREAD

**Issue by knocte** [flathub/flathub#684]
Even if flatpak provides better sandboxing capabilities than previous package management systems in Linux, I want to know if the software I'm installing is opensource or not.

When the "License" field contains "Free", this is clearly ambiguous, because what does this exactly mean? Free as in beer (free-ware) or free as in freedom(FLOSS)? Please make this explicit. A way to do this would be to mention the specific name of the license. Or if this is too technical, just mention if the licence is approved by the OSI or FSF.

One example where this is not explicit: https://flathub.org/apps/details/org.gimp.GIMP

**Comment by nedrichards** [comment]
Could you open this against the flathub website? https://github.com/flathub/linux-store-frontend

It's up to each software center how they'd like to display the information that the appstream metadata gives them (e.g. the flathub website, GNOME Software, KDE Discover etc.)

**Comment by knocte** [comment]
> Could you open this against the flathub website? https://github.com/flathub/linux-store-frontend

Done: https://github.com/flathub/linux-store-frontend/issues/143 thanks
