### ISSUE TITLE
Please add a wishlist repository

### ISSUE THREAD

**Issue by Croydon** [flathub/flathub#690]
Please create a separate repository named wishlist and let people create and upvote Flatpak wishes they desire the most via issues. This helps to understand what applications are most wanted.

Something similar to https://github.com/conan-io/wishlist

**Comment by TingPing** [comment]
I don't see how that would be useful. Just ask applications to make one. Point them here: https://github.com/flathub/flathub/wiki/App-Submission

**Comment by Croydon** [comment]
As I tried to bring across it would be a good indicator for which applications have the highest demand. Right now there are some forums with wishlists but it's completely non-transparent, unofficial and hard to track.

Having an official wishlist makes the demand transparent and trackable and people can directly support each other to work on a flatpak for a specific application.
