### ISSUE TITLE
Provide a community repository

### ISSUE THREAD

**Issue by mildred** [flathub/flathub#719]
When running distributions like Fedora Silverblue that offer a fixed base OS and where packaged applications are mostly coming from Flatpak, you need everything in a flatpak, and sadly, there are not much applications yet on Flathub.

I suggest that you create a community repository that could be used by the community to post applications that are not built by the application authors, but by the community instead. Possibly, reverse DNS names could be used to identify a user who created the flatpak. For example `org.flathub.username.app` would be the app created by `username`.

I know that you prefer application authors to provide the apps, but that might not always be possible. For example, I already packages a few command-line only applications, and I suspect that the app authors are not going to care much about providing a flatpak.

**Comment by barthalion** [comment]
We accept pull requests coming from external contributors as long as upstream has been contacted and such applications are already majority of what is shipped on Flathub. I'm not really sure what this issue is about.

**Comment by TingPing** [comment]
Indeed, this is a community repository.
