### ISSUE TITLE
Can't add filesystem permissions for gimp

### ISSUE THREAD

**Issue by TK1987** [flathub/flathub#721]
I have tried to add write permissions as described in the manual with the command:
`flatpak override --filesystem=/media/Daten:create org.gimp.GIMP`
but thist doesn't seem to have any effect. If i try to save a file in /media/Daten, it always says permission denied.

**Comment by TingPing** [comment]
All that does is ensure the application can see the directory, it doesn't change the permissions of that directory. So you probably just don't actually have permissions and need to fix that on the host.

**Comment by TK1987** [comment]
I have the writepermissions on the host, and can write to the folder - only from the gimp flatpak i can't write to it.
But meanwhile i figured out the problem only occurs in a virtualbox guestsystem when trying to write to a shared folder (mounted using /etc/fstab). If i use an other folder instead, the command works.

**Comment by muelli** [comment]
GIMP has wholesale access to the filesystem, cf. https://github.com/flathub/org.gimp.GIMP/pull/33, so it's unlikely, that it is the cause of your inability to write.

**Comment by muelli** [comment]
so I guess this can be closed, right?
