### ISSUE TITLE
poedit page missing

### ISSUE THREAD

**Issue by lazka** [flathub/flathub#725]
https://flathub.org/apps/search/poedit

links to https://flathub.org/apps/details/net.poedit.Poedit

which says "App not found"

edit: same for https://flathub.org/apps/details/io.github.quodlibet.QuodLibet

**Comment by TingPing** [comment]
Please report these against the packages: https://github.com/flathub/net.poedit.Poedit/issues

It just means their appdata is missing/has incorrect data.

**Comment by lazka** [comment]
hm, ok (appstream-util seems to be OK with it, so not sure what to report there)

https://flathub.org/apps/details/io.github.quodlibet.QuodLibet works again now for some reason.

**Comment by TingPing** [comment]
They could be valid appstream files but for example missing an icon.

**Comment by TingPing** [comment]
If it does turn out to be a website bug that is something to discuss here: https://github.com/flathub/linux-store-frontend

**Comment by lazka** [comment]
ok, filed https://github.com/flathub/linux-store-frontend/issues/154
