### ISSUE TITLE
[Fedora 29] Runescape: libcurl.so.4 issue, beaking runtime

### ISSUE THREAD

**Issue by silvernode** [flathub/flathub#727]
# Issue
Running the flatpak of Runescape generates the following error and prevents the application from running beyond the splash screen:

```
/app/extra/runescape: /lib/libcurl.so.4: no version information available (required by /app/extra/runescape)
/home/$USER/Jagex/launcher/rs2client: /lib/libcurl.so.4: no version information available (required by /home/$USER/Jagex/launcher/rs2client)
```

# Expected results
The application successfully running and prompting for login

# System Info
OS: Fedora 29 (Linux 4.19.2-300.fc29.x86_64)
Flatpak Version: Flatpak 1.0.6
Curl Version: 7.61.1 (/usr/lib/libcurl.so.4)

# Other Information
Reboot since Flatpak/FlatHub installation?: Yes
Contacted package maintainer?: No (not sure how)
OS up to date?: Yes

**Comment by AsciiWolf** [comment]
Seems to work fine on my Fedora 29 system.

**Comment by barthalion** [comment]
Yes, it's definitely not the error. Also please file it under runespace repository instead of here.
