### ISSUE TITLE
Remove non-i386 builds of com.scoutshonour.Digital

### ISSUE THREAD

**Issue by MateusRodCosta** [flathub/flathub#731]
After a failed attempt of building renpy from source for Digital I have decided on reverting the commits related to building renpy and only adding OARS and upgrading the runtime.

Since changing the flathub.json doesn't delete previous builds, could you remove the non-i386 builds once the new i386 build finishes?
It's building here: https://flathub.org/builds/#/builders/2/builds/6323

**Comment by TingPing** [comment]
@ramcq will have to do that.

**Comment by barthalion** [comment]
Done.
