### ISSUE TITLE
Permission to access drive SMART attributes

### ISSUE THREAD

**Issue by linuxhw** [flathub/flathub#775]
Please provide an option to permit read of drive S.M.A.R.T. attributes via `smartctl -x /dev/sda`: http://docs.flatpak.org/en/latest/sandbox-permissions.html

This is needed by https://flathub.org/apps/details/org.linux_hardware.hw-probe.

Thank you.

**Comment by barthalion** [comment]
Are you sure --filesystem=host or --filesystem=/dev doesn't do what you need? Either way, it's not Flathub issue.

**Comment by linuxhw** [comment]
> Are you sure --filesystem=host or --filesystem=/dev doesn't do what you need? Either way, it's not Flathub issue.

Moved to https://github.com/flatpak/flatpak/issues/2452.

`/dev` is blacklisted for now, so `--filesystem=/dev` is not effective.

Thank you.

**Comment by TingPing** [comment]
But `--device=all` does that.

**Comment by linuxhw** [comment]
@TingPing 

The command:

    flatpak run org.linux_hardware.hw-probe

or desktop app icon / launch button cannot run `smartctl`. There is a permission denied error.

`smartctl` requires to be executed as root to access `/dev/sdX`.

Tried locally with `--device=all`, but this doesn't fix the issue.

How to manage desktop app / launch button in the App Center to run `smartctl` properly?

Thank you.

**Comment by TingPing** [comment]
Well you can't ever get root access in the sandbox. You can start running things on the host but uh... why is it even a flatpak at that point.
