### ISSUE TITLE
Mark the gnome 3.24 runtime as EOL

### ISSUE THREAD

**Issue by matthiasclasen** [flathub/flathub#802]
no apps are using it anymore according to #667

**Comment by barthalion** [comment]
Do we know since when it's actually not supported? If not, does that sound okay:

`GNOME 3.24 platform is no longer supported as of 10th January 2018. Please ask your application developer to migrate to a supported runtime.`

**Comment by bilelmoussaoui** [comment]
@barthalion It's 2019 :P

**Comment by barthalion** [comment]
Damn, time flies so fast :(

**Comment by TingPing** [comment]
Well, the GNOME part I think has been unsupported since 3.26 came out probably over a year ago...

**Comment by TingPing** [comment]
Looks like webkitgtk (and its deps) kept getting security updates but thats all in the past year.

**Comment by barthalion** [comment]
Done.
