### ISSUE TITLE
Installation error: server unavailable

### ISSUE THREAD

**Issue by bsavitzky** [flathub/flathub#804]
Hi flathub developers - while attempting to install inkscape on Ubuntu 18.04.1 using flathub, I encountered an error in which it appears the flathub server is unavailable.

When running

```
flatpak install flathub org.inkscape.Inkscape
```

The following error is being thrown:

```
error: Failed to install org.inkscape.Inkscape/x86_64/stable: While pulling app/org.inkscape.Inkscape/x86_64/stable from remote flathub: Server returned status 503: Service Unavailable
```

Thanks for any help!
Ben

**Comment by barthalion** [comment]
Please just try again – the issue will be gone when we migrate to dedicated machines.

**Comment by bsavitzky** [comment]
Ok, thanks!

**Comment by AncientTom** [comment]
This is July and the issue is not gone while trying to install net.meijn.onvifviewer

**Comment by sebastiaanfranken** [comment]
I'm facing the same issue with installing Setzer (org.cvfosammm.Setzer), which is a hefty 1.6GB. It's downloading at 300KB (!) and stops after a few minutes, every time.. It's getting very annoying to use Flathub like this. Surely you guys use mirrors and such?
