### ISSUE TITLE
App metadata failed to update after seemingly successful build

### ISSUE THREAD

**Issue by cgutman** [flathub/flathub#806]
On Jan 08, I updated the [Moonlight Flatpak](https://github.com/flathub/com.moonlight_stream.Moonlight) to v0.8.1. [The build](https://flathub.org/builds/#/builders/2/builds/7325) seemingly completed without issues, however I noticed the next morning that the metadata of the [Flathub page](https://flathub.org/apps/details/com.moonlight_stream.Moonlight) never updated to the [v0.8.1 changelog](https://github.com/moonlight-stream/moonlight-qt/commit/32e7ddf272cfd1de795b71d5dae67199908feae4).

I double-checked that `appstream-util validate-relax` passes on my appstream.xml, which it does.

I verified that I was indeed pulling down v0.8.1 when running `flatpak update` but GNOME Software and Flathub were stilling reporting v0.8.0 as the latest build via their frontends.

When I took a look at one of the [build logs](https://flathub.org/builds/#/builders/28/builds/886), I saw an unusual warning near the end:
```
Mirroring screenshots from appdata
]2;flatpak-builder: Mirroring screenshotsFB: Running: flatpak build --die-with-parent --nofilesystem=host --filesystem=/srv/buildbot/worker/build-x86_64-5/com.moonlight_stream.Moonlight/builddir --filesystem=/srv/buildbot/worker/build-x86_64-5/com.moonlight_stream.Moonlight/.flatpak-builder/screenshots-cache --share=network /srv/buildbot/worker/build-x86_64-5/com.moonlight_stream.Moonlight/builddir appstream-util mirror-screenshots /srv/buildbot/worker/build-x86_64-5/com.moonlight_stream.Moonlight/builddir/files/share/app-info/xmls/com.moonlight_stream.Moonlight.xml.gz https://flathub.org/repo/screenshots/com.moonlight_stream.Moonlight-stable /srv/buildbot/worker/build-x86_64-5/com.moonlight_stream.Moonlight/.flatpak-builder/screenshots-cache /srv/buildbot/worker/build-x86_64-5/com.moonlight_stream.Moonlight/builddir/screenshots/com.moonlight_stream.Moonlight-stable
com.moonlight_stream.Moonlight:    Downloading https://moonlight-stream.org/appstream_resources/moonlight_screenshot_1.png
com.moonlight_stream.Moonlight:    Failed to download https://moonlight-stream.org/appstream_resources/moonlight_screenshot_1.png: Downloading failed: SSL handshake failed
com.moonlight_stream.Moonlight:    Downloading https://moonlight-stream.org/appstream_resources/moonlight_screenshot_2.png
com.moonlight_stream.Moonlight:    Failed to download https://moonlight-stream.org/appstream_resources/moonlight_screenshot_2.png: Downloading failed: SSL handshake failed
Saved screenshots in /srv/buildbot/worker/build-x86_64-5/com.moonlight_stream.Moonlight/builddir/screenshots
```

It might be a red herring, but I confirmed that these errors did not appear in the [previous successful build](https://flathub.org/builds/#/builders/2/builds/7004). I find it unlikely that there was a real SSL handshake failure on my end (since that site is hosted on CloudFlare and they didn't report any SSL issues at the time). But even if so, that shouldn't break publishing the metadata. And if an issue was encountered parsing or publishing metadata, I would hope that my build would fail rather than claiming success.

Any thoughts on this?

**Comment by barthalion** [comment]
@jgarciao Can you take a look?

**Comment by jgarciao** [comment]
Flathub.org gets the information about the apps from the appstream.xml file generated in the ostree repo. You can see the contents in your computer opening this file: `/var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml`

The file currently only has the release 0.8.0 so that's the version shown in the website and gnome-software. The same when you run flatpak search moonlight:
```
flatpak search moonlight
Application ID                 Version Branch Remotes Description                                               
com.moonlight_stream.Moonlight 0.8.0   stable flathub Play games remotely from your NVIDIA GameStream-enabled PC

```

Is it possible to force another build to try to fix it?

**Comment by cgutman** [comment]
I can probably kick off another build and that may fix it, but the main reason for this ticket is to understand why the appstream update failed in the first place. Do you have any idea what the root cause could have been?

I haven't rebuilt because I didn't want to destroy anything that would be useful for investigating the failure to update appstream metadata and incorrectly reported "successful" build.

**Comment by jgarciao** [comment]
Maybe @alexlarsson or @TingPing can help. I'm not familiar with the build process

**Comment by DoctorJohn** [comment]
If I'm not mistaking I'm experiencing something quite similar. The website used to show apps after they have been succefully updated in the "New & Updated Apps" section on flathub.org.
Several apps have been updates since yesterday including mine. But neither are they "featured" on the startpage, nor does my apps page show the correct version. Getting the updated version (flatpak update) work though.

**Comment by jgarciao** [comment]
It's not a website issue, is the appstream information that hasn't been properly updated
```
$ flatpak update --appstream
Updating appstream data for remote flathub

$ flatpak search Botfather
Application ID         Version Branch Remotes Description                   
io.botfather.Botfather 4.4.1   stable flathub Universal automation framework
```

**Comment by cgutman** [comment]
I ran [another build](https://flathub.org/builds/#/builders/2/builds/7519) several days ago which also claimed to have succeeded.

This time I do see that the version reported in the appstream data was updated, however my [Flathub.org app page](https://flathub.org/apps/details/com.moonlight_stream.Moonlight) still says 0.8.0 is the latest and has the corresponding 0.8.0 changelog instead of 0.8.1. 

```
$ flatpak search moonlight
Application ID                 Version Branch Remotes Description                                               
com.moonlight_stream.Moonlight 0.8.1   stable flathub Play games remotely from your NVIDIA GameStream-enabled PC
```

GNOME Software also now says 0.8.1 is the latest now, however it is unable to display the 0.8.1 changelog either. It still displays the one from 0.8.0, even when it says it's updating to 0.8.1.

![image](https://user-images.githubusercontent.com/2695644/51552842-5bd83f80-1e26-11e9-8492-578718e41643.png)

I'm pretty much at a loss now. It seems like we possibly have 2 different bugs here. Or maybe whatever is breaking the changelog in GNOME Software is also breaking Flathub.org?

**Comment by cgutman** [comment]
Ah, I'm a moron. I found the changelog issue clear as day when I opened up `/var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml` (thanks for that suggestion!)

I just realized I mistyped the year in my [release commit](https://github.com/moonlight-stream/moonlight-qt/commit/32e7ddf272cfd1de795b71d5dae67199908feae4) as `2018-01-08` despite staring at that change several different times looking for errors while investigating this bug. The changelog entry for 0.8.1 was in fact present in GNOME Software, just at the very bottom due to the incorrect date.

The weird mix of 0.8.1 and 0.8.0 info I saw in various places is probably due to the fact that some treat the first `<release>` entry as the latest and others use the most recent release by parsing the date information.

There _may_ still be a bug here since the behavior of the initial 0.8.1 build (which didn't update the version in `flatpak search`) and the second one (which did) was different, but there are far too many confounding factors with the metadata of this app version to cleanly investigate that occurrence IMHO.

@DoctorJohn You can open a new ticket for your issue, so Flathub folks don't have to wade through all of my unrelated stuff.

**Comment by jgarciao** [comment]
No problem. I also still think we are in 2018 :-)
