### ISSUE TITLE
Connectivity issues from China

### ISSUE THREAD

**Issue by kxygk** [flathub/flathub#813]
Please see the discussion here: https://github.com/flatpak/flatpak/issues/1285

There are serious issues with availability from China and the current CDN solutions is insufficient. Please look at other opensource projects for workable alternatives and solutions (ex: partnering with volunteer mirrors like https://lug.ustc.edu.cn/wiki/intro_english who host Ubuntu/Debian repos and stuff like that )

**Comment by amtlib-dot-dll** [comment]
Here https://github.com/ustclug/mirrorrequest/ is how to add Flathub to the USTC mirror.

Before submitting, I have some more questions, is plain `wget --mirror` sufficient? And should we mirror the Repo Frontend (dl.flathub.org) only or together with the Repo Backend (repo.flathub.org)? Can we use automatic 302 redirection per location to automatically configure mirrors?

**Comment by geokon-gh** [comment]
Let me know if you need me to do any testing from China @amtlib-dot-dll 

I'm not sure what the front/back end distinction is. As I mentioned in the flatpak issue, the command line is very slow and doesn't use a cache (like `apt` for instance), so autocomplete (hitting TAB) hangs things with a poor connection. 

The website is also very slow and sometimes unusable as well. That may be partly a CDN issue but also from the HTML I can see it's loading things from Google (like analytics) which is not super user friendly - so in China I think the webpage is unresponsive till all that stuff times out

**Comment by amtlib-dot-dll** [comment]
@geokon-gh 憋说了，都快放弃这玩意了😂😂

**Comment by ramcq** [comment]
The Flathub repo is over 1TB now, but the working set is far smaller. If we wanted to send China traffic to a different server, either with GeoDNS or mirrorlist we would need a caching proxy server, ideally one that we can send invalidation requests to. If someone knows somewhere we could host one in China, I'd be happy to work on eg a container image that could run there.

**Comment by lorenz** [comment]
This is not just a China issue. FlatHub is very slow (a few MiB/s) even in Europe on a 1Gbps line which is directly peered over 10Gbps+ to Fastly with a latency of ~6ms. Is the content actually getting pushed out to Fastly or are they just proxying?

**Comment by realnc** [comment]
> This is not just a China issue. FlatHub is very slow (a few MiB/s) even in Europe

Same here. Installing anything from flathub usually caps out at about 900KB/s or so. Maybe 1.3MB/s on a "fast" day.

**Comment by fikrillah** [comment]
hi, i'm from Indonesia, and the speed here is very slow (i mean it, you wouldn't want to imagine how terrible it is), i think this problem is not only happen only in China, but also on entire other side of the world...

**Comment by fenris** [comment]
Hi,
The same goes for Malaysia .... any update on this issue? Can't Flathub consider other CDN providers to resolve this issue?

**Comment by fenris** [comment]
Hi All,
I've contacted and filed a ticket to Fastly Support, 

> Hi Fenris,
Are you able to ask the affected customer to provide the output of https://www.fastly-debug.com/. May I also ask if you could send us the URL of a large file that we can use to test download speed and that we would also be allowed to purge. Many thanks, Stefanos

can someone help me to suggest what are the large file URL that can be used for testing the download speed?

**Comment by barthalion** [comment]
Hi @fenris,

I have uploaded a 100MB test file. It is accessible at `https://dl.flathub.org/testfile100MB` through Fastly or `https://front-hex.flathub.org/testfile100MB` from our UK server.

**Comment by barthalion** [comment]
Also feel free to include me into CC with Fastly support. My e-mail is `b@bpiotrowski.pl`

**Comment by cheese** [comment]
> Hi @fenris,
> 
> I have uploaded a 100MB test file. It is accessible at `https://dl.flathub.org/testfile100MB` through Fastly or `https://front-hex.flathub.org/testfile100MB` from our UK server.

How to test it? What information should we provide?

**Comment by fenris** [comment]
@barthalion thanks for the file.

I've already put you in the cc with the Fastly support.

**Comment by ZeroAurora** [comment]
> 
> 
> Hi All,
> I've contacted and filed a ticket to Fastly Support,
> 
> > Hi Fenris,
> > Are you able to ask the affected customer to provide the output of https://www.fastly-debug.com/. May I also ask if you could send us the URL of a large file that we can use to test download speed and that we would also be allowed to purge. Many thanks, Stefanos
> 
> can someone help me to suggest what are the large file URL that can be used for testing the download speed?

In China I can't even access this debug url as well as the 100MB test file. :(
However, directly accessing `front-hex.flathub.org` did work a bit better. (At least I can access FlatHub frontend with a really slow connection.)

**Comment by ZeroAurora** [comment]
China's firewall has completely censored fastly cdn. We can use it without a network proxy only when we are lucky enough,

**Comment by nlpsuge** [comment]
Any progress? Does flatpak has any mirror sites?

I cannot even use flatpak to install or update normally... I'll take ages to unfinish...

**Comment by barthalion** [comment]
@ZeroAurora @nlpsuge 

I have deployed new server in California, can you test it? It should be accessible from China and have reasonable transfer speed.

1. Run `flatpak remote-modify flathub --url=https://front-frt.flathub.org/repo` (you may need to add or run it additionally with `--user` depending on your setup).
2. Open `/var/lib/flatpak/repo/config` or/and `~/.local/share/flatpak/repo/config` in text editor and find `[remote "flathub"]` section. Add a new line with following content: `url-is-set=true` so the entire section looks like this:

```
[remote "flathub"]
url=https://front-frt.flathub.org/repo/
url-is-set=true
xa.title=Flathub
gpg-verify=true
gpg-verify-summary=true
xa.comment=Central repository of Flatpak applications
xa.description=Central repository of Flatpak applications
xa.icon=https://front-frt.flathub.org/repo/logo.svg
xa.homepage=https://flathub.org/
```

**Comment by abcfy2** [comment]
Sorry, but it's still blocked.

```
# curl -Lv --compressed https://front-frt.flathub.org/repo
*   Trying 45.79.93.189...
* TCP_NODELAY set
* connect to 45.79.93.189 port 443 failed: Connection timed out
* Failed to connect to front-frt.flathub.org port 443: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to front-frt.flathub.org port 443: Connection timed out
```

I think maybe it's better to use a China CDN ([Aliyun](https://www.alibabacloud.com/product/cdn), [HuaweiCloud](https://www.huaweicloud.com/en-us/product/cdn.html), [ChinaCache](https://en.chinacache.com/), and so on) or other CDN that can make services for China(like [cloudflare](https://www.cloudflare.com/network/china/), [quantil](https://www.quantil.com/content-delivery-network/china/), and so on). Thanks.

**Comment by barthalion** [comment]
Weird, I've been told it'll work fine. We can't really go with fancy CDN, we're not a commercial entity. Any idea if providers you mentioned (apart from Cloudflare) have free plans for open source projects?

**Comment by abcfy2** [comment]
And also, I think the most simple way is support mirror site. Like [Gitlab-CE](https://about.gitlab.com/install/).

There are so many mirror sites in China. If flathub support mirror site, I think many mirror sites would be willing to do this.

**Comment by barthalion** [comment]
Flatpak isn't really built for mirroring likes this as there are no set of packages to mirror per se like it is with debs/rpms.

**Comment by barthalion** [comment]
@abcfy2 Alternatively, do https://front-hex2.flathub.org or https://front-ams.flathub.org work for you?

**Comment by abcfy2** [comment]
Both sites can be accessed.

**Comment by suokunlong** [comment]
> Weird, I've been told it'll work fine. We can't really go with fancy CDN, we're not a commercial entity. Any idea if providers you mentioned (apart from Cloudflare) have free plans for open source projects?

How much does it cost for such a CDN service? Maybe we can raise some money here in China? I think many people may be willing to donate for this purpose.

**Comment by barthalion** [comment]
@abcfy2 Can you try https://front-sel.flathub.org/ ?

**Comment by abcfy2** [comment]
https://front-sel.flathub.org/  is working.

**Comment by suokunlong** [comment]
> @abcfy2 Can you try https://front-sel.flathub.org

front-sel.flathub.org is working great - I see the server is located in Korea and it seems to be a CN2 optimized route. Actually both Korea and HongKong CN2 servers would work.

**Comment by suokunlong** [comment]
There is a good online tool for this kind of test:
http://tool.chinaz.com/speedtest/front-sel.flathub.org

**Comment by wi24rd** [comment]
Could you support IPv6? The traffic charge of CERNET is expensive in some university of China, but luckily IPv6 traffic doesn't count in. FYI, many university do mirroring work by IPv6.

**Comment by barthalion** [comment]
@wi24rd Looks like Oracle Cloud does not support IPv6 in Seoul region so I can't do anything about it.

**Comment by wi24rd** [comment]
Hi @barthalion, I just tried dl.flathub.org(2a04:4e42:36::729) in my school, it's up to 4.3MB/s which reaches almost my network limit. Thanks for your work.

**Comment by cheese** [comment]
When using 'sel.flathub.org', sometimes error occurs:

```
$ flatpak --user install flathub org.gnome.Sdk/x86_64/3.36
Looking for matches…
error: Unable to load summary from remote flathub: Signature made Thu 01 Jan 1970 08:00:00 AM CST using [unknown name] key ID 562702E9E3ED7EE8
BAD signature from "Flathub Repo Signing Key <flathub@flathub.org>"
Primary key ID 4184DD4D907A7CAE
Primary key expires Mon 14 Jun 2027 09:18:56 PM CST
```

**Comment by skyzh** [comment]
SJTUG is actively working on a mirror of flathub.org https://github.com/flathub/flathub/issues/813 . However, we find it very slow to download the metadata objects. Is there any way to pack-download these meta objects (like git)?

<img width="523" alt="image" src="https://user-images.githubusercontent.com/4198311/89608792-a904f080-d8a8-11ea-8045-d89ffd648ded.png">

FYI, our mirroring scripts
```
ostree init --repo=$LUG_path --mode=archive --collection-id=org.flathub.Stable
ostree remote add --repo=$LUG_path --no-gpg-verify flathub https://dl.flathub.org/repo/
ostree pull --repo=$LUG_path --mirror flathub --depth=1
flatpak build-update-repo $LUG_path
```

**Comment by skyzh** [comment]
Is there any possibility that we can get some kind of archive to bootstrap our mirror?

**Comment by ramcq** [comment]
@skyzh I think it would make more sense for you to deploy a cache rather than a mirror, then only fresh/relevant objects are kept, up to your resource limit. There are 2.4TB of objects across our stable and beta repos, covering 4 architectures etc. Some are far more popular than others... :)

If you see the ansible role at https://github.com/flathub/ansible-playbook/tree/master/roles/frontend, the frontend servers that sit between the real origin, and our CDN, are a very simple configuration of nginx, as much of the data in an ostree repo is content addressed so works very well in caching scenarios. We could also add your host to the list of origins that received PURGE messages once the summary files are updated, which would help you to keep the cache fresh.

**Comment by skyzh** [comment]
@ramcq Thanks for your response! I will look into the possibility of setting up a cache on our server. Cache service seems to be a better choice than mirroring a whole repo, in the case of flathub and other ostree-based repositories.

**Comment by barthalion** [comment]
@cheese I disabled caching for summary files (and signatures). That should help.

**Comment by ramcq** [comment]
> @cheese I disabled caching for summary files (and signatures). That should help.

Where did you disable summary caching? This is typically a bad idea - its the largest bandwidth user on the Endless CDN and can seriously load the origin. You need to arrange PURGE for the front ends at the right time but you really want the summary to stay cached as much as possible!

**Comment by barthalion** [comment]
We're talking about about South Korean servers here. They're configured to use Fastly as connectivity to Mythic isn't the best so I'm not too concerned about origin load.

**Comment by suokunlong** [comment]
None of the urls mentioned above is working anymore.

The easiest solution (for me) is:
1. Pick an IP in: http://ping.chinaz.com/dl.flathub.org,
2. Add the ip to your /etc/hosts file:
`151.101.78.217` dl.flatpak.org

You should choose one near you. The best for me is one located in Hong Kong.

**Comment by skyzh** [comment]
Is it possible to provide a snapshot of file list? For example, http://archive.ubuntu.com/ubuntu/ls-lR.gz and https://dl.fedoraproject.org/pub/fedora/fullfilelist . This way, we could use our own tool to mirror the repository instead of using ostree.

**Comment by barthalion** [comment]
There is no such thing as a "file list", as objects being used by given ref are changing on update. That's why caching proxied request is the easiest thing to do.

**Comment by skyzh** [comment]
We have set up a beta mirror at

```
sudo flatpak remote-modify flathub --url=https://mirrors.sjtug.sjtu.edu.cn/flathub
```

We plan to make it available at another new server next month. Chinese user may have a try, and change URL to our new server next month.

The mirror works differently from traditional reverse proxy. It is served by our custom-made server https://github.com/sjtug/mirror-intel , and uses a S3-like backend as cache. Upon user connection, it will:

* check if requested file is summary / config (https://github.com/sjtug/mirror-intel/blob/master/src/utils.rs#L10) If so, redirect user to flathub original site.
* then query if that object exists in s3 backend
* if yes, it will redirect user to s3 object storage (s3.jcloud.sjtu.edu.cn)
* if not, it will redirect user to original flathub site, and submit task for background download
* the task will download file from original site and upload it to s3 backend

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/4198311/101195463-6c040b80-369a-11eb-866d-ae48e7a288c6.png">

We have pulled all available apps from flathub through this cache. This cache has been well-populated.

**Comment by skyzh** [comment]
If possible, you could set up a server that pulls latest apps from our registry every time there's an app update. This way, our cache can always get populated.

**Comment by barthalion** [comment]
That's excellent. Is `HEAD` enough to make it cached? I'll also look to include this URL on our website.

**Comment by skyzh** [comment]
> That's excellent. Is `HEAD` enough to make it cached? I'll also look to include this URL on our website.

Yes. Sending `HEAD` would help us populate cache. However, as we're using 301/302 redirect (otherwise old version of libcurl won't redirect correctly), the redirected request may become a GET.

I'm glad that our mirror could be included in website. I'll let you know when our mirror could be generally available and update the final url for use later.

**Comment by alexlarsson** [comment]
@skyzh Note that with flatpak 1.9.1 we need to also consider `summary.idx` and `summary.idx.sig` simiar to the `summary` and `summary.sig` files.

**Comment by skyzh** [comment]
> @skyzh Note that with flatpak 1.9.1 we need to also consider `summary.idx` and `summary.idx.sig` simiar to the `summary` and `summary.sig` files.

Thanks for reminding! I've ignore all files beginning with `summary`.

**Comment by alexlarsson** [comment]
Yeah, that will work well. There is also a new subdirectory called `summaries`, but the files in there are stored by hash so will be immutable. They are not as long lived as other things though as the summary changes more often so you might want to have different cache lifetime rules for them.

**Comment by skyzh** [comment]
> Yeah, that will work well. There is also a new subdirectory called `summaries`, but the files in there are stored by hash so will be immutable. They are not as long lived as other things though as the summary changes more often so you might want to have different cache lifetime rules for them.

Thanks! Now this directory will be cached on our storage backend (on next deploy).

**Comment by skyzh** [comment]
Our mirror is now generally available at https://mirror.sjtu.edu.cn/flathub

```
sudo flatpak remote-modify flathub --url=https://mirror.sjtu.edu.cn/flathub
```

**Comment by barthalion** [comment]
As the first step on our end, front-sel, front-sel2 and sel.flathub.org domains redirect now to https://mirror.sjtu.edu.cn/flathub.

**Comment by barthalion** [comment]
Also I thought about automating populating the cache on USTC mirror but I guess not every app is popular enough to justify "pushing" every objects possible to you, I guess the dynamic approach you went with is preferred.

**Comment by chenzhiwei** [comment]
@skyzh Hello, after I run the `flatpak remote-modify` command, the url in `/var/lib/flatpak/repo/config` was changed to the mirror url, but when I run `flatpak update`, the change was rolled back.

My flatpak version is 1.2.5.

**Comment by skyzh** [comment]
> @skyzh Hello, after I run the `flatpak remote-modify` command, the url in `/var/lib/flatpak/repo/config` was changed to the mirror url, but when I run `flatpak update`, the change was rolled back.
> 
> 
> 
> My flatpak version is 1.2.5.

We will investigate this soon.

**Comment by barthalion** [comment]
@chenzhiwei Yeah, the default flatpak behavior restores the "original" configuration. You may want to follow steps at https://flatpak.org/setup/ to install latest flatpak that will keep modifications, and re-run `remote-modify` with `--no-follow-redirect` switch.

If updating is not possible, please follow steps described at https://barthalion.blog/test-driving-flathub-mirror-for-users-in-china/ but use `https://mirror.sjtu.edu.cn/flathub` instead of `sel.flathub.org`.

**Comment by chenzhiwei** [comment]
@barthalion Thank you! Manually add `url-is-set=true` to the config file works well.

**Comment by chenzhiwei** [comment]
Hello, I am using the mirror `https://mirror.sjtu.edu.cn/flathub`, but there are still many connections to `dl.flathub.org:443`. @skyzh

**Comment by skyzh** [comment]
> Hello, I am using the mirror `https://mirror.sjtu.edu.cn/flathub`, but there are still many connections to `dl.flathub.org:443`. @skyzh

That is because the requested files are not cached on our server. We are building a smart reverse proxy instead of a full mirror.

**Comment by chenzhiwei** [comment]
But even if there is not update, there are still requests to dl.flathub.org.

**Comment by skyzh** [comment]
> But even if there is not update, there are still requests to dl.flathub.org.

You may open an issue with more information on our issue tracker https://github.com/sjtug/mirror-requests/issues/new?assignees=&labels=bug&template=2-bug-report.md

**Comment by barthalion** [comment]
If this is of any help, I can provide a `nocdn.flathub.org` endpoint which will directly use our caching servers in Amsterdam and London, front-ams.flathub.org and front-hex2.flathub.org respectively. I think these IPs are not blocked by GFW (yet?), but are of course slower than cache hit against SJTUG or Fastly CDN.

**Comment by chenzhiwei** [comment]
@barthalion Thank you, these two domains are not blocked and they work very well. No requests to dl.flathub.org with these two mirrors.

**Comment by itsnotsaved** [comment]
https://github.com/flatpak/flatpak/issues/4874

**Comment by chinanoahli** [comment]
If the network issues cannot be resolved. Why not give a way to download the software packages and a way to install them manually?

There are a lot of networking tools working well with browsers, but not cli tools in linux.

**Comment by kyon328** [comment]
> Our mirror is now generally available at https://mirror.sjtu.edu.cn/flathub/
> 
> ```
> sudo flatpak remote-modify flathub --url=https://mirror.sjtu.edu.cn/flathub
> ```

Thanks! I am in Guangxi China, this works for me perfectly, can reach 10MB/s (using official remote url is 20KB/s)

**Comment by GreatBigWhiteWorld** [comment]
Any idea why it doesn't work anymore?
```
:~> flatpak update
Looking for updates…


        ID                                                               Branch              Op             Remote              Download
 1. [✗] com.valvesoftware.Steam.CompatibilityTool.Proton-GE              stable              u              flathub             1.0 kB / 484.7 MB
 2. [✗] com.brave.Browser                                                stable              u              flathub             1.0 kB / 155.9 MB

Warning: While pulling runtime/com.valvesoftware.Steam.CompatibilityTool.Proton-GE/x86_64/stable from remote flathub: While fetching https://mirror.sjtu.edu.cn/flathub/config: [28] Timeout was reached
Error: While pulling app/com.brave.Browser/x86_64/stable from remote flathub: While fetching https://mirror.sjtu.edu.cn/flathub/config: [28] Timeout was reached
Updates complete.
error: There were one or more errors
```

**Comment by wangyongf** [comment]
> Our mirror is now generally available at [mirror.sjtu.edu.cn/flathub](https://mirror.sjtu.edu.cn/flathub/)
> 
> ```
> sudo flatpak remote-modify flathub --url=https://mirror.sjtu.edu.cn/flathub
> ```

works for me too in Shanghai, thanks

**Comment by LiuYi98** [comment]
> Any idea why it doesn't work anymore?
> 
> ```
> :~> flatpak update
> Looking for updates…
> 
> 
>         ID                                                               Branch              Op             Remote              Download
>  1. [✗] com.valvesoftware.Steam.CompatibilityTool.Proton-GE              stable              u              flathub             1.0 kB / 484.7 MB
>  2. [✗] com.brave.Browser                                                stable              u              flathub             1.0 kB / 155.9 MB
> 
> Warning: While pulling runtime/com.valvesoftware.Steam.CompatibilityTool.Proton-GE/x86_64/stable from remote flathub: While fetching https://mirror.sjtu.edu.cn/flathub/config: [28] Timeout was reached
> Error: While pulling app/com.brave.Browser/x86_64/stable from remote flathub: While fetching https://mirror.sjtu.edu.cn/flathub/config: [28] Timeout was reached
> Updates complete.
> error: There were one or more errors
> ```
> 
> Already tried 'flatpak repair'

same for me in Fedora 38, any update?

**Comment by notpushkin** [comment]
Here's an interesting observation: I'm currently in Georgia (the European country, not the U. S. state) and both `https://dl.flathub.org/` and all of `https://front-*.flathub.org` are giving 50-90 KB/s to me. When I switched to `https://mirror.sjtu.edu.cn/flathub`, I get <1 KB/s initially, but in a couple seconds it goes up to 500-900 KB/s! Any ideas why this could be happening?

**Comment by LiuYi98** [comment]
> > Any idea why it doesn't work anymore?
> > ```
> > :~> flatpak update
> > Looking for updates…
> > 
> > 
> >         ID                                                               Branch              Op             Remote              Download
> >  1. [✗] com.valvesoftware.Steam.CompatibilityTool.Proton-GE              stable              u              flathub             1.0 kB / 484.7 MB
> >  2. [✗] com.brave.Browser                                                stable              u              flathub             1.0 kB / 155.9 MB
> > 
> > Warning: While pulling runtime/com.valvesoftware.Steam.CompatibilityTool.Proton-GE/x86_64/stable from remote flathub: While fetching https://mirror.sjtu.edu.cn/flathub/config: [28] Timeout was reached
> > Error: While pulling app/com.brave.Browser/x86_64/stable from remote flathub: While fetching https://mirror.sjtu.edu.cn/flathub/config: [28] Timeout was reached
> > Updates complete.
> > error: There were one or more errors
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Already tried 'flatpak repair'
> 
> same for me in Fedora 38, any update?

change the https in mirror to http works in Shanghai

**Comment by TCB13** [comment]
> SJTUG is actively working on a mirror of flathub.org [sjtug/mirror-requests#86](https://github.com/sjtug/mirror-requests/issues/86) . However, we find it very slow to download the metadata objects. Is there any way to pack-download these meta objects (like git)?
> 
> <img alt="image" width="523" src="https://user-images.githubusercontent.com/4198311/89608792-a904f080-d8a8-11ea-8045-d89ffd648ded.png">
> 
> FYI, our mirroring scripts
> 
> ```
> ostree init --repo=$LUG_path --mode=archive --collection-id=org.flathub.Stable
> ostree remote add --repo=$LUG_path --no-gpg-verify flathub https://dl.flathub.org/repo/
> ostree pull --repo=$LUG_path --mirror flathub --depth=1
> flatpak build-update-repo $LUG_path
> ```
> 
> ~Just give up on mirroring by OSTree~

Did you actually manage to get around this or you completely gave out on mirroring and you're simply doing a reverse proxy with caching?
