### ISSUE TITLE
'Digital: A Love Story' not launching on Fedora 26

### ISSUE THREAD

**Issue by HoboPrimate** [flathub/flathub#83]
This game doesn't launch on Fedora 26:

> $ flatpak run com.scoutshonour.Digital
> /app/lib/python: line 23: /app/lib/linux-x86/python.real: No such file or directory
> /app/lib/python: line 23: /app/lib/linux-iliad/python.real: No such file or directory
> Could not find a python that runs on your platform. Sorry.

Installed through Gnome Software.

**Comment by TingPing** [comment]
Should probably open an issue on that specific package: https://github.com/flathub/com.scoutshonour.Digital

**Comment by HoboPrimate** [comment]
Thank you, will do
