### ISSUE TITLE
GTK2 themes

### ISSUE THREAD

**Issue by benwaffle** [flathub/flathub#85]
Specifically I'm looking for Adapta for Slack

**Comment by TingPing** [comment]
Would be nice, need to add an extension point to the GNOME Sdk for it first. Also side note Electron will move to Gtk3 eventually but it will probably be months for that to make it to Slack.

**Comment by bil-elmoussaoui** [comment]
That will make things a lot more complicated to handle. Adapta has 4 variants (Adapta, Adapta Eta, Adapta Nokto, Adapta Eta Nokta) for Gtk3. Adding Gtk2 as an extensions means 4 more repos for Adapta; and with Gtk4 in the future you will need more repos. Which is really impossible to handle :(

**Comment by TingPing** [comment]
@bil-elmoussaoui Just script it: https://github.com/flathub/org.gtk.Gtk3theme.Arc/blob/master/update-theme.sh

**Comment by jhasse** [comment]
Still users will have to install 3 themes. That's why I think starting Gtk4 is a bad idea while Gtk2 is still around.

**Comment by jurf** [comment]
Why don’t we just merge Gtk themes into one extension, specific to a runtime?

My original idea was to have on extension per theme, targeting different runtimes, so the user would just jave to install it once and have complete support.

**Comment by TingPing** [comment]
> Still users will have to install 3 themes.

That is a different problem. Gnome-Software or flatpak should automatically install themes.

**Comment by bil-elmoussaoui** [comment]
@TingPing Wouldn't be easier to ship the gtk2 theme within the gtk3.22 one? currently, I started using as much flatpak apps as I can! Gimp and Inkscape look like aliens to me :p

**Comment by TingPing** [comment]
> Wouldn't be easier to ship the gtk2 theme within the gtk3.22 one?

Logically no. It isn't tied to the gtk version its tied to the runtime version since, unlike gtk3, gtk2 themes are libraries.

**Comment by teohhanhui** [comment]
Now with Gtk4 on the rise, what's the plan for handling those themes?

    $ flatpak remote-ls flathub | grep -i gtk4theme

shows there's nothing yet...

**Comment by TingPing** [comment]
Have to duplicate the gtk3 solution. Its work but doable.

**Comment by bbhtt** [comment]
Considering that none of the runtime is shipping GTK2 anymore, I think it's time to close this issue.

Extension point for GTK4 themes is tracked separately https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1620 https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/697

**Comment by TingPing** [comment]
This is handled, in a very basic way, here: https://github.com/flathub/shared-modules/blob/master/gtk2/gtk2-common-themes.json
