### ISSUE TITLE
Please add "winepak" http://winepak.org/ to "FlatHub"

### ISSUE THREAD

**Issue by ovari** [flathub/flathub#864]
http://winepak.org/
https://github.com/winepak/winepak
https://github.com/winepak/winepak/issues/21

Flatpak-ing Microsoft Windows applications with Wine
Making Microsoft Windows applications Just Work™ under Linux

It can enable installing an application using the software center or via the terminal

What do you think?

Thank you

**Comment by TingPing** [comment]
You can add other repos, they don't have to be on Flathub.

Anyway Winepak is currently not an active project.
