### ISSUE TITLE
Flathub website is not showing VICE icon in search results

### ISSUE THREAD

**Issue by digitalstreamio** [flathub/flathub#880]
About a month ago, we updated VICE to have multiple entry points. Since then, the application icon is missing in Flathub search results.

The issue is appdata.xml points to

> net.sf.VICE.C64.desktop

which is used by Flathub to figure out which icon to use. Flathub defaults to the same name as the desktop id, so the url for the application icon used by Flathub is

> https://flathub.org/repo/appstream/x86_64/icons/128x128/net.sf.VICE.C64.png

However, desktop file points to a different image since the image is reused between multiple entry points.

> https://flathub.org/repo/appstream/x86_64/icons/128x128/net.sf.VICE.png

I tried to work around this issue and updated application's launchable desktop file and its icon to have the same name. 

> net.sf.VICE.C64.desktop
> net.sf.VICE.C64.png

The changes were published to Flathub and I can see that the new icon is there after I updated my local installation.

> ls /var/lib/flatpak/app/net.sf.VICE/x86_64/stable/27e717575f7e36815937446ff1a401ada48a29bbf71161bb804ba724d94ed012/files/share/app-info/icons/flatpak/128x128
 > net.sf.VICE.C64.png

Flathub however still returns 404 where referencing:

> https://flathub.org/repo/appstream/x86_64/icons/128x128/net.sf.VICE.C64.png

Full thread on this is in 

> https://github.com/flathub/net.sf.VICE/issues/10

**Comment by AsciiWolf** [comment]
VICE seems to be missing in GNOME Software as well.

**Comment by barthalion** [comment]
I'll be looking at it this week.

**Comment by digitalstreamio** [comment]
@barthalion Just to recap, currently appdata.xml has the following launchable entry:

>  <launchable type="desktop-id">net.sf.VICE.C64.desktop</launchable>

Flathub in search results correctly points to "net.sf.VICE.C64.png", however that file is missing from flathub repositiory.

Missing URL:
https://flathub.org/repo/appstream/x86_64/icons/128x128/net.sf.VICE.C64.png

Interestingly enough, another icon used by some other entrypoints is there.

Present:
https://flathub.org/repo/appstream/x86_64/icons/128x128/net.sf.VICE.png

**Comment by digitalstreamio** [comment]
@barthalion a quick ping, any chance we get can you to take a look at it this week? thx

**Comment by digitalstreamio** [comment]
@barthalion Hi, do you have any suggestions on what else we can do to troubleshoot this issue? Thanks

**Comment by bilelmoussaoui** [comment]
Is this still an issue? Upstream one seems to be closed.

**Comment by AsciiWolf** [comment]
The issue seems to be fixed.
