### ISSUE TITLE
[Request] Budgie themes?

### ISSUE THREAD

**Issue by camdenorrb** [flathub/flathub#886]
I really want to use Flatpak more, but I find that the lack of theming on Ubuntu Budgie is quite a turn off. Is there anyway y'all can add themes such as "Pocillo-dark" for the sake of my eyes? <3

**Comment by TingPing** [comment]
This isn't a place to make requests, but you can look at existing themes to package it: https://github.com/flathub?utf8=%E2%9C%93&q=gtk3theme&type=&language=
