### ISSUE TITLE
Automatically open issues when new version of a runtime is available

### ISSUE THREAD

**Issue by eszlari** [flathub/flathub#887]
I think it would useful, if an issue for every app would be opened automatically, when a new version of the runtime that the app uses is available. (Maybe a bot could be set up for this.)

This could help speed up the transition to newer runtimes (https://github.com/flathub/flathub/issues/667).

**Comment by jurf** [comment]
Would be also useful for raising other quality standards, e.g. AppData, HTTPS usage in sources, basic manifest formatting or project structure (some apps are a complete mess)…

**Comment by bbhtt** [comment]
This is https://github.com/flathub-infra/flatpak-external-data-checker/issues/161
