### ISSUE TITLE
Bad parsing of appdata.xml file

### ISSUE THREAD

**Issue by somas95** [flathub/flathub#901]
I've been trying a _lot_ of variations of my current appdata.xml file on the beta branch of uberwriter, but in every one of my attempts some tags are stripped off, mainly:
- OARS information
- Releases information
- URLs (in the current version those are not there, I removed them in case they were the issue, as they are optional)
- Mail address

Appstream-util validated every one of my attempts, but after compiling with the build bot, the appstream file in `var/lib/flatpak/app/de.wolfvollprecht.UberWriter/current/active/files/share/app-info/xmls` is incomplete.

I don't know what to try next. The current appdata file (https://github.com/flathub/de.wolfvollprecht.UberWriter/blob/beta/de.wolfvollprecht.UberWriter.appdata.xml) is a very stripped down one and still has issues. It would be very useful to know if there are some undocumented validations, or at least to have some debug info about the parsing of that file

---

Some variations I tried:
- different tags order
- component type `desktop` and `desktop-application`
- remove `translation` tag
- remove URLs tags
- remove descriptions and maybe problematic html tags in the `releases` tag
and others that I won't describe here (they are in the commit history anyway)

Any insight on this would be very helpful

**Comment by scx** [comment]
The `launchable` tag is missing, so it is unable to get data (`Icon`, `Categories` and probably `Keywords`) from the desktop file.
https://github.com/flathub/flathub/wiki/AppData-Guidelines#Launchable
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-launchable

Just put there something like this and you should be fine:
```
  <launchable type="desktop-id">de.wolfvollprecht.UberWriter.desktop</launchable>
```

Moreover, there is no need to specify `categories` in the AppData file if they are already present it in the desktop file.
https://github.com/UberWriter/uberwriter/blob/v2.1.5-beta1/de.wolfvollprecht.UberWriter.desktop#L4
The same applies to `icon` and probably `keywords`, although I'm not completely sure about the latter.

**Comment by somas95** [comment]
Yup, I know. That's how I had it before (see https://github.com/flathub/de.wolfvollprecht.UberWriter/commit/402f05c7c35b686459745d70b7857587fc162abe) and it didn't work. I stripped down a lot of tags to try to isolate the issue without success

**Comment by somas95** [comment]
I re-added those tags and removed the categories one (https://github.com/flathub/de.wolfvollprecht.UberWriter/blob/12a5dc9225c28cfc080907aaa9adcbd48d8fc404/de.wolfvollprecht.UberWriter.appdata.xml) and we have the same issue. 

Here is the output:
https://gist.github.com/somas95/5b65a4cc19130655c30c0e7fb36ded57

**Comment by TingPing** [comment]
URLs being lost is probably because of an old appstream package.

**Comment by TingPing** [comment]
Or perhaps this is relevant still: https://github.com/flatpak/flatpak/commit/5db64fe3426485e964e9ebe6e3be7964cedf19ce

**Comment by scx** [comment]
@TingPing 

> URLs being lost is probably because of an old appstream package.

Even `appstream-util` _0.7.8_ (Apr 20, 2018) from RHEL 7.6 (`libappstream-glib-0.7.8-2.el7.x86_64.rpm`) supports these URLs. The only problematic one is `contact`, but this AppData file doesn't contain it.

See also:
https://git.centos.org/summary/rpms!libappstream-glib.git
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-url

**Comment by somas95** [comment]
I don't think this is a caching issue, as I started using the beta channel not so long ago and it didn't work from the beggining
My appstream-glib version is 0.7.15-1
Btw, I update the file by hand and the validate it with appstream-util, but that shouldn't be a problem

**Comment by somas95** [comment]
> URLs being lost is probably because of an old appstream package.

Also, if they were just the URLs, I'd push the new release, but one thing that is missing too is the number version, and I'd like to have that fixed before pushing to the main channel

**Comment by somas95** [comment]
Hi, @nedrichards, do you know how can I test the appstream metadata file without triggering a whole compilation each time? It's a waste of resources, and pretty slow. I still don't know if this issue is a bug on my side or on flathub's, and it's pretty blocking

**Comment by somas95** [comment]
I think I got the error. Sorry for the inconveniences

**Comment by TingPing** [comment]
> I think I got the error. Sorry for the inconveniences

What was it for future readers?

**Comment by somas95** [comment]
Well, I was installing the appdata file 
https://github.com/flathub/de.wolfvollprecht.UberWriter/blob/a930b969b0675f3f6fb8c0d7d33c8af32278abc0/de.wolfvollprecht.UberWriter.json#L88
wich was the one hosted on the flathub repo, the one referenced in this issue, and the one wich I was modifying all the time
but after that I was installing the upstream one:
https://github.com/flathub/de.wolfvollprecht.UberWriter/blob/a930b969b0675f3f6fb8c0d7d33c8af32278abc0/de.wolfvollprecht.UberWriter.json#L108

wich wasn't up to date at all. They were so similar that I didn't realize this :/

Now I only rely in the uppstream one
