### ISSUE TITLE
flatpakrefs' Url= value has no trailing slash

### ISSUE THREAD

**Issue by mwleeds** [flathub/flathub#905]
For some reason the VSCode flatpakref file [here](https://flathub.org/repo/appstream/com.visualstudio.code.oss.flatpakref) has `Url=https://dl.flathub.org/repo` rather than `Url=https://dl.flathub.org/repo/` which means that you end up with separate `flathub` and `flathub-1` remotes when you install it to an installation that doesn't already have a flathub remote (the latter being added for the runtime).

I can't find where the typo is either in https://github.com/flathub/com.visualstudio.code.oss or https://github.com/flathub/linux-store-backend

**Comment by amtlib-dot-dll** [comment]
The build recipe is a general one, and the `.flatpakref` file is automatically generated.

**Comment by mwleeds** [comment]
I checked a few other flatpakrefs and they also don't have a trailing slash.

**Comment by mwleeds** [comment]
Ah, I guess it's the `repo_manager_main_base_url` setting here: https://github.com/flathub/ansible-playbook/blob/46133145d0844c6e7734e0c7808882a336ba597c/host_vars/hub.flathub.org
