### ISSUE TITLE
Error loading desktop file: Failed to find icon: Failed to find icon org.linux_hardware.hw-probe

### ISSUE THREAD

**Issue by linuxhw** [flathub/flathub#907]
The rebuild of the Flathub package [org.linux_hardware.hw-probe](https://github.com/flathub/org.linux_hardware.hw-probe) has failed (https://flathub.org/builds/#/builders/39/builds/148):

    Error loading desktop file: Failed to find icon: Failed to find icon org.linux_hardware.hw-probe
    Error: ERROR: appstream-compose failed: Child process exited with code 1

Previous build was successfully done several months ago.

Have you changed the build system?

Found similar issue https://github.com/flatpak/flatpak-builder/issues/228, but in my case there is no any files installed to `/app/usr`.

Thank you.

**Comment by TingPing** [comment]
At a glance your data files do seem fine so its probably a regression in some tooling.

**Comment by linuxhw** [comment]
Looks like this was my fault. I've missed a `smartd.service` file installed by `smartmontools` subpackage to `/app/usr`...

Lost 3 hours for debugging this again. Vote on https://github.com/hughsie/appstream-glib/issues/271#issuecomment-439396160.

Thanks.
