### ISSUE TITLE
Automated test builds of submitted apps

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/flathub#91]
Could the Buildbot be configured to automatically build manifests submitted via pull requests? People could iterate more quickly and there'd be less manual work involved.

**Comment by TingPing** [comment]
See also: flathub/buildbot-config#14

**Comment by nedrichards** [comment]
It's not automated, but admins can now `bot, build` a PR which is a lot less hassle.

**Comment by eszlari** [comment]
I think this issue can be closed.
