### ISSUE TITLE
org.kde.Sdk.Debug incomplete

### ISSUE THREAD

**Issue by eszlari** [flathub/flathub#915]
@aleixpol
```
flatpak install --user flathub org.kde.Sdk.Debug//5.12
flatpak run -d --command=sh org.kde.Sdk//5.12
find /usr -name '*Qt*.debug'
```
...gives 0 results.

**Comment by Erick555** [comment]
Perhaps you should report it on kde bug tracker.

**Comment by aleixpol** [comment]
Correct, debug information was removed because there were quite some problems on some 32bit systems, maybe it could be enabled for the rest.

You can report the bugs to the runtime here: https://bugs.kde.org/enter_bug.cgi?product=Qt%2FKDE%20Flatpak%20Runtime

**Comment by eszlari** [comment]
https://bugs.kde.org/show_bug.cgi?id=406448
