### ISSUE TITLE
Why field 'xa.redirect-url' in summary file?

### ISSUE THREAD

**Issue by myml** [flathub/flathub#916]
I use `ostree -v summary` command to see it.
![image](https://user-images.githubusercontent.com/13045857/54728972-c0601280-4bbb-11e9-8c59-affdc2aed54a.png)
Causing trouble for the **Reverse Proxy**

**Comment by barthalion** [comment]
It's used to redirect to the new address. If you are caching Flathub somehow, you should use it instead.
