### ISSUE TITLE
Dowloading flatpak bundle version by one click

### ISSUE THREAD

**Issue by mahmutelmas06** [flathub/flathub#921]
As you know many of users are not experts to use terminal to make an app as flatpak bundle.
i suggest you to provide a link to download bundle version of an app instead of .flatpakref file.

by the way we can:
Download the app to use in offline computer
Share the app with friends over email or whatsapp or etc.
Keep the app in personal archive. Even its older versions (which some times older is better)
This makes app sharing and keeping easier and make flatpak more populer (look at apks of android or exes of windows)

This is a consept image.
![Ekran görüntüsü_2019-03-27_18-07-09](https://user-images.githubusercontent.com/11191763/55088741-51a01f00-50bd-11e9-8be7-0cfd11c35ad2.png)

**Comment by TingPing** [comment]
Bundles are bad and users shouldn't interact with them really. For keeping app backups `flatpak` can copy them to a usb drive and EndlessOS has a version of GNOME-Software that exposes this with one click. A website cannot expose such a feature though.

**Comment by mahmutelmas06** [comment]
Why bundles are bad? And website doesnt have to bundle, pre-bundled version could be uploaded optional by developer.

**Comment by TingPing** [comment]
Some downsides:

- Bundles have to be generated on the server, they aren't free
- Bundles do not contain all dependencies required
- Bundles are not smart about update sizes, you have to download the entire thing

Using `flatpak create-usb` or `gnome-software` to make what is effectively a portable repo can avoid those issues.

**Comment by mahmutelmas06** [comment]
- Bundles could be made on computer and upload to  website or an online script could do that

- Doesnt snap packages or appimages contain all depencies? why not flatpak

- Doesnt bundles contain also flatpakref infornation to update an app? i mean install only from flatpak bundle but than use rest of as flatpakref.

**Comment by TingPing** [comment]
> Bundles could be made on computer and upload to website

No they can't. All data must come from a trusted source. 

> or an online script could do that

It still has to be created and hosted taking up resources.

> Doesnt snap packages or appimages contain all depencies? why not flatpak

Because we are better and have shared runtimes and extensions.

> Doesnt bundles contain also flatpakref infornation to update an app?

Yes it can.

**Comment by linux-player9** [comment]
So I was wondering, how can we create a flatpak from a flatpakref to install the flatpak on offline PC ?

**Comment by bilelmoussaoui** [comment]
@linux-player9 https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-create-usb

**Comment by razzeee** [comment]
I don't see a sensible way to do this - so I don't think we'll change the website.. I'll close this here, since this is an website issue anyway.
