### ISSUE TITLE
redistributing of 3rd party apps from flathub

### ISSUE THREAD

**Issue by damianatorrpm** [flathub/flathub#955]
I have the following question:
As there are a number of proprietary apps on flathub (and the license field does not have a link to the actual license of the package) I understand that implicitly one can for example bundle that app back to a file and/or mirror/ provide for download that as it is freely re-distributable because it is on flathub?

**Comment by aiamuzz** [comment]
> As there are a number of proprietary apps on flathub

which one's ?

Intelli J paid apps ?
I haven't used them ... but i guess they'll anyways require a licence at the end of their trial period ... making it useless after the trial period ... i guess these apps are allowed to be used for the first 30 days ... not violating anything ...

**Comment by damianatorrpm** [comment]
I mean it as a general rule. For example if I want to mirror flathub.
Does having them on flathub allow re-distribution?

I mean Skype, Visual Code, the newly added games by com.endlessnetwork etc etc

**Comment by TingPing** [comment]
Those applications are not actually *distributed* by Flathub. Flatpak has a feature called `extra-data` that downloads binaries on the users machine at installation time.

**Comment by damianatorrpm** [comment]
Ok, I understand.
