### ISSUE TITLE
install multple packages?

### ISSUE THREAD

**Issue by damianatorrpm** [flathub/flathub#958]
Is it possible to install multiple flatpack applications?
flatpak install flathub org.gnome.*
does not do that.

**Comment by bilelmoussaoui** [comment]
That's more of an issue of Flatpak itself than Flathub. Please ensure it's not reported first, here's the repository link https://github.com/flatpak/flatpak/issues

**Comment by damianatorrpm** [comment]
I dont find it there using the keywords I came up with, it should be reported there instead and closed here?
