### ISSUE TITLE
org.audacityteam.Audacity does not launch

### ISSUE THREAD

**Issue by dsboger** [flathub/flathub#96]
The specific repo does not have an Issues tab, so I'm reporting here.

When I try to `flatpak run org.audacityteam.Audacity`, I get

```
audacity: error while loading shared libraries: libFLAC++.so.6: cannot open shared object file: No such file or directory
```

Thanks for your efforts!

**Comment by alexlarsson** [comment]
Ah, libFLAC++.so is in the sdk, but not the platform, will fix it.

**Comment by joergister** [comment]
Had this issue too, but the new build fixed it. 
This problem seems to be kinda solved.

Thanks a lot
