### ISSUE TITLE
[Question] About safety of sandbox featrue of flatpak for Wine applications

### ISSUE THREAD

**Issue by Nokia808** [flathub/flathub#960]
Hi. I'm asked this question in Phoenicis but they reffer me to ask this for flathub - see:
https://github.com/PhoenicisOrg/phoenicis/issues/1920#issuecomment-483294689

The question is the following:
does sandbox feature of flatpak is enough to protect against possible virus run or other dangerous program ? Is this sandbox feature of flathub is equal to that od Firejail ?

**Comment by TingPing** [comment]
The permissions for that package: https://github.com/PhoenicisOrg/phoenicis/blob/master/phoenicis-dist/src/flatpak/org.phoenicis.playonlinux.yml#L30

(Or just run `flatpak info --show-permissions org.phoenicis.playonlinux`)

So it has some big sandbox holes like x11.

**Comment by plata** [comment]
@TingPing as you can see in the linked issue, @Nokia808 is now challenging us to "fix this risks & block all holes in your sandbox". Of course, we would like to be as secure as possible. However, I do not see how we could get rid of something like X11 or network. Any proposal what could be improved?

**Comment by TingPing** [comment]
>  However, I do not see how we could get rid of something like X11 or network. Any proposal what could be improved?

I don't think there is anything further you can do.

**Comment by Nokia808** [comment]
@TingPing 
@plata 

So, it is proved now that flatpak sandbox is NEVER superior to Firejail sandbox, but, in fact, inferior to Firejail.

**Comment by barthalion** [comment]
You're generally free to restrict any permissions you feel bad about. We can't make the applications non-functional by default as then someone else will report an issue saying "open holes so the app does what it should". The current status is the best we can do given X11 is still around or applications don't use portals. Not much more to discuss here.

**Comment by Kreyren** [comment]
Flatpak is fairly secure and that's good enough. == Shit and insecure

Fix the issue if there is any, escaping sandbox to live system is **NEVER ACCEPTABLE!!!** might as well call it working directories at that point

**Comment by Kreyren** [comment]
@TingPing
> I don't think there is anything further you can do.

Assuming this beeing caused by X11 packages present in phoenicis (or from what i understand) what are the options

**Comment by TingPing** [comment]
This conversation clearly went downhill. Ill just leave it at yes X11 is unsandboxed with Flatpak.
