### ISSUE TITLE
Publishing process took too long

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flathub/flathub#962]
The "Unpublished builds" section have 3 builds left there for 2 days. The builds were successful but we cannot use them.

**Comment by barthalion** [comment]
There was a problem with disk space, but flat-manager complains about it despite the fact the partition has been expanded. I'm building flat-manager with https://github.com/flatpak/flat-manager/pull/13 to see if it changes anything.

**Comment by barthalion** [comment]
Multiple `UPDATE` statements later… we're almost there, only LibreOffice and mkvtoolnix are left. I'll close it, sorry for the trouble.

@alexlarsson, we had to modify flat-manager code to ignore return code of `ostree checkout ... screenshots`, otherwise Tools extension of vscode was failing with this error:

```
InternalError: Command "ostree" "--repo=/srv/repo/builds/2315" "checkout" "--user-mode" "--bareuseronly-dirs" "--union" "screenshots/x86_64" "/srv/repo/stable/screenshots" exited unsuccesfully: error: Refspec 'screenshots/x86_64' not found
```

Something to take a look when you're back.

**Comment by amtlib-dot-dll** [comment]
I pushed another revision of my recipe https://flathub.org/builds/#/builders/32/builds/2616 because I found that the main application `com.visualstudio.code.oss` is not updated in the remote repo, neither in the version description at https://flathub.org/apps/details/com.visualstudio.code.oss; only the extension `com.visualstudio.code.oss.Tools` is updated. However, the build I triggered today is still stalled in the publishing process. Is it the same problem? Thanks!

**Comment by amtlib-dot-dll** [comment]
Published, thanks!

**Comment by barthalion** [comment]
Default is 3 hours between build and publish, for both testing (for app maintainer) and performance reasons (as we can queue more apps to publish at once). You can change it though: https://github.com/flathub/flathub/wiki/App-Maintenance#automatic-publishing-delay
