### ISSUE TITLE
Please add de.create3000.Titania

### ISSUE THREAD

**Issue by create3000** [flathub/flathub#978]
I have pulled Titania-flathub against new-pr as described in the Wiki, but GitHub says 'Nothing to compare'. So I made a pull request against the branch de.create3000.Titania, but I could not leave a comment. Is the Wiki wrong? Should I made a pull request against the master?

**Comment by barthalion** [comment]
Instructions here are describing how to submit new application. If you want to contribute to existing repo, just follow regular GitHub workflow.
