### ISSUE TITLE
Two GNOME chess entries on flathub.org

### ISSUE THREAD

**Issue by Zlopez** [flathub/flathub#981]
I noticed that the GNOME chess has two entries on flathub.org. See https://flathub.org/apps/search/gnome%20chess

Recently I marked old repo as EOL and created a new repo, because there were incompatible changes in flatpak name on upstream, but now you can find both old and new on flathub.org

**Comment by TingPing** [comment]
cc @jgarciao

**Comment by jgarciao** [comment]
Currently EOL apps are not automatically deleted from the website. They require manual removing from the database and I think only @alexlarsson has access to it. 

Alex, can you pleas run this in production?
```
delete  from app_category where app_id = (select app_id from app where flatpak_app_id = 'org.gnome.chess')
delete  from app_release where app_id = (select app_id from app where flatpak_app_id = 'org.gnome.chess)
delete  from screenshot where app_id = (select app_id from app where flatpak_app_id = 'org.gnome.chess')
delete  from app where flatpak_app_id = 'org.gnome.chess'
commit
```

**Comment by AsciiWolf** [comment]
Still the same issue.

**Comment by AsciiWolf** [comment]
Any news?

**Comment by jgarciao** [comment]
I think Alex will be on holidays until the end of July. 

@barthalion , do you have access to the website database?

**Comment by Zlopez** [comment]
I created https://github.com/flathub/org.gnome.Chess/pull/11 that could help with this issue.

@jgarciao Could you check it. I'm not sure if this change to branch that is considered EOL will do anything.

**Comment by AsciiWolf** [comment]
I just noticed that the old GNOME Chess entry is in the [Editor's Choice Games](https://flathub.org/apps/collection/editors-choice-games) list.

@alexlarsson @barthalion Would it be possible to replace it with the [new one](https://flathub.org/apps/details/org.gnome.Chess)?

**Comment by jgarciao** [comment]
> I just noticed that the old GNOME Chess entry is in the [Editor's Choice Games](https://flathub.org/apps/collection/editors-choice-games) list.

I just replaced the app in [this commit](https://github.com/flathub/linux-store-frontend/commit/e116b52ad636005824314f08cffc9e48026f2604). It will be updated online in the next deploy. Thanks for spotting it!

> @alexlarsson @barthalion Would it be possible to replace it with the [new one](https://flathub.org/apps/details/org.gnome.Chess)?

I'm taking a look about how to make this automatic in the web backend.

**Comment by jgarciao** [comment]
@alexlarsson  just removed the app manually. Sorry it took so long

**Comment by AsciiWolf** [comment]
It seems that the old Chess entry is still displayed on the [Editor's Choice Games](https://flathub.org/apps/collection/editors-choice-games) page.
