### ISSUE TITLE
Qt apps ignore system font scaling

### ISSUE THREAD

**Issue by ilmaisin** [flathub/flathub#982]
I have noticed that many Qt apps available via Flathub somehow ignore the system font scaling setting. It apparently has been publicly known [for a quite while](https://www.reddit.com/r/kde/comments/910awy/how_to_make_kde_flatpak_apps_respect_font_settings/), but still seems to be unaddressed.

Does anyone have any idea what causes this? Is it maybe an issue of the KDE runtime or one of the packages available here? If it matters, AppImage [is having a similar issue](https://github.com/appimage/appimagekit/issues/125).

I feel that this is important because it is necessary for not only users of high DPI displays, but also for those who have visual impairments. Thus, there are strong ethical obligations and in some locales even legal obligations to take it seriously.

If it is a KDE runtime issue and the KDE project is somehow unable or unwilling to address this problem, maybe the runtime could be forked, or another, non-KDE Qt runtime be created?

**Comment by eszlari** [comment]
I guess you're not on KDE? Qt doesn't respect GNOME's scaling setting:
https://bugreports.qt.io/browse/QTBUG-65424

**Comment by TingPing** [comment]
Eitherway this doesn't belong reported against Flathub. Qt (or the GNOME Platform) are the better places.

**Comment by neggative9** [comment]
i don't know about Qt thing but i have noticed that packages that have been downloaded with dl.flathub.org but when downloading same package with fedora's repo for flatpak, the scalling works with no issue. is that only my side issue or what? btw im using fedora 38 with gnome 44

 please help, softwares are extremely ususable for me with that font size.
