### ISSUE TITLE
Jami flatpak is broken

### ISSUE THREAD

**Issue by Charadon** [flathub/flathub#986]
I have no idea if this is the place to post this. But the jami flatpak is broken, giving this error when trying to install it:
```
(flatpak install:25871): flatpak-WARNING **: Non-prefixed filename cx.ring.Ring.service in app net.jami.Jami, removing.
error: No such file or directory
```
The ring flatpak "kinda" works, but not really since its an older client and no longer works with the current ring network. Hopefully this can be easily resolved.

**Comment by TingPing** [comment]
https://github.com/flathub/net.jami.Jami/issues/5 was the correct place.
