### ISSUE TITLE
Node.js dependency doesn't build (at least for some apps using Freedesktop 18.08)

### ISSUE THREAD

**Issue by x80486** [flathub/flathub#987]
As I was trying to update `io.github.liberodark.OpenDrive` to version `0.2.2`, I ran into a consistent error while building `Node.js` dependency:

```shell
...
creating config.gypi
creating config.mk
'import sitecustomize' failed; use -v for traceback
gyp: Call to 'python -c "import sys; print sys.byteorder"' returned exit status 0 while in /run/build/nodejs/deps/v8/src/v8.gyp. while loading dependencies of /run/build/nodejs/node.gyp while trying to load /run/build/nodejs/node.gyp
Error running GYP
Error: module nodejs: Child process exited with code 1
```

The [same](https://github.com/flathub/io.github.liberodark.OpenDrive/pull/2/) [happens](https://github.com/flathub/io.github.liberodark.OpenDrive/pull/1/) if I use the Flathub's infrastructure.

Moreover I went ahead and tried some other applications that also uses `Node.js`, like: `com.endlessm.HatchPreviewer` and `com.tutanota.Tutanota`...and I had the [same result(s)](https://8n1.org/15124/142a), so I hope I'm not alone on this one :sweat_smile:

What I've researched is that it could be related with Python, but again, I'm not sure how would that impact `flatpak-builder` (if so). Anyway, I'm just dropping this one here so anyone more knowledgeable can shed some light :sunglasses:

**Comment by ghisvail** [comment]
Same here whilst working on an initial release of `io.balena.etcher`.

I wonder whether Python is available in Freedesktop 18.08 actually?

**Comment by barthalion** [comment]
Python 2 used to be available in SDK, but not in Platform. Maybe it got removed in the meantime.

**Comment by x80486** [comment]
Since the issue is `node-gyp` –and it [requires](https://github.com/nodejs/node-gyp/) Python `2.7.x`-, what would be the right approach to provide that dependency as part of the build process?

**Comment by barthalion** [comment]
It's available as part of [shared-modules](https://github.com/flathub/shared-modules/tree/master/python2.7), but given you need it only for build, you can copy-paste it and replace `cleanup` content with `["*"]`.

**Comment by ghisvail** [comment]
> you can copy-paste it and replace cleanup content with ["*"].

I get the following:
```
configure: WARNING: unrecognized options: --enable-loadable-sqlite-extensions
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for python2.7... python2.7
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... linux2
checking EXTRAPLATDIR... 
checking for --without-gcc... no
checking for --with-icc... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/run/build/python-2.7':
configure: error: C compiler cannot create executables
```

**Comment by ghisvail** [comment]
I tested it for `com.jgraph.drawio.desktop` and it worked on the Flathub builders. Not sure why it fails on my local build.

**Comment by ghisvail** [comment]
> Not sure why it fails on my local build.

A typo in my cflags / cxxflags.

**Comment by x80486** [comment]
I'll close this one since adding the `python2.7` shared module makes it possible to build Node.js, at least, versions `8.x`.
