### ISSUE TITLE
Slack 2.8.0 fails to actually connect

### ISSUE THREAD

**Issue by maxxkrakoa** [flathub/flathub#99]
I ran `flatpak update` and got upgraded to Slack 2.8.0 but after that Slack seems to start up correctly (and the self tests run fine) but it never actually connects to any channels.

I tried downloading the Slack 2.8.0 RPM from slack.com and that works fine.

Here's the output of `flatpak info com.slack.Slack`. Is there anything else I can provide?

```
Ref: app/com.slack.Slack/x86_64/stable
ID: com.slack.Slack
Arch: x86_64
Branch: stable
Origin: flathub
Commit: 8e4efab61b024fc912da787f5cca6ed4448201e668b185e8d5bc1d0dcdc53966
Location: /var/lib/flatpak/app/com.slack.Slack/x86_64/stable/8e4efab61b024fc912da787f5cca6ed4448201e668b185e8d5bc1d0dcdc53966
Installed size: 17,0 MB
Runtime: org.freedesktop.Platform/x86_64/1.6
```

**Comment by cryptomaniac512** [comment]
I have the same problem

**Comment by Barthalion** [comment]
@nedrichards, can you take a look?

Same. In the meantime downgraded it following steps from Flatpak wiki and removing `~/.var/app/com.slack.Slack`:
```
ostree --repo=.local/share/flatpak/repo pull --depth=250 --commit-metadata-only flathub app/com.slack.Slack/x86_64/stable
flatpak --user update --commit=e1107b0524cad9767dbc47497790d42706656073f517f840d4cf1b2c92559e0a com.slack.Slack
```

**Comment by nedrichards** [comment]
Yep, will look.

**Comment by nedrichards** [comment]
Oh bloody hell. Let's revert to 2.7.1 for now - I've verified that continues to work and doesn't need you to delete your cache.

(I've also worked out the really stupid QA fail that led to me 'testing' a version of Slack from a completely different repo when suggesting that PR, apologies)

**Comment by Barthalion** [comment]
Pushed the revert. It should hit the repos really soon.

**Comment by nedrichards** [comment]
I've fixed this here https://github.com/flathub/com.slack.Slack/commit/d3fbcc970b5103c7d1e1a6fba667260c85954c19 it turns out to have added a new dependency on libxkbfile. (thanks to the team over at https://github.com/jessfraz/dockerfiles/pull/299 for providing a helpful search result when I eventually found the correct error message)

**Comment by TingPing** [comment]
@nedrichards Atom also depends on libxkbfile so if this is a new electron dep we should just add it to the baseapp.

**Comment by nedrichards** [comment]
@TingPing yes - if it's general it should certainly go into the baseapp. I wanted to get this fixed first and then do some electron focused research.

**Comment by nedrichards** [comment]
It's not currently in the [Electron Linux CI list of deps](https://github.com/electron/electron/blob/master/script/cibuild), but it does look common in actual apps.

**Comment by TingPing** [comment]
libsecret is also somewhat common it seems.
