### ISSUE TITLE
Mix Fedora runtimes with Flathub applications?

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flathub/flathub#992]
Now we can use Fedora runtimes and applications as well:

```sh
flatpak remote-add fedora oci+https://registry.fedoraproject.org
flatpak install fedora org.mozilla.Firefox
```

The base runtime `org.fedoraproject.Sdk` have a different set of softwares installed inside. Is it possible for Flathub recipe maintainers like me to specify a runtime from that remote?

**Comment by barthalion** [comment]
We don't host Fedora runtime on Flathub so no.

**Comment by amtlib-dot-dll** [comment]
Well Fedora's approach is very attractive as every one of their recipes is just a list of Fedora RPM packages, rather than a lengthy file specifying where to download the source and what to pass to the compiler. Thus the maintenance of RPM packages and Flatpak packages can be unified, just like those Snap packages in Ubuntu.

**Comment by barthalion** [comment]
It's even less likely that we will support that.

**Comment by nedrichards** [comment]
Yes. Fedora exists and has chosen a different method of delivering value to users using Flatpak. That's great news! If users and developers find it more useful then it'll be successful and the mission of improving the state of applications on Linux and the services available for developers will be advanced!
