### ISSUE TITLE
Appstream validation fails with missing translation tag

### ISSUE THREAD

**Issue by digitalstreamio** [flathub/flathub#997]
While trying to post a new build for net.sf.VICE, the validation for appstream data is now failing due to missing translation tag. This worked as recently as yesterday. 

Based on freedesktop spec, it seems that translation tag is optional.

https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

> The <translation/> tag is an optional tag which can be added to specify the translation domain used for this software component. It may be used by the AppStream distro metadata generator to determine the translation status of the respective software. 

However, build bot is failing with the following error:

```
flatpak run org.freedesktop.appstream-glib validate builddir/*/share/appdata/net.sf.VICE.appdata.xml
 in dir /srv/buildbot/worker/build-x86_64-3/build (timeout 1200 secs)
 watching logfiles {}
 argv: b'flatpak run org.freedesktop.appstream-glib validate builddir/*/share/appdata/net.sf.VICE.appdata.xml'
 using PTY: False
builddir/files/share/appdata/net.sf.VICE.appdata.xml: FAILED:
• tag-missing           : <translation> not specified
Validation of files failed
program finished with exit code 1
elapsedTime=0.294268
```

Any suggestions on how to resolve this? 

THanks

**Comment by digitalstreamio** [comment]
Here is a link to the pull request with the build bot errors.

https://github.com/flathub/net.sf.VICE/pull/14

**Comment by barthalion** [comment]
If application doesn't support translations, `<translation/>` should be enough. We're considering making this check a warning but as it's out there only since yesterday, it's too early to decide.
